### PR TITLE
Fix hold action for picture element card in Android app

### LINKED ISSUE #23305: Hold action not working for image element in picture-elements card in android app
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When using a image element inside a picture-elements card, the hold_action (long press) is not working. After the long press, we see some visual response in the bottom left of the screen but the action does not trigger.

I've tested that this doesn't happen using the browser version of lovelace so It seems it is only manifesting in with the android app. I opened a [issue there](https://github.com/home-assistant/android/issues/4908) but was forwarded here.

I include a reproducible snippet (might have to change the entity to something that exists) 

```
type: picture-elements
image: https://demo.home-assistant.io/stub_config/floorplan.png
elements:
  - type: image
    image: >-
      https://images.rawpixel.com/image_png_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDI0LTAxL2Rlc2lnbndpdGhtZTA5X2FfbGlnaHRfYnVsYl9pbl90aGVfc3R5bGVfb2ZfaHlwZXItcmVhbGlzdGljX2lsbF9iMTE2ZmI3Zi1kYzc4LTQ1MDEtYWQwNC05NDY4YjVlNzU2ZjAucG5n.png
    style:
      top: 50%
      left: 50%
      width: 15%
    tap_action:
      action: toggle
    entity: light.bathroom_office

```

take notice of the flashing on the bottom left corner

https://github.com/user-attachments/assets/43d7a3fd-e617-4bbe-847f-c73162cb7ce1

### Describe the behavior you expected

When long pressing the icon, the defined hold_action triggers (as it happens in non-android envs)

https://github.com/user-attachments/assets/5e8e6189-a9e7-4f68-93a4-c3a33c730537

### Steps to reproduce the issue

1. Create a widget as defined in the above snippet
2. Change the entity to something that exists in your system
3. Long press the bulb image

### What version of Home Assistant Core has the issue?

core-2024.12.3

### What was the last working version of Home Assistant Core?

core-2024.11.X

### In which browser are you experiencing the issue with?

Android 14 (One UI 6.1)

### Which operating system are you using to run this browser?

Android 14 (One UI 6.1)

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Fix hold action for hui-image in Android app (tested with OnePlus 8 phone). 

This fix the issue for these elements : 
- picture element
- picture-glance card
- picture-entity card

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/23305
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/hui-picture-entity-card.ts [hunk 1]
```diff
@@ -202,8 +211,14 @@ class HuiPictureEntityCard extends LitElement implements LovelaceCard {
       box-sizing: border-box;
     }
 
+    .image-container {
+      height: 100%;
+      cursor: pointer;
+    }
+
     hui-image {
       cursor: pointer;
```
Comment (MindFreeze) [inline src/panels/lovelace/cards/hui-picture-entity-card.ts]: This cursor: pointer; is redundant now
```suggestion
```

File: src/panels/lovelace/cards/hui-picture-entity-card.ts [hunk 2]
```diff
@@ -163,20 +163,8 @@ class HuiPictureEntityCard extends LitElement implements LovelaceCard {
...
-            ? this._config.entity
-            : this._config.camera_image}
-          .cameraView=${this._config.camera_view}
-          .entity=${this._config.entity}
-          .aspectRatio=${ignoreAspectRatio
-            ? undefined
-            : this._config.aspect_ratio}
-          .fitMode=${this._config.fit_mode}
+        <div
+          class="image-container"
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-picture-entity-card.ts]: Shouldnt this have a clickable class too based on if there is an action?

**Review by bramkragten — APPROVED** [review]

**Comment by woempiej** [comment]
Hi,

On which OS platform version is this issue fixed?
Android or HA update?

I am on:
```
Installatiemethode Home Assistant OS
Core 2025.9.3
Supervisor 2025.09.0
Operating System 16.2
Frontend 20250903.5
```
```
app version 2025.8.7-full
```

Using a simple card config;
```
type: horizontal-stack
cards:
  - type: picture
    image: /local/tmp/Radio538.png
    tap_action:
      action: perform-action
      data:
        media_content_id: speel radio 538 op woonkeuken
        media_content_type: TUNEIN
      target:
        entity_id: media_player.woonkamer
      perform_action: media_player.play_media
    hold_action:
      action: perform-action
      data:
        media_content_id: speel radio 538 op overal
        media_content_type: TUNEIN
      target:
        entity_id: media_player.woonkamer
      perform_action: media_player.play_media
  - type: picture
    tap_action:
      action: perform-action
...
````
On my Nothong 2a phone (Android 15) it does not work.

Thanks
