### PR TITLE
Localize trigger state in automation editor

### LINKED ISSUE #18357: Missing in lokalise existing automation - "When something changes"
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing in lokalise

Screen can be found in web version Settings/Automations and Scenes/ in existing automatisation

Snag_WhenSomethingChanges

### Describe the behavior you expected

Add to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.5

### What was the last working version of Home Assistant Core?

not relevant

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change
Localize trigger state in the automation editor. 

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #18357 
- This PR is related to issue or discussion: #13820
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/data/automation_i18n.ts [hunk 1]
```diff
@@ -199,126 +199,91 @@ const tryDescribeTrigger = (
...
 
-    if (entities.length === 0) {
-      // no entity_id or empty array
-      entities.push("something");
+    let entityArray: string[] = [];
+    if (!Array.isArray(trigger.entity_id)) {
+      entityArray = [trigger.entity_id];
+    } else {
+      entityArray = trigger.entity_id;
+    }
```
Comment (bramkragten) [inline src/data/automation_i18n.ts:223]:
```suggestion
    const entityArray = ensureArray(trigger.entity_id);
```

File: src/data/automation_i18n.ts [hunk 2]
```diff
@@ -199,126 +199,91 @@ const tryDescribeTrigger = (
...
+    for (const entity of entityArray.values()) {
```
Comment (bramkragten) [inline src/data/automation_i18n.ts:224]:
```suggestion
    for (const entity of entityArray) {
```

File: src/data/automation_i18n.ts [hunk 3]
```diff
@@ -199,126 +199,91 @@ const tryDescribeTrigger = (
...
+      if (states[entity]) {
+        entities.push(computeStateName(states[entity]) || entity);
+      }
     }
 
-    base += ` ${entities} changes`;
+    const stateObj = hass.states[trigger.entity_id[0]];
```
Comment (bramkragten) [inline src/data/automation_i18n.ts:230]: `trigger.entity_id` can be a string, so then this would only ge the first char of the entity id.
```suggestion
    const stateObj = hass.states[entityArray[0]];
```

File: src/data/automation_i18n.ts [hunk 4]
```diff
@@ -199,126 +199,91 @@ const tryDescribeTrigger = (
...
-        if (from.length !== 0) {
-          const fromString = formatListWithOrs(hass.locale, from);
-          base += ` from ${fromString}`;
+          fromChoice = "null";
         }
+      } else if (!Array.isArray(trigger.from)) {
+        fromArray = [trigger.from];
       } else {
-        base += ` from ${
+        fromArray = trigger.from;
```
Comment (bramkragten) [inline src/data/automation_i18n.ts:243]:
```suggestion
        fromArray = ensureArray(trigger.from);
```

File: src/data/automation_i18n.ts [hunk 5]
```diff
@@ -199,126 +199,91 @@ const tryDescribeTrigger = (
...
-              : hass.formatEntityState(stateObj, state)
-          );
-        }
-        if (from.length !== 0) {
-          const fromString = formatListWithOrs(hass.locale, from);
-          base += ` from ${fromString}`;
+          fromChoice = "null";
         }
+      } else if (!Array.isArray(trigger.from)) {
+        fromArray = [trigger.from];
```
Comment (bramkragten) [inline src/data/automation_i18n.ts:241]:
```suggestion
```

File: src/data/automation_i18n.ts [hunk 6]
```diff
@@ -199,126 +199,91 @@ const tryDescribeTrigger = (
...
       } else {
-        base += ` from ${
+        fromArray = trigger.from;
+      }
+      const from: string[] = [];
+      for (const state of fromArray.values()) {
```
Comment (bramkragten) [inline src/data/automation_i18n.ts:246]:
```suggestion
      for (const state of fromArray) {
```

**Review by bramkragten — APPROVED** [review]
