### PR TITLE
Fix climate hvac action color

### LINKED ISSUE #14608: State color of thermostat entity based on wrong attribute.
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

New color scheme for thermostat is... not usable..... Icon of thermostat is now red not when the state is 'heating'. It's now red when the 'operation' is set to 'heat'. So for my setup it is always red.......
In previous versions of HA colour of thermostat icon was based on state (heat/idle). It was very useful. Now it's based on 'operation' mode.
Thermostat in my setup is set to 'heat' operation for about 99.9% of time (I think it's common for everyone). So the icon is RED all the time, no matter if the termostat is in heat or idle state.
image

### Describe the behavior you expected

Thermostat icon color should be based on heat/idle state.

### Steps to reproduce the issue

1. Set the termostat to 'Operation' = 'Heat
2. Set temperature setpoint belos current themperature sensor (state = idle)
3. Icon of the termostat will be RED......

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.0 Supervisor 2022.11.2 Operating System 9.3 Frontend 20221207.0 - latest

### What was the last working version of Home Assistant Core?

Home Assistant 2022.11.0

### In which browser are you experiencing the issue with?

Google Chrome Wersja 108.0.5359.94

### Which operating system are you using to run this browser?

Windows 10 Pro. Compilation 19044.1645

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

If the entity support `hvac_action`, use action instead of state for icon color.
I also added the case in gallery.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #14608
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/common/entity/color/climate_color.ts [hunk 1]
```diff
@@ -1,3 +1,13 @@
+import { HvacAction } from "../../../data/climate";
+
+export const CLIMATE_HVAC_ACTION_COLORS: Record<HvacAction, string> = {
+  cooling: "var(--rgb-state-climate-cool-color)",
+  drying: "var(--rgb-state-climate-dry-color)",
+  heating: "var(--rgb-state-climate-heat-color)",
+  idle: "var(--rgb-state-climate-idle-color)",
+  off: "var(--rgb-state-climate-off-color)",
+};
```
Comment (spacegaier) [inline src/common/entity/color/climate_color.ts:9]: What happens to the existing CSS vars such as `--state-climate-auto-color`?

And looking at the current vars there are more, so I would assume we also need them here now?

Comment (piitaya) [reply src/common/entity/color/climate_color.ts:9]: Action can only have this values.
State is managed with `stateColor`.

Comment (piitaya) [reply src/common/entity/color/climate_color.ts:9]: I think all these variables can be removed.

Comment (piitaya) [reply src/common/entity/color/climate_color.ts:9]: Thermostat card uses the `--state-climate-{state}-color` variables. And probably other custom card. We can keep it for now.

**Review by bramkragten — APPROVED** [review]

File: src/common/entity/color/climate_color.ts (hunk 1 above)
Comment (SN0WTR00PER) [reply src/common/entity/color/climate_color.ts:9]: Hi @piitaya   If I update HA straight to 2022.12.5, do the thermostat state colour will work as before?

Comment (SN0WTR00PER) [reply src/common/entity/color/climate_color.ts:9]: I have my answer...  Yes, everything back to normal... 😊

Thx
