### PR TITLE
Fix default strategy when energy is not configured

### LINKED ISSUE #9821: default overview lovelace dashboard is empty
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

after latest docker (homeassistant/raspberrypi3-homeassistant) upgrade the defaul lovelace overview page contains only 1 card with following text:

Error loading the view strategy:

[object Object]

ha

other custom dashboards are fine

### Describe the behavior you expected

i should see all discovered entities

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2021.9.0.dev20210815

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

i have alredy tryed ti remove all lovelace* file from .storage with no changes in behavior
tryed also to set:

lovelace:
  mode: storage 

and 

lovelace:
  mode: yaml

with no success.

### PR DESCRIPTION
**Pull request by ludeeus**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9821
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/strategies/original-states-strategy.ts [hunk 1]
```diff
@@ -53,7 +48,13 @@ export class OriginalStatesStrategy {
         hass.loadBackendTranslation("title"),
       ]);
 
-    const energyPrefs = energyPromise ? await energyPromise : undefined;
```
Comment (balloob) [inline src/panels/lovelace/strategies/original-states-strategy.ts:56]: We can just catch this in a try…catch here. No need to only start the promise after all the other info has fetched.

**Review by balloob — APPROVED** [review]
