### PR TITLE
Use fixed layout for automation sidebar to have scrollbar on the side

### LINKED ISSUE #26739: Selecting fullscreen in Automation Sidebar YAML Editor Expands Behind Sidebar
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

This relates to the current dev branch.

In the new floating sidebar editor pane for Automations, when the code editor is made fullscreen, the editor disappears behind the sidebar.

If I make the window larger than 1296px wide, the issue goes away - the editor window is now in front of the sidebar.

  - Collapsed:
    
    Image

  - Fullscreen (< 1296px):
    
     Image

   - Fullscreen (>= 1296px)
   
     
Image

 

### Describe the behavior you expected

When pressing the fullscreen button, the code editor shouldn't be obscured by the main HA sidebar.

### Steps to reproduce the issue

1. Go to http://homeassistant.local:8123/config/automation/edit/new
2. Add Condition -> Other Conditions -> Template
3. Press the full-screen button
...

### What version of Home Assistant Core has the issue?

2025.10.0.dev0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

MS Edge Version 139.0.3405.119, Firefox 142.0

### Which operating system are you using to run this browser?

Windows 10 22H2

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
Current frontend `dev` branch (6a372a1)
```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Use fixed layout for automation sidebar to have scrollbar on the side. I also removed the breakpoint where the flow is behind the sidebar because it looks like a bug and the drag handle is hidden. 

Needs https://github.com/home-assistant/frontend/pull/26744 to be merged to adjust the different margin.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/26739
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/automation/action/ha-automation-action.ts [hunk 1]
```diff
@@ -409,14 +409,7 @@ export default class HaAutomationAction extends LitElement {
...
 
-  static styles = [
-    automationRowsStyles,
-    css`
-      :host([root]) .rows {
-        padding-right: 8px;
-      }
-    `,
-  ];
+  static styles = [automationRowsStyles];
```
Comment (wendevlin) [inline src/panels/config/automation/action/ha-automation-action.ts]:
```suggestion
  static styles = automationRowsStyles;
```

File: src/panels/config/automation/condition/ha-automation-condition.ts [hunk 2]
```diff
@@ -428,14 +428,7 @@ export default class HaAutomationCondition extends LitElement {
...
 
-  static styles = [
-    automationRowsStyles,
-    css`
-      :host([root]) .rows {
-        padding-right: 8px;
-      }
-    `,
-  ];
+  static styles = [automationRowsStyles];
```
Comment (wendevlin) [inline src/panels/config/automation/condition/ha-automation-condition.ts]:
```suggestion
  static styles = automationRowsStyles;
```

File: src/panels/config/automation/manual-automation-editor.ts [hunk 3]
```diff
@@ -260,40 +256,39 @@ export class HaManualAutomationEditor extends LitElement {
     return html`
       <div
         class=${classMap({
-          "split-view": true,
-          "sidebar-hidden": !this._sidebarConfig,
+          "has-sidebar": !!this._sidebarConfig && !this.narrow,
```
Comment (wendevlin) [inline src/panels/config/automation/manual-automation-editor.ts]:
```suggestion
          "has-sidebar": this._sidebarConfig && !this.narrow,
```

I think `!!` is not needed here because it's AND

File: src/panels/config/automation/trigger/ha-automation-trigger.ts [hunk 4]
```diff
@@ -368,14 +368,7 @@ export default class HaAutomationTrigger extends LitElement {
...
 
-  static styles = [
-    automationRowsStyles,
-    css`
-      :host([root]) .rows {
-        padding-right: 8px;
-      }
-    `,
-  ];
+  static styles = [automationRowsStyles];
```
Comment (wendevlin) [inline src/panels/config/automation/trigger/ha-automation-trigger.ts]:
```suggestion
  static styles = automationRowsStyles;
```

File: src/panels/config/script/manual-script-editor.ts [hunk 5]
```diff
@@ -199,40 +198,41 @@ export class HaManualScriptEditor extends LitElement {
     return html`
       <div
         class=${classMap({
-          "split-view": true,
-          "sidebar-hidden": !this._sidebarConfig,
+          "has-sidebar": !!this._sidebarConfig && !this.narrow,
```
Comment (wendevlin) [inline src/panels/config/script/manual-script-editor.ts]:
```suggestion
          "has-sidebar": this._sidebarConfig && !this.narrow,
```

**Review by wendevlin — CHANGES_REQUESTED** [review]

**Review by wendevlin — APPROVED** [review]
