### PR TITLE
Fix second load in firefox and localize init

### LINKED ISSUE #8504: Supervisor and Addon Tabs only load once in Firefox
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I hate to report those FF issues. :neutral_face:
Opening a new Browser window with HA and going to the Supervisor Tab loads only once.
If i go to Dev Tools and back to Supervisor the page doesn't load, needs CTRL-F5.
Same behavior for Addons (Terminal, VSC) in the sidebar. 

### Describe the behavior you expected

No need to reload the page with CTRL-F5

### Steps to reproduce the issue

1. Open HA in Firefox, go to Supervisor
2. Go to Dev Tools
3. Go back to Supervisor, it doesn't load
...

### What version of Home Assistant Core has the issue?

core-2021.3.0b5

### What was the last working version of Home Assistant Core?

core-2021.2.4

### In which browser are you experiencing the issue with?

Firefox 86.0

### Which operating system are you using to run this browser?

Ubuntu 18.03

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
NS_ERROR_NOT_INITIALIZED entrypoint.a5b7c2a9.js:34775
NS_ERROR_NOT_INITIALIZED entrypoint.a5b7c2a9.js:34775
```
for every click that doesn't load.

### PR DESCRIPTION
**Pull request by ludeeus**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #8504
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: hassio/src/supervisor-base-element.ts [hunk 1]
```diff
@@ -71,6 +70,16 @@ export class SupervisorBaseElement extends urlSyncMixin(
 
   protected updated(changedProperties: PropertyValues) {
     super.updated(changedProperties);
+    if (changedProperties.has("hass")) {
+      const oldHass = changedProperties.get("hass") as HomeAssistant;
```
Comment (bramkragten) [inline hassio/src/supervisor-base-element.ts:74]:
```suggestion
      const oldHass = changedProperties.get("hass") as HomeAssistant | undefined;
```

**Review by bramkragten — APPROVED** [review]

File: hassio/src/supervisor-base-element.ts [hunk 2]
```diff
@@ -86,6 +88,21 @@ export class SupervisorBaseElement extends urlSyncMixin(
         this._initializeLocalize();
       }
     }
+
+    if (changedProperties.has("_collections")) {
+      if (this._collections) {
+        for (const collection of Object.keys(this._collections)) {
+          if (!Object.keys(this._unsubs).includes(collection)) {
```
Comment (bramkragten) [inline hassio/src/supervisor-base-element.ts:95]: move `Object.keys(this._unsubs)` to line 93

**Review by bramkragten — APPROVED** [review]
