### PR TITLE
Change default shortcut tip in Quick Search to mod+k, add tip to settings

### LINKED ISSUE #29245: Opening the keyboard shortcuts dialog from Quick search should close Quick search
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I open Quick Search and click on the shortcuts tip on the bottom, Quick search should be dismissed.
https://github.com/user-attachments/assets/7328eb19-c3e9-46ea-b418-74dfec0d4906

### Describe the behavior you expected

Quick search should be dismissed.

### Steps to reproduce the issue

1. Open Quick Search via keyboard shortcut or pressing the "magnify" icon
2. Click the "keyboard shortcuts" from the footer of the Quick Search

### What version of Home Assistant Core has the issue?

2026.2.0b0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### LINKED ISSUE #29246: Change default shortcut tip in Quick Search
### Description

When opening Quick Search clicking on the "magnify" icon on desktop we see this tip:

Image

Please change it to the one below:
"Press keyboard shortcut CTRL / ⌘ + K on any page to open quick search."

**Note: Would be good to just show the appropriate function key based on the user OS, just like in the Keyboard Shortcuts dialog.**

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by timmo001**
## Proposed change

- Updates shortcut hint in quick bar to the mod+k for quick search.
- Also adds the same tip to the settings tips.
- Replace `hint` with a `showHint` param instead. Nothing special is done with hints, so consolidation made sense here
- Closes quick search when keyboard shortcut button is clicked. Addresses #29245

`''` in the translation is to allow the `{modifier}` to work. Visually, this shows as single quotes

<details>
<summary>Screenshots</summary>

dashboards
image

settings
image

</details>

 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: closes #29246  closes #29245
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/dashboard/ha-config-dashboard.ts [hunk 1]
```diff
@@ -364,17 +373,7 @@ class HaConfigDashboard extends SubscribeMixin(LitElement) {
...
-        >${this.hass.localize("ui.tips.keyboard_shortcut")}</a
-      >`,
-    };
-
-    showQuickBar(this, {
-      hint: this.hass.enableShortcuts
-        ? this.hass.localize("ui.dialogs.quick-bar.key_c_tip", params)
-        : undefined,
-    });
+    showQuickBar(this, { showHint: true });
```
Comment (MindFreeze) [inline src/panels/config/dashboard/ha-config-dashboard.ts:376]:
```suggestion
    showQuickBar(this, { showHint: this.hass.enableShortcuts });
```
Shouldn't it be like this?

Comment (timmo001) [reply src/panels/config/dashboard/ha-config-dashboard.ts:376]: Originally it always showed. I think this is the intention, so the link highlights the shortcuts, which then notes how to enable them

@marcinbauer85 is this correct?

File: src/dialogs/quick-bar/ha-quick-bar.ts [hunk 2]
```diff
@@ -231,9 +232,16 @@ export class QuickBar extends LitElement {
               clearable
             ></ha-picker-combo-box>`
           : nothing}
-        ${this._hint
+        ${this._showHint
           ? html`<ha-tip slot="footer" .hass=${this.hass}
-              >${this._hint}</ha-tip
+              >${this.hass.localize("ui.tips.key_shortcut_quick_search", {
+                keyboard_shortcut: html`<a
+                  href="#"
```
Comment (bramkragten) [inline src/dialogs/quick-bar/ha-quick-bar.ts]: Use a button instead of an anchor link, and use this styling:

https://github.com/home-assistant/frontend/blob/dev/src/resources/styles.ts#L4-L14

**Review by bramkragten — APPROVED** [review]

File: src/panels/config/dashboard/ha-config-dashboard.ts (hunk 1 above)
Comment (marcinbauer-ohf) [reply src/panels/config/dashboard/ha-config-dashboard.ts:376]: If somebody disables shortcuts, it's for a very specific reason: conflict with 3rd party plugins, a11y software etc. Although the goal of shortcuts is to provide additional a11y. But in the event they really need to be disabled, that user doesn't need the tips at all, so @MindFreeze suggestion is correct.
