### PR TITLE
Localize automation logbook text

### LINKED ISSUE #19464: Missing in lokalise - automation text
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Found missing words in lokalise (in attached screenshot).

1705572495649_AutomationText

1705572495640_AutomationText2

1705572495620_AutomationRule

### Describe the behavior you expected

Please add it to lokalise.
Thank you in advance.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2024.1.3

### What was the last working version of Home Assistant Core?

not relevant

### PR DESCRIPTION
**Pull request by silamon**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/19464
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/trace/hat-logbook-note.ts [hunk 1]
```diff
@@ -1,14 +1,20 @@
...
   render() {
-    return html`
-      Not all shown logbook entries might be related to this ${this.domain}.
-    `;
+    return this.hass.localize(
+      "ui.panel.config.automation.trace.messages.not_all_entries_are_related_note",
+      {
+        domain: this.domain,
+      }
+    );
```
Comment (piitaya) [inline src/components/trace/hat-logbook-note.ts:17]: What's the possible domains? Only script and automations, right? Should we add 2 translations for that because using a domain variable will not work in others language than english.

Comment (silamon) [reply src/components/trace/hat-logbook-note.ts:17]: automations and scripts indeed, according to the typing. 
I've added a fetch for the domain. Let me know if it is preferred to have 2 separate translations.

Comment (piitaya) [reply src/components/trace/hat-logbook-note.ts]: If we only have 2 domains, I would prefer 2 translations. In french for example, we will have "**ce** script" and "**cette** automatisation".

**Review by piitaya — APPROVED** [review]
Thank you @silamon!
