### PR TITLE
static styles, decorators and width fix

### LINKED ISSUE #2724: Shopping-List card cuts off text
**Home Assistant release with the issue:**
0.87.0

```
System Health
arch | x86_64
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.6.6
timezone | America/New_York
version | 0.87.0
virtualenv | false

Lovelace
mode | storage
resources | 3
views | 9
```

**Last working Home Assistant release (if known):**

This did work previously, but I don't recall which version this issue started with. Something between 0.85 and now is my best guess.

**Browser and Operating System:**

Google Chrome (Version 71.0.3578.98 (Official Build) (64-bit))

**Description of problem:**

The shopping list, when displayed as a card in lovelace, cuts off the list text too early.
As shown [in this screenshot](https://i.imgur.com/YIMJetY.png) (lower items blurred for privacy, but same issue as the first 2 items).
The screenshot includes the surrounding cards, and you can see that there's plenty of room left in the card to display more text (only ~50% is being used).

This issue is intermittent, sometimes if I open the UI it will load correctly, and if I refresh the page it jumps back to only displaying in half of the card.

When I open the shopping list as a frame (from the left-hand-side menu) it shows up fine.

**Additional information:**

### PR DESCRIPTION
**Pull request by iantrich**
Not sure how the width got messed up, perhaps changes to ha-card?

fixes https://github.com/home-assistant/home-assistant-polymer/issues/2724

### CODE REVIEW

**Review by balloob — APPROVED** [review]
You're back 💯

File: src/panels/lovelace/cards/hui-shopping-list-card.ts [hunk 1]
```diff
@@ -192,6 +190,9 @@ class HuiShoppingListCard extends LitElement implements LovelaceCard {
           padding: 9px 15px 11px 15px;
           cursor: pointer;
         }
+        paper-item-body {
+          width: 75%;
```
Comment (balloob) [inline src/panels/lovelace/cards/hui-shopping-list-card.ts]: This is putting a 75% on all items, both add and list items. Why not use the full width?

Comment (iantrich) [reply src/panels/lovelace/cards/hui-shopping-list-card.ts]: Looked weird imo
