### PR TITLE
Convert thermostat to round-slider

### LINKED ISSUE #2756: Thermostat: Card not applying themes
Hi there

My Setup includes a Generic Thermostat, build around MQTT and some fronend themes.
Unfortunately the style of the Thermostat Card in Lovelace is not applied.

If I add the "theme:" property, nothing changes.
ha: latest
Platform: Ubuntu 18.04 native in VM

See:
image
"Accent Color" (orange) is applied, but configured as red. If I switch to "default", the default theme works (blue)
Chrome: latest

Could it be that we mix up different properties per card?

Cheers, Lukas

### LINKED ISSUE #3622: Remove jQuery sliders in favor of round-slider
- [ ] hui-thermostat-card
- [x] hui-light-card

https://www.npmjs.com/package/@thomasloven/round-slider/v/0.2.0

### LINKED ISSUE #3711: Thermostat card doesn't look good when it is small (unneeded padding)
When You add multiple thermostats stacked they have padding and font size problems:
Open official demo (https://demo.home-assistant.io/#/lovelace/0)
add this card:
```
type: vertical-stack
cards:
  - cards:
      - type: thermostat
        entity: climate.upstairs
      - type: thermostat
        entity: climate.upstairs
    type: horizontal-stack
  - cards:
      - type: thermostat
        entity: climate.upstairs
      - type: thermostat
        entity: climate.upstairs
    type: horizontal-stack
```

You will get this look:
image

As you can see icons are cut on the bottom.

ha-card is getting the correct class (`small`), but there is unneeded padding-top for `modes` class. After removing this padding card look much better:
image

My proposition is to remove padding when ha-card has `small` class (or add padding when ha-card has `large` class).

Also please consider changing font size based on container size, as suggested here: https://github.com/home-assistant/ui-schema/issues/221#issuecomment-530862458, because right now `title` and `current-mode` are getting too large.

### LINKED ISSUE #3889: Thermostat Card showing <null> when ECO mode is on
Hello,
the thermostat card shows `null` string (instead of `blank`) when my Nest Learning Thermostat is in ECO mode (because home away).

This climate entity `state` is **eco** and state attributes are:
```
current_temperature: 18
min_temp: 9
max_temp: 32
temperature: null
operation_mode: eco
operation_list: off,heat,eco
away_mode: on
friendly_name: Family Room
supported_features: 1153
```

The `null` string is displayed above the state label:
mobile_vertical

### LINKED ISSUE #3891: Thermostat Card Clipping (Font scaling)
Hello,

I just wanted to point out that the thermostat card does not play well in a horizontal stack with any small browser window (really mobile is where I see it the most).  Just feel like at least it should not clip out the bottom buttons but should still be able to be stacked horizontally.  Doesn't make sense for this to be one of the exceptions.

https://imgur.com/a/nPr24VH

### PR DESCRIPTION
**Pull request by iantrich**
Closes https://github.com/home-assistant/home-assistant-polymer/issues/3622
Closes https://github.com/home-assistant/home-assistant-polymer/issues/2756
Closes https://github.com/home-assistant/home-assistant-polymer/issues/3711
Closes https://github.com/home-assistant/home-assistant-polymer/issues/3889
Closes https://github.com/home-assistant/home-assistant-polymer/issues/3891

### CODE REVIEW

**Comment by iantrich** [comment]
- [ ] Scale slider? Currently still using the based on client width for the radius calculation. I don't really like that approach. I think a minimum size of ~200px could be achieved without scaling. After that I don't think anything really looks good and not sure we should try to scale further than that. We have small (less than 390px) scaling vs regular scaling and I'm not sure if that is necessary or not. Light card does not do this.
- [ ] Handles are not properly themed yet

**Comment by thomasloven** [comment]
That's correct. I made them to look more like paper-slider than our old round sliders.

Re: card size, there should really be a minimum supported card width. 200-300 px is definitely reasonable.

**Comment by iantrich** [comment]
@thomasloven thanks. Yeah, I like the handles as is.

**Comment by iantrich** [comment]
I think the card looks good down to ~300px
Please check the preview and try to break the theming and/or find improvements.

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 1]
```diff
@@ -114,13 +88,14 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
     return html`
-      ${this.renderStyle()}
       <ha-card
         class="${classMap({
           [mode]: true,
-          large: this._broadCard!,
-          small: !this._broadCard,
+          large: this.clientWidth > 450,
+          medium: this.clientWidth <= 450 && this.clientWidth >= 350,
+          small: this.clientWidth < 350,
```
Comment (iantrich) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: Is there much benefit in only having this in the initial loading of the card?

Comment (thomasloven) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: IIRC all cards are rebuilt on large layout changes, i.e. when the screen size changes enough to adjust the columns. But you may want to rescale even on smaller changes, perhaps?

**Comment by thomasloven** [comment]
ezgif com-resize (1)

I think it could do with some more work 😉

**Comment by iantrich** [comment]
🤔 looks fine on refresh though, right?

**Comment by thomasloven** [comment]
Only the final state. There's still the problem with the name overlapping the circle at some sizes, and the circle being taller than the card in the single column.

**Comment by iantrich** [comment]
why did I sign up for something involving so much CSS... 🤦‍♂

**Comment by iantrich** [comment]
@thomasloven I only get that behavior when doing what you were doing; moving the window size. On a refresh of the page it looks fine to me. Do I need to fire an iron-resize or something? This is the kind of stuff I'm quite ignorant on, still.

**Comment by thomasloven** [comment]
I get the problem even after refresh if the window is between about 540 and 600 px wide.
image

File: src/panels/lovelace/cards/hui-thermostat-card.ts (hunk 1 above)
Comment (bramkragten) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: This is now checked at every render, but not necessarily on a resize of the window because we only render on a change of properties. clientWidth is not a property.

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 2]
```diff
@@ -147,7 +160,22 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
+                  ? this.formatTemp(
+                      [
+                        stateObj.attributes.target_temp_low,
+                        stateObj.attributes.target_temp_high,
+                      ],
+                      false
+                    )
+                  : Number.isFinite(Number(stateObj.attributes.temperature))
+                  ? stateObj.attributes.temperature
+                  : null}
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]:
```suggestion
                  : ""}
```

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 3]
```diff
@@ -238,94 +235,30 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
-        ? stateObj.attributes.temperature
-        : null;
-      uiValue = sliderValue !== null ? String(sliderValue) : "";
-    }
-
-    return [sliderValue, uiValue, sliderType];
-  }
-
   private _updateSetTemp(value: string): void {
     this.shadowRoot!.querySelector("#set-temperature")!.innerHTML = value;
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: You should not update `#set-temperature` both in render and here.

**Review by bramkragten — COMMENTED** [review]
Nice! 👍

**Comment by bramkragten** [comment]
We should also remove jquery and roundslider from the deps, and remove the load scripts.

**Comment by iantrich** [comment]
We can do that in a separate PR

**Comment by iantrich** [comment]
Last commit helps with window resizing but still struggling with scaling at certain sizes

**Comment by Misiu** [comment]
I found a weird behavior: when You enter config mode and add this entry:

```
type: vertical-stack
cards:
  - cards:
      - entity: climate.upstairs
        type: thermostat
        name: Kuchnia
      - entity: climate.upstairs
        type: thermostat
        name: Sypialnia
    type: horizontal-stack
  - cards:
      - entity: climate.upstairs
        type: thermostat
        name: Pokój dzienny
      - entity: climate.upstairs
        type: thermostat
        name: Korytarz
    type: horizontal-stack
```

You get this view: 
ha1

But when You close edit view You suddenly get this:
ha2

The easiest way to reproduce this is to add two thermostats into horizontal-stack:
ha3

**Comment by iantrich** [comment]
I regret starting this... 😂

**Comment by Misiu** [comment]
@iantrich even with these small issues, You version works and looks great 👏
The first problem (resizing after exiting edit mode) isn't that important - I can always hit refresh (but unfortunately not on demo site).
The only issue (for me) is placing two thermostats in horizontal-stack, but I can live with it 🙂

**Comment by iantrich** [comment]
@Misiu it will get there, just a chore at this point 👎

**Comment by thomasloven** [comment]
The light card doesn't scale... might be worth considering.

**Comment by Misiu** [comment]
@iantrich this is the ideal time to fix both issues 😉 Maybe another size variant? Extra small? For clientWidth that is smaller than 150? This would fix display issues when cards are used in horizontal group.

**Comment by iantrich** [comment]
@Misiu no. that can be its own PR

**Comment by bramkragten** [comment]
Isn’t it easier now we just have a custom element and not a jquery element that set a hard size on init? Can’t we give it a percentage size now?

File: package.json [hunk 4]
```diff
@@ -83,7 +83,6 @@
     "hls.js": "^0.12.4",
     "home-assistant-js-websocket": "^4.4.0",
     "intl-messageformat": "^2.2.0",
-    "jquery": "^3.4.0",
```
Comment (thomasloven) [inline package.json]: 🎉

**Comment by thomasloven** [comment]
The resizing seems to work almost perfectly now, but there's still an issue with long friendly names.
Skärmavbild 2019-10-11 kl  21 01 09

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 5]
```diff
@@ -246,86 +251,75 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
+      ? this.formatTemp(
+          [
+            stateObj.attributes.target_temp_low,
+            stateObj.attributes.target_temp_high,
+          ],
+          false
+        )
+      : Number.isFinite(Number(stateObj.attributes.temperature))
+      ? stateObj.attributes.temperature
+      : "";
```
Comment (thomasloven) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: This is a mess. Let the compiler do this, and make it readable instad. You'll have to maintain this some day.

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 6]
```diff
@@ -334,23 +328,23 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
       stateObj.attributes.target_temp_low &&
       stateObj.attributes.target_temp_high
     ) {
-      if (e.handle.index === 1) {
+      if (e.detail.low) {
```
Comment (thomasloven) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: The logic do determine which value to set is not the same as in `_dragEvent`. Why?

Comment (thomasloven) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: Results are the same, but the way to get there is not.

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 7]
```diff
@@ -246,86 +251,75 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
 
-    (this.shadowRoot!.querySelector(
-      "#thermostat"
-    ) as HTMLElement)!.style.height = radius * 2 + "px";
-
-    const loaded = await loadRoundslider();
-
-    this._roundSliderStyle = loaded.roundSliderStyle;
-    this._jQuery = loaded.jQuery;
+    await this.updateComplete;
```
Comment (thomasloven) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: What triggers the update we're awaiting?

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 8]
```diff
@@ -246,86 +251,75 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
+          ],
+          false
+        )
+      : Number.isFinite(Number(stateObj.attributes.temperature))
+      ? stateObj.attributes.temperature
+      : "";
   }
 
   private _updateSetTemp(value: string): void {
     this.shadowRoot!.querySelector("#set-temperature")!.innerHTML = value;
```
Comment (thomasloven) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: I agree with @bramkragten, but wouldn't it be better to move both this and the zero-padding from `formatTemp` into `render`?

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 9]
```diff
@@ -382,217 +376,212 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
     temps = temps.filter(Boolean);
+    let stringTemps = temps.map(String);
 
     // If we are sliding the slider, append 0 to the temperatures if we're
     // having a 0.5 step size, so that the text doesn't jump while sliding
     if (spaceStepSize) {
       const stepSize = this._stepSize;
-      temps = temps.map((val) =>
+      stringTemps = stringTemps.map((val) =>
         val.includes(".") || stepSize === 1 ? val : `${val}.0`
```
Comment (thomasloven) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: `val.toFixed(1)` ?

Comment (thomasloven) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: I suppose stepsize is unlikely to be less than 0.1 (or even 0.5).

Comment (thomasloven) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: But again, I think this would be better in `render`.

Comment (iantrich) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: what do you mean that it would be better in render? This is used in multiple places in the file.

File: src/panels/lovelace/cards/hui-thermostat-card.ts (hunk 8 above)
Comment (iantrich) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: this is called from numerous places and for different reasons, including inside the dragEvent. I don't think that makes sense to put in the render directly

File: src/panels/lovelace/cards/hui-thermostat-card.ts (hunk 7 above)
Comment (iantrich) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: https://lit-element.polymer-project.org/guide/lifecycle#updatecomplete

**Comment by iantrich** [comment]
> The resizing seems to work almost perfectly now, but there's still an issue with long friendly names.

What do you suggest? Make the radius larger? Wrap the name? Make the font smaller based on name length?

File: src/panels/lovelace/cards/hui-thermostat-card.ts (hunk 7 above)
Comment (thomasloven) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: Oh, sorry!
Github was folding the source, so I thought this was inside `firstUpdated`.

File: src/panels/lovelace/cards/hui-thermostat-card.ts (hunk 9 above)
Comment (thomasloven) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: I mean I think you could have a property for `setTemp` and making the render function do this processing:

Something like (simplified):

```js
${ Array.isarray(this.setTemp)
  ? html`${this.setTemp[0].toFixed(1)} - ${this.setTemp[1].toFixed(1)}`
  : html`${this.setTemp.toFixed(1)}
}
```

**Comment by thomasloven** [comment]
I'm afraid I don't have a good suggestion.
Put the name outside the ring, maybe? Like above?
I don't know...

**Comment by Misiu** [comment]
@iantrich can the font size be determined by the text length? If yes, then maybe this is the solution.
The name inside the ring looks really good and it should stay there, but that's just my opinion.

**Comment by iantrich** [comment]
@bramkragten any thoughts on handling long friendly names?

File: src/panels/lovelace/cards/hui-thermostat-card.ts (hunk 9 above)
Comment (iantrich) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: I get it! :tada: sorry for being dense. Yes, that makes a lot of sense. Thanks.

**Comment by iantrich** [comment]
Now if the name is greater than 10 characters, the title size is lowered from 23px to 18px. I think that's good for now and could possible be tweaked further in another PR.

**Comment by iantrich** [comment]
@bramkragten I think this is good to go now unless @thomasloven has anything to add. Thanks for both your help on this one.

**Comment by thomasloven** [comment]
> Now if the name is greater than 10 characters, the title size is lowered from 23px to 18px. I think that's good for now and could possible be tweaked further in another PR.

Did you perhaps forget to push that?

**Review by thomasloven — APPROVED** [review]

**Comment by iantrich** [comment]
> > Now if the name is greater than 10 characters, the title size is lowered from 23px to 18px. I think that's good for now and could possible be tweaked further in another PR.
> 
> Did you perhaps forget to push that?

I sure did, thanks!

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 10]
```diff
@@ -129,7 +125,45 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
+                  <round-slider
+                    .radius=${this._radius}
+                    .low=${stateObj.attributes.target_temp_low}
+                    .high=${stateObj.attributes.target_temp_high}
+                    .min=${stateObj.attributes.min_temp}
+                    .max=${stateObj.attributes.max_temp}
+                    .step=${this._stepSize}
+                    @value-changing=${this._dragEvent}
+                    @value-changed=${this._setTemperature}
+                    handleSize="10"
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: Can we make the handleSize the same as the light card? This feels to big, especially since they get even bigger on focus.

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 11]
```diff
@@ -204,38 +242,14 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
-      return stateObj.attributes.target_temp_step;
+  protected firstUpdated(): void {
+    this._updated = true;
+    if (this.isConnected && !this._loaded) {
+      this._initialLoad();
     }
-    return this.hass!.config.unit_system.temperature === UNIT_F ? 1 : 0.5;
   }
 
   private async _initialLoad(): Promise<void> {
```
[the remark this answers is not in the document]
Comment (iantrich) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: in other PRs, I've always been directed to handle things related to sizing in a function like this e.g. input-number row

[the remark this answers is not in the document]
Comment (bramkragten) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: yeah only for the clientWidth, (sucks though, should monitor resizes). But stateObject and the length of the title etc should not be in here. And is it necessary to await updateComplete? Why are we waiting?

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 12]
```diff
@@ -116,7 +115,8 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
           large: this._large!,
           medium: this._medium!,
           small: this._small!,
-          longName: this._longName!,
+          longName:
+            (this._config!.name || computeStateName(stateObj)).length > 10,
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: We are doing this twice now in 1 function, better to put it in a variable

**Comment by bramkragten** [comment]
Why is this? https://github.com/home-assistant/home-assistant-polymer/pull/3734/files/333568c622de79683ba54644db46ce5a2091d8ff..ff0706582e3ac1c4f5b836c9c346da152c18ab54#diff-aa72d1334cd817ce683ee67f3e2227adR254-R259

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 13]
```diff
@@ -129,7 +125,43 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
+                    .value=${stateObj.attributes.temperature !== null &&
+                    Number.isFinite(Number(stateObj.attributes.temperature))
+                      ? stateObj.attributes.temperature
+                      : stateObj.attributes.min_temp}
+                    .step=${this._stepSize}
+                    .min=${stateObj.attributes.min_temp}
+                    .max=${stateObj.attributes.max_temp}
+                    @value-changing=${this._dragEvent}
+                    @value-changed=${this._setTemperature}
+                  ></round-slider>
```
Comment (thomasloven) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: Actually, I think round-slider could handle this. If you give it both low, high and value, it will show one handle if low is undefined, and two otherwise.
May be a bit confusing, though...

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 14]
```diff
@@ -114,13 +104,19 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
     return html`
-      ${this.renderStyle()}
       <ha-card
         class="${classMap({
           [mode]: true,
-          large: this._broadCard!,
-          small: !this._broadCard,
+          large: this._large!,
+          medium: this._medium!,
+          small: this._small!,
```
Comment (thomasloven) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: Am I correct that those values are only calculated once, and only used here?
If so, can't the calculation be made here too?

Comment (thomasloven) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: Ok. I found the other place _initialLoad is called from.
But is *that* still necessary? Does it need to be called from both firstUpdated and connectedCallback?

Comment (bramkragten) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: We can only get the size when it is connected, and we don't know which will fire first, connected or updated.

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 15]
```diff
@@ -241,6 +241,11 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
     }
 
     this._setTemp = this._getSetTemp(this.hass!.states[this._config!.entity]);
+    this._longName =
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: I was more thinking of making `name` and const in render, as we now have to computeStateName and check if `config` has name twice (line 167). No need to make it a property.

File: src/panels/lovelace/cards/hui-thermostat-card.ts (hunk 14 above)
Comment (thomasloven) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: Ah yes.

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 16]
```diff
@@ -114,22 +103,69 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
     }
 
     const mode = stateObj.state in modeIcons ? stateObj.state : "unknown-mode";
+    const longName =
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]:
```suggestion
    const name = this._config!.name || computeStateName(this.hass!.states[this._config!.entity]);
```

**Review by bramkragten — APPROVED** [review]

**Comment by bramkragten** [comment]
> ...can this be done...? 🤣 I never want to look at this card again

I will assign all issues with this card to you :wink:
