### PR TITLE
Device page: sort related automations, scenes, scripts

### LINKED ISSUE #23539: Device info page - automations, scripts, scenes aren't sorted alphabetically
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On the device info page, there's cards for automations, scripts, scenes that the device is used in. This list isn't sorted alphabetically though, see below screenshot:

Screen Shot 2025-01-01 at 8 07 24 PM

On the more info dialog → related tab, these automations ARE correctly sorted alphabetically. This is how the device info page should behave too:

Screen Shot 2025-01-01 at 8 12 31 PM

### Describe the behavior you expected

Sort items alphabetically like the rest of the user interface

### Steps to reproduce the issue

1. View a device info page
2. View the cards where it says which automations/scripts/scenes the device is used in. They're not sorted alphabetically.

### What version of Home Assistant Core has the issue?

2025.1.0b5

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ildar170975**
## Proposed change

Before / after:

изображение

**Notes:**
1. Now the `ha-config-device-page` class has same `_toEntities()` (entity_ids -> objects) method as `ha-related-items`. Probably it should be made as a common function then.
2. I am not getting a need for `ha-tooltip` for related automations. Currently it is not present for scripts but is for automations & scenes.
3. There is also a difference in defining `href` for related entities between "automation & scenes" AND scripts. Looks like these blocks were written differently.
4. This old line causes a eslint error: "This comparison appears to be unintentional because the types 'string' and 'HassEntity' have no overlap":
```
(e) => e.entity_id === script
```
Trying to fix it.... Changed the comparison to `e.entity_id === script as any`.

Suggest to some Dev person (or to myself) to sort out these mentioned differences between blocks for related entities.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/23539
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by silamon** [comment]
#23470 is related.

File: src/panels/config/devices/ha-config-device-page.ts [hunk 1]
```diff
@@ -620,10 +634,10 @@ export class HaConfigDevicePage extends LitElement {
             ${this._related?.script?.length
               ? html`
                   <div class="items">
-                    ${this._related.script.map((script) => {
-                      const entityState = this.hass.states[script];
+                    ${this._toEntities(this._related.script).map((script) => {
+                      const entityState = script;
                       const entry = this._entityReg.find(
-                        (e) => e.entity_id === script
+                        (e) => e.entity_id === (script as any)
```
Comment (bramkragten) [inline src/panels/config/devices/ha-config-device-page.ts:640]: script is an `stateObj` right? So this should be?
```suggestion
                        (e) => e.entity_id === script.entity_id
```

File: src/panels/config/devices/ha-config-device-page.ts [hunk 2]
```diff
@@ -441,35 +453,37 @@ export class HaConfigDevicePage extends LitElement {
...
-                            .content=${this.hass.localize(
-                              "ui.panel.config.devices.cant_edit"
-                            )}
-                          >
-                            <a
-                              href=${ifDefined(
-                                entityState.attributes.id
-                                  ? `/config/automation/edit/${encodeURIComponent(entityState.attributes.id)}`
-                                  : undefined
+                    ${this._toEntities(this._related.automation).map(
```
Comment (bramkragten) [inline src/panels/config/devices/ha-config-device-page.ts:456]: We should wrap this in memoized, so we don't do the sorting and filtering on every render.

File: src/panels/config/devices/ha-config-device-page.ts (hunk 1 above)
Comment (ildar170975) [reply src/panels/config/devices/ha-config-device-page.ts]: My bad! Fixed.

File: src/panels/config/devices/ha-config-device-page.ts (hunk 2 above)
Comment (ildar170975) [reply src/panels/config/devices/ha-config-device-page.ts]: Refactored to memoize. Hope I did it right..
But the `entity` part is not included in the same memoize, it is in a different one (which was already present).

File: src/panels/config/devices/ha-config-device-page.ts [hunk 3]
```diff
@@ -161,26 +161,42 @@ export class HaConfigDevicePage extends LitElement {
     }
   );
 
+  private _getEntitiesSorted = (entities) =>
+    entities
+      .map((entity) => ({
+        ...entity,
+        stateName: this._computeEntityName(entity),
```
Comment (bramkragten) [inline src/panels/config/devices/ha-config-device-page.ts:168]: `_computeEntityName` takes a `EntityRegistryEntry`, you are passing state object to it. Please add proper typing so these things pop up automatically.

**Review by bramkragten — DISMISSED** [review]

File: src/panels/config/devices/ha-config-device-page.ts (hunk 3 above)
Comment (ildar170975) [reply src/panels/config/devices/ha-config-device-page.ts]: Changed the code, please review.

**Review by silamon — DISMISSED** [review]

File: src/panels/config/devices/ha-config-device-page.ts [hunk 4]
```diff
@@ -185,6 +185,27 @@ export class HaConfigDevicePage extends LitElement {
         )
   );
 
+  private _getEntitiesSorted = (entities) =>
```
Comment (silamon) [inline src/panels/config/devices/ha-config-device-page.ts]:
```suggestion
  private _getEntitiesSorted = (entities : HassEntity[]) =>
```

Comment (ildar170975) [reply src/panels/config/devices/ha-config-device-page.ts]: HassEntity should be imported, right?
Will check and test it when be near a PC, these days have no this luxury(

**Review by silamon — APPROVED** [review]
