### PR TITLE
Ensure ha-dialog uses correct <a> color

### LINKED ISSUE #7211: Unique ID docs link in more info dialog lacks styling (0.116b1)
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Small thing, the new link to docs for unique ID message lacks styling / css so it uses the browser default This is hard to see on the dark theme. 

image

## Steps to reproduce

Can reproduce in the [demo](https://demo.home-assistant.io/#/lovelace/0), open the more info and then hit the cog icon in top right.

## Environment

- Home Assistant release with the issue: 0.116.0b1
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Previously hyperlinks in a ha-dialog were not styled properly and therefore used the browsers default coloring (dark blue in my case). This e.g. occurred in the entity `persistent_notification.python_version` that appears if python version 3.7 is used.

Now, correctly the primary theme color is used, same as for all other links.

image

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by SeanPM5** [comment]
This fixes https://github.com/home-assistant/frontend/issues/7211

File: src/resources/styles.ts [hunk 1]
```diff
@@ -299,6 +299,10 @@ export const haStyleDialog = css`
     color: var(--primary-text-color);
   }
 
+  ha-dialog a {
```
Comment (bramkragten) [inline src/resources/styles.ts:302]:
```suggestion
  a {
```

**Review by bramkragten — APPROVED** [review]
