### PR TITLE
Ensure `conditional` rows getting `state_color` value

### LINKED ISSUE #10580: state_color not working for Switches inside Conditional in Entity Card
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In an Entity Card, the icons for Switch entities do not respond to the `state_color` option when they are placed in the `row:` section of a `type: conditional`. (For comparison, the icons for Light entities _do_ respond to `state_color` when inside a `type: conditional`.)

### Describe the behavior you expected

The icons of Switch entities inside a `type: conditional` should be coloured based on state.

### Steps to reproduce the issue

1. Create a Lovelace Entity Card with the same Switch both inside and outside a `type: conditional`
2. Turn on the switch

### What version of Home Assistant Core has the issue?

core-2021.11.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Firefox 78.15.0esr, Chromium 90.0.4430.212 (Developer Build)

### Which operating system are you using to run this browser?

Debian 11.1

### State of relevant entities

```txt
Entity: switch.foo
  state: on
```

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - type: conditional
    conditions: []
    row:
      entity: switch.foo
  - entity: switch.foo
  - type: conditional
    conditions: []
    row:
      entity: light.bar
  - entity: light.bar
title: Hello World!
show_header_toggle: false
state_color: true
# Note that the second icon for switch.foo (and both icons for light.bar) change colour with state, but the first icon for switch.foo does not
```

### Javascript errors shown in your browser console/inspector

```txt
None
```

### Additional information

image

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

The current behavior is somewhat inconsistent. The `state_color` property on card level affects all entities, except those that are in a conditional row. With this PR we now correctly forward the `state_color` setting from the card to the entity rows inside the conditional section.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #10580
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/special-rows/hui-conditional-row.ts [hunk 1]
```diff
@@ -12,7 +17,14 @@ class HuiConditionalRow extends HuiConditionalBase implements LovelaceRow {
       throw new Error("No row configured");
     }
 
-    this._element = createRowElement(config.row) as LovelaceRow;
+    this._element = createRowElement(
+      "state_color" in config && (config as EntityCardConfig).state_color
```
Comment (bramkragten) [inline src/panels/lovelace/special-rows/hui-conditional-row.ts:21]:
```suggestion
      config as EntityCardConfig).state_color
```

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
