### PR TITLE
Map Card: Fix Dark Mode Toggle

### LINKED ISSUE #5195: Map card - dark mode toggle issue
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

In the map card, it appears that the "Dark mode" toggle is on by default now, even though it's actually not. Map tiles are regular / white and when you switch to the code editor it won't have `dark_mode: true` in there.

So the toggle is in a wrong / misleading state by default. And if you did want dark mode, you'd now have to toggle it off first and then back on again. 

map

## Expected behavior

1. Enter Configure UI mode
2. Select Map card
3. Look at default toggle and the text I reported above

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by zsarnett**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #5195
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/editor/config-elements/hui-map-card-editor.ts [hunk 1]
```diff
@@ -113,7 +113,7 @@ export class HuiMapCardEditor extends LitElement implements LovelaceCardEditor {
           ></paper-input>
         </div>
         <ha-switch
-          .checked="${this._config!.dark_mode !== false}"
+          .checked="${this._config!.dark_mode}"
```
Comment (bramkragten) [inline src/panels/lovelace/editor/config-elements/hui-map-card-editor.ts]: Why not:
```suggestion
          .checked="${this._dark_mode}"
```

**Review by bramkragten — APPROVED** [review]
