### PR TITLE
Application credentials: small improvements

### LINKED ISSUE #21229: Application Credentials - data table display broken on mobile
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In Application Credentials, the data table rows appear empty on mobile / narrow width resolution.
IMG_1152

In this second screen shot when select mode is active, you can see there's four checkboxes to select them, but there's no text to read. This is after resetting column customization to default too, so I don't think it's that.

Also if you look at the top right there's a help tooltip/icon in a sorta weird place next to the trash icon. Not sure it's supposed to be there, as there's no help icon on desktop resolution.

IMG_1153

### Describe the behavior you expected

for it to work on mobile

### Steps to reproduce the issue

1. Go to Application Credentials page on mobile device

### What version of Home Assistant Core has the issue?

2024.7.0b5

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### LINKED ISSUE #21230: Application Credentials - missing red text on Delete button in select mode
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When in select mode of Application Credentials page, the "Delete Selected" button is lacking red text to indicate a destructive action. The other delete buttons (in action menu, and confirmation dialog) have red text as expected, just not here.

See top right of screenshot. 

Screenshot 2024-06-29 at 11 23 38 PM

### Describe the behavior you expected

Red text on "Delete Selected" button

### Steps to reproduce the issue

1. Go to Application Credentials page
2. Enter Select mode, look at delete button in top right

[Open your Home Assistant instance and Manage your application credentials.](https://my.home-assistant.io/redirect/application_credentials/)

### What version of Home Assistant Core has the issue?

2024.7.0b5

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #21229 fixes #21230
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **New Features**
  - Enhanced picker component headers with additional properties for better narrow-view support.
  
- **Style**
  - Introduced a `.warning` style to highlight elements with the primary theme color set to the error color.

### CODE REVIEW

File: src/panels/config/application_credentials/ha-config-application-credentials.ts [hunk 1]
```diff
@@ -75,6 +75,7 @@ export class HaConfigApplicationCredentials extends LitElement {
           title: localize(
             "ui.panel.config.application_credentials.picker.headers.name"
           ),
+          showNarrow: true,
```
Comment (bramkragten) [inline src/panels/config/application_credentials/ha-config-application-credentials.ts:78]:
```suggestion
          main: true,
```

**Comment by bramkragten** [comment]
Actions should not be removable or sortable

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]

**Comment by silamon** [comment]
> > Actions should not be removable or sortable and shown on mobile
> 
> I've left this out on mobile since you have the multi-delete with the checkboxes.

I see you added them. Looking good.
