### PR TITLE
Fix lab automations icons and sidebar width

### LINKED ISSUE #28183: Intuitive triggers and conditions lab: visual bugs
### Description

1. Remove content padding in the automation sidepanel
Image

2. Sizes of target icons differ from Floor to Area view. Icon size should be 24px, height of the "chip" 24px
Floor:
Image

Area:
Image

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change
- fix #28183
  - fix sidebar content width for lab triggers and condititons
  - fix lab selected target

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-icon.ts [hunk 1]
```diff
@@ -186,6 +186,7 @@ export class HaIcon extends LitElement {
 
   static styles = css`
     :host {
+      display: flex;
```
Comment (MindFreeze) [inline src/components/ha-icon.ts:189]: This seems risky. In `ha-svg-icon` it's handled with a variable `display: var(--ha-icon-display, inline-flex)`. But I don't see a problem in the UI so this is theoretical.

File: src/panels/config/automation/condition/types/ha-automation-condition-platform.ts [hunk 2]
```diff
@@ -393,6 +393,10 @@ export class HaPlatformCondition extends LitElement {
   }
 
   static styles = css`
+    :host {
+      display: block;
+      margin: 0px -16px;
```
Comment (MindFreeze) [inline src/panels/config/automation/condition/types/ha-automation-condition-platform.ts]:
```suggestion
      margin: 0px calc(-1 * var(--ha-space-4));
```

File: src/panels/config/automation/trigger/types/ha-automation-trigger-platform.ts [hunk 3]
```diff
@@ -429,6 +429,10 @@ export class HaPlatformTrigger extends LitElement {
   }
 
   static styles = css`
+    :host {
+      display: block;
+      margin: 0px -16px;
```
Comment (MindFreeze) [inline src/panels/config/automation/trigger/types/ha-automation-trigger-platform.ts]:
```suggestion
      margin: 0px calc(-1 * var(--ha-space-4));
```

File: src/components/ha-icon.ts (hunk 1 above)
Comment (wendevlin) [reply src/components/ha-icon.ts:189]: Yes, I was also pretty unsure but I havn't seen an issue anywhere :slightly_smiling_face:

Comment (piitaya) [reply src/components/ha-icon.ts:189]: I would not do that during beta 😅

Comment (piitaya) [reply src/components/ha-icon.ts:189]: Hum, I haven't see any issue yet so it should be fine I guess.. 😅

File: src/panels/config/automation/add-automation-element/ha-automation-add-items.ts
Comment (piitaya) [inline src/panels/config/automation/add-automation-element/ha-automation-add-items.ts]:
```suggestion
      gap: var(--ha-space-2);
```

Comment (piitaya) [reply src/panels/config/automation/add-automation-element/ha-automation-add-items.ts]: Unrelated feedback, should we add more space here?

Comment (wendevlin) [reply src/panels/config/automation/add-automation-element/ha-automation-add-items.ts]: I cannot commit it :unamused: 

I talked to Marcin and it's approved :+1:  thanks @piitaya I'll add it

**Review by piitaya — APPROVED** [review]
