### PR TITLE
Don't use selector inside choose action

### LINKED ISSUE #13642: Actions inside choose block cannot be reordered [2022.9.0b6]
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Actions inside `choose` block cannot be reordered. 
Conditions are reorder-able just fine.

### Describe the behavior you expected

Actions can be re-orderd inside any block.

### Steps to reproduce the issue

1. Create or edit automation
2. Create choose block with any conditions and at least 2 actions
3. Select "Re-order" option from 3-dots menu

### What version of Home Assistant Core has the issue?

core-2022.9.0b6

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome 105.0.5195.102, Mozilla Firefox 105beta, Android mobile app 2022.8

### Which operating system are you using to run this browser?

Windows 10, android 11

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

```yaml
action:
  - choose:
      - conditions:
          - <condition>
        sequence:
          - <action>
          - <action>
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Choose action was the only one that used action selector (that doesn't support re-order mode)

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #13642
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]

File: src/panels/config/automation/action/types/ha-automation-action-choose.ts [hunk 1]
```diff
@@ -64,13 +63,13 @@ export class HaChooseAction extends LitElement implements ActionElement {
                 "ui.panel.config.automation.editor.actions.type.choose.sequence"
               )}:
             </h3>
-            <ha-form
+            <ha-automation-action
+              .actions=${option.sequence || []}
+              .reOrderMode=${this.reOrderMode}
               .hass=${this.hass}
-              .schema=${[{ name: "sequence", selector: { action: {} } }]}
```
Comment (bramkragten) [inline src/panels/config/automation/action/types/ha-automation-action-choose.ts:69]: Auch, this one was expensive, good that it is gone 😄
