### PR TITLE
Media player fixes

### LINKED ISSUE #28602: Media player volume slider - Add step tap. Press and hold step change. Drag and set
### Description

The media player volume control should support precise, increment adjustments without introducing + & - buttons.

Updating the volume slider to match behaviour of Music Assistant by - 
	•	Step-based changes by tapping left/right on the slider track
	•	Direct value setting via dragging the slider button

### Additional context

[https://www.figma.com/design/7h74CnHOxmw5mTKxdI9c33/Media-player---dialog?node-id=797-734&t=D2xXQBhPhpQAs2tS-1](url)

**User action**

 _On mobile/ touch device_
- Tap left/right on the slider to step down/up in small increments
- Dragging and holding slider button changes level

 _On desktop device_
- Click left/right on the slider to jump volume to that point
- Dragging and holding slider button changes level

**System response**

- ON MOBILE / TOUCH device - When slider tapped volume steps down/up in small increments
- When slider button dragged, volume sets at released point.
- System displays volume level changes in real time.

**Micro interactions**

- Volume level indicator updated in real time

### PR DESCRIPTION
**Pull request by uptimeZERO**
## Proposed change

image
I'm aiming to address a few issues I discovered with the media player here:

1. The media track in the dialog does not update in real-time.
2. The media track in the media bar does not support seeking, nor is it using the system primary color.
3. There is no padding/margin between the volume button and the device select.
4. The album cover does not load in all situations on the dialog.
5. The dialog track times need padding/margin on the top to stop the progress dot from covering the time.
6. The volume slider does not behave in the same way as in music assistant

https://github.com/user-attachments/assets/4a92d232-6c14-4846-a183-3348d187b9cc

I've implemented the following fixes and missing functionality in this PR:

1. The media track in the dialog now updates in real-time.
2. The media track in the media bar now supports seeking and uses the system primary color.
3. Added missing margin between the volume button and device select in the media bar.
4. Fixed a bug with album covers not loading in all situations in the more info dialog.
5. Fixed margins around media track times.
6. Updated the volume slider to behave in the same way as described [here](https://github.com/home-assistant/frontend/issues/28602) (essentially making it like the volume slider in Music Assistant).
7. Migrated the volume slider to `ha-dropdown`.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #28602 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by uptimeZERO** [comment]
Please avoid scope creep PR comments unless they are directly focused on the media player. There are a lot more fixes and missing functionalities that I want to bring to the media browser page as-a-whole, but will be continuing in additional PRs to chunk out the overhaul a bit more for ease of review.

File: src/panels/media-browser/ha-bar-media-player.ts [hunk 1]
```diff
@@ -342,26 +412,24 @@ export class BarMediaPlayer extends SubscribeMixin(LitElement) {
                     </ha-button>
                   `
             }
-            <ha-list-item
-              .player=${BROWSER_PLAYER}
-              ?selected=${isBrowser}
-              @click=${this._selectPlayer}
+            <ha-dropdown-item
+              class=${isBrowser ? "selected" : ""}
```
Comment (silamon) [inline src/panels/media-browser/ha-bar-media-player.ts:416]:
```suggestion
              class=${classMap({ selected: isBrowser })}
```

File: src/panels/media-browser/ha-bar-media-player.ts [hunk 2]
```diff
@@ -342,26 +412,24 @@ export class BarMediaPlayer extends SubscribeMixin(LitElement) {
...
             >
               ${this.hass.localize("ui.components.media-browser.web-browser")}
-            </ha-list-item>
+            </ha-dropdown-item>
             ${this._mediaPlayerEntities.map(
               (source) => html`
-                <ha-list-item
-                  ?selected=${source.entity_id === this.entityId}
+                <ha-dropdown-item
+                  class=${source.entity_id === this.entityId ? "selected" : ""}
```
Comment (silamon) [inline src/panels/media-browser/ha-bar-media-player.ts:424]: Use classMap

**Review by silamon — APPROVED** [review]

**Comment by silamon** [comment]
> Please avoid scope creep PR comments unless they are directly focused on the media player. There are a lot more fixes and missing functionalities that I want to bring to the media browser page as-a-whole, but will be continuing in additional PRs to chunk out the overhaul a bit more for ease of review.

It's more preferred to have small focused PR's. Not only for reviewing, but also to pinpoint issues that are reported as bugs, it's easy to revert a part instead of the whole bunch of improvements. Going to merge it in, so you can continue the great improvements in different PR's.
