### PR TITLE
Multi term search sort by search score

### LINKED ISSUE #27269: Search results are not prioritizing the most relevant items at the top
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When searching for entities in various dropdown menus throughout Home Assistant, the most relevant matches are not consistently prioritized at the top of the results. This occurs in multiple contexts, including when adding entities to cards and when selecting entities for automations.

Example issue:
When searching for "aqaramotion3", entities named "aqaramotion1" appear above the exact match "aqaramotion3" in the search results.

Impact:
While this isn't a critical problem, it becomes increasingly frustrating when working with dozens of similarly named entities, as users must scan through irrelevant results to find the exact match they're looking for.

The search algorithm could be improved to better prioritize exact matches and more relevant results.

### Describe the behavior you expected

The most relevant items appear at the top of the search results.

### Steps to reproduce the issue

1.Open “Edit an entity’s card.”
2. Search for an entity to add.
3. Observe the dropdown results.

### What version of Home Assistant Core has the issue?

2025.9.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Google Chrome version 140.0.7339.128 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

Image

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change
- introduce `multiTermSortedSearch`
  - Use fusejs to search for multiple terms and respect result search score
  - Use search keys to define weights to each search label
- Replace HaFuse with `multiTermSearch`
- remove `ha-area-floor-picker` it was used in the old target-picker, but it's not used anymore
- fixes https://github.com/home-assistant/frontend/issues/27269

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by piitaya** [comment]
For datatable, I wonder if it makes sense to sort the result as we already have the sort column.

**Comment by wendevlin** [comment]
> For datatable, I wonder if it makes sense to sort the result as we already have the sort column.

It shouldn't sort for datatable. And I think I implemented it like this. Otherwise its a bug. Same for areafloor

File: src/components/entity/ha-statistic-picker.ts [hunk 1]
```diff
@@ -38,9 +38,21 @@ type StatisticItemType = "entity" | "external" | "no_state";
...
+const SEARCH_KEYS = [
+  { name: "label", weight: 10 },
+  { name: "search_labels.entityName", weight: 10 },
+  { name: "search_labels.friendlyName", weight: 9 },
+  { name: "search_labels.deviceName", weight: 8 },
+  { name: "search_labels.areaName", weight: 6 },
+  { name: "search_labels.domainName", weight: 4 },
+  { name: "statisticId", weight: 3 },
+  { name: "id", weight: 2 },
+];
```
Comment (piitaya) [inline src/components/entity/ha-statistic-picker.ts:54]: The search labels was created to put all the search term in a single array to simplify usage. Now that we have that search keys, should be consider to flat the object?

Comment (wendevlin) [reply src/components/entity/ha-statistic-picker.ts:54]: We could, but when we keep `search_labels` we can show with the object structure for what reason the values are in the object.

What is the exact reason you would like to flat it?

Comment (piitaya) [reply src/components/entity/ha-statistic-picker.ts:54]:
```
const SEARCH_KEYS = [
  { name: "label", weight: 10 },
  { name: "entityName", weight: 10 },
  { name: "friendlyName", weight: 9 },
  { name: "deviceName", weight: 8 },
  { name: "areaName", weight: 6 },
  { name: "domainName", weight: 4 },
  { name: "statisticId", weight: 3 },
  { name: "id", weight: 2 },
];
```
It would be easier 😅

Comment (wendevlin) [reply src/components/entity/ha-statistic-picker.ts:54]: depends now, you have to add it to the interface `StatisticComboBoxItem` and you loose the context why the value is in there. Sorry I am pro `search_labels`

**Review by piitaya — APPROVED** [review]
The combobox items and search keys should not be part of the registry files. I feel like we should create dedicated file for those.

**Comment by wendevlin** [comment]
> The combobox items and search keys should not be part of the registry files. I feel like we should create dedicated file for those.

yeah that makes sense. I will write it down and add a fix in future

**Comment by karwosts** [comment]
I think something has gone very wrong here:

image

image

**Comment by piitaya** [comment]
@wendevlin 

`search_keys` prefix is missing for service picker :  

```ts
const SEARCH_KEYS = [
  { name: "name", weight: 10 },
  { name: "description", weight: 8 },
  { name: "domainName", weight: 6 },
  { name: "serviceId", weight: 3 },
];
```

**Comment by wendevlin** [comment]
> `search_keys`

- https://github.com/home-assistant/frontend/pull/28481

**Comment by wendevlin** [comment]
> I think something has gone very wrong here:

haha yes. Search keys are wrong :see_no_evil:

**Comment by wendevlin** [comment]
> I think something has gone very wrong here:

- https://github.com/home-assistant/frontend/pull/28483
