### PR TITLE
Call correct "button.press" service for button entity toggle action

### LINKED ISSUE #10975: Button Card cannot operate with Button Entity
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

A button card in lovelace, configured with a button entity and tap action "toggle".
when the button card is tapped ui return the message:"failed to call service button/turn_off".

### Describe the behavior you expected

The button card connected to a button entity with tap action "toggle" shall call service "button/press".

### Steps to reproduce the issue

1. configure a button entity
2. configure a button card connected to the button entity above and default action "toggle"
3. tap the button card.

### What version of Home Assistant Core has the issue?

core-2021.12.2 to core-2021.12.9

### What was the last working version of Home Assistant Core?

 core-2021.12.9

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

Workaround: instead using "Toggle" as default action, use "Call Service" configured to call service "button:press" to the entity.

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Logic was missing, so wrong service got called.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #10975
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by zsarnett — APPROVED** [review]

**Review by balloob — APPROVED** [review]

File: src/panels/lovelace/common/entity/turn-on-off-entity.ts [hunk 1]
```diff
@@ -17,6 +17,9 @@ export const turnOnOffEntity = (
     case "cover":
       service = turnOn ? "open_cover" : "close_cover";
       break;
+    case "button":
```
Comment (frenck) [inline src/panels/lovelace/common/entity/turn-on-off-entity.ts:20]: And "input_button"?

Comment (spacegaier) [reply src/panels/lovelace/common/entity/turn-on-off-entity.ts:20]: Good point => https://github.com/home-assistant/frontend/pull/11350
