### PR TITLE
Disable pointer events when icon button disabled

### LINKED ISSUE #6151: User can delete current refresh token
## Checklist

- [ ] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

In the user profile page > refresh token section, there is one refresh token which referenced to current session, when user hover the delete icon of this session, a tooltip with "Unable to delete current refresh token" will shown, But this does not prevent the user to delete the refresh token.

## Expected behavior

May user can not delete self refresh token, or we should remove this tooltip.

## Environment

arch | x86_64
-- | --
chassis | desktop
dev | false
docker | true
hassio | true
host_os | Debian GNU/Linux 10 (buster)
installation_type | Home Assistant Supervised
os_name | Linux
os_version | 5.5.0-0.bpo.2-amd64
python_version | 3.7.7
supervisor | 227
timezone | Asia/Tehran
version | 0.110.4
virtualenv | false

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### LINKED ISSUE #6153: Attempting to move the bottom card of a view down deletes it and corrupts the view's config
### Problem

When you click the button to move a card down and that card is already at the lowest point, the card's contents will disappear and the card itself will somehow corrupt your config until you remove it through the UI. Instead of the contents of the card you'll see a red bar saying "Config is not an object." Editing the raw config of the UI through the interface will just show a white screen with no YAML content, and editing the card doesn't work either, the frontend seems to think you're making a new card and shows the header of the interface you get when making a new card, but shows none of the options to actually make one. The only way to solve the issue is to delete the card and re-adding it.

The lovelace configuration includes a `null` instead of the card that just disappeared:

```
                    "cards": [
                        {
                            "entities": [],
                            "title": "Lights",
                            "type": "entities"
                        },
                        null
                    ]
```

I included the penultimate card here to show where the null goes, it's not part of the problem of course.

I first noticed this problem in 0.109 but I figured I had just screwed something up, but I just encountered it again. It's pretty destructive because it removes the entire content of the whatever card it happens to and you have to rewrite that card completely.

### Environment:

Docker container with homeassistant/home-assistant version 0.111.1 on a Synology NAS with an Atom CPU.

### Screenshot of the issue

image

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Fixes https://github.com/home-assistant/frontend/issues/6153
Fixes https://github.com/home-assistant/frontend/issues/6151

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-icon-button.ts [hunk 1]
```diff
@@ -24,28 +24,21 @@ export class HaIconButton extends LitElement {
...
-    }
-  }
-
   static get styles(): CSSResult {
     return css`
       :host {
         display: inline-block;
         outline: none;
       }
+      :host([disabled]) {
```
Comment (balloob) [inline src/components/ha-icon-button.ts:39]: Does mwc-icon-button reflect it? You changed it from attribute to property

File: src/components/ha-icon-button.ts [hunk 2]
```diff
@@ -24,28 +24,21 @@ export class HaIconButton extends LitElement {
 
   protected render(): TemplateResult {
     return html`
-      <mwc-icon-button
-        .label=${this.label}
-        ?disabled=${this.disabled}
-        @click=${this._handleClick}
-      >
+      <mwc-icon-button .label=${this.label} .disabled=${this.disabled}>
```
Comment (balloob) [inline src/components/ha-icon-button.ts:27]: This is a bug in mwc-icon-button. They should do this.

**Review by balloob — APPROVED** [review]

File: src/components/ha-icon-button.ts (hunk 1 above)
Comment (bramkragten) [reply src/components/ha-icon-button.ts:39]: Yes
