### PR TITLE
Fix bug in non-recurring calendar event creation

### LINKED ISSUE #14853: Cannot create calendar event without repetition
### The problem

If I connect to Home Assistant then go to calendar and Add event, I type a description, a summary, choose my local calendar, choose beginning and end date which are the same except for the hour, I let repetition to None but when I click to add event I have an error.

### What version of Home Assistant Core has the issue?

2022.12.8

### What was the last working version of Home Assistant Core?

_No response_

### What type of installation are you running?

Home Assistant Core

### Integration causing the issue

Local calendar

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/local_calendar

### Diagnostics information

_No response_

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

```txt
2022-12-21 18:00:45.945 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281471277087856] Error handling message: Invalid rrule: empty string for dictionary value @ data['event']['rrule']. Got '' (invalid_format) from xxx.xxx.xxx.xxx (Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0)
2022-12-21 18:00:53.413 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281471277087856] Error handling message: Invalid rrule: empty string for dictionary value @ data['event']['rrule']. Got '' (invalid_format) from xxx.xxx.xxx.xxx (Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0)
2022-12-21 18:02:13.273 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281471277087856] Error handling message: Invalid rrule: empty string for dictionary value @ data['event']['rrule']. Got '' (invalid_format) from xxx.xxx.xxx.xxx (Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0)
2022-12-21 18:02:29.231 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281471277087856] Error handling message: Invalid rrule: empty string for dictionary value @ data['event']['rrule']. Got '' (invalid_format) from xxx.xxx.xxx.xxx (Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0)
2022-12-21 18:04:50.706 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281471277087856] Error handling message: Invalid rrule: empty string for dictionary value @ data['event']['rrule']. Got '' (invalid_format) from xxx.xxx.xxx.xxx (Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0)
2022-12-21 18:04:54.121 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281471277087856] Error handling message: Invalid rrule: empty string for dictionary value @ data['event']['rrule']. Got '' (invalid_format) from xxx.xxx.xxx.xxx (Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0)
2022-12-21 18:08:35.131 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281471277087856] Error handling message: Invalid rrule: empty string for dictionary value @ data['event']['rrule']. Got '' (invalid_format) from xxx.xxx.xxx.xxx (Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0)
2022-12-21 18:18:14.509 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281470810307792] Error handling message: Invalid rrule: empty string for dictionary value @ data['event']['rrule']. Got '' (invalid_format) from xxx.xxx.xxx.xxx (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36)
```

### Additional information

Of course, the message is always the same, all my attempts  in fact.
I tried on both Chrome and Firefox
Each time, the form displays
`Invalid rrule: empty string for dictionary value @ data['event']['rrule']. Got ''`
If I select a repetition, I can add the event without issue.

### PR DESCRIPTION
**Pull request by allenporter**
## Proposed change

Fix event creation with no repeat:
```
2022-12-21 18:08:35.131 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281471277087856] Error handling message: Invalid rrule: empty string for dictionary value @ data['event']['rrule'].
```
This happens when you create an event, change to recurring, then change back to None and it sends an empty string. Now it is omitted from the request when there is no repeat.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #14853
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — DISMISSED** [review]

File: src/panels/calendar/dialog-calendar-event-editor.ts [hunk 1]
```diff
@@ -387,7 +387,7 @@ class DialogCalendarEventEditor extends LitElement {
     const data: CalendarEventMutableParams = {
       summary: this._summary,
       description: this._description,
-      rrule: this._rrule,
+      rrule: this._rrule ? this._rrule : undefined,
```
Comment (bramkragten) [inline src/panels/calendar/dialog-calendar-event-editor.ts:390]:
```suggestion
      rrule: this._rrule || undefined,
```

**Review by bramkragten — APPROVED** [review]
