### PR TITLE
Fix icon db loading

### LINKED ISSUE #9269: MDI icons missing since 2021.5.5 update
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since the latest update to 5.5 my MDI icons disappear and will reappear later (sometimes after multiple refreshes). I am using the app on my iphone (latest update). I have cleared my front end cache.

### Describe the behavior you expected

icons not disappearing

### Steps to reproduce the issue

1. Open IOs app
2.look at pages and other icons. They will be missing
3.close app and cross fingers when app reopened 
...

### What version of Home Assistant Core has the issue?

2021.5.5

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

IOS 2021.5 (2021.150)

### Which operating system are you using to run this browser?

IOS 14.6

### State of relevant entities

```txt
Climate, icons like mdi:home, mdi:climate, etc…
```

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Return the actual icon from the DB... 

AND

Pretty ugly fix for Safari on iOS sometimes just not opening the database...
Fixes https://github.com/home-assistant/frontend/issues/9269

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/common/util/promise-timeout.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+export const promiseTimeout = (ms: number, promise: Promise<any>) => {
+  const timeout = new Promise((_resolve, reject) => {
+    setTimeout(() => {
+      reject("Timed out in " + ms + "ms.");
```
Comment (ludeeus) [inline src/common/util/promise-timeout.ts:4]:
```suggestion
      reject(`Timed out in ${ms} ms.`);
```

**Review by ludeeus — APPROVED** [review]
