### PR TITLE
Fix ha-state-badge name in picture element card

### LINKED ISSUE #19673: State Badge in Picture Elements does not show label/legend with entity name any more (2024.2.0bx)
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

From 2024.2 betas and on, the state-badge object does not show the name of the entity if used inside a picture element object.

### Describe the behavior you expected

On previous versions like 2024.01 and earlier, there was a label with the full name of the entity attribute under the state badge.
Are there ongoing changes on picture element and/or state-badge that should hide/show that label ?  

### Steps to reproduce the issue

1. On the UI, add a new card based on a picture element
2. Add a state-badge for an entity attribute ( ex. temperature of a sensor )
3. View the card on UI

### What version of Home Assistant Core has the issue?

2024.2.0b5

### What was the last working version of Home Assistant Core?

2024.1.x

### In which browser are you experiencing the issue with?

Firefox

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

`showName` was implicitly set to true by default by checking `false`. Now it's explicitly set.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/19673
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by karwosts** [comment]
I don't think we ever intended to show this name here, it's not configurable via title, and user can't turn it off.

If we're going to do this, should we at least make `name` and `title` the same, so user can configure?

**Comment by piitaya** [comment]
It's only a fix to restore the `2024.1` behavior. Isn't what we had before?

**Comment by karwosts** [comment]
That's fine, I just think the 2024.1 behavior was wrong 😅 

But if we just want to roll back to that, we can improve it later.

**Comment by piitaya** [comment]
Yes, we can improve it later 👍. As the release is tomorrow, we do not want to change something one day before release. 😅

File: src/panels/lovelace/elements/hui-state-badge-element.ts [hunk 1]
```diff
@@ -58,6 +58,7 @@ export class HuiStateBadgeElement
           : this._config.title === null
             ? ""
             : this._config.title}
+        .showName=${true}
```
Comment (bramkragten) [inline src/panels/lovelace/elements/hui-state-badge-element.ts:61]:
```suggestion
        showName
```

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
