### PR TITLE
Fixes for snapshot upload during onboarding

### LINKED ISSUE #7316: Snapshot upload not working
## The problem
I woud like to migrate my Hass installation to a new VM, so i made a snapshot, downloaded that one and now trying to restore it on the new VM. I can select the upload option, select the file, but after a while it gives back a 502 Bad Gateway error.

## Environment
Latest and greatest version of HassOS OVA (4.13)

- Operating environment (OS/Container/Supervised/Core): OS

## Problem-relevant `configuration.yaml`
No configuration.yaml file yet as this is in the setup wizard

## Traceback/Error logs
502 Bad Gateway

In core log : 

```txt
ERROR (MainThred) [homeassistant.components.hassio.http] Client timeout error on API request snapshots/new/upload
```

## Additional information
Backup is 1.34GB.

### PR DESCRIPTION
**Pull request by ludeeus**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #7316
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/onboarding/onboarding-restore-snapshot.ts [hunk 1]
```diff
@@ -38,7 +38,7 @@ class OnboardingRestoreSnapshot extends ProvideHassLitMixin(LitElement) {
 
   @property({ type: Boolean }) public restoring = false;
 
-  @internalProperty() private _log?: string;
+  @internalProperty() private _log: string = "";
```
Comment (bramkragten) [inline src/onboarding/onboarding-restore-snapshot.ts:41]:
```suggestion
  @internalProperty() private _log = "";
```

**Review by bramkragten — APPROVED** [review]
