### PR TITLE
Fix external auth reconnection loop if connection lost after refresh token expiration

### LINKED ISSUE #7732: Reconnecting loop if connection is broken after 30 minutes
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Every now and then i can't get a reconnection to my home assistant after the connection is broken (ex. duo to a home assistant restart) with the android app. The frontend just shows the message "Connection lost. Reconnecting..." for ever. I had never problems with HA releases  before this PR #7236.

Did some debugging the last couple of days and tracked down the problem to this PR #7236. 

While HA is restarting the frontend tries to reconnect in background.

1. `RefreshAccessToken`is called 
https://github.com/home-assistant/frontend/blob/4973d8f629c3619f7e113b6fb6888aaf3027ede6/src/external_app/external_auth.ts#L69

2.  `RefreshAccessToken`calls `getExternalAuth`
https://github.com/home-assistant/frontend/blob/4973d8f629c3619f7e113b6fb6888aaf3027ede6/src/external_app/external_auth.ts#L92

3. `getExternalAuth` triggers the `onGetExternalAuth` of the android app 
https://github.com/home-assistant/android/blob/6e13b162144cfeed69d0d37f050098d2b16ebf6c/app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt#L82

4. The method call `view.setExternalAuth` will fail because Home assistant is not yet restarted.

5. The catch block is triggered and calls the following method:
https://github.com/home-assistant/android/blob/6e13b162144cfeed69d0d37f050098d2b16ebf6c/app/src/main/java/io/homeassistant/companion/android/webview/WebViewPresenterImpl.kt#L88

6. Now the `_tokenCallbackPromise` is trigged 
https://github.com/home-assistant/frontend/blob/4973d8f629c3619f7e113b6fb6888aaf3027ede6/src/external_app/external_auth.ts#L81
with success = false. Meaning the _tokenCallbackPromise is in a rejected state.

7. Now after one second the next try for a reconnect starts.  
https://github.com/home-assistant/home-assistant-js-websocket/blob/1836b3ae57309a969627fc993619cfd40b47204c/lib/socket.ts#L84

8. Again `RefreshAccessToken` is called because of expired session token. This time from the reconnection instead of the app https://github.com/home-assistant/home-assistant-js-websocket/blob/1836b3ae57309a969627fc993619cfd40b47204c/lib/socket.ts#L87

9. Then this check is called:
https://github.com/home-assistant/frontend/blob/4973d8f629c3619f7e113b6fb6888aaf3027ede6/src/external_app/external_auth.ts#L70  `_tokenCallbackPromise` is not undefined and force is undefined because the parameter is not defined by the caller.  Then the `_tokenCallbackPromise` is called. And here is the **culprint**: `tokenCallbackPromise` is in a rejected state with undefined data.   The rejected promise triggers an exception.

10. The exception is then handled here:
https://github.com/home-assistant/home-assistant-js-websocket/blob/1836b3ae57309a969627fc993619cfd40b47204c/lib/socket.ts#L90
This triggers that the websocket will be closed again.

11. Then the reconnection process is beginning from the start. And we are in a reconnect loop.

On the home assistant side there are following messages. Which explains this process above.

```txt
2020-11-16 17:31:00 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140600942755264] Connected from ipaddress
2020-11-16 17:31:00 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140600942755264] Sending {'type': 'auth_required', 'ha_version': '0.117.6'}
2020-11-16 17:31:00 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140600942755264] Disconnected
```
I hope i could describe the problem understandable. 

## Expected behavior

Reconnecting should also work if  connected longer than 30 minutes.

## Steps to reproduce

I think this is reproducible with following steps:

1. Deactivate "Close connection automatically" in the profile settings of HA.
2. Open the android app and let it connect to home assistant
3. Lock the phone/tablet leaving the app open and in foreground
4. Wait around 30 minutes (I think this is the session timeout for the token)
5. Restart HA and wait till it is running fully again
5. Unlock the phone/tablet.

## Environment

- Home Assistant release with the issue: 0.117.6
- Last working Home Assistant release (if known): I think this should be 0115.6, because since 0.116 this PR is included
- Browser and browser version: Latest chrome/ android webview
- Operating system: Intel NUC - HASS OS

## Problem-relevant configuration

Disabled Close connection automatically in the profile settings.
This also happens on my samsung tablet with enabled close connection automatically, but i think this is a problem with the android app which doesnt pause the webview. I'm unsure on that one.

## Javascript errors shown in your browser console/inspector

Connection refused errors are shown as soon as the HA connection is broken

## Additional information

Maybe here
https://github.com/home-assistant/frontend/blob/4973d8f629c3619f7e113b6fb6888aaf3027ede6/src/external_app/external_auth.ts#L70

should be a check if the promise is rejected. If it is reject then do not return the reject promise. Instead do the stuff below (call getExternalAuth etc.) If the promise is resolved, then return the promise.

### PR DESCRIPTION
**Pull request by chriss158**
## Proposed change

This PR fixes the bug described in the issue #7732. This bug was introduced with PR #7236.

The external auth module (which is used by the companion apps (iOS/Android)) doesn't survive a lost connection if the refresh token is expired. The process is fully described in the issue #7732

The problem occurs frequently more on devices which doesn't close/suspend the app if not used and therefore doesn't force close the connection by closing/suspending the app.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

For better debugging, I lowered the refresh token expiration from 30 minutes to 1 minute in HA here:
https://github.com/home-assistant/core/blob/ac3a6aaa8cdb005b3c900f9d9671e5a859351060/homeassistant/auth/const.py#L4

To reproduce this problem you need to disable "Close connection automatically" in the profile settings (only if you didn't lower the refresh token expiration time < 5 minutes) and use the Home Assistant Companion App (Then the external auth module is used)

1. Open the app and let it open and wait for the refresh token timeout (30 minutes or if lowered the ACCESS_TOKE_EXPIRATION then X Minutes)
2. Right after the refresh token is expired, stop HA
3. Now wait till the App tries to reconnect and show the "Connection unsuccessful" popup with the "Wait/Retry/Settings" buttons.
3a. Alternatively you can try to trigger a fetch from HA with auth (which needs a new refresh token), by opening e.g. the history tab.
4. Now start HA again.

Now we are in a reconnection loop and the frontend cannot connect anymore.
You will see in the Home Assistant log continuously following messages (Be sure to enable the websocket debug logs in HA)
```yaml
logger:
  default: info
  logs:
    homeassistant.components.websocket_api: debug
```
```
2020-11-16 17:31:00 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140600942755264] Connected from ipaddress
2020-11-16 17:31:00 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140600942755264] Sending {'type': 'auth_required', 'ha_version': '0.117.6'}
2020-11-16 17:31:00 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection.140600942755264] Disconnected
```

## Additional information

- This PR fixes or closes issue: fixes #7732 
- This PR is related to issue or discussion: #7236 
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/external_app/external_auth.ts [hunk 1]
```diff
@@ -81,7 +87,9 @@ export class ExternalAuth extends Auth {
     this._tokenCallbackPromise = new Promise<RefreshTokenResponse>(
       (resolve, reject) => {
         window[CALLBACK_SET_TOKEN] = (success, data) =>
-          success ? resolve(data) : reject(data);
+          success
+            ? resolve(data)
+            : reject(new Error("Refresh token unsuccessful; "));
```
Comment (bramkragten) [inline src/external_app/external_auth.ts:92]: Why was this changed? We still want to use the data we get from the external app?

**Review by bramkragten — APPROVED** [review]

File: src/external_app/external_auth.ts (hunk 1 above)
Comment (chriss158) [reply src/external_app/external_auth.ts]: Yes your are right. I did not think that the data maybe still useful on a reject. I reverted the change. Thanks for the review 👍
