### PR TITLE
Don't add audio track if webrtc player is muted

### LINKED ISSUE #23230: WebRTC cameras open an audio stream and hold it
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If I have a Home Assistant tab open in a browser (Tested in Firefox and Edge.), if that dashboard contains any Picture Entity cards that tie onto cameras, it starts and holds an audio stream on that tab whether audio is being sent or not. This disrupts Bluetooth Multipoint 100%.

'Same goes for the mobile app. If the mobile application is open on my phone, Bluetooth audio will not hope back to my PC.

I can consistently reproduce this issue by starting audio on Device 1 has that HA open with a camera, then trying to listen to audio on Device 2— nothing. The very _instant_ I close Home Assistant the audio hops to the correct device.

Conclusion? The new WebRTC camera rigging is lighting up an audio channel– utilized or not.

### Describe the behavior you expected

I expect Home Assistant WebRTC cameras to not wrest control of an audio channel unless I choose to.

Here's the problem: I use Bluetooth Multipoint. What it does is hops between two different devices depending on the one that is playing audio. The benefit to this is one can throw on a Bluetooth headset, play audio from their PC, pause any audio, and then play audio from the cell phone instead. This is more-or-less how I get my meeting notifications.

Unfortunately, Multipoint is currently fully automatic, it is not possible for a user to choose which audio device they want play in their headphones. "Whichever one was playing first and is playing now."

### Steps to reproduce the issue

1. Connect a Bluetooth Multipoint device to two different devices. A PC and a cell phone will be easiest, I'd imagine.
2. Open a Home Assistant tab/instance with a dashboard that has a camera on it.
3. Verify no other audio in playing on the same device Home Assistant is running on.
4. Start up a different audio stream on– in this example– your cell phone. Notice that you hear nothing.
5. Close the HA on the PC— note the audio _instantly_ jumps to the correct device on the phone.

### What version of Home Assistant Core has the issue?

2024.12.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Edge 131.0.2903.86

### Which operating system are you using to run this browser?

Windows 10 Build 19045.5131

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Don't add audio track if webrtc player is muted.
Need more test before merging.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/23230
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-camera-stream.ts [hunk 1]
```diff
@@ -220,9 +220,10 @@ export class HaCameraStream extends LitElement {
         if (
           hlsStreams.hasVideo &&
           hlsStreams.hasAudio &&
-          !webRtcStreams.hasAudio
+          !webRtcStreams.hasAudio &&
+          !this.muted
```
Comment (bramkragten) [inline src/components/ha-camera-stream.ts]: That means we need to include `muted` in the memoized function variables?

Comment (oded106e) [reply src/components/ha-camera-stream.ts]: @bramkragten Hi,
There is an estimate time this fix will be published?

Thank you!

**Review by bramkragten — APPROVED** [review]
