### PR TITLE
Prevent index access errors in entity quick bar

### LINKED ISSUE #9925: Shortcut bar causes error when started and closed
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

entering 'c' to get to the shortcut bar shows the shortcut bar alright, but also errors in the log, see below.
when the shortcut bar is removed/closed another error is displayed

this is happening in Safari Mac. When using Chrome, only the closing error is raised

### Describe the behavior you expected

no errors

### Steps to reproduce the issue

1. enter c to reveal shortcut bar
2. nothing further is needed
3. closing...
...

### What version of Home Assistant Core has the issue?

2021.9.0b6/7

### What was the last working version of Home Assistant Core?

not sure

### In which browser are you experiencing the issue with?

Safari  Mac, Chrome Mac

### Which operating system are you using to run this browser?

macOS Big sur 11.4

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

opening error
```txt
2021-09-01 11:35:29 ERROR (MainThread) [frontend.js.latest.202108300] :0:0 Script error.
```

and upon closing:

```
2021-09-01 11:37:36 ERROR (MainThread) [frontend.js.latest.202108300] https://mydomain:port/frontend_latest/a4f644cd.js:172:56140 TypeError: undefined is not an object (evaluating 'e.target.items[t].item')
```

### Additional information

as per request in. https://discord.com/channels/330944238910963714/427516175237382144/882595152798023690

### LINKED ISSUE #9952: An error is thrown when using the entity quick bar
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

An error is raised then closing the entity details popup.

The following error is displayed in the logbook:

frontend_latest/a4f644cd.js:172:251 Uncaught TypeError: Cannot read properties of undefined (reading 'item')

### Describe the behavior you expected

no error was raised

### Steps to reproduce the issue

1. Open the entity quick bar
2. Click on a random entity
3. Close the entity details popup (either esc or close button)
4. Check the logbook

### What version of Home Assistant Core has the issue?

2021.9.2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google chrome 93.0.4577.63

### Which operating system are you using to run this browser?

macOs Big Sur (11.4)

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

```txt
Uncaught TypeError: Cannot read properties of undefined (reading 'item')
    at HTMLElement.value (a4f644cd.js:2160)
    at j.handleEvent (app.f08a72d3.js:5264)
    at Object.notifySelected (02f7d316.js:1359)
    at G.setSingleSelectionAtIndex_ (02f7d316.js:238)
    at G.setSelectedIndex (02f7d316.js:238)
    at HTMLElement.select (02f7d316.js:1359)
    at HTMLElement.updateItems (02f7d316.js:238)
    at HTMLElement.layout (02f7d316.js:1359)
    at 02f7d316.js:238
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

After selection of an entity in the quickbar, the function `_handleSelected()` gets called twice. First with the real selection index and then a second time with -1. This PR prevents the invalid access attempts for -1.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9952 fixes #9925
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/quick-bar/ha-quick-bar.ts [hunk 1]
```diff
@@ -299,8 +299,10 @@ export class QuickBar extends LitElement {
 
   private _handleSelected(ev: SingleSelectedEvent) {
     const index = ev.detail.index;
-    const item = ((ev.target as List).items[index] as any).item;
-    this.processItemAndCloseDialog(item, index);
+    if (index >= 0) {
```
Comment (bramkragten) [inline src/dialogs/quick-bar/ha-quick-bar.ts:302]:
```suggestion
    if (index < 0) {
    	return;
    }
```

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
