### PR TITLE
Prevent service call error if preset_mode is null

### LINKED ISSUE #13801: Climate more-info calls service unnecessarily if preset mode changed by integration
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

On the climate control (maybe applies to others too), if the more info dialog is open and the preset mode (looking at the code think also applies to all supported functions that can be changed in more info) is changed by the integration (not the UI), the UI in 
_handlePresetmodeChanged calls the service to change preset mode.  However, this is unnecessary as it has already been set.

This issue is very prevalent when an integration uses preset modes to both set a mode but also display modes that cannot be set directly but are from logic on the heating controller.  Selecting the preset mode in the UI does correctly set the preset mode but then the integration reports a preset mode of None.  If the more info dialog is open, this updates the select box and causes it to call the service again, resulting in an error:
```
Failed to call service climate/set_preset_mode. String value is None for dictionary value @ data['preset_mode']
```

### Describe the behavior you expected

If the select box is changed by a re-render and not by UI interaction, it should not call the service to set preset mode.  Equally if the preset mode is None, it should not call the service.

### Steps to reproduce the issue

1. Access more-info dialog for a climate entity
2. Set preset mode to x
3. Change the preset mode outside the more info dialog
4. Monitor the service calls to the integration and see another service call made.
5. Additionally, set the preset mode outside the more info to an option not available in preset modes in UI
6. Get the error as described above
...

### What version of Home Assistant Core has the issue?

2022.9.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Firefox 104.0 and Chrome 105.0.5195.127

### Which operating system are you using to run this browser?

Ubuntu 20.04 and Windows 11

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

Video Example

https://www.loom.com/share/f9ef44680149423e9ff203cebc5e1a44

### PR DESCRIPTION
**Pull request by msp1974**
## Proposed change

On the more-info-climate dialog, the preset_mode value can be null.  However, if it is null, it calls the set_preset_mode service with the preset_mode as null and causes an error.  

```
Failed to call service climate/set_preset_mode. String value is None for dictionary value @ data['preset_mode']
```
This minor change amends _handlePresetmodeChanged to prevent calling of the service is the preset_mode is null. 

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #13801 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/more-info/controls/more-info-climate.ts [hunk 1]
```diff
@@ -394,7 +394,7 @@ class MoreInfoClimate extends LitElement {
       [key: string]: unknown;
     }
   ) {
-    if (oldVal === newVal) {
+    if (oldVal === newVal || !newVal) {
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-climate.ts:397]: This is now for every service call, this also means you can no longer set the temperature to `0` for example.

This guard should be in `_handlePresetmodeChanged`

**Review by bramkragten — APPROVED** [review]
