### PR TITLE
Fix ha-selector-action drag and drop

### LINKED ISSUE #22255: Automation: Repeat GUI not visually updating after drag and drop
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After creating an Automation and with the 'Repeat' action, trying to drag and drop removes the dragged Action from its original location but it appears no action is added to the 'Repeat' action. If you save the automation and refresh the page or navigate away and back, it correctly displays the action within the 'Repeat' action only. 

The same issue occurs in reverse. Dragging an action from a 'Repeat' action to somewhere else appears to duplicate it, but does not truly continue to exist.

https://github.com/user-attachments/assets/615f595d-8333-4e78-8af5-2acdffaa7aad

### Describe the behavior you expected

To see the 'Action' update in real time and visually show its location.

### Steps to reproduce the issue

1. Create/Edit an Automation
2. Create a `Repeat` action and any other action
3. Drag and drop the other action into the `Repeat` action, and it will visually disappear
4. (Optional) Navigate away and back/refresh the page and it will display correctly

### What version of Home Assistant Core has the issue?

2024.10.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome 129.0.6668.90, Firefox 131.0

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

I recently attempted to recover a backup and am not confident I did so correctly. This may be a local issue instead of a bug.

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change

- Fix drag and drop to and from automation repeat actions

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #22255

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/common/util/array-move.ts [hunk 1]
```diff
@@ -20,14 +20,29 @@ function findNestedItem(
...
+
+  if (oldPath) {
+    newObj = updateNestedItem(newObj, [...oldPath]);
+  }
+  if (newPath) {
+    newObj = updateNestedItem(newObj, [...newPath]);
+  }
+
   const from = oldPath ? findNestedItem(newObj, oldPath) : newObj;
   const to = newPath ? findNestedItem(newObj, newPath, true) : newObj;
```
Comment (bramkragten) [inline src/common/util/array-move.ts:47]: We already have `from` and `to` here right, we can just make a copy here?

Comment (bramkragten) [reply src/common/util/array-move.ts:47]: Or use `toSpliced` instead of `splice` (not supported on older browsers)

Comment (wendevlin) [reply src/common/util/array-move.ts:47]: We have to set a new reference for `from` and `to` and we have to include this into newObj.

I set the new reference before manipulating, because there can be the case of index shifting which makes it way more complex afterwards.
Then I get the referenced `from` and `to` from new object and manipulate them. 

If I say `from = [...findNestedItem(newObj, oldPath)]`, from wouldn't update inside newObj anymore and I would need to include it at the correct position again.

toSpliced isn't well supported as you said and we woulnd't get a benefit out of it, because we would need to insert the spliced array again into the parent object.

 I also tried to clone the full object, but then we collapse everything because this is bound to the reference too.


If you find a simpler solution please suggest :slightly_smiling_face:

**Comment by piitaya** [comment]
Looks like this issue was introduced with the memoize function in the ha-selector-action. Should we fix it at the selector level?
https://github.com/home-assistant/frontend/blob/6df4992a1c394b96d67682336a1c67f93f6138d5/src/components/ha-selector/ha-selector-action.ts#L21-L26

**Comment by piitaya** [comment]
This is still not the right way to do it. I will look to fix it by handling drag and drop differently.

File: src/common/util/array-move.ts [hunk 2]
```diff
@@ -20,20 +20,33 @@ function findNestedItem(
...
-  const newObj = (Array.isArray(obj) ? [...obj] : { ...obj }) as A;
-  const from = oldPath ? findNestedItem(newObj, oldPath) : newObj;
-  const to = newPath ? findNestedItem(newObj, newPath, true) : newObj;
+  let newObj = (Array.isArray(obj) ? [...obj] : { ...obj }) as A;
 
-  if (!Array.isArray(from) || !Array.isArray(to)) {
-    return obj;
+  if (oldPath) {
+    newObj = updateNestedItem(newObj, [...oldPath]);
   }
```
Comment (piitaya) [inline src/common/util/array-move.ts:43]: We should keep this.

File: src/common/util/array-move.ts [hunk 3]
```diff
@@ -20,20 +20,33 @@ function findNestedItem(
   }, obj);
 }
 
+function updateNestedItem(obj: any, path: ItemPath): any {
+  const lastKey = path.pop()!;
+  const parent = findNestedItem(obj, path);
+  parent[lastKey] = Array.isArray(parent[lastKey])
+    ? [...parent[lastKey]]
+    : [parent[lastKey]];
```
Comment (piitaya) [inline src/common/util/array-move.ts:28]:
```suggestion
    ? [...parent[lastKey]]
    : { ...parent[lastKey] };
```
Should it be this?

File: src/common/util/array-move.ts [hunk 4]
```diff
@@ -20,20 +20,33 @@ function findNestedItem(
   }, obj);
 }
 
+function updateNestedItem(obj: any, path: ItemPath): any {
```
Comment (piitaya) [inline src/common/util/array-move.ts:23]:
```suggestion
function cloneNestedItem(obj: any, path: ItemPath): any {
```
Should be renamed

**Comment by piitaya** [comment]
@bramkragten @wendevlin I still did a review as it fixed the issue. I still think we should fix it in another way but at least for now, it closes the issue so I'm ok to merge it in you want.

File: src/common/util/array-move.ts (hunk 3 above)
Comment (wendevlin) [reply src/common/util/array-move.ts:28]: They idea is to fix it here if it isn't an Array, it actually should be an array but cannot be a array because of yaml

File: src/common/util/array-move.ts (hunk 2 above)
Comment (wendevlin) [reply src/common/util/array-move.ts:43]: Because "cloneNestedItem" converts to array if it isn't we won't need it.

**Comment by wendevlin** [comment]
> @bramkragten @wendevlin I still did a review as it fixed the issue. I still think we should fix it in another way but at least for now, it closes the issue so I'm ok to merge it in you want.

:+1: yeah there should be a cleaner solution

**Review by piitaya — APPROVED** [review]
