### PR TITLE
Fix timing issue in external auth

### LINKED ISSUE #3575: External authentication is not working
**Home Assistant release with the issue:** 0.98.1

**Last working Home Assistant release (if known):** unknown

**UI (States or Lovelace UI?):** both

**Browser and Operating System:** Chrome OS, Chrome 76

**Description of problem:** External authentication is not working. I'm opening web UI with `?external_auth=1` injecting JS in the `head` section of the page. Here is JS code:
```javascript
console.log('Start');
window.externalApp = {};
window.externalApp.getExternalAuth = function(options) {
  var options = JSON.parse(options);
  console.log("external auth callback: "+options.callback);
  if (options && options.callback) {
    console.log("Calling callback: "+options.callback);
    window[options.callback](true, {access_token: "%my_access_token%",expires_in: 1800});
  }
};
``` 
`getExternalAuth` method is called. I'm getting the first and the second output in console, but the I'm getting an error.
I tried to call a callback in different ways:
```javascript
window[options.callback]({access_token: "%my_access_token%",expires_in: 1800});
```
and
```javascript
window[options.callback](true, JSON.stringify({access_token: "%my_access_token%",expires_in: 1800}));
```
No luck.

**Javascript errors shown in the web inspector (if applicable):**
```
Uncaught (in promise) 1
```

**Additional information:**
So as a workaround I can call a callback with some delay after `getExternalAuth` was called.  This is because getExternalAuth called before Promise object created.

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/3575

### CODE REVIEW

File: src/external_app/external_auth.ts [hunk 1]
```diff
@@ -63,6 +63,13 @@ class ExternalAuth extends Auth {
   public async refreshAccessToken() {
     const callbackPayload = { callback: CALLBACK_SET_TOKEN };
 
+    const callbackPromise = new Promise<RefreshTokenResponse>(
+      (resolve, reject) => {
+        window[CALLBACK_SET_TOKEN] = (success, data) =>
+          success ? resolve(data) : reject(data);
+      }
+    );
+
```
Comment (balloob) [inline src/external_app/external_auth.ts]: We should add an `await 0` here so that we sleep 1 microtask to get the promise to actually set it on the window object.

File: src/external_app/external_auth.ts [hunk 2]
```diff
@@ -85,6 +87,11 @@ class ExternalAuth extends Auth {
   public async revoke() {
     const callbackPayload = { callback: CALLBACK_REVOKE_TOKEN };
 
+    const callbackPromise = new Promise((resolve, reject) => {
+      window[CALLBACK_REVOKE_TOKEN] = (success, data) =>
+        success ? resolve(data) : reject(data);
+    });
+
```
Comment (balloob) [inline src/external_app/external_auth.ts]: Same

**Review by balloob — APPROVED** [review]
ok to merge when comments addressed
