### PR TITLE
Fix floating ha-toast

### LINKED ISSUE #30330: Starting banner moving while scrolling on Mobile App
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

While HA starts, the banner at the bottom of the screen is moving while scrolling. 

### Describe the behavior you expected

The banner should remain still.

### Steps to reproduce the issue

During startup procedure, banner at the bottom, start scrolling on any page of the dashboard or settings.

### What version of Home Assistant Core has the issue?

core-2026.4.0b0 

### What was the last working version of Home Assistant Core?

core-2026.3.X

### In which browser are you experiencing the issue?

Android Companion App 

### Which operating system are you using to run this browser?

Android 16

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

https://github.com/user-attachments/assets/b69ac264-5841-4de8-a152-41938a787b46

### PR DESCRIPTION
**Pull request by timmo001**
## Proposed change

Replaced the `wa-popup` with standard div using the popover API directly. Replicated most of the functionality and fallbacks to CSS (see legacy browser testing below)

Adjusted the padding on the toast itself to fit the content a little better (space 2 -> 3 etc) 

## Screenshots

https://github.com/user-attachments/assets/5b1b8308-893e-45c1-afbf-14416c60ace7

https://github.com/user-attachments/assets/d2286683-5511-4da5-accb-8e097c9b7f00

image
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #30330
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

**Comment by timmo001** [comment]
[`90b753c` (this PR)](https://github.com/home-assistant/frontend/pull/30344/commits/90b753ca1b791a6e60be7b38b4bac058d8ff1a32)

Installed package locally, it is newer than webawesome's version though

https://github.com/home-assistant/webawesome/blob/next/packages/webawesome/package.json#L85

**Comment by bramkragten** [comment]
I feel like floating-ui is a bit of overkill for this, as we dont need to attach it to an element that is moving on screen, or keep the toast on screen, cant we just set the toast itself to a fixed position?

**Comment by timmo001** [comment]
Not without changing the library to force fixed strategy: https://github.com/home-assistant/webawesome/blob/next/packages/webawesome/src/components/popup/popup.ts?rgh-link-date=2026-03-26T10%3A45%3A02Z#L434

**Comment by bramkragten** [comment]
We are not using popup anymore now right?

**Comment by timmo001** [comment]
> We are not using popup anymore now right?

In dev we are yeah. Unless you mean `wa-popover`?

**Comment by bramkragten** [comment]
I mean for the toast

**Comment by timmo001** [comment]
Ah yeah damn stops the toast working on top layer again 
image

**Comment by timmo001** [comment]
Tried the strategy fixed change on the lib, that made things worse

https://github.com/user-attachments/assets/f6fe61eb-ef44-4aac-b0a6-532f062930cd

**Comment by timmo001** [comment]
Found a better solution using the popover api directly

**Comment by wendevlin** [comment]
That won't work in legacy browsers. Is WA using this API too?

**Comment by timmo001** [comment]
> That won't work in legacy browsers. Is WA using this API too?

https://github.com/home-assistant/webawesome/blob/80c10c1ff3290ef2b11b2371555c0fa7818948c6/packages/webawesome/src/components/popup/popup.ts#L36

They use this and rely on CSS otherwise for legacy browsers. This is the same for wa-popover usage as they expand wa-popup.

I've added a fallback to css for legacy browsers

**Comment by wendevlin** [comment]
> I've added a fallback to css for legacy browsers

nice, can you test it in a legacy browser and confirm that it works?

**Comment by timmo001** [comment]
Windows 10 Chrome 100 (build from 2022, popovers added in 2024):


https://github.com/user-attachments/assets/ecedf159-45c6-4243-b4e4-0e7e7b028840

Functional, but top layer issue returns.

ES5 build uses standard `dialog` element not sure if this has a fix in old browsers

Second test in same build with mobile layout:

https://github.com/user-attachments/assets/9836fd1d-a0dd-454f-90de-5c0af4b600f6


There's a secondary issue here with pickers in the wrong position, but as most desktops are on the new build I would say this is fine. The bottom sheets in mobile are odd also, but these might be browserstack/bad build related, not an es5 issue.

Might also try an old mobile device on here

**Comment by timmo001** [comment]
iPad os 18 on safari  (seems to class as a modern build):


https://github.com/user-attachments/assets/e1f96183-661c-4ae4-93bd-60491badc342

**Comment by timmo001** [comment]
iPad os 17

https://github.com/user-attachments/assets/881e6399-68a8-458f-9ccc-2d5ea447fed3

**Comment by bramkragten** [comment]
Does it work on iOS 16? (popover was introduced in iOS 17)

**Comment by timmo001** [comment]
macos with 16.5 (versions lower than 16.4 has no support of the ha-input implementation which uses [ElementInternals.setValidity()](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals/checkValidity#browser_compatibility)), no ios variant has this patched version



https://github.com/user-attachments/assets/a50f6c62-7cb4-45e3-a983-26434e6f2909

image

There are other flaws with this legacy browser, it might be browserstack related though - Dialogs have no scrim, copy doesnt show at all but toast works in normal views. pickers also have issues with closing outside (scrim) unless using esc or picking an item

File: src/components/ha-toast.ts [hunk 1]
```diff
@@ -1,11 +1,17 @@
...
+import { ifDefined } from "lit/directives/if-defined";
 import { fireEvent } from "../common/dom/fire_event";
 import { nextRender } from "../common/util/render-status";
 
+const SUPPORTS_POPOVER = globalThis?.HTMLElement?.prototype
+  ? Object.prototype.hasOwnProperty.call(
+      globalThis.HTMLElement.prototype,
+      "popover"
+    )
+  : false;
```
Comment (wendevlin) [inline src/components/ha-toast.ts]: you should put this into common

**Comment by timmo001** [comment]
> Does it work on iOS 12? (popover was introduced in iOS 17)

image

Doesnt even load in the simulator

File: src/components/ha-toast.ts (hunk 1 above)
Comment (timmo001) [reply src/components/ha-toast.ts]: Added

**Review by wendevlin — APPROVED** [review]
