### PR TITLE
Fix inability to leave scene creation page without saving

### LINKED ISSUE #28513: Impossible to leave new scene creation page without saving
### The problem

As described by the title of this issue, I report the impossibility to leave the page dedicated to a new scene creation, without saving the changes.
This happens both by clicking on the back button and selecting any of the sidebar link.

### What version of Home Assistant Core has the issue?

2025.12.2

### What was the last working version of Home Assistant Core?

_No response_

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

_No response_

### Link to integration documentation on our website

_No response_

### Diagnostics information

_No response_

### Example YAML snippet

```yaml

```

### Anything in the logs that might be useful for us?

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

When the confirmation dialog opens, it pushes a history state. The `_goBack()` method was calling `goBack()` immediately after the dialog resolved, but the dialog's history state hadn't been cleaned up yet. This caused `history.back()` to only pop the dialog state, not actually navigate to the previous page.

The fix waits for any open dialog to fully close and its history state to be cleaned up before navigating.

Used the same approach as we have for `navigate`

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #28513
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/common/navigate.ts [hunk 1]
```diff
@@ -68,9 +68,28 @@ export const navigate = async (
...
+    if (!closed) {
+      // eslint-disable-next-line no-console
+      console.warn("Navigation blocked, because dialog refused to close");
+      return;
+    }
+    // need to wait for history state to be updated in case a dialog was closed
+    await new Promise<void>((resolve) => {
+      setTimeout(resolve);
+    });
+    await goBack(fallbackPath, timestamp);
```
Comment (wendevlin) [inline src/common/navigate.ts]: We could create a function for this, it seems to be exactly the same as in `navigate`

**Review by wendevlin — APPROVED** [review]
