### PR TITLE
Card Picker: Fix Clicking cards

### LINKED ISSUE #5400: Card picker - Entities card preview interactive
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Sorry for poor title, didn't know how to best describe it.

When selecting the Entities card from the card picker, the toggles are controllable in the preview. This can result in a scenario where you're attempting to click on the card to select it, but you are accidentally toggling switches instead. 

image

This does not appear to be the case for any other cards in the picker. None of the previews appear to be interactive besides this one.

## Expected behavior

Just open card when clicked on, rather than controlling a toggle.

## Steps to reproduce

1. Open demo, configure UI mode
2. Add card
3. Click on the right side of the Entities card preview, chances are you will control a toggle rather than it selecting that card (see above image for where to click).

## Environment

- Home Assistant release with the issue: 0.107.7
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by zsarnett**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/editor/card-editor/hui-card-picker.ts [hunk 1]
```diff
@@ -242,6 +243,15 @@ export class HuiCardPicker extends LitElement {
           align-items: center;
           justify-content: center;
         }
+
+        .overlay {
+          position: absolute;
+          top: 0;
+          left: 0;
```
Comment (bramkragten) [inline src/panels/lovelace/editor/card-editor/hui-card-picker.ts:250]: not needed

File: src/panels/lovelace/editor/card-editor/hui-card-picker.ts [hunk 2]
```diff
@@ -242,6 +243,15 @@ export class HuiCardPicker extends LitElement {
...
+          width: 100%;
+          height: 100%;
+          z-index: 1;
```
Comment (bramkragten) [inline src/panels/lovelace/editor/card-editor/hui-card-picker.ts:253]: not needed I think?

File: src/panels/lovelace/editor/card-editor/hui-card-picker.ts (hunk 1 above)
Comment (zsarnett) [reply src/panels/lovelace/editor/card-editor/hui-card-picker.ts:250]: Not needed indeed

File: src/panels/lovelace/editor/card-editor/hui-card-picker.ts (hunk 2 above)
Comment (zsarnett) [reply src/panels/lovelace/editor/card-editor/hui-card-picker.ts:251]: This is needed. Otherwise I can still toggle

File: src/panels/lovelace/editor/card-editor/hui-card-picker.ts [hunk 3]
```diff
@@ -297,7 +305,12 @@ export class HuiCardPicker extends LitElement {
     }
 
     return html`
-      <div class="card" @click="${this._cardPicked}" .config="${cardConfig}">
+      <div class="card">
+        <div
+          class="overlay"
+          @click=${this._cardPicked}
+          .config=${cardConfig}
```
Comment (bramkragten) [inline src/panels/lovelace/editor/card-editor/hui-card-picker.ts:312]: You didn't have to move this, but it it fine.

**Review by bramkragten — APPROVED** [review]

File: src/panels/lovelace/editor/card-editor/hui-card-picker.ts (hunk 3 above)
Comment (zsarnett) [reply src/panels/lovelace/editor/card-editor/hui-card-picker.ts:312]: Gotcha I guess I didnt test with out changing. I just assumed it would be above it and not register the click on the lower element
