### PR TITLE
Fix Date Time Helper

### LINKED ISSUE #11356: Creating DateTime Helper through UI fails if left on default "what do you want to input:"
### The problem

If you create a DateTime Helper in the UI, and leave it on the default setting of "Date" it fails to create.
It seems that it is actually sent to a default of "null" until you click on "Time" then back on to "Date"

### What version of Home Assistant Core has the issue?

2021.12.4

### What was the last working version of Home Assistant Core?

_No response_

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Input DateTime

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/input_datetime/

### Example YAML snippet

```yaml
n/a
```

### Anything in the logs that might be useful for us?

```txt
Error in UI:

Entity needs at least a date or a time. Got {'name': 'test', 'icon': 'mdi:account', 'has_date': False, 'has_time': False}
```

### Additional information

If you click onto the radio button for Time, then back on to the Date radio button.
It creates as expected.

### PR DESCRIPTION
**Pull request by zsarnett**
## Proposed change

Changes the logic to auto select date on first load for DateTime Helpers

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #11356
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/helpers/forms/ha-input_datetime-form.ts [hunk 1]
```diff
@@ -35,6 +35,8 @@ class HaInputDateTimeForm extends LitElement {
           : item.has_time
           ? "time"
           : "date";
+      this._item.has_date =
+        !item.has_date && !item.has_time ? true : item.has_date;
```
Comment (spacegaier) [inline src/panels/config/helpers/forms/ha-input_datetime-form.ts:39]: Should this perhaps be above the `this._mode` determination right before?

Comment (balloob) [reply src/panels/config/helpers/forms/ha-input_datetime-form.ts:39]: Can't this check just be `mode != "time` ?

Comment (zsarnett) [reply src/panels/config/helpers/forms/ha-input_datetime-form.ts:39]: mode is not on the item

**Review by spacegaier — APPROVED** [review]
