### PR TITLE
Display zone name in state badge

### LINKED ISSUE #14953: Person badges with no label if different then home or away
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since update to 2023.1.0b1 beta, if person location is diferent then HOME or AWAY, the no label (zone name) is displayed.
If you click on badge, then proper info is displayed.
No badge label

### Describe the behavior you expected

I'd like to have it as it was, zone name is use s label for person badge.

### Steps to reproduce the issue

1. just stopped working after update to 2023.1.0b1 and not working still in 2023.1.0b4
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2023.1.0b4

### What was the last working version of Home Assistant Core?

core-2022.12.8

### In which browser are you experiencing the issue with?

Google Chrome 108.0.5359.125

### Which operating system are you using to run this browser?

Windows 10 19045.2364

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Zone name case was missing after #14691 PR

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #14953
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]

File: src/components/entity/ha-state-label-badge.ts [hunk 1]
```diff
@@ -223,6 +223,10 @@ export class HaStateLabelBadge extends LitElement {
     if (domainStateKey) {
       return this.hass!.localize(`state_badge.${domainStateKey}`);
```
Comment (bramkragten) [inline src/components/entity/ha-state-label-badge.ts:224]:
```suggestion
      return this.hass!.localize(`state_badge.${domainStateKey}`) || entityState.state;
```
