### PR TITLE
Attempt to fix picture-elements functionality broken in 2022.11

### LINKED ISSUE #14297: Picture Elements Card - missing overlaying elements
### The problem

I have a few Picture Elements cards configured to control my lights, but this is broken after upgrading to 2022.11.0 - images on top of the picture are now gone and nothing happens if I click on the spot where the dots (images) should be. Resources (images) are locally accessible.

Example:
image

There should be clickable dots on places circled with red:
image

Images are locally accessible:
image
image
image
image

Nothing in the logs. Restarted HA instance a few time and it does not help.
The same issue is present on my desktop PC (Firefox, Chrome, Edge), on my tablet (via browser and Android app) and mobile (Android app).

Mentioned [here](https://community.home-assistant.io/t/2022-11-a-heck-of-a-release/483295/45?u=c1c3r0).

### What version of Home Assistant Core has the issue?

core-2022.11.0

### What was the last working version of Home Assistant Core?

core-2022.10.5

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

_No response_

### Link to integration documentation on our website

_No response_

### Diagnostics information

_No response_

### Example YAML snippet

```yaml
elements:
  - entity: group.kuhinja
    image: /local/lightbulb-group(1).png
    state_image:
      'on': /local/lightbulb-group-outline(1).png
    style:
      left: 5%
      top: 8%
    tap_action:
      action: toggle
    type: image
  - entity: switch.kuhinja_pc
    image: /local/red1.png
    state_image:
      'on': /local/green1.png
    style:
      left: 23.3%
      top: 53.5%
    tap_action:
      action: toggle
    type: image
  - entity: switch.kuhinja_ikea
    image: /local/red1.png
    state_image:
      'on': /local/green1.png
    style:
      left: 39%
      top: 18.3%
    tap_action:
      action: toggle
    type: image
  - entity: switch.kuhinja_ikea
    image: /local/red1.png
    state_image:
      'on': /local/green1.png
    style:
      left: 80%
      top: 10%
    tap_action:
      action: toggle
    type: image
  - entity: switch.kuhinja_glavna
    image: /local/red1.png
    state_image:
      'on': /local/green1.png
    style:
      left: 62.8%
      top: 20.4%
    tap_action:
      action: toggle
    type: image
  - entity: switch.emillux2
    image: /local/red1.png
    state_image:
      'on': /local/green1.png
    style:
      left: 14%
      top: 81.5%
    tap_action:
      action: toggle
    type: image
image: /local/kuhinja1.jpg
type: picture-elements
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by smonesi**
## Proposed change

My attempt to fix the broken picture-element since 2022.11 (https://github.com/home-assistant/frontend/pull/14245).

I am not sure this is not breaking anything else, but it does seem to fix the issue reported by many users on picture-elements (see https://github.com/home-assistant/frontend/issues/14297) although I kept as much code as possible of https://github.com/home-assistant/frontend/pull/14245. Given that there was no code to test https://github.com/home-assistant/frontend/pull/14245 and the description was also a bit limited, I don't know how else to test the impacts.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

(see discussion in https://github.com/home-assistant/frontend/issues/14297)

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/14297

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/components/hui-image.ts [hunk 1]
```diff
@@ -193,8 +193,6 @@ export class HuiImage extends LitElement {
         style=${styleMap({
           paddingBottom: useRatio
             ? `${((100 * this._ratio!.h) / this._ratio!.w).toFixed(2)}%`
-            : !this._lastImageHeight
-            ? "56.25%"
```
Comment (bramkragten) [inline src/panels/lovelace/components/hui-image.ts:197]: instead of removing this, we should check if `this._lastImageHeight` is `undefined` instead of falsy

File: src/panels/lovelace/components/hui-image.ts [hunk 2]
```diff
@@ -206,7 +204,7 @@ export class HuiImage extends LitElement {
               : undefined,
         })}
         class="container ${classMap({
-          ratio: useRatio || !this._lastImageHeight,
+          ratio: useRatio,
```
Comment (bramkragten) [inline src/panels/lovelace/components/hui-image.ts:207]:
```suggestion
          ratio: useRatio || this._lastImageHeight === undefined,
```

File: src/panels/lovelace/components/hui-image.ts (hunk 1 above)
Comment (smonesi) [reply src/panels/lovelace/components/hui-image.ts]: 👍

File: src/panels/lovelace/components/hui-image.ts (hunk 2 above)
Comment (smonesi) [reply src/panels/lovelace/components/hui-image.ts]: 👍

**Review by bramkragten — APPROVED** [review]
