### PR TITLE
Set initial focus for some more dialogs

### LINKED ISSUE #10754: Modal dialogs need keyboard focus management
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For nearly all modal dialogs I can think of, the keyboard focus does not transfer to the dialog as it should for accessibility.  I need to to click or space bar once  to get the focus inside the dialog to be able to read it with a screen reader.  Furthermore, after closing a dialog with escape or button, keyboard focus is transferred all the way back to the beginning of the page DOM, instead of back to the button which opened the dialog as expected.

### Describe the behavior you expected

In general, these dialogs should all follow the [modal dialog design pattern in the W3C ARIA Authoring Practices](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal).  These design patterns have detailed notes on managing keyboard focus.

### Steps to reproduce the issue

For example, I might go to Configuration → Entities and:
1. Click on an entity to get it's settings dialog, and then click again to read it
2. Click the control button to get that dialog, then have to click again to read it
3. Click the attributes button, then have to click again to read them
4. Hit escape to get out, then have to navigate back to where I started

2.
3.
...
For example, I might go to Configuration → Entities and:
1. Click on an entity to get it's settings dialog, and then click again to read it
2. Click the control button to get that dialog, then have to click again to read it
3. Click the attributes button, then have to click again to read them
4. Hit escape to get out, then have to navigate back to where I started

### What version of Home Assistant Core has the issue?

Any

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Firefox & Chrome (latest stable)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

I suspect that the cause of this may be also causing lots of other "double action" keyboard issues throughout the UI, but I figured I'd keep this issue tight and to the point rather than jumping to that conclusion.

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

| Dialog Module | Initial Focus |
|:------ |:----:|
| dialog-add-user | Name or user field |
| dialog-system-log-detail | Log entry |
| dialog-statistics-fix-units-changed | Radio |
| dialog-statistics-fix-unsupported-unit-meta | Fix button |
| dialog-config-entry-system-options | First checkbox |
| dialog-mqtt-device-debug-info | First checkbox |

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: #10754 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

File: src/panels/config/logs/dialog-system-log-detail.ts [hunk 1]
```diff
@@ -104,7 +104,7 @@ class DialogSystemLogDetail extends LitElement {
               )}
             </ha-alert>`
           : ""}
-        <div class="contents">
+        <div class="contents" tabindex="-1" dialogInitialFocus>
```
Comment (bramkragten) [inline src/panels/config/logs/dialog-system-log-detail.ts:107]: Please add `outline: none` css to this div

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
