### PR TITLE
Handle delay templates properly + error handling tweaks

### LINKED ISSUE #8475: Automation editor corrupts template in delay action
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

I want to implement a random delay in the action of an automation. The docs suggest it is possible like this (https://www.home-assistant.io/docs/scripts/ , search for "random"). When I add this manually to `automations.yaml` it works. When I open the same automation in the UI the template is removed. When I save without touching that segment of the automation the template is also removed.

**Describe the behavior you expected**

To be able to edit the template AND that the template is correctly saved to `automations.yaml`.

**Steps to reproduce the issue**

1. Add this to `automations.yaml` and reload automations:
```yaml
- delay:
      seconds: '{{ range(1, 30)|random }}'
```
2. Open the automation in the editor and make a minor change (description or so). Save. It does not matter if I use `Edit with UI` or `Edit as YAML`. 
3. The following code is written to `automations.yaml`:
```yaml
- delay:
      hours: 0
      minutes: 0
      seconds:
      milliseconds: 0
```
2A. Edit with UI results in:
Screenshot 2021-02-27 at 09 36 32

2B. Edit as YAML results in:
Screenshot 2021-02-27 at 09 38 32

...

**What version of Home Assistant Core has the issue?**

core-2021.2.3

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

Firefox 86.0

**Which operating system are you using to run this browser?**

MacOS 11.2.1 on M1 Macbook air

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
- id: '1614349029131'
  alias: 'Occusim: random off (test)'
  description: x
  trigger:
  - at: '22:20:00'
    platform: time
  condition: []
  action:
  - delay:
      seconds: '{{ range(10, 20)|random }}'
  - service: light.turn_off
    data: {}
    entity_id: all
  - data:
      message: 'Occusim: lichten gaan uit'
    service: notify.telegram
  - data: {}
    entity_id: input_boolean.occupancy_simulation
    service: input_boolean.turn_off
  - delay: 00:00:10
  - service: light.turn_on
    data: {}
    entity_id: light.mbr_plafond_level
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: light.turn_off
    data: {}
    entity_id: light.mbr_plafond_level
  mode: single
```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

1. Detect if a delay action contains a template string. If so, then switch to YAML mode.
2. Prevent empty ul/li HTML elements if the config error has no actual error or warning messages (applies to both automation editor and HUI card editor).
3. Make "Visual editor" wording consistent between card editor and automation editor.

image

Open / minor issue: The 3 dot menu in the action card, is now a bit wider => horizontal scrollbar shown, when menu items are shown.

image

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/8475
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/automation/action/ha-automation-action-row.ts [hunk 1]
```diff
@@ -193,12 +193,16 @@ export default class HaAutomationActionRow extends LitElement {
...
           ${this._warnings
             ? html`<div class="warning">
-                UI editor is not supported for this config:
+                ${this.hass.localize("ui.errors.config.editor_not_supported")}:
                 <br />
-                <ul>
-                  ${this._warnings.map((warning) => html`<li>${warning}</li>`)}
-                </ul>
-                You can still edit your config in YAML.
+                ${this._warnings!.length > 0 && this._warnings![0] !== undefined
```
Comment (bramkragten) [inline src/panels/config/automation/action/ha-automation-action-row.ts:198]: Is this possible? When does it happen?

File: src/panels/config/automation/action/types/ha-automation-action-delay.ts [hunk 2]
```diff
@@ -20,39 +20,62 @@ export class HaDelayAction extends LitElement implements ActionElement {
...
-          hours: Number(parts[0]) || 0,
-          minutes: Number(parts[1]) || 0,
-          seconds: Number(parts[2]) || 0,
-          milliseconds: Number(parts[3]) || 0,
-        };
+      if (typeof this.action.delay === "string" || isNaN(this.action.delay)) {
+        const delayString = this.action.delay?.toString();
+        // Check for template string. Otherwise we assume time string
+        if (delayString.startsWith("{{")) {
+          templateDetected = true;
```
Comment (bramkragten) [inline src/panels/config/automation/action/types/ha-automation-action-delay.ts:30]:
```suggestion
fireEvent(
          this,
          "ui-mode-not-available",
          Error(
            this.hass.localize("ui.errors.config.no_template_editor_support")
          )
        )
return;
```

File: src/panels/config/automation/action/types/ha-automation-action-delay.ts [hunk 3]
```diff
@@ -20,39 +20,62 @@ export class HaDelayAction extends LitElement implements ActionElement {
...
-      };
+
+      if (
+        days?.toString().startsWith("{{") ||
+        hours?.toString().startsWith("{{") ||
+        minutes?.toString().startsWith("{{") ||
+        seconds?.toString().startsWith("{{") ||
+        milliseconds?.toString().startsWith("{{")
+      ) {
+        templateDetected = true;
```
Comment (bramkragten) [inline src/panels/config/automation/action/types/ha-automation-action-delay.ts:54]:
```suggestion
fireEvent(
          this,
          "ui-mode-not-available",
          Error(
            this.hass.localize("ui.errors.config.no_template_editor_support")
          )
        )
return;
```

File: src/panels/config/automation/action/types/ha-automation-action-delay.ts [hunk 4]
```diff
@@ -20,39 +20,62 @@ export class HaDelayAction extends LitElement implements ActionElement {
...
     if (typeof this.action.delay !== "object") {
-      if (isNaN(this.action.delay)) {
-        const parts = this.action.delay?.toString().split(":") || [];
-        data = {
-          hours: Number(parts[0]) || 0,
-          minutes: Number(parts[1]) || 0,
-          seconds: Number(parts[2]) || 0,
-          milliseconds: Number(parts[3]) || 0,
-        };
+      if (typeof this.action.delay === "string" || isNaN(this.action.delay)) {
```
Comment (bramkragten) [inline src/panels/config/automation/action/types/ha-automation-action-delay.ts:26]: Can we do this with a struct?

File: src/panels/config/automation/action/ha-automation-action-row.ts (hunk 1 above)
Comment (spacegaier) [reply src/panels/config/automation/action/ha-automation-action-row.ts:198]: When you fire the event `"ui-mode-not-available"` without any detailed `Error`. The error handling still creates an entry in `warnings` which is undefined. I tried to suppress that, but somehow failed.

File: src/panels/config/automation/action/types/ha-automation-action-delay.ts (hunk 4 above)
Comment (spacegaier) [reply src/panels/config/automation/action/types/ha-automation-action-delay.ts:26]: How do you mean?

File: src/panels/config/automation/action/ha-automation-action-row.ts (hunk 1 above)
Comment (bramkragten) [reply src/panels/config/automation/action/ha-automation-action-row.ts:198]: Something like?
```
    if (ev.detail && ev.detail instanceof Error) {
      this._warnings = handleStructError(this.hass, ev.detail).warnings;
    }
```

Comment (bramkragten) [reply src/panels/config/automation/action/ha-automation-action-row.ts:198]: You should not fire `ui-mode-not-available` without Error to begin with ofc...

File: src/panels/config/automation/action/types/ha-automation-action-delay.ts [hunk 5]
```diff
@@ -20,62 +21,45 @@ export class HaDelayAction extends LitElement implements ActionElement {
...
-    let templateDetected = false;
+
+    // Check for templates in action. If found, revert to YAML mode.
+    if (this.action && hasTemplate(JSON.stringify(this.action))) {
+      fireEvent(
+        this,
+        "ui-mode-not-available",
+        Error(this.hass.localize("ui.errors.config.no_template_editor_support"))
+      );
+    }
```
Comment (bramkragten) [inline src/panels/config/automation/action/types/ha-automation-action-delay.ts:32]: Let's do this in updated, and check if the action is changed, and not in render.

File: src/panels/config/automation/action/ha-automation-action-row.ts (hunk 1 above)
Comment (spacegaier) [reply src/panels/config/automation/action/ha-automation-action-row.ts:198]: Ideally not, but if someone did, then this will handle it. Your code proposal would prevent the error/info from being shown at all, which I think is not ideal.
