### PR TITLE
Fix race condition with picture-elements card custom elements

### LINKED ISSUE #18764: picture-elements will occasionally not display custom card elements
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Occasionally `custom:` cards used in `picture-elements` does no appear.

Video reproduction:
[before.webm](https://github.com/home-assistant/frontend/assets/1752370/60e1b048-4531-4c20-83d1-ae1e37aa476c)

### Describe the behavior you expected

All `custom:` cards used in `picture-elements` should appear.

### Steps to reproduce the issue

This tends to occur in chrome most often.

1. Add `custom:` card to dashboard. Preferably a complex card.
2. Add `picture-elements` card on dashboard
3. Add a `custom:` card to the `picture-elements` card.
4. Refresh the page a bunch of times. 
5. The `custom:` cards in the `picture-elements` is not visible.

See configuration example below.

When the custom cards do not appear, they are replaced with these error cards (which are also not visible). 
285662715-ab20155f-c0e1-4dc0-b916-76421115ad46

### What version of Home Assistant Core has the issue?

2023.12.0.dev0

### What was the last working version of Home Assistant Core?

None

### In which browser are you experiencing the issue with?

Chrome, all versions.

### Which operating system are you using to run this browser?

Ubuntu 23.10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

```yaml
title: House
views:
  - icon: mdi:home
    panel: false
    path: default_view
    title: Home
    badges: []
    cards:
      - type: picture-elements
        image: /local/transparent_490x275.gif
        elements:
          - type: custom:mushroom-title-card
            style:
              transform: translate(0px, 0px)
              left: 0em
              top: '-1.0em'
              width: 100%
            title: Always Visible 1
      - type: custom:auto-entities
        card:
          type: entities
          show_empty: false
          state_color: true
        filter:
          include:
            - attributes:
                device_class: door
              state: 'on'
        show_empty: false
        sort:
          method: name
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: Always Visible 2
      - type: picture-elements
        image: /local/transparent_490x275.gif
        elements:
          - type: custom:mushroom-title-card
            style:
              transform: translate(0px, 0px)
              left: 0em
              top: '-1.0em'
              width: 100%
            title: Occasionally Visible 1
```

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

Originally reported and investigated here: https://github.com/piitaya/lovelace-mushroom/issues/1161

### PR DESCRIPTION
**Pull request by vangorra**
## Proposed change

`picture-elements` is rendering it's `elements` during the config phase of initialization. Due to a race condition, there are times where `custom:` cards listed as `elements` are not loaded because the supporting custom card code is not loaded yet.

Before the patch:
[before.webm](https://github.com/home-assistant/frontend/assets/1752370/30e39a54-b999-4ff3-ba0a-625e24584e35)
Notice how `Occasionally Visible` is loaded sometimes.

After the path:
[after.webm](https://github.com/home-assistant/frontend/assets/1752370/7f792985-b064-41c4-9990-741d3d3cf679)
Notice how `Occasionally Visible` is loaded all the time.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
title: House
views:
  - icon: mdi:home
    panel: false
    path: default_view
    title: Home
    badges: []
    cards:
      - type: picture-elements
        image: /local/transparent_490x275.gif
        elements:
          - type: custom:mushroom-title-card
            style:
              transform: translate(0px, 0px)
              left: 0em
              top: '-1.0em'
              width: 100%
            title: Always Visible 1
      - type: custom:auto-entities
        card:
          type: entities
          show_empty: false
          state_color: true
        filter:
          include:
            - attributes:
                device_class: door
              state: 'on'
        show_empty: false
        sort:
          method: name
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: Always Visible 2
      - type: picture-elements
        image: /local/transparent_490x275.gif
        elements:
          - type: custom:mushroom-title-card
            style:
              transform: translate(0px, 0px)
              left: 0em
              top: '-1.0em'
              width: 100%
            title: Occasionally Visible 1
```

## Additional information

- This PR fixes or closes issue: fixes #18764
- This PR is related to issue or discussion: https://github.com/piitaya/lovelace-mushroom/issues/1161
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/hui-picture-elements-card.ts [hunk 1]
```diff
@@ -77,16 +77,6 @@ class HuiPictureElementsCard extends LitElement implements LovelaceCard {
     }
 
     this._config = config;
-
-    this._elements = this._config.elements.map(
-      (elementConfig: LovelaceElementConfig) => {
-        const element = createStyledHuiElement(elementConfig);
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-picture-elements-card.ts:83]: This should be fixed in a different way, if custom elements are not loaded yet, we will listen for them to be loaded. When it is loaded, the element will fire an event, `ll-rebuild` when that event is received the element should be recreated.

That recreate logic seems to be missing here, it should be the same as for a cards:
https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/views/hui-view.ts#L74-L84

File: src/panels/lovelace/cards/hui-picture-elements-card.ts [hunk 2]
```diff
@@ -165,6 +160,35 @@ class HuiPictureElementsCard extends LitElement implements LovelaceCard {
...
+      (ev) => {
+        ev.stopPropagation();
+        this._rebuildCard(element, cardConfig);
+      },
+      { once: true }
+    );
+    return element;
+  }
+
+  private _rebuildCard(
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-picture-elements-card.ts:180]:
```suggestion
  private _rebuildElement(
```

File: src/panels/lovelace/cards/hui-picture-elements-card.ts [hunk 3]
```diff
@@ -165,6 +160,35 @@ class HuiPictureElementsCard extends LitElement implements LovelaceCard {
       }
     `;
   }
+
+  private _createLovelaceCard(cardConfig: LovelaceElementConfig): LovelaceCard {
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-picture-elements-card.ts:164]:
```suggestion
  private _createElement(elementConfig: LovelaceElementConfig): LovelaceElement {
```

**Review by bramkragten — APPROVED** [review]
