### PR TITLE
Fix cast navigation on none default dashboard

### LINKED ISSUE #5613: HA Cast navigation only works for main dashboard
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Home Assistant Cast supports navigating to other views on a loaded Lovelace dashboard. This however only works on the default dashboard (`/lovelace`/).

https://github.com/home-assistant/frontend/blob/4f518cac2c78e8d57e955ca6fdf06ddb72051dbc/cast/src/receiver/layout/hc-main.ts#L98-L104

## Expected behavior

This should work for all dashboards. Clicking a link like `/playground/media` should open my dashboard for `/playground` with the `media` view loaded.

## Steps to reproduce

- Create dashboard on `/playground` with 2 views, `home` and `media`
- Add an entities card with a `weblink` special row to `home` that links to `/playground/media`
- Cast it to HA Cast
- Tap on the link

## Work around

If you know the device it's being cast on, you can use the `cast.show_lovelace_view` service with a `call-service` special row for the entities card.

## Environment

- Home Assistant release with the issue: 0.108
- Last working Home Assistant release (if known): -
- Browser and browser version: all
- Operating system: all

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes #5613

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: build-scripts/gulp/cast.js [hunk 1]
```diff
@@ -13,7 +13,6 @@ gulp.task(
   gulp.series(
     async function setEnv() {
       process.env.NODE_ENV = "development";
-      process.env.IS_CAST = "true";
```
Comment (balloob) [inline build-scripts/gulp/cast.js:16]: Still used in `build-scripts/gulp/translations.js:279`

**Review by balloob — APPROVED** [review]

File: build-scripts/gulp/cast.js (hunk 1 above)
Comment (balloob) [reply build-scripts/gulp/cast.js:16]: I'm thinking now, I think that we can remove the old translations for cast now that we mix in backend. You can remove that whole hack.
