### PR TITLE
Re-add success/failure indicator on call service button in dev tools

### LINKED ISSUE #8562: Call Service button in Developer Tools does not change color to indicate call status
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The `Call Service` button used to turn green to indicate that a call completed successfully. It no longer does so.

### Describe the behavior you expected

When a service call completes successfully, give the user an indication that the call was successful (could be turning the button green, could be a toast). I recall their being feedback on the button when the call failed too but I could be wrong about that.

### Steps to reproduce the issue

1. Make a successful service call
2. Note that there is no feedback in the UI that the call was successful
3.
...

### What version of Home Assistant Core has the issue?

core-2021.3.1

### What was the last working version of Home Assistant Core?

2021.2.x

### In which browser are you experiencing the issue with?

Google Chrome 88.0.4324.182, HA Companion app (mobile and desktop)

### Which operating system are you using to run this browser?

macOS Catalina

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

### PR DESCRIPTION
**Pull request by raman325**
## Proposed change
It seems that the feedback that we used to get through the call service button in developer tools to indicate a successful or failed call was removed as part of #8410 . This PR adds it back in - if it was intentional I am not clear on why since it seems to work with no loss in functionality elsewhere

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/8562

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/developer-tools/service/developer-tools-service.ts [hunk 1]
```diff
@@ -295,12 +299,14 @@ class HaPanelDevService extends LitElement {
...
 
-  private async _callService() {
+  private async _callService(ev) {
+    const button = ev.currentTarget;
     if (!this._serviceData?.service) {
       return;
     }
     try {
       await callExecuteScript(this.hass, [this._serviceData]);
+      button.actionSuccess();
```
Comment (ludeeus) [inline src/panels/developer-tools/service/developer-tools-service.ts:309]: Move this to after the try block and add a return in the catch section.
Now it will provide no feedback for services that are expected to stop the webserver

**Review by ludeeus — CHANGES_REQUESTED** [review]

**Review by bramkragten — DISMISSED** [review]

File: src/panels/developer-tools/service/developer-tools-service.ts [hunk 2]
```diff
@@ -295,7 +299,8 @@ class HaPanelDevService extends LitElement {
     }
   );
 
-  private async _callService() {
+  private async _callService(ev) {
+    const button = ev.currentTarget;
```
Comment (bramkragten) [inline src/panels/developer-tools/service/developer-tools-service.ts:303]:
```suggestion
    const button = ev.currentTarget as HaProgressButton;
```

Comment (raman325) [reply src/panels/developer-tools/service/developer-tools-service.ts:303]: `HaProgressButton` is not exported so we can't use it here. Should I export it as part of the change?

**Review by bramkragten — APPROVED** [review]
