### PR TITLE
Data tables: keep "Actions" as the last column

### LINKED ISSUE #28099: Fix misaligned three-dots menu in tables
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When I disable and enable all of the columns the three-dots menu gets incorrectly placed in front of the columns:

https://github.com/user-attachments/assets/dd9a0473-65e6-47b8-96e7-2cf6c62d0fd7

### Describe the behavior you expected

Three-dots menu should be always at the end of a table list-item.

### Steps to reproduce the issue

1. Open any table
2. Edit visible columns and hide all of them
3. Show at least one column
Result: Three-dots menu jumps in front of the columns.

### What version of Home Assistant Core has the issue?

2025.11.3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ildar170975**
## Proposed change

Additional details - https://github.com/home-assistant/frontend/issues/28099

In data tables, currently it is possible to place a column after an “Actions” column (which is supposed to be fixed as the last column).
Proposing a new flag `last_fixed` in `DataTableColumnData` which is sorted as the last.

Notes:
1. The proposed `last_fixed` flag can be used not only for “Actions” but for any other column which is needed to be fixed as last.
2. Not affected `developer-tools-statistics`, the “actions” column there is moveable (which is great).

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/28099
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by karwosts** [comment]
Instead of additional attributes (which can be dissonant with the existing movable attribute), maybe can just be inferred from being `movable: false`, and the final column in the definition?

**Comment by ildar170975** [comment]
> and the final column in the definition?

Then it will depend on an order in which a user placed columns when defined them.
(also, a rule "always place a code in the end for a column to be fixed " could be easily forgotten)

**Comment by marcinbauer-ohf** [comment]
It's fixed, but I would hide the "Actions" row altogether. It's not configurable in any way, it's just a default part of the row.

**Comment by ildar170975** [comment]
> but I would hide the "Actions" row altogether

Unclear, what do you mean by "actions row", can you post a screenshot?
Do you want to get this row removed from here?

image

Agree absolutely.
But:
1. In the proposed PR it is not the "actions" column which is always fixed to the right side (in LTR). It is an entry with `last_fixed: true` property; and it is set for the "actions" column. Means - the "actions" word is not hard-coded.
2. Imagine that some tables (incl. tables with "actions" column) in future may have one more column always fixed to the right (LTR). It could be some "very important column" which is supposed to be always fixed. In this case we can set `last_fixed: true` for this column to get the desired effect.
3. But - in the dialog we still want to NOT SHOW the "actions" entry (as I understood you from [here](https://github.com/home-assistant/frontend/pull/29364#issuecomment-3846098598)) and still SHOW that "very important column" (fixed, not moveable, not hideable). If you are agree with that - then in the dialog we need to add an additional logic like "if it is `actions` - do not show".

@marcinbauer85 - what do you think?

Update 12.02.26: simplified, all "lastFixed" entries (currently - "actions" only) will be not shown in the dialog.

File: src/components/data-table/ha-data-table.ts [hunk 1]
```diff
@@ -86,6 +86,7 @@ export interface DataTableColumnData<T = any> extends DataTableSortColumnData {
   flex?: number;
   forceLTR?: boolean;
   hidden?: boolean;
+  last_fixed?: boolean;
```
Comment (MindFreeze) [inline src/components/data-table/ha-data-table.ts]: The others are camelCase but this is snake_case

Comment (ildar170975) [reply src/components/data-table/ha-data-table.ts]: fixed

**Comment by marcinbauer-ohf** [comment]
@ildar170975 Yes I ment to remove the Actions list item from the edit columns dialog. This is just part of the UI of a data-table row (at least in Automations - we could also use it in other data-tables).
I don't see why we'd need a fixed column other than an overflow one which are the "actions". Data tables are ment to be flexible and customizable, but actions are key there.

Thanks!

**Comment by marcinbauer-ohf** [comment]
Could you please take a look at this sizing bug on mobile? It's when you have more than one column enabled:
https://github.com/user-attachments/assets/503e4434-3dea-4fa1-90e6-277ce4486d22
This is on production.

**Comment by ildar170975** [comment]
> I don't see why we'd need a fixed column other than an overflow one which are the "actions"

Could be needed in future. It will be possible to add the functionality which I described when needed.

**Comment by ildar170975** [comment]
> Could you please take a look at this sizing bug on mobile?

Will check. But I do not think this is related to this PR.
Update: I see the glitch, on it.

**Comment by ildar170975** [comment]
@marcinbauer85 
There are issues with data tables at least for Automations, Scenes & Scripts (definitely not Entities) - and I see it on untouched 2026.2:

image

1. Open a data table on mobile.
2. Open table settings, unhide "Assistants".
3. Swipe the table to the left.
4. The table is moved to the left along with a header.

Not sure if it is related to the glitch you reported.
Still investigating.

**Comment by ildar170975** [comment]
@marcinbauer85 
> Could you please take a look at this sizing bug on mobile?

I double checked & reproduced this bug w/o this PR.
With this PR the bug is just more obvious since you see the "actions" 3-dots beyond the right border - because with this PR this "actions" column is always the last.
W/o this PR - the "actions" column may not be the last, and you just see a horiz scrollbar & empty area on the right (which is a continuation of the last column).

I will try to investigate the issue; but as I said it is not related to this PR.

Just a guess, the glitch may be caused by an "Assistants" column with fixed "min/max width = 160px", a short presentation in "Automations" with "icon + name + assistants + actions" causes a scrollbar.
To confirm that, I commented this line in "assistants-table-column.ts":
```
    title: localize("ui.panel.config.generic.headers.assistants"),
    type: "flex",
    // defaultHidden: !visible,
    sortable: true,
    showNarrow: true,
    minWidth: "160px",
    maxWidth: "160px",
```
and the scrollbar is shown initially right after the 1st opening the Automations data table:

Untitled Project

**Comment by ildar170975** [comment]
Narrowed down the "Assistants" column, became much better, but will still cause an overflow if many columns are unhidden on a mobile in a portrait orientation. (although particularly for "Automations" it is not possible since all other columns have `showNarrow: false`)

**Comment by marcinbauer-ohf** [comment]
It's better, but in a longer run I see the assistants column to be improved so it takes less space.

**Comment by ildar170975** [comment]
> I see the assistants column to be improved so it takes less space.

It is now quite compact, no?

image

Spacings between icons can be decreased from 8px to 4px if it matters:
image

**Comment by ildar170975** [comment]
@marcinbauer85 
Sorry, I am not getting what to do next. If you disapprove this PR, just close it please. Otherwise the PR is hanging.
Very same about https://github.com/home-assistant/frontend/pull/28951 which is hanging too.
I need to know what to do next)))).

**Comment by silamon** [comment]
From reading the comments, I guess it needs a code review to get accepted.

**Comment by marcinbauer-ohf** [comment]
The Assistants column is what is breaking this, which wasn't part of this PR so all is good here. In next PRs we can think of fixing this, but it's not that of a priority. Thanks ildar :)

**Comment by ildar170975** [comment]
@marcinbauer85 
> The Assistants column is what is breaking this

Thanks for the feedback! But honestly I think I fixed this?
With "Spacings between icons can be decreased from 8px to 4px if it matters" as was proposed - it looks like:
image
and I cannot see issues - at least with iPhone 15...

File: src/panels/config/voice-assistants/expose/assistants-table-column.ts [hunk 2]
```diff
@@ -21,12 +21,12 @@ export function getAssistantsTableColumn<T>(
...
     sortable: true,
     showNarrow: true,
-    minWidth: "120px",
-    maxWidth: "120px",
+    minWidth: "112px",
+    maxWidth: "112px",
     valueColumn: "assistants_sortable_key",
     template: (entry: any) =>
       html`${entry.assistants.length !== 0
-        ? html`<div style="display: flex; gap: var(--ha-space-2);">
```
Comment (bramkragten) [inline src/panels/config/voice-assistants/expose/assistants-table-column.ts]: I don't think we should make it 4px personally

File: src/panels/config/helpers/ha-config-helpers.ts
Comment (bramkragten) [inline src/panels/config/helpers/ha-config-helpers.ts]: These can be removed now I think?

File: src/panels/config/voice-assistants/expose/assistants-table-column.ts (hunk 2 above)
Comment (ildar170975) [reply src/panels/config/voice-assistants/expose/assistants-table-column.ts]: Actually, even with 4px there is a chance that we'll see a scrollbar:
image
if "Editable" column is shown (it is empty on the screenshot above - but it is shown & takes a space).

When the 'Editable" column is not shown - no scrollbar:
image

Next, with 8px - even with hidden "Editable", a scrollbar is shown, a scrollable area is only a few pixels wider than needed:
image

So, I would vote for 4px.
What do you think?

File: src/panels/config/helpers/ha-config-helpers.ts
Comment (ildar170975) [reply src/panels/config/helpers/ha-config-helpers.ts]: Yes!

**Review by silamon — APPROVED** [review]
