### PR TITLE
Fix/dhcp config network sort

### LINKED ISSUE #25490: Sorting IP addresses uses numerical sort
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

the DHCP network discovery page offers the option of sorting on "IP address" but its a numerical sort.

### Describe the behavior you expected

IP aware sort.

### Steps to reproduce the issue

1. settings -> network -> Network discovery DHCP browser
2. sort on IP Address
3.
...

### What version of Home Assistant Core has the issue?

core-2025.5.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Chrome 136.0.7103.93 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by miecielica**
## Proposed change

This PR improves the sorting of IP addresses in the DHCP settings data table. Previously, IP addresses were sorted as strings, which led to incorrect order (e.g., `192.168.1.100` appearing before `192.168.1.2`). This fix applies proper numeric sorting for IP addresses, providing a more intuitive and correct display order.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes [#25490](https://github.com/home-assistant/frontend/issues/25490)
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/common/string/compare.ts [hunk 1]
```diff
@@ -33,6 +33,22 @@ export const stringCompare = (
   return fallbackStringCompare(a, b);
 };
 
+export const ipCompare = (a: string, b: string) => {
+   const num1 = Number(
+     a
+       .split(".")
+       .map((num) => `000${num}`.slice(-3))
```
Comment (bramkragten) [inline src/common/string/compare.ts]: Why not use `padStart`?

File: src/common/string/compare.ts [hunk 2]
```diff
@@ -33,6 +33,22 @@ export const stringCompare = (
   return fallbackStringCompare(a, b);
 };
 
+export const ipCompare = (a: string, b: string) => {
```
Comment (bramkragten) [inline src/common/string/compare.ts:37]: Should this function also take ipv6 addresses into account? Otherwise you should use a different name for the function and column I think?

File: src/common/string/compare.ts (hunk 1 above)
Comment (miecielica) [reply src/common/string/compare.ts]: Changed to better readable padStart

File: src/common/string/compare.ts (hunk 2 above)
Comment (miecielica) [reply src/common/string/compare.ts:37]: Renamed the method, because the arp, dhcp lookup should only retrieve ipv4 addresses.

File: src/panels/config/integrations/integration-panels/dhcp/dhcp-config-panel.ts [hunk 3]
```diff
@@ -60,6 +60,7 @@ export class DHCPConfigPanel extends SubscribeMixin(LitElement) {
           title: localize("ui.panel.config.dhcp.ip_address"),
           filterable: true,
           sortable: true,
+          type: "ipv4",
```
Comment (MindFreeze) [inline src/panels/config/integrations/integration-panels/dhcp/dhcp-config-panel.ts]: Do we know if it's always v4 ? The integration's docs don't specify

Comment (miecielica) [reply src/panels/config/integrations/integration-panels/dhcp/dhcp-config-panel.ts]: I also didn't find information regarding the format of the retrieved IP addresses. I enhanced the sort to include v6 and added a test

**Review by MindFreeze — APPROVED** [review]
Very nice. Thank you!
