### PR TITLE
Ensure forecast temperatures are properly positioned + show em-dash when n/a

### LINKED ISSUE #9063: Weather forecast temperatures not displaying properly in Lovelace Card
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Follow-up to #9047 and #9055. #9055 fixed the issue with weather forecast detailed pop-up. However, the lovelace card is still displaying the low temeperature as a high temperature (Friday).

### Describe the behavior you expected

Screen Shot 2021-04-30 at 11 22 44 PM

### Steps to reproduce the issue

See screenshot.

### What version of Home Assistant Core has the issue?

dev

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome Version 90.0.4430.93

### Which operating system are you using to run this browser?

macOS Big Sur (11.3)

### State of relevant entities

```txt
temperature: 5.5
humidity: 56
pressure: 1014
wind_bearing: 304
wind_speed: 30
visibility: 24.1
attribution: Data provided by Environment Canada
forecast: 
- datetime: '2021-04-30T23:28:36.104853-04:00'
  condition: rainy
  precipitation_probability: 30
  temperature: null
  templow: 0
- datetime: '2021-05-01T23:28:36.104886-04:00'
  temperature: 14
  templow: 11
  condition: rainy
  precipitation_probability: 60
- datetime: '2021-05-02T23:28:36.104930-04:00'
  temperature: 15
  templow: 9
  condition: rainy
  precipitation_probability: 40
- datetime: '2021-05-03T23:28:36.104954-04:00'
  temperature: 13
  templow: 10
  condition: rainy
  precipitation_probability: 0
- datetime: '2021-05-04T23:28:36.104982-04:00'
  temperature: 14
  templow: 7
  condition: rainy
  precipitation_probability: 0
- datetime: '2021-05-05T23:28:36.105031-04:00'
  temperature: 15
  templow: 4
  condition: partlycloudy
  precipitation_probability: 0

friendly_name: Toronto
```

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

PR- https://github.com/home-assistant/core/pull/49826 merged on top of dev. Running in dev container.

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Ensure forecast temperatures are correctly positioned even when null. In that case we show a long dash ("em dash") to clearly show that there is no data here.

Logic works for both missing/null low and high temperatures.

@bramkragten I know that at least initially in PR #9055 you were not a fan, but perhaps those screenshots can convince you 😄. I really think having an empty space in a structured "table" display such as the forecasts looks wrong (like a rendering bug).

image

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9063
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/more-info/controls/more-info-weather.ts [hunk 1]
```diff
@@ -187,6 +187,7 @@ class MoreInfoWeather extends LitElement {
                             this.hass.locale
                           )}
                         </div>
+                        <div class="templow">—</div>
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-weather.ts:190]: This is weird, for an integration that doesn't provide min temps, we now just don't show the column, what is good I think, now we will show a `-` on each row?

If we want to show a `-` we should only do it if one of the other rows has a min temp value.

Comment (michaeldavie) [reply src/dialogs/more-info/controls/more-info-weather.ts:190]: This is a bit of an edge case; in the evening Canada's weather service stops providing a high temperature for the current day, but still provides a low for the night ahead. This is what is looks like on their website:

Screen Shot 2021-05-20 at 8 32 13 PM

**Comment by michaeldavie** [comment]
@spacegaier Are you ready to move this out of draft? The associated [PR](https://github.com/home-assistant/core/pull/49826) in `core` was merged into `dev` yesterday.

**Comment by spacegaier** [comment]
> 
> 
> @spacegaier Are you ready to move this out of draft? The associated [PR](https://github.com/home-assistant/core/pull/49826) in `core` was merged into `dev` yesterday.

I seem to remember that there is an open point I need to change or at least double check based on Bram's review.

**Comment by spacegaier** [comment]
Will tackle that soon-ish...

**Comment by MatthewFlamm** [comment]
NWS avoids all this by providing the data as it comes from the API, i.e. one day and one night forecast separately.  Thus there are two separate entries per day until the day is over.  Then there is a single night forecast followed by the normal set of two entries per day.

File: src/dialogs/more-info/controls/more-info-weather.ts (hunk 1 above)
Comment (spacegaier) [reply src/dialogs/more-info/controls/more-info-weather.ts]: I adjusted the logic now to check if we have at least one of `templow` or `temperature`, otherwise we hide the column (or row in the more-info) as before.

File: src/dialogs/more-info/controls/more-info-weather.ts [hunk 2]
```diff
@@ -169,48 +175,49 @@ class MoreInfoWeather extends LitElement {
...
-                        </div>
-                      `
-                    : ""}
-                  <div class="temp">
-                    ${this._showValue(item.temperature)
-                      ? `${formatNumber(item.temperature, this.hass.locale)}
-                    ${getWeatherUnit(this.hass, "temperature")}`
+            ${this.stateObj.attributes.forecast.map((item) =>
+              this._showValue(item.templow) || this._showValue(item.temperature)
+                ? html` <div class="flex">
```
Comment (zsarnett) [inline src/dialogs/more-info/controls/more-info-weather.ts:180]:
```suggestion
                ? html`<div class="flex">
```

File: src/panels/lovelace/cards/hui-weather-forecast-card.ts [hunk 3]
```diff
@@ -288,69 +281,76 @@ class HuiWeatherForecastCard extends LitElement implements LovelaceCard {
...
+                          </div>
+                          <div class="templow">
+                            ${this._showValue(item.templow)
+                              ? html`${formatNumber(
+                                  item.templow!,
+                                  this.hass!.locale
+                                )}°`
+                              : hourly
+                              ? ""
+                              : "—"}
```
[the remark this answers is not in the document]
Comment (spacegaier) [reply src/panels/lovelace/cards/hui-weather-forecast-card.ts:349]: Hourly forecasts usually do not have a low temperature, so we would have a lot of dashes which looks weird. Also this keeps things more in line with how they were before when we did not have any dashes at all.

**Review by zsarnett — APPROVED** [review]
