### PR TITLE
Fix browser language detection for region specific languages (#8982)

### LINKED ISSUE #8982: When default language is set to a hyphenated locale (e.g. en-US), the frontend will choose the first non-hyphenated language in the translation list
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I noticed that when I went to install, as well as when I go to the login screen my logins were in Spanish.  I did some debugging and found that the issue is that my default language is hyphenated (en-US), and the system was picking the first non-hyphenated langauge that it finds in the translation list.

navigator.languages = 
0: "en-US"
1: "es-US"
2: "es"
3: "fr-FR"
4: "fr"

in getLocalLanguage (src/util/hass-translation.ts) it returns the first language that it finds in the list, but en-US isn't in the list. 

 if (navigator.languages) {
    for (const locale of navigator.languages) {
      language = findAvailableLanguage(locale);
      if (language) {
        return language;
      }
    }
  }
  
  It only falls back to using the first language or accepting the first part of a hyphenated language as a last resort before defaulting to English:
  
  language = findAvailableLanguage(navigator.language);
  if (language) {
    return language;
  }
  if (navigator.language && navigator.language.includes("-")) {
    language = findAvailableLanguage(navigator.language.split("-")[0]);
    if (language) {
      return language;
    }
  }

### Describe the behavior you expected

I expect the software to respect my language choice in my browser, even if it is a localised version of the language.

### Steps to reproduce the issue

1.  Set your language list (in Chrome, for example) as follows:
English (United States)
Spanish

2. Navigate to the login page, and it will show in Spanish

### What version of Home Assistant Core has the issue?

2021.4.6

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome Version 90.0.4430.85 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

macOS Catalina 10.15.7

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.

```

### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by rmogstad**
## Proposed change

Detect hyphenated languages (e.g. en-US) as we are looking through the list of browser languages, rather than as a separate step.  This prevents it from picking a later language that is non-hyphenated instead of using the preferred language.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #8982
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/util/hass-translation.ts [hunk 1]
```diff
@@ -88,19 +88,18 @@ export function getLocalLanguage() {
...
   language = findAvailableLanguage(navigator.language);
   if (language) {
     return language;
   }
-  if (navigator.language && navigator.language.includes("-")) {
-    language = findAvailableLanguage(navigator.language.split("-")[0]);
-    if (language) {
-      return language;
-    }
-  }
```
Comment (bramkragten) [inline src/util/hass-translation.ts:102]: I think adding it to `navigator.languages` makes sense, but we should not remove it here? We should instead make a helper function for:

```ts
      language = findAvailableLanguage(locale);
      if (language) {
        return language;
      }
      if (locale.includes("-")) {
        language = findAvailableLanguage(locale.split("-")[0]);
        if (language) {
          return language;
        }
      }
```

Comment (rmogstad) [reply src/util/hass-translation.ts:102]: OK, I see.  I misunderstood what navigator.language was.  I will make a method and call it in both places.

Comment (rmogstad) [reply src/util/hass-translation.ts:102]: I made a change that is a little different.  I couldn't think of a good name for the helper function, and it seemed like something we would want to always check when searching for an available translation, so I added it to that function.

I'll understand if you prefer not to have the recursive call there and want me to break it out differently.  

This is my first time doing a CR on github, first time submitting to HA (or any OS project, for that matter), and first time working with TS, so I'm not super familiar with the industry best practices, nor with the project best practices.  I am more than happy to make changes to make it 

I am in the discord (@Zondebok) if you want to discuss directly.

File: src/util/hass-translation.ts [hunk 2]
```diff
@@ -36,9 +36,21 @@ export function findAvailableLanguage(language: string) {
...
   );
+  if (translation) {
+    return translation;
+  }
+
+  if (language.includes("-")) {
+    translation = findAvailableLanguage(language.split("-")[0]);
+    if (translation) {
+      return translation;
+    }
```
Comment (bramkragten) [inline src/util/hass-translation.ts:50]:
```suggestion
    return findAvailableLanguage(language.split("-")[0]);
```

File: src/util/hass-translation.ts [hunk 3]
```diff
@@ -36,9 +36,21 @@ export function findAvailableLanguage(language: string) {
...
+  }
+
+  return null;
```
Comment (bramkragten) [inline src/util/hass-translation.ts:53]:
```suggestion
  return undefined;
```

File: src/util/hass-translation.ts (hunk 2 above)
Comment (rmogstad) [reply src/util/hass-translation.ts:50]: I assume that the next change is the preferred one?  I think this would create an infinite loop (I did try to figure out a way to end like this though :) )

Comment (bramkragten) [reply src/util/hass-translation.ts:50]: It will not create a loop, as it first checks if it has an `-`, the second run can never have a `-`.

Comment (rmogstad) [reply src/util/hass-translation.ts:50]: Sure, I see.  I was only looking at it in this context and forgetting the if around it.

**Comment by rmogstad** [comment]
should I squash/rebase this at some point?

**Review by bramkragten — APPROVED** [review]

File: src/util/hass-translation.ts [hunk 4]
```diff
@@ -36,9 +36,18 @@ export function findAvailableLanguage(language: string) {
     return LOCALE_LOOKUP[langLower];
   }
 
-  return Object.keys(translationMetadata.translations).find(
+  let translation = Object.keys(translationMetadata.translations).find(
```
Comment (bramkragten) [inline src/util/hass-translation.ts:39]:
```suggestion
  const translation = Object.keys(translationMetadata.translations).find(
```
