### PR TITLE
Convert cover UI to Lit + ensure proper tilt rendering

### LINKED ISSUE #9222: The more-info-cover dialog does not properly support tilt control for one-way communication protocols
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Currently the only way to display the tilt control UI for covers is to support setting tilt position. There are covers that use one-way communication protocols (such as Somfy RTS venetian blinds) which support tilt control but not tilt position. Neither of the current options for them works well:

add

-  SUPPORT_SET_TILT_POSITION to supported_features without actually supporting it. The tilt position slider does nothing.
- do not add SUPPORT_SET_TILT_POSITION to supported_features. Tilt control UI is not shown at all. Tilt can be controlled with services but not through UI.
- add SUPPORT_SET_TILT_POSITION to supported_features, and build support for it. Not practical because you have to guestimate the device current position and it depends to too many unknowns such as using a physical remote or buttons, the actual setting of the stop/my button, etc.

### Describe the behavior you expected

The tilt position slider should be shown or not depending on SUPPORT_SET_TILT_POSITION only. The tilt open, tilt close, and tilt stop buttons should be visible depending on SUPPORT_OPEN_TILT, SUPPORT_CLOSE_TILT, and SUPPORT_STOP_TILT respectively, independently from the tilt position slider.

### Steps to reproduce the issue

The issue came up when adding support for RFY (Somfy RTS) venetian blinds tilt control - home-assistant/core#44309

### What version of Home Assistant Core has the issue?

core-2021.5.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

This is a copy of #8074 which was automatically closed without any action on it.

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Originally, I only wanted to fix the reported issue, but then it quickly turned into a Lit con version and the addition of a demo page to cover all the different combinations.

**Note**: I marked in the coding changes what was part of the actual issue fix. Everything else is just due to the Lit conversion (and cleanup to simplify some coding => even with the newly added gallery demo this PR only slightly increases the overall LOC).

image

image

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9222
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/more-info/controls/more-info-cover.ts [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+  supportsSetPosition,
+  supportsSetTiltPosition,
+} from "../../../data/cover";
+import { HomeAssistant } from "../../../types";
+
+const FEATURE_CLASS_NAMES = {
+  4: "has-set_position",
+  16: "has-open_tilt",
+  32: "has-close_tilt",
+  64: "has-stop_tilt",
```
Comment (spacegaier) [inline src/dialogs/more-info/controls/more-info-cover.ts:20]: Part of the actual issue fix, to ensure we have a matching CSS class set for the tilt controls to be visible.

File: src/dialogs/more-info/controls/more-info-cover.ts [hunk 2]
```diff
@@ -0,0 +1,147 @@
...
+        max-height: 0px;
+        overflow: hidden;
+      }
+
+      .has-set_position .current_position,
+      .has-current_position .current_position,
+      .has-open_tilt .tilt,
+      .has-close_tilt .tilt,
+      .has-stop_tilt .tilt,
+      .has-set_tilt_position .tilt,
```
Comment (spacegaier) [inline src/dialogs/more-info/controls/more-info-cover.ts:125]: Part of the actual issue fix.

File: src/dialogs/more-info/controls/more-info-cover.ts [hunk 3]
```diff
@@ -0,0 +1,147 @@
...
+      }
+
+      [invisible] {
+        visibility: hidden !important;
+      }
+
+      /* from ha-labeled-slider for consistent look */
+      .title {
+        margin: 5px 0 8px;
+        color: var(--primary-text-color);
```
Comment (spacegaier) [inline src/dialogs/more-info/controls/more-info-cover.ts:137]: Part of the actual issue fix.

File: src/dialogs/more-info/controls/more-info-cover.ts [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+            : html`
+                <div class="title" .hidden=${_isTiltOnly}>
+                  ${this.hass.localize("ui.card.cover.tilt_position")}
+                </div>
+                <ha-cover-tilt-controls
+                  .hass=${this.hass}
+                  .hidden=${_isTiltOnly}
+                  .stateObj=${this.stateObj}
+                ></ha-cover-tilt-controls>
+              `}
```
Comment (spacegaier) [inline src/dialogs/more-info/controls/more-info-cover.ts:76]: Part of the actual issue fix.

File: src/dialogs/more-info/controls/more-info-cover.ts [hunk 5]
```diff
@@ -0,0 +1,151 @@
...
+import "../../../components/ha-labeled-slider";
+import {
+  CoverEntity,
+  isTiltOnly,
+  supportsSetPosition,
+  supportsSetTiltPosition,
+} from "../../../data/cover";
+import { HomeAssistant } from "../../../types";
+
+const FEATURE_CLASS_NAMES = {
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-cover.ts:16]: Move this to `data/cover`

File: src/dialogs/more-info/controls/more-info-cover.ts [hunk 6]
```diff
@@ -0,0 +1,151 @@
...
+                  .caption=${this.hass.localize("ui.card.cover.tilt_position")}
+                  pin=""
+                  extra=""
+                  .value=${this.stateObj.attributes.current_tilt_position}
+                  @change=${this._coverTiltPositionSliderChanged}
+                >
+                  <ha-cover-tilt-controls
+                    .hass=${this.hass}
+                    slot="extra"
+                    .hidden=${_isTiltOnly}
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-cover.ts:66]: Does this do anything?

File: src/dialogs/more-info/controls/more-info-cover.ts [hunk 7]
```diff
@@ -0,0 +1,151 @@
...
+                    .stateObj=${this.stateObj}
+                  ></ha-cover-tilt-controls>
+                </ha-labeled-slider>
+              `
+            : html`
+                <div class="title" .hidden=${_isTiltOnly}>
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-cover.ts:72]: Does this do anything?

File: src/dialogs/more-info/controls/more-info-cover.ts [hunk 8]
```diff
@@ -0,0 +1,151 @@
...
+                  ${this.hass.localize("ui.card.cover.tilt_position")}
+                </div>
+                <ha-cover-tilt-controls
+                  .hass=${this.hass}
+                  .hidden=${_isTiltOnly}
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-cover.ts:77]: Does this do anything?

File: src/dialogs/more-info/controls/more-info-cover.ts [hunk 9]
```diff
@@ -0,0 +1,151 @@
...
+      .has-close_tilt .tilt,
+      .has-stop_tilt .tilt,
+      .has-set_tilt_position .tilt,
+      .has-current_tilt_position .tilt {
+        max-height: 208px;
+      }
+
+      [invisible] {
+        visibility: hidden !important;
+      }
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-cover.ts:136]: Not used?

File: src/dialogs/more-info/controls/more-info-cover.ts (hunk 6 above)
Comment (spacegaier) [reply src/dialogs/more-info/controls/more-info-cover.ts:66]: You mean the `hidden` condition? That is there in case a cover only supports tilting but not up/down. In that case, the tilt buttons should not be shown above the tilt slider, but instead they will be shown as part of the state card (main buttons). That is the existing behavior.

Comment (bramkragten) [reply src/dialogs/more-info/controls/more-info-cover.ts:66]: Where is the hidden property consumed then? I don't see it...

Comment (spacegaier) [reply src/dialogs/more-info/controls/more-info-cover.ts:66]: It is not "consumed". It is the regular HTML `hidden` attribute. It was only by mistake a property here. Changed that.

File: src/dialogs/more-info/controls/more-info-cover.ts (hunk 8 above)
Comment (spacegaier) [reply src/dialogs/more-info/controls/more-info-cover.ts]: See discussion above

File: src/dialogs/more-info/controls/more-info-cover.ts (hunk 9 above)
Comment (spacegaier) [reply src/dialogs/more-info/controls/more-info-cover.ts]: Removed now

File: src/dialogs/more-info/controls/more-info-cover.ts (hunk 7 above)
Comment (spacegaier) [reply src/dialogs/more-info/controls/more-info-cover.ts]: See discussion above

File: src/dialogs/more-info/controls/more-info-cover.ts (hunk 6 above)
Comment (bramkragten) [reply src/dialogs/more-info/controls/more-info-cover.ts]: Please use a ternary for rendering instead of this attribute

**Review by bramkragten — APPROVED** [review]
