### PR TITLE
Fix history-graph card not showing first value

### LINKED ISSUE #51342: history-graph card not showing first value and tooltip is not on top since 2026.4.0
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When using a history-graph card, if the first value started before the start of the graph, it is not shown in the card. It just shows empty space

Example:
First value "On" started between 25 and 26 hours ago

hours_to_show: 25
Image

hours_to_show: 26
Image

Tooltip is not showing entirely. It falls behind other controls and rows and cards.
Image

It does show correctly in the more-info dialog:
Image

### Describe the behavior you expected

First value to start at the beginning of graph even when it started before

### Steps to reproduce the issue

1. make history-graph 
2. see first value missing

### What version of Home Assistant Core has the issue?

2026.4.0

### What was the last working version of Home Assistant Core?

2026.3.4

### In which browser are you experiencing the issue?

Firefox 149, Edge latest, iOS companion app

### Which operating system are you using to run this browser?

Windows / iOS

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

The `"filter"` dataZoom mode introduced in #51307 removes timeline bars whose start time predates the visible range. This causes the first state bar to be missing in history-graph cards when the state started before `hours_to_show`.

Use a three-tier filterMode: `"boundaryFilter"` for line charts, `"filter"` for bar charts, and `"weakFilter"` for custom/timeline series so bars spanning the range boundary are kept.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #51342
- This PR is related to issue or discussion: #51307
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure
[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/components/chart/ha-chart-base.ts [hunk 1]
```diff
@@ -610,9 +610,13 @@ export class HaChartBase extends LitElement {
...
       // just outside each boundary to avoid line gaps at the zoom edges.
       // Only use it for line charts — it causes issues with bar charts.
+      // Use "filter" for bar charts, and "weakFilter" for other types
+      // (e.g. custom/timeline) so bars spanning the visible range are kept.
       filterMode: (ensureArray(this.data).every((s) => s.type === "line")
         ? "boundaryFilter"
-        : "filter") as any,
+        : ensureArray(this.data).some((s) => s.type === "bar")
+          ? "filter"
+          : "weakFilter") as any,
```
Comment (wendevlin) [inline src/components/chart/ha-chart-base.ts]: To reduce complexity in this config definition I would create a func to get the filter mode which get's the detailed comments.

**Review by wendevlin — APPROVED** [review]

**Comment by wltng** [comment]
Awesome guys. Thanks for your immediate attention.
