### PR TITLE
Enhance sun condition automation: add 'between' option and improve duration formatting

### LINKED ISSUE #29194: Sun condition does not allow 'clearing' field
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When configuring a sun condition, if the 'Before' or 'After' condition has been selected initially, it cannot be unselected.
An unselected state here is something distinct, and a valid state:

Image

### Describe the behavior you expected

I expect there to be an option to de-select the before and after state.

### Steps to reproduce the issue

1. Create a 'Sun' condition in an automation
2. Change the 'Before' option to 'Sunrise'
3. Now the 'Before' option cannot be changed.

### What version of Home Assistant Core has the issue?

2026.1.3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change
- fix #29194
- automation condition sun:
  - add select for the form type
  - fix default values
  - Add duration selector instead of simple text

## Screenshots
grafik

grafik

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/panels/config/automation/condition/types/ha-automation-condition-sun.ts [hunk 1]
```diff
@@ -17,59 +22,120 @@ export class HaSunCondition extends LitElement implements ConditionElement {
...
+            ]
+          : []),
       ] as const
   );
 
   protected render() {
-    const schema = this._schema(this.hass.localize);
+    const schema = this._schema(this.hass.localize, this._formType);
     return html`
+      <ha-select
```
Comment (timmo001) [inline src/panels/config/automation/condition/types/ha-automation-condition-sun.ts:111]: How does this look at a radio button? Since its 3 options

File: src/translations/en.json
Comment (NoRi2909) [inline src/translations/en.json]: This ICU string is missing an "and" if we're in that "between" state.
Perhaps we can add this along with this PR.

Also It should begin with "If it is …" instead of "If the sun …"

Comment (NoRi2909) [reply src/translations/en.json]: Or we go one step further, with the summary style matching the new purpose-specific conditions – dropping that if-clause:

- "Before sunrise/set"
- "After sunrise/set"
- "Between sunrise/set and sunrise/set"

(plus the optional offsets)

Comment (wendevlin) [reply src/translations/en.json]: So you mean keep it simple? Sounds good to me!

Comment (NoRi2909) [reply src/translations/en.json]: Yes, it makes them shorter – good for mobile. And it simplifies the grammar, too.

As you know that's an issue in German because adding an if-clause changes the word order in German.
With just a "Between sunrise and sunset" it still forms a nice sentence with the big "and if" above the conditions block: "Und wenn … zwischen Sonnenaufgang und Sonnenuntergang".

Comment (wendevlin) [reply src/translations/en.json]: grafik

File: src/panels/config/automation/condition/types/ha-automation-condition-sun.ts (hunk 1 above)
Comment (wendevlin) [reply src/panels/config/automation/condition/types/ha-automation-condition-sun.ts:111]: here some options

grafik

grafik

grafik

grafik

The button toggle is okay, but with other languages it could look strange. I would stick to the select.

Comment (timmo001) [reply src/panels/config/automation/condition/types/ha-automation-condition-sun.ts:111]: I like the last one, but the select could be useful to avoid misclicks too

:+1: select is fine

File: src/translations/en.json
Comment (NoRi2909) [reply src/translations/en.json]: Yes, that is all that is needed for a proper summary. 👍

**Review by timmo001 — APPROVED** [review]
Good to go if others are

**Review by NoRi2909 — APPROVED** [review]

**Comment by marcinbauer-ohf** [comment]
@wendevlin I think there is an issue in YAML mode:
https://github.com/user-attachments/assets/cf58234a-6eba-49be-90f2-38f68a67b1a1
