### PR TITLE
Read correctly the minutes of a schedule

### LINKED ISSUE #13544: Schedule helper loses half hour settings
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When editing a schedule helper, if it was originally set to end or start on half past the hour, when you return to edit the helper the UI is showing it running on whole hours not the original set half past the hour.

### Describe the behavior you expected

UI allows you to set by the half hour, this should be displayed as such when you reload it

### Steps to reproduce the issue

1: create a new schedule helper
2: set an "on" time for 21:00 to 21:30 (screen shot 1)
3: create the helper

...wait for the time to come around to check the scheduled end time...

4: at 21:05 checked the state of the helper and state is 'on' with attribute next event is 21:30
5: edit the helper the time is blocked out as 21:00 to 22:00 (screen shot 2)
6: save the helper

7: checking the attributes the next event is still 21:30 

image
image

### What version of Home Assistant Core has the issue?

2022.9.0b0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome 104.0.5112.102, Edge 104.0.1293.70

### Which operating system are you using to run this browser?

W11

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by amitfin**
## Breaking change

When reading a schedule, the UI ignored the minutes, so half-hour time range was rounded down.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #13544, #13877
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by amitfin** [comment]
half-hour

Tested after the fix:
fixed

**Comment by amitfin** [comment]
Note that zeros for "secondsValue" and "msValue" were also added (on the 1st call to setHours). Otherwise, the old values (which were set as the current time) are used.

From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setHours:

_If you do not specify the minutesValue, secondsValue, and msValue parameters, the values returned from the [getMinutes()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMinutes), [getSeconds()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getSeconds), and [getMilliseconds()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMilliseconds) methods are used._

File: src/panels/config/helpers/forms/ha-schedule-form.ts [hunk 1]
```diff
@@ -221,14 +221,16 @@ class HaScheduleForm extends LitElement {
         start.setDate(start.getDate() + distance);
         start.setHours(
           parseInt(item.from.slice(0, 2)),
-          parseInt(item.from.slice(-2))
+          parseInt(item.from.slice(3, 5)),
```
Comment (bramkragten) [inline src/panels/config/helpers/forms/ha-schedule-form.ts:224]: this is not correct:

```
"9:30".slice(3,5) => '0'
"12:30".slice(3,5) => '30'
```

Comment (bramkragten) [reply src/panels/config/helpers/forms/ha-schedule-form.ts:224]: As the value of my item is: `{from: '9:00', to: '13:30'}` so the format depends on the locale of the browser

Comment (bramkragten) [reply src/panels/config/helpers/forms/ha-schedule-form.ts:224]: We can use:
```
item.from.split(":")[1];
```

Comment (amitfin) [reply src/panels/config/helpers/forms/ha-schedule-form.ts]: Changed to split() instead of slice().

Note: the root cause of the problem is the existence of the "seconds" (3rd) token in the time string. It doesn't exist when creating a new schedule, but it does exist when retrieving the config of a schedule.

File: src/panels/config/helpers/forms/ha-schedule-form.ts [hunk 2]
```diff
@@ -220,15 +220,17 @@ class HaScheduleForm extends LitElement {
         const start = new Date();
         start.setDate(start.getDate() + distance);
         start.setHours(
-          parseInt(item.from.slice(0, 2)),
-          parseInt(item.from.slice(-2))
+          parseInt(item.from.split(":")[0]),
```
Comment (bramkragten) [inline src/panels/config/helpers/forms/ha-schedule-form.ts:223]: We should do the split just once:
```
const splitted = item.from.split(":", 2);
start.setHours(splitted[0], splitted[1], 0, 0);

Comment (amitfin) [reply src/panels/config/helpers/forms/ha-schedule-form.ts]: Done

**Review by bramkragten — APPROVED** [review]
