### PR TITLE
Open external device configuration url to a new tab/window

### LINKED ISSUE #12904: "Visit Device" button does not open in a new tab or window
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When visiting a device configuration page and clicking on "Visit Device" button, the page open on the same tab and not a new one. This happens also on iOS app.

### Describe the behavior you expected

When clicking the "Visit device" button, the page should open in a new tab or windows. 

### Steps to reproduce the issue

1. Go to Settings
2. Devices & Services
3. Devices
4. Pick a Tasmota device
5. Click on "Visit Device" button
...

### What version of Home Assistant Core has the issue?

2022.6.3

### What was the last working version of Home Assistant Core?

2022.5.X

### In which browser are you experiencing the issue with?

Google Chrome Version 102.0.5005.61 (Official Build) (x86_64)

### Which operating system are you using to run this browser?

macOS Monterey 12.4

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Open external device configuration url to a new tab or window.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #12904
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/devices/ha-config-device-page.ts [hunk 1]
```diff
@@ -80,6 +80,8 @@ export interface EntityRegistryStateEntry extends EntityRegistryEntry {
 
 export interface DeviceAction {
   href?: string;
+  target?: string;
+  rel?: string;
```
Comment (ludeeus) [inline src/panels/config/devices/ha-config-device-page.ts:84]: Why is this an option when its hardcoded to "noreferrer" the only place that's defining it?

File: src/panels/config/devices/ha-config-device-page.ts [hunk 2]
```diff
@@ -981,6 +991,8 @@ export class HaConfigDevicePage extends LitElement {
     if (configurationUrl) {
       deviceActions.push({
         href: configurationUrl,
+        rel: "noreferrer",
+        target: configurationUrlIsHomeAssistant ? "_self" : "_blank",
```
Comment (ludeeus) [inline src/panels/config/devices/ha-config-device-page.ts:995]:
```suggestion
        target: configurationUrlIsHomeAssistant ? undefined : "_blank",
```

Comment (piitaya) [reply src/panels/config/devices/ha-config-device-page.ts:995]: We can automatically add `noreferrer` if target is defined and remove the option.

**Review by ludeeus — APPROVED** [review]
