### PR TITLE
Localize time pattern trigger in automation editor

### LINKED ISSUE #18352: Missing in lokalise existing automation - "Invalid time pattern Seconds"
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing in lokalise

Screen can be found in web version Settings/Automations and Scenes/ in existing automatisation

Snag_InvalidTimePatternSeconds

### Describe the behavior you expected

Add to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.5

### What was the last working version of Home Assistant Core?

not relevant

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### LINKED ISSUE #18356: Missing in lokalise existing automation - "Trigger on the..."
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing in lokalise

Screen can be found in web version Settings/Automations and Scenes/ in existing automatisation

Snag_TriggerOnThe

### Describe the behavior you expected

Add to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.5

### What was the last working version of Home Assistant Core?

not relevant

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### LINKED ISSUE #18358: Missing in lokalise existing automation - "When Time Pattern Matches"
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing in lokalise

Screen can be found in web version Settings/Automations and Scenes/ in existing automatisation

Snag_WhenTimePatternMatches

### Describe the behavior you expected

Add to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.5

### What was the last working version of Home Assistant Core?

not relevant

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change
Localize time pattern trigger in the automation editor. It's yet another complex translation to add unfortunately because of the very dynamic way the sentence is built together. 

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #18352 fixes #18358 fixes #18356
- This PR is related to issue or discussion: #13820
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by karwosts** [comment]
Wow did not think anyone would attempt this one 😅 

Very minor nit, but the following pattern:

```
platform: time_pattern
hours: "0"
seconds: "0"
```

generates a slightly incorrect string:

Trigger on the 0th second **_of on_** the 0th minute of the 0th hour.

It's subtle enough could probably let it go if it's difficult to fix, but just wanted to point that out if you want to look at it. Adding `minutes: "0"` makes the string correct, so you're probably really close, maybe just a minor correction needed.

File: src/data/automation_i18n.ts [hunk 1]
```diff
@@ -488,24 +494,68 @@ const tryDescribeTrigger = (
...
+        secondsChoice: secondsChoice,
+        minutesChoice: minutesChoice,
+        hoursChoice: hoursChoice,
+        seconds: seconds,
+        minutes: minutes,
+        hours: hours,
+        secondsWithOrdinal: hass.localize(
+          `${triggerTranslationBaseKey}.time_pattern.description.ordinal`,
+          {
+            part: seconds,
```
Comment (bramkragten) [inline src/data/automation_i18n.ts:542]: This should be using `new Intl.PluralRules("en", {type: "ordinal"}).select(seconds)`

**Review by bramkragten — APPROVED** [review]
