### PR TITLE
Correctly handle seconds in top "delay" key

### LINKED ISSUE #8376: "delay: 5" in yaml is converted to 5 hours in UI editor
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

If the action ```- delay: 5``` is written in YAML and the automation is loaded in the UI editor, the editor will indicate that the delay is 5 hours. (```05:00:00:000```).

**Describe the behavior you expected**

I would expect it to be 5 seconds.

**Steps to reproduce the issue**

1. Create a delay in YAML
2. Open in UI automation/script-editor

**What version of Home Assistant Core has the issue?**

core-2021.2.3

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

Google Chrome 88.0.4324.150 / Android companion app beta-580-5ee48f2-full

**Which operating system are you using to run this browser?**

Windows 10 / Android

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
- delay: 5

```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

The format `delay: <seconds>` was incorrectly interpreted also as a string time value and attempted to be split at ":". This meant the seconds were interpreted as hours.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/8376
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/automation/action/types/ha-automation-action-delay.ts [hunk 1]
```diff
@@ -22,13 +22,17 @@ export class HaDelayAction extends LitElement implements ActionElement {
...
-      data = {
-        hours: Number(parts[0]),
-        minutes: Number(parts[1]),
-        seconds: Number(parts[2]),
-        milliseconds: Number(parts[3]),
-      };
+      if (isNaN(this.action.delay)) {
+        const parts = this.action.delay?.toString().split(":") || [];
+        data = {
+          hours: Number(parts[0]),
```
Comment (bramkragten) [inline src/panels/config/automation/action/types/ha-automation-action-delay.ts:28]:
```suggestion
          hours: Number(parts[0] || 0),
```

File: src/panels/config/automation/action/types/ha-automation-action-delay.ts [hunk 2]
```diff
@@ -22,13 +22,17 @@ export class HaDelayAction extends LitElement implements ActionElement {
...
-        seconds: Number(parts[2]),
-        milliseconds: Number(parts[3]),
-      };
+      if (isNaN(this.action.delay)) {
+        const parts = this.action.delay?.toString().split(":") || [];
+        data = {
+          hours: Number(parts[0]) || 0,
+          minutes: Number(parts[1]),
+          seconds: Number(parts[2]),
+          milliseconds: Number(parts[3]),
```
Comment (bramkragten) [inline src/panels/config/automation/action/types/ha-automation-action-delay.ts:31]: And then also for the rest 😄

**Review by bramkragten — APPROVED** [review]
