### PR TITLE
Fix selection state not updating after item deletion

### LINKED ISSUE #27922: Deleting selected items does not update the count of selected items
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

If multiple selected items are deleted (e.g., in Automations), the total count of selected items at the top of the page does not update.

### Describe the behavior you expected

If any of the selected items are deleted, the total number of selected items shown should update to reflect the lower number of selected items.

### Steps to reproduce the issue

1. Open the automations page
2. Select multiple items
3. Note the total count of the selected items at the top of the page
4. Delete one of the selected items
5. Check the total count of the selected items again

### What version of Home Assistant Core has the issue?

2025.11.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Firefox 144.0.2

### Which operating system are you using to run this browser?

Debian 13 KDE

### State of relevant entities

```txt
N.A.
```

### Problem-relevant frontend configuration

```yaml
N.A.
```

### JavaScript errors shown in your browser console/inspector

```txt
N.A.
```

### Additional information

Image

### PR DESCRIPTION
**Pull request by ezra-freedman**
## Proposed change
When deleting items from automation, script, or scene pickers while they are selected, the selection count and "Select all" checkbox state were not properly updated. For example:
- Select 2 automations, delete one, select header still reads "Selected 2"
- Deleting the last selected item would leave the checkbox in an indeterminate state (blue with horizontal line)

This PR fixes both issues:
1. Cleans up the internal _checkedRows array in ha-data-table when data changes, removing references to deleted items
2. Updates the _selected array in automation, script, and scene pickers after successful deletion

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information
The issue where this was reported indicates this would happen in the automations list. In reviewing the code the same issues would occur in Scripts and Scenes so I updated those as well.

Other list views use `HaDataTable` but none seem to work exactly like Automations so may not show the reported issue. For other cases should they be impacted the safeguard removal of deleted rows from checked items is still appropriate.

- This PR fixes or closes issue: fixes #27922

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/script/ha-script-picker.ts [hunk 1]
```diff
@@ -1184,6 +1184,9 @@ ${rejected
       if (entry) {
         await deleteScript(this.hass, entry.unique_id);
       }
+      this._selected = this._selected.filter(
+        (entityId) => entityId !== script.entity_id
+      );
```
Comment (MindFreeze) [inline src/panels/config/script/ha-script-picker.ts]: Can we move this inside `if (entry)`? It's an edge case but otherwise it would just deselect it and not delete it if the entry is not found.

**Review by MindFreeze — CHANGES_REQUESTED** [review]

**Review by MindFreeze — APPROVED** [review]
Thank you @ezra-freedman
