### PR TITLE
Set mandatory bool service data without a default value to false

### LINKED ISSUE #10073: Visual Editor not setting value based on the initial state of the interface for a required field
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In the visual editor for calling a service from an automation, I was setting up the media_player.volume_mute service, which requires is_volume_muted parameter to be true or false to function. As I wanted the automation to unmute, I left the value defaulted. However, this caused the automation to break since it appears that unless the toggle is activated on and off, the visual editor does not set the value for the is_volume_muted parameter. I found the issue can be easily recreated in the developer-tools/service screen as well.

### Describe the behavior you expected

Since the visual editor defaults to "off/false" for the toggle, the underlying yaml should be default to having written is_volume_muted: false by default

### Steps to reproduce the issue

1. Go to developer-tools/service
2. With the visual editor enabled, pick the media_player.volume_mute serivce
3. choose a media player entity 
4. Click "Call Service" at this point, yields the following error: `Failed to call service media_player.volume_mute. required key not provided @ data['is_volume_muted']. Got None`
5. Click "go to YAML mode", and you should see it setup as follows:
```yaml
service: media_player.volume_mute
target:
  entity_id: media_player.example_media_player
```
6. Click on "Go to UI Mode", and toggle "**Muted**" parameter on and off again
7. Go back to YAML mode, and the parameter has actually been set this time:
```yaml
service: media_player.volume_mute
target:
  entity_id: media_player.example_media_player
data:
  is_volume_muted: false
```
8. Clicking "Call Service" at this point is successful.

### What version of Home Assistant Core has the issue?

Home Assistant 2021.9.7

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Confirmed on Firefox 92 and Google Chrome 93.0.4577.82

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
When muted:
Media_player.example_media_player
State: Playing

volume_level: 1
is_volume_muted: true
media_content_id: spotify:track:5WC03eSIqpv6Hxv7X7MV0j
media_content_type: music
media_duration: 301.386
media_position: 143.508
media_position_updated_at: '2021-09-22T12:17:12.022939+00:00'
media_title: The Beast of Pirate’s Bay (Original version)
media_artist: Aurelio Voltaire
media_album_name: Spooky Songs For Creepy Kids
app_id: CC32E753
app_name: Spotify
entity_picture_local: >-
  /api/media_player_proxy/media_player.example_media_player?token=5130cef008770dd6255e54c909bf6cd63ee4c9e24517d27695d9d8c6e3e0b556&cache=1bac21561c2381cc
friendly_name: Living Room speaker
entity_picture: https://i.scdn.co/image/ab67616d00001e02922553ac06b0cebd2598555f
supported_features: 152511

When not muted
Media_player.example_media_player
State: Playing
volume_level: 1
is_volume_muted: false
media_content_id: spotify:track:5WC03eSIqpv6Hxv7X7MV0j
media_content_type: music
media_duration: 301.386
media_position: 143.508
media_position_updated_at: '2021-09-22T12:17:12.022939+00:00'
media_title: The Beast of Pirate’s Bay (Original version)
media_artist: Aurelio Voltaire
media_album_name: Spooky Songs For Creepy Kids
app_id: CC32E753
app_name: Spotify
entity_picture_local: >-
  /api/media_player_proxy/media_player.example_media_player?token=5130cef008770dd6255e54c909bf6cd63ee4c9e24517d27695d9d8c6e3e0b556&cache=1bac21561c2381cc
friendly_name: Living Room speaker
entity_picture: https://i.scdn.co/image/ab67616d00001e02922553ac06b0cebd2598555f
supported_features: 152511
```

### Problem-relevant frontend configuration

```yaml
n/a
```

### Javascript errors shown in your browser console/inspector

```txt
None found
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by emontnemery**
## Proposed change

Set mandatory bool service data without a default value to false so the actual service data matches what's shown in the UI.

This PR does not prevent saving an automation with invalid services though, for example if a mandatory field is missing.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/10073

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-service-control.ts [hunk 1]
```diff
@@ -74,15 +74,34 @@ export class HaServiceControl extends LitElement {
...
+            field.selector &&
+            field.required &&
+            field.default === undefined &&
+            "boolean" in field.selector
+          ) {
+            mandatoryBools[field.key] = false;
+          }
+        });
+        this.value.data = {
+          ...this.value?.data,
```
Comment (bramkragten) [inline src/components/ha-service-control.ts:99]:
```suggestion
          ...this.value.data,
```

File: src/components/ha-service-control.ts [hunk 2]
```diff
@@ -74,15 +74,34 @@ export class HaServiceControl extends LitElement {
...
-
     const serviceData = this._getServiceInfo(
       this.value?.service,
       this.hass.services
     );
 
+    if (oldValue?.service !== this.value?.service) {
+      this._checkedKeys = new Set();
+
+      if (this.value) {
```
Comment (bramkragten) [inline src/components/ha-service-control.ts:85]:
```suggestion
      if (this.value && serviceData) {
```

File: src/components/ha-service-control.ts [hunk 3]
```diff
@@ -74,15 +74,34 @@ export class HaServiceControl extends LitElement {
...
+        // Set mandatory bools without a default value to false
+        const mandatoryBools = {};
+        serviceData?.fields.forEach((field) => {
```
Comment (bramkragten) [inline src/components/ha-service-control.ts:88]:
```suggestion
        serviceData.fields.forEach((field) => {
```

**Review by bramkragten — APPROVED** [review]
