### PR TITLE
Fix back button when directly opening subview

### LINKED ISSUE #14041: Subview back function not working, when opening subview directly
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When opening a subview directly the back button is without function.
This is mostly an isssue within the apps, after closing the app and restarting the app.
Example : https://www.youtube.com/watch?v=aqWfycG3jmA

Can be replicated with a browser by opening the subview from commandline/shortcut.
Example: https://www.youtube.com/watch?v=Z3q441a4mSE

### Describe the behavior you expected

Back arrow should atleast lead somewhere, which is not a subview.

### Steps to reproduce the issue

App:
1. Open Subview in app
2. Close app process
3. Restart app

Desktop
1. Open subview url directly

### What version of Home Assistant Core has the issue?

2022.10.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

Setting the back_path is a workaround for now, but breaks the ability to have multiple ways to a subview and back.

### PR DESCRIPTION
**Pull request by piitaya**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #14041
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/hui-root.ts [hunk 1]
```diff
@@ -743,12 +743,14 @@ class HUIRoot extends LitElement {
     const curViewConfig =
       typeof this._curView === "number" ? views[this._curView] : undefined;
 
-    if (curViewConfig?.back_path) {
-      navigate(curViewConfig.back_path);
+    if (curViewConfig?.back_path != null) {
+      navigate(curViewConfig.back_path, { replace: true });
```
Comment (bramkragten) [inline src/panels/lovelace/hui-root.ts:747]: replace is actually wrong here... I guess the most correct would be to do a back and then replace... but... that would also not be correct...

Comment (piitaya) [reply src/panels/lovelace/hui-root.ts:747]: Yes, I added replace option to avoid pushing into history. But I'm ok to remove it.

**Review by bramkragten — APPROVED** [review]
