### PR TITLE
Use integration manifest for service documentation URL

### LINKED ISSUE #9919: Service call UI link to integration documentation is wrong for custom integrations
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This can be summarised by https://github.com/HASwitchPlate/openHASP-custom-component/issues/70

The link assumes the integration is always core

### Describe the behavior you expected

Should read the link from manifest and not assume

### Steps to reproduce the issue

1. Install a custom_integration with service
2. go to the service page in Developer tools
3. Click on ?

### What version of Home Assistant Core has the issue?

core-2020.08

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Use the integration manifest for the service documentation, so that it also works for custom integrations.

If the user just switches to a different service from the same domain, no re-fetching happens. Only when a different domain is used, a new fetch request is triggered.

@bramkragten Do you think we need to add static caching to only retrieve the manifest once per integration (even if in between the user selects a different domain)? I would expect that usually a user is not wildly switching around the integrations when creating e.g. automations, so there should not be that many WS calls anyway.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9919
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-service-control.ts [hunk 1]
```diff
@@ -387,6 +404,14 @@ export class HaServiceControl extends LitElement {
     });
   }
 
+  private async _fetchManifest(integration: string) {
+    try {
+      this._manifest = await fetchIntegrationManifest(this.hass, integration);
+    } catch (err) {
+      // Ignore if loading manifest fails. Probably bad JSON in manifest
```
Comment (bramkragten) [inline src/components/ha-service-control.ts:411]: It will not clear the old manifest now, before fetching a new one, set `this._manifest = undefined`

File: src/components/ha-service-control.ts [hunk 2]
```diff
@@ -72,6 +77,21 @@ export class HaServiceControl extends LitElement {
...
     );
 
+    // Fetch the manifest if we have a service selected and the service domain changed.
+    // If no service is selected, clear the manifest.
+    if (this.value?.service) {
+      if (
+        oldValue?.service
+          ? computeDomain(this.value?.service) !==
+            computeDomain(oldValue?.service)
+          : true
```
Comment (bramkragten) [inline src/components/ha-service-control.ts:87]:
```suggestion
      if (
        !oldValue?.service ||
          computeDomain(this.value.service) !==
            computeDomain(oldValue.service)
```

**Comment by bramkragten** [comment]
> @bramkragten Do you think we need to add static caching to only retrieve the manifest once per integration (even if in between the user selects a different domain)? I would expect that usually a user is not wildly switching around the integrations when creating e.g. automations, so there should not be that many WS calls anyway.

Nah, don't think so

**Review by bramkragten — APPROVED** [review]
