### PR TITLE
Remove extra spacing for automation editor content

### LINKED ISSUE #30083: Remove unnecessary space in automation editor content
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The automation editor has unnecessary space that shouldn't be there. This is more apparent on mobile.
Image
Image

### Describe the behavior you expected

Remove the space.

### Steps to reproduce the issue

1. Create new automation

### What version of Home Assistant Core has the issue?

2026.3.0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by timmo001**
## Screenshots

disabled:

image

with description:

image

no description:

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: resolves #30083
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/panels/config/automation/styles.ts [hunk 1]
```diff
@@ -147,7 +147,6 @@ export const manualEditorStyles = css`
   }
 
   .content {
-    padding-top: 24px;
```
Comment (marcinbauer-ohf) [inline src/panels/config/automation/styles.ts:150]: I think this is still needed:

Image

Comment (timmo001) [reply src/panels/config/automation/styles.ts:150]: Brought back but with a reduced value. See updated screenshots

**Comment by marcinbauer-ohf** [comment]
Good to go! 🚀

**Review by MindFreeze — APPROVED** [review]
