### PR TITLE
Fix for when the preview element was an error element

### LINKED ISSUE #4957: Light card visual editor preview doesn't update in 0.106
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Visual editors were mostly fixed with https://github.com/home-assistant/home-assistant-polymer/pull/4947 yesterday.

One that's still a little messed up (different issue tho) is Light card. When you select an entity from the dropdown, the preview on the right side never updates. It continues to say `Specify an entity from within the light domain.`  even after you've already selected one.

**NOTE**:  If you click the Show Code Editor button, it will have the correct YAML code in there with the entity ID and everything. And if you hit save, you will have a working card. Lastly, if you edit an existing card the preview works fine. So the problem is just with the preview on **new** light cards from what I can tell.

You can see it in the screenshot below and reproduce it in the [demo](https://demo.home-assistant.io/#/lovelace/0).

light

## Expected behavior

Update preview after light entity is selected

## Steps to reproduce

1. Go to [demo website](https://demo.home-assistant.io/#/lovelace/0)
2. Enter Configure UI mode
3. Add new card > Light card
4. Select an entity as the error tells you to, but preview doesn't update after you do so

## Environment

- Home Assistant release with the issue: 0.106.0b1
- Last working Home Assistant release (if known): 0.105.X
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: Chrome stable
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/4957

### CODE REVIEW

File: src/panels/lovelace/editor/card-editor/hui-card-preview.ts [hunk 1]
```diff
@@ -66,13 +66,17 @@ export class HuiCardPreview extends HTMLElement {
       return;
     }
 
-    if (curConfig && configValue.type === curConfig.type) {
+    // in case of an error we always want to recreate the element
+    if (!this._error && curConfig && configValue.type === curConfig.type) {
       try {
-        this._element.setConfig(deepClone(configValue));
+        this._error = false;
+        this._element.setConfig(deepFreeze(configValue));
```
Comment (balloob) [inline src/panels/lovelace/editor/card-editor/hui-card-preview.ts]: We shouldn't deep freeze here. This is a passed in value to this component. So now rendering something with this component has the side-effect of freezing your object. We should freeze, but we should freeze in the component that owns the config (the parent I think in this case)

File: src/panels/lovelace/editor/card-editor/hui-card-preview.ts [hunk 2]
```diff
@@ -81,6 +85,10 @@ export class HuiCardPreview extends HTMLElement {
     this._cleanup();
     this._element = createCardElement(configValue);
 
+    if (this._element.tagName === "HUI-ERROR-CARD") {
```
Comment (balloob) [inline src/panels/lovelace/editor/card-editor/hui-card-preview.ts]: If we're already deriving it here, why even keep track of `this._error`  ? Can't we make it a getter that does this under the hood? 

```ts
private get _error() { return this._element && this._element.tagName === "HUI-ERROR-CARD"; }
```

**Review by balloob — APPROVED** [review]
