### PR TITLE
Fix code editor autocomplete using wa popup

### LINKED ISSUE #29764: Card editor: autocomplete popup is clipped
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Autocomplete popup is clipped:

Image

Just in case – reverted locally changes from https://github.com/home-assistant/frontend/pull/29674, does not help.

### Describe the behavior you expected

no clipping

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

dev 2026.3

### What was the last working version of Home Assistant Core?

2026.2

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by timmo001**
## Proposed change

Initially tried to set the parent, this didn't show at all, second was to use position absolute, and then the helper to use `wa-popup`. This works pretty well.

Only loss is the width of the select list to make sure it cannot go outside of the editor/dialog.

May be better to work on a full popover with a vertical split for the selection and helper sections, but this is a lot more involved. For now this is OK and can allow users to keep using the autocomplete as before with the old dialogs

## Screenshots

image

When the entity is at the bottom of a card code editor, it will introduce scrolling, but it is now visible when scrolling. This was from the `position: absolute` edit:

image

Non dialogs still compatible (bad screenshot):

image

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #29764
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [x] I understand the code I am submitting and can explain how it works.
- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] I have followed the [perfect PR recommendations][perfect-pr]
- [x] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [x] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/resources/codemirror.ts [hunk 1]
```diff
@@ -151,10 +152,22 @@ export const haTheme = EditorView.theme({
       "var(--code-editor-background-color, var(--card-background-color))",
     border: "1px solid var(--divider-color)",
     borderRadius: "var(--mdc-shape-medium, 4px)",
+    maxWidth: "min(420px, calc(100vw - (2 * var(--ha-space-4, 16px))))",
```
Comment (wendevlin) [inline src/resources/codemirror.ts]: what about safe area? I think we should consider this here too.

**Review by wendevlin — APPROVED** [review]
