### PR TITLE
Fix issue with toggles blocking dialog and dialog launching on mobile

### LINKED ISSUE #7517: Quickbar shortcuts "e" & "c" trigger the quickbar when typing in some text fields on a mobile device
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The new Quickbar shortcuts ("e" and "c") trigger the Quickbar when typing into some text boxes.  Examples are typing into the dev->Templates or the service data field of dev->Services, or (I'm told) editing automations.  There may be others.  This behavior seems to be limited to mobile devices (I use an iPhone) and I don't see the behavior in my desktop browser (Chrome).

## Expected behavior

The Quickbar shortcuts should not trigger when typing text into a textbox, or maybe not at all on a mobile device.  Maybe only if a physical keyboard is attached, such as with an iPad?

## Steps to reproduce

Go to Dev->Services or Dev->Templates on an iOS device and hit "c" or "e" in the text box for service data or the template text field.  Note that the Quickbar appears.

## Environment

- Home Assistant release with the issue: 0.117
- Last working Home Assistant release (if known): N/A
- Browser and browser version: Official Home Assistant iOS app
- Operating system: iOS 14.1

## State of relevant entities

None

## Problem-relevant configuration

None

## Javascript errors shown in your browser console/inspector

None

### PR DESCRIPTION
**Pull request by donkawechico**
## Proposed change

1. Be more granular about which input fields should block dialog if focused. Fixes a bug where toggle buttons (which are inputs of type "checkbox") will block dialog launching if just clicked.
2. Block dialog from launching on mobile devices (using detection code from http://detectmobilebrowsers.com/). Fixes an issue where iOS users currently in template / call service data field / automation editor fields will launch the dialog if they type `e` or `c`.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/7517
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/state/quick-bar-mixin.ts [hunk 1]
```diff
@@ -48,8 +48,15 @@ export default <T extends Constructor<HassElement>>(superClass: T) =>
...
+      const el = e.composedPath()[0] as any;
+      return (
+        el.tagName === "TEXTAREA" ||
+        (el.tagName === "INPUT" &&
+          ["TEXT", "NUMBER"].includes(this._getInputType(el)))
       );
     }
+
+    private _getInputType(el) {
+      return el.type && el.type.toUpperCase();
```
Comment (bramkragten) [inline src/state/quick-bar-mixin.ts:60]:
```suggestion
      return el.type?.toUpperCase();
```

File: src/state/quick-bar-mixin.ts [hunk 2]
```diff
@@ -48,8 +48,15 @@ export default <T extends Constructor<HassElement>>(superClass: T) =>
     }
 
     private _inInputField(e: KeyboardEvent) {
-      return ["INPUT", "TEXTAREA"].includes(
-        (e.composedPath()[0] as HTMLElement).tagName
+      const el = e.composedPath()[0] as any;
+      return (
+        el.tagName === "TEXTAREA" ||
+        (el.tagName === "INPUT" &&
+          ["TEXT", "NUMBER"].includes(this._getInputType(el)))
```
Comment (bramkragten) [inline src/state/quick-bar-mixin.ts:55]: It would not be just text and number, but also email, date, search, color, tel, time, email, URL, etc.

Comment (bramkragten) [reply src/state/quick-bar-mixin.ts:55]: Maybe easier to check the types we do want the event to handle.

Comment (donkawechico) [reply src/state/quick-bar-mixin.ts]: Done

File: src/state/quick-bar-mixin.ts (hunk 1 above)
Comment (donkawechico) [reply src/state/quick-bar-mixin.ts]: N/A now

File: src/state/quick-bar-mixin.ts [hunk 3]
```diff
@@ -36,20 +37,42 @@ export default <T extends Constructor<HassElement>>(superClass: T) =>
...
 
-    private _inInputField(e: KeyboardEvent) {
-      return ["INPUT", "TEXTAREA"].includes(
-        (e.composedPath()[0] as HTMLElement).tagName
+    private _canShowQuickBar(e: KeyboardEvent) {
+      return (
+        this.hass?.user?.is_admin &&
+        this.hass.enableShortcuts &&
+        this._canOverrideAlphanumericInput(e) &&
+        !isMobileOrTablet()
```
Comment (bramkragten) [inline src/state/quick-bar-mixin.ts:52]: Is this just for codemirror? Can't we just detect it was fired in a codemirror element instead of blocking all mobiles and tablets?

I think a tablet with a Bluetooth keyboard should just work with quickbar, codemirror has some workarounds for iOS, which probably causes this problem.

I think it is safe to just filter out `div.CodeMirror-code`, we could even do that in the `ha-code-editor` element instead of here.

Comment (bramkragten) [reply src/state/quick-bar-mixin.ts:52]: Adding `this.addEventListener("keydown", (ev) => ev.stopPropagation());` to `ha-code-editor`

Comment (donkawechico) [reply src/state/quick-bar-mixin.ts:52]: You don't think using a class name, and of a 3rd party tool, is going to be too brittle?

Comment (donkawechico) [reply src/state/quick-bar-mixin.ts]: Went ahead and did the change and pushed. Keeping the "`isMobileOrTablet`" helper though as I suspect it will be useful as we work out mobile shortcut/gesture strategies.

Comment (donkawechico) [reply src/state/quick-bar-mixin.ts]: Oh I didn't see your 2nd comment :P Okay I'll add there.

Comment (donkawechico) [reply src/state/quick-bar-mixin.ts]: Done

**Review by bramkragten — APPROVED** [review]
