### PR TITLE
Do not close aliases dialog on enter

### LINKED ISSUE #14907: Frontend alias pop-up not saving when hitting enter
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

With HA Core 2023.1.0b0 you can add aliases to entities, but when you've added an alias to an entity and hit enter on your keyboard: the dialog closes without saving.

### Describe the behavior you expected

I expected the dialog to close with saving the content, I believe that's expected behaviour of the enter key

### Steps to reproduce the issue

1. Open an entity
2. Click on Settings
3. Click on Advanced Settings
4. Click on No configured aliases
5. Type something, i.e. Test
6. Hit the enter key on your keyboard
7. Nothing is being saved and the alias pop-up is closed like you have hit the cancel box

### What version of Home Assistant Core has the issue?

core-2023.1.0b0

### What was the last working version of Home Assistant Core?

never

### In which browser are you experiencing the issue with?

Brave version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 22H2

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

When hitting enter, a new alias textfield is added instead of closing the dialog.
Translations have been improved too.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #14907
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts [hunk 1]
```diff
@@ -133,6 +142,12 @@ class DialogEntityAliases extends LitElement {
     this._aliases[index] = (ev.target as any).value;
   }
 
+  private async _keyDownAlias(ev: KeyboardEvent) {
+    if (ev.key === "Enter") {
+      this._addAlias();
```
Comment (bramkragten) [inline src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts:147]: Can t we do the `stopPropagation` here?

Comment (piitaya) [reply src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts:147]: I handled it at the container level because if user focus the delete button or the add alias button and press enter, we will have the same issue.
Or we can add the `stopPropagation` to each element ?

Comment (bramkragten) [reply src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts:147]: OK, shouldn't we limit it to the enter key then?

Comment (piitaya) [reply src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts:138]: I replaced actions by buttons to avoid automatic submission. It's cleaner than stopping propagation.

Comment (bramkragten) [reply src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts:138]: Not sure I agree... An update of the dialog now requires manual action here to adjust styling etc.

We have this issue in way more dialogs I noticed btw, maybe we should work on a more generic solution (in the future)

File: src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts [hunk 2]
```diff
@@ -72,16 +73,21 @@ class DialogEntityAliases extends LitElement {
                     dialogInitialFocus=${index}
                     .index=${index}
                     class="flex-auto"
-                    label="Alias"
+                    label=${this.hass!.localize(
```
Comment (bramkragten) [inline src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts:76]:
```suggestion
                    .label=${this.hass!.localize(
```

**Review by bramkragten — DISMISSED** [review]

File: src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts [hunk 3]
```diff
@@ -59,6 +59,7 @@ class DialogEntityAliases extends LitElement {
           "ui.dialogs.entity_registry.editor.aliases.heading",
           { name }
         )}
+        .suppressDefaultPressSelector=${"input"}
```
Comment (bramkragten) [inline src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts:62]: Should it not also have the defaults?

Comment (piitaya) [reply src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts:62]: It will disable the behavior for all prompt dialogs 😞

Comment (bramkragten) [reply src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts:62]: No, I mean you now overrule `suppressDefaultPressSelector`, to only be `input`, all the default suppressed elements (like button) are not suppressed now for this dialog?

**Comment by TyzzyT** [comment]
When I opened #14907, I couldn't have imagined there was so much to be done! Thank you very much for all your work Piitaya and Bram! You rock!

File: src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts (hunk 3 above)
Comment (piitaya) [reply src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts:62]: No, dialog base merges it

Comment (steverep) [reply src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts:62]: Why not just list all the elements that we want to suppress in ha-dialog (this is what mwc-dialog does)? Making it an input seems unnecessary.

Comment (piitaya) [reply src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts]: For now I stopped propagation from the textfield and added button to the list. 
I agree @steverep, we should have a list based on accessibility criteria. I will look to do this in another PR

**Review by bramkragten — APPROVED** [review]

File: src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts (hunk 3 above)
Comment (steverep) [reply src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts]: Maybe I'm missing what you're trying to do here, but I'm concerned you're breaking enter key behavior that will be universally expected for any keyboard user. The only elements that shouldn't close a dialogue on enter would be multi line fields or open drop downs.

I can't do it now, but later tonight or tomorrow, I can take a closer look and pull the branch down.

Comment (piitaya) [reply src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts]: The aliases are in a list of input field. Pressing enter add a new line (new input field). User can delete the line by clicking the delete button next to the input field. User can add a new input field by clicking "add alias" button.

I'll be interested by your feedback how we can provide a good accessibility support for list of input field.

Comment (steverep) [reply src/panels/config/entities/entity-aliases/dialog-entity-aliases.ts]: That part I get, and pressing enter to add the field to the list is fine, although some helper text to advise of that behavior would be nice.  I was more concerned with having `button` or `input` in the suppress list.  Let me check it out.

More generally though, I think the list of input fields used here (and in various card editor dialogs) is just a very clunky experience for keyboard users.  It takes too many strokes to accomplish something simple like just reading the list or finding and deleting an item.  I would much rather see a single text field to add/edit, and the items already in the list held as a listbox with text/icons or chips.
