### PR TITLE
Fix shopping list initial data fetch

### LINKED ISSUE #6006: shopping list empty
## Checklist

- [x] I have updated to the latest available Home Assistant version. (**0.110.1**)
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

when loading the shopping list card, it will render as empty until you load the integration on the sidebar.

## Expected behavior

that the card is populated when first loaded.
## Steps to reproduce

1. add the shopping list integration
2. add items to the list
3. add the shopping list card to lovelace
4. clear cookies
5. log in
6. observe empty list
7. click the tab in the sidebar (showing items on the list)
8. navigate back to lovelace (now also showing items) 
## Environment

- Home Assistant release with the issue: 0.110.1
- Last working Home Assistant release (if known): 0.109.*
- Browser and browser version: Firefox & chrome android
- Operating system: manjaro linux

## State of relevant entities

```yaml
title: Boodschappenlijst
type: shopping-list
```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Fixes https://github.com/home-assistant/frontend/issues/6006

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/hui-shopping-list-card.ts [hunk 1]
```diff
@@ -57,26 +59,24 @@ class HuiShoppingListCard extends LitElement implements LovelaceCard {
...
   public connectedCallback(): void {
     super.connectedCallback();
-
-    if (this.hass) {
-      this._unsubEvents = this.hass.connection.subscribeEvents(
-        () => this._fetchData(),
-        "shopping_list_updated"
-      );
-      this._fetchData();
+    if (!this.hass) {
```
Comment (balloob) [inline src/panels/lovelace/cards/hui-shopping-list-card.ts:66]: I wonder if we can use the subscribeMixin. We can have the subscribe callback do the fetching before returning the callback?

**Review by balloob — APPROVED** [review]

File: src/panels/lovelace/cards/hui-shopping-list-card.ts (hunk 1 above)
Comment (bramkragten) [reply src/panels/lovelace/cards/hui-shopping-list-card.ts]: Yes that would be possible, with some adjustments to the `subscribeMixin` to deal with promises.

**Review by balloob — APPROVED** [review]
