### PR TITLE
Display live remaining time for timer on tile card

### LINKED ISSUE #21288: Timers remaning time not working in tile card
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On a views of type section.
When the timer is running, the remaining stay at duration time and not countdown
Capture d’écran 2024-07-04 153412

### Describe the behavior you expected

The timer card in views section, with remaining time work as other type views with decremant time 
Capture d’écran 2024-07-04 154053

### Steps to reproduce the issue

1.Add a card by entity of an timer
2. Add State content: Remaining
3. Start the timer

### What version of Home Assistant Core has the issue?

2024.7.0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Firefox 127.0.2 / Brave Version 1.67.123 Chromium: 126.0.6478.126

### Which operating system are you using to run this browser?

Windows 11 / Linux

### State of relevant entities

```txt
timer.name active
```

### Problem-relevant frontend configuration

```yaml
type: tile
entity: timer.auto_rearme
layout_options:
  grid_columns: 4
  grid_rows: 1
state_content:
  - remaining
  - duration
  - finishes_at
```

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Only the state was displayed before.
I also clean up state-summary and state-card to share the same logic.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/21288
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **New Features**
  - Introduced `state-display-timer` component for displaying timer information in various parts of the UI.
  
- **Refactor**
  - Enhanced `HuiTileCard` rendering logic for "update" and "timer" domains, improving display and maintainability.
  - Refactored `HuiTimerEntityRow` and `state-card-timer` components to utilize the new `state-display-timer` component, removing redundant timer logic.

- **Bug Fixes**
  - Updated display timer logic to show "0" when no time remains, enhancing clarity when the timer has expired.

### CODE REVIEW

**Review by silamon — APPROVED** [review]
This does fix it for the tile card, but you need to keep the state content empty. If you're adding "remaining" and "duration" both to the state content, it will just show the initial duration of the timer for both "remaining" and "duration".

File: src/state-display/state-display-timer.ts [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+
+  @property({ attribute: false }) public stateObj!: HassEntity;
+
+  @state() private timeRemaining?: number;
+
+  private _updateRemaining: any;
+
+  protected createRenderRoot() {
+    return this;
+  }
```
Comment (bramkragten) [inline src/state-display/state-display-timer.ts:19]: Why no shadowroot?

**Comment by piitaya** [comment]
> This does fix it for the tile card, but you need to keep the state content empty. If you're adding "remaining" and "duration" both to the state content, it will just show the initial duration of the timer for both "remaining" and "duration".

Yep I will look to create another PR to let the user select these special states.
