### PR TITLE
Use ha-card-border-color for integration cards instead of divider-color

### LINKED ISSUE #30397: Settings -> Integration page uses divider-color for all cards instead of ha-card-border-color
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When attempting to theme overall card border separately from divider-color, I found out that the only inconsistent page with these properties is Settings -> Integrations.  The divider color that separates the top bar and side bar share the same color option for the cards on that page.

Looking at the inspector, the is card  for some reason inherits it's border color from `--state-color` which inherits it's color from `--divider-color`.  It should just use `--ha-card-border-color` without inheriting colors from any other variable.

Image

### Describe the behavior you expected

I'd expect the cards to use the theme's ha-card-border-color for the borders of the cards.

### Steps to reproduce the issue

1.  Use a theme with `ha-card-border-color: red` and `divider-color: blue`
2.  Go to Settings -> Integrations
3.  Notice the cards on the page match `divider-color: blue` not `ha-card-border-color: red`

### What version of Home Assistant Core has the issue?

core-2026.4.0b4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Windows FireFox, Windows Edge, Windows Chrome, iOS app, (did not check safari/chrome on iOS)

### Which operating system are you using to run this browser?

Windows and iOS

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Integration cards on the Settings > Integrations page unconditionally override `--ha-card-border-color` with `--state-color` (which resolves to `--divider-color`), ignoring the theme's `--ha-card-border-color`. This moves the override to only the state-specific CSS rules (error, warning, etc.) so the default border respects the theme.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #30397
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure
[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/panels/config/integrations/ha-integration-card.ts [hunk 1]
```diff
@@ -318,19 +317,23 @@ export class HaIntegrationCard extends LitElement {
         }
         .debug-logging {
           --state-color: var(--warning-color);
+          --ha-card-border-color: var(--state-color);
```
Comment (piitaya) [inline src/panels/config/integrations/ha-integration-card.ts:320]: Can't we just use `var(--warning-color)` directly?

Comment (MindFreeze) [reply src/panels/config/integrations/ha-integration-card.ts:320]: Wasn't sure if `--state-color` was used deeper for something

**Review by piitaya — APPROVED** [review]
