### PR TITLE
Local images flagged as already loaded to avoid flickering/slow-down

### LINKED ISSUE #9988: Problems with Picture-Elements
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Have an issue with `picture_elements `taking a long time to load, using only HA picture elements cards and 100x100px icons on a background image, all in www folder.
It is only since updating to 2021.9. Blue spinning circles and takes anything up to 20 seconds to load all the icons (before it was instant, never saw any loading)

Issue is on Chrome and Android HA app.

### Describe the behavior you expected

Not seeing the blue spinning circles as in 2021.8

### Steps to reproduce the issue

1. Picture elements cards with 100x100px icons
2.
3.
...
s=

### What version of Home Assistant Core has the issue?

2021.9

### What was the last working version of Home Assistant Core?

2021.8

### In which browser are you experiencing the issue with?

Chrome Version 93.0.4577.63 (Official Build) (64-bit)
Android HA App

### Which operating system are you using to run this browser?

Windows

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

```
type: picture-elements
image: /local/images/BG_BINStrans.png
elements:
  - type: image
    entity: sensor.green_bin_days
    image: /local/images/green_bin2.png
    title: null
    state_filter:
      "unavailable": grayscale(100%) drop-shadow(0px 0px 2px Red)
      "Today": drop-shadow(0px 0px 3px Green) saturate(200%)
      "Tomorrow": drop-shadow(0px 0px 3px Green) saturate(150%)
    style:
      top: 65%
      left: 15%
      width: 15%
  - type: state-label
    entity: sensor.green_bin_days
    tap_action:
      action: none
    hold_action:
      action: none
    style:
      top: 35%
      left: 15%

  - type: image
    entity: sensor.brown_bin_days
    image: /local/images/brown_bin2.png
    title: null
    state_filter:
      "unavailable": grayscale(100%) drop-shadow(0px 0px 2px Red)
      "Today": drop-shadow(0px 0px 3px Brown) saturate(200%)
      "Tomorrow": drop-shadow(0px 0px 3px Brown) saturate(150%)
    style:
      top: 65%
      left: 50%
      width: 15%
  - type: state-label
    entity: sensor.brown_bin_days
    tap_action:
      action: none
    hold_action:
      action: none
    style:
      top: 35%
      left: 50%

  - type: image
    entity: sensor.blue_bin_days
    image: /local/images/blue_bin2.png
    title: null
    state_filter:
      "unavailable": grayscale(100%) drop-shadow(0px 0px 2px Red)
      "Today": drop-shadow(0px 0px 3px Blue) saturate(200%)
      "Tomorrow": drop-shadow(0px 0px 3px Blue) saturate(150%)
    style:
      top: 65%
      left: 85%
      width: 15%
  - type: state-label
    entity: sensor.blue_bin_days
    tap_action:
      action: none
    hold_action:
      action: none
    style:
      top: 35%
      left: 85%
```

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

Similar issue (Closed)
https://github.com/home-assistant/frontend/issues/9968

### PR DESCRIPTION
**Pull request by smonesi**
## Proposed change

Since frontend release 20210825 (specifically PR https://github.com/home-assistant/frontend/pull/9690) a spinning loading image appears for every type of image (eg. in `picture-elements`). This slows down page loading and causes specific issues (eg. https://github.com/home-assistant/frontend/issues/9988 although a specific fix for `config-template-card` has been suggested).

This simple PR removes the spinning loading image for static images (ie. any image except cameras) because they should be loaded immediately and the spinner is useless.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

External image (will still have spinner):
```yaml
type: picture-elements
image: >-
  http://hs.sbcounty.gov/CN/Photo%20Gallery/_t/Sample%20Picture%20-%20Koala_jpg.jpg?Mobile=0
elements:
  - type: state-icon
    entity: sun.sun
```

Local image (no more spinner):
```yaml
type: picture-elements
image: >-
  /local/whatever/image.png
elements:
  - type: state-icon
    entity: sun.sun
```

## Additional information

- This PR fixes or closes issue: fixes #9988 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @smonesi, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;frontend#10086).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by bramkragten** [comment]
> I haven't checked what happens with camera images but I expect them not to have a static local path.

A camera will have a relative path, so this will not work


Like: `entity_picture: /api/camera_proxy/camera.id?token=xxx`

**Comment by smonesi** [comment]
Thanks for the information on cameras, I explicitly exclude them from my fix now (see my last commit), so they will still have the "loading" stage.

File: src/panels/lovelace/components/hui-image.ts [hunk 1]
```diff
@@ -161,6 +161,15 @@ export class HuiImage extends LitElement {
       imageSrc = this.image;
     }
 
+    if (
+      this._loadState === LoadState.Loading &&
+      !this.cameraImage &&
+      imageSrc &&
+      !imageSrc.startsWith("http")
+    ) {
```
Comment (bramkragten) [inline src/panels/lovelace/components/hui-image.ts:169]: I think it might be enough to show the spinner just for camera images

Comment (smonesi) [reply src/panels/lovelace/components/hui-image.ts:169]: I fully agree on this! However I wanted to provide minimum impact with my PR...

Do you think I can just do:
```
      this._loadState === LoadState.Loading &&
      !this.cameraImage &&
      imageSrc
    ) {
      this._loadState = LoadState.Loaded;
```
?

(I would read this as "if the image is still loading but it's not from camera and there is an actual image URL, then consider the image as already loaded")

Comment (bramkragten) [reply src/panels/lovelace/components/hui-image.ts:169]: We should move it to the rendering then

Comment (smonesi) [reply src/panels/lovelace/components/hui-image.ts]: I pushed this change. 

If you mean to change the rendering part (strictly speaking, ie. where the html is returned), I think there are more lines of code and checks to change there, rather than just change the state to "loaded" as I did so I'm not very confident to perform this change myself (also, I have no cameras, so it will be hard for me to check).

Comment (bramkragten) [reply src/panels/lovelace/components/hui-image.ts]: Add `this.cameraImage` on line 244: <https://github.com/home-assistant/frontend/pull/10086/files#diff-9e43694b64739d4f3f9ae00b65811d9954b15a6756aa734512c2877d9e909a04R244>

Comment (smonesi) [reply src/panels/lovelace/components/hui-image.ts]: I think there are multiple places where the concept of "Loading" vs "Loaded" is used, eg.:
```
          filter:
            this._loadState === LoadState.Loaded || this.cameraView === "live"
              ? filter
              : undefined,
```
```
                  display:
                    useRatio || this._loadState === LoadState.Loaded
                      ? "block"
                      : "none",
```

For this reason I preferred to maintain the logic (that is proved to be working) of having "Loaded" images managed as they are and force the state from "Loading" to "Loaded" for images that we know should never be in "Loading" state (ie. everything but cameras).

File: src/panels/lovelace/components/hui-image.ts [hunk 2]
```diff
@@ -161,6 +161,14 @@ export class HuiImage extends LitElement {
       imageSrc = this.image;
     }
 
+    if (
+      this._loadState === LoadState.Loading &&
+      !this.cameraImage &&
+      imageSrc
+    ) {
+      this._loadState = LoadState.Loaded;
+    }
```
Comment (bramkragten) [inline src/panels/lovelace/components/hui-image.ts:170]: Render should not have side effects, this should be done in `willUpdate`

File: src/panels/lovelace/components/hui-image.ts (hunk 1 above)
Comment (bramkragten) [reply src/panels/lovelace/components/hui-image.ts]: I see your point 👍

File: src/panels/lovelace/components/hui-image.ts (hunk 2 above)
Comment (smonesi) [reply src/panels/lovelace/components/hui-image.ts]: Good point!

**Review by bramkragten — APPROVED** [review]
