### PR TITLE
Fix number format for monetary device class

### LINKED ISSUE #15691: New precision feature still has problems with number format None
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

With the update to 2023.2.1 the precision feature with Number format set to None changed but still not working

I have 3 sensors. All are sensors that should report a price in DKK/kWh with two decimals

Here is how it looks like with Number format set to my system (English UK). Here it looks right.

image

And here with None. Why is the first number shows with 3 decimals? It does not matter what precision I choose. It is 3 decimals. And the unit it gone. Same for Nordpool. The unit is DKK/kWh. It is not shown. Why? These are the same electricity price but from 3 different integrations because they are often not updated correctly and I see the problem and can act when they are not the same.

image

The actual values without rounding off are

The Electricity Price (EDS) is 1.81386011609675
The Electricity Price Kamstrup is 1.81 - yes rounded by the template sensor to be displayed with 2 decimals
The Nordpool Electricity Price is 1.814 - it has 3 decimals from the source

Note the units.
When the number format is none - the units are gone. But only for some of the numbers. The unit handling in HA lately has become a mess and all the integrations do it differently. I just want the numbers show in the units_of

The EDS has 
unit_of_measurement: DKK/kWh
device_class: monetary

The Kamstrup only has
unit_of_measurement: DKK/kWh

The Nordpool has
unit_of_measurement: DKK/kWh
device_class: monetary

I have another one.

I have a sensor that shows a cost in DKK in very small numbers where I need all the decimals to see what is going on
The actual value is 0.018139 and the unit is DKK
unit_of_measurement: DKK
device_class: monetary

Here is the sensor displayed with Number format not set to None and I have chosen to see 6 decimals. I get 3 decimals. No matter what precision I select I get 3 decimals. And the unit it gone.

image

And now I set the Number format to my system. I get 2 decimals. No matter what precision I set. I cannot use that. I need to see this particular value with its precision. In fact I want all decimals. I have a unit. It is in the front of the value. I guess this makes sense in English for things with money and I can live with that.

image

### Describe the behavior you expected

I expect - no matter what Number Format I have

To see the number of decimals that I choose

No matter what number format
No matter what unit of measurement it is
No matter what device class it is

If I ask for 2 decimals I expect 2 decimals. If I ask for 4 decimals I expect 4 padded with 0's if needed

If I choose default - then I am I expect something intelligent and that may not fit my need. But that it OK as long as I can set the precision.

And if a unit_of_measurement is defined I expect it displayed. Always  Also if it is bananas/lightyears

### Steps to reproduce the issue

See above

### What version of Home Assistant Core has the issue?

core-2023.3.1

### What was the last working version of Home Assistant Core?

New feature

### In which browser are you experiencing the issue with?

Multiple browsers

### Which operating system are you using to run this browser?

Multiple OS Linux, Windows and iPad

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Fix number format for monetary device class

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #15691
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/common/number/format_number.ts [hunk 1]
```diff
@@ -82,17 +82,14 @@ export const formatNumber = (
     !Number.isNaN(Number(num)) &&
     num !== "" &&
     localeOptions?.number_format === NumberFormat.none &&
-    Intl &&
-    (options?.maximumFractionDigits != null ||
-      options?.minimumFractionDigits != null)
+    Intl
   ) {
-    // If NumberFormat is none, just set the digits options for precision and use en-US format without grouping.
+    // If NumberFormat is none, use en-US format without grouping.
```
Comment (piitaya) [inline src/common/number/format_number.ts:87]: Always use this function so any format will be used for format none (except grouping)

File: src/common/entity/compute_state_display.ts [hunk 2]
```diff
@@ -71,6 +71,11 @@ export const computeStateDisplayFromEntityAttributes = (
           style: "currency",
           currency: attributes.unit_of_measurement,
           minimumFractionDigits: 2,
+          // Override monetary options with number format
+          ...getNumberFormatOptions(
+            { state, attributes } as HassEntity,
+            entity
+          ),
```
Comment (piitaya) [inline src/common/entity/compute_state_display.ts:78]: monetary device class should use precision option.

**Review by bramkragten — APPROVED** [review]
