### PR TITLE
Echarts network graph for ZHA

### LINKED ISSUE #23968: Zigbee network visualization hard to read
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the ZHA Zigbee network visualization:
Image

The green and red colors are much too close in luminosity to be able to tell the nodes apart for someone who is red/green colorblind. As you can see in the image, the only data made available at that zoom level are the red/green shadings, so for someone who is red/green colorblind, it's hard to read the graph. I am mildly red/green colorblind and find it frustrating, but not impossible to read.

### Describe the behavior you expected

I recommend changing the green nodes to some other color, or using some other non-color way to signify that a node is offline (putting a little "!" near it? on it?). An alternative would be to make it so that the relative brightness/luminosity of the online vs. offline state are different. This is another clue that can help colorblind people distinguish between two states. Whatever solution is found can be tested using [the Chrome color vision deficiency dev tool](https://developer.chrome.com/docs/chromium/cvd) or others.

### Steps to reproduce the issue

1. Be red/green colorblind
2. Attempt to read the high-level overview of the ZHA graph, but find it lacking critical online/offline information for you
3. 
...

### What version of Home Assistant Core has the issue?

2025.1.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

For zigbee initially with intention to use this `ha-network-graph` for all OHF protocols in future PRs. Further generalization of can be done later.
I have tested various screen and network sizes but we need more testing on real networks.

Unlike the current graph, LQI and other info is displayed in tooltips to reduce clutter.

Active routes are used for the links with neighbor data used only as a fallback if a node has no routes.

Previous:
image

New:
image

Known issues:
- There is currently a [bug in echarts](https://github.com/apache/echarts/issues/20793) when hovering over the legend. It can be avoided by disabling `emphasis.focus: adjacency` but I think this feature is too useful to disable.
- Panning only works within the bounding rect of the graph nodes https://github.com/apache/echarts/issues/17214

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #23968 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by MindFreeze** [comment]
@puddly Give this a go on your network, please

**Comment by wendevlin** [comment]
I tested it with my network and 29 devices. :rocket: it finally can help to have a look at the visualizations :clap:

File: src/panels/config/integrations/integration-panels/zha/zha-network-visualization-page.ts [hunk 1]
```diff
@@ -144,358 +56,276 @@ export class ZHANetworkVisualizationPage extends LitElement {
...
+  private _createChartData(devices: ZHADevice[]): NetworkData {
+    const nodes: NetworkNode[] = [];
+    const links: NetworkLink[] = [];
+    const categories = [
+      {
+        name: "Coordinator",
+        icon: "roundRect",
+        itemStyle: { color: "#4CAF50" },
+      },
+      { name: "Router", icon: "circle", itemStyle: { color: "#2196F3" } },
```
[the remark this answers is not in the document]
Comment (MindFreeze) [reply src/panels/config/integrations/integration-panels/zha/zha-network-visualization-page.ts:154]: was just about to push that :D

**Comment by dmulcahey** [comment]
I’ll give it a go w/ mine too (~190 devices). This looks awesome!! Will report back within a couple days.

**Comment by puddly** [comment]
Amazing!

image

For comparison:

image

I'm going to play with a few options to reduce the density of these background neighbor links.

**Comment by dmulcahey** [comment]
this is amazing. Couple questions: is it possible to keep the double click actions on the nodes from the original (double click opened the device page) and the quick find that was there for a device? On smaller networks I could see why the thought could be that it isn't necessary but check this out: 

image

image

anyways this is absolutely awesome. Really love the way this is shaping up!

**Comment by MindFreeze** [comment]
We can do the double click again but it is not discoverable and not mobile friendly. I was thinking about changing that to clicking on the label but looking at your image that might not be very usable for large networks. Have to think about it more.
Definitely want to have the quick find but with highlighting instead of the zoom in. This will come in a later PR though.

**Comment by MindFreeze** [comment]
> Bundle size -2.38% 🎉

And the Graph component is loaded on demand so the initially loaded code should be even smaller

File: src/components/chart/ha-network-graph.ts [hunk 2]
```diff
@@ -0,0 +1,273 @@
...
+}
+
+export interface NetworkData {
+  nodes: NetworkNode[];
+  links: NetworkLink[];
+  categories?: { name: string }[];
+}
+
+// eslint-disable-next-line @typescript-eslint/naming-convention
+let GraphChart: any;
```
Comment (bramkragten) [inline src/components/chart/ha-network-graph.ts:56]:
```suggestion
let GraphChart: typeof import("echarts/lib/chart/graph/install");
```

File: src/components/chart/ha-network-graph.ts [hunk 3]
```diff
@@ -0,0 +1,273 @@
...
+  protected render() {
+    if (!GraphChart) {
+      return nothing;
+    }
+    return html`<ha-chart-base
+      .hass=${this.hass}
+      .data=${this._getSeries()}
+      .options=${this._createOptions()}
+      height="100%"
+      .extraComponents=${[GraphChart]}
```
Comment (bramkragten) [inline src/components/chart/ha-network-graph.ts:122]: Side note, `extraComponents` should not be a reactive property in `ha-chart-base`, as it will now always cause a re-render because we create a new array here every render. And `extraComponents` is not used during rendering.

File: src/components/chart/ha-network-graph.ts [hunk 4]
```diff
@@ -0,0 +1,273 @@
...
+    >
+      <slot name="button" slot="button"></slot>
+      <ha-icon-button
+        slot="button"
+        class="refresh-button ${this._physicsEnabled ? "active" : "inactive"}"
+        .path=${mdiGoogleCirclesGroup}
+        @click=${this._togglePhysics}
+        title=${this.hass.localize(
```
Comment (bramkragten) [inline src/components/chart/ha-network-graph.ts:130]:
```suggestion
        .label=${this.hass.localize(
```

File: src/components/chart/ha-network-graph.ts [hunk 5]
```diff
@@ -0,0 +1,273 @@
...
+    };
+  }
+
+  private _getSeries() {
+    if (!this.data) {
+      return [];
+    }
+
+    const containerWidth = this.clientWidth;
+    const containerHeight = this.clientHeight;
```
Comment (bramkragten) [inline src/components/chart/ha-network-graph.ts:162]: Should we add a resize controller then?

Comment (MindFreeze) [reply src/components/chart/ha-network-graph.ts:163]: I had added it but then I tried it without and it still worked fine so I removed it. I think it's because we only use this for the initial layout and after that echarts takes over and handles the resize.

**Comment by MindFreeze** [comment]
Some things are not translated but I'll fix that in the next PR

File: src/components/chart/ha-network-graph.ts [hunk 6]
```diff
@@ -0,0 +1,275 @@
...
+  value?: number;
+  symbolSize?: number;
+  symbol?: string;
+  itemStyle?: {
+    color?: string;
+    borderColor?: string;
+    borderWidth?: number;
+  };
+  fixed?: boolean;
+  polarDistance?: number; // distance from the center, where 0 is the center and 1 is the edge
```
Comment (wendevlin) [inline src/components/chart/ha-network-graph.ts:28]:
```suggestion
  /**
   * Distance from the center, where 0 is the center and 1 is the edge
   */
  polarDistance?: number;
```

this let vscode shows the hint inline, when using the interface.

File: src/panels/config/integrations/integration-panels/zha/zha-network-visualization-page.ts [hunk 7]
```diff
@@ -144,358 +58,296 @@ export class ZHANetworkVisualizationPage extends LitElement {
...
-        this.zoomedDeviceId
-      );
-      if (device) {
-        this._network!.fit({
-          nodes: [device.ieee],
-          animation: { duration: 500, easingFunction: "easeInQuad" },
-        });
+      const area = this.hass.areas[device.area_id];
+      if (area) {
+        label += `<br><b>Area: </b>${area.name}`;
```
Comment (wendevlin) [inline src/panels/config/integrations/integration-panels/zha/zha-network-visualization-page.ts:123]: @MindFreeze Should we add translations here?

Comment (MindFreeze) [reply src/panels/config/integrations/integration-panels/zha/zha-network-visualization-page.ts:123]: https://github.com/home-assistant/frontend/pull/25457#issuecomment-2889729140

**Review by wendevlin — APPROVED** [review]
