### PR TITLE
Fix sensor card graph not updating when value is unchanged

### LINKED ISSUE #29883: Sensor card not updating when sensor value is unchanged
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

At night, my solar production sensor stays at `0 W` for a long period.  
In this situation, the Sensor card does not update/re-render while the value remains unchanged.

Even though this is expected sensor data (continuous `0 W` at night), the card appears visually stale and only refreshes after a manual page reload or when the state value finally changes.

The Sensor card has stayed on the same display for 4 hours without any visible update.
Image

However, the History graph for the same entity clearly shows that the value has continuously remained at `0 W` during those same 4 hours.
Image

### Describe the behavior you expected

The Sensor card should continue to refresh/update in the same way the History graph.

### Steps to reproduce the issue

1. Use a solar production sensor that remains at `0 W` for an extended period (for example, overnight).
2. Add that entity to a Lovelace Sensor card (`type: sensor`).
3. Keep the dashboard open for several hours.
4. Observe that the Sensor card display does not update over time.
5. Open the History graph for the same entity and confirm it shows continuous `0 W` over the same period.

### What version of Home Assistant Core has the issue?

2026.3.0b1

### What was the last working version of Home Assistant Core?

2026.1

### In which browser are you experiencing the issue?

Google Chrome 145.0.7632.117

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

The `_redrawGraph` timer only cloned the coordinates array reference without recomputing from history data, so the time window never shifted forward.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #29883
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/panels/lovelace/header-footer/hui-graph-header-footer.ts [hunk 1]
```diff
@@ -190,10 +177,66 @@ export class HuiGraphHeaderFooter
...
+      return;
+    }
+    const entityId = this._config.entity;
+    const entityHistory = this._history[entityId];
+    if (entityHistory?.length) {
+      const purgeBeforeTimestamp =
+        (Date.now() - this._config.hours_to_show * 60 * 60 * 1000) / 1000;
+      const expiredStates = entityHistory.filter(
+        (entry) => entry.lu < purgeBeforeTimestamp
+      );
```
Comment (bramkragten) [inline src/panels/lovelace/header-footer/hui-graph-header-footer.ts]: We can skip one of the filters by doing:

```ts
let purgedHistory = entityHistory.filter(
          (entry) => entry.lu >= purgeBeforeTimestamp
        );
if (purgedHistory.length !== entityHistory.length) {
	...
}
```

**Review by bramkragten — APPROVED** [review]
