### PR TITLE
Gauge improvements

### LINKED ISSUE #30333: Guage card no longer shows arc below minimum as blue
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Gauge card redesign looks good; only one thing is missing/lost in the redesign ...
The card used to show a small *blue arc* for values above minimum and below green, with config below. The blue arc is no longer visible.

The native units GBP/h also used to fit within the arc and now overlap, so I had to change units to £/h to prevent the value from being too large in the new font. The new font is much easier to read. 

### Describe the behavior you expected

Blue arc for values below green

### Steps to reproduce the issue
```
type: gauge
entity: sensor.grid_import_real_time_energy_cost
needle: true
severity:
  green: 0
  yellow: 0.45
  red: 0.9
min: -0.05
name: " "
max: 1.9
unit: £/h
```

### What version of Home Assistant Core has the issue?

2026.4.b0

### What was the last working version of Home Assistant Core?

2026.3

### In which browser are you experiencing the issue?

Companion app

### Which operating system are you using to run this browser?

Android

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### LINKED ISSUE #30345: Gauge card only shows half when it has a name
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When i give a name to my gauge card it doesn't scale the gauge down anymore. Instead i only see the bottom half.

[https://imgur.com/a/v04Vl1L](https://imgur.com/a/v04Vl1L) (left is with a name, right is without a name)
YAML:

### Describe the behavior you expected

Before the card was scaled down in size so i could see the gauge as half the size.

### Steps to reproduce the issue

Gauge card with a name and grid options as follows:
grid_options:
  columns: 3
  rows: 1

### What version of Home Assistant Core has the issue?

2026.4.0b1

### What was the last working version of Home Assistant Core?

2026.3.4

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change
Back to dynamically changed font-size to match longer units. 
Different needle (rounded arrow, but shorter)
Fixed the case when min is not the first 0 from. 
Padding tweaks to make it like before but still better.
Back to butt rounding since smaller rounded corners require heavier calculation. 

- Fixes https://github.com/home-assistant/frontend/issues/30345
- Fixes https://github.com/home-assistant/frontend/issues/30333

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

**Comment by silamon** [comment]
I'm going to spend more time on this to let it look like this: 
image

**Comment by Mariusthvdb** [comment]
please also consider allowing control of the color of the needle. During beta we discovered it can be very difficult to see when on a darker severity color. 
Maybe auto set it to contrast the severity color

Scherm­afbeelding 2026-03-26 om 09 03 00

would be great if we could set a theme var to it so it isnt always black, but follows our themed designs

**Comment by bramkragten** [comment]
I think adding a border around the needle, like in the screenshot posted would fix this.

**Comment by Mariusthvdb** [comment]
yes that is a certain improvement indeed. looking forward to that.

the needle being black always and not following a themed variable makes it that stand out rather harshly against a text that does follow eg primary-text-color in the theme.

I can open a FR if you need that, but figured while in the process of follow-through here could suffice.

**Comment by silamon** [comment]
image

**Comment by Ainndy** [comment]
Inconsistent Font Scaling: The scaling logic for 2-digit vs. 4-digit numbers is too aggressive, leading to disproportionate font sizes that look uncoordinated. In v2026.3, the gauge text was a consistent 50px.
image

Static Text Positioning: When resizing the card, the text position remains fixed instead of scaling proportionally with the gauge arc. This causes the gap between the gauge scale and the text to stretch awkwardly as the card gets larger, breaking the visual balance.



https://github.com/user-attachments/assets/6a94bd1c-f315-40f1-800f-9a6766a06c1e

File: src/components/ha-gauge.ts [hunk 1]
```diff
@@ -204,6 +212,18 @@ export class HaGauge extends LitElement {
...
 
+  private _rescaleSvg() {
+    // Set the viewbox of the SVG containing the value to perfectly
+    // fit the text
+    // That way it will auto-scale correctly
+    const svgRoot = this.shadowRoot!.querySelector(".text")!;
+    const box = svgRoot.querySelector("text")!.getBBox()!;
+    svgRoot.setAttribute(
+      "viewBox",
+      `${box.x} ${box!.y} ${box.width} ${box.height}`
```
Comment (MindFreeze) [inline src/components/ha-gauge.ts]:
```suggestion
      `${box.x} ${box.y} ${box.width} ${box.height}`
```

File: src/components/ha-gauge.ts [hunk 2]
```diff
@@ -88,87 +90,92 @@ export class HaGauge extends LitElement {
...
+                  const x1 =
+                    -arcRadius * Math.cos((startAngle * Math.PI) / 180);
+                  const y1 =
+                    -arcRadius * Math.sin((startAngle * Math.PI) / 180);
+                  const x2 = -arcRadius * Math.cos((endAngle * Math.PI) / 180);
+                  const y2 = -arcRadius * Math.sin((endAngle * Math.PI) / 180);
+
+                  const isFirst = i === 0;
+                  const isLast = i === arr.length - 1;
+                  const linecap = "butt";
```
Comment (MindFreeze) [inline src/components/ha-gauge.ts]: This var doesn't change and it's hardcoded to "butt" almost everywhere so we don't need it

**Comment by silamon** [comment]
> Inconsistent Font Scaling: The scaling logic for 2-digit vs. 4-digit numbers is too aggressive, leading to disproportionate font sizes that look uncoordinated. In v2026.3, the gauge text was a consistent 50px. image
> 
> Static Text Positioning: When resizing the card, the text position remains fixed instead of scaling proportionally with the gauge arc. This causes the gap between the gauge scale and the text to stretch awkwardly as the card gets larger, breaking the visual balance.
> 
>  hapcb.mp4

This is what it was in 2026.3:
image

It's the same behavior as before and to be honest, also the same code I putted back in.

**Comment by Ainndy** [comment]
> > Inconsistent Font Scaling: The scaling logic for 2-digit vs. 4-digit numbers is too aggressive, leading to disproportionate font sizes that look uncoordinated. In v2026.3, the gauge text was a consistent 50px. image
> > Static Text Positioning: When resizing the card, the text position remains fixed instead of scaling proportionally with the gauge arc. This causes the gap between the gauge scale and the text to stretch awkwardly as the card gets larger, breaking the visual balance.
> > hapcb.mp4
> 
> This is what it was in 2026.3: image
> 
> It's the same behavior as before and to be honest, also the same code I putted back in.

image

image

image

File: src/components/ha-gauge.ts [hunk 3]
```diff
@@ -224,32 +243,43 @@ export class HaGauge extends LitElement {
...
-      stroke-linecap: round;
+      stroke-linecap: butt;
       transition: stroke-dashoffset 1s ease 0s;
     }
 
     .needle {
-      stroke: var(--primary-text-color);
-      stroke-width: 2;
+      fill: var(--primary-text-color);
+      stroke: var(--card-background-color);
```
Comment (wendevlin) [inline src/components/ha-gauge.ts:266]: what about a transparency for this stroke? Just an idea not sure if it looks nice.

Comment (silamon) [reply src/components/ha-gauge.ts:266]: I don't think that's going to be a good idea. The full white (or black depending on theme) behind it makes the contrast better to see where the needle exactly is. We've already received a lot of feedback that this is important for some users.

Comment (Mariusthvdb) [reply src/components/ha-gauge.ts:266]: would it be possible to give needle  it its own variable? so we can theme independently from text-color/background-color? might seem niche, but given the many different uses for a gauge, it would be a welcome option to be able to differentiate

**Comment by Ainndy** [comment]
The gauge is looking much closer to the original now.  Vertical spacing is still too large,

image

image

File: src/components/ha-gauge.ts [hunk 4]
```diff
@@ -88,87 +90,91 @@ export class HaGauge extends LitElement {
...
-                  x2="-45.0"
-                  y2="0"
-                  style=${styleMap({ transform: `rotate(${this._angle}deg)` })}
-                />
+                <path
+                class="needle"
+                d="M -36,-2 L -44,-1 A 1,1,0,0,0,-44,1 L -36,2 A 2,2,0,0,0,-36,-2 Z"
+
+                style=${styleMap({ transform: `rotate(${this._angle}deg)` })}
+              >
```
Comment (MindFreeze) [inline src/components/ha-gauge.ts]:
```suggestion
              />
```

**Comment by silamon** [comment]
> The gauge is looking much closer to the original now. Vertical spacing is still too large,

That looks like an old version, since the rounded borders around the gauge are gone. 

---

If nothing is keeping this from merge, then let's merge.

**Review by MindFreeze — APPROVED** [review]
I liked the earlier, more rounded design but we have to take baby steps, I guess

**Comment by Ainndy** [comment]
> > The gauge is looking much closer to the original now. Vertical spacing is still too large,
> 
> That looks like an old version, since the rounded borders around the gauge are gone.
> 
> If nothing is keeping this from merge, then let's merge.

You might be misinterpreting my point. It’s not about the borders—the main issue is the vertical spacing around the Title.

1. The gap between the Title and the Gauge itself is far too large.
2. There is also excessive whitespace below the Title.

**Comment by silamon** [comment]
> > > The gauge is looking much closer to the original now. Vertical spacing is still too large,
> > 
> > 
> > That looks like an old version, since the rounded borders around the gauge are gone.
> > If nothing is keeping this from merge, then let's merge.
> 
> You might be misinterpreting my point. It’s not about the borders—the main issue is the vertical spacing around the Title.
> 
> 1. The gap between the Title and the Gauge itself is far too large.
> 2. There is also excessive whitespace below the Title.

Could you post your card configuration so I can check this case specific? 

EDIT: There's an extra 5px between gauge and title so that the needle is fully shown. Is that what we're talking about?

**Comment by Ainndy** [comment]
> > > > The gauge is looking much closer to the original now. Vertical spacing is still too large,
> > > 
> > > 
> > > That looks like an old version, since the rounded borders around the gauge are gone.
> > > If nothing is keeping this from merge, then let's merge.
> > 
> > 
> > You might be misinterpreting my point. It’s not about the borders—the main issue is the vertical spacing around the Title.
> > 
> > 1. The gap between the Title and the Gauge itself is far too large.
> > 2. There is also excessive whitespace below the Title.
> 
> Could you post your card configuration so I can check this case specific?
> 
> EDIT: There's an extra 5px between gauge and title so that the needle is fully shown. Is that what we're talking about?

image
There is excessive vertical whitespace above and below the title.

-----
[https://github.com/ofekashery/vertical-stack-in-card](https://github.com/ofekashery/vertical-stack-in-card)
```
type: custom:vertical-stack-in-card
cards:
  - type: custom:vertical-stack-in-card
    cards:
      - type: gauge
        name: CPU
        entity: sensor.test
        needle: false
        severity:
          green: 0
          yellow: 60
          red: 85
      - type: gauge
        name: RAM
        entity: sensor.test
        needle: false
        severity:
          green: 0
          yellow: 60
          red: 85
      - type: gauge
        name: Disk
        entity: sensor.test
        needle: false
        severity:
          green: 0
          yellow: 60
          red: 85
      - type: gauge
        name: CPU
        entity: sensor.test
        needle: false
        severity:
          green: 0
          yellow: 60
          red: 85
  - type: markdown
    content: >-
      The **Markdown** card allows you to write any text. You can style it
      **bold**, *italicized*, ~strikethrough~ etc. You can do images, links, and
      more.
```

**Comment by silamon** [comment]
The padding has been removed in tha latest version. You are still running the old version somehow.

**Comment by Ainndy** [comment]
> The padding has been removed in tha latest version. You are still running the old version somehow.

My apologies! I was still on Beta 7 when I saw that. I've updated to the latest version now and it looks great. Thank you for the hard work and for listening to the feedback!
