### PR TITLE
Fix dropdown selection in General Settings

### LINKED ISSUE #16722: Language selection in General Settings not sticking (2023.6 beta)
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Currently on Beta 2023.6.0b2.

I am unable to test some entity name translations as changing the language from English to another language does not stick. See below:

ezgif com-video-to-gif

Edit:
Just checked on Home Assistant 2023.5.4: Changing the language works as expected. So, it seems like the bug was introduced starting with 2023.6.0b0

### Describe the behavior you expected

Expected newly selected language to remain selected.

### Steps to reproduce the issue

1. Go to general settings
2. Select new language
3. Click on update
4. Exit general settings and return back to general settings

### What version of Home Assistant Core has the issue?

2023.6.0b0, 2023.6.0b1, 2023.6.0b2

### What was the last working version of Home Assistant Core?

2023.5.4

### In which browser are you experiencing the issue with?

Edge Chromium (113.0.1774.57), Safari (16.4.1), iOS Home Assistant app

### Which operating system are you using to run this browser?

macOS Monterey 12.6.5

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change

Dropdown selection is not working from the General Settings. 
Introduced after refactoring in #16514, fixes #16722. 

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/core/ha-config-section-general.ts [hunk 1]
```diff
@@ -19,15 +19,15 @@ import "../../../components/ha-radio";
 import type { HaRadio } from "../../../components/ha-radio";
 import "../../../components/ha-select";
 import "../../../components/ha-settings-row";
-import "../../../components/ha-textfield";
```
Comment (bramkragten) [inline src/panels/config/core/ha-config-section-general.ts:22]: You are missing this import now

File: src/panels/config/core/ha-config-section-general.ts [hunk 2]
```diff
@@ -19,15 +19,15 @@ import "../../../components/ha-radio";
...
 import "../../../components/ha-timezone-picker";
 import "../../../components/map/ha-locations-editor";
 import type { MarkerLocation } from "../../../components/map/ha-locations-editor";
 import { ConfigUpdateValues, saveCoreConfig } from "../../../data/core";
 import { showConfirmationDialog } from "../../../dialogs/generic/show-dialog-box";
 import "../../../layouts/hass-subpage";
 import { haStyle } from "../../../resources/styles";
-import type { HomeAssistant } from "../../../types";
+import type { HomeAssistant, ValueChangedEvent } from "../../../types";
+import { HaTextField } from "../../../components/ha-textfield";
```
Comment (bramkragten) [inline src/panels/config/core/ha-config-section-general.ts:30]:
```suggestion
import type { HaTextField } from "../../../components/ha-textfield";
import "../../../components/ha-textfield";
```

File: src/panels/config/core/ha-config-section-general.ts [hunk 3]
```diff
@@ -303,11 +303,11 @@ class HaConfigSectionGeneral extends LitElement {
 
   private _handleValueChanged(ev) {
     const target = ev.currentTarget;
-    this[`_${target.name}`] = ev.detail.value;
+    this[`_${target.getAttribute("name")}`] = ev.detail.value;
   }
 
-  private _handleChange(ev) {
-    const target = ev.currentTarget;
+  private _handleChange(ev: ValueChangedEvent<string>) {
```
Comment (bramkragten) [inline src/panels/config/core/ha-config-section-general.ts:309]:
```suggestion
  private _handleChange(ev: Event) {
```

File: src/panels/config/core/ha-config-section-general.ts [hunk 4]
```diff
@@ -303,11 +303,11 @@ class HaConfigSectionGeneral extends LitElement {
 
   private _handleValueChanged(ev) {
```
Comment (bramkragten) [inline src/panels/config/core/ha-config-section-general.ts:304]:
```suggestion
  private _handleValueChanged(ev: ValueChangedEvent<string>) {
```

**Review by bramkragten — APPROVED** [review]

**Comment by bramkragten** [comment]
Thanks!
