### PR TITLE
Set initial focus for lovelace dialogs

### LINKED ISSUE #10754: Modal dialogs need keyboard focus management
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For nearly all modal dialogs I can think of, the keyboard focus does not transfer to the dialog as it should for accessibility.  I need to to click or space bar once  to get the focus inside the dialog to be able to read it with a screen reader.  Furthermore, after closing a dialog with escape or button, keyboard focus is transferred all the way back to the beginning of the page DOM, instead of back to the button which opened the dialog as expected.

### Describe the behavior you expected

In general, these dialogs should all follow the [modal dialog design pattern in the W3C ARIA Authoring Practices](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal).  These design patterns have detailed notes on managing keyboard focus.

### Steps to reproduce the issue

For example, I might go to Configuration → Entities and:
1. Click on an entity to get it's settings dialog, and then click again to read it
2. Click the control button to get that dialog, then have to click again to read it
3. Click the attributes button, then have to click again to read them
4. Hit escape to get out, then have to navigate back to where I started

2.
3.
...
For example, I might go to Configuration → Entities and:
1. Click on an entity to get it's settings dialog, and then click again to read it
2. Click the control button to get that dialog, then have to click again to read it
3. Click the attributes button, then have to click again to read them
4. Hit escape to get out, then have to navigate back to where I started

### What version of Home Assistant Core has the issue?

Any

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Firefox & Chrome (latest stable)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

I suspect that the cause of this may be also causing lots of other "double action" keyboard issues throughout the UI, but I figured I'd keep this issue tight and to the point rather than jumping to that conclusion.

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

| Dialog Module | Initial Focus | Notes |
|:------ |:----:|:----- |
| dialog-lovelace-dashboard-detail | Title field or Close button | Title field was already done |
| dialog-lovelace-resource-detail | URL field | Already done |
| hui-dialog-save-config | checkbox or yaml editor | ❓ I can't figure out when the `ha-yaml-editor` comes into play in order to test |
| hui-dialog-create-card | By Card tab |  |
| hui-dialog-delete-card | Cancel button |  |
| hui-dialog-edit-card | `hui-card-element-editor` | 🔜 This is the right element to call focus, but a separate PR to get it working and tested for all cards is probably best |
| hui-dialog-suggest-card | Cancel button | Again, I have no idea when `ha-yaml-editor` gets invoked, but cancel button probably still appropriate for initial focus |
| hui-dialog-create-headerfooter | First card button | I converted the choices to buttons because they were inaccessible |
| hui-dialog-edit-lovelace | `hui-lovelace-editor` | ❓ I have no idea how to invoke this dialog |
| hui-dialog-select-view | Dashboard dropdown, View radio, or Cancel button | ❔ Radio group won't work as fallback in all browsers because of different treatment of focusing disabled controls.  Why not just eliminate the dropdown instead of disabling it? |
| hui-dialog-edit-view | Settings tab |  |

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR partially fixes or closes issue: #10754 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

File: src/panels/lovelace/editor/header-footer-editor/hui-dialog-create-headerfooter.ts [hunk 1]
```diff
@@ -56,15 +56,20 @@ export class HuiCreateDialogHeaderFooter
...
+                  aria-labeledby=${"card-name-" + index}
                   outlined
                   .type=${headerFooter.type}
                   @click=${this._handleHeaderFooterPicked}
+                  @keyDown=${this._handleHeaderFooterPicked}
+                  dialogInitialFocus
                 >
                   <ha-svg-icon .path=${headerFooter.icon}></ha-svg-icon>
-                  <div>
+                  <div id=${"card-name-" + index} role="none presentation">
```
Comment (bramkragten) [inline src/panels/lovelace/editor/header-footer-editor/hui-dialog-create-headerfooter.ts:72]:
```suggestion
                  <div .id=${"card-name-" + index} role="none presentation">
```

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
