### PR TITLE
Make energy graph colors brighter in dark mode

### LINKED ISSUE #9953: Energy Graphs need different color-set for dark mode
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have my HA Theme set to dark mode.   The Energy graphs tend towards darker colors for the individual items, and therefore there's not enough difference in the colors to differentiate between the individual items on a graph.  In the graph below, there are two items in the dark bars at the right (but you can't tell.  If a lighter color palette were used when in Dark mode, the colors might not run together.  It looks like there is a similar issue when in Light mode, but at least you can tell the borders between the shades of dark grey.

As you can see, there are 7 items on the graph column, but you can only differentiate between 4:

image

### Describe the behavior you expected

Being able to differentiate between multiple items on the same bar

### Steps to reproduce the issue

1. Set Theme=Dark (or Theme=Auto) on personal profile page
2.Navigate to Energy page and view a weekly or monthly graph
3.
...

### What version of Home Assistant Core has the issue?

2021.9.2

### What was the last working version of Home Assistant Core?

2021.9.2

### In which browser are you experiencing the issue with?

Chrome, Latest

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
n/a, energy values constantly fluctuate
```

### Problem-relevant frontend configuration

```yaml
Theme: Dark, or Auto (PC is set to Dark mode, so Auto follows System setting)
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

In dark mode we now make the colors incrementally brighter, rather than darker.

image

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9953
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — DISMISSED** [review]

File: src/panels/lovelace/cards/energy/hui-energy-solar-graph-card.ts [hunk 1]
```diff
@@ -258,10 +258,11 @@ export class HuiEnergySolarGraphCard
       const data: ChartDataset<"bar" | "line">[] = [];
       const entity = this.hass.states[source.stat_energy_from];
 
+      const modifiedColor = this.hass.themes.darkMode
+        ? labBrighten(rgb2lab(hex2rgb(solarColor)), idx)
+        : labDarken(rgb2lab(hex2rgb(solarColor)), idx);
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/hui-energy-solar-graph-card.ts:263]: We should only do this if idx > 0

File: src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts [hunk 2]
```diff
@@ -170,12 +170,13 @@ export class HuiEnergySourcesTableCard
                     this._data!.stats[source.stat_energy_from]
                   ) || 0;
                 totalSolar += energy;
+
+                const modifiedColor = this.hass.themes.darkMode
+                  ? labBrighten(rgb2lab(hex2rgb(solarColor)), idx)
+                  : labDarken(rgb2lab(hex2rgb(solarColor)), idx);
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts:176]: We should only do this if idx > 0

File: src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts [hunk 3]
```diff
@@ -229,22 +230,20 @@ export class HuiEnergySourcesTableCard
                     this._data!.stats[source.stat_energy_to]
                   ) || 0;
                 totalBattery += energyFrom - energyTo;
+
+                const modifiedFromColor = this.hass.themes.darkMode
+                  ? labBrighten(rgb2lab(hex2rgb(batteryFromColor)), idx)
+                  : labDarken(rgb2lab(hex2rgb(batteryFromColor)), idx);
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts:236]: We should only do this if idx > 0

File: src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts [hunk 4]
```diff
@@ -229,22 +230,20 @@ export class HuiEnergySourcesTableCard
...
-                    ? rgb2hex(
-                        lab2rgb(
-                          labDarken(rgb2lab(hex2rgb(batteryFromColor)), idx)
-                        )
-                      )
+                    ? rgb2hex(lab2rgb(modifiedFromColor))
                     : batteryFromColor;
+                const modifiedToColor = this.hass.themes.darkMode
+                  ? labBrighten(rgb2lab(hex2rgb(batteryToColor)), idx)
+                  : labDarken(rgb2lab(hex2rgb(batteryToColor)), idx);
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts:243]: We should only do this if idx > 0

File: src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts [hunk 5]
```diff
@@ -331,14 +330,15 @@ export class HuiEnergySourcesTableCard
                   if (cost !== null) {
                     totalGridCost += cost;
                   }
+
+                  const modifiedColor = this.hass.themes.darkMode
+                    ? labBrighten(rgb2lab(hex2rgb(consumptionColor)), idx)
+                    : labDarken(rgb2lab(hex2rgb(consumptionColor)), idx);
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts:336]: We should only do this if idx > 0

File: src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts [hunk 6]
```diff
@@ -391,12 +391,13 @@ export class HuiEnergySourcesTableCard
                   if (cost !== null) {
                     totalGridCost += cost;
                   }
+
+                  const modifiedColor = this.hass.themes.darkMode
+                    ? labBrighten(rgb2lab(hex2rgb(returnColor)), idx)
+                    : labDarken(rgb2lab(hex2rgb(returnColor)), idx);
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts:397]: We should only do this if idx > 0

File: src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts [hunk 7]
```diff
@@ -473,12 +474,13 @@ export class HuiEnergySourcesTableCard
                 if (cost !== null) {
                   totalGasCost += cost;
                 }
+
+                const modifiedColor = this.hass.themes.darkMode
+                  ? labBrighten(rgb2lab(hex2rgb(gasColor)), idx)
+                  : labDarken(rgb2lab(hex2rgb(gasColor)), idx);
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts:480]: We should only do this if idx > 0

File: src/panels/lovelace/cards/energy/hui-energy-usage-graph-card.ts [hunk 8]
```diff
@@ -477,10 +477,12 @@ export class HuiEnergyUsageGraphCard
       Object.entries(sources).forEach(([statId, source], idx) => {
         const data: ChartDataset<"bar">[] = [];
         const entity = this.hass.states[statId];
+
+        const modifiedColor = this.hass.themes.darkMode
+          ? labBrighten(rgb2lab(hex2rgb(colors[type])), idx)
+          : labDarken(rgb2lab(hex2rgb(colors[type])), idx);
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/hui-energy-usage-graph-card.ts:483]: We should only do this if idx > 0

File: src/panels/lovelace/cards/energy/hui-energy-gas-graph-card.ts [hunk 9]
```diff
@@ -247,10 +247,10 @@ export class HuiEnergyGasGraphCard
       const data: ChartDataset<"bar" | "line">[] = [];
       const entity = this.hass.states[source.stat_energy_from];
 
-      const borderColor =
-        idx > 0
-          ? rgb2hex(lab2rgb(labDarken(rgb2lab(hex2rgb(gasColor)), idx)))
-          : gasColor;
+      const modifiedColor = this.hass.themes.darkMode
+        ? labBrighten(rgb2lab(hex2rgb(gasColor)), idx)
+        : labDarken(rgb2lab(hex2rgb(gasColor)), idx);
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/hui-energy-gas-graph-card.ts:252]: We should only do this if idx > 0

File: src/panels/lovelace/cards/energy/hui-energy-gas-graph-card.ts [hunk 10]
```diff
@@ -247,10 +247,10 @@ export class HuiEnergyGasGraphCard
...
+      const borderColor = idx > 0 ? rgb2hex(lab2rgb(modifiedColor)) : gasColor;
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/hui-energy-gas-graph-card.ts:253]:
```suggestion
	  const modifiedColor =
	    idx > 0
	      ? this.hass.themes.darkMode
	        ? labBrighten(rgb2lab(hex2rgb(gasColor)), idx)
	        : labDarken(rgb2lab(hex2rgb(gasColor)), idx)
	      : undefined;
	  const borderColor = modifiedColor ? rgb2hex(lab2rgb(modifiedColor)) : gasColor;
```

**Review by bramkragten — APPROVED** [review]
