### PR TITLE
FIx selecting service/url path action after choosing default action

### LINKED ISSUE #9363: Tap Action dropdown fails after after selection default action
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In a button card, there is a Tap Action dropdown. Selecting an action show more info if needed, like for an URL or service. Selectin 'Default Action' 1st and than the URL action, doesn't give you the extra options to select anymore. Need to select an other option first.

### Describe the behavior you expected

Using the dropdown Tap Action should always work whatever option I select.

### Steps to reproduce the issue

1. Create a button card
2. Select URL in tap action
3. you see the extra URL field
4. select Dafault Action
5. select URL again
6. no extra field is shown for the url

### What version of Home Assistant Core has the issue?

core-2021.6.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes #9363

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/components/hui-action-editor.ts [hunk 1]
```diff
@@ -33,18 +33,18 @@ export class HuiActionEditor extends LitElement {
   @property() protected hass?: HomeAssistant;
 
   get _navigation_path(): string {
-    const config = this.config as NavigateActionConfig;
+    const config = this.config as NavigateActionConfig | undefined;
     return config.navigation_path || "";
```
Comment (ludeeus) [inline src/panels/lovelace/components/hui-action-editor.ts:37]:
```suggestion
    return config?.navigation_path || "";
```

**Review by ludeeus — APPROVED** [review]
