### PR TITLE
Fix outline on mouseover in firefox

### LINKED ISSUE #7050: Outline on mouseover broken in Firefox
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Outline around items is Firefox is broken again when in Edit dashboard mode:
Works fine in Chrome based browsers.

This was fixed by @thomasloven in #5430 but was broken again in #6132.

firefox_FigahHpAXt

## Expected behavior

vivaldi_sknLUG6jVN

## Steps to reproduce

Go to Edit Dashboard in Firefox and mouse over any of the cards.

## Environment

- Home Assistant release with the issue: 0.115
- Last working Home Assistant release (if known): 0.108
- Browser and browser version: Firefox 80.0.1 x64
- Operating system: Windows 10 x64 1909

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

edit. fixed incorrect mention

### PR DESCRIPTION
**Pull request by thomasloven**
## Proposed change

Fix #7050, see #5430 

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/components/hui-card-options.ts [hunk 1]
```diff
@@ -99,6 +99,7 @@ export class HuiCardOptions extends LitElement {
   static get styles(): CSSResult {
     return css`
       :host(:hover) {
+        overflow: hidden;
```
Comment (bramkragten) [inline src/panels/lovelace/components/hui-card-options.ts:102]: This breaks the overflow menu

Comment (bramkragten) [reply src/panels/lovelace/components/hui-card-options.ts:102]: image

**Comment by thomasloven** [comment]
The... *behavior*... seems to be related to absolutely positioned elements, but for some reason giving the card `display: block`makes it go away. The new fix should not interfere with the menu.

**Review by bramkragten — APPROVED** [review]
