### PR TITLE
Handle tiny values in a log chart

### LINKED ISSUE #25678: History graph card: logarithmic y-axis limited to 0.1
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The History graph card on the UI always a minimum of 0.1 even if I set the minimum to be lower (such as 0.001).

### Describe the behavior you expected

I can hover over the data on the graph and see that it is 0.04, but the axis label is always stuck at 0.1. 

### Steps to reproduce the issue

1. Have data with values below 0.1. 
2. Create a history graph card.
3.  type: history-graph
entities:
  - entity: sensor.pt1_plate_t
    name: PT1
  - entity: sensor.pt2_plate_t
    name: PT2
  - entity: sensor.still_plate_t
    name: Still
  - entity: sensor.cold_plate_t
    name: Cold Plate
  - entity: sensor.mc_plate_cernox_t
    name: MC CX
  - entity: sensor.mc_plate_ruo2_t
    name: MC RuO2
logarithmic_scale: true
hours_to_show: 72
grid_options:
  columns: full
  rows: 6
fit_y_data: false
min_y_axis: 0.001
max_y_axis: 300
4. 

Image

### What version of Home Assistant Core has the issue?

2025.5.3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #25678
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by silamon — APPROVED** [review]

File: src/components/chart/state-history-chart-line.ts [hunk 1]
```diff
@@ -229,14 +229,20 @@ export class StateHistoryChartLine extends LitElement {
           minYAxis = ({ min }) => Math.min(min, this.minYAxis!);
         }
       } else if (this.logarithmicScale) {
-        minYAxis = ({ min }) => Math.floor(min > 0 ? min * 0.95 : min * 1.05);
+        minYAxis = ({ min }) => {
+          const value = min > 0 ? min * 0.95 : min * 1.05;
+          return Math.abs(value) < 1 ? value : Math.floor(value);
```
Comment (Marchat9) [inline src/components/chart/state-history-chart-line.ts:234]: Hello,
To understand, why would you want to keep the precise values between -1 and 1 ?
Thanks.
