### PR TITLE
Energy: Wait with subscribe for _config to be set

### LINKED ISSUE #11829: Energy dashboard stopped working
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Changing energy monitoring time interval have no effect on displayed data.
Day:
image
Week:
image

On mobile app it is working correctly.

### Describe the behavior you expected

Show the energy usage for the selected interval.

### Steps to reproduce the issue

1.Select Energy Dashboard
2.Switch View Drom Day to Week (Month, ...)
3.Check displayed data
...

### What version of Home Assistant Core has the issue?

core-2022.3.0b1

### What was the last working version of Home Assistant Core?

core_2022.2.9

### In which browser are you experiencing the issue with?

Google Chrome Version 98.0.4758.102 / Microsoft Edge Version 98.0.1108.56

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Fixes https://github.com/home-assistant/frontend/issues/11829

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by balloob — DISMISSED** [review]

File: src/mixins/subscribe-mixin.ts [hunk 1]
```diff
@@ -13,6 +13,8 @@ export const SubscribeMixin = <T extends Constructor<ReactiveElement>>(
   class SubscribeClass extends superClass {
     @property({ attribute: false }) public hass?: HomeAssistant;
 
+    protected hassSubscribeNeedsProperties?: string[];
```
Comment (balloob) [inline src/mixins/subscribe-mixin.ts:16]: Let's add comment what it does.

**Review by zsarnett — APPROVED** [review]
