### PR TITLE
Fix ha-wa-dialog fullscreen and make alerts not fullscreen

### LINKED ISSUE #28193: ha-wa-dialog safe areas on iOS
### Description

~Appears to have a negative safe area. Need to make sure safe areas are clamped~

Image

Image

### Additional context

We also need to make the alert/confirmation box dialog not fullscreen

### PR DESCRIPTION
**Pull request by timmo001**
## Proposed change

Alert dialogs are no longer fullscreen, safe area bounds are set with max-height/width and transformation

Screenshots using safe areas of:

<details>
<summary>Android (Pixel 10) - Landscape (left)</summary>

```css
    --app-safe-area-inset-bottom: 36px;
    --app-safe-area-inset-left: 68px;
```

Standard wa dialogs:
image

image

image

</details>

<details>
<summary>All safe areas set</summary>

```css
    --app-safe-area-inset-top: 64px;
    --app-safe-area-inset-bottom: 36px;
    --app-safe-area-inset-left: 48px;
    --app-safe-area-inset-right: 24px;
```

image
image
image
image
image

image
image

</details>

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #28193
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-wa-dialog.ts [hunk 1]
```diff
@@ -84,6 +85,9 @@ export class HaWaDialog extends LitElement {
   @property({ type: Boolean, reflect: true })
   public open = false;
 
+  @property({ type: String, reflect: true, attribute: "type" })
```
Comment (bramkragten) [inline src/components/ha-wa-dialog.ts]:
```suggestion
  @property({ reflect: true })
```

File: src/components/ha-wa-dialog.ts [hunk 2]
```diff
@@ -141,11 +145,13 @@ export class HaWaDialog extends LitElement {
             .showBorder=${this._bodyScrolled}
           >
             <slot name="headerNavigationIcon" slot="navigationIcon">
-              <ha-icon-button
-                data-dialog="close"
-                .label=${this.hass?.localize("ui.common.close") ?? "Close"}
-                .path=${mdiClose}
-              ></ha-icon-button>
+              ${this.type === "alert"
```
Comment (bramkragten) [inline src/components/ha-wa-dialog.ts]: Why is this handled here and not in `dialog-box`?

File: src/dialogs/generic/dialog-box.ts [hunk 3]
```diff
@@ -60,35 +59,32 @@ class DialogBox extends LitElement {
...
       <ha-wa-dialog
         .hass=${this.hass}
         .open=${this._open}
+        type=${confirmPrompt ? "alert" : "standard"}
         ?prevent-scrim-close=${confirmPrompt}
+        aria-labelledby=${ifDefined(titleId)}
         @closed=${this._dialogClosed}
-        aria-labelledby="dialog-box-title"
         aria-describedby="dialog-box-description"
+        header-title=${ifDefined(
```
Comment (bramkragten) [inline src/dialogs/generic/dialog-box.ts]: this should be set as a property not an attribute

File: src/resources/theme/main.globals.ts [hunk 4]
```diff
@@ -28,13 +28,16 @@ export const mainStyles = css`
     --margin-title-rtl: 0 24px 0 0;
 
     /* safe-area-insets */
-    --safe-area-inset-top: var(--app-safe-area-inset-top, env(safe-area-inset-top, 0));
-    --safe-area-inset-bottom: var(--app-safe-area-inset-bottom, env(safe-area-inset-bottom, 0));
-    --safe-area-inset-left: var(--app-safe-area-inset-left, env(safe-area-inset-left, 0));
-    --safe-area-inset-right: var(--app-safe-area-inset-right, env(safe-area-inset-right, 0));
+    --safe-area-inset-top: max(var(--app-safe-area-inset-top, env(safe-area-inset-top, 0)), 0px);
```
Comment (bramkragten) [inline src/resources/theme/main.globals.ts]: Why the max? safe area can never be negative right?

File: src/dialogs/generic/dialog-box.ts [hunk 5]
```diff
@@ -60,35 +59,32 @@ class DialogBox extends LitElement {
...
-                  data-dialog="close"
-                  .label=${this.hass?.localize("ui.common.close") ?? "Close"}
-                  .path=${mdiClose}
-                ></ha-icon-button
-              ></slot>`
-            : nothing}
-          <span slot="title" id="dialog-box-title">
-            ${this._params.warning
-              ? html`<ha-svg-icon
+        ${this._params.warning
```
Comment (bramkragten) [inline src/dialogs/generic/dialog-box.ts]: Why all the conditional stuff based on if warning is set? Why do we change the logic of the header and stuff?

File: src/resources/theme/main.globals.ts [hunk 6]
```diff
@@ -28,13 +28,16 @@ export const mainStyles = css`
...
+    --safe-area-inset-bottom: max(var(--app-safe-area-inset-bottom, env(safe-area-inset-bottom, 0)), 0px);
+    --safe-area-inset-left: max(var(--app-safe-area-inset-left, env(safe-area-inset-left, 0)), 0px);
+    --safe-area-inset-right: max(var(--app-safe-area-inset-right, env(safe-area-inset-right, 0)), 0px);
 
     --safe-area-inset-y: calc(var(--safe-area-inset-top, 0px) + var(--safe-area-inset-bottom, 0px));
     --safe-area-inset-x: calc(var(--safe-area-inset-left, 0px) + var(--safe-area-inset-right, 0px));
+
+    --safe-width: calc(100vw - var(--safe-area-inset-left, 0px) - var(--safe-area-inset-right, 0px));
```
Comment (bramkragten) [inline src/resources/theme/main.globals.ts]: We already fallback to zero above right?

```suggestion
    --safe-width: calc(100vw - var(--safe-area-inset-left) - var(--safe-area-inset-right));
```

File: src/resources/theme/main.globals.ts [hunk 7]
```diff
@@ -28,13 +28,16 @@ export const mainStyles = css`
...
+    --safe-height: calc(100vh - var(--safe-area-inset-top, 0px) - var(--safe-area-inset-bottom, 0px));
```
Comment (bramkragten) [inline src/resources/theme/main.globals.ts]:
```suggestion
    --safe-height: calc(100vh - var(--safe-area-inset-top) - var(--safe-area-inset-bottom));
```

File: src/components/ha-wa-dialog.ts (hunk 2 above)
Comment (timmo001) [reply src/components/ha-wa-dialog.ts]: Do we only want an alert/confirmation to be used with `dialog-box`?

Comment (bramkragten) [reply src/components/ha-wa-dialog.ts]: Yes, that is the element that handles alerts and confirmations.

File: src/components/ha-wa-dialog.ts [hunk 8]
```diff
@@ -246,6 +246,14 @@ export class HaWaDialog extends LitElement {
         min-height: var(--ha-dialog-min-height);
         position: var(--dialog-surface-position, relative);
         margin-top: var(--dialog-surface-margin-top, auto);
+        transform: translateX(
```
Comment (bramkragten) [inline src/components/ha-wa-dialog.ts]: Why do we need to translate the dialog? What are we trying to fix here?

File: src/components/ha-wa-dialog.ts (hunk 2 above)
Comment (timmo001) [reply src/components/ha-wa-dialog.ts]: OK will revert all these changes 👍

File: src/components/ha-wa-dialog.ts (hunk 8 above)
Comment (timmo001) [reply src/components/ha-wa-dialog.ts]: The offset of the dialog, say the safe area is this:

```css
    --app-safe-area-inset-bottom: 36px;
    --app-safe-area-inset-left: 68px;
```
(this is a pixel 10 in landscape, which is the nav bar + camera bump)

Without the transform, the position will stay centered to the screen and not the safe area. This is fine until the space is limited. This is only the case for alert/confirmation boxes, as the standard dialog will fall into fullscreen with padding

File: src/resources/theme/main.globals.ts (hunk 4 above)
Comment (timmo001) [reply src/resources/theme/main.globals.ts]: I didn't think this either, this is the main potential fix for iOS (will need testing as I only have android or desktop)

From @piitaya :
image
image

Comment (piitaya) [reply src/resources/theme/main.globals.ts]: I think it's not because of negative margin, Looks like the dialog is push from the bottom (there is a grey bar)

**Comment by piitaya** [comment]
Also for generic dialog, I feel like this should be aligned : 

CleanShot 2025-11-27 at 16 30 46

File: src/resources/theme/main.globals.ts (hunk 4 above)
Comment (timmo001) [reply src/resources/theme/main.globals.ts]: Ah this makes more sense

Comment (timmo001) [reply src/resources/theme/main.globals.ts]: OK reverted.

Reproduced this in android too, it has the same effect on the fullscreen dialog of pushing the header/dialog up with the nav bar

File: src/components/ha-wa-dialog.ts (hunk 8 above)
Comment (bramkragten) [reply src/components/ha-wa-dialog.ts]: But since the position is `relative` we can simply use `top` and `left` to position it? We don't need `translate` then?

File: src/components/ha-wa-dialog.ts [hunk 9]
```diff
@@ -275,8 +275,10 @@ export class HaWaDialog extends LitElement {
 
           wa-dialog::part(dialog) {
             /* Make the dialog fill the whole screen height and not the safe height */
-            min-height: var(--ha-dialog-min-height, 100vh);
-            max-height: var(--ha-dialog-max-height, 100vh);
+            min-height: var(--ha-dialog-min-height, var(--safe-height));
+            max-height: var(--ha-dialog-max-height, var(--safe-height));
```
Comment (piitaya) [inline src/components/ha-wa-dialog.ts]:
```suggestion
            min-height: var(--ha-dialog-min-height, 100vh);
            max-height: var(--ha-dialog-max-height, 100vh);
```
We want it fullscreen. Padding are here to apply safe area

Comment (timmo001) [reply src/components/ha-wa-dialog.ts]: That causes this on android

Comment (timmo001) [reply src/components/ha-wa-dialog.ts]: With --safe-height:

Comment (piitaya) [reply src/components/ha-wa-dialog.ts]: Try using `100dvh`. It's not because of safe area, it's because of browser header bar.

Comment (piitaya) [reply src/components/ha-wa-dialog.ts]: ios 
`--safe-height`
Image
`100vh` or `100dvh` (it's the same inside the app)
Image

Comment (piitaya) [reply src/components/ha-wa-dialog.ts]:
```
min-height: var(--ha-dialog-min-height, 100vh);
min-height: var(--ha-dialog-min-height, 100dvh);
max-height: var(--ha-dialog-max-height, 100vh);
max-height: var(--ha-dialog-max-height, 100dvh);
```
This should fix the issue

Comment (timmo001) [reply src/components/ha-wa-dialog.ts]: Hmm well that worked :shrug: 

I guess the x margins and dvh were the final fix here

File: src/dialogs/generic/dialog-box.ts [hunk 10]
```diff
@@ -199,6 +205,9 @@ class DialogBox extends LitElement {
     ha-textfield {
       width: 100%;
     }
+    .title.alert {
+      margin-left: var(--ha-space-2);
```
Comment (piitaya) [inline src/dialogs/generic/dialog-box.ts]: Use margin inline start

**Review by piitaya — APPROVED** [review]

**Comment by Mariusthvdb** [comment]
seems not fixed, and still opening full screen in iOS Companion

C15FB75D-672A-43C0-9380-6BFDBB156433
