### PR TITLE
Show battery in and out energy in Sankey chart

### LINKED ISSUE #26419: Sankey in Energy Panel not showing correct Battery use by home
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The Sankey Chart in the Energy Dashboard is not showing the correct values for Solar going into the battery, or the battery usage by the home.

Also there is a graphical overlap with the "Fridge" and "Network"

Image
Image
Image

### Describe the behavior you expected

I expect it to show the amount of energy from the solar panels going into the battery and then from the battery into the home

### Steps to reproduce the issue

1. Goto Energy Dashboard
2. View Sankey Chart
3. Compare with Energy Distribution Chart
...

### What version of Home Assistant Core has the issue?

2025.8.0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Version 138.0.3351.121 (Official build) (64-bit)

### Which operating system are you using to run this browser?

Windows 11 24H2 (26100.4770)

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #26419
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by raghu-ranganathan** [comment]
Noticed there is work on this topic -
https://github.com/home-assistant/frontend/pull/26490

Thanks.

File: src/panels/lovelace/cards/energy/hui-energy-sankey-card.ts [hunk 1]
```diff
@@ -92,6 +93,10 @@ class HuiEnergySankeyCard
     const prefs = this._data.prefs;
     const types = energySourcesByType(prefs);
     const { summedData, compareSummedData: _ } = getSummedData(this._data);
+    const { consumption, compareConsumption: __ } = computeConsumptionData(
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/hui-energy-sankey-card.ts:96]:
```suggestion
    const { consumption } = computeConsumptionData(
```

File: src/panels/lovelace/cards/energy/hui-energy-sankey-card.ts [hunk 2]
```diff
@@ -92,6 +93,10 @@ class HuiEnergySankeyCard
     const prefs = this._data.prefs;
     const types = energySourcesByType(prefs);
     const { summedData, compareSummedData: _ } = getSummedData(this._data);
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/hui-energy-sankey-card.ts:95]:
```suggestion
    const { summedData } = getSummedData(this._data);
```

**Review by bramkragten — APPROVED** [review]

**Comment by MindFreeze** [comment]
This is for 2025.9
