### PR TITLE
Scale oversized brand thumbnails in media browser

### LINKED ISSUE #12816: Oversized Media Source brand thumbnails
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The brand thumbnails in the new media-source library do not fit with the overall look of the media browser cards. 

image

### Describe the behavior you expected

The original svg icons were based on a .40 scaling.  It would be nice to have the same scaling for the brand thumbnails too.

image

### Steps to reproduce the issue

1.  Access the Media tab for any media-source
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

linux/Windows

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

Code changes used to generate screenshots
https://github.com/wizmo2/frontend/commit/00af4ad46c5aaaff2c092072e27c49f7af22a819

### PR DESCRIPTION
**Pull request by wizmo2**
## Breaking change

The brand thumbnails in the new media-source libraries do not fit well with the overall look of the media browser cards

## Proposed change

As brand thumbnails are typically raster icons, this PR proposes to identify brand thumbnails and resize similar to the original svg class icons.

before
Current View

after
Proposed

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [x] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #12816 
- This PR is related to issue or discussion:
- Link to documentation pull request:

- This PR replaces #12819 

Please feel free to make direct changes or 'close' if you feel this does not fit with future plans. I'm not, by any means, a frontend developer/expert. My motivation is that this has merely bugged me for a while now!

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.
My development setup has limited testing capabilities for frontend

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by matthiasdebaat** [comment]
Nice!

File: src/components/media-player/ha-media-player-browse.ts [hunk 1]
```diff
@@ -564,7 +568,12 @@ export class HaMediaPlayerBrowse extends LitElement {
                     class="${["app", "directory"].includes(child.media_class)
                       ? "centered-image"
                       : ""} image"
-                    style="background-image: ${until(backgroundImage, "")}"
+                    style="background-image: ${until(
+                      backgroundImage,
+                      ""
+                    )}${isBrandUrl(child.thumbnail)
+                      ? "; background-size: 40%"
+                      : ""}"
```
Comment (zsarnett) [inline src/components/media-player/ha-media-player-browse.ts:576]: Lets do this in the Class and add the style in the CSS below

**Review by zsarnett — APPROVED** [review]
