### PR TITLE
computeLovelaceEntityName(): allow "number" names to be processed

### LINKED ISSUE #28118: Entities card: issue with a "name" using digits
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Consider an Entities card:
```
type: entities
entities:
  - entity: sun.sun
    name: "123"
  - entity: sun.sun
    name: 123
  - entity: sun.sun
    name: 123x
```

Image

Here `name: 123` is treated as empty.
Seems like a value is processed as a number instead of a string.
We can solve this by pasting a value into quotes.
But it was changed recently, earlier values were processed properly.

Same seems to happen to some other cards (confirmed for Entity card too).

### Describe the behavior you expected

Values are processed as strings.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2025.11.3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ildar170975**
## Proposed change

Allow names like "123", "123.456" (in case of a corr. number format) to be shown.
Due to recent changes for names, these "number" names are not shown.
This PR allows these "number" names to be shown on cards.

Before:
518999602-f65f65be-674d-4917-bbee-6c9396b69270

After:
image

Warnings in UI editor are still here - consider this as an advice to convert number values to strings like `"123"`.
But at least in yaml-mode dashboards (where these warnings are not shown) these "number" names will be shown as they were before.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/28118
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by piitaya** [comment]
According to the typings, it should be string. I would keep string only. The fix is very easy, just put quotes around the number.
Why would you add a number instead of a string?
Also, if you enter a number using the UI, the quotes will be automatically added.

**Comment by ildar170975** [comment]
> Why would you add a number instead of a string?

It is a proper way if you start anew.
But users may have tons of old code without quotes which has been working for years.
And this code may be kept in yaml-mode dashboards where users will not see these warning, they will only see an absent name.
That is why I suggested this fix.

Even in storage-mode dashboards, users will not be warned until they open a problematic card in UI editor.

OR - we can write in Release notes smth like "breaking change - place these values into quotes", but who cares about reading release notes(((

File: src/panels/lovelace/common/entity/compute-lovelace-entity-name.ts [hunk 1]
```diff
@@ -21,7 +21,7 @@ export const computeLovelaceEntityName = (
   if (!config) {
     return stateObj ? computeStateName(stateObj) : "";
   }
-  if (typeof config === "string") {
+  if (typeof config === "string" || typeof config === "number") {
     return config;
   }
```
Comment (MindFreeze) [inline src/panels/lovelace/common/entity/compute-lovelace-entity-name.ts]: Let's make this more defensive

```suggestion
  if (typeof config !== "object") {
    return String(config);
  }
```

**Review by MindFreeze — APPROVED** [review]
We don't officially support this but we see how it can confuse users that are not very familiar with YAML and this will help them
