### PR TITLE
Fix disabled button state for vacuum in tile card

### LINKED ISSUE #14613: Tile Card Vacuum is not showing Start/Pause on the UI
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When adding a vacuum entity to the dashboard, the card shows correctly, however, the start/pause and stop buttons are greyed out. Opening the control, however, the built in controls to start stop are displayed properly:
image

image

For clarity, this is a Neato Vacuum

### Describe the behavior you expected

Using the Mushroom vacuum tile I would think the controls would be usable (which they were). 

### Steps to reproduce the issue

1. Add vacuum to the interface. Add vacuum controls
2. Find that controls are greyed out (disabled). 
3.
...

### What version of Home Assistant Core has the issue?

2022.12.0

### What was the last working version of Home Assistant Core?

Unknown...feature was introduced in 2022.12.0

### In which browser are you experiencing the issue with?

Microsoft Edge

### Which operating system are you using to run this browser?

Operating System 9.3

### State of relevant entities

```txt
battery_level: 99
battery_icon: mdi:battery-charging-100
status: Docked
clean_start: 2022-10-28T16:08:42Z
clean_stop: 2022-10-28T17:07:13Z
clean_area: 59.0672
clean_suspension_count: 0
clean_suspension_time: 0
clean_pause_time: 0
clean_error_time: 0
battery_level_at_clean_start: 98
battery_level_at_clean_end: 23
launched_from: app
icon: mdi:robot-vacuum-variant
friendly_name: Downstairs Vacuum
supported_features: 15964
```

### Problem-relevant frontend configuration

```yaml
type: tile
entity: vacuum.downstairs_vacuum
features:
  - type: vacuum-commands
    commands:
      - start_pause
      - stop
      - return_home
```

### Javascript errors shown in your browser console/inspector

```txt
N/A
```

### Additional information

Neato Vacuum,

Cleared my cache

Tried Incognito Mode

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

The condition for whether a vacuum can start was inverted. Also added "idle" to the states in which a vacuum cannot be stopped, since it is already stopped (tested with the `demo` entity `vacuum.5_fifth_floor`).

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #14613
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/tile-features/hui-vacuum-commands-tile-feature.ts [hunk 1]
```diff
@@ -85,7 +85,7 @@ export const VACUUM_COMMANDS_BUTTONS: Record<
           translationKey: "start",
           icon: mdiPlay,
           serviceName: "start",
-          disabled: canStart(stateObj),
+          disabled: !canStart(stateObj),
```
Comment (bramkragten) [inline src/panels/lovelace/tile-features/hui-vacuum-commands-tile-feature.ts:88]: This is still wrong, the button would now be enabled when the state === unavailable

Comment (spacegaier) [reply src/panels/lovelace/tile-features/hui-vacuum-commands-tile-feature.ts:88]: True and the button linked to `canReturnHome()` has the same issue.

Comment (spacegaier) [reply src/panels/lovelace/tile-features/hui-vacuum-commands-tile-feature.ts:88]: Actually, that is not true. If the entity is not available all buttons are disabled by default in `render()`.

Comment (piitaya) [reply src/panels/lovelace/tile-features/hui-vacuum-commands-tile-feature.ts:88]: The unavailable condition is checked for every button line 185.

**Review by piitaya — APPROVED** [review]
