### PR TITLE
Remove padding when narrow

### LINKED ISSUE #9211: System icon missing in mobile view
### Describe the issue you are experiencing

Since updating to supervisor-2021.05.1 I've noticed I no longer get the System icon in the bottom bar when viewing supervisor on a mobile device, the alignment of the other icons also seems a bit off so it could be that the system icon is pushed off screen. System option is still there in the top bar on PC.

### What is the used version of the Supervisor?

supervisor-2021.05.1

### What type of installation are you running?

Home Assistant OS

### Which operating system are you running on?

Home Assistant Operating System

### What is the version of your installed operating system?

6.0.rc1

### What version of Home Assistant Core is installed?

core-2021.5.5

### Steps to reproduce the issue

1.
2.
3.
...
It was OK on supervisor-2021.4.3 yesterday, not 100% sure whether this started in 2021.05.0 or 2021.05.1.

### Anything in the Supervisor logs that might be useful for us?

```txt
Nothing that stands out, as noted above it appears to just be an issue when viewing on mobile.
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

Before:
image

After:
image

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9211
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-tab.ts [hunk 1]
```diff
@@ -119,6 +119,9 @@ export class HaTab extends LitElement {
       :host([narrow]) {
         padding: 0 16px;
       }
+      :host([narrow]) div {
```
Comment (balloob) [inline src/components/ha-tab.ts:122]: Update the line above it instead

Comment (balloob) [reply src/components/ha-tab.ts:122]: Oh nevermind that's different selector

**Review by balloob — APPROVED** [review]
