### PR TITLE
Filter Integration in Target and Area selectors + clean up some code

### LINKED ISSUE #12254: Filter entity selector by integration doesn't work
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

We got reports that using the utility meter service for resetting didn't allow selecting the sensors. This means that filtering an entity list by integration doesn't work. Selector config:

image

(the red line is because it's getting removed for this HA release)

### Describe the behavior you expected

It should show only the entities created by the utility meter.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2022.4

### What was the last working version of Home Assistant Core?

-

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### LINKED ISSUE #12315: Can't pick entities from non-config entries filtered by integration
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It's not possible to pick entities from non-config entries filtered by integration 

Step-by-step reproduction:
1. Setup a super cool utility_meter in configuration.yaml:
```yaml
utility_meter:                 
  super_cool:                  
    source: sensor.today_energy
    tariffs:                   
      - peak                   
      - offpeak                
```

2. Try to pick the super cool utility meter in the developer tool for utility meter's calibrate service:
image

### Describe the behavior you expected

It should be possible to select `select.super_cool` according to the step-by-step instruction below

### Steps to reproduce the issue

1. Setup a super cool utility_meter in configuration.yaml:
```yaml
utility_meter:                 
  super_cool:                  
    source: sensor.today_energy
    tariffs:                   
      - peak                   
      - offpeak                
```

2. Try to pick the super cool utility meter in the developer tool for utility meter's calibrate service:
image

3. 😢 

### What version of Home Assistant Core has the issue?

2022.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zsarnett**
## Proposed change

Code Quality: Create selector filter functions to reuse code

Area Selector: Use entity sources for the integration filter
Target Selector: Use entity sources for the integration filter
Device Selector: Use new functions for filtering
Entity Selector: Use new functions for filtering

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #12254 #12315
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by zsarnett** [comment]
Used to test: https://gist.github.com/zsarnett/69e17d6857c78bd2d5a33e119ce0c7b0

Basically just a clone of Frencks

File: src/data/device_registry.ts [hunk 1]
```diff
@@ -142,3 +143,23 @@ export const getDeviceEntityLookup = (
   }
   return deviceEntityLookup;
 };
+
+export const getDeviceIntegrationLookup = (
```
Comment (bramkragten) [inline src/data/device_registry.ts:147]: Should this be in `device_registry`? As it is all entity based and not device?

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
