### PR TITLE
Use localized string for empty logbook entries in trace view

### LINKED ISSUE #30248: Add to lokalise - "No Logbook entries found for this step."
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Missing translation "No Logbook entries found for this step."

### Describe the behavior you expected

Please add it to lokalise.
https://github.com/home-assistant/frontend/blob/d9c39640e0dc70d11dc553062da615375e1e08c2/src/components/trace/ha-trace-logbook.ts#L35

### Steps to reproduce the issue

not relevant

### What version of Home Assistant Core has the issue?

2026.3

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Replace the hardcoded English string "No Logbook entries found for this step." with the existing localize key `ui.panel.config.automation.trace.path.no_logbook_entries` so the text can be translated via Lokalise.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #30248
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure
[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/components/trace/ha-trace-logbook.ts [hunk 1]
```diff
@@ -32,7 +32,9 @@ export class HaTraceLogbook extends LitElement {
           ></hat-logbook-note>
         `
       : html`<div class="padded-box">
-          No Logbook entries found for this step.
+          ${this.hass.localize(
+            "ui.panel.config.automation.trace.path.no_logbook_entries"
```
Comment (timmo001) [inline src/components/trace/ha-trace-logbook.ts:36]: https://github.com/home-assistant/frontend/blob/cc35d4782c82f9cb2174e85124053c0c26b06a64/src/translations/en.json#L5734

?

Comment (timmo001) [reply src/components/trace/ha-trace-logbook.ts:36]: Oh thats the new name :laughing:

**Review by timmo001 — APPROVED** [review]
