### PR TITLE
Fix localization `Solar total` in Enery dashboard

### LINKED ISSUE #14801: Missing translation string "Solar total"
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have problem that translation string of word "Solar total" is not listed for translation from English to Slovenian language.

https://app.lokalise.com/project/3420425759f6d6d241f598.13594006/?view=single&reference_lang_id=640&single_lang_id=920&search=Solar%20total

So how to translate this?

### Describe the behavior you expected

No info.

### Steps to reproduce the issue

No info.

### What version of Home Assistant Core has the issue?

2022.12.6

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chrome

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt
No info.
```

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jbouwh**
## Proposed change

Lokalize text `Solar total` on the Energy dashboard to allow translations.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #14801
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts [hunk 1]
```diff
@@ -279,7 +279,9 @@ export class HuiEnergySourcesTableCard
                 ? html`<tr class="mdc-data-table__row total">
                     <td class="mdc-data-table__cell"></td>
                     <th class="mdc-data-table__cell" scope="row">
-                      Solar total
+                      ${this.hass.localize(
+                        "panel.lovelace.cards.energy.solar_total"
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts:283]:
```suggestion
                        "ui.panel.lovelace.cards.energy.energy_sources_table.solar_total"
```

File: src/translations/en.json [hunk 2]
```diff
@@ -3828,6 +3828,7 @@
               "not_produced_solar_energy": "You have not produced any solar energy",
               "self_consumed_solar_could_not_calc": "Self-consumed solar energy couldn't be calculated"
             },
+            "solar_total": "Solar total",
```
Comment (bramkragten) [inline src/translations/en.json:3831]: This should be move too now, to line 3811

**Review by bramkragten — APPROVED** [review]
