### PR TITLE
Fix state-label-badge override name

### LINKED ISSUE #4163: Badge 'name' property not overwriting entity's 'friendly_name' in 0.101.1
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
Home Assistant 0.101.1

**Last working Home Assistant release (if known):**
Home Assistant 0.100.3
**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
safari, chrome, macos

**Description of problem:**
I'm setting the badge names in raw config editor like this:

```
  - badges:
      - sun.sun
      - entity: sensor.kitchen_feels_like
        name: Bucatarie
      - entity: sensor.living_room_feels_like
        name: Living
      - entity: sensor.ground_floor_bathroom_feels_like
        name: Baie jos
      - entity: sensor.alex_bedroom_feels_like
        name: Alex
      - entity: sensor.cristina_bedroom_feels_like
        name: Cristina
      - entity: sensor.daria_bedroom_feels_like
        name: Daria
      - entity: sensor.upstairs_bathroom_feels_like
        name: Baie sus
      - entity: sensor.disk_use_percent
        name: Disk usage
      - entity: sensor.cpu_temperature
        name: CPU Temp
```
and the names are not overwritten. I keep getting the old names

**Javascript errors shown in the web inspector (if applicable):**
no errors

**Additional information:**
image

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/4163

### CODE REVIEW

File: src/panels/lovelace/badges/hui-state-label-badge.ts [hunk 1]
```diff
@@ -37,11 +36,7 @@ export class HuiStateLabelBadge extends LitElement implements LovelaceBadge {
       <ha-state-label-badge
         .hass=${this.hass}
         .state=${stateObj}
-        .title=${this._config.name
-          ? this._config.name
-          : stateObj
-          ? computeStateName(stateObj)
-          : ""}
+        .name=${this._config.name}
```
Comment (iantrich) [inline src/panels/lovelace/badges/hui-state-label-badge.ts]: why remove the computeStateName?

Comment (iantrich) [reply src/panels/lovelace/badges/hui-state-label-badge.ts]: oh...because it does it already in ha-state-label-badge 🤦‍♂

**Review by iantrich — APPROVED** [review]
