### PR TITLE
Fix add integration discovery

### LINKED ISSUE #14288: Manually adding a device is not working when there are discovered devices for an intergration
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When there are discoved devices waiting to be configured and you are manually tying to add a device the frontend will offer to check if it is one of them, clicking on "Setup another instance of..." is broken. If the devices are ignored it is possible to manually add a device.

### Describe the behavior you expected

"Setup another instance of" should work

### Steps to reproduce the issue

1. Try to manually add a device:
image
2. Click on "Setup another instance of"
3. Button does not work and exception is shown in browser console
image

### What version of Home Assistant Core has the issue?

core-2022.11.1 (also broken in latest dev core)

### What was the last working version of Home Assistant Core?

core-2022.10?

### In which browser are you experiencing the issue with?

Chrome 107.0.5304.88 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

```txt
integrations:1 Autofocus processing was blocked because a document already has a focused element.
ha-domain-integrations.ts:200 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'supported_by')
    at F.value (ha-domain-integrations.ts:200:1)
    at F.handleEvent (styles.ts:371:1)
    at n.fireRequestSelected (mwc-list-item-base.ts:224:1)
    at n.<anonymous> (mwc-list-item-base.ts:224:1)
    at 01055a0b.js:2:1798
    at Map.forEach (<anonymous>)
    at e.updated (01055a0b.js:2:1724)
    at n._$AE (styles.ts:371:1)
    at n.performUpdate (styles.ts:371:1)
    at n.scheduleUpdate (styles.ts:371:1)
value @ ha-domain-integrations.ts:200
handleEvent @ styles.ts:371
fireRequestSelected @ mwc-list-item-base.ts:224
(anonymous) @ mwc-list-item-base.ts:224
(anonymous) @ 01055a0b.js:2
e.updated @ 01055a0b.js:2
_$AE @ styles.ts:371
performUpdate @ styles.ts:371
scheduleUpdate @ styles.ts:371
_$EC @ styles.ts:371
await in _$EC (async)
requestUpdate @ styles.ts:371
set @ styles.ts:371
setSelectedStateForElementIndex @ mwc-list-base.ts:270
setSingleSelectionAtIndex_ @ 342ceb2d.js:2
setSelectedIndexOnAction_ @ 342ceb2d.js:2
handleSingleSelection @ 342ceb2d.js:2
onRequestSelected @ mwc-list-base.ts:270
handleEvent @ styles.ts:371
fireRequestSelected @ mwc-list-item-base.ts:224
onClick @ mwc-list-item-base.ts:224
cb @ mwc-circular-progress-base.ts:156 
```
```


### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Fixes load the right discovered flows, and starting a new non discovered flow if one was discovered.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/14288
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/integrations/dialog-add-integration.ts [hunk 1]
```diff
@@ -188,6 +189,9 @@ class AddIntegrationDialog extends LitElement {
                   ([dom, val]) => val.name || domainToName(localize, dom)
                 )
               : undefined,
+            domains: integration.integrations
+              ? Object.keys(integration.integrations || {})
```
Comment (ludeeus) [inline src/panels/config/integrations/dialog-add-integration.ts:193]:
```suggestion
              ? Object.keys(integration.integrations)
```
You already checked its existence on the line above.

**Review by ludeeus — DISMISSED** [review]

**Review by ludeeus — APPROVED** [review]
