### PR TITLE
Limit `ha-toast` width to window, refactor CSS

### LINKED ISSUE #51266: Updated toast does not wrap below 650px
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Updated toast notification does not wrap below 650px meaning that action and dismiss buttons are not visible when screen is smaller in width. When duration is -1 this leaves a non-actionable, non-dismissable toast.

2026.3.4

Image

2026.4.0b4

Image

### Describe the behavior you expected

Toast wraps.

### Steps to reproduce the issue

1. Run code in console

```javascript
document.querySelector("home-assistant").dispatchEvent(new CustomEvent("hass-notification", { detail: { message: "A long long long long long long long long long long long messgae", duration: -1, dismissable: true }, bubbles: true, composed: true }));
```

### What version of Home Assistant Core has the issue?

2026.4.0b4

### What was the last working version of Home Assistant Core?

2026.3.4

### In which browser are you experiencing the issue?

Version 146.0.7680.165 (Official Build) (arm64)

### Which operating system are you using to run this browser?

MacOS Version 15.7.1 (24G231)

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by timmo001**
## Screenshots

image
image
image
image
image
image

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #51266
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

**Comment by TCWORLD** [comment]
Probably unrelated to this PR, but is it worth adding a slight larger inside margin on the left - it looks kind of unbalanced compared to the dismiss button on the right.

File: src/components/ha-toast.ts [hunk 1]
```diff
@@ -198,15 +198,7 @@ export class HaToast extends LitElement {
...
-        350px,
-        calc(
-          100vw - var(--ha-space-4) - var(--safe-area-inset-left, 0px) - var(
-              --safe-area-inset-right,
-              0px
-            )
-        )
-      );
+      min-width: min(350px, calc(var(--safe-width) - var(--ha-space-4)));
       max-width: 650px;
```
Comment (MindFreeze) [inline src/components/ha-toast.ts]: Shouldn't this be constrained too? I think on a 550px screen, it can still overflow

**Review by MindFreeze — APPROVED** [review]
