### PR TITLE
Remove flag that sets icon as required when creating a new dashboard

### LINKED ISSUE #19639: Add new dashboard modal indicates visually that the Icon field is required when it is not required
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

image

### Describe the behavior you expected

I am still able to create a dashboard without completing the Icon field, so it should not show as required.

### Steps to reproduce the issue

1. Settings
2. Dashboards
3. Add Dashboard
4. Enter Title
5. Create

### What version of Home Assistant Core has the issue?

core-2024.1.6

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

iOS Safari in iOS app

### Which operating system are you using to run this browser?

iOS 17.3

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

https://github.com/home-assistant/frontend/blob/dev/src/panels/config/lovelace/dashboards/dialog-lovelace-dashboard-detail.ts#172

### PR DESCRIPTION
**Pull request by codyc1515**
## Proposed change
Less friction to create a new dashboard. Moreover, an icon isn't actually required in order to create the dashboard anyway.

## Type of change
- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration
Create a new dashboard from the UI.

## Additional information
- This PR fixes or closes issue: fixes #19639 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist
- [ ] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]

File: src/panels/config/lovelace/dashboards/dialog-lovelace-dashboard-detail.ts [hunk 1]
```diff
@@ -169,7 +169,7 @@ export class DialogLovelaceDashboardDetail extends LitElement {
         },
         {
           name: "icon",
-          required: true,
```
Comment (bramkragten) [inline src/panels/config/lovelace/dashboards/dialog-lovelace-dashboard-detail.ts:172]: You can just remove it btw, as the default is false

**Comment by codyc1515** [comment]
Tested working on 2024.2.1
