### PR TITLE
Merge Long Term Statistics for Power Sensors in Energy Dashboard

### LINKED ISSUE #28737: Power Sources on Energy Dashboard missing if selected date is beyond short term statistics limit
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When selecting a historic date on the summary tab of the energy dashboard, the power sources chart is empty if the selected date range exceeds the available short term statistics:

Image

However there is data is present in long term statistics:

Image

If a range of >9 days is selected, the power sources data is properly populated:

Image

### Describe the behavior you expected

The power sources data should show long-term statistics data if short-term statistics are not available. Similar to the history charge.

### Steps to reproduce the issue

1. Go to energy dashboard summary tab
2. Select a day that is beyond the limit of short term statistics,
3. No data is shown even though present in long term statistics
...

### What version of Home Assistant Core has the issue?

2025.12.1

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue?

N/A

### Which operating system are you using to run this browser?

N/A

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

This appears to be due to the way the statistics data is requested here:

https://github.com/home-assistant/frontend/blob/6efe444af308d057f0758567a486ff0c9d95ed27/src/data/energy.ts#L451-L461

For longer time periods, the hourly data is requested which is fetched from long term statistics, however for short time periods only 5 minute data is requested regardless of whether the data is available in short term statistics or not.

### PR DESCRIPTION
**Pull request by TCWORLD**
## Proposed change

When using 5minute data for the power sources chart, data would be missing if the selected range was beyond the short term statistics limit. 

This change takes data from long term statistics and merges it in to the power sources data if the short term statistics doesn't extend far enough back for the selection.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #28737 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/data/energy.ts [hunk 1]
```diff
@@ -511,6 +511,15 @@ const getEnergyData = async (
...
     : {};
+  // If power stats 5 minute data is selected, then also fetch hourly data which
+  // will be used to back-fill any missing data points in the 5 minute data when
+  // the requested range is beyond the limit of short term statistics.
+  const _powerStatsHour: Statistics | Promise<Statistics> =
+    powerStatIds.length && finePeriod === "5minute"
+      ? fetchStatistics(hass!, start, end, powerStatIds, "hour", powerUnits, [
+          "mean",
+        ])
+      : {};
```
Comment (MindFreeze) [inline src/data/energy.ts:522]: It would be nice to only fetch hourly data when the period exceeds the available 5minute data but not sure it's worth the complexity. If 5minute data kept only for a fixed period in core, it might be easy.

**Review by MindFreeze — APPROVED** [review]

File: src/data/energy.ts (hunk 1 above)
Comment (TCWORLD) [reply src/data/energy.ts:522]: I'd thought about it, but I don't think there is an easy way of telling whether the data is there - for example short-term data can be purged in which case we can't just rely on the recorder limit, and different sensors may be configured with different limits.

Given 5 minute data is only fetched for shorter time periods, and the hourly data is much fewer samples, it's probably not worth the complexity of optimising it. 

If you want to reduce the overhead further, it wouldn't be unreasonable to reduce the number of days that 5minute data is fetched for from the current 9 down to say 3 days (to match how hourly energy data is only shown for 3 days before it switches to daily). Would still require the mixing of both data sets for when 5minute is missing (e.g. going to a historic day range). but then it would be a maximum of 72 samples of extra data for each sensor rather than the current maximum of 216 per sensor.
