### PR TITLE
Automation editor sidebar

### LINKED ISSUE #26503: Nested IF Statements can cause excessive UI padding (unusable editor space)
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I love my automations. My automations are weird with many nested if statements. So much so, that **selecting entities and using the editing space becomes unnecessarily difficult.**

I recommend that the side padding no longer be existent with this level of nesting, instead use a varied colour or other gradient background denotating "how deep" in the nest you are. 

Maybe remove padding if both the top and bottom of a given element is not within the screen viewport.

Retaining user feedback on the depth of nesting whilst keeping functionality will be tricky with this level of if statements. 

Maybe a "slide in, slide out" animation would be nice. Say for example "maximum horizontal padding equals the amount of pixels outside of viewport" would produce the animation whilst scrolling up or down through many nestings.

### Describe the behavior you expected

It would be awesome if there was a cap on padding for elements plus sub elements.

### Steps to reproduce the issue

1. Make many nested if statements
2. Keep trying to select and edit things
3. Frustration 
...

### What version of Home Assistant Core has the issue?

2025.8.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change
- Add automation editor sidebar
  - fixes #26503

image

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-automation-row.ts [hunk 1]
```diff
@@ -0,0 +1,143 @@
...
+    if (ev.type === "keydown" && ev.key !== "Enter" && ev.key !== " ") {
+      return;
+    }
+    ev.stopPropagation();
+    ev.preventDefault();
+
+    fireEvent(this, "toggle-collapsed");
+  }
+
+  private async _click(ev): Promise<void> {
```
Comment (bramkragten) [inline src/components/ha-automation-row.ts]:
```suggestion
  private async _handleKeyDown_(ev: KeyboardEvent): Promise<void> {
```

File: src/components/ha-automation-row.ts [hunk 2]
```diff
@@ -0,0 +1,143 @@
...
+    if (ev.defaultPrevented) {
+      return;
+    }
+    if (ev.type === "keydown" && ev.key !== "Enter" && ev.key !== " ") {
```
Comment (bramkragten) [inline src/components/ha-automation-row.ts]:
```suggestion
    if (ev.key !== "Enter" && ev.key !== " ") {
```

File: src/data/selector.ts [hunk 3]
```diff
@@ -131,6 +132,7 @@ export interface ColorTempSelector {
 
 export interface ConditionSelector {
   condition: {} | null;
+  optionsInSidebar?: boolean;
```
Comment (bramkragten) [inline src/data/selector.ts]: this should be inside `condition`

File: src/data/selector.ts [hunk 4]
```diff
@@ -75,6 +75,7 @@ export type Selector =
 
 export interface ActionSelector {
   action: {} | null;
+  optionsInSidebar?: boolean;
```
Comment (bramkragten) [inline src/data/selector.ts]: This should be inside `action`

File: src/components/ha-selector/ha-selector-condition.ts [hunk 5]
```diff
@@ -27,6 +27,7 @@ export class HaConditionSelector extends LitElement {
         .conditions=${this.value || []}
         .hass=${this.hass}
         .narrow=${this.narrow}
+        .optionsInSidebar=${!!this.selector.optionsInSidebar}
```
Comment (bramkragten) [inline src/components/ha-selector/ha-selector-condition.ts]:
```suggestion
        .optionsInSidebar=${!!this.selector.condition?.optionsInSidebar}
```

File: src/components/ha-selector/ha-selector-action.ts [hunk 6]
```diff
@@ -69,6 +69,7 @@ export class HaActionSelector extends SubscribeMixin(LitElement) {
         .actions=${this._actions(this.value)}
         .hass=${this.hass}
         .narrow=${this.narrow}
+        .optionsInSidebar=${!!this.selector.optionsInSidebar}
```
Comment (bramkragten) [inline src/components/ha-selector/ha-selector-action.ts]:
```suggestion
        .optionsInSidebar=${!!this.selector.action?.optionsInSidebar}
```

File: src/panels/config/automation/action/ha-automation-action-row.ts [hunk 7]
```diff
@@ -69,28 +73,46 @@ import "./types/ha-automation-action-event";
...
-export const getType = (action: Action | undefined) => {
-  if (!action) {
-    return undefined;
-  }
-  if ("action" in action) {
-    return getActionType(action) as "action" | "play_media";
-  }
-  if (["and", "or", "not"].some((key) => key in action)) {
-    return "condition" as const;
+export const ACTION_BUILDING_BLOCKS = [
```
Comment (bramkragten) [inline src/panels/config/automation/action/ha-automation-action-row.ts]: We probably should unify this with https://github.com/home-assistant/frontend/blob/dev/src/data/action.ts#L57?

File: src/panels/config/automation/condition/ha-automation-condition.ts [hunk 8]
```diff
@@ -24,6 +24,8 @@ import {
 import "./ha-automation-condition-row";
 import type HaAutomationConditionRow from "./ha-automation-condition-row";
 
+export const CONDITION_BUILDING_BLOCKS = ["and", "or", "not"];
```
Comment (bramkragten) [inline src/panels/config/automation/condition/ha-automation-condition.ts]: https://github.com/home-assistant/frontend/blob/dev/src/data/condition.ts#L43

File: src/panels/config/automation/manual-automation-editor.ts [hunk 9]
```diff
@@ -185,7 +187,12 @@ export class HaManualAutomationEditor extends LitElement {
         .path=${["triggers"]}
```
Comment (bramkragten) [inline src/panels/config/automation/manual-automation-editor.ts]:
```suggestion
```
Not related but cleanup 🙃

File: src/panels/config/automation/ha-automation-sidebar.ts [hunk 10]
```diff
@@ -0,0 +1,401 @@
...
+
+    this.config?.save(ev.detail.value);
+
+    if (this.config) {
+      fireEvent(this, "value-changed", {
+        value: {
+          ...this.config,
+          config: ev.detail.value,
+        },
+      });
```
Comment (bramkragten) [inline src/panels/config/automation/ha-automation-sidebar.ts:315]: Why do we fire a value changed in the sidebar?

File: src/panels/config/automation/ha-automation-sidebar.ts [hunk 11]
```diff
@@ -0,0 +1,401 @@
...
+    }
+  }
+
+  private _closeSidebar() {
+    this.config?.close();
+    this.config = undefined;
```
Comment (bramkragten) [inline src/panels/config/automation/ha-automation-sidebar.ts]: Shouldn't the parent set this to undefined instead of the child? Will the parent not set this to his stored value again now?

File: src/panels/config/automation/manual-automation-editor.ts (hunk 9 above)
Comment (wendevlin) [reply src/panels/config/automation/manual-automation-editor.ts]: So also remove conditions and actions path prop? What was it for?

File: src/panels/config/automation/ha-automation-sidebar.ts (hunk 10 above)
Comment (wendevlin) [reply src/panels/config/automation/ha-automation-sidebar.ts:315]: To let the parent (`manual-automation-editor`) change the `_sidebarConfig`, otherwise it would lead to a not visible change.

File: src/panels/config/automation/ha-automation-sidebar.ts (hunk 11 above)
Comment (wendevlin) [reply src/panels/config/automation/ha-automation-sidebar.ts]: Yes I think we can remove this.

File: src/panels/config/automation/manual-automation-editor.ts (hunk 9 above)
Comment (bramkragten) [reply src/panels/config/automation/manual-automation-editor.ts]: yeah also for conditions and actions
It was used for drag and drop reordering, but no longer used

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
