### PR TITLE
Fix logbook keeps loading

### LINKED ISSUE #24212: Loogbook not working for number entities
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When clicking a number entity, the logbook does not load, the circle keeps sniping: 

Image

The entity does populate the global logbook when an automation triggers a change:

Image

When checking the logbook for the device itself, changing number entities does not register an entry in the log:

Image
Even if the closing degree was changed 3 seconds ago, the last entry is from 2 minutes ago.

It behaves the same in safe mode:

Image

From what I can see, this affects only number entities

### Describe the behavior you expected

Loogbook loading for number entites.

### Steps to reproduce the issue

1. Click on any number entity that has been changed by an automation.

### What version of Home Assistant Core has the issue?

2025.2.3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

All, including copanion app.

### Which operating system are you using to run this browser?

Windows 10 and 11, Android, iOS.

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change
2 bug fixes for https://github.com/home-assistant/frontend/issues/24212 introduced after https://github.com/home-assistant/frontend/pull/23853. It's a bit the logic how it is handled that makes it hard to not break anything here along the line. 

So, some sensors are continuous, and there's a short circuit in the backend that will provide an empty event straight away after subscription. But the event and the subscription are message wise sent together. 
First bug appears that the event is pushed through before the subscription is finalized, and the event is being throw away for being too early according to the comment. I've added the promise to a temporary variable to ensure we know that events that come with the subscription are not being handled as too "early". The subscription promise will resolve shortly after. 
Second bug appears on unsubscribing (whenever you change entities for example). The unsubscribe has already happened and the subscription is gone. Giving an error and failing to clean the UI state, resulting in the need to hard refresh. 

The demo integration provides a "number.temperature_setting", which you can add on the logbook page. 
* Go to the logbook page
* Add the "number.temperature_setting" => First bug
* Remove the "number.temperature_setting" => Second bug

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/24212
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/logbook/ha-logbook.ts [hunk 1]
```diff
@@ -288,13 +289,13 @@ export class HaLogbook extends LitElement {
...
     try {
-      this._subscribed = await subscribeLogbook(
+      const subscribePromise = subscribeLogbook(
         this.hass,
         (streamMessage) => {
           // "recent" means start time is a sliding window
           // so we need to calculate an expireTime to
           // purge old events
-          if (!this._subscribed) {
+          if (!subscribePromise) {
```
Comment (MindFreeze) [inline src/panels/logbook/ha-logbook.ts:298]: This will never evaluate to `true`. It looks like it was put there to handle the case where the component is unloading but events keep coming in. I don't think it did it properly though as it would only work after `unsubscribe` and at that point there shouldn't be any more events coming.
In any case, we should figure out another condition here or remove it if it is not needed.

File: src/panels/logbook/ha-logbook.ts [hunk 2]
```diff
@@ -305,6 +306,7 @@ export class HaLogbook extends LitElement {
         this.entityIds,
         this.deviceIds
       );
+      this._subscribed = await subscribePromise;
```
Comment (bramkragten) [inline src/panels/logbook/ha-logbook.ts:309]: `_subscribed` is typed as promise, and it also awaited in the code, we now no longer save a `promise` in `_subscribed`.

Also now `_subscribed` is set later, so that when `_unsubscribe` is called, `_subscribed` might not be set yet and we never unsubscribe.

File: src/panels/logbook/ha-logbook.ts [hunk 3]
```diff
@@ -288,13 +289,13 @@ export class HaLogbook extends LitElement {
       return;
     }
     try {
-      this._subscribed = await subscribeLogbook(
```
Comment (bramkragten) [inline src/panels/logbook/ha-logbook.ts:291]: Seems like we already awaited the promise, which is wrong.

**Comment by GigiPompieru** [comment]
any idea when this will get implemented?

**Comment by silamon** [comment]
I've redone the typing starting from the connection handler, then checked every situation. 
I don't think we have a mechanism to track when backend unsubscribes for us, which is also happening here. In case it will no longer send events, it closes prematurely, but since we're still subscribed, it still calls unsub.

File: src/panels/logbook/ha-logbook.ts [hunk 4]
```diff
@@ -208,15 +209,30 @@ export class HaLogbook extends LitElement {
...
+   *
+   * @param loading Indicates if the page should be put in a loading state again.
+   */
+  private _unsubscribe(loading: boolean): void {
+    if (this._unsubLogbook) {
       try {
-        await this._subscribed();
-        this._subscribed = undefined;
-        this._pendingStreamMessages = [];
+        this._unsubLogbook.then((unsub) => unsub());
```
Comment (bramkragten) [inline src/panels/logbook/ha-logbook.ts:228]: This will not throw as it is not awaited, if you want to do something with the error, either use:

```ts
try {
	const unsub = await this._unsubLogbook;
	unsub();
} catch (...)
{ .. }
```

OR:

```ts
this._unsubLogbook.then((unsub) => unsub()).catch(err => {console.error("Error unsubscribing:", err)});
```

I this case I would go for the second (although I don't think we have to log) as we dont have to wait for the unsub I think to continue?

File: src/panels/logbook/ha-logbook.ts [hunk 5]
```diff
@@ -284,20 +279,13 @@ export class HaLogbook extends LitElement {
   private async _subscribeLogbookPeriod(
     logbookPeriod: LogbookTimePeriod
   ): Promise<void> {
-    if (this._subscribed) {
+    if (this._unsubLogbook) {
       return;
     }
     try {
-      this._subscribed = await subscribeLogbook(
+      this._unsubLogbook = subscribeLogbook(
```
Comment (bramkragten) [inline src/panels/logbook/ha-logbook.ts:286]: As this is also no awaited, it will not throw. To fix that you could do:

```ts
try {
	this._unsubLogbook = subscribeLogbook(...);
	await this._unsubLogbook;
} catch (e) {
	...
}

File: src/panels/logbook/ha-logbook.ts (hunk 4 above)
Comment (silamon) [reply src/panels/logbook/ha-logbook.ts:228]: The purpose of this code was clean up the variables, so the filters around this components remain to work, so the try catch finally can be removed then.

**Comment by silamon** [comment]
Thanks for the reviews. I think I've got it covered.

**Review by bramkragten — APPROVED** [review]

**Comment by GigiPompieru** [comment]
hi, I'm guessing this was implemented in 2025.4? Now it no longer keeps loading, but it does not display any information either:
image

**Comment by bramkragten** [comment]
A little more info might be useful, it seems to be working fine here.
Please create an issue describing the issue.

**Comment by raldred** [comment]
This isn't fixing the underlying issue https://github.com/home-assistant/frontend/issues/24212 for me on 2025.04.

It stops it showing the loading indicator showing indefinitely, but there's still no logbook entries showing for any number entities when in their more-info dialog or when filtering for them directly in the logbook.

However... this is where it gets odd.
I have managed to get them to show only for a brief moment when I had two logbook windows open.
Something odd must happening with the way events are being subscribed to.

You can repro this behaviour with a single logbook window following these steps & shown in this video:

https://drive.google.com/file/d/1VX3MJDgqhHU5kaU9ZK-_J6jUEjysYMN4/view?usp=sharing

1. Open a logbook window
2. Open a separate tab with entity more-info dialog
3. Change the entity
4. Observer no logbook entries for the entity
5. Filter the logbook window on the entity in question
6. Observer no logbook entries
7. Change the entity from it's more-info dialog
8. Observe no logbook entries still.
9. Remove the entity from the filter
10. Observe the logbook entries appear (mixed amongst others) 
11. Hard refresh
12. Make a change
13. No log book entries added
14. Hard refresh
15. Log book entries appear.

**Comment by raldred** [comment]
@bramkragten This isn't fixing the underlying issue https://github.com/home-assistant/frontend/issues/24212 for me on 2025.04.

It stops it showing the loading indicator showing indefinitely, but there's still no logbook entries showing for any number entities when in their more-info dialog or when filtering for them directly in the logbook.

However... this is where it gets odd.
I have managed to get them to show only for a brief moment when I had two logbook windows open.
Something odd must happening with the way events are being subscribed to.

You can repro this behaviour with a single logbook window following these steps & shown in this video:

https://drive.google.com/file/d/1VX3MJDgqhHU5kaU9ZK-_J6jUEjysYMN4/view?usp=sharing

Open a logbook window
Open a separate tab with entity more-info dialog
Change the entity
Observer no logbook entries for the entity
Filter the logbook window on the entity in question
Observer no logbook entries
Change the entity from it's more-info dialog
Observe no logbook entries still.
Remove the entity from the filter
Observe the logbook entries appear (mixed amongst others)
Hard refresh
Make a change
No log book entries added
Hard refresh
Log book entries appear.

**Comment by silamon** [comment]
It was solved, but please note in the pull request description that continious sensors don't provide logging. 

If you feel like there is still an issue, make a new issue and we'll take a look.

**Comment by raldred** [comment]
If that's the case, it seems like a shame, it's useful to look back at what changed an entity. I guess resolving that is a larger core issue. Would therefore help UX (and reduce instances of this issue being raised by other users) if the UI provided a warning notice or something to that affect, showing the logbook particularly in the more info dialog makes it look broken?
