### PR TITLE
Dev tools -> yaml: use "pre" instead of "span" for "validate-log"

### LINKED ISSUE #24720: Dev tools -> yaml, validate-log: a text cannot be selected in FF
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Originally reported here: https://github.com/home-assistant/frontend/issues/24651#issuecomment-2743423799

Dev tools -> yaml:
in FF 136.0 it is impossible to select a whole text:

Image

You can only select one line.

Works OK in Chrome 134.0.6998.89, MS Edge 134.0.3124.72 (Official build) (64-bit).

### Describe the behavior you expected

Text is selectable by a mouse.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2025.3.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

FF 136.0 (64-bit)

### Which operating system are you using to run this browser?

Win10x64

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ildar170975**
## Proposed change

Before:
изображение

After:
изображение

My subjective opinion is that using a monospace font for Logs (and this is a small log) containing technical stuff is better than using a proportional font.

Also, there is one more practical outcome - fixing an issue.
It is not possible to select this text in FF:
изображение
But it is possible in Chrome 134.0.6998.89, MS Edge 134.0.3124.72 (Official build) (64-bit).
Just a guess (I am not a css pro) that FF does not like a multiline span.
As a workaround, I considered to set `-moz-user-select: all` for `.validate-log`.
But in the end proposed a different way.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/24720
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by teskanoo** [comment]
Thank you so much - I can finally drop my custom-in-browser css fix

**Review by MindFreeze — APPROVED** [review]
This makes more sense semantically too as it is pre-formatted text

File: src/panels/developer-tools/yaml_configuration/developer-yaml-config.ts [hunk 1]
```diff
@@ -246,6 +246,7 @@ export class DeveloperYamlConfig extends LitElement {
         .validate-log {
           white-space: pre-wrap;
           direction: ltr;
+          margin: 0 !important;
```
Comment (MindFreeze) [inline src/panels/developer-tools/yaml_configuration/developer-yaml-config.ts:249]: Wait, does this have to be `!important` ? You should be able to use a more specific selector instead

**Review by MindFreeze — CHANGES_REQUESTED** [review]

File: src/panels/developer-tools/yaml_configuration/developer-yaml-config.ts (hunk 1 above)
Comment (ildar170975) [reply src/panels/developer-tools/yaml_configuration/developer-yaml-config.ts]: `pre` has some margins. In my tests it needed to be "important" to override.

**Comment by ildar170975** [comment]
See this glitch:
изображение

Will think what to do...

File: src/panels/developer-tools/yaml_configuration/developer-yaml-config.ts (hunk 1 above)
Comment (ildar170975) [reply src/panels/developer-tools/yaml_configuration/developer-yaml-config.ts]: @MindFreeze retested again w/o `important` - it works in Chrome, FF, Edge.
Earlier when it did not work - was a glitch (most probably in my brains).

**Review by MindFreeze — APPROVED** [review]
