### PR TITLE
Fix developer tools set state for unexisting entity

### LINKED ISSUE #18821: Dev tools -> Set state: it is possible to select a non-existing entity
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

1. Go to Dev tools -> Set State.
2. Select some existing sensor from a list:

изображение

3. Place a mouse cursor to an "entity" input field.
4. Manually type some sensor - and make an error with a purpose -> and type a name of some non-existing entity.

изображение

5. Now you may edit a state, attributes -> and be surprised that it affects nothing.

In a real scenario a user may select some existing `sensor.device_xxx`, then - some non-existing `sensor.device_xxx2` instead of a `sensor.device_xxx_2`.
Since `sensor.device_xxx` & `sensor.device_xxx_2` may have a similar structure (i.e. similar states, similar attributes) - a user may not notice that a wrong (non-existing) was selected.

### Describe the behavior you expected

Do not allow to select a non-existing entity.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2023.11.2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chrome 119.0.6045.160 

### Which operating system are you using to run this browser?

Win10x64

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change
Regression from #18134 mentioned in #18821.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #18821
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/developer-tools/state/developer-tools-state.ts [hunk 1]
```diff
@@ -360,17 +360,16 @@ class HaPanelDevState extends LitElement {
   }
 
   private _updateEntity() {
-    if (!this._entityId) {
+    const entityState = this._entityId
+      ? this.hass.states[this._entityId]
+      : undefined;
+    if (!this._entityId || !entityState) {
```
Comment (bramkragten) [inline src/panels/developer-tools/state/developer-tools-state.ts:366]:
```suggestion
    if (!entityState) {
```

**Review by bramkragten — APPROVED** [review]
