### PR TITLE
Fix ZHA network visualization page navigation

### LINKED ISSUE #7983: ZHA Integration configuration header menu disappears when selecting Visualization
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem
When looking at the Network Visualization in configurations options for the ZHA Zigbee integration, the header menu disappears which makes it hard to go back to the other configuration options.

## Expected behavior
The header menu should remain allowing navigation back to Network or Groups

## Steps to reproduce
Visit http://homeassistant.local:8123/config/zha/visualization

## System Health

version | 2020.12.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.6
os_name | Linux
os_version | 5.4.79-v8
arch | aarch64
timezone | Europe/London

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 26 December 2020, 0:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.8
-- | --
update_channel | beta
supervisor_version | 2020.12.6
docker_version | 19.03.13
disk_total | 57.8 GB
disk_used | 7.0 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (2.6.1), Visual Studio Code (2.9.1), UniFi Controller (0.19.3), SSH & Web Terminal (7.8.0), AppDaemon 4 (0.3.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
mode | auto-gen
resources | 0

</details>

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by dmulcahey**
## Proposed change

This PR fixes the navigation for the ZHA network visualization page. Fixes: #7983

Before: 

Screen Shot 2021-04-26 at 7 32 40 AM

After:

Screen Shot 2021-04-26 at 7 31 38 AM

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #7983
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/integrations/integration-panels/zha/zha-network-visualization-page.ts [hunk 1]
```diff
@@ -29,12 +29,17 @@ import { formatAsPaddedHex } from "./functions";
...
 import type { HaCheckbox } from "../../../../../components/ha-checkbox";
+import { zhaTabs } from "./zha-config-dashboard";
 
 @customElement("zha-network-visualization-page")
 export class ZHANetworkVisualizationPage extends LitElement {
-  @property({ type: Object }) public hass!: HomeAssistant;
+  @property({ attribute: false }) public hass!: HomeAssistant;
 
-  @property({ type: Boolean, reflect: true }) public narrow = false;
+  @property({ type: Object }) public route!: Route;
```
Comment (bramkragten) [inline src/panels/config/integrations/integration-panels/zha/zha-network-visualization-page.ts:38]:
```suggestion
  @property({ attribute: false }) public route!: Route;
```

**Review by bramkragten — APPROVED** [review]
