### PR TITLE
Fix use of "" on lock entity more info (use default code)

### LINKED ISSUE #18705: Lock card does not respect default code
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Using the lock card without entering a code does not work.

I have configured my lock with a default code, but when I use the lock card lock or unlock, I am still being asked for a code:
image

However, if try to lock or unlock without providing a code, the service call is not sent. Instead, I see this service call on the web socket:
```
{"type":"call_service","domain":"system_log","service":"write","service_data":{"logger":"frontend.js.latest.202310302","message":"Unhandled promise rejection from Firefox 118.0 on Mac OS 10.15\nError: Code dialog closed\nhass.localize (src/data/lock.ts:42:12)\n_callService (src/dialogs/more-info/components/lock/ha-more-info-lock-toggle.ts:71:6)\n_turnOff (src/dialogs/more-info/components/lock/ha-more-info-lock-toggle.ts:59:17)\n_valueChanged (src/dialogs/more-info/components/lock/ha-more-info-lock-toggle.ts:43:11)\ncall (src/lit-html.ts:2018:28)\ndispatchEvent (src/common/dom/fire_event.ts:76:7)\n_toggle (src/components/ha-control-switch.ts:61:14)\n_toggle (src/components/ha-control-switch.ts:118:13)\ndata (src/manager.js:334:18)\nemit (src/recognizers/tap.js:117:19)","level":"debug"},"id":40}
```
A similar log message is sent in Chrome.

I am not sure if HA should ask the user to enter a code or not when a default code is provided. Personally, I would favour _not_ asking the user for a code in this case.

Secondary, the lock slider transitions position (but not colour) when asking for the code, but if I cancel entering the code, it does not slide back. In this case, I think it should not change position until a code is submitted.

### Describe the behavior you expected

Lock should lock or unlock.

### Steps to reproduce the issue

1. Install an integration with a lock (e.g. Verisure)
2. Configure a default code on the lock
3. Use the lock card to lock or unlock

### What version of Home Assistant Core has the issue?

2023.12.0.dev0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

Found during debugging https://github.com/home-assistant/core/issues/101404

### PR DESCRIPTION
**Pull request by gjohansson-ST**
## Proposed change

- Fix so it accepts the default of `""` from the submit code dialog so it will revert to use the default code given on the `lock` entity
- Add code formatting validation error

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #18705
- This PR is related to issue or discussion: https://github.com/home-assistant/core/pull/103463
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by gjohansson-ST** [comment]
We could/should perhaps consider to not load the "code-dialog" at all if there is a default code but not sure if there is a use-case to provide another code than the default which would stop such?

**Comment by piitaya** [comment]
> We could/should perhaps consider to not load the "code-dialog" at all if there is a default code but not sure if there is a use-case to provide another code than the default which would stop such?

The default code is set to avoid user entering the code right? If yes, we should not ask the user to enter the code.

**Comment by gjohansson-ST** [comment]
This PR is now updated so besides handling `""` as an accepted code it now also provides a validation error and handle no submit in case code doesn't match format.

File: src/data/lock.ts [hunk 1]
```diff
@@ -30,15 +31,20 @@ export const callProtectedLockService = async (
   service: ProtectedLockService
 ) => {
   let code: string | undefined;
+  const lockRegistryEntry = await getExtendedEntityRegistryEntry(
+    hass,
+    stateObj.entity_id
+  );
+  const defaultCode = lockRegistryEntry.options?.lock?.default_code;
```
Comment (piitaya) [inline src/data/lock.ts:38]:
```suggestion
  const lockRegistryEntry = await getExtendedEntityRegistryEntry(
    hass,
    stateObj.entity_id
  ).catch(() => undefined);
  const defaultCode = lockRegistryEntry?.options?.lock?.default_code;
```
The promise can fail if the lock isn't in the entity registry (demo lock for example)

**Review by piitaya — DISMISSED** [review]
Thank you for the change!

I'm not sure it's necessary to explain to the user that the code is not in the right format because here is no indication on what the format should be.

I wonder if we could raise an architecture issue to convert the code format to `number` and `text` like we have for alarm control panel (https://developers.home-assistant.io/docs/core/entity/alarm-control-panel/#code-formats). So we can display a keypad or a textfield depending of the format.

**Comment by gjohansson-ST** [comment]
> Thank you for the change!
> 
> 
> 
> I'm not sure it's necessary to explain to the user that the code is not in the right format because here is no indication on what the format should be.
> 

Wouldn't the user be confused otherwise to why the submit doesn't work?

> 
> I wonder if we could raise an architecture issue to convert the code format to `number` and `text` like we have for alarm control panel (https://developers.home-assistant.io/docs/core/entity/alarm-control-panel/#code-formats). So we can display a keypad or a textfield depending of the format.

Makes sense. I'll make one as I think these two should be sort of same handling codes.

**Comment by piitaya** [comment]
> Wouldn't the user be confused otherwise to why the submit doesn't work?

Is it the same if the code is wrong? The problem is that the code format is a regex so we can not explain to the user what is the correct format. I think number or text can be enough.

**Comment by gjohansson-ST** [comment]
So if we'll remove the message from this PR we can bring it in, then open an arch topic to "harmonize" `lock` and `alarm_control_panel` and then get the necessary changes done for a nicer experience?

**Comment by piitaya** [comment]
Yes, it seems to be a good idea to keep the scope of that PR to default code and we can improve the code format behavior in another (probably core and frontend after architecture discussion)

File: src/dialogs/enter-code/dialog-enter-code.ts [hunk 2]
```diff
@@ -52,8 +52,14 @@ export class DialogEnterCode
   }
 
   private _submit(): void {
-    this._dialogParams?.submit?.(this._input?.value ?? "");
-    this.closeDialog();
+    if (
+      this._dialogParams &&
+      this._dialogParams.codePattern &&
+      RegExp(this._dialogParams.codePattern).test(this._input?.value ?? "")
```
Comment (bramkragten) [inline src/dialogs/enter-code/dialog-enter-code.ts:58]: If there is code pattern the user can not submit? Is code pattern mandatory in core? Looking at the dev docs it seems to be optional?

File: src/data/lock.ts [hunk 3]
```diff
@@ -30,15 +31,20 @@ export const callProtectedLockService = async (
...
 ) => {
   let code: string | undefined;
+  const lockRegistryEntry = await getExtendedEntityRegistryEntry(
+    hass,
+    stateObj.entity_id
+  ).catch(() => undefined);
+  const defaultCode = lockRegistryEntry?.options?.lock?.default_code;
 
-  if (stateObj!.attributes.code_format) {
+  if (stateObj!.attributes.code_format && !defaultCode) {
```
Comment (bramkragten) [inline src/data/lock.ts:40]: Wasn't the idea not so show the code dialog when the `defaultCode` is `""`?

File: src/dialogs/enter-code/dialog-enter-code.ts [hunk 4]
```diff
@@ -52,14 +52,18 @@ export class DialogEnterCode
...
-      this._dialogParams?.submit?.(this._input?.value ?? "");
-      this.closeDialog();
+    if (this._dialogParams && this._dialogParams.codePattern) {
+      if (
+        RegExp(this._dialogParams.codePattern).test(this._input?.value ?? "")
+      ) {
+        this._dialogParams?.submit?.(this._input?.value ?? "");
+        this.closeDialog();
+      } else {
+        this.closeDialog();
```
Comment (bramkragten) [inline src/dialogs/enter-code/dialog-enter-code.ts:62]: I don't think we want to close the dialog in this case, but show an error to the user?

File: src/dialogs/enter-code/dialog-enter-code.ts [hunk 5]
```diff
@@ -52,14 +52,18 @@ export class DialogEnterCode
...
-      RegExp(this._dialogParams.codePattern).test(this._input?.value ?? "")
-    ) {
-      this._dialogParams?.submit?.(this._input?.value ?? "");
-      this.closeDialog();
+    if (this._dialogParams && this._dialogParams.codePattern) {
+      if (
+        RegExp(this._dialogParams.codePattern).test(this._input?.value ?? "")
+      ) {
+        this._dialogParams?.submit?.(this._input?.value ?? "");
+        this.closeDialog();
```
Comment (bramkragten) [inline src/dialogs/enter-code/dialog-enter-code.ts:60]: return;

File: src/data/lock.ts [hunk 6]
```diff
@@ -37,7 +37,10 @@ export const callProtectedLockService = async (
   ).catch(() => undefined);
   const defaultCode = lockRegistryEntry?.options?.lock?.default_code;
 
-  if (stateObj!.attributes.code_format && !defaultCode) {
+  if (
+    stateObj!.attributes.code_format &&
+    (defaultCode == null || defaultCode === "")
```
Comment (bramkragten) [inline src/data/lock.ts:42]: This will still show the dialog when `defaultCode` is `""`? What is exactly the goal?

File: src/data/lock.ts [hunk 7]
```diff
@@ -30,18 +31,32 @@ export const callProtectedLockService = async (
...
+    if (response == null) {
       throw new Error("Code dialog closed");
     }
     code = response;
+  } else if (
+    stateObj!.attributes.code_format &&
+    defaultCode &&
+    defaultCode.length >= 0
+  ) {
+    code = defaultCode;
```
Comment (piitaya) [inline src/data/lock.ts:59]: If there is a default code, code should not be send to the service, right?

File: src/data/lock.ts (hunk 6 above)
Comment (piitaya) [reply src/data/lock.ts:42]: If there is a default code in the entity registry, user should not be prompted to enter a code because the back-end will automatically send the code for unlocking.
Just checking `!defaultCode` should be enough right?

**Review by piitaya — COMMENTED** [review]
Can we keep `codePattern` changes outside of this PR and only focus on default code? If code format changes according to the architecture discussion you opened, this code will be obsolete.

File: src/data/lock.ts (hunk 6 above)
Comment (bramkragten) [reply src/data/lock.ts:42]: I thought it could also be an empty string? Or did I misunderstood?

Comment (bramkragten) [reply src/data/lock.ts:42]: nvm

Comment (gjohansson-ST) [reply src/data/lock.ts:42]: In core it sets the default_code to `""` when the entity is registered in the entity registry but it can also be entities without unique id so we also need to handle `null´

Comment (bramkragten) [reply src/data/lock.ts:42]: yes

**Comment by gjohansson-ST** [comment]
> Can we keep `codePattern` changes outside of this PR and only focus on default code? If code format changes according to the architecture discussion you opened, this code will be obsolete.

Not entirely sure which portion you mean I would change the code pattern?

**Comment by piitaya** [comment]
> > Can we keep `codePattern` changes outside of this PR and only focus on default code? If code format changes according to the architecture discussion you opened, this code will be obsolete.
> 
> Not entirely sure which portion you mean I would change the code pattern?

The code inside the submit. If we move to code format, code pattern will be gone, right?

**Comment by gjohansson-ST** [comment]
I reduced it again to only handle default_code so we should be pretty much set now.
I left the validation in as I don't see why not showing it to the user while we still have a code pattern there in place.

**Review by bramkragten — APPROVED** [review]
