### PR TITLE
Make graph colors themable

### LINKED ISSUE #9547: History Graphs - Color change in 2021.7.1 update - Cannot find documentation of the change - new colors are harder to read
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

With the last update to 2021.7.1, the colors / look of the History Graph in lovelace have changed. I looked through the release notes and all recent pull requests, and none mention where or why the previous colors were changed.

Previously, for a history graph with multiple values/entities, lovelace would automatically choose very contrasting colors, making the graphs easy to read.

With the change, lovelace is selecting different colors yes, but they are all very similar, variations of blue/purple/teal, making the graphs much harder to read.

I believe this issue is related to the one mentioned here:
https://github.com/home-assistant/frontend/issues/9495#issuecomment-875826241

Essentially something changed the automatic color scheme for the History Graphs.

### Describe the behavior you expected

Previous colors were more distinct.

### Steps to reproduce the issue

Update from 2021.6 to 2021.7. Use History Graphs in lovelace.

### What version of Home Assistant Core has the issue?

2021.7.1

### What was the last working version of Home Assistant Core?

2021.6

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Not everyone likes the default colors we ship with HA and especially when custom themes are used, our colors can easily clash visually. This PR now adds the option to switch out colors in graphs (so statistics and history). A theme can either override all colors or only a few that clash.

**Example:**

I added this to my test theme
```
      graph-color-1: "#00ddff"
      graph-color-2: "#0000ff"
      graph-color-3: "#ffdd33"
      graph-color-4: "#ff00ff"
```

**Result:**

Note that the 3rd and 4th line in the history card is still using the `--state-<state>-color` vars as before since those are already themable but default to green and red based on the entity.

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9547
- This PR is related to issue or discussion: https://github.com/home-assistant/frontend/pull/7804
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by Mariusthvdb** [comment]
thank you for that PR, awesome!

**Comment by spacegaier** [comment]
> thank you for this PR, awesome!
> 
> would this also allow us to eg set theme colors for various states? home/not_home/zone etc etc, or would we still require an 3d party custom card like card-mod for that. Also cool, just asking

Not generically for all, but for the following that is already possible today anway:

```
--state-on-color
--state-off-color
--state-home-color
--state-not_home-color
--state-unavailable-color
--state-unknown-color
--state-idle-color
```

**Review by KTibow — DISMISSED** [review]

**Comment by Youpimatin** [comment]
Magnificent !

Graph colors, it is the main reason I am still on core-2021.6.6
Just have to learn how to use themes now...

Thank you so much !

File: src/common/color/colors.ts [hunk 1]
```diff
@@ -61,3 +61,12 @@ export const COLORS = [
 export function getColorByIndex(index: number) {
   return COLORS[index % COLORS.length];
 }
+
+export function getGraphColorByIndex(
+  index: number,
+  style: CSSStyleDeclaration
+) {
+  return (
+    style.getPropertyValue(`--graph-color-${index}`) || getColorByIndex(index)
```
Comment (bramkragten) [inline src/common/color/colors.ts:70]: Should we use `index + 1` here for the variable name? As normal people start with 1 instead of 0?
```suggestion
    style.getPropertyValue(`--graph-color-${index}`) || getColorByIndex(index)
```

Comment (spacegaier) [reply src/common/color/colors.ts:70]: I had thought about that as well, and I think you could argue both directions: 1..n is more logical for most non-tec users, whereas 0..n matches what we have in the coding (and we would mention that wherever we document it).

=> I am fine either way. Any other opinions here?

Comment (Mariusthvdb) [reply src/common/color/colors.ts:70]: tbh, changing to what 'normal people' do would be a breaking change ;-)

seriously though, I feel 0..n should be used, just like everywhere else in HA and beyond

Comment (spacegaier) [reply src/common/color/colors.ts:70]: How would it be breaking? We are adding something that did not exist before.

Comment (Mariusthvdb) [reply src/common/color/colors.ts:70]: it was a joke... 
yet, we use 0...n in all user available code, be it jinja, JS or Python. Moving away from that would be new indeed.(aka breaking)

Comment (Youpimatin) [reply src/common/color/colors.ts:70]: Anybody "normal" overriding these colors can understand index starts at 0, no ? (Especially if it's in the documentation, as @spacegaier said)
Both paradigms are conceivable, but I don't see the need to add an offset...

Comment (spacegaier) [reply src/common/color/colors.ts]: > 

I don't think that this is a valid comparison. Programming and low-level scripting languages of course use 0..n and we have no option to change that behavior, but here we are talking about end-user facing things that we control, so we decided to go for 1..n. Should be less confusing to the end-user.

Comment (Mariusthvdb) [reply src/common/color/colors.ts]: tbh, imho it will on the contrary  _introduce_ confusion.
Any user setting these custom colors will be used to the 0..n range in the first place. This would make it the only place in the full HA settings, backend and frontend, where 1..n is used.

of course, it's your call, and I thankfully accept the new options, just fear for a frontend issue afterwards ;-)

Comment (spacegaier) [reply src/common/color/colors.ts]: Where in the frontend do we already use 0..n in end-user facing stuff? Do we already have CSS vars with 0..n that I am not aware of?

**Review by bramkragten — APPROVED** [review]

File: src/common/color/colors.ts (hunk 1 above)
Comment (Mariusthvdb) [reply src/common/color/colors.ts]: probably not in core Ha, but all custom cards that support either JS or Jinja. And backend Jinja ofc. any mapper uses  0...n

Comment (bramkragten) [reply src/common/color/colors.ts]: That is programming, this is not programming.
