### PR TITLE
fix: update the z-index of search button mainly for yaml mode

### LINKED ISSUE #28839: Save button hidden behind bottom search panel in YAML mode
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When editing an automation/script in YAML mode and opening the search panel (cmd-F), the Save button is hidden behind the search panel, needing to close it (with the tiny X) before saving it, and sometimes not realizing that a change is pending (because no Save button is visible, which is an indicator of a change pending to be saved).

### Describe the behavior you expected

Save button is always visible (when a change is pending save, as per current logic).

https://github.com/user-attachments/assets/3425cc99-d865-4a48-8203-6aa7ef56708c

### Steps to reproduce the issue

1. Settings > Automations
2. Open an existing Automation (or create a new one)
3. Switch to "Edit in YAML" mode
4. Make a change in the yaml (Save button appears)
5. Open the search panel (CTRL-F)
6. Save button is no longer visible

### What version of Home Assistant Core has the issue?

Core 2025.12.5

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Google Chrome 145.0.7587.4

### Which operating system are you using to run this browser?

macOS Sequoia 15.7.2

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

z-index of the Search panel `<div class="cm-panels cm-panels-bottom" ` is 300

Image

### PR DESCRIPTION
**Pull request by fury0928**
## Breaking change

Fixes: #28839

Update the z-index for the Search button in YAML mode
## Proposed change

{18190B30-D4CE-4844-88D7-CB435F4DFFC0}

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by eureka0928** [comment]
@bramkragten would you review my PR? quick win
Thank you

**Comment by eureka0928** [comment]
cc: @MindFreeze for review 😉

**Comment by karwosts** [comment]
If your screen was smaller horizontally won't the button now be blocking the search bar functions? Might need some more thought.

**Comment by eureka0928** [comment]
> If your screen was smaller horizontally won't the button now be blocking the search bar functions? Might need some more thought.

You're right - it hides the search functionality, how about putting the Save button on the top of search bar?
{E48717A0-428E-46D5-A674-871BFB30CE26}

**Comment by eureka0928** [comment]
@bramkragten would you ask for UX team as well if we need to put the Save button on the top of search box? I will put the PR for that
I will reopen it once I get the reply
Thank you

**Comment by karwosts** [comment]
If you want a UX review, this should be left open. Otherwise it will be forgotten.

**Comment by silamon** [comment]
What we do in other places is have a fab-bottom-space, that would probably be the best solution here: 
https://github.com/home-assistant/frontend/blob/dev/src/layouts/hass-tabs-subpage.ts#L194

**Comment by eureka0928** [comment]
> What we do in other places is have a fab-bottom-space, that would probably be the best solution here: https://github.com/home-assistant/frontend/blob/dev/src/layouts/hass-tabs-subpage.ts#L194

@silamon do you prefer like this way?
{9E872BE4-C940-432C-AE1B-9586F5E6FAB7}
{7501937E-A7C7-4623-B5ED-93B511BE5834}

cc: @karwosts @MindFreeze 

Please let me know so that I can update this PR
Thank you

**Comment by eureka0928** [comment]
Hi @piitaya hope you had a great weekend
Would you review my screenshots if I am correct?
Thank you!

**Comment by eureka0928** [comment]
https://github.com/home-assistant/frontend/issues/28839#issuecomment-3738031380

Updated based on this UX feedback

**Comment by bramkragten** [comment]
@marcinbauer85 Do we want the search on top just for mobile, or also for wider screens?

File: src/panels/config/automation/ha-automation-editor.ts [hunk 1]
```diff
@@ -1336,6 +1336,7 @@ export class HaAutomationEditor extends PreventUnsavedMixin(
           right: calc(16px + var(--safe-area-inset-right, 0px));
           bottom: calc(-80px - var(--safe-area-inset-bottom));
           transition: bottom 0.3s;
+          z-index: 301;
```
Comment (bramkragten) [inline src/panels/config/automation/ha-automation-editor.ts]: You should probably revert these changes if we are going for the different solution?

Comment (fury0928) [reply src/panels/config/automation/ha-automation-editor.ts]: updated

**Comment by marcinbauer-ohf** [comment]
@bramkragten Yes, both mobile and desktop devices.

**Comment by eureka0928** [comment]
This is fixed and updated.
Ready to go!

{9548FDED-30F1-4D71-A1D5-83FDB14B99DB}
{8CD2F7C0-A7CE-4CBA-AC5B-E1C1FF57E191}

File: src/resources/codemirror.ts [hunk 2]
```diff
@@ -39,6 +43,7 @@ export const langCompartment = new Compartment();
 export const readonlyCompartment = new Compartment();
 export const linewrapCompartment = new Compartment();
 export const foldingCompartment = new Compartment();
+export const searchCompartment = new Compartment();
```
Comment (bramkragten) [inline src/resources/codemirror.ts]: No need for a compartment if we don't need this to change dynamically right?

Comment (fury0928) [reply src/resources/codemirror.ts]: Updated! finally good to go?

**Comment by eureka0928** [comment]
Updated and passed testing

**Review by bramkragten — APPROVED** [review]
