### PR TITLE
Restore default hours to show on map card to 0

### LINKED ISSUE #15216: Map card shows path of previous locations without being configured that way (2023.2 beta)
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Map card shows path of previous locations without being configured that way on 2023.2.0b1. This was not the case in 2023.1.7.

### Describe the behavior you expected

No path visible (as was the case up until 2023.1.7)

### Steps to reproduce the issue

Config of map card (note the absence of the [hours_to_show setting](https://www.home-assistant.io/dashboards/map/#hours_to_show)):
```yaml
      - type: map
        entities:
          - person.bob
          - !secret person_mw
          - !secret person_mini
          - !secret person_puber
          - zone.cz
          - zone.home
          - zone.new_home
          - zone.school
          - zone.school_mini
          - zone.scouting
          - zone.work
          - zone.work_ms
```
### What version of Home Assistant Core has the issue?

core-2023.2.0b1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

image
This track shouldn't be there

### PR DESCRIPTION
**Pull request by bdraco**
## Proposed change

fixes #15216

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by piitaya** [comment]
We should use 
```ts
this._config!.hours_to_show ?? DEFAULT_HOURS_TO_SHOW,
```
instead of
```ts
this._config!.hours_to_show || DEFAULT_HOURS_TO_SHOW,
```

So it will only check if hours_to_show is null or undefined

**Comment by bdraco** [comment]
> Also, I pushed a fix to wait for unsubscribe before subscribe in #15217. I think we can have the same here.
> 
> ```ts
> await this._unsubscribeHistoryTimeWindow();
> this._subscribeHistoryTimeWindow();
> ```

Does it need to be awaited, can we do this instead?
```
  private _unsubscribeHistoryTimeWindow() {
    if (!this._subscribed) {
      return;
    }
    this._subscribed.then((unsubscribe) => {
      if (unsubscribe) {
        unsubscribe();
      }
    });
    this._subscribed = undefined;
  }
```

File: src/panels/lovelace/cards/hui-map-card.ts [hunk 1]
```diff
@@ -223,22 +223,21 @@ class HuiMapCard extends LitElement implements LovelaceCard {
...
-    });
+    const unsubscribe = await this._subscribed;
+    if (unsubscribe) {
+      unsubscribe();
+    }
+    this._subscribed = undefined;
   }
 
-  protected updated(changedProps: PropertyValues): void {
+  protected async updated(changedProps: PropertyValues) {
```
Comment (bdraco) [inline src/panels/lovelace/cards/hui-map-card.ts:237]: This needs a different solution per https://github.com/home-assistant/frontend/pull/15217#discussion_r1088325647

**Review by piitaya — APPROVED** [review]
