### PR TITLE
Sort groups if same as sort column

### LINKED ISSUE #25827: Cannot sort alphabetically by device when grouping entities by device
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On the Entities page in the Home Assistant UI, when entities are grouped by device, it is not possible to sort the list alphabetically by device name. The sorting dropdown only affects entity-level sorting, and the device groups remain in an unsorted or static order. 

In contrast, when not grouped by device, sorting device works correctly.

### Describe the behavior you expected

There should be an option to sort device groups alphabetically by their device name when entities are grouped by device.

### Steps to reproduce the issue

1.	Navigate to Settings → Devices & Services → Entities.
2.	Click the Group by dropdown and choose Device.
3.	Attempt to sort the list alphabetically by device name.
4.	Observe that the order of device groups does not change.

### What version of Home Assistant Core has the issue?

2025.6.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Chrome, Brave

### Which operating system are you using to run this browser?

macOS 15.4.1 (24E263)

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

grouped by device
Image
ungrouped
Image

### PR DESCRIPTION
**Pull request by kevinlacotaco**
## Proposed change

1. If the grouped and sorted the groups, sort the groups by the sort column. Since all elements in each group would be the same nothing happens currently. 

Make it an array of entries that can be sorted instead of calling the entries later.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #25827
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/data-table/ha-data-table.ts [hunk 1]
```diff
@@ -708,16 +708,29 @@ export class HaDataTable extends LitElement {
         let items = [...data];
 
         if (groupColumn) {
+          const isGroupSortColumn = this.sortColumn === this.groupColumn;
```
Comment (MindFreeze) [inline src/components/data-table/ha-data-table.ts]: Shouldn't be using `this.sortColumn` and `this.groupColumn` here as they will skip the memoization. These should be passed to `_groupData` as arguments

**Review by MindFreeze — CHANGES_REQUESTED** [review]

File: src/components/data-table/ha-data-table.ts (hunk 1 above)
Comment (kevinlacotaco) [reply src/components/data-table/ha-data-table.ts]: Perfect. Thanks. One thing I noticed, I just went into another table to test the changes and saw that device, and `device_full` will not end up sorting since the column is `device`. Any ideas with this column? Apologies, quite new to the project and just picking it up as I go.

Comment (kevinlacotaco) [reply src/components/data-table/ha-data-table.ts]: Spotted the configs for the columns. Guess would need some guidance on how we want to sync those up? Filter on device_full, keep hidden - while sorting/grouping by device?

Comment (MindFreeze) [reply src/components/data-table/ha-data-table.ts]: The hidden column is only there for searching. Sorting should be done only on the visible columns so we don't confuse users

**Review by MindFreeze — APPROVED** [review]
Thank you!
