### PR TITLE
Script ID update with Alias

### LINKED ISSUE #12001: Entity_ID doesn't update when editing automation or script name
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When setting a new script or automation, entity_ID doesn't reflect the Name. It bugs out, usually stopping updating after a single keystroke. So, for example, if I edit my automation name to "Play baby songs", the entity_ID of said automation would be just "p". See [video here](https://youtu.be/RoU42tq8N0s).

### Describe the behavior you expected

Entity_ID updates according to the Name.

### Steps to reproduce the issue

1. create or edit automation or script
2. edit Name
3.
...

### What version of Home Assistant Core has the issue?

2022.3.3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Safari, Edge, HA App

### Which operating system are you using to run this browser?

Monterey 12.2, iOS 15.3.1

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zsarnett**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #12001 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/script/ha-script-editor.ts [hunk 1]
```diff
@@ -569,9 +569,13 @@ export class HaScriptEditor extends KeyboardShortcutMixin(LitElement) {
   }
 
   private _aliasChanged(alias: string) {
```
Comment (balloob) [inline src/panels/config/script/ha-script-editor.ts:571]: Why would we calculate this on every key stroke and not when the user clicks save ?

Comment (zsarnett) [reply src/panels/config/script/ha-script-editor.ts:571]: This was our current behavior. We can remove it but they would no longer see the entity ID be created while typing

Comment (balloob) [reply src/panels/config/script/ha-script-editor.ts:571]: Oh, I didn't realize this was a thing. What weird that we show this to users 🤦 

For now this is ok as this fixes the bug then…

**Review by balloob — APPROVED** [review]
