### PR TITLE
Only update dev tools yaml editor on entity change or submit

### LINKED ISSUE #18568: Cannot edit state attributes in "Current entities"
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

It is impossible to edit or add an attribute to/from an entity: 
- the attribute fields gets completely erased
- characters are type with a leading space

### Describe the behavior you expected

normal editor behaviour

### Steps to reproduce the issue

1.developer tools
2.states
3.select an entity
4. on the first empty line try add an attribute
5. all text gets ereased
6. characters are typed with an leading space
...

### What version of Home Assistant Core has the issue?

2023.11.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chrome  118.0.5993.120 and Edge 119.0.2151.44

### Which operating system are you using to run this browser?

win11

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

https://github.com/home-assistant/frontend/pull/18134 introduced `autoUpdate` for YAML editor. `autoUpdate` must only be used with `readOnly` because if the format is not valid, it will clear the entire field value (e.g. adding a new line)
This PR only update the yaml editor on entity change or submit.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/18568
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/developer-tools/state/developer-tools-state.ts [hunk 1]
```diff
@@ -357,7 +364,7 @@ class HaPanelDevState extends LitElement {
       this._entity = undefined;
       this._state = "";
       this._stateAttributes = {};
-      return;
+      this._updateEditor();
```
Comment (silamon) [inline src/panels/developer-tools/state/developer-tools-state.ts:367]: The return statement prevents the function from continuing and fetching state since the entityId is empty anyway. 
```suggestion
      this._updateEditor();
      return;
```

Comment (piitaya) [reply src/panels/developer-tools/state/developer-tools-state.ts:367]: 🙈 Good catch !

**Review by silamon — APPROVED** [review]
I've checked if I did autoUpdate also on the dev tools event PR, but that's not the case. Thanks for fixing. 👍

**Review by bramkragten — APPROVED** [review]
