### PR TITLE
Fix passive color radius and fix switch label clicks

### LINKED ISSUE #4686: Zones editor map preview - passive zones always displayed orange instead of gray
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

passive

When you edit an existing **Passive zone**, it's gray on the map but when you edit it, it'll show up as orange in the preview.  You can see it in my above screenshot. It should be consistent in both places (gray).

**Also**, when you toggle on "Passive" the circle remains orange in the preview, I think it should turn gray immediately. This would make it clear to users the difference in how they're displayed.

Edit: one more tiny thing I noticed just now, small typo in the passive descriptive text here. usefull = useful

## Expected behavior

Turn gray when Passive is toggled on, Orange when off

## Steps to reproduce

1. Edit an existing zone
2. Toggle on "Passive", doesn't turn gray in the preview

## Environment

- Home Assistant release with the issue: 0.105.1b
- Last working Home Assistant release (if known): n/a 
- UI Type (States or Lovelace): Lovelace
- Browser and browser version: stable Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/4686

### CODE REVIEW

File: src/components/ha-switch.ts [hunk 1]
```diff
@@ -55,6 +80,12 @@ export class HaSwitch extends MwcSwitch {
       `,
     ];
   }
+
+  private _haChangeHandler(e: Event) {
+    this.mdcFoundation.handleChange(e);
+    // catch "click" event and sync properties
+    this.checked = this.formElement.checked;
```
Comment (balloob) [inline src/components/ha-switch.ts]: We shouldn't do this. This will lead to nasty bugs.

When a parent renders this element, it will diff against itself to know if it needs to change the property. 

So let's say this happens:
 - Parent renders checked = true
 - User changes it, sets checked=false
 - Parent renders checked = true -> this will not update `<ha-switch>` because it already rendered `true` last time, even though the property current value is `false`

File: src/panels/config/zone/dialog-zone-detail.ts [hunk 2]
```diff
@@ -127,6 +127,7 @@ class DialogZoneDetail extends LitElement {
               class="flex"
               .location=${this._locationValue}
               .radius=${this._radius}
+              .radiusColor=${this._passive ? "#9b9b9b" : "#FF9800"}
```
Comment (balloob) [inline src/panels/config/zone/dialog-zone-detail.ts]: Let's extract these colors into variables and reuse them.

File: src/components/ha-switch.ts (hunk 1 above)
Comment (bramkragten) [reply src/components/ha-switch.ts]: This was actually a copy/paste from `mwc-switch`, because it was a private function

Comment (bramkragten) [reply src/components/ha-switch.ts]: It would be weird of the parent not to update it's value btw when the switch is changed.

Comment (bramkragten) [reply src/components/ha-switch.ts]: Also, there is no `value-changed` event, just the normal change event of the native checkbox, so it would be impossible for the parent to see what the state is when we would not update the prop? `ev.target.checked` would no longer work.

I could rewrite it and fire the `value-changed` event and not do this, but that would differ us a lot from `mwc-switch` and means a lot of change.

Comment (balloob) [reply src/components/ha-switch.ts]: ok let's keep it.
