### PR TITLE
Fix spacing more info

### LINKED ISSUE #6418: More info dialog spacing 0.113.0b1
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

First mentioned by Tediore in Discord, I noticed it too so opening an issue here as well.

The new more info dialogs in 0.113b have less spacing between the state and other elements (history graph etc). This might've been an intentional design decision, but I feel these are a bit too close together now.

image
image

## Expected behavior

Here's what the previous dialogs looked like for reference, see how there is consistent spacing above and below the dropdown here. 

image

## Steps to reproduce

Open a more info dialog

## Environment

- Home Assistant release with the issue: 0.113.0b1
- Last working Home Assistant release (if known): 0.112.4
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
## Type of change

Fixes https://github.com/home-assistant/frontend/issues/6418

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/more-info/ha-more-info-dialog.ts [hunk 1]
```diff
@@ -199,6 +199,7 @@ export class MoreInfoDialog extends LitElement {
   }
 
   private _computeShowHistoryComponent(entityId) {
+    return true;
```
Comment (ludeeus) [inline src/dialogs/more-info/ha-more-info-dialog.ts:202]: Should probably not be there, leftover from debug?

**Review by ludeeus — CHANGES_REQUESTED** [review]

File: src/dialogs/more-info/ha-more-info-dialog.ts (hunk 1 above)
Comment (bramkragten) [reply src/dialogs/more-info/ha-more-info-dialog.ts:202]: Hehe you think? 😄

**Review by ludeeus — APPROVED** [review]
