### PR TITLE
Call a service: Split remaining service_data's into data and target

### LINKED ISSUE #13827: "tap_action" needs differently defined "entity_id"
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Check these docs (https://www.home-assistant.io/dashboards/actions/#tap-action):

image

Means - I must define `entity_id` inside `data` section:
```
    tap_action:
      action: call-service
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.test_boolean
```
But in practice I may use `data`, `service_data`, `target`:
```
type: entities
entities:
  - input_boolean.test_boolean
  - entity: sun.sun
    name: using data
    tap_action:
      action: call-service
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.test_boolean
  - entity: sun.sun
    name: using service_data
    tap_action:
      action: call-service
      service: input_boolean.toggle
      service_data:
        entity_id: input_boolean.test_boolean
  - entity: sun.sun
    name: using target
    tap_action:
      action: call-service
      service: input_boolean.toggle
      target:
        entity_id: input_boolean.test_boolean
```
image

Seems that using `data`, `service_data`, `target` gives same result.
Probably we should use ONE method and it must be reflected in docs correspondingly.

Now check a picture-entities card:
```
type: picture-elements
elements:
  - type: state-badge
    entity: sun.sun
    tap_action:
      action: call-service
      service: input_boolean.toggle
      target:
        entity_id: input_boolean.test_boolean
    style:
      top: 10%
      left: 10%
  - type: state-badge
    entity: sun.sun
    tap_action:
      action: call-service
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.test_boolean
    style:
      top: 10%
      left: 50%
  - type: state-badge
    entity: sun.sun
    tap_action:
      action: call-service
      service: input_boolean.toggle
      service_data:
        entity_id: input_boolean.test_boolean
    style:
      top: 10%
      left: 30%
  - type: service-button
    title: input_boolean.toggle (target)
    service: input_boolean.toggle
    target:
      entity_id: input_boolean.test_boolean
    style:
      top: 22%
      left: 50%
  - type: service-button
    title: input_boolean.toggle (data)
    service: input_boolean.toggle
    data:
      entity_id: input_boolean.test_boolean
    style:
      top: 27%
      left: 50%
  - type: service-button
    title: input_boolean.toggle (service_data)
    service: input_boolean.toggle
    service_data:
      entity_id: input_boolean.test_boolean
    style:
      top: 32%
      left: 50%
image: /local/images/test/white.jpg
```
image

The `state-badge` element works with `data`, `service_data`, `target`, the `service-button` works with `service_data` only ([as it is described in docs](https://www.home-assistant.io/dashboards/picture-elements/#service-call-button)).

Here a similar situation: we should use ONE method which must be documented in docs.

### Describe the behavior you expected

See above

### Steps to reproduce the issue

See above

### What version of Home Assistant Core has the issue?

2022.9.5

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chrome 105.0.5195.127 

### Which operating system are you using to run this browser?

Win10x64

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change
It's been a while you can use `data` and `target` to call a service as a replacelement for `service_data`.  This migrates the remaining parts to use data and target. Take a good look if you can, since I'm still unsure if this doesn't introduce breaking changes.

It also introduces changes in the picture elements card so the service call button supports that as well. That will need a documentation change to be done. 

```
type: picture-elements
elements:
  - type: service-button
    title: 81% (old)
    style:
      top: 55%
      left: 30%
    service: light.turn_on
    service_data:
      entity_id: light.bed_light
      brightness_pct: 81
  - type: service-button
    title: 81% (new)
    style:
      top: 65%
      left: 30%
    service: light.turn_on
    data:
      brightness_pct: 81
    target:
      entity_id: light.bed_light
  - type: service-button
    title: off (old)
    style:
      top: 55%
      left: 60%
    service: light.turn_off
    service_data:
      entity_id: light.bed_light
  - type: service-button
    title: off (new)
    style:
      top: 65%
      left: 60%
    service: light.turn_off
    target:
      entity_id: light.bed_light
image: https://demo.home-assistant.io/stub_config/floorplan.png
```

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #13827
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **New Features**
  - Introduced a new `target` property for specifying service call targets, enhancing service invocation precision.
  - Added a `data` property for improved service data handling, replacing the previous `serviceData`.

- **Bug Fixes**
  - Improved fallback mechanisms for target and data configurations in the service button, enhancing usability in various scenarios.

- **Documentation**
  - Updated interface `ServiceButtonElementConfig` to include new optional properties, promoting clearer service handling in configurations.

### CODE REVIEW

File: src/panels/lovelace/elements/hui-service-button-element.ts [hunk 1]
```diff
@@ -40,12 +40,17 @@ export class HuiServiceButtonElement
       return nothing;
     }
 
+    const updatedTarget = this._config.target ?? {
+      entity_id: this._config.service_data?.entity_id,
```
Comment (bramkragten) [inline src/panels/lovelace/elements/hui-service-button-element.ts:44]: This should not be needed, targets can technically be in the data of a service call too.

(If we would do this, we should do it for all targets, so also area, device, etc)

Comment (silamon) [reply src/panels/lovelace/elements/hui-service-button-element.ts:44]: Seems like it's somehow required after all: adding other keys.

**Review by bramkragten — APPROVED** [review]

**Comment by silamon** [comment]
Documentation has been added through https://github.com/home-assistant/home-assistant.io/pull/34047. Thanks!
