### PR TITLE
Display HA username + flags in user config

### LINKED ISSUE #3907: User list show name and username
*[move[bot]](https://github.com/apps/move) commented on Mar 12, 2019, 2:42 AM UTC:*

_[move[bot]](https://github.com/apps/move) commented on Feb 16, 2019, 12:56 AM UTC:_

_[mikeplem](https://github.com/mikeplem) commented on Feb 16, 2019, 12:44 AM UTC:_

**Home Assistant release with the issue:**
0.87.0

**Last working Home Assistant release (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**
Docker

**Component/platform:**
User Interface

**Description of problem:**
The User configuration screen should show the name and username in the user details. I did not write down my password but I can still login. I want to change my password but I am not given the option so I try to create a new user but the username is already taken. The user list only appears to show the display name but not the username. Please show the display name and the username in the user list.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
N/A

**Traceback (if applicable):**
N/A

**Additional information:**
N/A

_This issue was moved by [awarecan](https://github.com/awarecan) from [home-assistant/home-assistant#21105](https://github.com/home-assistant/home-assistant/issues/21105)._

_This issue was moved by [iantrich](https://github.com/iantrich) from [home-assistant/home-assistant-polymer#2761](https://github.com/home-assistant/home-assistant-polymer/issues/2761)._

*This issue was moved by [iantrich](https://github.com/iantrich) from [home-assistant/ui-schema#253](https://github.com/home-assistant/ui-schema/issues/253).*

### PR DESCRIPTION
**Pull request by spacegaier**
Depends on core PR https://github.com/home-assistant/core/pull/43283

## Proposed change

Show the user name both in the user table as well as in the edit dialog. Also overwrite the "Group" to "Owners" for the owners to not have to use an extra column for that information.

image

image

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/3907
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/data/user.ts [hunk 1]
```diff
@@ -9,6 +9,7 @@ export const GROUPS = [SYSTEM_GROUP_ID_USER, SYSTEM_GROUP_ID_ADMIN];
 
 export interface User {
   id: string;
+  username: string;
```
Comment (balloob) [inline src/data/user.ts:12]:
```suggestion
  username: string | null;
```

File: src/translations/en.json [hunk 2]
```diff
@@ -1933,15 +1933,19 @@
           "users_privileges_note": "The user group feature is a work in progress. The user will be unable to administer the instance via the UI. We're still auditing all management API endpoints to ensure that they correctly limit access to administrators.",
           "picker": {
             "headers": {
-              "name": "Name",
+              "name": "Display name",
+              "username": "User name",
```
Comment (balloob) [inline src/translations/en.json:1937]:
```suggestion
              "username": "Username",
```

File: src/translations/en.json [hunk 3]
```diff
@@ -1933,15 +1933,19 @@
...
+              "is_active": "Active",
+              "is_owner": "Owner"
             },
             "add_user": "Add user"
           },
           "editor": {
             "caption": "View user",
-            "name": "Name",
+            "name": "Display Name",
+            "username": "User Name",
```
Comment (balloob) [inline src/translations/en.json:1948]: We should not duplicate these translations?

Comment (spacegaier) [reply src/translations/en.json:1948]: Removed the duplication between "add_user" and "editor", but left it for the table headers since there we are usually only capitalizing the first letter, where as for input fields in dialogs we capitalize all.

**Comment by spacegaier** [comment]
I switched to using the check marks without the circle around it, since the circled one we seem to use so far to indicate defaults, e.g. the default dashboard.

File: src/panels/config/users/ha-config-users.ts [hunk 4]
```diff
@@ -43,36 +43,73 @@ export class HaConfigUsers extends LitElement {
...
           template: (groupIds) => html`
             ${this.hass.localize(`groups.${groupIds[0]}`)}
           `,
         },
+        is_active: {
+          title: this.hass.localize(
+            "ui.panel.config.users.picker.headers.is_active"
+          ),
+          type: "icon",
+          width: "10%",
```
Comment (bramkragten) [inline src/panels/config/users/ha-config-users.ts:84]:
```suggestion
```

File: src/panels/config/users/ha-config-users.ts [hunk 5]
```diff
@@ -43,36 +43,73 @@ export class HaConfigUsers extends LitElement {
...
+          template: (is_active) => html`
+            ${is_active ? html` <ha-icon icon="hass:check"> </ha-icon> ` : ""}
+          `,
+        },
+        is_owner: {
+          title: this.hass.localize(
+            "ui.panel.config.users.picker.headers.is_owner"
+          ),
+          type: "icon",
+          width: "10%",
```
Comment (bramkragten) [inline src/panels/config/users/ha-config-users.ts:96]:
```suggestion
```

File: src/panels/config/users/ha-config-users.ts [hunk 6]
```diff
@@ -43,36 +43,73 @@ export class HaConfigUsers extends LitElement {
...
+            ${is_owner ? html` <ha-icon icon="hass:check"> </ha-icon> ` : ""}
+          `,
+        },
         system_generated: {
           title: this.hass.localize(
             "ui.panel.config.users.picker.headers.system"
           ),
           type: "icon",
-          width: "80px",
+          width: "15%",
```
Comment (bramkragten) [inline src/panels/config/users/ha-config-users.ts:108]:
```suggestion
```

File: src/panels/config/users/ha-config-users.ts [hunk 7]
```diff
@@ -43,36 +43,73 @@ export class HaConfigUsers extends LitElement {
...
         },
+        is_active: {
+          title: this.hass.localize(
+            "ui.panel.config.users.picker.headers.is_active"
+          ),
+          type: "icon",
+          width: "10%",
+          sortable: true,
+          filterable: true,
+          template: (is_active) => html`
```
Comment (balloob) [inline src/panels/config/users/ha-config-users.ts:87]: Why wrap the ternary statement in `html` tag ?

File: src/translations/en.json [hunk 8]
```diff
@@ -1933,15 +1933,19 @@
...
+              "system": "System generated",
+              "is_active": "Active",
+              "is_owner": "Owner"
             },
             "add_user": "Add user"
           },
           "editor": {
             "caption": "View user",
-            "name": "Name",
+            "name": "Display Name",
```
Comment (bramkragten) [inline src/translations/en.json:1947]:
```suggestion
            "name": "Display name",
```

File: src/panels/config/users/ha-config-users.ts [hunk 9]
```diff
@@ -43,36 +43,73 @@ export class HaConfigUsers extends LitElement {
...
           ),
           sortable: true,
           filterable: true,
-          width: "30%",
+          width: "20%",
           template: (groupIds) => html`
             ${this.hass.localize(`groups.${groupIds[0]}`)}
           `,
         },
+        is_active: {
```
Comment (balloob) [inline src/panels/config/users/ha-config-users.ts:79]: Is it worth showing this? We don't allow the user to change it.

File: src/panels/config/users/ha-config-users.ts [hunk 10]
```diff
@@ -43,36 +43,73 @@ export class HaConfigUsers extends LitElement {
...
+          ),
+          type: "icon",
+          width: "10%",
+          sortable: true,
+          filterable: true,
+          template: (is_active) => html`
+            ${is_active ? html` <ha-icon icon="hass:check"> </ha-icon> ` : ""}
+          `,
+        },
+        is_owner: {
```
Comment (balloob) [inline src/panels/config/users/ha-config-users.ts:91]: Feels weird to have a whole column just for a single user. We should override the group value with "Owner", since the user has all access regardless of the group.

File: src/panels/config/users/ha-config-users.ts (hunk 6 above)
Comment (spacegaier) [reply src/panels/config/users/ha-config-users.ts:108]: Without those widths, the columns become unusable, since the header is just a single letter.
image

File: src/panels/config/users/ha-config-users.ts (hunk 9 above)
Comment (spacegaier) [reply src/panels/config/users/ha-config-users.ts:79]: I was thinking about adding that option in the future, so that owners can for example enable and disable guest users when needed.

File: src/panels/config/users/ha-config-users.ts (hunk 10 above)
Comment (spacegaier) [reply src/panels/config/users/ha-config-users.ts:91]: Override purely in the frontend rendering or in the backend service?

Comment (balloob) [reply src/panels/config/users/ha-config-users.ts:88]: Frontend.

File: src/panels/config/users/ha-config-users.ts (hunk 9 above)
Comment (balloob) [reply src/panels/config/users/ha-config-users.ts:78]: Then we should show it in the UI when we can do that.

File: src/panels/config/users/ha-config-users.ts (hunk 10 above)
Comment (spacegaier) [reply src/panels/config/users/ha-config-users.ts]: Okay, added that.

File: src/panels/config/users/ha-config-users.ts (hunk 9 above)
Comment (spacegaier) [reply src/panels/config/users/ha-config-users.ts]: I added it now. Took a lot longer than hoped, but that was my own unfamiliarity with some backend aspects.
https://github.com/home-assistant/core/pull/43463 and https://github.com/home-assistant/frontend/pull/7757

Should those be merged first and then we continue with this PR?

Comment (bramkragten) [reply src/panels/config/users/ha-config-users.ts]: Let's do that in a new PR

File: src/panels/config/users/ha-config-users.ts (hunk 6 above)
Comment (bramkragten) [reply src/panels/config/users/ha-config-users.ts]: Then set them to fixed widths, no need to have them grow.

File: src/translations/en.json [hunk 11]
```diff
@@ -89,6 +89,7 @@
     }
   },
   "groups": {
+    "owners": "Owners",
```
Comment (bramkragten) [inline src/translations/en.json:92]:
```suggestion
    "owner": "Owner",
```

**Review by bramkragten — APPROVED** [review]
