### PR TITLE
Return focus after dialogs close

### LINKED ISSUE #10754: Modal dialogs need keyboard focus management
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For nearly all modal dialogs I can think of, the keyboard focus does not transfer to the dialog as it should for accessibility.  I need to to click or space bar once  to get the focus inside the dialog to be able to read it with a screen reader.  Furthermore, after closing a dialog with escape or button, keyboard focus is transferred all the way back to the beginning of the page DOM, instead of back to the button which opened the dialog as expected.

### Describe the behavior you expected

In general, these dialogs should all follow the [modal dialog design pattern in the W3C ARIA Authoring Practices](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal).  These design patterns have detailed notes on managing keyboard focus.

### Steps to reproduce the issue

For example, I might go to Configuration → Entities and:
1. Click on an entity to get it's settings dialog, and then click again to read it
2. Click the control button to get that dialog, then have to click again to read it
3. Click the attributes button, then have to click again to read them
4. Hit escape to get out, then have to navigate back to where I started

2.
3.
...
For example, I might go to Configuration → Entities and:
1. Click on an entity to get it's settings dialog, and then click again to read it
2. Click the control button to get that dialog, then have to click again to read it
3. Click the attributes button, then have to click again to read them
4. Hit escape to get out, then have to navigate back to where I started

### What version of Home Assistant Core has the issue?

Any

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Firefox & Chrome (latest stable)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

I suspect that the cause of this may be also causing lots of other "double action" keyboard issues throughout the UI, but I figured I'd keep this issue tight and to the point rather than jumping to that conclusion.

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

Adds an event handler to return focus, where possible, to the button or control that opened the dialog.  This is best practice for good accessibility.  Here are some details on the implementation:
- Finds and stores the active element and possibly dialog generically right before new dialog is shown
- Data is stored in the module in tag dictionary same as created elements, and typing was added for better code quality
- Handles the common special case where dialog is opened from a popup menu and returns focus to the trigger
- Handles the replace situation for more info / entity settings
- When dialog is opened from another dialog, focus method for `mwc-dialog` becomes the fallback in case of failure
### Limitations
1. Assumes the dialog fires the `dialog-closed` event.  The majority of the 70+ dialogs do, but about 20 or so need to be updated in future changes.
2. Assumes the element that opened the dialog is focusable, which is not always the case, but should be for keyboard accessibility (e.g. entity settings dialogs from configuration page and some more info dialogs from certain cards)

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: #10754 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

**Comment by steverep** [comment]
Approvals is slower than usual... something I did? 😕 😄

**Comment by zsarnett** [comment]
Bram is on Holiday 😄  I haven't been able to take a look yet.

**Comment by steverep** [comment]
Ah I was wondering where he disappeared to.  Okay thanks for the heads up.

**Comment by steverep** [comment]
Any chance this can get a review in time for April's beta?

File: src/dialogs/make-dialog-manager.ts [hunk 1]
```diff
@@ -60,11 +72,46 @@ export const showDialog = async (
...
+  if (mainWindow.history.state?.replaced) {
+    LOADED[dialogTag].closedFocusTarget =
+      LOADED[mainWindow.history.state.dialog].closedFocusTarget;
+    LOADED[dialogTag].closedFocusDialog =
+      LOADED[mainWindow.history.state.dialog].closedFocusDialog;
+  } else {
+    let focusedDialog: LoadedDialogInfo["closedFocusDialog"] = null;
+    let focusedElement = document.activeElement;
+    while (focusedElement?.shadowRoot?.activeElement) {
+      focusedElement = focusedElement.shadowRoot.activeElement;
```
Comment (bramkragten) [inline src/dialogs/make-dialog-manager.ts:97]: Use https://github.com/home-assistant/frontend/blob/dev/src/common/dom/deep-active-element.ts#L1

**Comment by bramkragten** [comment]
I wonder if we need this change, as `mwc-dialog` should handle this (it does here I think? https://material-components.github.io/material-web/demos/dialog/)

I think the issue is the location in the DOM where we add the dialogs probably? They are in a different place in the DOM then the element that triggers it...

Would have to look in to that

**Comment by steverep** [comment]
There's no code in `mwc-dialog` to handle returning focus.  What OS/browser are you using on those demos?  Focus is not put back on the trigger for me in Chrome or Firefox on Windows.  It's just letting the browser handle it, which varies with browser.  For example, Firefox always throws focus back to the top of the document, whereas Chrome tends to throw focus further down the page.

You could make the argument that `mwc-dialog` should have a default to return to the last focused element, but that will only ever handle a subset of cases.  For example, `mwc-dialog` is never going to handle cases of replacing dialogs, trigger buttons becoming hidden, dialogs changing the DOM on close, etc.  That logic needs to be specific to the app.

**Comment by bramkragten** [comment]
I'm using Chrome on MacOS

**Comment by steverep** [comment]
> I'm using Chrome on MacOS

I don't have a Mac to reproduce that, but I'd be shocked if webkit was actively trying to return focus.  It doesn't do that on iOS.

In any case,leaving it up to the browser isn't a good or even consistent approach as I said, and it's definitely not `mwc-dialog` code.  All the component does is use [PolymerLabs/blocking-elements](https://github.com/PolymerLabs/blocking-elements) to set the `inert` and `aria-hidden="true"` attributes outside the dialog when it's open, and removes them when it's closed.  The only code regarding focus is to set it when the dialog is open, but only if the `dialogInitialFocus` attribute is set.

**Comment by steverep** [comment]
@bramkragten  so what's the review verdict here?  Have I convinced you this code is needed independent of `mwc-dialog` in order to handle HA situations?

**Comment by bramkragten** [comment]
Yeah, I'm seriously considering it, want to make it as easy as possible to maintain... Will get back to you this week.

**Comment by steverep** [comment]
@balloob can you intercede here?  I've commented in the past that HA does not prioritize accessibility and this PR lingering on without a review is an example.  This implements simple focus management for dialogs - a fundamental piece of good keyboard accessibility.

**Comment by zsarnett** [comment]
Please stop pinging developers. Bram advised he will be reviewing.

This is not about limiting Accessibility so don't try to pull on that string. This is about maintainability.

Normally your PRs go through without much question. This one adds a lot of code we have to maintain. Be patient

**Comment by steverep** [comment]
> Please stop pinging developers. Bram advised he will be reviewing.

That was weeks ago and much work has come and merged since.  I don't see any problem with trying to call attention and start a discussion with the project's lead on prioritizing accessibility.  It was not meant to offend anyone.

> This is not about limiting Accessibility so don't try to pull on that string. This is about maintainability.

I didn't accuse the project of limiting accessibility.  I accused the project of not prioritizing it.  There's a huge difference.  If there is a way to make it more maintainable, then review and I'd be happy to implement it.  No one has done that.

> Normally your PRs go through without much question. This one adds a lot of code we have to maintain. Be patient

Please don't pretend like this is an exorbitant amount of code.  Again, many more lines have come and merged since.  And, just as food for thought, do you have any idea how often people with disabilities are told to be patient when trying to resolve accessibility or accommodation issues?  It's not about patience - it's just about treating those issues with the priority they deserve.

File: src/dialogs/make-dialog-manager.ts [hunk 2]
```diff
@@ -60,11 +72,46 @@ export const showDialog = async (
...
+      if (slotRoot instanceof ShadowRoot) {
+        const slotHost = slotRoot.host;
+        if (slotHost instanceof HaButtonMenu) {
+          // Use trigger button since popup menu will be hidden again
+          focusedElement = slotHost.querySelector('[slot="trigger"]');
+          break;
+        } else if (slotHost instanceof HaDialog) {
+          // Focus will return inside another dialog
+          focusedDialog = slotHost;
+        }
```
Comment (bramkragten) [inline src/dialogs/make-dialog-manager.ts:110]: Can we instead add a function to the elements that need this, check if that function exists and then let that function return the correct element? So the logic is in the element and not in the dialog manager?

**Review by bramkragten — DISMISSED** [review]

File: src/dialogs/make-dialog-manager.ts (hunk 2 above)
Comment (steverep) [reply src/dialogs/make-dialog-manager.ts:110]: My initial reaction was yes, but after thinking about how to code it, it won't really remove the logic from here because what to do with the returned value depends on the type of element.  This module would still need to know whether it's modifying the focus target or just recording an underlay dialog.

If you just want this logic out of the dialog module, I think I have a much better idea.  Give me a day or two to add a commit.

Comment (steverep) [reply src/dialogs/make-dialog-manager.ts]: I moved all of the active element/dialog searching to the `deepActiveElement` function, which now has 3 different modes.  So all of that is now in one place.  The rest of the code left in the dialog manager just grabs it, stores it, and sets the event handler.  See if that resolves your concerns.

Apologies for the delay... had to learn some unfamiliar Typescript then work around a known limitation.

File: src/common/dom/deep-active-element.ts [hunk 3]
```diff
@@ -1,8 +1,47 @@
...
-  }
-  return root.activeElement;
+import { HaDialog } from "../../components/ha-dialog";
+import { HaButtonMenu } from "../../components/ha-button-menu";
+
+export const deepActiveElement = <
+  modeType extends "normal" | "dialog" | "check"
+>(
+  root: DocumentOrShadowRoot = document,
+  mode?: modeType,
```
[the remark this answers is not in the document]
Comment (steverep) [reply src/common/dom/deep-active-element.ts:8]: Making this change would decouple `mode` from the return type, which defeats the purpose of the conditional return.

Or are you just suggesting to remove `"normal"` as a possibility?

File: src/common/dom/deep-active-element.ts [hunk 4]
```diff
@@ -1,8 +1,47 @@
...
-  root: DocumentOrShadowRoot = document
-): Element | null => {
-  if (root.activeElement?.shadowRoot?.activeElement) {
-    return deepActiveElement(root.activeElement.shadowRoot);
-  }
-  return root.activeElement;
+import { HaDialog } from "../../components/ha-dialog";
+import { HaButtonMenu } from "../../components/ha-button-menu";
+
+export const deepActiveElement = <
```
[the remark this answers is not in the document]
Comment (steverep) [reply src/common/dom/deep-active-element.ts:4]: I'm not following your suggestion.  Do you mean have the dialog manager call a new function that calls the original `deepActiveElement`?  It's impossible to use the original version because the checks need to be done at the document and every shadow root level.

File: src/common/dom/deep-active-element.ts [hunk 5]
```diff
@@ -1,8 +1,47 @@
...
+      }
+    }
+
+    deeperElement = activeElement?.shadowRoot?.activeElement;
+    activeElement = deeperElement ?? activeElement;
+  } while (deeperElement);
+
+  if (mode === "check") return false as any;
+  if (mode === "dialog") return [activeElement, activeDialog] as any;
+  return activeElement as any;
```
[the remark this answers is not in the document]
Comment (steverep) [reply src/common/dom/deep-active-element.ts:46]: It needs to be there or Typescript throws an error.  This is the known limitation I referred to in my comment.  Apparently, conditional returns work great for the callers, but TS can't resolve it inside the function.  The work around is either to assert as any or use a bunch of overload signatures instead of the conditional.  See microsoft/TypeScript#33912 or any of the many duplicate issues.

File: src/common/dom/deep-active-element.ts [hunk 6]
```diff
@@ -1,8 +1,47 @@
...
+    // Mode to check if a target is focused
+    if (mode === "check" && checkElement === activeElement) return true as any;
+
+    // Mode to determine closed dialog targets
+    if (mode === "dialog") {
+      // Detect when focus is slotted into certain components
+      const slotRoot = activeElement?.assignedSlot?.getRootNode();
+      if (slotRoot instanceof ShadowRoot) {
+        const slotHost = slotRoot.host;
+        if (slotHost instanceof HaButtonMenu) {
```
[the remark this answers is not in the document]
Comment (steverep) [reply src/common/dom/deep-active-element.ts:29]: Working on a new more generic approach that will resolve this...

**Comment by steverep** [comment]
@bramkragten  this is ready for another look.  I like this version better and I think it settles all your issues.

File: src/dialogs/make-dialog-manager.ts [hunk 7]
```diff
@@ -137,3 +168,31 @@ export const makeDialogManager = (
...
+
+  // Make sure backdrop is fully updated before trying (especially needed for underlay dialogs)
+  await nextRender();
+
+  // Try all targets in order and stop when one works
+  for (const focusTarget of closedFocusTargets) {
+    if (focusTarget instanceof HTMLElement) {
+      focusTarget.focus();
+      focusedElement = deepActiveElement();
+      if (focusedElement && focusedElement !== document.body) break;
```
Comment (bramkragten) [inline src/dialogs/make-dialog-manager.ts:187]: We can return here right?

**Comment by bramkragten** [comment]
Looks a lot better 👍

**Review by bramkragten — APPROVED** [review]
