### PR TITLE
Logbook card: place a gap between an icon/image & a text

### LINKED ISSUE #13131: Logbook card: tight placement for entities with images
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Suppose some entity has an `entity_picture` attribute specified.
Then this image is displayed when the entity is shown in a Logbook card.

The problem is that a horizontal space between the image & a right part of the logbook's row is too narrow:
image

Earlier this gap was bigger.

### Describe the behavior you expected

There is a gap between an image and a text.

### Steps to reproduce the issue

1. Create & customize a helper:
```
homeassistant:
  customize:
    input_boolean.flag_with_image:
      entity_picture: /local/images/blue.jpg

input_boolean:
  flag_with_image:
```

2. Create a card:
```
type: vertical-stack
cards:
  - type: entities
    entities:
      - input_boolean.flag_with_image
  - type: logbook
    entities:
      - input_boolean.flag_with_image
    hours_to_show: 1
```

3. Start changing a helper's value.

### What version of Home Assistant Core has the issue?

2022.7.0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chrome 103.0.5060.114 

### Which operating system are you using to run this browser?

Win10x64

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ildar170975**
## Proposed change

Add a horizontal gap between an icon/image and a text.
Currently w/o this gap a placement of these elements is very tight.

For details - see https://github.com/home-assistant/frontend/issues/13131

изображение

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/13131
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ x] The code change is tested and works locally.
- [x ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by frogman544 — DISMISSED** [review]

File: src/panels/logbook/ha-logbook-renderer.ts [hunk 1]
```diff
@@ -560,6 +560,7 @@ class HaLogbookRenderer extends LitElement {
         .icon-message {
           display: flex;
           align-items: center;
+          column-gap: 8px;
```
Comment (zsarnett) [inline src/panels/logbook/ha-logbook-renderer.ts:563]: We shouldn't use gaps without using grid

**Comment by zsarnett** [comment]
https://github.com/home-assistant/frontend/pull/13348/files#diff-fe0260e1d2f2eea8dcb455d644828da865c94f2522881f2abd0a24012f808cc0R615-R619

.narrow .icon-message state-badge {
    margin-left: 0;
    margin-inline-start: 0;
    margin-inline-end: 8px;
    margin-right: 8px;
    direction: var(--direction);
}

File: src/panels/logbook/ha-logbook-renderer.ts (hunk 1 above)
Comment (ildar170975) [reply src/panels/logbook/ha-logbook-renderer.ts]: But this is a flex, gaps for flex too.
https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap
This style works in FF & Chrome (Win), iOS Companion App as well

Comment (zsarnett) [reply src/panels/logbook/ha-logbook-renderer.ts:563]: Thats okay that it works. I would rather use the margin as mentioned below to keep things consistent in the code

Comment (ildar170975) [reply src/panels/logbook/ha-logbook-renderer.ts]: Agree, using a margin is a possible solution.
But some things are easier to solve on a higher level - i.e. on the flexbox container level (.icon-message).
Assume that in future something will change - like "3rd column is added", then we will face this "tight problem" again.

Well, both variants are OK for me!

Comment (ildar170975) [reply src/panels/logbook/ha-logbook-renderer.ts]: Let's using margin-right then

Comment (zsarnett) [reply src/panels/logbook/ha-logbook-renderer.ts:563]: You will need to update margin-inline-end as well

Comment (ildar170975) [reply src/panels/logbook/ha-logbook-renderer.ts]: Not sure if it is needed since the element is never rotated...
But OK - let's set `margin-inline-end` as well!

**Review by zsarnett — APPROVED** [review]
