### PR TITLE
Fix for Zone icon visibility on Map panel and Lovelace Map card

### LINKED ISSUE #3409: Zone icon legibility issues on Map panel and Lovelace Map card
**Home Assistant release with the issue:**
0.96.3 and way earlier

**UI (States or Lovelace UI?):**
Lovelace

**Description of problem:**
The map panel has had a long-standing issue with illegible zone icons on dark themes for quite a while - there are forum posts [here](https://community.home-assistant.io/t/how-to-change-map-icon/59218), [here](https://community.home-assistant.io/t/separate-css-for-map-icons/97864) and [here](https://community.home-assistant.io/t/slate-a-new-dark-theme-updated/86410/11?u=seanm), and in at least one case a theme creator [added black borders around all icons](https://community.home-assistant.io/t/green-slate/96179/4?u=seanm) just to make this legible. 

See this comparison screenshot of my instance on the left (a dark theme called "Slate") and the [HA demo](https://demo.home-assistant.io/#/map) on the right with the default white theme:

zoneicons1

And here's another comparison using my own instance on a dark theme (Slate) and light theme (default), there's a drastic difference in legibility. At the default zoom level, the icons are nearly invisible on a dark theme:

zoneicons2

Here is where the icon is generated: https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/map/ha-panel-map.js#L116

I think the issue is that it does not seem to have any styling applied to it, so it uses the `primary-text-color`. This works out OK on the default theme where the text color is black, but that's not good for dark themes since the `primary-text-color` is always some variation of white. And white icons overlaid on a white background is near impossible to see.

My initial thought was that the icon should be hardcoded to `#000000` / black, and I think that would work for the actual map panel because (so far?) there's no option to use dark tiles there.

But then I discovered another related issue involving the "dark mode" map tiles in Lovelace cards that @JBassett added in this PR: https://github.com/home-assistant/home-assistant-polymer/pull/3250 . When using the dark mode tiles on the default theme, that exhibits the same issue as mentioned above but in reverse (black on black instead of white on white).

Here's a screenshot demonstrating the legibility issue with a "dark mode" map card on the default theme. Even with me zoomed in super far and with a huge red arrow pointing at the icon, it's still hard to see:

darkmode

There might be a better solution, but basically I think it needs to be:

Default map tiles - icon hardcoded to black `#000000`
Dark map tiles - icon hard coded to white `#FFFFFF`

### PR DESCRIPTION
**Pull request by springstan**
Fixes #3409

Description:
- Default map panel: icon color hardcoded to black e.g `#000000`
- Lovelace Map card: icon color depends on darkMode setting:
  - darkMode is set - icon color is `#FFFFFF` 
  - darkMode is not set - icon color is `#000000`

Results with default and [slate](https://github.com/seangreen2/slate_theme) theme:
- Default map panel:
map

- Lovelace Map Card:
default_white
default_black

### CODE REVIEW

File: src/panels/lovelace/cards/hui-map-card.ts [hunk 1]
```diff
@@ -325,11 +325,27 @@ class HuiMapCard extends LitElement implements LovelaceCard {
...
+        }
+
         // create marker with the icon
         mapItems.push(
           Leaflet.marker([latitude, longitude], {
             icon: Leaflet.divIcon({
-              html: icon ? `<ha-icon icon="${icon}"></ha-icon>` : title,
+              html: iconHTML,
               iconSize: [24, 24],
               className: "",
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-map-card.ts]:
```
              html: icon ? `<ha-icon icon="${icon}"></ha-icon>` : title,
              iconSize: [24, 24],
              className: this._config!.dark_mode === true ? "dark" : "light",
            }),
```

Comment (bramkragten) [reply src/panels/lovelace/cards/hui-map-card.ts]: Add a class to the marker and define a class in `hui-map-card`: `.dark { color: #fafaf8;}`

File: src/panels/map/ha-panel-map.js [hunk 2]
```diff
@@ -129,7 +133,7 @@ class HaPanelMap extends LocalizeMixin(PolymerElement) {
           className: "",
```
Comment (bramkragten) [inline src/panels/map/ha-panel-map.js]: Use the `className` here too.

File: src/panels/lovelace/cards/hui-map-card.ts (hunk 1 above)
Comment (springstan) [reply src/panels/lovelace/cards/hui-map-card.ts]: Implemented in https://github.com/home-assistant/home-assistant-polymer/pull/4085/commits/9d10ab8f054f4dcf50bc10b0768c8194b4359c2b

File: src/panels/map/ha-panel-map.js (hunk 2 above)
Comment (springstan) [reply src/panels/map/ha-panel-map.js]: Implemented in https://github.com/home-assistant/home-assistant-polymer/pull/4085/commits/9d10ab8f054f4dcf50bc10b0768c8194b4359c2b

**Review by bramkragten — APPROVED** [review]
