### PR TITLE
Use new localized context state and source in logbook

### LINKED ISSUE #12698: Broken localization of logbook messages (and others)
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Log messages are created as concatenating words. It may work in some languages but it does not work in others. The sentence does not make any sense eg. in Czech. We don't need any "by" or "from" words in sentences. We have different word order. There are other problems like https://en.wikipedia.org/wiki/Grammatical_case

The same problem was already reported before:

- https://github.com/home-assistant/frontend/issues/7179
- https://github.com/home-assistant/frontend/issues/11509

### Describe the behavior you expected

I understand it's hard to solve it but I think there are two ways:

- Table/List - each part of the sentence as a label with value.
- Prepare whole sentences with placeholders (eg. for user) so the translator can change word order etc.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

master

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bdraco**
Does not need to wait for https://github.com/home-assistant/core/pull/72333 since we can't rewrite history.  (the `source` was only exposed on the original message and missing from the context message). 

## Proposed change

- Refactor to remove more static english strings that come from the backend

- Everything should be localized except for external events (https://github.com/home-assistant/frontend/pull/12742/files#diff-fe0260e1d2f2eea8dcb455d644828da865c94f2522881f2abd0a24012f808cc0R413)

Fixes #12698 (except for the backend messages that come from integrations since we don't control thoose)

Screen Shot 2022-05-20 at 14 18 19
Screen Shot 2022-05-20 at 14 17 47
Screen Shot 2022-05-20 at 14 17 42
Screen Shot 2022-05-20 at 14 17 30
Screen Shot 2022-05-20 at 14 17 13
Screen Shot 2022-05-20 at 14 16 46
Screen Shot 2022-05-20 at 14 16 39
Screen Shot 2022-05-20 at 14 16 33
Screen Shot 2022-05-20 at 14 37 34
Screen Shot 2022-05-20 at 14 38 55
Screen Shot 2022-05-20 at 14 46 15

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/logbook/ha-logbook-renderer.ts [hunk 1]
```diff
@@ -31,9 +34,30 @@ import {
...
+
+const localizeTriggerMessages = (hass: HomeAssistant, message: string) => {
+  for (const triggerPhrase in triggerPhrases) {
+    if (message.startsWith(triggerPhrase)) {
+      message = message.replace(
+        triggerPhrase,
+        `${hass.localize(
+          `ui.components.logbook.${triggerPhrases[triggerPhrase]}`
+        )} `
+      );
```
Comment (balloob) [inline src/panels/logbook/ha-logbook-renderer.ts:52]: The problem with localization is that we can't assume that words are all the same order. So it would need to be that we extract the "other part" and inject that as a  variable. 

Something like this (untested):

```suggestion
      message = hass.localize(
        `ui.components.logbook.${triggerPhrases[triggerPhrase]}`,
        {what: message.substr(triggerPhrase)}
      )
```

Comment (balloob) [reply src/panels/logbook/ha-logbook-renderer.ts:52]: Now each described event can be triggered by different things. So it will be wild to try to create a localized string for every permutation, which would be necessary if we want to do it 100% correct.

We could also split it up in the UI such that we don't have to create localized strings for each permutation of trigger combined with each cause.

Comment (balloob) [reply src/panels/logbook/ha-logbook-renderer.ts:52]: btw I still think that this PR is an improvement and we should go for it

Comment (bdraco) [reply src/panels/logbook/ha-logbook-renderer.ts:52]: I picked the 3 that appear the most common since it will get most of the cases.

I don't think we can ever get to 100% without heroic effort and singular dedication to this.  It would take an army to get there!

Comment (bdraco) [reply src/panels/logbook/ha-logbook-renderer.ts:52]: These are the ones its trying to pick up

https://github.com/home-assistant/core/blob/dev/homeassistant/components/homeassistant/triggers/state.py#L182
https://github.com/home-assistant/core/blob/dev/homeassistant/components/homeassistant/triggers/numeric_state.py#L159
https://github.com/home-assistant/core/blob/dev/homeassistant/components/homeassistant/triggers/time.py#L57
https://github.com/home-assistant/core/blob/dev/homeassistant/components/homeassistant/triggers/time_pattern.py#L82
https://github.com/home-assistant/core/blob/dev/homeassistant/components/homeassistant/triggers/homeassistant.py#L39
https://github.com/home-assistant/core/blob/dev/homeassistant/components/homeassistant/triggers/homeassistant.py#L57
https://github.com/home-assistant/core/blob/dev/homeassistant/components/homeassistant/triggers/event.py#L109

Maybe we make we also make these keys?

Comment (bdraco) [reply src/panels/logbook/ha-logbook-renderer.ts:52]: I think we already have enough to do that since context_source is that without the 'triggered by' https://github.com/home-assistant/core/blob/dev/homeassistant/components/automation/logbook.py

So we can make all the source strings to a locale key and use that when available

I think that was actually the original plan but we never got around to implementing on the frontend

File: src/panels/logbook/ha-logbook-renderer.ts [hunk 2]
```diff
@@ -294,38 +269,119 @@ class HaLogbookRenderer extends LitElement {
...
+      return "";
+    }
+    const contextMessage = localizeTriggerMessages(
+      this.hass,
+      item.context_message
+    );
+    if (item.context_event_type === "automation_triggered") {
+      return html`${this.hass.localize("ui.components.logbook.triggered_by")}
+      ${this._renderEntity(item.context_entity_id, item.context_entity_id_name)}
+      ${item.context_message
```
Comment (bdraco) [inline src/panels/logbook/ha-logbook-renderer.ts:373]: We should use context_source since we can localize it much easier

File: src/panels/logbook/ha-logbook-renderer.ts (hunk 1 above)
Comment (bdraco) [reply src/panels/logbook/ha-logbook-renderer.ts:52]: https://github.com/home-assistant/core/blob/9c3f9491651f409e8b4d0d645115b55b14f06165/homeassistant/components/homeassistant/triggers/time.py?rgh-link-date=2022-05-22T05%3A58%3A48Z#L163
https://github.com/home-assistant/core/blob/9c3f9491651f409e8b4d0d645115b55b14f06165/homeassistant/components/homeassistant/triggers/time.py?rgh-link-date=2022-05-22T05%3A58%3A48Z#L121

Comment (bdraco) [reply src/panels/logbook/ha-logbook-renderer.ts]: Last push contained the scope to only the trigger messages since thats 99% of what I see in the logbook anyways

**Comment by bdraco** [comment]
I moved export const `localizeTriggerSource` next to `localizeStateMessage` in `data/logbook` since it seemed like it was a better fix there.

**Comment by zsarnett** [comment]
We can merge today most likely. Ill review this soon. Just need to fix the conflicts with your other PR

**Comment by bdraco** [comment]
> It looks much much better (eg. `ui.components.logbook.for` is gone) but it still looks (based on the screenshots) that texts are concatenated together... It would be still difficult for translator to translate it in a way that make sense.
> 
> Something like this can be traslated more easier:
> 
> ```
> Light turned on
> Triggered by automatition: Some automatition name
> Triggered by state of: Some entity
> ```

Unfortunately, while it is easier to translate, splitting makes it look inconstant so it would need a UX redesign which is outside the scope of this PR.   

Since this is an improvement over the last iteration, and it will make it easier to refactor into a multi-line setup later.  I suggest we merge this now and iterate on the UX design in the future.

**Review by zsarnett — APPROVED** [review]

**Comment by kukulich** [comment]
> Since this is an improvement over the last iteration, and it will make it easier to refactor into a multi-line setup later. I suggest we merge this now and iterate on the UX design in the future.

I totally agree 👍 It is already an improvement 👍  I just hope that the UX redesign will not be forgotten :)
