### PR TITLE
Fix typo in alarm editor

### LINKED ISSUE #2679: Alarm Panel width impacts column count
**Home Assistant release with the issue:**

0.86
**Last working Home Assistant release (if known):**
0.85

**Browser and Operating System:**

Chrome

**Description of problem:**

Alarm panel seems to result in a change in column behavior.  Prior this UI would result in 3 columns, now it results in two columns.  All other combinations of panels I can find seem to have 3 columns.

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**
screen shot 2019-02-04 at 10 02 25 pm

### LINKED ISSUE #2702: Alarm Panel - Arm Custom Bypass button shows blank
ffd01822-1efd-4a61-9190-b5edcba2f7b8

**Home Assistant release with the issue:**

**Last working Home Assistant release (if known):**

**Browser and Operating System:**

**Description of problem:**

**Javascript errors shown in the web inspector (if applicable):**
```

```

**Additional information:**

### PR DESCRIPTION
**Pull request by iantrich**
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/2702
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/2679

### CODE REVIEW

File: src/panels/lovelace/cards/hui-alarm-panel-card.ts [hunk 1]
```diff
@@ -50,20 +52,22 @@ class HuiAlarmPanelCard extends LitElement implements LovelaceCard {
...
-    };
-  }
+  @property() public hass?: HomeAssistant;
+  @property() private _config?: Config;
+  @property() private _code?: string;
 
   public getCardSize(): number {
-    return 4;
+    if (!this._config || !this.hass) {
+      return 0;
```
Comment (balloob) [inline src/panels/lovelace/cards/hui-alarm-panel-card.ts]: We're never 0. In that case return 3.

**Review by balloob — APPROVED** [review]
