### PR TITLE
Fix relative time above 22 hours

### LINKED ISSUE #14815: Relative time displays days incorrectly
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The UI shows that my alarm is "Tomorrow":
image

However, it's actually on the 19th of December:
image

And currently it's the 17th:
image

If I set the alarm to the 20th, then it shows "In 2 days" instead of "In 3 days".

### Describe the behavior you expected

I expect the UI to show "In 2 days"

### Steps to reproduce the issue

1. Create an entity that shows relative time. Set it to 9:20 in days.
2. Create a tile that shows that entity. See configuration in the relevant section.
3. Set your timezone to GMT+2
4. Look at the tile between 23:00 and midnight (might happen earlier too)

### What version of Home Assistant Core has the issue?

2022.12.6

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Firefox 107.0.1, iOS app & Safari

### Which operating system are you using to run this browser?

Windows 11, iOS 16.1

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

```yaml
type: tile
entity: sensor.somneo_next_alarm
name: Next alarm
```

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Nezz**
## Proposed change

This PR fixes #14815. The issue affects relative time displays greater than 22 hours where the time difference is displayed in days, weeks, months or years.

The previous implementation did not take into account when a day/week/month/year starts or ends, therefore the frontend displayed text that was ±1 day/week/month/year off.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
type: tile
entity: sensor.somneo_next_alarm
name: Next alarm
```

## Additional information

- This PR fixes or closes issue: fixes #14815
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by Nezz** [comment]
Here is a list of newly added test cases fixed by this PR:
<details>
  <summary>Details</summary>

```
  1) relativeTime
       23 hour difference during the same day
         past tense:

      AssertionError: expected 'yesterday' to equal '23 hours ago'
      + expected - actual

      -yesterday
      +23 hours ago
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:79:48)
      at processImmediate (node:internal/timers:466:21)

  2) relativeTime
       23 hour difference during the same day
         future tense:

      AssertionError: expected 'tomorrow' to equal 'in 23 hours'
      + expected - actual

      -tomorrow
      +in 23 hours
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:82:48)
      at processImmediate (node:internal/timers:466:21)

  3) relativeTime
       23 hour difference during the same day
         without tense:

      AssertionError: expected '1 day' to equal '23 hours'
      + expected - actual

      -1 day
      +23 hours
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:85:48)
      at processImmediate (node:internal/timers:466:21)

  4) relativeTime
       33 hour difference during three days
         past tense:

      AssertionError: expected 'yesterday' to equal '2 days ago'
      + expected - actual

      -yesterday
      +2 days ago
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:107:48)
      at processImmediate (node:internal/timers:466:21)

  5) relativeTime
       33 hour difference during three days
         future tense:

      AssertionError: expected 'tomorrow' to equal 'in 2 days'
      + expected - actual

      -tomorrow
      +in 2 days
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:110:48)
      at processImmediate (node:internal/timers:466:21)

  6) relativeTime
       33 hour difference during three days
         without tense:

      AssertionError: expected '1 day' to equal '2 days'
      + expected - actual

      -1 day
      +2 days
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:113:48)
      at processImmediate (node:internal/timers:466:21)

  7) relativeTime
       5 day difference Sunday to Friday
         with Sunday as first day of the week
           past tense:

      AssertionError: expected 'last week' to equal '5 days ago'
      + expected - actual

      -last week
      +5 days ago
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:122:50)
      at processImmediate (node:internal/timers:466:21)

  8) relativeTime
       5 day difference Sunday to Friday
         with Sunday as first day of the week
           future tense:

      AssertionError: expected 'next week' to equal 'in 5 days'
      + expected - actual

      -next week
      +in 5 days
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:125:50)
      at processImmediate (node:internal/timers:466:21)

  9) relativeTime
       5 day difference Sunday to Friday
         with Sunday as first day of the week
           without tense:

      AssertionError: expected '1 week' to equal '5 days'
      + expected - actual

      -1 week
      +5 days
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:128:50)
      at processImmediate (node:internal/timers:466:21)

  10) relativeTime
       5 day difference Tuesday to Sunday
         with Monday as first day of the week
           past tense:

      AssertionError: expected 'last week' to equal '5 days ago'
      + expected - actual

      -last week
      +5 days ago
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:162:50)
      at processImmediate (node:internal/timers:466:21)

  11) relativeTime
       5 day difference Tuesday to Sunday
         with Monday as first day of the week
           future tense:

      AssertionError: expected 'next week' to equal 'in 5 days'
      + expected - actual

      -next week
      +in 5 days
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:165:50)
      at processImmediate (node:internal/timers:466:21)

  12) relativeTime
       5 day difference Tuesday to Sunday
         with Monday as first day of the week
           without tense:

      AssertionError: expected '1 week' to equal '5 days'
      + expected - actual

      -1 week
      +5 days
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:168:50)
      at processImmediate (node:internal/timers:466:21)

  13) relativeTime
       30 day difference during the same month
         past tense:

      AssertionError: expected 'this month' to equal '4 weeks ago'
      + expected - actual

      -this month
      +4 weeks ago
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:191:48)
      at processImmediate (node:internal/timers:466:21)

  14) relativeTime
       30 day difference during the same month
         future tense:

      AssertionError: expected 'this month' to equal 'in 4 weeks'
      + expected - actual

      -this month
      +in 4 weeks
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:194:48)
      at processImmediate (node:internal/timers:466:21)

  15) relativeTime
       30 day difference during the same month
         without tense:

      AssertionError: expected '0 months' to equal '4 weeks'
      + expected - actual

      -0 months
      +4 weeks
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:197:48)
      at processImmediate (node:internal/timers:466:21)

  16) relativeTime
       11 month difference during same year
         past tense:

      AssertionError: expected 'this year' to equal '11 months ago'
      + expected - actual

      -this year
      +11 months ago
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:219:48)
      at processImmediate (node:internal/timers:466:21)

  17) relativeTime
       11 month difference during same year
         future tense:

      AssertionError: expected 'this year' to equal 'in 11 months'
      + expected - actual

      -this year
      +in 11 months
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:222:48)
      at processImmediate (node:internal/timers:466:21)

  18) relativeTime
       11 month difference during same year
         without tense:

      AssertionError: expected '0 years' to equal '11 months'
      + expected - actual

      -0 years
      +11 months
      
      at Context.eval (webpack-internal:///./test/common/datetime/relative_time.ts:225:48)
      at processImmediate (node:internal/timers:466:21)
```
</details>

File: src/common/util/select-unit.ts [hunk 1]
```diff
@@ -49,29 +53,56 @@ export function selectUnit(
...
 
-  const days = secs / SECS_PER_DAY;
+  const fromDate = new Date(from);
+  const toDate = new Date(to);
+
+  // Set time component to zero, which allows us to compare only the days
+  fromDate.setHours(0, 0, 0, 0);
+  toDate.setHours(0, 0, 0, 0);
+
+  const days = (+fromDate - +toDate) / MS_PER_SECOND / SECS_PER_DAY;
```
Comment (bramkragten) [inline src/common/util/select-unit.ts:63]: Please use `date-fns` `differenceInDays`

File: src/common/util/select-unit.ts [hunk 2]
```diff
@@ -49,29 +53,56 @@ export function selectUnit(
...
       unit: "day",
     };
   }
 
-  const weeks = secs / SECS_PER_WEEK;
+  const firstWeekday = firstWeekdayIndex(locale);
+  const fromWeek = getFirstDayOfTheWeek(fromDate, firstWeekday);
+  const toWeek = getFirstDayOfTheWeek(toDate, firstWeekday);
+
+  const weeks = (+fromWeek - +toWeek) / MS_PER_SECOND / SECS_PER_WEEK;
```
Comment (bramkragten) [inline src/common/util/select-unit.ts:81]: https://date-fns.org/v2.29.3/docs/differenceInWeeks

File: src/common/util/select-unit.ts (hunk 1 above)
Comment (Nezz) [reply src/common/util/select-unit.ts:63]: Done. Please note that the first two lines are still needed since `differenceInDays` counts full days.

File: src/common/util/select-unit.ts (hunk 2 above)
Comment (Nezz) [reply src/common/util/select-unit.ts:81]: Done, same note as above.

File: src/common/util/select-unit.ts [hunk 3]
```diff
@@ -82,6 +112,20 @@ export function selectUnit(
   };
 }
 
+function getFirstDayOfTheWeek(date: Date, firstWeekday: number) {
```
Comment (bramkragten) [inline src/common/util/select-unit.ts:115]: https://date-fns.org/v2.29.3/docs/startOfWeek

`startOfWeek(date, { weekStartsOn: firstWeekday })`

Comment (Nezz) [reply src/common/util/select-unit.ts]: Nice find, switched to that :+1:

**Review by bramkragten — APPROVED** [review]
