### PR TITLE
Fix for Sidebar view rendering issue

### LINKED ISSUE #11834: Sidebar view loading incorrectly.
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Sidebars views load correctly on initial view.  When browser is refreshed all cards stack in the main view and the sidebar is empty.  A reload of lovelace corrects the issue until the browser is refreshed again.

Confirmed on Chrome, Edge on Windows and Fire Tablet using Fully Kiosk.

### Describe the behavior you expected

Cards loading in correct area of sidebar view after browser refresh.

### Steps to reproduce the issue

1. Load a sidebar view.
2. Refresh browser for incorrect render.
3. Reload lovelace for correct render.

### What version of Home Assistant Core has the issue?

2022.3.0b1

### What was the last working version of Home Assistant Core?

2022.2.9

### In which browser are you experiencing the issue with?

Chrome Version 98.0.4758.102 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Windows 10.0.19043

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

```yaml
title: 'Test'
icon: mdi:ab-testing
path: test
type: sidebar
cards:
  - type: entities
    entities:
      - sensor.outdoor_temperature
    view_layout:
      position: sidebar

  - type: entities
    entities:
      - sensor.outdoor_temperature
```

### Javascript errors shown in your browser console/inspector

```txt
None.
```

### Additional information

sidebar good
Correct Render

sidebar error
Incorrect Render

### PR DESCRIPTION
**Pull request by zsarnett**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #11834
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/views/hui-sidebar-view.ts [hunk 1]
```diff
@@ -69,7 +69,10 @@ export class SideBarView extends LitElement implements LovelaceViewElement {
       this._createCards();
     }
 
-    if (!changedProperties.has("lovelace")) {
+    if (
+      !changedProperties.has("lovelace") &&
+      !changedProperties.has("_config")
```
Comment (balloob) [inline src/panels/lovelace/views/hui-sidebar-view.ts:74]: This is the wrong check. Now you won't do anything unless _both_ Lovelace and config update.

**Review by balloob — APPROVED** [review]
