### PR TITLE
Catch translation errors

### LINKED ISSUE #1917: Showing detailed information in "Configured" section of Configuration/Integrations does not work when profile language set to Dutch
**Home Assistant release with the issue:**
0.81.1

**Last working Home Assistant release (if known):**
Don't know. First time I noticed the Configured section in Integrations that has the issue.

**Browser and Operating System:**
Chrome 69 on Windows
Home Assistant on Raspberry Pi 3

**Description of problem:**

Selecting items in the "Configured" section under "Configuration >> Integrations" does not work when the language in my profile is set to Dutch (Nederlands). The window remains empty, just a small popup with the text "system_log/write" appears for a short while in the bottom left corner.

It works fine when I have the language in my profile set to English.

I tried with all integrations I have and they all behave the same ( Philips Hue, Google Cast and Sonos)

**Javascript errors shown in the web inspector (if applicable):**
```
app-c039924c.js:2090 Uncaught Error: The intl string context variable 'fabrikant' was not provided to the string 'door {fabrikant}'
    at MessageFormat.format (app-c039924c.js:2090)
    at HTMLElement.args (app-c039924c.js:2090)
    at runMethodEffect (app-c039924c.js:1067)
    at Function._evaluateBinding (app-c039924c.js:1067)
    at Object.runBindingEffect [as fn] (app-c039924c.js:1067)
    at runEffectsForProperty (app-c039924c.js:1067)
    at runEffects (app-c039924c.js:1067)
    at HTMLElement._propagatePropertyChanges (app-c039924c.js:1067)
    at HTMLElement._propertiesChanged (app-c039924c.js:1067)
    at HTMLElement._flushProperties (app-c039924c.js:1438)
```

**Additional information:**
Same error as in the javascript console show in the Home Assistant log.

Note: the text "fabrikant" mentioned in the error is Dutch for "manufacturer"

### PR DESCRIPTION
**Pull request by bramkragten**
No longer fails the entire page when a placeholder is translated, or translation fails.

Fixes: https://github.com/home-assistant/home-assistant-polymer/issues/1917

### CODE REVIEW

File: src/mixins/localize-base-mixin.ts [hunk 1]
```diff
@@ -88,7 +88,11 @@ export const localizeBaseMixin = (superClass) =>
           argObject[args[i]] = args[i + 1];
         }
 
-        return translatedMessage.format(argObject);
+        try {
+          return translatedMessage.format(argObject);
+        } catch (err) {
+          return "Translation " + err;
```
Comment (balloob) [inline src/mixins/localize-base-mixin.ts]: What kind of errors would this generate ? And how would that look in the UI?

Comment (bramkragten) [reply src/mixins/localize-base-mixin.ts]: image

Comment (bramkragten) [reply src/mixins/localize-base-mixin.ts]: https://github.com/yahoo/intl-messageformat/blob/0cecaff663d2d73bf6602b71fab3b5e01d0ca16f/src/core.js#L49

Comment (bramkragten) [reply src/mixins/localize-base-mixin.ts]: image

Comment (bramkragten) [reply src/mixins/localize-base-mixin.ts]: It ain't pretty, but better than not showing anything at all, and it is an error after all... (we might make it red)

Comment (balloob) [reply src/mixins/localize-base-mixin.ts]: We can't make it red as we only can return strings.

I guess it's fine.

Comment (balloob) [reply src/mixins/localize-base-mixin.ts]: Also someone stop that Dutch translator …
