### PR TITLE
Use display precision for number format none

### LINKED ISSUE #15667: The new precision feature does not work at all when Number Format for the user is set to None. Both UI and rounding is broken
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The new precision feature is great  - except it does not work.
But the UI has a small problem
If the value of a sensor happen to be a round number - the UI is not very user friendly in showing the choices in the pull down

See pictures below. Price is close to 2 and rounded off the first 2 decimals are zeros

And EDIT

The feature does not seem to work at all. Nothing happens no matter what value my sensors have

EDIT EDIT

The trigger is that the user has Number Format set to None which is a valid value and one I like to use. See discussion below.
As temporary work around people can set one of the other number formats

### Describe the behavior you expected

The UI should show the zeros after the decimal

Like 
2
2.0
2.00

and not
2
2
2

### Steps to reproduce the issue

Have a sensor with a value that is with zeros like 2.000 or 1.99998
This will show
2
2
2
2
2
1.99998

Should be
2
2.0
2.00
2.000
2.0000
1.99998

Here is an actual example

image

I even had a sensor where the choices were
2
2
2
2
2
2

### What version of Home Assistant Core has the issue?

core-2023.3.0

### What was the last working version of Home Assistant Core?

new feature

### In which browser are you experiencing the issue with?

Google Chrome

### Which operating system are you using to run this browser?

Windows

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Use display precision for number format none.
I also added a fix for entity not updated when display precision changed.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #15667
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — DISMISSED** [review]

File: src/common/number/format_number.ts [hunk 1]
```diff
@@ -77,6 +77,24 @@ export const formatNumber = (
       ).format(Number(num));
     }
   }
+
+  if (
+    !Number.isNaN(Number(num)) &&
+    num !== "" &&
+    localeOptions?.number_format === NumberFormat.none &&
+    Intl
```
Comment (bramkragten) [inline src/common/number/format_number.ts:85]:
```suggestion
    Intl && (options?.maximumFractionDigits || options?.minimumFractionDigits)
```
Should we only do this when there is a precision specified?

**Review by bramkragten — APPROVED** [review]
