### PR TITLE
💄 align light card regardless of brightness support

### LINKED ISSUE #4552: Light card in horizontal stack doesnt line up if brightness support difference
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.104.0

**Last working Home Assistant release (if known):**
None

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
Chrome + Windows 10

**Description of problem:**
If two light cards are added to a horizontal stack, and one support brightness and the other doesnt, then the icons and text don't align.

Screenshot_20200121-112153

**Expected behaviour:**
Icons and text align for all lights in a horizontal stack, regardless of supported features.

**Relevant config:**
```
  - cards:
      - entity: light.kitchen_lights
        type: light
      - entity: light.kitchen_lamp
        type: light
    type: horizontal-stack
```

**Steps to reproduce this problem:**
1. Create 2 light entities, one that supports brightness and one that doesn't.
2. Add both entities into a horizontal stack
3. Observe misalignment of icon and text.

### PR DESCRIPTION
**Pull request by iantrich**
fixes https://github.com/home-assistant/home-assistant-polymer/issues/4552

### CODE REVIEW

File: src/panels/lovelace/cards/hui-light-card.ts [hunk 1]
```diff
@@ -100,19 +100,20 @@ export class HuiLightCard extends LitElement implements LovelaceCard {
...
+              style=${styleMap({
+                visibility: supportsFeature(stateObj, SUPPORT_BRIGHTNESS)
+                  ? "visible"
+                  : "hidden",
+              })}
+            ></round-slider>
             <paper-icon-button
               class="light-button ${classMap({
-                "slider-center": supportsFeature(stateObj, SUPPORT_BRIGHTNESS),
+                "slider-center": true,
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-light-card.ts]: Move it out of the `classMap` if you want it to always be present

Comment (balloob) [reply src/panels/lovelace/cards/hui-light-card.ts]: Or maybe can even merge the `slider-center` CSS properties into `light-button` class?
