### PR TITLE
Dynamic total energy for pie chart

### LINKED ISSUE #27856: new circle diagram total is incorrect when filtering
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### The problem

Love the new circle diagram. but the total in the middle is not changed depending on the filtered values.

Example: this picture shows the total of all power usage.
Image

But if i remove the untracked usage from the circle the total stays the same.
Image

### Describe the behavior you expected

would love to maybe see a second line show up with total from selected
or just the total changing to the devices selected total

### Steps to reproduce the issue

1.open energy dashboard
2.look at total
3.filter a device out
4.total is still the same

### What version of Home Assistant Core has the issue?

core-2025.11

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Don't include hidden entities in the total.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #27856
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/energy/hui-energy-devices-graph-card.ts [hunk 1]
```diff
@@ -442,21 +442,26 @@ export class HuiEnergyDevicesGraphCard
           }
         }
       }
+      const totalChart = chartData.reduce(
+        (acc: number, d: any) =>
+          this._hiddenStats.includes(d.id) ? acc : acc + d.value[0],
```
Comment (wendevlin) [inline src/panels/lovelace/cards/energy/hui-energy-devices-graph-card.ts]: When I look at the chartData type, I think we should integrate some checks here to prevent erros.

`NonNullable<(BarDataItemOption | OptionDataValue | OptionDataValue[])[] | (OptionDataValueNumeric | OptionDataValueNumeric[] | PieDataItemOption)[] | undefined`

Or you are sure it's just always `PieDataItemOption`, then please set it as that.

**Review by wendevlin — CHANGES_REQUESTED** [review]

**Review by wendevlin — APPROVED** [review]
