### PR TITLE
Fix oscillating handler in more info fan card (#18305)

### LINKED ISSUE #18305: `fan.oscillate` will be called when open the more-info-fan page
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

`fan.oscillate` will be called when open the more-info-fan page

### Describe the behavior you expected

Don't call the `fan.oscillate` service

### Steps to reproduce the issue

1. click any fan entity to open the more-info page
2. service `fan.oscillate` will be called

### What version of Home Assistant Core has the issue?

core-2023.10.3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Any

### Which operating system are you using to run this browser?

Any

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by caibinqing**
## Proposed change

Check `oldVal` before call `fan.oscillate` service in `_handleOscillating`

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #18305
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/more-info/controls/more-info-fan.ts [hunk 1]
```diff
@@ -87,6 +87,9 @@ class MoreInfoFan extends LitElement {
 
   _handleOscillating(ev) {
     const newVal = ev.target.value === "true";
+    const oldVal = this.stateObj?.attributes.oscillating;
+
+    if (!newVal || oldVal === newVal) return;
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-fan.ts:92]: This means oscillation can never be turned off?

Comment (Necroneco) [reply src/dialogs/more-info/controls/more-info-fan.ts:92]: oh sorry, I made a mistake, I just copy the code from _handlePresetMode.

**Review by bramkragten — APPROVED** [review]
