### PR TITLE
Fix downloads on mobile

### LINKED ISSUE #9374: Snapshots can't be downloaded in iOS
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Snapshots cannot be downloaded in iOS (app or browsers). Tapping the download link results in nothing happening. Snapshot uploads appear to be available 

### Describe the behavior you expected

File download prompt to appear

### Steps to reproduce the issue

1. Open instance in any iOS browser
2. Navigate to a snapshot in supervisor
3. Attempt to download

### What version of Home Assistant Core has the issue?

core-2021.6.2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

iOS Safari

### Which operating system are you using to run this browser?

iOS 14.6

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ludeeus**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9374
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/util/filedownload.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
+const isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
```
Comment (bramkragten) [inline src/util/filedownload.ts:1]: We already have this check in `ha-gauge` let's move it to it's own file

File: src/util/filedownload.ts [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+
+  element.shadowRoot!.appendChild(a);
+
+  setTimeout(
+    () => {
+      a.click();
+    },
+    // Directy calling a.click() is not working in iOS, adding a delay works around that issue.
+    // https://github.com/home-assistant/frontend/issues/9374
+    isSafari ? 500 : 0
```
Comment (bramkragten) [inline src/util/filedownload.ts:21]: Are you sure other browsers still work now? I think a lot of browsers only allow the download when it was initiated by a user action, and with the timeout in between the browser will probably no longer link it to the user action.

File: src/util/filedownload.ts [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+  );
+  element.shadowRoot!.removeChild(a);
```
Comment (bramkragten) [inline src/util/filedownload.ts:23]: We now remove it before it is clicked?

File: src/util/filedownload.ts (hunk 2 above)
Comment (ludeeus) [reply src/util/filedownload.ts:21]: Tested chrome and Firefox, which browsers don't like it?

Comment (bramkragten) [reply src/util/filedownload.ts:21]: Those ^, I think the popup blocker would block them...

Comment (ludeeus) [reply src/util/filedownload.ts:21]: K... I'll move it _move it_

File: src/panels/config/integrations/integration-panels/zwave_js/zwave_js-config-dashboard.ts [hunk 4]
```diff
@@ -24,6 +24,7 @@ import {
 import "../../../../../layouts/hass-tabs-subpage";
 import { haStyle } from "../../../../../resources/styles";
 import type { HomeAssistant, Route } from "../../../../../types";
+import { fileDownload } from "../../../../../util/filedownload";
```
Comment (bramkragten) [inline src/panels/config/integrations/integration-panels/zwave_js/zwave_js-config-dashboard.ts:27]:
```suggestion
import { fileDownload } from "../../../../../util/file-download";
```

File: src/util/filedownload.ts (hunk 2 above)
Comment (bramkragten) [reply src/util/filedownload.ts:21]: Let's just only use the timeout on safari to be save?

Comment (ludeeus) [reply src/util/filedownload.ts:21]: yeah, that's what I ment

File: src/util/file_download.ts [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+  const a = document.createElement("a");
+  a.target = "_blank";
+  a.href = href;
+  a.download = filename;
+
+  element.shadowRoot!.appendChild(a);
+
+  a.addEventListener("click", () => {
+    element.shadowRoot!.removeChild(a);
+  });
```
Comment (bramkragten) [inline src/util/file_download.ts:18]: Because of this event listener `element` and `a` can never be garbage collected, meaning we have a memory leak. We should remove the event listener.

File: src/util/file_download.ts [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+
+  if (isSafari || isAndroid) {
+    // Directy calling a.click() is not working in mobile, fireing a MouseEvent is used as a workaround.
+    // https://github.com/home-assistant/frontend/issues/9374
+    a.dispatchEvent(new MouseEvent("click"));
```
Comment (bramkragten) [inline src/util/file_download.ts:23]: Weird... `click()` should do that... whatevah 🤷‍♂️

Comment (ludeeus) [reply src/util/file_download.ts:23]: ideally yes, but this feels less of a hack than the delay, and it has no delay :P

**Review by bramkragten — APPROVED** [review]

File: src/util/file_download.ts (hunk 6 above)
Comment (bramkragten) [reply src/util/file_download.ts:19]: Btw, so this doesn't work for desktop?

Comment (ludeeus) [reply src/util/file_download.ts:19]: It might, in my testing it did, but better to keep that as is to not get any surprises?

Comment (bramkragten) [reply src/util/file_download.ts:19]: I don't know, if it saves use checking useragents 🤷🏻‍♂️

Can we find some docs on why it behaves different on mobile?

Comment (ludeeus) [reply src/util/file_download.ts:19]: That would be great!
I have not found _anything_ that would suggest it should (other than the fact that it's not the same)

Comment (ludeeus) [reply src/util/file_download.ts]: Tested `a.dispatchEvent(new MouseEvent("click"))` with:
- Chrome/Firefox (desktop)
- Safari (iOS)
- Chrome/Safari (MacOS)

Should be fairly safe to switch to it.

**Review by bramkragten — APPROVED** [review]
