### PR TITLE
Template dev tools: Print the type of the response and stringify objects

### LINKED ISSUE #7438: Tuples incorrectly rendered in developer-tools/template for 0.117.0b1
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

See the screenshots for the different types of behaviours:
Screenshot 2020-10-22 at 10 32 37
Screenshot 2020-10-22 at 10 32 43
Screenshot 2020-10-22 at 10 32 52
## Environment

- Home Assistant release with the issue: 0.117.0b1
- Last working Home Assistant release (if known): 0.116
- Browser and browser version: Chrome Version 86.0.4240.80 (Official Build) (x86_64
- Operating system: MacOS 10.15.7 (19H2)

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Now that not every template result comes back as a string, we print the type of the result and stringify objects.

image

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/7438
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/developer-tools/template/developer-tools-template.ts [hunk 1]
```diff
@@ -141,16 +148,27 @@ class HaPanelDevTemplate extends LitElement {
...
+            : ""}
           <pre
-            class="rendered ${classMap({ error: Boolean(this._error) })}"
-          ><!-- display: block -->${this._error}${this._templateResult
-            ?.result}</pre>
+            class="rendered ${classMap({
+              error: Boolean(this._error),
+              [resultType]: resultType,
+            })}"
+          ><!-- display: block -->${this._error}${type === "object"
```
Comment (balloob) [inline src/panels/developer-tools/template/developer-tools-template.ts:169]: What's with this comment ?

**Review by balloob — APPROVED** [review]

File: src/panels/developer-tools/template/developer-tools-template.ts (hunk 1 above)
Comment (bramkragten) [reply src/panels/developer-tools/template/developer-tools-template.ts:169]: It is for prettier... it fucks up the lines in the `pre`

**Review by zsarnett — APPROVED** [review]
