### PR TITLE
Change home and other zones edit dialog title to location name

### LINKED ISSUE #25686: Default zone "home" not using friendly name on UI
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have a default "home" zone rename to Dom
https://ss.codeone.pl/ss-2025-06-03-22-59-54-1748984394-2wCwa6sJ.png
https://ss.codeone.pl/ss-2025-06-03-22-59-42-1748984382-YpbuYK6n.png

I have noticed that tracking history (or any entity having locaiton attribute) is correctly recognising name "Praca" while not using "Dom" instead of home.
https://ss.codeone.pl/ss-2025-06-03-22-57-14-1748984234-bxhm69nH.png

### Describe the behavior you expected

See the name, I have provided.

### Steps to reproduce the issue

Can't really say? Probably just change defualt name "home" to something else.

### What version of Home Assistant Core has the issue?

2025.5.3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Chrome

### Which operating system are you using to run this browser?

Windows

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by timmo001**
## Proposed change

Previous home title used localized "Edit home" and zone edit title just used the location name. Sets both to `Edit <location_name>`

image

image

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #25686
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/zone/dialog-home-zone-detail.ts [hunk 1]
```diff
@@ -63,7 +64,7 @@ class DialogHomeZoneDetail extends LitElement {
         escapeKeyAction
         .heading=${createCloseHeading(
           this.hass,
-          this.hass!.localize("ui.panel.config.zone.edit_home")
+          `${this.hass!.localize("ui.common.edit")} ${this._data.name}`
```
Comment (MindFreeze) [inline src/panels/config/zone/dialog-home-zone-detail.ts]: You should pass the name as context, so the word order can be changed for other languages. Same for the other instances
```suggestion
          this.hass!.localize("ui.common.edit_item", {name: this._data.name})
```

**Review by MindFreeze — APPROVED** [review]

**Comment by MindFreeze** [comment]
I don't understand what should be fixed there but this PR is not related to that component so I doubt it
