### PR TITLE
show first visible view on default

### LINKED ISSUE #5327: First view gets shown by default when it is not visible for user
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## Expected behavior

At the first access first view is shown to everyone even the visibility is set only for some users. Users are always redirected on /lovelace/0,
If any user try to access other views changing index in the url (eg. /lovelace/1, lovelace/2 etc.), view is shown even the visibility is set to off

## Steps to reproduce

Set different visibility for different users 

## Environment

- Home Assistant release with the issue: 0.107.5
- Last working Home Assistant release (if known): never worked fine
- Browser and browser version: all browsers
- Operating system: all OS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by iantrich**
## Proposed change
Show the first view that is visible for the viewer as the default view.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #5327
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by zsarnett — APPROVED** [review]

File: src/panels/lovelace/hui-root.ts [hunk 1]
```diff
@@ -608,7 +608,18 @@ class HUIRoot extends LitElement {
...
     }
 
-    viewIndex = viewIndex === undefined ? 0 : viewIndex;
+    const isVisible = (view) =>
+      Boolean(
+        this._editMode ||
+          view.visible === undefined ||
+          (Array.isArray(view.visible) &&
+            view.visible.some((e) => e.user === this.hass!.user!.id)) ||
+          view.visible === true
```
Comment (balloob) [inline src/panels/lovelace/hui-root.ts:617]: move this check up. It's super fast and so we should do it before iterating over an array

File: src/panels/lovelace/hui-root.ts [hunk 2]
```diff
@@ -608,7 +608,18 @@ class HUIRoot extends LitElement {
...
+      );
+    viewIndex =
+      viewIndex === undefined || viewIndex === 0
```
Comment (balloob) [inline src/panels/lovelace/hui-root.ts:620]: Why would we try to look it up if `viewIndex` is -? The old check would only guard against undefined. In what scenario would we link to `0` ? And if so, shouldn't that place be updated to not redirect to 0?

Comment (iantrich) [reply src/panels/lovelace/hui-root.ts:620]: good point, I'll track that down

File: src/panels/lovelace/hui-root.ts [hunk 3]
```diff
@@ -412,6 +412,8 @@ class HUIRoot extends LitElement {
         newSelectView = 0;
       } else if (viewPath === "hass-unused-entities") {
         newSelectView = "hass-unused-entities";
+      } else if (viewPath === "default_view") {
+        newSelectView = undefined;
```
Comment (bramkragten) [inline src/panels/lovelace/hui-root.ts:416]: Why would we do this? Wouldn't this prevent navigating back to the view with path `default_view`?

Comment (bramkragten) [reply src/panels/lovelace/hui-root.ts:416]: The statement underneath this would already cover this right? And it is no certainty that the `default_view` is also the first view.

Comment (iantrich) [reply src/panels/lovelace/hui-root.ts:416]: Yeah, I think you're right. I think checking if viewIndex was set to 0 or undefined at line 621 was more clear in its intention as I first proposed. What do you think?

Comment (bramkragten) [reply src/panels/lovelace/hui-root.ts:416]: I would add your new logic at line 411, that's where we are choosing a view when no view is specified.

**Review by bramkragten — CHANGES_REQUESTED** [review]
Move the logic of what view to initial show to line 411

File: src/panels/lovelace/hui-root.ts [hunk 4]
```diff
@@ -405,11 +405,25 @@ class HUIRoot extends LitElement {
...
+            viewIndex.visible.some((e) => e.user === this.hass!.user!.id))
+      );
+
     if (changedProperties.has("route")) {
       const views = this.config.views;
-      if (!viewPath && views.length) {
-        navigate(this, `${this.route!.prefix}/${views[0].path || 0}`, true);
-        newSelectView = 0;
+
+      if ((!viewPath && views.length) || viewPath === "default_view") {
```
Comment (bramkragten) [inline src/panels/lovelace/hui-root.ts:420]: Why do we need to check for `default_view`?

File: src/panels/lovelace/hui-root.ts [hunk 5]
```diff
@@ -405,11 +405,25 @@ class HUIRoot extends LitElement {
 
     const viewPath = this.route!.path.split("/")[1];
 
+    const isVisible = (viewIndex) =>
```
Comment (bramkragten) [inline src/panels/lovelace/hui-root.ts:408]:
```suggestion
    const isVisible = (view) =>
```

File: src/panels/lovelace/hui-root.ts [hunk 6]
```diff
@@ -449,8 +463,14 @@ class HUIRoot extends LitElement {
...
-          navigate(this, `${this.route?.prefix}/${views[0]?.path || 0}`);
-          newSelectView = 0;
+          newSelectView = views.findIndex(isVisible);
+          navigate(
+            this,
+            `${this.route!.prefix}/${
+              views[newSelectView].path || newSelectView
+            }`,
+            true
+          );
```
Comment (bramkragten) [inline src/panels/lovelace/hui-root.ts:473]: Can we extract this in a function so we don't have duplicate code?

File: src/panels/lovelace/hui-root.ts (hunk 5 above)
Comment (anyuta1166) [reply src/panels/lovelace/hui-root.ts:408]: After this suggested change the patch doesn't work. Without it works fine.

**Comment by anyuta1166** [comment]
Just tested this patch, works fine! Everything as expected. I was waiting for it so long time, because I need to show different sets of views for different users (kids, parents etc..).

File: src/panels/lovelace/hui-root.ts (hunk 5 above)
Comment (bramkragten) [reply src/panels/lovelace/hui-root.ts:408]: You would need to rename the var name in the function too

**Review by bramkragten — APPROVED** [review]
