### PR TITLE
Properly wrap integration title / device names

### LINKED ISSUE #5806: Integrations page name overflows on long names
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Screenshot_2020-05-08 Einstellungen - Home Assistant
The name of the integration overflows if the text is too long without spaces.

## Expected behavior

Text breaks or has an ellipsis.

## Steps to reproduce

1. Go to integrations page
2. Add ZHA integration and add device by path

alternatively:
1. Go to integrations page
2. Open inspector and inspect any .card-content and edit the \<h2> content to `/dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DM01DRWR-if00-port0`

## Environment

- Home Assistant release with the issue: 0.109.5
- Last working Home Assistant release (if known):
- Browser and browser version: Chromium 81, Firefox 75
- Operating system: Arch Linux

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Ensure the title `<h3>` in an integration card gets word-wrapped so that the whole value is visible. Since I think we are usually talking about technical values that are too long (compared to short info such as IP addresses or Spotify account name for other integrations) I thought using `break-word`is fine here.

Using the word-wrap of course makes the other cards next to it in the same row grow as well, but I thought it might make sense to see the full value in this use-case.

image

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/5806
- This PR is related to issue: https://github.com/home-assistant/frontend/issues/6989
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/integrations/ha-integration-card.ts [hunk 1]
```diff
@@ -510,6 +509,9 @@ export class HaIntegrationCard extends LitElement {
           margin-top: 0;
           min-height: 24px;
         }
+        h3 {
+          word-wrap: break-word;
```
Comment (zsarnett) [inline src/panels/config/integrations/ha-integration-card.ts:513]: Can we cap this at like 2-3 lines?

Comment (zsarnett) [reply src/panels/config/integrations/ha-integration-card.ts:513]: `line-clamp`

Comment (zsarnett) [reply src/panels/config/integrations/ha-integration-card.ts:513]: https://caniuse.com/css-line-clamp

Is good enough to use. We use it in the media browser as well.
