### PR TITLE
Fix various issues in time/duration input

### LINKED ISSUE #11861: Cannot enter 2 digits for hour or minute in input_datetime
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In an input_date time which only has the hour, you cannot enter 2 digits to change the hour or the minutes. For example, try entering 12:30

On computer, we can do it if we go very fast
On a cell phone it is impossible!

image

### Describe the behavior you expected

Be able to enter hours and minutes with 2 digits

### Steps to reproduce the issue

In Lovelace put an input_datetime which only has the time
Try changing the time to 12:30

### What version of Home Assistant Core has the issue?

core-2022.3.0b3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome Version 98.0.4758.102

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

- Found and fixed the root cause of #11861 (and many duplicates) by removing the calls to `blur()`.  This also affected date inputs.
- Fixed lots of lit and typing issues for instances of `ha-time-input`, `ha-duration-input`, and their base elements.
- Fix what I think is a bug in a recent change to the wait for trigger action (see my review comments).
- Also suggest we change input event to change event (see review comment)

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #11861 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

### CODE REVIEW

File: src/panels/config/automation/action/types/ha-automation-action-wait_for_trigger.ts [hunk 1]
```diff
@@ -43,12 +43,12 @@ export class HaWaitForTriggerAction
...
       >
         <ha-switch
-          .checked=${continue_on_timeout ?? true}
+          .checked=${this.action.continue_on_timeout ?? true}
           @change=${this._continueChanged}
         ></ha-switch>
       </ha-formfield>
       <ha-automation-trigger
-        .triggers=${wait_for_trigger}
+        .triggers=${ensureArray(this.action.wait_for_trigger)}
```
Comment (steverep) [inline src/panels/config/automation/action/types/ha-automation-action-wait_for_trigger.ts:51]: @frenck please review this adjustment to #13426 which might be a bug?  The type you created accepts `Trigger | Trigger[]`, but the automation component needs an array.

File: src/components/ha-base-time-input.ts [hunk 2]
```diff
@@ -140,11 +136,11 @@ export class HaBaseTimeInput extends LitElement {
                 id="day"
                 type="number"
                 inputmode="numeric"
-                .value=${this.days}
+                .value=${this.days.toFixed()}
                 .label=${this.dayLabel}
                 name="days"
                 @input=${this._valueChanged}
```
Comment (steverep) [inline src/components/ha-base-time-input.ts:142]: Does this really need to be on the `input` event?  Seems kind of superfluous to fire a change to the backend every time a digit is added or deleted.  I would suggest changing to the `change` event.  Any objections?

Comment (bramkragten) [reply src/components/ha-base-time-input.ts:142]: It could lead to timing issues to change it, it would need some testing (esp. in dialogs and stuff)

**Review by bramkragten — APPROVED** [review]
