### PR TITLE
Fix gauge on ios 15.2

### LINKED ISSUE #10766: The gauge card doesn't render correctly on Safari 15.1 on macOS / iOS
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

In Safari or Safari web-views (e.g. the Home Assistant iOS/macOS companion apps) the `gauge` card doesn't correctly render its dial.

Screenshot 2021-12-02 at 15 00 01

This seems to be due to the way the rotation transformation is applied, via the `transform` SVG attribute [0]:

1. https://github.com/home-assistant/frontend/blob/2a5fc5181e4d1c39588499ac62c4a4fd818508f3/src/components/ha-gauge.ts#L116
2. https://github.com/home-assistant/frontend/blob/2a5fc5181e4d1c39588499ac62c4a4fd818508f3/src/components/ha-gauge.ts#L129

In my test on macOS Safari it seems that the rotation point is not needed anymore (i.e. the transform could be written like: `transform="rotate(<angle>)"`). Furthermore, Safari supports CSS transform rotate, so this could be treated the same like for other browsers.

[0] - https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform

### Describe the behavior you expected

The gauge cards should render correctly, like in all the other browsers (e.g. Firefox, Chrome).

### Steps to reproduce the issue

Have a `gauge` card configured like:
```yaml
- type: gauge
   entity: sensor.temperature
   min: 0
   max: 100
   severity:
     green: 20
     yellow: 22
     red: 25
   name: ' '
```

### What version of Home Assistant Core has the issue?

core-2021.11.5

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Safari 15.1

### Which operating system are you using to run this browser?

macOS 12.0, macOS 12.1, iOS 15.1, iOS 15.2

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

The card works correctly on iOS 14.8.1.

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes https://github.com/home-assistant/frontend/issues/10766

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by ludeeus — DISMISSED** [review]

**Comment by AmoebeLabs** [comment]
Is this a specific fix for iOS 15.x, ie the Gauge still works on iOS 14 devices?

**Review by spacegaier — DISMISSED** [review]

**Review by spacegaier — COMMENTED** [review]
Good point from the comment above: Will this introduce a regression for older Apple devices?

**Comment by bramkragten** [comment]
> Good point from the comment above: Will this introduce a regression for older Apple devices?

it does... I HATE Safari.

**Comment by spacegaier** [comment]
So probably the  `isSafari` helper will need a variant to check for a certain WebKit version and only then apply the change from this PR?

**Comment by bramkragten** [comment]
Yeah... it still needs the workaround we use now for safari, but with slightly other behavior...

File: src/components/ha-gauge.ts [hunk 1]
```diff
@@ -8,6 +8,10 @@ import { FrontendLocaleData } from "../data/translation";
 import { getValueInPercentage, normalize } from "../util/calculate";
 import { isSafari } from "../util/is_safari";
 
+// Safari version 15.2 and up behaves differently than other Safari versions.
```
Comment (ludeeus) [inline src/components/ha-gauge.ts:11]: 😠

**Review by ludeeus — APPROVED** [review]

**Review by spacegaier — APPROVED** [review]

File: src/components/ha-gauge.ts (hunk 1 above)
Comment (thomasloven) [reply src/components/ha-gauge.ts:11]: We don't even know this. Maybe 15.2.1 works again :shrug:

**Review by thomasloven — APPROVED** [review]
Tested and works as expected in iOS 15.2 and 15.1.

File: src/components/ha-gauge.ts (hunk 1 above)
Comment (AmoebeLabs) [reply src/components/ha-gauge.ts:11]: It might depend on the SVG structure / hierarchy, @thomasloven . My custom SVG based cards didn’t need any change from iOS 14 to iOS 15. No idea why, but they still work 😄

**Comment by spacegaier** [comment]
It was reported that issue also exists in 15.3.

https://github.com/home-assistant/frontend/issues/10910#issuecomment-1001168233

**Comment by thomasloven** [comment]
This fix should apply to any version above 15.1.

**Comment by bcutter** [comment]
Updated to HA 2021.12.6. Reset frontend cache of iOS device (HA Companion app). Still looking strange.

image

Wrong expectations when I read about this fix in the release notes or another issue?

**Comment by raducotescu** [comment]
Same here. The fix works correctly on Safari on both platforms, but not in the companion apps. I've also reset the frontend cache. Any ideas?

**Comment by raducotescu** [comment]
I think I found the problem: the companion app on macOS reports this user agent:

```2021-12-28 15:23:43.821 [Info] [main] [Environment.swift:71] init() > WebSocket: connecting using HAConnectionInfo(url: <redacted>.nabu.casa, userAgent: Optional("Home Assistant/2021.12 (io.robbie.HomeAssistant; build:2021.322; macOS 12.1.0)"), engine: nil)```

The fix applied in the PR works only if the user-agent includes the word `safari` (case-insensitive) and the reported version is 15.x (where x is not 0 or 1). TBH, the fix and the way the transforms are handled for the various browsers (but especially for Safari) are brittle. What happens when Safari will be out with version 16? :)

@bramkragten, should we reopen the issue or create yet another one?

I would do the fix like this:
1. for Safari I would try to extract the version number and parse it as a float number; if the version >= 15.2 then apply the transforms like for any other browser
2. for the HA Companion App parse the macOS version;
3. similar to 2. for the HA Companion App on iOS if it reports a different user agent - how can I easily check this?

**Comment by balloob** [comment]
@raducotescu note that the user agent you posted is for the websocket connection. That's not the one exposed in the webview.

**Comment by balloob** [comment]
(moving discussion to #11041)
