### PR TITLE
Fix light more info

### LINKED ISSUE #6837: More info dialog with Lights - color picker disappears in some cases (0.115.0b0)
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When on the more info Lights dialog, when you toggle off a light and then toggle it back on, the color picker does not reappear. Tested with a Hue light strip. See image below:

image

## Steps to reproduce

1. Open more info for a light entity
2. Toggle light off
3. Toggle light back on

The color picker will not re-appear, will just be an empty space where it belongs.

## Environment

- Home Assistant release with the issue: 0.115.0b0
- Last working Home Assistant release (if known): 0.114.4
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml
min_mireds: 153
max_mireds: 500
effect_list: colorloop, random
brightness: 24
hs_color: 33.767, 84.314
rgb_color: 255, 160, 39
xy_color: 0.561, 0.404
effect: none
friendly_name: Office Light Strip
supported_features: 63
```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes #6837
Fixes picking light effect

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/more-info/controls/more-info-light.ts [hunk 1]
```diff
@@ -134,7 +134,7 @@ class MoreInfoLight extends LitElement {
                         attr-for-selected="item-name"
                         >${this.stateObj.attributes.effect_list.map(
                           (effect: string) => html`
-                            <paper-item itemName=${effect}
+                            <paper-item .itemName=${effect}
```
Comment (zsarnett) [inline src/dialogs/more-info/controls/more-info-light.ts:137]: Damn why am I so bad at remembering the dot on this one property...

**Review by zsarnett — APPROVED** [review]
