### PR TITLE
cloud-tts-pref: fix for language picker

### LINKED ISSUE #27975: Text-to-speech combo boxes overlap on iOS app (and mobile Safari)
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

On the iOS app, the language and default voice to use boxes overlap.

Making the window as small as possible on FF doesn't seem to replicate the behavior, even though the window becomes a similar size:

Image

Safari/iOS App:

image

### Describe the behavior you expected

Boxes to not overlap

### Steps to reproduce the issue

Visit `config/cloud/account` on mobile Safari and/or the iOS mobile app?

### What version of Home Assistant Core has the issue?

2025.11.2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Safari 604.1

### Which operating system are you using to run this browser?

iOS 18.7.1

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ildar170975**
## Proposed change

Fixing  a overflow on a mobile client - language picker overflows on a `ha-select` element.
Proposing a new variable - `--ha-generic-picker-min-width` (in addition to the already existing variable `--ha-generic-picker-max-width`).

## Screenshots

image

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/27975
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [x] I understand the code I am submitting and can explain how it works.
- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] I have followed the [perfect PR recommendations][perfect-pr]
- [x] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

**Comment by MindFreeze** [comment]
I think if it's called `ha-generic-picker-min-width` it should be used in the generic picker. But it's also the width of a different thing 🤔

**Comment by ildar170975** [comment]
> I think if it's called ha-generic-picker-min-width it should be used in the generic picker. But it's also the width of a different thing 🤔

I see. Checked again the `ha-generic-picker`, that `--ha-generic-picker-max-width` variable is definitely for a different purpose (I would say that it has a confusing name then...)
Also, it was not very thoughtful from me to advice a new variable which would only be used in one place...
Now I am considering another approach with a property. Making a draft.

**Comment by ildar170975** [comment]
@MindFreeze 
Please consider another proposal - using a property.
Added necessary fixes.

**Review by MindFreeze — COMMENTED** [review]
Do we even need to set `min-width`? I think we can just remove it.

**Comment by ildar170975** [comment]
> Do we even need to set min-width? I think we can just remove it.

Yes! fixed.

**Comment by MindFreeze** [comment]
No, I mean don't use a `minWidth` property at all and just never set `min-width`.

**Comment by ildar170975** [comment]
> No, I mean don't use a `minWidth` property at all and just never set `min-width`.

In this case it will be like
image
i.e. there must be a way to control a width of the element.
Also, I may try to play with a width of the `ha-language-picker` itself - so the `ha-generic-picker` will just fill the available area. But this will change nothing - anyway we will need to set a smaller width for `cloud-tts-pref`.
Alternatively - we may not fix 200px in the `ha-language-picker`, instead we will add styles for every page where the `ha-language-picker` occurs (~10 places, it will be cluttering to repeat same "200px" style everywhere except `cloud-tts-pref`). What do think about this way?

**Comment by MindFreeze** [comment]
Yeah, I think it should just fill the available area and have the parent define that area. Having min/max constraints in the picker itself will always be problematic imo.

**Comment by ildar170975** [comment]
@MindFreeze 
Please check the changes, did as was suggested.

**Comment by MindFreeze** [comment]
The gap in media browser TTS is missing
image

File: src/panels/profile/ha-pick-language-row.ts [hunk 1]
```diff
@@ -52,6 +52,9 @@ export class HaPickLanguageRow extends LitElement {
     a {
       color: var(--primary-color);
     }
+    ha-language-picker {
+      min-width: 200px;
```
Comment (MindFreeze) [inline src/panels/profile/ha-pick-language-row.ts]:
```suggestion
      width: 100%;
```
This makes it the same as the other dropdowns on the page

Comment (ildar170975) [reply src/panels/profile/ha-pick-language-row.ts]: Agreed

**Review by MindFreeze — APPROVED** [review]

**Comment by ildar170975** [comment]
> gap in media browser TTS is missing

Missed this because checked the "Demo" only, not the "Home Assistant Cloud" (((
image

**Comment by ildar170975** [comment]
@MindFreeze 
can you auto-merge again?
