### PR TITLE
Always show "off" button if supported by player

### LINKED ISSUE #7068: Power off button missing in media player card
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

For my mediaplayers (Sonos, Cast, Kodi) I don't see a Power Off button. Pretty sure there used to be one.
image

## Expected behavior

Be able to power off a mediaplayer

Actually I just noticed that the power off button _does_ appear when media is playing.
So expected behaviour is that the power button is always visible.
image

## Steps to reproduce

* Take a mediaplayer entity. I see it with Sonos, Cast and Kodi standard integrations and add it to the frontend with the default mediaplayer card.
* Turn mediaplayer on with the button on the card (on button changes into play button)
* Go to the popup menu by pressing the 3 dots menu at top right of the card
* Expected to to see Power Off button

## Environment

- Home Assistant release with the issue: 0.115.1
- Last working Home Assistant release (if known): not sure
- Browser and browser version: Chrome Version 85.0.4183.102 (Official Build) (64-bit) on Windows 10
- Operating system: Home Assistant (HassIO)

## State of relevant entities

Screenshot is in the problem section
```yaml
volume_level: 0.4000000059604645
is_volume_muted: false
media_content_id: 'https://www.home-assistant.io/images/cast/splash.png'
media_position: 0
media_position_updated_at: '2020-09-19T15:26:29.442637+00:00'
app_id: CC1AD845
app_name: Default Media Receiver
entity_picture_local: null
friendly_name: Hobbykamer Mini
supported_features: 152463
```

## Problem-relevant configuration

```yaml
All configured through UI
```

## Javascript errors shown in your browser console/inspector

```txt
none
```

### LINKED ISSUE #7457: Missing power button when media_player is on
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

In previous versions of home assistant, media players always contained a power button in the lovelace entity dialog that could be used to turn the device on *and* off. That button now only shows up when the device is off, forcing me to either add a separate button, or go to the developer tools to turn off my TV.

## Expected behavior

The power button should be visible in all states except "Unavailable", allowing the user to turn their media players on and off.

## Steps to reproduce

1. Add a media_player integration that supports power controls (Android TV is a good example, assuming it supports CEC).
2. Navigate to Lovelace and find the entity for the media player
    1. Since this has to do with the entity *dialog*, you can do this straight from the "entities" configuration page
3. Turn the device on
4. Observe there is no way to turn it off now

## Environment

- Home Assistant release with the issue: 0.116.4
- Last working Home Assistant release (if known): 0.116.2 (not 100% sure on this as I ran two updates fairly close to one another)
- Browser and browser version: Chrome 86.0.4240.111, Firefox 82.0
- Operating system: Windows (client), Docker on CentOS 8 (server)

## State of relevant entities

```yaml
adb_response: null
friendly_name: Living Room TV
entity_picture: >-
  /api/media_player_proxy/media_player.living_room_tv_4?token=39bcbb5c7fb6ecb44b123e52d5ba8bd86808964aab90ef2b6e140d3b5dc16597&cache=1603407881.393676
supported_features: 23997
```
### Anything other than `off` or `unavailable`
image

### `off`
image

## Problem-relevant configuration

```yaml
media_player:
  - platform: androidtv
    name: Living Room TV
    host: 10.0.0.142
```

## Javascript errors shown in your browser console/inspector

image

## Additional information

### LINKED ISSUE #7550: Media control card does not display artist information for images
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

When the media being displayed by the media control card is MEDIA_TYPE_IMAGE, the card does not display the artist - even if that information is available to the media player. Conversely, if a fake MEDIA_TYPE_MUSIC is reported, the card will display the artist information.

This matches the dev docs which state for media_player:
_property media_artist
Artist of current playing media, music track only._

But this limitation seems to assume that only music tracks can have artists, while for images this information can be just as relevant. For example, the name of the person who took a particular photograph (which could be found in EXIF information of a user's displayed photo), but also for artists that made visual art (eg images of paintings, fine art photography, modern computer graphic art, or any other form). As an example, see the below screenshots of a media control card of my digital art frame integration when I report media_content_type as MEDIA_TYPE_IMAGE:

Screenshot 2020-10-30 at 13 32 07

And compare to the following where I report the content type as MEDIA_TYPE_MUSIC:

Screenshot 2020-10-30 at 13 30 12

I believe this second version is also how the media control card should look when MEDIA_TYPE_IMAGE is used.

## Expected behavior

If artist information for the currently played media is available to the media control card, it should display it no matter what media_content_type is being reported.

But if this causes unexpected behavior for other media content types I am not currently aware of, specifically the MEDIA_TYPE_IMAGE content type should show artist information, resulting in the following view of the media control card:

Screenshot 2020-10-30 at 13 30 12

## Steps to reproduce

1. Install a media player entity that supports images.
2. Add this media player as a media control card to Lovelace.
3. Play an image on this media player.
4. No artist information will be visible in the media control card, similar to:

Screenshot 2020-10-30 at 13 32 07

## Environment

- Home Assistant release with the issue: 0.117
- Last working Home Assistant release (if known): None
- Browser and browser version: All (but specifically, Chrome 86.0.4240.75)
- Operating system: All (but specifically, MacOS 10.15.7)

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

If media player is idle, the off switch is now also shown, not only when actually playing some media.

In general, aligned the behavior between hui-card and more-info by using a central function. entity-row is still somewhat separate although similar.

**Gallery screenshots:**

image

image

image

image

image

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/7068 fixes https://github.com/home-assistant/frontend/issues/7457 fixes https://github.com/home-assistant/frontend/issues/7550
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by OnFreund** [comment]
@spacegaier there are a few things missing here. Checkout:
https://github.com/home-assistant/frontend/compare/dev...OnFreund:poweroff_on_idle?expand=1

Let me know if you'd like to integrate those changes, or close this and I'll open a new PR.

**Comment by spacegaier** [comment]
Sorry, wasn't aware that you wanted to create a PR for it.

I indeed only focused on one card. I will add the other one.

In your PR I think the "off" switch would also be shown if the device is already "off".

**Comment by OnFreund** [comment]
> In your PR I think the "off" switch would also be shown if the device is already "off".

The "off" state is already handled before and returns.

File: src/dialogs/more-info/controls/more-info-media_player.ts [hunk 1]
```diff
@@ -277,24 +277,26 @@ class MoreInfoMediaPlayer extends LitElement {
...
-    }
-
     const buttons: ControlButton[] = [];
 
-    if (supportsFeature(stateObj, SUPPORT_TURN_OFF)) {
-      buttons.push({
-        icon: "hass:power",
-        action: "turn_off",
-      });
+    if (state === "on" || state === "idle") {
```
Comment (OnFreund) [inline src/dialogs/more-info/controls/more-info-media_player.ts:282]: I'm not sure this condition is needed. Shouldn't the power off button be shown when the state is `playing`, for example?

Comment (spacegaier) [reply src/dialogs/more-info/controls/more-info-media_player.ts:282]: I though about that earlier, and my initial feeling was no, to prevent an accidental turning off if the user slightly miss-clicks but was attempting to hit "pause". Hence the condition.

However, 2 minutes ago, I thought about a related scenario. Given my point above stays (no off switch while playing visible), and we then show the off switch if paused the rules would look like this:

Off: On
On: Off
Idle: Off | Play
Playing: Pause
Pause: Off | Play

That is not ideal, since you cannot quickly/easily press pause and then play again, since the position of the buttons changes. I was wondering whether it would make sense that if a player can in general turn off, that the turn off icon is always shown (to keep the button order at the beginning consistent) but disabled if media is playing.

Comment (OnFreund) [reply src/dialogs/more-info/controls/more-info-media_player.ts:282]: Generally speaking, I think that present and disabled is better, both from a discovery standpoint (if something is disabled and has a tooltip, for example, it's easier to understand why it's disabled, vs it not showing at all), and as you said, to ensure a consistent location.
However, I'm not sure we need to protect the user here - people regularly turn media players off while they're playing, and it is currently available.

Comment (spacegaier) [reply src/dialogs/more-info/controls/more-info-media_player.ts:282]: What about always showing the "off" icon and also keeping it enabled all the time even while playing, but if pressed while playing we show a confirmation dialog to the user to prevent accidental shutoffs? Or is that also still too intrusive? 

TBH I haven't used media_players much with HA yet, so I might be unnecessarily too cautious here.

Comment (OnFreund) [reply src/dialogs/more-info/controls/more-info-media_player.ts:282]: Honestly I think this is beyond the scope of this PR.
Initially, the power off button was there in any state but "off" (in which case there was an identically looking power button to turn on).
We then had a regression, where in "idle", the power off button was not there. I think that the scope should be to revert that regression. Any change in behavior to turn off, would probably make sense as a separate PR.

BTW I just realized that for the lovelace card we only took care of idle, but not other non-off states.

Comment (bramkragten) [reply src/dialogs/more-info/controls/more-info-media_player.ts:282]: I agree with @OnFreund here, let's just address the regression

**Review by zsarnett — APPROVED** [review]

**Comment by spacegaier** [comment]
@bramkragten I think this should also be part of the 0.117.0 milestone.

**Comment by bramkragten** [comment]
> @bramkragten I think this should also be part of the 0.117.0 milestone.

Why? This wasn't introduced in this (or previous) version?

**Comment by spacegaier** [comment]
> 
> 
> > @bramkragten I think this should also be part of the 0.117.0 milestone.
> 
> Why? This wasn't introduced in this (or previous) version?

Based on the raised issues I was/am under the impression that this was a regression from the previous version, hence my proposal. If I am wrong here, then of course no need for the milestone 👍 .

**Comment by bramkragten** [comment]
We have now changed the logic in all places (card, row, more info) I think only the more info showed the power button before.

I'm ok with aligning it, but we should make sure we use the correct logic.

File: src/dialogs/more-info/controls/more-info-media_player.ts [hunk 2]
```diff
@@ -277,17 +277,6 @@ class MoreInfoMediaPlayer extends LitElement {
         : undefined;
     }
 
-    if (state === "idle") {
-      return supportsFeature(stateObj, SUPPORTS_PLAY)
-        ? [
-            {
-              icon: "hass:play",
-              action: "media_play",
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-media_player.ts:285]: So instead of just a play button when idle, we now show the power, next, previous, and play button? I don't think that is what we want?

Comment (spacegaier) [reply src/dialogs/more-info/controls/more-info-media_player.ts:285]: It is now consistent across all three usages: Entity row, more-info and media card. 

And yes, if the player supports "next" and "previous" they are shown together with the "play" button, since those can also act as play buttons. E.g. on the Spotify integration, if the player is idle and you press "next", then the next song will start playing. So it made sense for me to group them. Does it also for you or would you propose to not show them in idle/on?

Comment (bramkragten) [reply src/dialogs/more-info/controls/more-info-media_player.ts:285]: Idle is not paused right?

Comment (spacegaier) [reply src/dialogs/more-info/controls/more-info-media_player.ts:285]: No, those are separate. Basically "idle" is the default for players as a service (such as Spotify) that cannot be turned off.

Comment (bramkragten) [reply src/dialogs/more-info/controls/more-info-media_player.ts:285]: Then I'm not sure what next would do. Next of what? If I'm not currently playing anything?

Comment (spacegaier) [reply src/dialogs/more-info/controls/more-info-media_player.ts:286]: If you are not playing anything, there is still a selection in Spotify from the last time you played something, so "next" is whatever Spotify has queued up as next title (e.g. next song in the playlist).
image

Comment (bramkragten) [reply src/dialogs/more-info/controls/more-info-media_player.ts:286]: Your screenshot is state `paused` I think, can you check your state? Idle doesn't show media information.

**Comment by balloob** [comment]
Please add an example to the gallery with this state and post some screenshots of how it looks.

**Comment by bramkragten** [comment]
Can you add screenshots of the added items to the gallery?

**Comment by spacegaier** [comment]
> 
> 
> Can you add screenshots of the added items to the gallery?

Yes, did not have time yet, but will follow soon.

**Comment by spacegaier** [comment]
> 
> 
> Please add an example to the gallery with this state and post some screenshots of how it looks.

@balloob Screenshots added. Please have a look.

File: src/dialogs/more-info/controls/more-info-media_player.ts (hunk 2 above)
Comment (spacegaier) [reply src/dialogs/more-info/controls/more-info-media_player.ts:286]: Just as a note: Aligned with Bram that idle will not show previous/next buttons.

**Review by bramkragten — APPROVED** [review]
