### PR TITLE
Handle history api being passed entity ids as CSV

### LINKED ISSUE #12767: History-graph broken in frontend 20220523.0
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

after updating to dev 2022.6.0.dev20220524 all history-graph cards are broken.

### Describe the behavior you expected

show history data

### Steps to reproduce the issue

1. type: history-graph
2.
3.
...

### What version of Home Assistant Core has the issue?

2022.6.0.dev20220524

### What was the last working version of Home Assistant Core?

2022.6.0.dev20220523

### In which browser are you experiencing the issue with?

any

### Which operating system are you using to run this browser?

macOS  Monterey 12.3.1

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

```yaml
- type: custom:hui-element
        card_type: history-graph
        entities:
          - entity: sensor.co2_living_statistics
            name: Co2
          - entity: sensor.temp_living_statistics
            name: Temp Living
          - entity: sensor.humid_living_statistics
            name: Vocht
          - entity: sensor.schimmel_sensor
            name: Schimmel
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

Schermafbeelding 2022-05-24 om 22 53 46

all entities do have their history logged, as can be seen by clicking on the individual entity, or, by adding them in a logbook card

Schermafbeelding 2022-05-24 om 22 57 16

or the statistics-graph card for the exact same entities:

Schermafbeelding 2022-05-24 om 22 58 21

### PR DESCRIPTION
**Pull request by bdraco**
## Proposed change

Fixes #12767

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/data/history.ts [hunk 1]
```diff
@@ -197,7 +197,7 @@ export const fetchRecent = (
 
 export const fetchRecentWS = (
   hass: HomeAssistant,
-  entityId: string,
+  entityId: string, // This may be comma seperate entities
```
Comment (bdraco) [inline src/data/history.ts:200]:
```suggestion
  entityId: string, // This may be CSV
```

**Review by zsarnett — DISMISSED** [review]

**Review by zsarnett — APPROVED** [review]
