### PR TITLE
Alarm codes

### LINKED ISSUE #2602: Alarm Panel Card (lovelace) fails for codes entered via keyboard
*@meaniegreenie commented on Jan 26, 2019, 4:53 PM UTC:*

**Home Assistant release with the issue:**

Home Assistant v0.86.2

**Last working Home Assistant release (if known):**
unknown

**Operating environment (Hass.io/Docker/Windows/etc.):**

Linux (python virtual environment 3.5.3)

**Component/platform:**

[https://www.home-assistant.io/lovelace/alarm-panel/](https://www.home-assistant.io/lovelace/alarm-panel/)

**Description of problem:**

Using the Alarm Panel Card to control Elk M1 alarm in HASS 0.86 correctly arms/disarms the alarm when code is entered using the on-screen buttons. However, the code input allows users to type in values as well. When this is done, the arm/disarm does not occur and HASS logs the following error.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**

```yaml
      - type: alarm-panel
        name: elkTest
        entity: alarm_control_panel.area001
```

**Traceback (if applicable):**

```
NOTE: I have replaced the specific base directory with the following text: "<HASS_DIR>"

2019-01-26 10:22:15 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
result = coro.send(None)
File "<HASS_DIR>/hass/env/lib/python3.5/site-packages/homeassistant/helpers/service.py", line 287, in _handle_service_platform_call
await getattr(entity, func)(**data)
File "<HASS_DIR>/hass/env/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/elkm1.py", line 185, in async_alarm_arm_home
self._element.arm(ArmLevel.ARMED_STAY.value, int(code))
ValueError: invalid literal for int() with base 10: ''

```

**Additional information:**

Since the log seems to indicate that a blank string was passed to the alarm, I suspect this component is not sending a value obtained from the text field, but dynamically creates the sent code based each click of an on-screen button.

*This issue was moved by [cgarwood](https://github.com/cgarwood) from [home-assistant/home-assistant#20475](https://github.com/home-assistant/home-assistant/issues/20475).*

### PR DESCRIPTION
**Pull request by iantrich**
Closes https://github.com/home-assistant/home-assistant-polymer/issues/2602

### CODE REVIEW

File: src/panels/lovelace/cards/hui-alarm-panel-card.ts [hunk 1]
```diff
@@ -194,11 +196,17 @@ class HuiAlarmPanelCard extends LitElement implements LovelaceCard {
   }
 
   private _handleActionClick(e: MouseEvent): void {
+    const input = this.shadowRoot!.querySelector(
+      "#alarmCode"
+    ) as PaperInputElement;
+    const code =
```
Comment (balloob) [inline src/panels/lovelace/cards/hui-alarm-panel-card.ts]: Why is this necessary? `_handlePadClick` is mutating `this._code` so should be up to date ?

Comment (iantrich) [reply src/panels/lovelace/cards/hui-alarm-panel-card.ts]: This is for keyboard input

Comment (balloob) [reply src/panels/lovelace/cards/hui-alarm-panel-card.ts]: it's a bit dangerous that we keep `this._code` and the input out of sync, but fine with this.

Comment (iantrich) [reply src/panels/lovelace/cards/hui-alarm-panel-card.ts]: Yeah, considered that but thought it would be pretty unlikely and would clear after one failed attempt 🤷‍♀️
