### PR TITLE
Card Picker: Remove Scale

### LINKED ISSUE #5196: Card picker - sensor card preview cut off
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Noticed this on both my own setup and reproduced in the [demo](https://demo.home-assistant.io/#/lovelace/0). When adding a card, the Sensor card preview has the text cut off at the top. It's only showing the top half of the sensor name in the preview. See image below, look at the Morning Commute text:

image

Card is fine when clicking through and adding to a view, it's just this preview. Think the height of the card preview in the add card picker is too small or something.

## Steps to reproduce

1. Enter Configure UI Mode
2. Add card picker
3. Look at sensor card preview

## Environment

- Home Assistant release with the issue: 0.107.0b1
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by zsarnett**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #5196
- This PR is related to issue: #5097 
- Link to documentation pull request: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/editor/card-editor/hui-card-picker.ts [hunk 1]
```diff
@@ -190,11 +190,6 @@ export class HuiCardPicker extends LitElement {
         }
 
         .preview > :first-child {
-          zoom: 0.6;
```
Comment (bramkragten) [inline src/panels/lovelace/editor/card-editor/hui-card-picker.ts]: Shouldn't we leave zoom for all the browsers that do support it?
