### PR TITLE
Restore previous codemirror tab behavior

### LINKED ISSUE #8460: Codemirror tab indentation broken
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

A tab now inserts a real tab rather than the 2 spaces we had before. This breaks saving e.g. in the YAML card editor.

**Describe the behavior you expected**

A tab should insert two spaces.

**Steps to reproduce the issue**

1. Go to any YAML card editor
2. Indent some lines with tab
3. Inspect resulting white spaces
...

**What version of Home Assistant Core has the issue?**

2021.4.0.dev0 / beta

**What was the last working version of Home Assistant Core?**

_No response_

**In which browser are you experiencing the issue with?**

_No response_

**Which operating system are you using to run this browser?**

_No response_

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```

**Javascript errors shown in your browser console/inspector**

```txt
# Paste your logs here.

```

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Restores the previous behavior of Tab = 2 spaces. However, it needs to be noted that CM6 by design does not have that as default behavior, apparently due to some accessibility concerns. For the current beta, I think we need to ignore that since otherwise YAML saving is broken, which weighs heavier.

Also CM6 includes an escape hatch: Esc + Tab leaves the editor, see: https://codemirror.net/6/examples/tab/

Perhaps we can document that somewhere?

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/8460
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-code-editor.ts [hunk 1]
```diff
@@ -1,5 +1,6 @@
 import type { StreamLanguage } from "@codemirror/stream-parser";
 import type { EditorView, KeyBinding, ViewUpdate } from "@codemirror/view";
+import { indentMore, indentLess } from "@codemirror/commands";
```
Comment (bramkragten) [inline src/components/ha-code-editor.ts:3]: Import this in the on demand files, and remove the other tab binding

File: src/resources/codemirror.ts [hunk 2]
```diff
@@ -7,8 +7,9 @@ import { yaml } from "@codemirror/legacy-modes/mode/yaml";
 export { keymap } from "@codemirror/view";
 export { CMEditorView as EditorView };
 export { EditorState, Prec, tagExtension } from "@codemirror/state";
-export { defaultKeymap, defaultTabBinding } from "@codemirror/commands";
+export { defaultKeymap } from "@codemirror/commands";
 export { lineNumbers } from "@codemirror/gutter";
+export { indentMore, indentLess } from "@codemirror/commands";
```
Comment (bramkragten) [inline src/resources/codemirror.ts:12]: Combine them with the other export from commands

Comment (spacegaier) [reply src/resources/codemirror.ts:12]: How did I miss that 🤦

**Review by bramkragten — APPROVED** [review]
