### PR TITLE
Convert state history chart to LitElement + add warning if history is disabled

### LINKED ISSUE #7960: History graph card is not rendered if "history" component is disabled
## The problem

[History graph card](https://www.home-assistant.io/lovelace/history-graph/) is not rendered if [history component](https://www.home-assistant.io/integrations/history/) is disabled.

image

## Expected behavior

Instead of rendering "Loading state history..." a message e.g. "Disabled because of missing history component" should be displayed. At least a warning message should be logged.

## Steps to reproduce

Disable history component, restart Home Assistant and check history graph card.

## Environment

- Home Assistant release with the issue: 0.118.5
- Browser and browser version: Chrome v87.0.4280.88
- Operating system: Windows 7 x64

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Converted to LitElement + show an info in history card if history component is disabled / not loaded.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/7960
- This PR is related to issue or discussion: https://github.com/home-assistant/frontend/pull/7994
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/state-history-charts.ts [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+
+@customElement("state-history-charts")
+class StateHistoryCharts extends LitElement {
+  @property({ attribute: false }) public hass!: HomeAssistant;
+
+  @property() public historyData!: HistoryResult;
+
+  @property() public names = false;
+
+  @property() public endTime;
```
Comment (iantrich) [inline src/components/state-history-charts.ts:25]: Add a type

File: src/components/state-history-charts.ts [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+    const historyDataEmpty =
+      !this.historyData ||
+      !this.historyData.timeline ||
+      !this.historyData.line ||
+      (this.historyData.timeline.length === 0 &&
+        this.historyData.line.length === 0);
+    return !this.isLoadingData && historyDataEmpty;
+  }
+
+  _computeEndTime() {
```
Comment (iantrich) [inline src/components/state-history-charts.ts:92]: Declare as private and add return type

File: src/components/state-history-charts.ts [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+            line.data.length === 1}
+            .end-time=${this._computeEndTime()}
+            .names=${this.names}
+          ></state-history-chart-line>
+        `
+      )}
+    `;
+  }
+
+  private _isHistoryEmpty() {
```
Comment (iantrich) [inline src/components/state-history-charts.ts:82]: Add return type

File: src/components/state-history-charts.ts [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+          `
+        : html``}
+      ${this.historyData.line.map(
+        (line) => html`
+          <state-history-chart-line
+            .hass=${this.hass}
+            .unit=${line.unit}
+            .data=${line.data}
+            .identifier=${line.identifier}
+            .is-single-device=${!this.noSingle &&
```
Comment (iantrich) [inline src/components/state-history-charts.ts:71]:
```suggestion
            .isSingleDevice=${!this.noSingle &&
```

File: src/components/state-history-charts.ts [hunk 5]
```diff
@@ -0,0 +1,118 @@
...
+    }
+
+    return html`
+      ${this.historyData.timeline.length
+        ? html`
+            <state-history-chart-timeline
+              .hass=${this.hass}
+              .data=${this.historyData.timeline}
+              .end-time=${this._computeEndTime()}
+              .no-single=${this.noSingle}
```
Comment (iantrich) [inline src/components/state-history-charts.ts:59]:
```suggestion
              .noSingle=${this.noSingle}
```

File: src/components/state-history-charts.ts [hunk 6]
```diff
@@ -0,0 +1,118 @@
...
+      </div>`;
+    }
+
+    return html`
+      ${this.historyData.timeline.length
+        ? html`
+            <state-history-chart-timeline
+              .hass=${this.hass}
+              .data=${this.historyData.timeline}
+              .end-time=${this._computeEndTime()}
```
Comment (iantrich) [inline src/components/state-history-charts.ts:58]:
```suggestion
              .endTime=${this._computeEndTime()}
```

File: src/components/state-history-charts.ts [hunk 7]
```diff
@@ -0,0 +1,118 @@
...
+        (line) => html`
+          <state-history-chart-line
+            .hass=${this.hass}
+            .unit=${line.unit}
+            .data=${line.data}
+            .identifier=${line.identifier}
+            .isSingleDevice=${!this.noSingle &&
+            line.data &&
+            line.data.length === 1}
+            .end-time=${this._computeEndTime()}
```
Comment (iantrich) [inline src/components/state-history-charts.ts:74]:
```suggestion
            .endTime=${this._computeEndTime()}
```

**Review by iantrich — APPROVED** [review]

File: src/components/state-history-charts.ts [hunk 8]
```diff
@@ -0,0 +1,118 @@
...
+        (line) => html`
+          <state-history-chart-line
+            .hass=${this.hass}
+            .unit=${line.unit}
+            .data=${line.data}
+            .identifier=${line.identifier}
+            .isSingleDevice=${!this.noSingle &&
+            line.data &&
+            line.data.length === 1}
+            .endTime=${this._computeEndTime()}
```
Comment (bramkragten) [inline src/components/state-history-charts.ts:74]: We should move this to a var above the `return html`, so we do it only once instead for every chart.

File: src/components/state-history-charts.ts [hunk 9]
```diff
@@ -0,0 +1,120 @@
...
+      (this.historyData.timeline.length === 0 &&
+        this.historyData.line.length === 0);
+    return !this.isLoadingData && historyDataEmpty;
+  }
+
+  private _computeEndTime(): Date {
+    // We don't really care about the value of historyData, but if it change we want to update
+    // endTime.
+    return this.upToNow ? new Date() : this.endTime || new Date();
+  }
```
Comment (bramkragten) [inline src/components/state-history-charts.ts:98]:
```suggestion
```

File: src/components/state-history-charts.ts [hunk 10]
```diff
@@ -0,0 +1,120 @@
...
+      </div>`;
+    }
+
+    if (this._isHistoryEmpty()) {
+      return html` <div class="info">
+        ${this.hass.localize("ui.components.history_charts.no_history_found")}
+      </div>`;
+    }
+
+    const computedEndTime = this._computeEndTime();
```
Comment (bramkragten) [inline src/components/state-history-charts.ts:52]:
```suggestion
    const computedEndTime = this.upToNow ? new Date() : this.endTime || new Date();
```

File: src/panels/history/ha-panel-history.ts [hunk 11]
```diff
@@ -101,7 +101,7 @@ class HaPanelHistory extends LitElement {
                   .hass=${this.hass}
                   .historyData=${this._stateHistory}
                   .endTime=${this._endDate}
-                  no-single
+                  noSingle
```
Comment (bramkragten) [inline src/panels/history/ha-panel-history.ts:104]: Better to make this none breaking and keep the attr `no-single`.

Change:
```
  @property() public noSingle = false;
```
Too:
```
  @property({type: Boolean, attribute: "no-single"}) public noSingle = false;
```

File: src/components/state-history-charts.ts [hunk 12]
```diff
@@ -0,0 +1,120 @@
...
+
+  @property() public names = false;
+
+  @property() public endTime?: Date;
+
+  @property() public upToNow = false;
+
+  @property() public noSingle = false;
+
+  @property() public isLoadingData = false;
```
Comment (bramkragten) [inline src/components/state-history-charts.ts:31]: Add `{type: Boolean}` to boolean attributes (Also line 23)

File: src/components/state-history-charts.ts [hunk 13]
```diff
@@ -0,0 +1,120 @@
...
+
+@customElement("state-history-charts")
+class StateHistoryCharts extends LitElement {
+  @property({ attribute: false }) public hass!: HomeAssistant;
+
+  @property() public historyData!: HistoryResult;
+
+  @property() public names = false;
+
+  @property() public endTime?: Date;
```
Comment (bramkragten) [inline src/components/state-history-charts.ts:25]:
```suggestion
  @property({ attribute: false }) public endTime?: Date;
```

File: src/components/state-history-charts.ts [hunk 14]
```diff
@@ -0,0 +1,120 @@
...
+import "./state-history-chart-timeline";
+import { isComponentLoaded } from "../common/config/is_component_loaded";
+import type { HomeAssistant } from "../types";
+import { HistoryResult } from "../data/history";
+
+@customElement("state-history-charts")
+class StateHistoryCharts extends LitElement {
+  @property({ attribute: false }) public hass!: HomeAssistant;
+
+  @property() public historyData!: HistoryResult;
```
Comment (bramkragten) [inline src/components/state-history-charts.ts:21]: `{ attribute: false }` probably? Or otherwise an array?

File: src/panels/history/ha-panel-history.ts (hunk 11 above)
Comment (spacegaier) [reply src/panels/history/ha-panel-history.ts:104]: The risk you see with breaking is coming from custom cards using that element? Inside this repo there are no uses anymore of "no-single".

Comment (bramkragten) [reply src/panels/history/ha-panel-history.ts:104]: yeah

Comment (bramkragten) [inline src/panels/history/ha-panel-history.ts:104]:
```suggestion
                  no-single
```

**Review by bramkragten — APPROVED** [review]
