### PR TITLE
Fix gauge when safari is zoomed

### LINKED ISSUE #6467: Gauge doesn’t show properly in Safari macOS
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Schermafdruk 2020-07-26 14 38 27

## Expected behavior

image

## Steps to reproduce

    
1. Define a gauge card in Lovelace
2. Open the Home Assistant UI in Safari (macOS)

## Environment

- Home Assistant release with the issue: 0.113.1
- Last working Home Assistant release (if known): 0.112.4
- Browser and browser version: Safari 13.1.2
- Operating system: macOS Catalina, version 10.15.6

I don't see this issue in Safari iOS. Only in Safari macOS.
I didn't test this with other browsers, because I like to use only one browser (also it worked fine in HA 0.112.4).

## State of relevant entities

N/A
```yaml

```

## Problem-relevant configuration

      - title: Elektra
        type: entities
        entities:
          - type: custom:hui-element
            card_type: horizontal-stack
            cards:
              - type: gauge
                title: Stroomverbruik
                entity: sensor.power_consumption_kwh_to_watt
                theme: gauge_card
                min: 0
                max: 4000
                severity:
                  green: 0
                  yellow: 0
                  red: 2000
                style: |
                  ha-card {
                    --ha-card-box-shadow: none;
                    margin: 2px -8px -20px -8px;
                  }
              - type: gauge
                title: Stroomopbrengst
                entity: sensor.power_production_kwh_to_watt
                theme: gauge_card
                min: 0
                max: 1800
                severity:
                  green: 0
                  yellow: 2500
                  red: 3000
                style: |
                  ha-card {
                    --ha-card-box-shadow: none;
                    margin: 2px -8px -20px -8px;
                  }
```yaml

```

## Javascript errors shown in your browser console/inspector

There are no error logs in the browser’s console.

## Additional information
N/A

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

It's kinda dirty, and it does browser detection... but what works in Safari breaks things in Firefox... Chrome doesn't care, everything works in Chrome...

Animation between values won't work anymore for Safari, only the initial animation.

Fixes https://github.com/home-assistant/frontend/issues/6467

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by zsarnett** [comment]
This is atrocious... Like why safari

**Comment by fjufju** [comment]
If bug in safari maybe create issue in their repo? This is a hack workaround @bramkragten can You do this? Thank you.

File: src/components/ha-gauge.ts [hunk 1]
```diff
@@ -27,6 +28,8 @@ const getValueInPercentage = (value: number, min: number, max: number) => {
   return (100 * newVal) / newMax;
 };
 
+const isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
```
Comment (balloob) [inline src/components/ha-gauge.ts:31]:
```suggestion
// Workaround for https://github.com/home-assistant/frontend/issues/6467
const isSafari = /^((?!chrome|android).)*safari/i.test(navigator.userAgent);
```

**Review by balloob — APPROVED** [review]
