### PR TITLE
Show error if no OZW instances are detected

### LINKED ISSUE #7088: OZW Integration Configuration - "Select an OpenZWave Instance"
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I see two problems related to the OpenZWave integration configuration, both occur when the MQTT broker is offline.

When the broker is offline:
1. And HA is online, the integration configuration shows that the ozw daemon is online and everything is OK. I can click on Add and Remove node buttons without any kind of indication that they would fail.
2. And HA is restarted, the integration configuration asks me to "Select an OpenZWave Instance" and has a blank page.

## Expected behavior

I would expect that some kind of error/warning is showing that the ozwd instance is not available, or it was unable to find any instances.

## Steps to reproduce

For scenario 1:

While HA is running:
1. Stop the MQTT broker.
2. Go to Configuration -> Integrations -> OpenZWave -> Click Configure

Observe that the status of the instance is showing whatever it was prior to the broker shutdown. Notice you can click on the service buttons, which won't do anything.

Presumably this is more of an ozw integration/HA problem since it's just rendering the data the backend provides.

For scenario 2:

1. Stop HA
2. Stop the MQTT broker.
3. Start HA.
2. Go to Configuration -> Integrations -> OpenZWave -> Click Configure

Observe that the page is basically empty. It says "Select an OpenZWave Instance" in the header, with body text "You have more than one OpenZWave instance running. Which instance would you like to manage?".

"Select an OpenZWave Instance" is usually only prompted when more than one ozwd instance is seen. When there is only one instance it will select that one automatically. In this case, it sees 0 instances and still prompts. Preferably that'd be some kind of other message indicating that no instances are seen.

## Environment

- Home Assistant release with the issue: I observed in 0.115.2 in my production setup. For testing I am using 0.116.0.dev20200921.
- Last working Home Assistant release (if known): Never, this is new to 0.115.
- Browser and browser version: N/A
- Operating system: N/A

## State of relevant entities

N/A

## Problem-relevant configuration

N/A

## Javascript errors shown in your browser console/inspector

None

## Additional information

None

### PR DESCRIPTION
**Pull request by cgarwood**
## Proposed change
Currently the OZW config panel shows a "Select an OpenZWave Instance" page with nothing to select if there are no instances detected (like if MQTT is offline). This PR updates the panel to show an error page instead. Error message suggested by @masonevans

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #7088
- This PR is related to issue: https://github.com/home-assistant/core/issues/4073
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/integrations/integration-panels/ozw/ozw-config-dashboard.ts [hunk 1]
```diff
@@ -45,11 +46,21 @@ class OZWConfigDashboard extends LitElement {
 
   @internalProperty() private _instances: OZWInstance[] = [];
```
Comment (bramkragten) [inline src/panels/config/integrations/integration-panels/ozw/ozw-config-dashboard.ts:47]:
```suggestion
  @internalProperty() private _instances?: OZWInstance[];
```

File: src/panels/config/integrations/integration-panels/ozw/ozw-config-dashboard.ts [hunk 2]
```diff
@@ -45,11 +46,21 @@ class OZWConfigDashboard extends LitElement {
...
 
+  @internalProperty() private _firstFetch = false;
```
Comment (bramkragten) [inline src/panels/config/integrations/integration-panels/ozw/ozw-config-dashboard.ts:49]:
```suggestion
```

File: src/panels/config/integrations/integration-panels/ozw/ozw-config-dashboard.ts [hunk 3]
```diff
@@ -45,11 +46,21 @@ class OZWConfigDashboard extends LitElement {
...
+
   protected firstUpdated() {
     this._fetchData();
   }
 
   protected render(): TemplateResult {
+    if (this._instances.length === 0 && this._firstFetch) {
```
Comment (bramkragten) [inline src/panels/config/integrations/integration-panels/ozw/ozw-config-dashboard.ts:56]:
```suggestion
    if (this._instances && this._instances.length === 0) {
```

File: src/panels/config/integrations/integration-panels/ozw/ozw-config-dashboard.ts [hunk 4]
```diff
@@ -136,6 +147,7 @@ class OZWConfigDashboard extends LitElement {
 
   private async _fetchData() {
     this._instances = await fetchOZWInstances(this.hass!);
+    this._firstFetch = true;
```
Comment (bramkragten) [inline src/panels/config/integrations/integration-panels/ozw/ozw-config-dashboard.ts:150]:
```suggestion
```

File: src/panels/config/integrations/integration-panels/ozw/ozw-config-dashboard.ts [hunk 5]
```diff
@@ -45,11 +46,21 @@ class OZWConfigDashboard extends LitElement {
...
 
   protected render(): TemplateResult {
+    if (this._instances.length === 0 && this._firstFetch) {
+      return html`<hass-error-screen
+        .error="${this.hass.localize(
+          "ui.panel.config.ozw.select_instance.none_found"
+        )}"
+      ></hass-error-screen>`;
+    }
+
```
Comment (bramkragten) [inline src/panels/config/integrations/integration-panels/ozw/ozw-config-dashboard.ts:63]:
```suggestion
if (!this._instances) {
   return html`LOADING SCREEN OR EMPTY`
}
```

File: src/panels/config/integrations/integration-panels/ozw/ozw-config-dashboard.ts [hunk 6]
```diff
@@ -44,16 +45,18 @@ class OZWConfigDashboard extends LitElement {
...
     this._fetchData();
   }
 
   protected render(): TemplateResult {
-    if (this._instances.length === 0 && this._firstFetch) {
+    if (!this._instances) {
+      return html`<hass-loading-screen></hass-loading-screen>`;
+    }
+
+    if (this._instances && this._instances.length === 0) {
```
Comment (bramkragten) [inline src/panels/config/integrations/integration-panels/ozw/ozw-config-dashboard.ts:59]:
```suggestion
    if (this._instances.length === 0) {
```

**Review by bramkragten — APPROVED** [review]
