### PR TITLE
Prevent cutting off of attributes in more-info light

### LINKED ISSUE #9218: Details light domain cut off
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When opening details of a light domain entity, the bottom is cut off, switch domain doesn't have this problem.
Capture

### Describe the behavior you expected

The deatils shouldn't be cut off so we can read everything.  We can copy/paste all the info so the data is all there, it's just cut off in UI.

### Steps to reproduce the issue

1. click on light entity that has info in the bottom
2. See it being cut off
3.
...

### What version of Home Assistant Core has the issue?

core-2021.5.5

### What was the last working version of Home Assistant Core?

core-2021.5.5

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```
supported_color_modes:
  - brightness
color_mode: brightness
brightness: 81
shelly_type: Shelly Dimmer 2
shelly_id: E8DB84A1C05C
ip_address: 192.168.1.13
room: Keuken
protocols:
  - CoAP-msg
over_temp: 0
current_consumption: 12 W
friendly_name: Keuken
supported_features: 1
```

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by spacegaier**
## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9218
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/more-info/controls/more-info-light.ts [hunk 1]
```diff
@@ -552,7 +552,6 @@ class MoreInfoLight extends LitElement {
 
       .content > * {
         width: 100%;
-        max-height: 84px;
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-light.ts:555]: I don't think this is the right solution, I remember it was there for a reason... Will check... We could at least remove `max-height` from `ha-attributes`

File: src/dialogs/more-info/controls/more-info-light.ts [hunk 2]
```diff
@@ -552,7 +552,6 @@ class MoreInfoLight extends LitElement {
...
         overflow: hidden;
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-light.ts:555]:
```suggestion
```

**Review by bramkragten — APPROVED** [review]
