### PR TITLE
Filter out disabled entities in the statistics dev tools

### LINKED ISSUE #10561: Developer Tools / Statistics shows issue for disabled entities
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Looking in Developer Tools / Statistics I see a long list of these issues: `There is no state available for this entity.`

These are all disabled sensors. So it's not really an issue, it is expected that a disabled entity will have no state. 

### Describe the behavior you expected

Ignore disabled sensors.

### Steps to reproduce the issue

1. Disable an entity in an integration.
2. Look in Developer Tools / Statistics
3.
...

### What version of Home Assistant Core has the issue?

core-2021.11.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

All of them

### Which operating system are you using to run this browser?

Windows 10 Pro version 21H1 (19043.1237)

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Filter out disabled entities. They are now no longer shown in the table. If they get enabled, while the table is visible, the table will get automatically updated to reflect the new situation.

The alternative would be to still show the disabled entities, but render a different text in the "Issue" column.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #10561
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/developer-tools/statistics/developer-tools-statistics.ts [hunk 1]
```diff
@@ -43,6 +45,8 @@ class HaPanelDevStatistics extends LitElement {
     state?: HassEntity;
   })[] = [] as StatisticsMetaData[];
 
+  @state() private _disabledEntities = new Set<string>();
```
Comment (bramkragten) [inline src/panels/developer-tools/statistics/developer-tools-statistics.ts:48]: `_disabledEntities` is not used in render/updated, so it doesnt need to be a `state`

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
