### PR TITLE
Refresh store collection when adding or removing repository

### LINKED ISSUE #26173: Add-ons from newly added add-on repositories don't show up until refreshing page
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When you add a new add-on repository in the add-on store, the add-ons from that repository do not show up in the store (including when you search) until you refresh the page.

### Describe the behavior you expected

I expected the frontend to automatically update the page with the add-ons from the newly-added repository.

### Steps to reproduce the issue

1. Go to the Add-on Store
2. Use the menu to go to your repositories
3. Add a new repository (e.g. https://github.com/brenner-tobias/ha-addons)
4. Search for an add-on from that repository (e.g. CloudFlared)
5. Refresh the page
6. Search for the add-on again
...

### What version of Home Assistant Core has the issue?

core-2025.7.2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Mozilla Firefox 140.0.4

### Which operating system are you using to run this browser?

macOS Sequoia (15.5)

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by loganrosen**
## Proposed change
This PR ensures that the store collection is updated whenever a repository is added or removed. As described in the linked PR, this allows add-ons from a newly-added (or removed) repository to show up without needing to refresh the page.

## Type of change
- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration
N/A

## Additional information
- This PR fixes or closes issue: fixes #26173

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.
  - I tried adding tests for this, but it seems like the right testing infrastructure doesn't exist in this repo to test component behavior. Please let me know if I'm missing something.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: hassio/src/dialogs/repositories/dialog-hassio-repositories.ts [hunk 1]
```diff
@@ -233,6 +233,7 @@ class HassioRepositoriesDialog extends LitElement {
       this._repositories = await fetchStoreRepositories(this.hass);
 
       fireEvent(this, "supervisor-collection-refresh", { collection: "addon" });
+      fireEvent(this, "supervisor-collection-refresh", { collection: "store" });
```
Comment (MindFreeze) [inline hassio/src/dialogs/repositories/dialog-hassio-repositories.ts]: `_loadData` is called in `showDialog` and in `_removeRepository`. We don't need to refresh the store in these cases. I think it makes more sense to only refresh it in `_addRepository` directly

File: hassio/src/addon-store/hassio-addon-store.ts [hunk 2]
```diff
@@ -206,6 +206,7 @@ export class HassioAddonStore extends LitElement {
     fireEvent(this, "supervisor-collection-refresh", {
       collection: "supervisor",
     });
+    fireEvent(this, "supervisor-collection-refresh", { collection: "store" });
```
Comment (MindFreeze) [inline hassio/src/addon-store/hassio-addon-store.ts]: Do we need this here if the dialog already does a refresh after adding a store?

File: hassio/src/dialogs/repositories/dialog-hassio-repositories.ts (hunk 1 above)
Comment (loganrosen) [reply hassio/src/dialogs/repositories/dialog-hassio-repositories.ts]: Agreed for `showDialog`, but for `_removeRepository`, wouldn't we want that repository/its addons not to show up upon removal?

File: hassio/src/addon-store/hassio-addon-store.ts (hunk 2 above)
Comment (loganrosen) [reply hassio/src/addon-store/hassio-addon-store.ts]: You're right, we don't – I only added it for consistency. Removed.

File: hassio/src/dialogs/repositories/dialog-hassio-repositories.ts (hunk 1 above)
Comment (MindFreeze) [reply hassio/src/dialogs/repositories/dialog-hassio-repositories.ts]: I thought `removeStoreRepository` already did that but if it doesn't, we should add a refresh to `_removeRepository` too

Comment (loganrosen) [reply hassio/src/dialogs/repositories/dialog-hassio-repositories.ts]: Yeah, it seems this is needed for repository removal as well; otherwise the repository isn't removed from the addon store when refreshing. I've updated the PR to only refresh the store for repository addition and removal based on your feedback.

**Review by MindFreeze — APPROVED** [review]
Thank you!
