### PR TITLE
Fix ignored config entries

### LINKED ISSUE #5875: [0.110.0b0] Ignored integrations are shown
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

This is what my integrations page looks like. As you can see, the HomeKit integrations is shown altough it should be ignored:
Screenshot_2020 05 14_14h48m12s_021_

When I press "Show ignored integrations", the ignored integrations is shown twice:
Screenshot_2020 05 14_14h49m54s_022_

## Expected behavior

Hide ignored integrations 

## Environment

- Home Assistant release with the issue: 0.110.0b0
- Last working Home Assistant release (if known): 0.109.x
- Browser and browser version: Edge Chrome 83
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/5875
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/integrations/ha-config-integrations.ts [hunk 1]
```diff
@@ -170,11 +170,12 @@ class HaConfigIntegrations extends SubscribeMixin(LitElement) {
         filter
       );
       const ignored: ConfigEntryExtended[] = [];
-      filteredConfigEnties.forEach((item, index) => {
-        if (item.source === "ignore") {
-          ignored.push(filteredConfigEnties.splice(index, 1)[0]);
+      let i = filteredConfigEnties.length;
+      while (i--) {
```
Comment (zsarnett) [inline src/panels/config/integrations/ha-config-integrations.ts:174]: Is this better than a for loop? I feel like they are the same but a for loop is more readable as its more common
