### PR TITLE
Propagate schema changes to existing form editor element

### LINKED ISSUE #29776: Updated schemas may not be updated down to ha-form
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Look how attribute selectors work differently in these cards:

Entity card:
1. Select an entity containing a numerical attribute.
2. Select a numerical attribute.

Image

3. Change the entity to some other entity which does not contain THIS selected attribute.
4. See that the "Attribute" field is cleared - CORRECT.

Guess this happens because of this code in `hui-entity-card-editor`:
```
      {
        name: "attribute",
        selector: {
          attribute: {},
        },
        context: {
          filter_entity: "entity",
        },
      },
```

But the same scenario will not work for a `state-label` in a Picture elements card - although there is same code in `hui-state-label-element-editor`:
4. See that the "Attribute" field is NOT cleared - WRONG.

Image

----------

Another case which I observed while working on https://github.com/home-assistant/frontend/pull/29759:
1. Open Map card editor.
2. Go to sub editor for some entity which is not `zone`.
3. Select some "Label mode" value.
4. Change the entity to some `zone` one.
5. See that the "Label mode" is not cleared - WRONG.

The proposed code for `hui-map-card-editor` in https://github.com/home-assistant/frontend/pull/29759 as follows:
```
          schema: [
            {
              name: "label_mode",
              disabled: this._disabledLabelMode(entityId),
              selector: {
                select: {
                  mode: "dropdown",
```
and the `disabled` line only affects after reopening the sub editor.

Compare with a Tile card:
The `features_position` element is `disabled` under some conditions:
`disabled: vertical && value === "inline"`
Open Tile card editor and start changing an orientation - then `features_position` will be updated properly.

----

Seems that the updated schema (if I may express it in this way) may not make to the final `ha-form` element:
1. The Entity card editor uses `ha-form` directly, and the Picture elements card uses a long chain `hui-sub-element-editor` -> `hui-picture-element-element-editor` -> `hui-state-badge-element-editor` -> `ha-form`.
2. Similarly, the Tile card uses `ha-form` directly for `features_position`, and the proposed `hui-map-card-editor` uses a similar long chain.

### Describe the behavior you expected

see above

### Steps to reproduce the issue

see above

### What version of Home Assistant Core has the issue?

2026.2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

When a parent passes a new schema to `hui-form-element-editor` (e.g. with updated `disabled` flags after an entity selection changes), the internal `hui-form-editor` was not updated because `loadConfigElement()` returns early once the element already exists.

Fix: make `_configElement` `protected` in `HuiElementEditor` and add an `updated()` hook in `HuiFormElementEditor` that pushes the new schema directly onto the existing config element when it changes.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #29776
- This PR is related to issue or discussion: #29759
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure
[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

**Comment by ildar170975** [comment]
Another example was described [here](https://github.com/home-assistant/frontend/issues/29776):
an editor for Picture elements card does not clear an "Attribute" field when editing a `state-label` element.

File: src/panels/lovelace/cards/hui-map-card.ts [hunk 1]
```diff
@@ -38,10 +38,7 @@ import {
 } from "../common/has-changed";
 import { processConfigEntities } from "../common/process-config-entities";
 import type { LovelaceCard, LovelaceGridOptions } from "../types";
-import type {
-  MapCardConfig,
-  MapEntityConfig,
-} from "./types";
+import type { MapCardConfig, MapEntityConfig } from "./types";
```
Comment (MindFreeze) [inline src/panels/lovelace/cards/hui-map-card.ts:41]: This is unrelated but needs to be fixed in `dev`

Comment (ildar170975) [reply src/panels/lovelace/cards/hui-map-card.ts:41]: Strange that there were no errors when I prepared that PR for map card editor.

**Comment by karwosts** [comment]
Did you test this? If I try changing the schema the entire editor just vanishes.

I don't think spreading an object will cause it to fail a deepequal check, it's still equivalent when you compare the keys.

**Comment by MindFreeze** [comment]
Sorry, I saw this but forgot to draft the PR and didn't have time to fix it

**Comment by MindFreeze** [comment]
Found a simpler fix

**Review by silamon — APPROVED** [review]
