### PR TITLE
Handle no operation mode

### LINKED ISSUE #1881: Lovelace thermostat card broken if operation_list absent
**Home Assistant release with the issue:**
0.81.0

**Last working Home Assistant release (if known):**
N/A

**Browser and Operating System:**
Firefox on linux

**Description of problem:**

Thermostat card does not show up in the UI if the underlying entity does not expose an operations_list.

**Javascript errors shown in the web inspector (if applicable):**
```
TypeError: stateObj.attributes.operation_list is undefined    [Learn More] d076e229b8879acac643.chunk.js:1701
```

**Additional information:**
@balloob suggested that operation_list should always be present on a climate entity, but that would make support for operation_modes mandatory for climate platforms, which will look weird in both classic UI and lovelace if only 1 operation mode is supported.
Either way, the thermostat card should deal with a situation where this list contains less than 2 items, for example by hiding the operation modes.

### PR DESCRIPTION
**Pull request by balloob**
Type the climate entity component and handle the missed cases.

Fixes #1881

For domain specific cards, we should take the types from [the docs](https://developers.home-assistant.io/docs/en/entity_climate.html). (and probably fill them in if they don't exist)

### CODE REVIEW

File: src/types.ts [hunk 1]
```diff
@@ -85,3 +86,27 @@ export interface HomeAssistant {
   sendWS: (msg: MessageBase) => Promise<void>;
   callWS: <T>(msg: MessageBase) => Promise<T>;
 }
+
+export type ClimateEntity = HassEntity & {
```
Comment (balloob) [inline src/types.ts]: This is kinda annoying as HassEntity also defines `attributes = {[s: string]: any}`, which means autocomplete doesn't work. I opened https://github.com/home-assistant/home-assistant-js-websocket/pull/64 to address that. Will update this in a future PR.

**Review by zsarnett — APPROVED** [review]
