### PR TITLE
Fix background on panel

### LINKED ISSUE #2839: View in panel mode does not apply theme
**Home Assistant release with the issue:** 0.88.0

**Browser and Operating System:** Chrome/Linux

**Description of problem:**
When creating a view with "panel: true" the view specific theme is not getting applied. When removing "panel: true" everything works as expected.

Example:
```
views:
  - title: MyView
    panel: true
    theme: dashboard
    cards:
        [ ... ]
```

### LINKED ISSUE #3705: LL view in panel mode shows no background image
**Home Assistant release with the issue:**
0.99.0b0

**Last working Home Assistant release (if known):**
0.98.5

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
FF and Chrome confirmed.

**Description of problem:**
Add a view with background image and a simple markdown card.
```
  - title: Panelview
    background: center / cover no-repeat url("/local/pictures/backgrounds/sunset01.jpg") fixed
    #panel: true
    cards:
      - type: markdown
        content: some text
```

Now enable panel mode
```
    panel: true
```

The background image doesn't show anymore.
An empty panel view shows the background image, after adding the first card, it's gone.

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/3705
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/2839

### CODE REVIEW

File: src/panels/lovelace/hui-root.ts [hunk 1]
```diff
@@ -614,7 +617,13 @@ class HUIRoot extends LitElement {
     } else {
       if (viewConfig.panel && viewConfig.cards && viewConfig.cards.length > 0) {
         view = createCardElement(viewConfig.cards[0]);
-        view.isPanel = true;
+        view = document.createElement("div");
```
Comment (balloob) [inline src/panels/lovelace/hui-root.ts]: you override the created view element above?

File: src/panels/lovelace/hui-root.ts [hunk 2]
```diff
@@ -614,7 +617,13 @@ class HUIRoot extends LitElement {
...
+        view.id = "panel";
+        view.classList.add("panel");
```
Comment (balloob) [inline src/panels/lovelace/hui-root.ts]: There is already a div with class=panel in the render method ?

Comment (bramkragten) [reply src/panels/lovelace/hui-root.ts]: Yes, but since cast doesn’t have this div I can’t use it for the background, we could set the background on both that div and `hui-view`, but that will give problems with transparant backgrounds.

Comment (balloob) [reply src/panels/lovelace/hui-root.ts]: Can we add it to cast? Is this better fixed by breaking up `hui-root` into a UI with tabs and a "content renderer" ? 

We can't have two divs with the same class, that is going to cause bugs eventually.

Comment (bramkragten) [reply src/panels/lovelace/hui-root.ts]: So I used id's to apply the class, mean styles are duplicated a bit... Problem is that the theme is set in `hui-view` so we don't have the theme settings yet on the `#view` element. For a panel there was no theme set at all btw, that is now done in `hui-root`, but without watching for changes etc like in `hui-view` the best solution would be to have a panel element that deals with the theme properly and the styling.

Breaking up `hui-root` is a good idea, it is too big and does too much.

File: src/panels/lovelace/hui-root.ts (hunk 1 above)
Comment (bramkragten) [reply src/panels/lovelace/hui-root.ts]: Was supposed to be deleted... 🤦‍♂

File: src/panels/lovelace/hui-root.ts [hunk 3]
```diff
@@ -613,8 +626,15 @@ class HUIRoot extends LitElement {
       view = this._viewCache![viewIndex];
     } else {
       if (viewConfig.panel && viewConfig.cards && viewConfig.cards.length > 0) {
-        view = createCardElement(viewConfig.cards[0]);
-        view.isPanel = true;
+        view = document.createElement("div");
+        view.id = "panel";
```
[the remark this answers is not in the document]
Comment (bramkragten) [reply src/panels/lovelace/hui-root.ts]: no, you would have:
```html
<div id="view">
    <div id="panel">
        <card></card>
    </div>
</div>
```

**Review by balloob — APPROVED** [review]
