### PR TITLE
Fix entity and device selector with `multiple: true`

### LINKED ISSUE #12246: Filtering for the device selector doesn't work when multiple devices are allowed
### The problem

Filtering devices in the `device` selector (e.g. with `integration`) doesn't seem to be applied in the UI picker when combined with `multiple: true`, but does seem to work with `multiple: false`.

### What version of Home Assistant Core has the issue?

2022.04.0

### What was the last working version of Home Assistant Core?

_No response_

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

_No response_

### Link to integration documentation on our website

https://www.home-assistant.io/docs/blueprint/selectors/#device-selector

### Diagnostics information

_No response_

### Example YAML snippet

```yaml
script:
  test:
    alias: 'Test'
    fields:
      target:
        name: 'Target'
        selector:
          device:
            integration: 'mobile_app'
            multiple: true
    sequence: []
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

Screenshot from 2022-04-07 11-10-44
Screenshot from 2022-04-07 11-11-48

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

The selector variants for multiple entities and devices had various issues:
1. Devices were not filtered as no filter function was passed along
2. Both device and entity selectors did not forward the `disabled` state
3. The active input dropdown had not `allow-custom-entity` set where as the single ones did

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #12246
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/device/ha-devices-picker.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@ import { customElement, property } from "lit/decorators";
 import { fireEvent } from "../../common/dom/fire_event";
 import { PolymerChangedEvent } from "../../polymer-types";
 import { HomeAssistant } from "../../types";
-import "./ha-device-picker";
+import { HaDevicePickerDeviceFilterFunc } from "./ha-device-picker";
```
Comment (zsarnett) [inline src/components/device/ha-devices-picker.ts:6]: Still need the other import

**Review by zsarnett — DISMISSED** [review]

File: src/components/device/ha-devices-picker.ts (hunk 1 above)
Comment (spacegaier) [reply src/components/device/ha-devices-picker.ts:6]: I then get an `eslint` error regarding duplicate imports. I don't have them in `ha-entities-picker.ts` though.

**Review by zsarnett — APPROVED** [review]
