### PR TITLE
Fix device config tooltips

### LINKED ISSUE #5074: Automation opens in browser instead of app
**Home Assistant Android app version(s):** 2025.3.1-full

**Android version(s):** 15

**Device model(s):** Nothing Phone (1)

**Home Assistant version:** 2025.3.0b8

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:** When clicking on an automation on a device page, it opens in a browser instead of the HA Companion app.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**
https://github.com/user-attachments/assets/54a8cf3d-407b-4d6e-a9ec-2d42e3117ef1

**Additional information:**

### LINKED ISSUE #24591: Frontend reloads when navigating to automation from device page
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When clicking on an automation on a device page, the entire frontend reloads instead of simply navigating to that page without reloading as other links do (for example, the link to the integration on that same page). This is noticeable because the initial load screen is visible. 

https://github.com/user-attachments/assets/526d69ba-3fbf-4ae1-8154-9e4fa3e3e3df

I think the link is missing an event handler making it behave like a normal link?

(via: home-assistant/android#5074, the 'raw' link is treated as navigating away from the main app interface so opened in the device browser)

### Describe the behavior you expected

The frontend navigates to the page without reloading.

### Steps to reproduce the issue

1. Go to Settings > Devices & services > Devices > [pick a device which is included in an automation]
2. Click on an automation in the 'Automations' section
3. [the frontend reloads]

### What version of Home Assistant Core has the issue?

core-2025.3.1

### What was the last working version of Home Assistant Core?

core-2025.2.5

### In which browser are you experiencing the issue?

Firefox 136.0, Google Chrome 134.0.6998.36, Android System WebView 134.0.6998.39

### Which operating system are you using to run this browser?

Windows 11, Windows 11/Android 15, Android 15

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change
Fixes https://github.com/home-assistant/frontend/issues/24591
Fixes https://github.com/home-assistant/android/issues/5074

For automations: Removes the tooltip and provide a link to view the automation in read-only mode. 
For scenes: Only defines the tooltip when the scene is not editable, so it no longer pushes the app to open in browser.  The disabled state has been removed to fix the tooltip. 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/devices/ha-config-device-page.ts [hunk 1]
```diff
@@ -531,34 +519,38 @@ export class HaConfigDevicePage extends LitElement {
...
                                   <ha-list-item
                                     hasMeta
                                     .scene=${entityState}
-                                    .disabled=${!entityState.attributes.id}
                                   >
                                     ${computeStateName(entityState)}
                                     <ha-icon-next slot="meta"></ha-icon-next>
                                   </ha-list-item>
                                 </a>
                               </ha-tooltip>
```
Comment (MindFreeze) [inline src/panels/config/devices/ha-config-device-page.ts:535]:
```suggestion
```
leftover line

**Review by MindFreeze — DISMISSED** [review]
This fixes the current issue but I still don't see why it happened. Do you know why the new shoelace tooltip causes this?

**Comment by MindFreeze** [comment]
cc @wendevlin

**Comment by silamon** [comment]
> This fixes the current issue but I still don't see why it happened. Do you know why the new shoelace tooltip causes this?

It's because the ha-list-item is embedded in the ha-tooltip, where it previously was the ha-tooltip being part of the ha-list-item.

**Review by MindFreeze — APPROVED** [review]

**Comment by wendevlin** [comment]
I tested it on my test env and I am not able to reproduce it :shrug: when I wrap it with `ha-tooltip`

@silamon have you been able to reproduce it?

**Comment by silamon** [comment]
> I tested it on my test env and I am not able to reproduce it 🤷 when I wrap it with `ha-tooltip`
> 
> @silamon have you been able to reproduce it?

Yes, it's reproducable even without app.
