### PR TITLE
Correctly handle  "hours to show" for footer graph

### LINKED ISSUE #8055: Line graph card loose 24h older data on auto-update when showing 48h
## Checklist

- [ X] I have updated to the latest available Home Assistant version.
- [ X] I have cleared the cache of my browser.
- [ X] I have tried a different browser to see if it is related to my browser.

## The problem

When line graph card update data list, it loose the 24h old and older data.
This happen when using when using a 48h Hours to Show (Optionnal) parameter.

## Expected behavior

Having the same graph with updated data. Correct chart plot for full 48h, not just 24h.

## Steps to reproduce

1. Create any line chart card.
2. Show/display the card
3. Wait for refresh
4. Bug starts to appear after ~1min, ~15min for all). Seems to be at the programmed JS trigger

## Environment

- Home Assistant release with the issue: Supervised Debian 2020.12.7
- Last working Home Assistant release (if known): Unknown
- Browser and browser version: Chrome 87.0.4280.88 & Firefox 84.0.1 & Chromium 86.0.4240.197
- Operating system: Windows 10 19042.685 & Debian 10.7 on RPi 4 & Debian 10.7 on x64

## State of relevant entities

State: all ok except: Last updated: Invalid Date

Picture after full browser update:

image

Picture after chart auto refresh

image
image

## Problem-relevant configuration

Line graph card:
```yaml
  - type: sensor
    entity: sensor.outside_ds_temperature
    graph: line
    detail: 2
    hours_to_show: 48
```

* (Outside & Outside DS temperature) & (MPL3115 pressure kPa & temperature): MQTT using Discovery
* MPL3115 hPa: sensor template: (states('sensor.mpl3115_pressure') | float * 10) | round(2)
* Environnement Canada: Weather platform environment_canada 
* Institute: Meteorologisk institutt integration
* APC: Network UPS Tools (NUT) integration

## Javascript errors shown in your browser console/inspector

```txt
None relevant
```

## Additional information

If i'm correct, when the graph is updating data, it does not get the full data array. (If yes, a code reusability is missing.)

It seems that only last data is received and the code clean iteself (old data that do not need to be plotted/shown anymore). When the code is cleaning old data, it uses the 24h default configuration rather than the 48h configuration option of the card. Then cleaning data between the 48h and 24h offsets.

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

This PR fixes two issues:
1. The old coding did always check against 24 hours to see whether previously loaded history entries should be discarded rather than using the config parameter "hours to show".
2. The old coding did not account for the "initial state" of the history. So if 12 hours should be shown, but only 13 hours ago and then 2 hours ago did state changes occur, the frontend receives also the history entry from 13 hours ago from the backend. So the initial graph rendering was always fine. However, during the subsequent updates (when only the delta of newly recorded history entries is retrieved from the backend), the frontend did discard all cached history entries that lie outside the 12 hours. That would mean that "initial state" history entry would be lost (and effectively only values from 2 hours ago until now would be rendered). 
This PR now ensures that the last previous history entry that now lies outside the "hours to show" is retained so that the graph has a correct "entry value" = value on the left border of the graph.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/8055
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by spacegaier** [comment]
@zsarnett Since you did the implementation for the cached history, could you have a look at my changes if those look good to you

File: src/panels/lovelace/header-footer/hui-graph-header-footer.ts [hunk 1]
```diff
@@ -162,10 +162,25 @@ export class HuiGraphHeaderFooter extends LitElement
...
       );
+      this._stateHistory = [];
+
+      if (outHoursToShow.length) {
+        // If we have values that are now outside of "hours to show", re-add the last entry. This could e.g. be
+        // the "initial state" from the history backend. Without it, it would look like there is no history data
+        // at the start at all in the database = graph would start suddenly instead of on the left side of the card.
+        this._stateHistory.push(outHoursToShow[outHoursToShow.length - 1]);
+      }
+      this._stateHistory = this._stateHistory.concat(inHoursToShow);
```
Comment (bramkragten) [inline src/panels/lovelace/header-footer/hui-graph-header-footer.ts:183]:
```suggestion
      this._stateHistory = inHoursToShow;
```

File: src/panels/lovelace/header-footer/hui-graph-header-footer.ts [hunk 2]
```diff
@@ -162,10 +162,25 @@ export class HuiGraphHeaderFooter extends LitElement
...
+      const outHoursToShow: HassEntity[] = [];
+      // Split into inside and outside of "hours to show".
+      this._stateHistory!.forEach((entity) =>
+        (endTime.getTime() - new Date(entity.last_changed).getTime() <=
+        this._config!.hours_to_show! * HOUR
+          ? inHoursToShow
+          : outHoursToShow
+        ).push(entity)
       );
+      this._stateHistory = [];
```
Comment (bramkragten) [inline src/panels/lovelace/header-footer/hui-graph-header-footer.ts:175]:
```suggestion
```

File: src/panels/lovelace/header-footer/hui-graph-header-footer.ts [hunk 3]
```diff
@@ -162,10 +162,25 @@ export class HuiGraphHeaderFooter extends LitElement
...
+
+      if (outHoursToShow.length) {
+        // If we have values that are now outside of "hours to show", re-add the last entry. This could e.g. be
+        // the "initial state" from the history backend. Without it, it would look like there is no history data
+        // at the start at all in the database = graph would start suddenly instead of on the left side of the card.
+        this._stateHistory.push(outHoursToShow[outHoursToShow.length - 1]);
```
Comment (bramkragten) [inline src/panels/lovelace/header-footer/hui-graph-header-footer.ts:181]:
```suggestion
        inHoursToShow.push(outHoursToShow[outHoursToShow.length - 1]);
```

**Comment by spacegaier** [comment]
@bramkragten I verified your proposals. They indeed work as the order of entries in `this._stateHistory` plays no role (the coordinates() logic seems to take care of the sorting on its own already), so my convoluted attempt to retain the order was not needed.

**Comment by spacegaier** [comment]
@zsarnett Ping. It would really like to have that in the next beta 😄. The issue drives me nuts on my dashboard.

**Review by bramkragten — APPROVED** [review]
