### PR TITLE
Include background in light, climate and security views

### LINKED ISSUE #28212: Theme background not visibel in new  "Lights" "Climate" "Security"
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Theme backround not visibel in new  "Lights" "Climate" "Security"

The Theme backround is visible in "Home"

### Describe the behavior you expected

I expect the background to be visibel in "Lights" "Climate" "Security" and "Home"

### Steps to reproduce the issue

1. Install Theme with a background (ios-dark-mode-blue-red)
2. Go to "Lights" "Climate" "Security" and "Home"
3.
...

### What version of Home Assistant Core has the issue?

2025-12-0b2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Firefox

### Which operating system are you using to run this browser?

Ubuntu

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

Image

Image

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change
Just the background variable as the views don't have a background setting in UI.
Fixes https://github.com/home-assistant/frontend/issues/28212 

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/climate/ha-panel-climate.ts [hunk 1]
```diff
@@ -115,6 +115,11 @@ class PanelClimate extends LitElement {
         this._lovelace
           ? html`
               <hui-view-container .hass=${this.hass}>
+                <hui-view-background
+                  .hass=${this.hass}
+                  .background=${this._lovelace.config.views[0].background}
```
Comment (bramkragten) [inline src/panels/climate/ha-panel-climate.ts]:
```suggestion
                  .background=${this._lovelace.config.views[this._viewIndex].background}
```

File: src/panels/light/ha-panel-light.ts [hunk 2]
```diff
@@ -115,6 +115,11 @@ class PanelLight extends LitElement {
         this._lovelace
           ? html`
               <hui-view-container .hass=${this.hass}>
+                <hui-view-background
+                  .hass=${this.hass}
+                  .background=${this._lovelace.config.views[0].background}
```
Comment (bramkragten) [inline src/panels/light/ha-panel-light.ts]:
```suggestion
                  .background=${this._lovelace.config.views[this._viewIndex].background}
```

File: src/panels/security/ha-panel-security.ts [hunk 3]
```diff
@@ -115,6 +115,11 @@ class PanelSecurity extends LitElement {
         this._lovelace
           ? html`
               <hui-view-container .hass=${this.hass}>
+                <hui-view-background
+                  .hass=${this.hass}
+                  .background=${this._lovelace.config.views[0].background}
```
Comment (bramkragten) [inline src/panels/security/ha-panel-security.ts]:
```suggestion
                  .background=${this._lovelace.config.views[this._viewIndex].background}
```

File: src/panels/climate/ha-panel-climate.ts (hunk 1 above)
Comment (bramkragten) [reply src/panels/climate/ha-panel-climate.ts]: Setting the background prop might not be needed, as it will never be set anyway but 🤷‍♂️

**Review by MindFreeze — CHANGES_REQUESTED** [review]
Missing `import "../lovelace/views/hui-view-background";` on all 3 files

**Review by MindFreeze — APPROVED** [review]
