### PR TITLE
Avoid gaps in grid card with conditional

### LINKED ISSUE #9433: Grid card shows empty first (conditional) card
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

using a type: grid card to show conditional button cards, all squares (using `aspect_ratio: 1/1`) , it always shows the first (left) position as an empty placeholder without a card.

other than that, the grid is filled perfectly, and depending on the conditions for the individual cards, fills as should

4 'on' cards:
Schermafbeelding 2021-06-16 om 14 04 00

3:
Schermafbeelding 2021-06-16 om 14 01 02

2:
Schermafbeelding 2021-06-16 om 14 02 03

1:
Schermafbeelding 2021-06-16 om 14 15 09

### Describe the behavior you expected

use the first placeholder in the grid

### Steps to reproduce the issue

1. create the grid, with config below
2.
3.
...

### What version of Home Assistant Core has the issue?

2021.6.5

### What was the last working version of Home Assistant Core?

dk

### In which browser are you experiencing the issue with?

Any really, both desktop an handheld 

### Which operating system are you using to run this browser?

Big sur 11.4

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

```yaml
- type: grid
  title: Alerts
  columns: 4
  cards:
    !include /config/lovelace/buttons/buttons_alerts.yaml
```

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

the include files has all conditional cards, like:

```
- type: conditional
  conditions:
    - entity: binary_sensor.doors
      state: 'on'
  card: !include /config/lovelace/includes/include_button_sensor_doors.yaml

- type: conditional
  conditions:
    - entity: binary_sensor.garage_door
      state: 'on'
  card: !include /config/lovelace/includes/include_button_garage_door.yaml

- type: conditional
  conditions:
    - entity: binary_sensor.github_repo_has_update
      state: 'on'
  card: !include /config/lovelace/includes/include_button_github_repo_alert.yaml

- type: conditional
  conditions:
    - entity: binary_sensor.earthquakes_near_active
      state: 'on'
  card: !include /config/lovelace/includes/include_button_quake_alert.yaml

- type: conditional
  conditions:
    - entity: binary_sensor.trash_notification
      state: 'on'
  card: !include /config/lovelace/includes/include_button_trash_alert.yaml
```

etc etc

seems to have to do with the preceding conditional cards in the list, that are not 'on', and hence leave the empty first space. taking all out of the list until the current Meteoalarm you see I the screen shot, moves it to the correct first slot.

if several others after it are 'off' and then again 1 is 'on', it shows nicely next to the first, no empty space.

### PR DESCRIPTION
**Pull request by thomasloven**
## Proposed change

The first card in a grid is forced into col 1 row 1 if the cards are square. That means there will be a gap if that card is currently hidden (by e.g. a conditional).

This fixes that by giving conditionals an attribute, and then checking for that as a special case in the grid card.

This uses a CSS trick to apply the row/col contraint to all cards, and then unset it to all but the first visible one. See https://stackoverflow.com/questions/3615518/css-selector-to-select-first-element-of-a-given-class/3615559#3615559

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9433
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/hui-grid-card.ts [hunk 1]
```diff
@@ -87,10 +87,14 @@ class HuiGridCard extends HuiStackCard<GridCardConfig> {
           grid-column: 1 / 1;
         }
 
-        :host([square]) #root > *:first-child {
+        :host([square]) #root > *:not([invisible]) {
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-grid-card.ts:90]: Why don't we just check if the first child has the attribute `invisible?`

Comment (thomasloven) [reply src/panels/lovelace/cards/hui-grid-card.ts:90]: If any card is visible, at least one needs `grid-area: 1/1/1/1`. So if the first card is invisible, the second one should take that spot, and so on.
And unfortunately `:first-of-type` doesn't work with attribute selectors.

Comment (bramkragten) [reply src/panels/lovelace/cards/hui-grid-card.ts:90]: Oh... right it is because of the `::before` that targets `1/1/1/1`...

**Comment by bramkragten** [comment]
Ugh... https://caniuse.com/?search=aspect-ratio

**Comment by thomasloven** [comment]
It *could* have been easy...

**Comment by thomasloven** [comment]
Maybe it would work better if the `::before` was an `::after` 🤔. I'll do some experimenting when my docker starts behaving again.

**Comment by bramkragten** [comment]
> Maybe it would work better if the `::before` was an `::after` 🤔. I'll do some experimenting when my docker starts behaving again.

That should not make a difference

File: src/panels/lovelace/components/hui-conditional-base.ts [hunk 2]
```diff
@@ -17,6 +17,8 @@ export class HuiConditionalBase extends ReactiveElement {
 
   @property() protected _config?: ConditionalCardConfig | ConditionalRowConfig;
 
+  @property({ type: Boolean, reflect: true }) public invisible = false;
```
Comment (bramkragten) [inline src/panels/lovelace/components/hui-conditional-base.ts:20]: Might be better name?
```suggestion
  @property({ type: Boolean, reflect: true }) public hidden = false;
```

File: src/panels/lovelace/cards/hui-grid-card.ts [hunk 3]
```diff
@@ -87,10 +87,14 @@ class HuiGridCard extends HuiStackCard<GridCardConfig> {
...
           grid-row: 1 / 1;
           grid-column: 1 / 1;
         }
+        :host([square]) #root > *:not([invisible]) ~ *:not([invisible]) {
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-grid-card.ts:94]: Could also be done with `[style*='display: none']` instead of `[invisible]`

**Review by bramkragten — DISMISSED** [review]

File: src/panels/lovelace/components/hui-conditional-base.ts (hunk 2 above)
Comment (thomasloven) [reply src/panels/lovelace/components/hui-conditional-base.ts:20]: I agree.

File: src/panels/lovelace/cards/hui-grid-card.ts (hunk 3 above)
Comment (thomasloven) [reply src/panels/lovelace/cards/hui-grid-card.ts]: `style*` seems to be very picky about exact formatting in the styles. I feel there's an increased risk of mistakes with that.

File: src/panels/lovelace/cards/hui-grid-card.ts [hunk 4]
```diff
@@ -87,10 +87,14 @@ class HuiGridCard extends HuiStackCard<GridCardConfig> {
           grid-column: 1 / 1;
         }
 
-        :host([square]) #root > *:first-child {
+        :host([square]) #root > *:not([hidden]) {
           grid-row: 1 / 1;
           grid-column: 1 / 1;
         }
+        :host([square]) #root > *:not([hidden]) ~ *:not([hidden]) {
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-grid-card.ts:94]: Can we add a comment for this one? We probably won't remember what the heck this does and why in a few months

Comment (bramkragten) [inline src/panels/lovelace/cards/hui-grid-card.ts:94]:
```suggestion
        :host([square]) #root > *:not([hidden]) ~ *:not([hidden]) {
           /* 
	       * Remove grid-row and grid-column from every element that comes after the first
	       * non-hidden element
	       */
```

**Review by bramkragten — DISMISSED** [review]

File: src/panels/lovelace/cards/hui-grid-card.ts (hunk 4 above)
Comment (thomasloven) [reply src/panels/lovelace/cards/hui-grid-card.ts:94]: I was thinking that git blame would lead to this PR with the description, but a comment is probably a good idea too, yes.

**Review by bramkragten — APPROVED** [review]
