### PR TITLE
Fix issue where schema is null

### LINKED ISSUE #8308: Texecom2MQTT Add-on Config edit problem on core-2021.2.0b3
## The problem

The config edit tab for add-on texecom2mqtt appears to be trying to use a blank UI and will not allow the user to supply a configuration.

## Steps to reproduce

Install texecom2mqtt add-on.
Select Configuration tab
Note that UI is blank and that the option to select Edit in YAML is greyed out, there is no method for adding configuration details.

## Environment

Issue became apparent on 2021.2 beta (not sure which one) and is still there on 2021.2 proper
Issue is NOT present on 2021.1 
Issue is apparent on Safari (latest) and Firefox for Mac (latest)
OS is macOS Big Sur (latest)

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

Fixes issues when the schema is `null` (if the dev set a bool for the `schema` key)

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #8308
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: hassio/src/addon-view/config/hassio-addon-config.ts [hunk 1]
```diff
@@ -108,10 +108,12 @@ class HassioAddonConfig extends LitElement {
 
   protected firstUpdated(changedProps) {
     super.firstUpdated(changedProps);
-    this._canShowSchema = !this.addon.schema.find(
-      // @ts-ignore
-      (entry) => !SUPPORTED_UI_TYPES.includes(entry.type) || entry.multiple
-    );
+    this._canShowSchema =
+      this.addon.schema != null &&
```
Comment (balloob) [inline hassio/src/addon-view/config/hassio-addon-config.ts:112]:
```suggestion
      this.addon.schema !== null &&
```

**Review by balloob — APPROVED** [review]

File: hassio/src/addon-view/config/hassio-addon-config.ts (hunk 1 above)
Comment (ludeeus) [reply hassio/src/addon-view/config/hassio-addon-config.ts]: That's what I get when jumping between python and TS :D
