### PR TITLE
Don't show a battery if the entity domain is Number

### LINKED ISSUE #17578: Battery level shown for a device should be limited to certain domains
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If you have a `number` entity with the `BATTERY` device class, the frontend will show the state of that entity on the device dashboard and device lists as the battery level for the device.

I have a couple number entities for setting a low battery level cutoff for a relay and the UI is showing the cutoff value as the device's battery percent.

Sample:
image

### Describe the behavior you expected

I think this should be limited to sensors with the `battery` device class, not other "writable" entity platforms like `number`.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.9dev

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

All

### Which operating system are you using to run this browser?

N/A

### State of relevant entities

```txt
Entity ID/Name:
number.nc1_test_cutoff_battery_level
NC1 Test Cutoff battery level

State: 30.0

Attributes:
min: 0
max: 100
step: 1
mode: auto
device_class: battery
friendly_name: NC1 Test Cutoff battery level
```

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change
For device class "battery": The logic to show a battery state (for example 52%) was whenever the domain was not a binary sensor. With the introduction of the number domain, it started to show the battery as well. Other details are in the issue #17578. 

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration
You can change the device class of the number, binary sensor and sensor demo entities to have something that works. 

## Additional information

- This PR fixes or closes issue: fixes #17578
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/devices/ha-config-device-page.ts [hunk 1]
```diff
@@ -329,11 +328,10 @@ export class HaConfigDevicePage extends LitElement {
     const entitiesByCategory = this._entitiesByCategory(entities);
     const batteryEntity = this._batteryEntity(entities);
     const batteryChargingEntity = this._batteryChargingEntity(entities);
-    const batteryState = batteryEntity
+    const battery = batteryEntity
```
Comment (bramkragten) [inline src/panels/config/devices/ha-config-device-page.ts:331]: Why do we rename the const here?

File: src/panels/config/devices/ha-config-devices-dashboard.ts [hunk 2]
```diff
@@ -378,21 +377,24 @@ export class HaConfigDeviceDashboard extends LitElement {
...
               : undefined;
-          const batteryIsBinary =
-            battery && computeStateDomain(battery) === "binary_sensor";
+          const batteryDomain = battery ? computeStateDomain(battery) : "";
 
-          return battery && (batteryIsBinary || !isNaN(battery.state as any))
+          return battery &&
+            (batteryDomain === "sensor" ||
+              batteryDomain === "binary_sensor" ||
+              !isNaN(battery.state as any))
```
Comment (bramkragten) [inline src/panels/config/devices/ha-config-devices-dashboard.ts:385]: We don't do anything with these entities, so I think it should be removed here?

File: src/panels/config/devices/ha-config-device-page.ts (hunk 1 above)
Comment (silamon) [reply src/panels/config/devices/ha-config-device-page.ts:331]: It was renamed to be consistent with the other 2 pages. (The code is being used on 3 pages and is mostly the same, I've looked into putting it in it's own component. )

File: src/panels/config/devices/ha-config-devices-dashboard.ts (hunk 2 above)
Comment (silamon) [reply src/panels/config/devices/ha-config-devices-dashboard.ts:385]: On this page, the battery is showed near the end of the row in the table where a battery entity exists on a device.
The battery entity is used to show the state and if no state is present (because entity is a binary sensor) then the state is sort of reflected in the battery icon to indicate if it's charging or not as well to show if the battery is fully charged or empty.

**Comment by piitaya** [comment]
Why not checking the domain in `findBatteryEntity` function so we only keep `sensor` and `binary_sensor` entities with these domain?

**Comment by silamon** [comment]
> Why not checking the domain in `findBatteryEntity` function so we only keep `sensor` and `binary_sensor` entities with these domains?

You still need to compute the domain after doing so since we need to know if it's a sensor or a binary sensor. Also, a number entity with battery class is still a battery entity, we just don't want to use it to display it on a device.

**Comment by piitaya** [comment]
`findBatteryEntity` is only used for this usage. A number entity should not be considered as `battery`. It's a configuration entity, not a sensor.
And yes, we need to check for binary and sensor to adapt the display like we are doing with the current code.

We can also improve it to add some priority. For example, if a device has a binary sensor and a sensor, we must take the sensor because it has the percentage of battery.

File: src/data/entity_registry.ts [hunk 3]
```diff
@@ -129,15 +130,29 @@ export interface EntityRegistryEntryUpdateParams {
...
-      hass.states[entity.entity_id].attributes.device_class === "battery"
-  );
+): T | undefined => {
+  const batteryEntities = entities
+    .filter(
+      (entity) =>
+        hass.states[entity.entity_id] &&
+        hass.states[entity.entity_id].attributes.device_class === "battery"
+    )
+    .filter((item) => batteryPriorities.includes(computeDomain(item.entity_id)))
```
[the remark this answers is not in the document]
Comment (silamon) [reply src/data/entity_registry.ts:144]:
```suggestion
    .filter(
      (entity) =>
        hass.states[entity.entity_id] &&
        hass.states[entity.entity_id].attributes.device_class === "battery" &&
        batteryPriorities.includes(computeDomain(entity.entity_id))
    )
```

File: src/dialogs/more-info/controls/more-info-vacuum.ts [hunk 4]
```diff
@@ -303,6 +302,7 @@ class MoreInfoVacuum extends LitElement {
               "battery_level",
               Math.round(stateObj.attributes.battery_level)
             )}
+            %
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-vacuum.ts:305]: This is handled by `formatEntityAttributeValue` https://github.com/home-assistant/frontend/blob/dev/src/data/entity_attributes.ts#L71

File: src/dialogs/more-info/controls/more-info-vacuum.ts [hunk 5]
```diff
@@ -263,11 +263,8 @@ class MoreInfoVacuum extends LitElement {
       ? this.hass.states[batteryEntity.entity_id]
       : undefined;
 
-    const batteryIsBinary =
-      battery && computeStateDomain(battery) === "binary_sensor";
-
     // Use device battery entity
-    if (battery && (batteryIsBinary || !isNaN(battery.state as any))) {
+    if (battery && !isNaN(battery.state as any)) {
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-vacuum.ts:267]: Why this change?

Comment (silamon) [reply src/dialogs/more-info/controls/more-info-vacuum.ts:267]: battery contains the result of findBatteryEntity, which is now capable of detecting the domain as suggested above by Piitaya. The check is no longer needed until a bit below where we need to know if the battery is a sensor. 
FindBatteryEntity now only returns sensors and binary sensors, not longer number entities since these are configurable.

Comment (piitaya) [reply src/dialogs/more-info/controls/more-info-vacuum.ts:267]: We must keep this condition because if it's a binary sensor, it display a battery with charging state.

Comment (silamon) [reply src/dialogs/more-info/controls/more-info-vacuum.ts]: I see, thank you for the clarification. I've added the condition back in.

**Review by bramkragten — APPROVED** [review]
