### PR TITLE
Save default panel at user and system level

### LINKED ISSUE #18626: Default dashboard keeps resetting to Overview
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I recently reconfigured my primary custom .yaml dashboard configuration to clean up the URL (i.e. remove reference to anything "lovelace"). My configuration now looks like this:

```
lovelace:
  mode: storage
  dashboards:
    dash-board:
      mode: yaml
      filename: dashboard.yaml
      title: Home
      icon: mdi:home-account
      show_in_sidebar: true
      require_admin: false
```
Ever since, some of my devices seem to reset the default dashboard every 1-2 days to the Overview which is marked as default even if I stay logged in and on WiFi and/or when the app has to switch to external access (Nabu Casa) and then back to internal.

I cannot seem to pinpoint what part of the configuration changes are causing this. Any ideas or is this just a bug I need to report?

### Describe the behavior you expected

The dashboard I set as the default to persist.

### Steps to reproduce the issue

See above

### What version of Home Assistant Core has the issue?

2023.11.2

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

Multiple including iOS HA app and Edge

### Which operating system are you using to run this browser?

iOS 17.0.3 and Windows 10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Breaking change

The select from the profile page now update the user default panel
The `set as default` button from the dashboards config page now updates the system default panel

Per device default panel is not supported anymore to be consistent with sidebar settings.

## Proposed change

Alternative PR to https://github.com/home-assistant/frontend/pull/25702.

We also want to add default dashboard at the system level so this settings should be separated from sidebar.

- Needs https://github.com/home-assistant/core/pull/155945 for system storage (error is handled if the system storage websocket is not available to avoid UI blocking)

Changes : 
- [x] save the default panel per user when a user change it.
- [x] load the default panel from user data 
- [x] Load default panel **before** HA navigate to default panel
- [x] Compatible with existing default panel
- [x] Add system storage

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/18626
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by alexisgaziello** [comment]
Coincidence - I was just working on a similar feature on https://github.com/home-assistant/frontend/pull/27924. I kept local storage to have browser specific storage - You might want to have the device in you living default to something different than other devices.

Essentially I think the ideal preference should look like:

Browser specific > user specific > system specific > default

Thoughts?

**Comment by piitaya** [comment]
@alexisgaziello Yes, I saw your PR, thanks for the contribution 🙂

For now, we’ve decided not to use browser storage for several reasons:
- it keeps things consistent with the sidebar, since data is stored per user;
- browser storage isn’t fully reliable (especially on mobile, where the WebView storage can be cleared after some time or after an update). 
Because of that, browser storage will only be used for temporary purposes (e.g. data table filtering)

The correct approach is to create a dedicated user (e.g. for a wall-mounted tablet). This way, the sidebar and default panel can be properly configured.

**Comment by MindFreeze** [comment]
For mounted tablets, you can also just set the URL directly to a dashboard instead of relying on settings

File: src/panels/profile/ha-pick-dashboard-row.ts
Comment (MindFreeze) [inline src/panels/profile/ha-pick-dashboard-row.ts:35]: This string says "Pick a default dashboard for this device." but it isn't per device now

File: src/layouts/home-assistant.ts [hunk 1]
```diff
@@ -53,11 +52,12 @@ export class HomeAssistantAppEl extends QuickBarMixin(HassElement) {
...
-      navigate(`/${getStorageDefaultPanelUrlPath()}${location.search}`, {
-        replace: true,
-      });
-    }
+    // if (["", "/"].includes(path)) {
+    //   const defaultPanel = getCachedDefaultPanelUrlPath();
+    //   if (defaultPanel) {
+    //     navigate(`/${defaultPanel}${location.search}`, { replace: true });
+    //   }
+    // }
```
Comment (MindFreeze) [inline src/layouts/home-assistant.ts]: Commented out code

File: src/data/panel.ts [hunk 2]
```diff
@@ -1,26 +1,29 @@
...
 };
 
-export const setDefaultPanel = (
-  element: HTMLElement,
-  urlPath: string
-): void => {
-  fireEvent(element, "hass-default-panel", { defaultPanel: urlPath });
+export const getLegacyDefaultPanelUrlPath = (): string | null => {
+  const defaultPanel = window.localStorage.getItem("defaultPanel");
+  return defaultPanel ? JSON.parse(defaultPanel) : null;
```
Comment (MindFreeze) [inline src/data/panel.ts]: These functions are identical

File: src/panels/profile/ha-pick-dashboard-row.ts
Comment (piitaya) [reply src/panels/profile/ha-pick-dashboard-row.ts:35]: Oh right ! I must update the text. Good catch!

File: src/state/connection-mixin.ts [hunk 3]
```diff
@@ -282,10 +284,22 @@ export const connectionMixin = <T extends Constructor<HassBaseEl>>(
...
-      subscribeFrontendUserData(conn, "core", ({ value: userData }) => {
-        this._updateHass({ userData });
+      // Catch errors to userData and systemData subscription (e.g. if the
+      // backend isn't up to date) and set to null so frontend can continue
+      subscribeFrontendUserData(conn, "core", ({ value: userData }) =>
+        this._updateHass({ userData: userData || {} })
+      ).catch(() => {
+        // eslint-disable-next-line no-console
+        console.error("Failed to subscribe to user data, setting to null");
+        this._updateHass({ userData: {} });
```
Comment (MindFreeze) [inline src/state/connection-mixin.ts]: It's not really `null`

**Review by MindFreeze — DISMISSED** [review]

File: src/state/connection-mixin.ts [hunk 4]
```diff
@@ -282,10 +284,22 @@ export const connectionMixin = <T extends Constructor<HassBaseEl>>(
...
       subscribePanels(conn, (panels) => this._updateHass({ panels }));
-      subscribeFrontendUserData(conn, "core", ({ value: userData }) => {
-        this._updateHass({ userData });
+      // Catch errors to userData and systemData subscription (e.g. if the
+      // backend isn't up to date) and set to null so frontend can continue
+      subscribeFrontendUserData(conn, "core", ({ value: userData }) =>
+        this._updateHass({ userData: userData || {} })
+      ).catch(() => {
+        // eslint-disable-next-line no-console
+        console.error("Failed to subscribe to user data, setting to null");
```
Comment (piitaya) [inline src/state/connection-mixin.ts]:
```suggestion
        console.error("Failed to subscribe to user data, setting to empty object");
```

File: src/state/connection-mixin.ts [hunk 5]
```diff
@@ -282,10 +284,22 @@ export const connectionMixin = <T extends Constructor<HassBaseEl>>(
...
+        this._updateHass({ userData: {} });
+      });
+      subscribeFrontendSystemData(conn, "core", ({ value: systemData }) =>
+        this._updateHass({ systemData: systemData || {} })
+      ).catch(() => {
+        // eslint-disable-next-line no-console
+        console.error("Failed to subscribe to system data, setting to null");
```
Comment (piitaya) [inline src/state/connection-mixin.ts]:
```suggestion
        console.error("Failed to subscribe to system data, setting to empty object");
```

**Review by MindFreeze — APPROVED** [review]

File: src/components/ha-sidebar.ts [hunk 6]
```diff
@@ -418,23 +422,27 @@ class HaSidebar extends SubscribeMixin(LitElement) {
...
+    panels: PanelInfo[],
+    selectedPanel: string,
+    defaultPanel: string
+  ) {
     return panels.map((panel) =>
       this._renderPanel(
         panel.url_path,
-        panel.url_path === this.hass.defaultPanel
+        panel.url_path === defaultPanel
           ? panel.title || this.hass.localize("panel.states")
```
Comment (bramkragten) [inline src/components/ha-sidebar.ts:442]: Not sure we need to do this, but, not really related to this PR

Comment (piitaya) [reply src/components/ha-sidebar.ts:442]: I will look to clean the logic about the default panel. I found very weird logic about this 🤣 The name and icon are not computed the same way in sidebar/dashboards config and navigation picker.
