### PR TITLE
[Bug] Do not overwrite the content of JSONTextField while the user is editing such

### LINKED ISSUE #816: Content of JSON fields gets overwritten while typing
While editing existing data in a field containing JSON data, such as the "Service Data" field within an action on the automation editor or script editor, **in a manner where the field momentarily becomes invalid JSON, such as when hand typing in a second parameter** the content of the field is periodically overwritten with the original contents, making certain edits impossible without copying the JSON out to an external editor, making a change, and copying it back.

For example: I with this initial value, I could successfully change the brightness to 190, but would not be able to add an entity_id parameter.
{
  "brightness": 180
}

Looking at the code, this issue appears to be constrained exclusively to JSONTextArea and its onChange action, where the validity of the JSON input is checked, however I was not successful at the moment of tracking it down to a specific line due to my lack of familiarity with Polymer.

### PR DESCRIPTION
**Pull request by nkaminski**
Closes #816 

This change prevents the value of the JSONTextField object from being overwritten when a render is triggered while the content is invalid JSON (such as when the user is editing such!), and therefore not stored in the JSONTextField's props object.

### CODE REVIEW

File: js/panel-config/json_textarea.js [hunk 1]
```diff
@@ -32,10 +32,12 @@ export default class JSONTextArea extends Component {
   }
 
   componentWillReceiveProps({ value }) {
```
Comment (balloob) [inline js/panel-config/json_textarea.js]: I don't think that this is a good fix as it means that unsaved changes can still get overwritten if they are valid JSON.

The correct approach is to only change the state if the passed in value has changed from the previous value.

```js
if (value === this.props.value) return;
```

Comment (nkaminski) [reply js/panel-config/json_textarea.js]: Thanks for the advice! I have reworked this change as per your suggestion. 

However just so you are aware, I was not able to reproduce a case where valid JSON would get overwritten, even with the original implementation. Any insight as to why (purely out of curiosity)?.

Comment (balloob) [reply js/panel-config/json_textarea.js]: Oh, I think I know why that is the case. The moment it is valid, we call `this.props.onChange(parsed);`, which means that the parent is notified of the new value. Home Assistant will store the new value and pass it down again, making sure it persists.

**Review by balloob — APPROVED** [review]
