### PR TITLE
Fix ha-dropdown z-index for legacy browsers

### LINKED ISSUE #29172: More actions (ha-dropdown) pop-up doesn't have focus (also maybe theme control missing?)
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The more actions/info pop-up when editing or creating an Automation doesn't seem to have focus: it looks transparent and you can't click on any of the items (even with default theme).

Also, the items in the list seem to ignore theming (unless i'm missing something - are there variables which control the text)?

It's a problem in several others area of the UI as well (among others, creating a new script has the same problem as automations).  Looking around, I was surprised it find it works properly when creating a new scene (http://<IP>:8123/config/scene/edit/new).  

Can't click on anything in the list on the right.  It's like it isn't on top:
Image

### Describe the behavior you expected

a. To be able to click some of the entries 
b. To be able to theme the entries

### Steps to reproduce the issue

1. Navigate to http://192.168.2.22:8123/config/automation/dashboard
2. Click on any existing automation, or create a new one
3. Click the 3 dots in the upper right corner

### What version of Home Assistant Core has the issue?

2026.1.3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

The main difference I see is "activatable" is present on the code for the scene creating, where it works.  Is that the correct fix for the broken places (automation and script tabs, and elsewhere)?

Image

### LINKED ISSUE #29983: Three dots menus are broken in web interface
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

There is a problem with the three-dot menus (sandwich menu). I was hoping this bug would be discovered/reported by others and fixed by now, but after 3-5 updates it's still there and it's very annoying. :)

The menu is either open on top, but impossible to select anything from it.
Or interspersed with other elements of the web page and when you try to select something the action is done on the elements below the menu.
Or hidden somewhere under other elements and impossible to see or use.

I use the latest version of HA:
Core 2026.3.0
Supervisor 2026.02.3
Operating System 17.1
Frontend 20260304.0 · legacy 

I used Firefox, Brave and Chrome on multiple computers and with the same results.

### Describe the behavior you expected

HA->Settings-> ⋮ is working as expected and all the rest should be fixed following this model.

### Steps to reproduce the issue

You can easily reproduce it, but don't maximize the window on a large monitor so the items are closer together.

HA->Settings-> Home Assistant Cloud ->  ⋮
You can't select anything with the mouse from that menu

HA->Settings->Devices/Areas ->  ⋮
The menu is open behind all other elements and is impossible to use, also Group by or Sort by is open somewhere in between the HTML elements and when you try to select something it will always selects the elements behind the menu

HA->Settings-> Devices ->  [Devices tab] -> [any device] -> [any sensor] ->  ⋮
The menu is shown, but you can't select any element from it with your mouse.

Those are just a few examples, but this problem is all over the web interface.

Image
Image
Image
Image
Image

### What version of Home Assistant Core has the issue?

2026.3.0

### What was the last working version of Home Assistant Core?

2025.???

### In which browser are you experiencing the issue?

FF, Chrome, Brave

### Which operating system are you using to run this browser?

Windows 10, 7

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### LINKED ISSUE #30065: Select dropdown list is behind other cards
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I’m using standard select helpers of which the dropdown lists pop under other entities / cards. This behaviour is since HA version 2026.3.0. In previous HA versions the select entities worked fine without problems.
When I rollback to 2026.2.3 all works fine. When I update to 2026.3.0 the issue is there again.

One remarkable thing is that the problem occurs depending on the vertical position of the select entity on the page, also see pictures below:
- if the select dropdown list is opened below the select entity, it disappears behind other elements and it’s not possible to make a selection from the list.
- if the select dropdown list is opened above the select entity, it works fine as it should (does not pop under).

Dropdown list pops up below the select entity:
Image

Dropdown list pops up above the select entity:
Image

Looks like this could be fixed easily. 

On my windows 11 computer I don’t have any issues with the select entities dropdowns.
On my tablet with Android 16 also no issues.

### Describe the behavior you expected

The select dropdown list should appear on top of other cards / entities.

### Steps to reproduce the issue

1. Create a couple of select helpers with e.g. 5 items each
2. Create a new tab and add the select entities to a entity card
3. Open the new tab in HA
4. Click on the first select entity 
5. Check the behaviour of the dropdown list, it opens under the next select entities  
...

### What version of Home Assistant Core has the issue?

2026.3.0

### What was the last working version of Home Assistant Core?

2026.2.3 

### In which browser are you experiencing the issue?

Edge, Firefox, Chrome, Safari 

### Which operating system are you using to run this browser?

iPad with ios 16.7.14 and 16.7.15 (updated on March 13th 2026).

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
- title: DSMR
    path: tab8
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: DSMR logging
            show_header_toggle: false
            entities:
              - select.dsmr_log_files
              - select.dsmr_log_dates
```

### JavaScript errors shown in your browser console/inspector

```txt
NA
```

### Additional information

NA

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change
- fix #29983
- fix #29172
- fix #30065

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/components/ha-dropdown.ts [hunk 1]
```diff
@@ -100,6 +100,9 @@ export class HaDropdown extends Dropdown {
         #menu {
           padding: var(--ha-space-1);
         }
+        wa-popup::part(popup) {
+          z-index: 1;
```
Comment (timmo001) [inline src/components/ha-dropdown.ts]: May need to go higher, chrome 109 (win 7 browserstack) 

Image

The labels are showing on top

Everywhere else looks good though

Comment (timmo001) [reply src/components/ha-dropdown.ts]: Actually might be specific to the entity id textfield

**Review by timmo001 — APPROVED** [review]

**Comment by BluffingJohn** [comment]
Thank you so much for fixing the issues!
Now all the drop-down menus are working as expected, but I found that this bug is still present in at least 3 other places.

> settings -> devices-> helpers -> element -> ...
> settings -> automations & scenes -> blueprints -> element ...
> settings -> dashboards -> element ...
> 

img1


img2


img3
