### PR TITLE
Localize durations using Intl.NumberFormat

### LINKED ISSUE #18013: Missing in Lokalise: automations related strings
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing words and phrases in Lokalise for translation

URL: /config/automation/edit/

Screenshot 2023-09-25 at 11-02-10 Paramètres – Home Assistant

Screenshot 2023-09-25 at 11-03-51 Paramètres – Home Assistant

Screenshot 2023-09-25 at 11-10-02 Paramètres – Home Assistant

Screenshot 2023-09-25 at 11-12-35 Paramètres – Home Assistant

### Describe the behavior you expected

Missing words and phrases should be in Lokalise.

### Steps to reproduce the issue

1. Switch to an other language than English
2. Go to Automations

YAML:
```
platform: numeric_state
entity_id: sensor.open_air_mini_rpm
for:
  hours: 0
  minutes: 1
  seconds: 0
below: 5
above: 10
```

```
condition: numeric_state
entity_id: weather.forecast_maison
attribute: temperature
above: 23
```

```
delay:
  hours: 0
  minutes: 0
  seconds: 10
  milliseconds: 0
```

```
delay:
  hours: 0
  minutes: 0
  seconds: 0
  milliseconds: 5
```

### What version of Home Assistant Core has the issue?

Home Assistant 2023.9.2 Interface utilisateur : 20230911.0 - latest 

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change
Localize durations using Intl.NumberFormat 
It's not entirely clear why some statements are displayed as "04:05:06" instead of 4 hours, 5 minutes and 6 seconds.  

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #18013 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/common/datetime/format_duration.ts [hunk 1]
```diff
@@ -1,16 +1,23 @@
...
   const m = duration.minutes || 0;
   const s = duration.seconds || 0;
   const ms = duration.milliseconds || 0;
 
   if (d > 0) {
-    return `${d} day${d === 1 ? "" : "s"} ${h}:${leftPad(m)}:${leftPad(s)}`;
+    return `
+      ${hass.localize("ui.duration.day", { count: d })}
+      ${h}:${leftPad(m)}:${leftPad(s)}
+    `;
```
Comment (KTibow) [inline src/common/datetime/format_duration.ts:20]:
```suggestion
    return hass.localize("ui.duration.day", { count: d }) + `${h}:${leftPad(m)}:${leftPad(s)}`;
```

File: src/common/datetime/format_duration.ts [hunk 2]
```diff
@@ -19,10 +26,10 @@ export const formatDuration = (duration: HaDurationData) => {
     return `${m}:${leftPad(s)}`;
   }
   if (s > 0) {
-    return `${s} second${s === 1 ? "" : "s"}`;
+    return `${hass.localize("ui.duration.second", { count: s })}`;
```
Comment (KTibow) [inline src/common/datetime/format_duration.ts:29]:
```suggestion
    return hass.localize("ui.duration.second", { count: s });
```

File: src/common/datetime/format_duration.ts [hunk 3]
```diff
@@ -19,10 +26,10 @@ export const formatDuration = (duration: HaDurationData) => {
...
   }
   if (ms > 0) {
-    return `${ms} millisecond${ms === 1 ? "" : "s"}`;
+    return `${hass.localize("ui.duration.millisecond", { count: ms })}`;
```
Comment (KTibow) [inline src/common/datetime/format_duration.ts:32]:
```suggestion
    return hass.localize("ui.duration.millisecond", { count: ms });
```

**Review by bramkragten — DISMISSED** [review]

File: src/common/datetime/format_duration.ts (hunk 1 above)
Comment (bramkragten) [reply src/common/datetime/format_duration.ts]: We generally prefer template strings above concatenation, it is easier to read and causes less mistakes (like you forgot the space between day and hours there)

**Comment by bramkragten** [comment]
We can btw also use something like this: 
```ts
Intl.NumberFormat("en", {
    style: "unit",
    unit: "second",
    unitDisplay: "long",
  }).format(23)
  ```
  ->
  `23 seconds`

**Comment by bramkragten** [comment]
Or even in the localization we want to (we dont 😄 ):

`{seconds, number, :: unit-width-full-name unit/second}`

File: src/common/datetime/format_duration.ts (hunk 1 above)
Comment (KTibow) [reply src/common/datetime/format_duration.ts]: Yeah but the original has a load of whitespace, what if it gets passed to somewhere that doesn't do whitespace collapsing?

File: src/common/datetime/format_duration.ts [hunk 4]
```diff
@@ -1,23 +1,21 @@
...
   const m = duration.minutes || 0;
   const s = duration.seconds || 0;
   const ms = duration.milliseconds || 0;
 
   if (d > 0) {
-    return (
-      hass.localize("ui.duration.day", { count: d }) +
-      ` ${h}:${leftPad(m)}:${leftPad(s)}`
-    );
+    return `${Intl.NumberFormat("en", {
```
Comment (bramkragten) [inline src/common/datetime/format_duration.ts]: Can we pass the locale of the user?

Comment (bramkragten) [reply src/common/datetime/format_duration.ts]: And move it to format date/format time

Comment (silamon) [reply src/common/datetime/format_duration.ts]: I think you may have reviewed the wrong commit. User locale is already passed in.

File: src/panels/mailbox/ha-panel-mailbox.ts [hunk 5]
```diff
@@ -19,6 +19,7 @@ import { HomeAssistant } from "../../types";
 import { fireEvent } from "../../common/dom/fire_event";
 import { haStyle } from "../../resources/styles";
 import "../../components/ha-top-app-bar-fixed";
+import "../../resources/intl-polyfill";
```
Comment (bramkragten) [inline src/panels/mailbox/ha-panel-mailbox.ts:22]: To prevent having to manage this everywhere, we should just move the format function to a file that imports this.

**Review by bramkragten — APPROVED** [review]
