### PR TITLE
Fix race condition in translation loading

### LINKED ISSUE #7512: [Beta] Sidebar displays in lowercase when reloading from non-Lovelace page with sidebar expanded
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When the sidebar is expanded and the page is reloaded from a non-Lovelace page (e.g. Configuration, Logbook, etc.), the sidebar labels appear in lowercase or are missing entirely:

image

It displays correctly when reloading from a Lovelace page

image

This appears to be related to loading or applying of translations as, when switching to a different language in profile settings, the lowercase sidebar is still in English.

## Expected behavior

Should display sidebar correctly when reloading from any page.

## Steps to reproduce

1.  Expand sidebar
2. From Configuration page, reload page in browser - should see sidebar with lowercase labels (first screenshot)
2. Navigate to Lovelace dashboard
3. Reload again - correct sidebar should show (second screenshot)

## Environment

- Home Assistant release with the issue: 0.117.0b6
- Last working Home Assistant release (if known): 0.114
- Browser and browser version: Chrome 86.0.4240.80 
- Operating system: macOS Catalina 10.15.7

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### LINKED ISSUE #7596: Strings occasionally appear un-localized
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Sometimes strings in the sidebar appear as developer string names instead of properly localized strings. Screenshot from Safari on Mac OS X 10.15:

Screen Shot 2020-11-04 at 6 18 04 PM

## Expected behavior

Strings should appear in the correct language.

## Steps to reproduce

Inconsistent repro. All that is required is to load the home page.

I have reproduced in both Chrome and Safari.

## Environment

- Home Assistant release with the issue: 20201021.4
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Safari 14.0
- Operating system: Mac OS X 10.15

## Javascript errors shown in your browser console/inspector

None. However I did track this down to a race condition in how localized strings are loaded. When the bug reproduces, the appropriate strings are *missing* from the Hass object:

```txt
>> document.body.children[0].__hass.resources.en
{
  component.alexa.title: "Amazon Alexa"
  ...
  ... NOTE: no panel.developer_tools string is present.
}
```

## Additional information

Pull request forthcoming.

### PR DESCRIPTION
**Pull request by adamjernst**
I occasionally observed strings being rendered in un-localized form. Puzzling.

Missing localized strings screenshot

After some digging, I tracked it down to this race condition deep in the translations mixin.

- `panelUrlChanged` may be triggered before `hassConnected`; it even has a helpful comment saying so! This in turn calls `_loadFragmentTranslations`, which calls `_updateResources`.
- `firstUpdated` may also be triggered before `hassConnected`; it calls `_loadCoreTranslations`, which calls `_updateResources`.

If both resources finish loading before `hassConnected`, the second set of strings will completely overwrite the first!

The solution is to reach into the internals and grab `_pendingHass` if `this.hass` is unset. This feels sorta nasty, but I am not yet familiar enough with the codebase to attempt a more sweeping refactor. I might suggest following React's lead: just as [React's `setState` accepts a closure](https://reactjs.org/docs/react-component.html#setstate), `_updateHass` should accept a closure that passes you a non-null `HomeAssistant` instance, and you must return a new `HomeAssistant` computed from that base state (instead of using the nullable `this.hass`).

## Proposed change

Fixes #7596, #7512.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

# Additional information

- This PR fixes or closes issue: fixes #7596, fixes #7512
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/state/translations-mixin.ts [hunk 1]
```diff
@@ -221,9 +221,18 @@ export default <T extends Constructor<HassBaseEl>>(superClass: T) =>
...
+      //
+      // Beware of a subtle race condition: it is possible to get here twice
+      // before this.hass is even created. In this case our base state comes
+      // from this._pendingHass instead. Otherwise the first set of strings is
+      // overwritten when we call _updateHass the second time!
+      const baseHass = this.hass ?? this._pendingHass;
       const resources = {
+        // Spread any other language resources before adding the new one to
+        // avoid possible race conditions related to language switching.
+        ...baseHass?.resources,
```
Comment (adamjernst) [inline src/state/translations-mixin.ts:233]: No idea if there *is* such a race condition, but "hey let's throw away any other language data and assume `language` is the current language" seemed suspicious to me. Best to be safe, since there's no real cost to it here.

**Comment by kukulich** [comment]
It's probably fix for https://github.com/home-assistant/frontend/issues/7512 too.

File: src/state/translations-mixin.ts (hunk 1 above)
Comment (bramkragten) [reply src/state/translations-mixin.ts:233]: Let's move the check of line 240 up, so don't end up with all languages in memory, I don't think we need to update the resources if the language of the resources doesn't match the current language?

Comment (adamjernst) [reply src/state/translations-mixin.ts:233]: Sure. Let me tweak this.

**Comment by adamjernst** [comment]
@bramkragten In the interest of keeping this PR minimal and reviewable, I dropped the unrelated language race fix. I'll send a separate PR to tweak that later. Let's get this more important fix landed first.

**Review by bramkragten — APPROVED** [review]
