### PR TITLE
fix: null value error on ha-form-integer

### LINKED ISSUE #51349: Cannot enter Apple TV pin
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Cannot enter Apple TV pin

The UI does not show the text box to enter the apple tv paring code to proceed to the next step. 

### Describe the behavior you expected

Being able to enter pairing codes. 

### Steps to reproduce the issue

1. Click add new integration to Pair new apple TV
2. Try enter the airplay code on the TV
3. suffer!
...

### What version of Home Assistant Core has the issue?

2026.4.0

### What was the last working version of Home Assistant Core?

2026.3.0

### In which browser are you experiencing the issue?

Mobile app, Chromium browser, safari

### Which operating system are you using to run this browser?

IOS Mac OS

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

https://www.reddit.com/r/homeassistant/comments/1sa6pe1/cannot_enter_apple_tv_pin/

others with the same issue on reddit!

### PR DESCRIPTION
**Pull request by timia2109**
## Proposed change

This fix resolves the bug responsible for #51349. This problem was introduced in #30294 

## Type of change

Bugfixes for null values

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #51349, fixes https://github.com/home-assistant/core/issues/167129

## Checklist

- [x] I understand the code I am submitting and can explain how it works.
- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] I have followed the [perfect PR recommendations][perfect-pr]
- [x] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [x] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

**Comment by iluvdata** [comment]
This is a duplicate of #51390 which has already been added to a milestone release.

File: src/components/ha-form/ha-form-integer.ts [hunk 1]
```diff
@@ -100,7 +100,7 @@ export class HaFormInteger extends LitElement implements HaFormElement {
         inputMode="numeric"
         .label=${this.label}
         .hint=${this.helper}
-        .value=${this.data !== undefined ? this.data.toString() : ""}
+        .value=${this.data !== undefined ? this.data?.toString() : ""}
```
Comment (fareshan) [inline src/components/ha-form/ha-form-integer.ts]: This fixes the crash !

However, if `this.data === null`, we still end up with `value = undefined`.

Are we OK with that or do we prefer to normalize that to an empty string instead?

`.value=${this.data?.toString() ?? ""}`

Comment (bramkragten) [inline src/components/ha-form/ha-form-integer.ts]:
```suggestion
        .value=${this.data?.toString() ?? ""}
```

**Review by bramkragten — APPROVED** [review]

**Review by fareshan — COMMENTED** [review]
This fixes the crash !

However, if `this.data === null`, I think we still end up with `value = undefined`.

Are we OK with that or do we prefer to normalize that to an empty string instead?

`.value=${this.data?.toString() ?? ""}`
