### PR TITLE
Fix calendar date display and parsing issues

### LINKED ISSUE #14684: [local calendar]: Adding event to calendar in unknown timezone
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

While adding new event to calendar there's no indication in which timezone it will be saved. Local timezone of device? Timezone that configured in HA? UTC?

### Describe the behavior you expected

Add clear note about timezone or add timezone selector dropdown.

### Steps to reproduce the issue

1. Set device timezone to different from HA.
2. Open Local calendar integration.
3. Add event.
4. Try to set date/time.
...

### What version of Home Assistant Core has the issue?

core-2022.12.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Home assistant app

### Which operating system are you using to run this browser?

Android

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### LINKED ISSUE #14786: Calendar event properties dates off by one day
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When clicking an all-day event on the calendar that's from the Local Calendar integration, the start and end dates displayed on the event properties dialog are one day prior than the actual dates.

Calendar Event Properties Issue

Here's the local_calendar ICS content for the event in the screenshot above:

    BEGIN:VEVENT
    DTSTAMP:20221214T174139
    UID:90545bf6-7bd6-11ed-92ed-52540009e893
    DTSTART:20231001
    DTEND:20231007
    SUMMARY:Test
    CREATED:20221214T174139
    DESCRIPTION:
    SEQUENCE:0
    END:VEVENT

This occurs on both single-day and multi-day all day events.

### Describe the behavior you expected

The dates displayed on the event properties dialog match the actual event dates.

### Steps to reproduce the issue

1. Create a new all day (i.e., enable the All Day option) calendar event using the Local Calendar integration
2. Click the event on the calendar

### What version of Home Assistant Core has the issue?

core-2022.12.5

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Firefox 107.0.1 (x64)

### Which operating system are you using to run this browser?

Windows 10 21H2

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by allenporter**
## Proposed change

Fix calendar date display and parsing issues. The primary change is to always display dates in the browsers display timezone, so that it is consistent with dates in other surfaces (e.g. the calendar display, logbook, etc). The date input controls will work in terms of the browser timezone, then convert to the home assistant timezone when persisting the event.

Note: Event date/times are created without a timezone, using floating dates relative to the core timezone.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #14786 and fixes #14684
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/calendar/dialog-calendar-event-editor.ts [hunk 1]
```diff
@@ -60,6 +61,12 @@ class DialogCalendarEventEditor extends LitElement {
 
   @state() private _submitting = false;
 
+  // Dates are manipulated and displayed in the browser timezone
+  // which may be different from the Home Assistant timezone. When
+  // events are persisted, they are relative to the Home Assistant
+  // timezone, but floating without a timezone.
+  private _timeZone: string;
```
Comment (bramkragten) [inline src/panels/calendar/dialog-calendar-event-editor.ts:68]:
```suggestion
  private _timeZone?: string;
```

File: src/panels/calendar/dialog-calendar-event-editor.ts [hunk 2]
```diff
@@ -281,19 +289,35 @@ class DialogCalendarEventEditor extends LitElement {
...
+      startTime: this._formatTime(startDate),
+      endDate: this._formatDate(endDate),
+      endTime: this._formatTime(endDate),
+    }));
+
+  // Formats a date in specified timezone, or defaulting to browser display timezone
+  private _formatDate(date: Date, timeZone?: string): string {
+    return formatInTimeZone(
+      date,
+      timeZone || this.timeZone,
```
Comment (bramkragten) [inline src/panels/calendar/dialog-calendar-event-editor.ts:303]:
```suggestion
      timeZone || this._timeZone,
```

File: src/panels/calendar/dialog-calendar-event-editor.ts [hunk 3]
```diff
@@ -281,19 +289,35 @@ class DialogCalendarEventEditor extends LitElement {
...
-  );
+  private _getLocaleStrings = memoizeOne((startDate?: Date, endDate?: Date) => ({
+      startDate: this._formatDate(startDate),
+      startTime: this._formatTime(startDate),
+      endDate: this._formatDate(endDate),
+      endTime: this._formatTime(endDate),
+    }));
+
+  // Formats a date in specified timezone, or defaulting to browser display timezone
+  private _formatDate(date: Date, timeZone?: string): string {
```
Comment (bramkragten) [inline src/panels/calendar/dialog-calendar-event-editor.ts:300]:
```suggestion
  private _formatDate(date: Date, timeZone?: string = this._timeZone): string {
```

**Review by bramkragten — APPROVED** [review]
