### PR TITLE
Default to yaml editing when there are multiple states in condition

### LINKED ISSUE #6664: Automation editor clobbers multiple state conditions
## Checklist

- [ X ] I have updated to the latest available Home Assistant version.
- [ X ] I have cleared the cache of my browser.
- [ X ] I have tried a different browser to see if it is related to my browser.

## The problem

Release 0.112 added [multiple state support](https://www.home-assistant.io/docs/scripts/conditions/#state-condition) for conditions in Automations.

This is great, so I have many automations now that trigger if I'm in one of several modes. eg:
```yaml
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state:
      - Night
      - Home
```
However, if I load this automation in the UI, the UI reads it in and displays it as 
image

and if I save any change to any part of this automation in the UI, it clobbers the condtion and becomes:
```yaml
condition: state
entity_id: input_select.home_mode
state: 'Sleep,Night'
```

## Expected behavior

Can open and edit automation in UI with multiple states and have it save in the correct format ie:
```yaml
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state:
      - Night
      - Home
```
instead of 
```yaml
condition: state
entity_id: input_select.home_mode
state: 'Sleep,Night'
```

## Steps to reproduce

1. Edit Automations.yaml manually and create an automation with a condition with multiple states such as:
```yaml
- id: trigger_good_morning
  alias: 'Trigger: Good Morning'
  trigger:
  - entity_id: binary_sensor.master_closet_motion
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_select.home_mode
    state:
      - Sleep
      - Night
  action:
  - data: {}
    service: script.good_morning
  mode: single
```
2. Go to the UI and load the automation "Trigger: Good Morning"
3. Without changing anything, press save.

## Environment

- Home Assistant release with the issue: 0.114.3
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Firefox Version 78.0.2 (64-bit) and Chrome 84.0.4147.89 and mobile app
- Operating system: Windows and Android

## State of relevant entities

n/a

## Problem-relevant configuration

see steps to reproduce

## Javascript errors shown in your browser console/inspector

n/a

### PR DESCRIPTION
**Pull request by cnorick**
## Proposed change
Before, when editing an automation containing a condition with an array of states, the UI would convert them to a comma-separated list. Now, instead of trying to parse the array as a string, we default to yaml mode and show an error.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

automations.yaml
```yaml
- id: trigger_good_morning
  alias: 'Trigger: Good Morning'
  trigger:
  - entity_id: binary_sensor.master_closet_motion
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id:
    - person.nathan
    attribute: friendly_name
    state:
    - Home
    - Away
  action:
  - data: {}
    service: script.good_morning
  mode: single
```

## Additional information
@bramkragten, this is a followup to your comment in #10384.

- This PR fixes or closes issue: fixes #6664 #10473
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Follow up to #10384 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Demo
yaml-mode

### CODE REVIEW

File: src/panels/config/automation/condition/types/ha-automation-condition-state.ts [hunk 1]
```diff
@@ -22,6 +23,25 @@ export class HaStateCondition extends LitElement implements ConditionElement {
...
+  protected shouldUpdate(changedProperties: PropertyValues): boolean {
+    if (
+      changedProperties.has("condition") &&
+      this._stateIsArray(this.condition)
+    ) {
+      if (this._stateIsArray(this.condition)) {
+        fireEvent(
+          this,
+          "ui-mode-not-available",
+          Error(this.hass.localize("ui.errors.config.editor_not_supported"))
```
Comment (cnorick) [inline src/panels/config/automation/condition/types/ha-automation-condition-state.ts:35]: Should I add another more specific error here? Maybe something like "State arrays not supported in the visual editor"

Comment (bramkragten) [reply src/panels/config/automation/condition/types/ha-automation-condition-state.ts:35]: Yes, I think we should

File: src/panels/config/automation/condition/types/ha-automation-condition-state.ts [hunk 2]
```diff
@@ -22,6 +23,25 @@ export class HaStateCondition extends LitElement implements ConditionElement {
     return { entity_id: "", state: "" };
   }
 
+  protected shouldUpdate(changedProperties: PropertyValues): boolean {
+    if (
+      changedProperties.has("condition") &&
+      this._stateIsArray(this.condition)
+    ) {
+      if (this._stateIsArray(this.condition)) {
```
Comment (bramkragten) [inline src/panels/config/automation/condition/types/ha-automation-condition-state.ts:31]: We do this check twice now, you can remove the second one

File: src/panels/config/automation/condition/types/ha-automation-condition-state.ts [hunk 3]
```diff
@@ -22,6 +23,25 @@ export class HaStateCondition extends LitElement implements ConditionElement {
     return { entity_id: "", state: "" };
   }
 
+  protected shouldUpdate(changedProperties: PropertyValues): boolean {
```
Comment (bramkragten) [inline src/panels/config/automation/condition/types/ha-automation-condition-state.ts:26]: This should be done in `willUpdate` and not in `shouldUpdate`

File: src/panels/config/automation/condition/types/ha-automation-condition-state.ts [hunk 4]
```diff
@@ -67,6 +87,10 @@ export class HaStateCondition extends LitElement implements ConditionElement {
   private _valueChanged(ev: CustomEvent): void {
     handleChangeEvent(this, ev);
   }
+
+  private _stateIsArray(condition: StateCondition): boolean {
+    return Array.isArray(condition?.state);
+  }
```
Comment (bramkragten) [inline src/panels/config/automation/condition/types/ha-automation-condition-state.ts:93]: This is not really needed as a class function, just inline the check

**Comment by bramkragten** [comment]
Eventually I would like to do this like we do for Lovelace, using Superstruct:

https://github.com/home-assistant/frontend/blob/dev/src/panels/lovelace/editor/config-elements/hui-calendar-card-editor.ts#L24-L32

**Comment by cnorick** [comment]
@bramkragten, are we waiting for something to merge this one?

**Review by bramkragten — APPROVED** [review]
