### PR TITLE
Expand groups in entitry row to check toggle

### LINKED ISSUE #6599: group with nested groups shows toggle instead of state home/not_home
## The problem

a group containing only other groups shows a toggle (which is useless) instead of home/not_home. All contained groups are of the home/not_home type, since they contain device_trackers of mobile devices/persons etc.

desired solution: have these groups show home/not_home

## Environment

- Home Assistant Core release with the issue:  113.3
- Last working Home Assistant Core release (if known): not sure, but think never
- Operating environment (OS/Container/Supervised/Core):  OS
- Integration causing this issue: group
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/group/

## Problem-relevant `configuration.yaml`

```yaml
# for the group
  family_home:
    name: Familie Home
    icon: mdi:home-heart
    entities:
      - group.daughter_1
      - group.daughter_2
      - group.daughter_3
      - group.daughter_4
      - group.she
      - group.me

# lovelace card:
 - type: entities
    title: At home
    entities:
    #####
      - entity: group.family
        secondary_info: last-changed
      - entity: group.family_home
        secondary_info: last-changed
```

## Traceback/Error logs

NO errors
```txt

```

## Additional information
the first group contains individual entitities, the second contains the groups, 
Schermafbeelding 2020-08-03 om 23 07 09

which individually do show their correct state in the more-info of the group, as does the group itself:

Schermafbeelding 2020-08-03 om 23 07 29

clicking the toggle is ineffective because an error is displayed it cant find a service device_tracker/turn_on, which is correct of course. and, though the toggle does change position, the entity doesnt change state.

### LINKED ISSUE #6925: Nested Groups of Persons display toggle
## Checklist

- [x] I have cleared the cache of my browser.
- [x] I have updated to the latest available Home Assistant version.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When a nested group of persons is created, the second order group is not appear to render correctly as an entities card. Instead of showing the status, a toggle is shown. It the details view it is shown correctly. In an entity card (as opposed to 'entities'), it appears to display correctly. When activating the toggle a failed service call is displayed.

image
image
image
image

## Expected behavior
No toggle on entity and no toggle on whole card. Display home/away status.

## Steps to reproduce

1. Create group of persons
2. Create second group, nesting the first group
3. Add lovelace entity/entities card

## Environment

- Home Assistant release with the issue: 0.110-0.113
- Last working Home Assistant release (if known): None
- Browser and browser version: Chrome/Firefox all recent versions
- Operating system: n/a

## State of relevant entities

Issue occurs irrelevent of home/away state.
```yaml


```

## Problem-relevant configuration

```yaml
residents:
  name: Residents
  entities:
    - person.one
    - person.two
known_people:
  name: Known People
  entities:
    - group.residents
    - person.three
```

## Javascript errors shown in your browser console/inspector

```txt
n/a
```

## Additional information
Unresolved topic in forum here: https://community.home-assistant.io/t/nested-group-of-persons/210312

### PR DESCRIPTION
**Pull request by ludeeus**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #6925 fixes #6599
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/entity-rows/hui-group-entity-row.ts [hunk 1]
```diff
@@ -22,6 +23,21 @@ class HuiGroupEntityRow extends LitElement implements LovelaceRow {
 
   @internalProperty() private _config?: EntityConfig;
 
+  private _computeCanToggle = memoizeOne(
+    (hass: HomeAssistant, entityIds: string[]): boolean => {
+      return entityIds.some((entityId) => {
+        const domain = entityId.split(".", 1)[0];
```
Comment (bramkragten) [inline src/panels/lovelace/entity-rows/hui-group-entity-row.ts:29]:
```suggestion
        const domain = computeDomain(entityId);
```

**Review by bramkragten — APPROVED** [review]

File: src/panels/lovelace/entity-rows/hui-group-entity-row.ts [hunk 2]
```diff
@@ -22,6 +23,21 @@ class HuiGroupEntityRow extends LitElement implements LovelaceRow {
 
   @internalProperty() private _config?: EntityConfig;
 
+  private _computeCanToggle = memoizeOne(
+    (hass: HomeAssistant, entityIds: string[]): boolean => {
```
Comment (bramkragten) [inline src/panels/lovelace/entity-rows/hui-group-entity-row.ts:28]: Just see you made a memoize from it, but you pass `hass`, that means it will still update on every state change.

Comment (ludeeus) [reply src/panels/lovelace/entity-rows/hui-group-entity-row.ts:28]: True...
