### PR TITLE
Corrects add-on link

### LINKED ISSUE #4623: Links to add-ons are broken
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

All links to the external add-on pages are broken, an additional `"` is on the end of the URL.

image

⚠️ Additionally, the space character after the link text seems to be linked as well (really minor, but 🤷‍♂)

## Expected behavior

Working links 😄 

## Steps to reproduce

Open up any add-on, click on the add-on link right under the add-on description.

## Environment

- Home Assistant release with the issue: 0.104.3 / Supervisor 196 (dev)
- Last working Home Assistant release (if known): Supervisor 195
- UI Type (States or Lovelace): n/a
- Browser and browser version: Version 79.0.3945.117 (Official Build) (64-bit)
- Operating system: macOS Mojave

## Problem-relevant configuration

```yaml
n/a
```

## Javascript errors shown in your browser console/inspector

```txt
Nothing.
```

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

Fixes addon link ⛓ 

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
For the most part yaml is not really needed here is it?
```

## Additional information

- This PR fixes or closes issue: fixes #4623
- This PR is related to issue: Nope
- Link to documentation pull request: Nope

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.

How? Why? Examples, please.
- [ ] Tests have been added to verify that the new code works.

***

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by ludeeus** [comment]
Why this changed so much is beyond me, some pre-commit hook going haywire 🤷‍♂

**Comment by balloob** [comment]
Prettier doing a new style formatting it seems. We should make sure that pre-commit and our CI/yarn use the same.

File: hassio/src/addon-view/hassio-addon-info.ts [hunk 1]
```diff
@@ -183,7 +183,7 @@ class HassioAddonInfo extends LitElement {
           <div class="description light-color">
             ${this.addon.description}.<br />
             Visit
-            <a href=${this.addon.url} target="_blank">
+            <a href="${this.addon.url}" target="_blank">
```
Comment (balloob) [inline hassio/src/addon-view/hassio-addon-info.ts]: This is not necessary because it's dynamic.
