### PR TITLE
Fix datetime handling in energy charts

### LINKED ISSUE #28342: Power Source Chart cut off at around 23:00
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The power source (Stromquellen) chart is cut of at around 23:00. In Summary and Now tab
Image
Tested in firefox and chromium

ignore the wrong battery data. it's already mentioned here:
https://github.com/orgs/home-assistant/discussions/1904

### Describe the behavior you expected

See the full 24 hours

### Steps to reproduce the issue

1. Go to energy/overview or energy/now
2. have power entities configured
3. see chart

### What version of Home Assistant Core has the issue?

2025.12.0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Fix end datetime for energy charts. This was not visible on the other charts because they only show hourly data but the new power chart shows more detail.

Also changed the current state to only be added when viewing today. It wasn't a problem because it is just cut off when it's not in the selected period but this is cleaner.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #28342
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/energy/common/energy-chart-options.ts [hunk 1]
```diff
@@ -40,12 +40,13 @@ export function getSuggestedMax(dayDifference: number, end: Date): number {
     suggestedMax = subHours(suggestedMax, 1);
   }
 
-  suggestedMax.setMinutes(0, 0, 0);
```
Comment (karwosts) [inline src/panels/lovelace/cards/energy/common/energy-chart-options.ts:43]: I'm not quite making the connection between the reason for this change and the described bug this is trying to fix. 

Can you add a comment why we don't want to set minutes to 0 for single-day chart?

File: src/panels/lovelace/cards/energy/common/energy-chart-options.ts [hunk 2]
```diff
@@ -40,12 +40,13 @@ export function getSuggestedMax(dayDifference: number, end: Date): number {
...
   if (dayDifference > 35) {
     suggestedMax.setDate(1);
+    suggestedMax.setMinutes(0, 0, 0);
```
Comment (karwosts) [inline src/panels/lovelace/cards/energy/common/energy-chart-options.ts]: Is this redundant with line 49? If dayDifference is > 35, then it must also be >2, which guarantees that the next if block will also execute and set the minutes. 

It's if/if not if/elseif.

File: src/panels/lovelace/cards/energy/common/energy-chart-options.ts (hunk 1 above)
Comment (MindFreeze) [reply src/panels/lovelace/cards/energy/common/energy-chart-options.ts:43]: The problem is that the end time is 23:59:59 . This set it to 23:00:00 . It wasn't a problem for bar charts because they just show the whole hour starting from 23:00 . The new power graph is not hourly though and `suggestedMax.setMinutes(0, 0, 0)` cuts it off at 23:00 when looking at a single day.

Comment (karwosts) [reply src/panels/lovelace/cards/energy/common/energy-chart-options.ts:43]: So thinking back to the bar charts, why did the bar charts care if the suggestedMax is 23:00 or 23:59? Was there a reason we do this here?

This seems like it will also change the behavior of a 1-day bar chart, does that still need to be 23:00?

Should we just add some `type != bar` logic instead, to reduce the scope of the change?

Comment (MindFreeze) [reply src/panels/lovelace/cards/energy/common/energy-chart-options.ts:43]: I think I found the reason. With 23:59, the bar charts leave a space for another bar at the end. Maybe there are other issues then so, yeah, we should check the chart type. I'll add some logic
image

File: src/panels/lovelace/cards/energy/common/energy-chart-options.ts [hunk 3]
```diff
@@ -40,12 +40,12 @@ export function getSuggestedMax(dayDifference: number, end: Date): number {
...
-  if (dayDifference > 35) {
-    suggestedMax.setDate(1);
-  }
   if (dayDifference > 2) {
     suggestedMax.setHours(0);
+    suggestedMax.setMinutes(0, 0, 0);
+    if (dayDifference > 35) {
+      suggestedMax.setDate(1);
+    }
   }
```
Comment (piitaya) [inline src/panels/lovelace/cards/energy/common/energy-chart-options.ts]:
```suggestion
if (dayDifference > 35) {
    suggestedMax.setDate(1);
}
if (dayDifference > 2) {
    suggestedMax.setHours(0);
    suggestedMax.setMinutes(0, 0, 0);
}
```
Flatten conditions we don't have nested conditions (easier to read)

Comment (MindFreeze) [reply src/panels/lovelace/cards/energy/common/energy-chart-options.ts]: It's not easier for me but alright

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
