### PR TITLE
Fix history charts not auto refreshing with cached history

### LINKED ISSUE #12859: history-graph card doesn't auto update with new values since 2022.06.0
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Having a dashboard with a history-graph card usually updated automatically with any new value. Now it doesn't until you refresh the page.

My specific example is a custom energy graph that shows the last 3 hours of energy production / consumption. I usually have it opened on a secondary monitor to keep an eye on it. Now I need to reload the page to see the updated graph.

It's always been with `refresh_interval` not set (so default 0). I assume that meant update on new values. Anyway I tried setting a interval value (e.g. 60 seconds) but the issue remains (no updates at all).

### Describe the behavior you expected

The graph should update with new values.

### Steps to reproduce the issue

1. Create a history-card with some sensor that changes frequently enough (e.g. 1 minute)
2. Wait until there's enough new data
3. It doesn't show the updated graph
...

### What version of Home Assistant Core has the issue?

2022.6.1

### What was the last working version of Home Assistant Core?

2022.5.x

### In which browser are you experiencing the issue with?

Firefox 101.10 / Brave 1.39.111 (Chromium 102.0.5005.61) 

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt
entity: sensor.solar_production
state: 146
attrs:
 state_class: measurement
 unit_of_measurement: W
 device_class: power
 icon: mdi:solar-power
 friendly_name: solar_production
```

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: sensor.solar_production
hours_to_show: 1
```

### Javascript errors shown in your browser console/inspector

```txt
No errors shown.
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bdraco**
## Proposed change

The git archaeology on this is very difficult to sort out. Best I can tell: while fixing the history caching in https://github.com/home-assistant/frontend/pull/12788 made the cache work now (so we aren't constantly overloading the backend with history requests), it also re-introduced a regression similar to #2061 . I'm not sure that original issue was completely fixed, but the working theory is that since the history cache was no longer effective after #7072 it had the effect of solving it and fixing the history cache reintroduced the regression.

Fixes #12859

Unrelated to this PR, but I think `getRecent`  (not `getRecentWithCache`) is dead code AFAICT.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/data/cached-history.ts [hunk 1]
```diff
@@ -158,8 +158,14 @@ export const getRecentWithCache = (
...
     if (appendingToCache) {
-      mergeLine(stateHistory.line, cache.data.line);
-      mergeTimeline(stateHistory.timeline, cache.data.timeline);
+      if (stateHistory.line.length) {
+        mergeLine(stateHistory.line, cache.data.line);
+      }
+      if (stateHistory.timeline.length) {
+        mergeTimeline(stateHistory.timeline, cache.data.timeline);
+        // Replace the timeline array to force an update
+        cache.data.timeline = [...cache.data.timeline];
```
Comment (bdraco) [inline src/data/cached-history.ts:167]: Since mutating the array doesn't trigger the update I did this to force it.  Is there a better way?

File: src/data/cached-history.ts [hunk 2]
```diff
@@ -191,6 +197,8 @@ const mergeLine = (
           oldLine.data.push(entity);
         }
       });
+      // Replace the cached line data to force an update
+      oldLine.data = [...oldLine.data];
```
Comment (bdraco) [inline src/data/cached-history.ts:201]: Since mutating the array doesn't trigger the update I did this to force it.  Is there a better way?

File: src/data/cached-history.ts (hunk 1 above)
Comment (balloob) [reply src/data/cached-history.ts:167]: I would expect `mergeLine` and `mergeTimeline` to create new arrays.

Comment (balloob) [reply src/data/cached-history.ts:167]: `cache.data.timeline = mergeTimeline(stateHistory.timeline, cache.data.timeline);`

Comment (bdraco) [reply src/data/cached-history.ts:167]: That didn't work out very well unfortunately since the update is a partial update and the current code enumerates the new data so if the entity didn't update in history call it disappears.

File: src/data/cached-history.ts (hunk 2 above)
Comment (bdraco) [reply src/data/cached-history.ts:201]: This one is even more complex since its arrays in arrays and it has the same issue of only enumerating the new data

File: src/data/cached-history.ts (hunk 1 above)
Comment (bdraco) [reply src/data/cached-history.ts:167]: I ended up reverting the last commit because I think its too risky to refactor without adding a whole lot of tests.

**Comment by bdraco** [comment]
Not sure how to proceed on this one. I reverted the last commit since they hit my risk tolerance for a bug fix.

**Review by balloob — APPROVED** [review]

**Comment by balloob** [comment]
meh looking at this code and it's indeed confusing. 

Do we even need caching ? It seems like if we are showing a more-info, we always want to show latest, and if a user is bouncing between tabs it can be locally cached, not at the top-level.

**Comment by bdraco** [comment]
I think we only need caching for the case where they have a whole page of history graph cards which I'm learning is apparently a more common use case than expected. 😢
