### PR TITLE
Fix for integration 'Add entry' unnecessary dialogs

### LINKED ISSUE #23780: Adding a new integration entry causes displaying wrong popups before a proper popup appears
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Sorry for a confusing title, cannot find a proper terminology.
Assume we need to add a new integration entry:
1. Go to "Settings -> Devices & Services".
2. Select some integration.
3. Add a new entry.
4. Another popups may be quickly displayed before a proper popup appears:
Image

### Describe the behavior you expected

Only one needed popup is opened.

### Steps to reproduce the issue

see above

### What version of Home Assistant Core has the issue?

2025.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Chrome 132.0.6834.84 

### Which operating system are you using to run this browser?

Win10x64

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by phiychai**
## Proposed change
 Show correct dialogs when adding a new entry in integrations.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #23780 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by MindFreeze — APPROVED** [review]
Thanks

File: src/panels/config/integrations/dialog-add-integration.ts [hunk 1]
```diff
@@ -97,22 +97,26 @@ class AddIntegrationDialog extends LitElement {
...
-    this._pickedBrand = params?.brand;
-    this._initialFilter = params?.initialFilter;
-    this._narrow = matchMedia(
-      "all and (max-width: 450px), all and (max-height: 500px)"
-    ).matches;
     if (params?.domain) {
-      this._createFlow(params.domain);
+      // Just open the config flow dialog, do not show this dialog
+      await this._createFlow(params.domain);
+      return;
```
Comment (bramkragten) [inline src/panels/config/integrations/dialog-add-integration.ts:103]: We should actually call `closeDialog` here, as the history stack is not properly cleaned now and we didn't fire the `dialog-closed` event.

**Comment by karwosts** [comment]
FYI I have proposed a revert of this change because it caused quite a significant break in the add integration dialog flow, that's been a festering problem for many users for some time.

Please comment at https://github.com/home-assistant/frontend/pull/29101 if you would like, thanks.  @phiychai
