### PR TITLE
Check for entity state and entity string in conditional card

### LINKED ISSUE #20304: Breaking change in PR#19182
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

https://github.com/home-assistant/frontend/pull/19182 introduced being able to compare an entitiy's state to another entity's state but that breaks being able to compare an entity's state to a entity_id string of an existing entity.

```
type: conditional
conditions:
  - condition: state
    entity: input_text.media_player
    state: media_player.onkyo_dlna
card:
...
```

This conditional card would show when `input_text.media_player` had a state of the STRING "media_player.onkyo_dlna". With https://github.com/home-assistant/frontend/pull/19182 this does not work anymore as "media_player.onkyo_dlna" is now a reference to the state of the entity "media_player.onkyo_dlna".

### Describe the behavior you expected

I expected this PR to not introduce breaking changes or being able to specify if the expected state is an entity or a string.

### Steps to reproduce the issue

1. create helper `input_text.temp`
2. set value of helper to the name of an existing entity (e.g. `sensor.some-other-sensor`)
3. create a conditional card and filter on state of `input_text.temp` being the STRING `sensor.some-other-sensor`
4. the conditional card will not be shown as state of `input_text.temp` does not equal the state of `sensor.some-other-sensor`

### What version of Home Assistant Core has the issue?

core-2024.4.0b3

### What was the last working version of Home Assistant Core?

core-2024.3.3

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/20304
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/common/validate-condition.ts [hunk 1]
```diff
@@ -103,10 +106,10 @@ function checkStateNumericCondition(
 
   // Handle entity_id, UI should be updated for conditionnal card (filters does not have UI for now)
   if (typeof above === "string") {
-    above = getValueFromEntityId(hass, above) as string;
+    above = getValueFromEntityId(hass, above) ?? above;
   }
   if (typeof below === "string") {
-    below = getValueFromEntityId(hass, below) as string;
+    below = getValueFromEntityId(hass, below) ?? above;
```
Comment (silamon) [inline src/panels/lovelace/common/validate-condition.ts:112]:
```suggestion
    below = getValueFromEntityId(hass, below) ?? below;
```

**Comment by piitaya** [comment]
Thank you @silamon !

**Review by frenck — APPROVED** [review]
Thanks, @piitaya 👍 

../Frenck
