### PR TITLE
Fix time and date-time 12h formats  (#16692)

### LINKED ISSUE #16692: Time displays incorrectly throughout Home Assistant when in 12hr clock format.
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When the global time setting in Home Assistant is set to 12-hr it displays all times of the day correctly using AM/PM, with the only exception being midday. At midday Home Assistant displays the time as 0:58:28 pm, as seen here in the logbook: 
image

### Describe the behavior you expected

Expected behaviour would be to display the time as 12:58:28 pm in the example above, and changing all midday & midnight times to display as 12 instead of 0.

### Steps to reproduce the issue

1. Change time to 12hrs (AM/PM) in Profile -> Time Format
2. View the time at midday or midnight on any screen (I used the logbook for example, but History or other places also contain the issue)

### What version of Home Assistant Core has the issue?

core-2023.5.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by christophwen**
- am/pm check possible for other languages
- adjusted date format gallery page for consistency
- added gallery pages for date-time and time formats

## Proposed change

Problem: Time in the 12h format shows 0:15 PM instead of 12:15PM #16692 
Wanted: correct 12h format
Solution: Added correct hour cycle to formatting functions

Additionally adapted check if am/pm is the default for a given language the other supported languages which don't use "AM"/"PM".

Adapted gallery pages for the numeric date format to be consistent with the new pages (date-time and time formats).

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

To verify the changes for all supported languages, there are new gallery pages in the "Date and Time" category.

- This PR fixes or closes issue: fixes #16692 #11891 
- This PR is related to issue or discussion: #9379 [Community Topic](https://community.home-assistant.io/t/wth-ha-energy-graph-should-be-12-00pm-not-00-00pm-for-midday/479342)
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/common/datetime/use_am_pm.ts [hunk 1]
```diff
@@ -8,8 +8,10 @@ export const useAmPm = memoizeOne((locale: FrontendLocaleData): boolean => {
   ) {
     const testLanguage =
       locale.time_format === TimeFormat.language ? locale.language : undefined;
-    const test = new Date().toLocaleString(testLanguage);
-    return test.includes("AM") || test.includes("PM");
+    const test = new Date("Januar 1, 2023 22:00:00").toLocaleString(
```
Comment (bramkragten) [inline src/common/datetime/use_am_pm.ts:11]:
```suggestion
    const test = new Date("January 1, 2023 22:00:00").toLocaleString(
```

File: src/common/datetime/format_date_time.ts [hunk 2]
```diff
@@ -11,19 +11,14 @@ export const formatDateTime = (dateObj: Date, locale: FrontendLocaleData) =>
 
 const formatDateTimeMem = memoizeOne(
   (locale: FrontendLocaleData) =>
-    new Intl.DateTimeFormat(
-      locale.language === "en" && !useAmPm(locale)
-        ? "en-u-hc-h23"
-        : locale.language,
```
Comment (bramkragten) [inline src/common/datetime/format_date_time.ts:17]: This was done to actually fix a bug in Chrome, can you elaborate why you removed it?

Comment (christophwen) [reply src/common/datetime/format_date_time.ts:17]: It is not removed, the h23 hour cycle is used when the 24 hour time format is wanted. Additionally for the 12 hour format the 12h hour cycle is added. I just moved the h23 a few lines down `hour12: useAmPm(locale)`.
Now the h23 and h12 is used for all languages, not only `en`.

Comment (bramkragten) [reply src/common/datetime/format_date_time.ts:17]: The issue is that that was not working, hence this less nice solution from the time. This may have been fixed by now in Chrome, but we need to check

Comment (christophwen) [reply src/common/datetime/format_date_time.ts:17]: Ah okay, the new gallery pages can be used for that.

Comment (bramkragten) [reply src/common/datetime/format_date_time.ts:17]: The issue was that it displayed 24:12 instead of 00:12 I believe.

Comment (christophwen) [reply src/common/datetime/format_date_time.ts:17]: **Safari Gallery Page Example:**
Safari Gallery Page Example

**Chrome Gallery Page Example:**
Chrome Gallery Page Example

**Comment by christophwen** [comment]
I rebased my changes to the "current" dev to resolve newly occurred conflicts.

File: src/common/datetime/format_date_time.ts (hunk 2 above)
Comment (bramkragten) [reply src/common/datetime/format_date_time.ts:21]: https://bugs.chromium.org/p/chromium/issues/detail?id=1045791

Comment (bramkragten) [reply src/common/datetime/format_date_time.ts:21]: I guess the issue is not showing because you removed `hour12`

**Review by bramkragten — APPROVED** [review]
