### PR TITLE
Fixed Logbook Card/Panel/Dialog Incorrect Entires for `input_datetime` Entities

### LINKED ISSUE #9405: Logbook Card/Panel/Dialog Incorrect Entires Texts for `input_datetime` Entities
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

For `input_datetime` entities, logbook card/panel/dialog shows every entry with the same 'Changed to' date/time even thought the entity was changed to different date/time/datetime.

For example, in this video, although I changed the `input_datetime` to different dates, logbook dialog's every entry shows the same: "Changed to July 3, 2021".

https://user-images.githubusercontent.com/7324708/121449645-d8b8d500-c95f-11eb-8ba2-fd00be464471.mp4

## My root-cause investigation

1. Back in #6978 we added a parameter `state` to `computeStateDisplay` in order to compute the display of an explicit state (instead of the entity's current state). But the `input_datetime` handling wasn't changed properly.
2. When logbook computes the history state into string, we pass the history state into `computeStateDisplay` and `computeStateDisplay` would compute the passed in `state` if it exists instead of the entity's current state.
3. The `input_datetime` handling should try to format the passed in explicit state if it exists. But it only formats the entity's current state regardless of whether `state` parameter exists.

### Describe the behavior you expected

Logbook card/panel/dialog should show every history entry with the correct date that the entity was changed to.

### Steps to reproduce the issue

1. Have a `input_datetime` entity.
2. Change it to different date/time/datetime for multiple times.
3. Open logbook panel, or open the entity's logbook dialog or add/refresh the logbook card of this entity.
4. See all the entries in the logbook card/panel/dialog have the same 'Changed to' date/time.

### What version of Home Assistant Core has the issue?

2021.6.3

### What was the last working version of Home Assistant Core?

always has this issue as long as I start using `input_datetime` w/ logbook.

### In which browser are you experiencing the issue with?

Chrome and Safari

### Which operating system are you using to run this browser?

macOS Big Sur

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ShaneQi**
## Proposed change

The issue (in the video, although I changed the input_datetime to different dates, logbook dialog's every entry shows the same date):

https://user-images.githubusercontent.com/7324708/121449645-d8b8d500-c95f-11eb-8ba2-fd00be464471.mp4

The issue under the hood is:
Back in #6978 we added a parameter `state` to `computeStateDisplay` in order to compute the display of an explicit state (instead of the entity's current state). But the `input_datetime` handling wasn't changed properly.
The `input_datetime` handling should try to format the passed in explicit `state` if it exists. 
This PR added the handling for passed in explicit input_datetime `state`.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

N/A

## Additional information

- This PR fixes or closes issue: fixes #9405
- This PR is related to issue or discussion: #6978
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/common/entity/compute_state_display.ts [hunk 1]
```diff
@@ -28,38 +28,73 @@ export const computeStateDisplay = (
 
   const domain = computeStateDomain(stateObj);
 
+  // Below logic for `input_datetime` works only if the frontend's (browser's) timezone is the same as core's.
+  // If frontend's timezone is different from core's, `input_datetime`s' state display computation will be incorrect.
+  // Needs further fixes for frontend to get core's timezone offset, in order to make computation correct all the time.
```
Comment (ShaneQi) [inline src/common/entity/compute_state_display.ts:33]: I've written the explanation of this in the PR description above.

File: src/common/entity/compute_state_display.ts [hunk 2]
```diff
@@ -28,38 +28,73 @@ export const computeStateDisplay = (
...
+      // If trying to display an explicit state, need to parse the explict state to `Date` then format.
+      // Attributes aren't available, we have to use `state`.
+      try {
+        if (!stateObj.attributes.has_time) {
+          // Only has date.
+          const dateObj = new Date(state);
+          // When only date is passed to `Date` constructor, it uses UTC regardless frontend's timezone,
+          // so we need to compensate that timezone offset.
+          // Other usages of `Date` constructor uses frontend's timezone w/o problem, no compensation needed.
+          const timezoneOffset = new Date().getTimezoneOffset() * 60 * 1000;
```
Comment (ShaneQi) [inline src/common/entity/compute_state_display.ts:45]: snipaste_20210612_150608

File: src/common/entity/compute_state_display.ts [hunk 3]
```diff
@@ -28,38 +28,73 @@ export const computeStateDisplay = (
...
+      // Attributes aren't available, we have to use `state`.
+      try {
+        if (!stateObj.attributes.has_time) {
+          // Only has date.
+          const dateObj = new Date(state);
+          // When only date is passed to `Date` constructor, it uses UTC regardless of frontend's timezone,
+          // so we need to add the frontend's timezone offset.
+          // Other usages of `Date` constructor have both date and time in the string, frontend's timezone is used w/o problem.
+          const timezoneOffset = new Date().getTimezoneOffset() * 60 * 1000;
+          const adjustedDateObj = new Date(dateObj.getTime() + timezoneOffset);
```
Comment (ShaneQi) [inline src/common/entity/compute_state_display.ts:46]: snipaste_20210612_150853

**Comment by bramkragten** [comment]
So the issue here is that we don't have the attributes in the logbook?

File: src/common/entity/compute_state_display.ts (hunk 3 above)
Comment (bramkragten) [reply src/common/entity/compute_state_display.ts:43]: Safari does not accept this format for the Date constructor at all, it will return `Invalid Date`

File: src/common/entity/compute_state_display.ts [hunk 4]
```diff
@@ -29,37 +29,69 @@ export const computeStateDisplay = (
...
+          // Only has time.
+          const now = new Date();
+          const dateTiemString = now.toDateString() + " " + state;
+          const dateObj = new Date(dateTiemString);
+          return formatTime(dateObj, locale);
+        }
+        // Has both date and time.
+        const dateObj = new Date(state);
+        return formatDateTime(dateObj, locale);
+      } catch {
```
Comment (bramkragten) [inline src/common/entity/compute_state_display.ts:56]: The Date constructor doesnt throw on an invalid date.

File: src/common/entity/compute_state_display.ts [hunk 5]
```diff
@@ -29,37 +29,69 @@ export const computeStateDisplay = (
...
+        date = new Date(
+          stateObj.attributes.year,
+          stateObj.attributes.month - 1,
+          stateObj.attributes.day
+        );
+        return formatDate(date, locale);
+      }
+      if (!stateObj.attributes.has_date) {
+        const now = new Date();
+        date = new Date(
```
Comment (bramkragten) [inline src/common/entity/compute_state_display.ts:74]: Instead of creating a new date, we can just set the hour and minute of now?

File: src/common/entity/compute_state_display.ts [hunk 6]
```diff
@@ -29,37 +29,69 @@ export const computeStateDisplay = (
   const domain = computeStateDomain(stateObj);
 
   if (domain === "input_datetime") {
-    let date: Date;
-    if (!stateObj.attributes.has_time) {
+    if (state) {
+      // If trying to display an explicit state, need to parse the explict state to `Date` then format.
+      // Attributes aren't available, we have to use `state`.
+      try {
+        if (!stateObj.attributes.has_time) {
```
Comment (bramkragten) [inline src/common/entity/compute_state_display.ts:36]: If attributes are not available, how can we do this?

File: src/common/entity/compute_state_display.ts [hunk 7]
```diff
@@ -29,37 +29,69 @@ export const computeStateDisplay = (
...
+          // Only has date.
+          const dateObj = new Date(state);
```
Comment (bramkragten) [inline src/common/entity/compute_state_display.ts:38]: I think we should make the `state` string a valid ISO 8601 string, by adding a date or time, then we don't have to struggle with all these issues, and don't have to rely on the current attributes.

**Comment by ShaneQi** [comment]
@bramkragten  thanks for taking a look at this PR!

---

> So the issue here is that we don't have the attributes in the logbook?

Yes, we only added `icon` and `state` for logbook (back in https://github.com/home-assistant/core/pull/40039), no attributes are sent in the API.

---

> If attributes are not available, how can we do this?

We are getting `has_time` and `has_date` from the entity's current attributes.
Because we don't have the event's attributes, I was making the assumption that the entity's `has_time` and `has_date` attributes didn't change. That can be wrong, but very rarely to be wrong IMO.
I hope we end up with a solution in which we don't need to make this assumption.

---

> Instead of creating a new date, we can just set the hour and minute of now?

This code exists prior to this PR, I only changed indentation. But yes, I think we can, I can try it.

--- 

> Safari does not accept this format for the Date constructor at all, it will return `Invalid Date`
> image

> The Date constructor doesnt throw on an invalid date.

> I think we should make the state string a valid ISO 8601 string, by adding a date or time, then we don't have to struggle with all these issues, and don't have to rely on the current attributes.

To the 3 comments above, I think you are making good points. There seems to be too many issues and hacks when we try to create a `Date` object from `state`.

2 questions on this direction:

### For making state a ISO 8601 string

Do we make core store the `input_datetime`'s state in ISO 8601? (This sounds to be too big of a breaking change to me)

Or we add logic to [core logbook component](https://github.com/home-assistant/core/blob/6d656dd2ecc5a7dcdc1d580358f8d0900f27cd27/homeassistant/components/logbook/__init__.py#L319) to process `input_datetime`s' states into ISO 8601?

Or do we do it on frontend? We would do something like these?:

```
date and time: 2021-06-03 01:06:00 -> 2021-06-03T01:06:00Z
// split by space, join with `T`, then append `Z`

time only: 16:11:00 -> 2021-06-15T16:11:00Z
// today's ISO 8601 date string + `T` + state + `Z`

date only: 2021-08-07
// this is already ISO 8601

// I think all 3 above need to add timezone offset because they are all UTC while the `state` string was generated in the user's timezone
```

### For `has_time` and `has_date` attributes

If we don't want to rely on the current attributes, I think the only way is the make core logbook component return them, right?

Or are you thinking about 'looking at state to figure out if it is date or time or both'?

**Comment by bramkragten** [comment]
Yes, I think the frontend should create a ISO 8601 string. 

We don't need to use the `has_time` and `has_date` attributes, it can be derived from the state anyway? But I agree that it is an edge case that the current state would have different settings than the historic states.

About timezone:
If there is a time in an ISO 8601 string, it won't be treated as UTC, just when it is just a date it would be UTC.

**Comment by ShaneQi** [comment]
@bramkragten  gotcha, thanks for the advice! I will go with this direction see how it works out.

For timezone: doesn't the letter `Z` mean UTC? e.g. `2021-06-15T16:11:00Z` meaning 16:11:00 UTC (but the state meant to say it's 16:11:00 in the user's timezone therefore we need to add timezone offset). 
I might be confused tho right now, will figure it out when I actually debug it.

Thanks again.

**Comment by ShaneQi** [comment]
@bramkragten Finished refactoring to what we discussed. 

Let me know if I've misunderstood about anything or anything can be improved.
There are lots of ways to convert the state string to IS8601 as well as derive `date only/time only/datetime` from it. I'm open to any suggestions of changes.

File: src/common/entity/compute_state_display.ts (hunk 4 above)
Comment (ShaneQi) [reply src/common/entity/compute_state_display.ts:72]: You are right, it will only return a `invalid date` w/o throwing, but `formatTime`/`formatDate`/`formatDateTime` will throw in that case. I've updated the comments below this line.

File: src/common/entity/compute_state_display.ts (hunk 5 above)
Comment (ShaneQi) [reply src/common/entity/compute_state_display.ts]: This is done.

File: src/common/entity/compute_state_display.ts [hunk 8]
```diff
@@ -29,37 +29,77 @@ export const computeStateDisplay = (
...
+      // Attributes aren't available, we have to use `state`.
+      try {
+        // We are going to convert the state string into a ISO8601 string,
+        // which is always in UTC and causing the tiemzone info to be lost,
+        // therefore we need to compensate the local timezone offset.
+        const timezoneOffset = new Date().getTimezoneOffset() * 60 * 1000;
+        const components = state.split(" ");
+        if (components.length === 2) {
+          // Date and time.
+          const iso8601String = components.join("T") + "Z";
```
Comment (bramkragten) [inline src/common/entity/compute_state_display.ts:43]: If you leave the `Z` of, you don't need the `timezoneOffset`

File: src/common/entity/compute_state_display.ts [hunk 9]
```diff
@@ -29,37 +29,77 @@ export const computeStateDisplay = (
...
+              dateObj.getTime() + timezoneOffset
+            );
+            return formatDate(adjustedDateObj, locale);
+          }
+          if (state.includes(":")) {
+            // Time only.
+            // Inserting today's Date string.
+            const now = new Date();
+            const dateISO8601String =
+              now.toISOString().substring(0, 10) + "T" + state + "Z";
```
Comment (bramkragten) [inline src/common/entity/compute_state_display.ts:63]: Same here, no need for `timezoneOffset` when `Z` is dropped

File: src/common/entity/compute_state_display.ts [hunk 10]
```diff
@@ -29,37 +29,77 @@ export const computeStateDisplay = (
...
+        }
+        if (components.length === 1) {
+          if (state.includes("-")) {
+            // Date only.
+            // Date only state is already a valid ISO8601 string.
+            const dateObj = new Date(state);
+            const adjustedDateObj = new Date(
+              dateObj.getTime() + timezoneOffset
+            );
+            return formatDate(adjustedDateObj, locale);
```
Comment (bramkragten) [inline src/common/entity/compute_state_display.ts:56]: This will work, but `const dateObj = new Date(`${state}T00:00:00`);` will work too.

File: src/common/entity/compute_state_display.ts (hunk 9 above)
Comment (bramkragten) [inline src/common/entity/compute_state_display.ts:63]:
```suggestion
              `${now.toISOString().split("T")[0]}T${state};
```

File: src/common/entity/compute_state_display.ts (hunk 8 above)
Comment (ShaneQi) [reply src/common/entity/compute_state_display.ts:43]: I thought `Z` is required in ISO8601 spec, even after reading some documents, it's still vague.

But I verified it works without `Z` on both Chrome and Safari, I will remove it. Thanks for the reminder!

**Comment by ShaneQi** [comment]
@bramkragten I resolved the last 4 comments. I'm amazed how simple this ended up with, thank you!

File: src/common/entity/compute_state_display.ts [hunk 11]
```diff
@@ -29,37 +29,64 @@ export const computeStateDisplay = (
...
+    if (state) {
+      // If trying to display an explicit state, need to parse the explict state to `Date` then format.
+      // Attributes aren't available, we have to use `state`.
+      try {
+        const components = state.split(" ");
+        if (components.length === 2) {
+          // Date and time.
+          const iso8601String = components.join("T");
+          const dateObj = new Date(iso8601String);
+          return formatDateTime(dateObj, locale);
```
Comment (bramkragten) [inline src/common/entity/compute_state_display.ts:41]:
```suggestion
          return formatDateTime(new Date(components.join("T")), locale);
```

File: src/common/entity/compute_state_display.ts [hunk 12]
```diff
@@ -29,37 +29,64 @@ export const computeStateDisplay = (
...
+        }
+        if (components.length === 1) {
+          if (state.includes("-")) {
+            // Date only.
+            const iso8601String = `${state}T00:00`;
+            const dateObj = new Date(iso8601String);
+            return formatDate(dateObj, locale);
```
Comment (bramkragten) [inline src/common/entity/compute_state_display.ts:48]:
```suggestion
            return formatDate(new Date(`${state}T00:00`), locale);
```

File: src/common/entity/compute_state_display.ts [hunk 13]
```diff
@@ -29,37 +29,64 @@ export const computeStateDisplay = (
...
+          }
+          if (state.includes(":")) {
+            // Time only.
+            const now = new Date();
+            const iso8601String = `${now.toISOString().split("T")[0]}T${state}`;
+            const dateObj = new Date(iso8601String);
+            return formatTime(dateObj, locale);
```
Comment (bramkragten) [inline src/common/entity/compute_state_display.ts:55]:
```suggestion
            return formatTime(new Date(`${now.toISOString().split("T")[0]}T${state}`), locale);
```

**Review by bramkragten — APPROVED** [review]
