### PR TITLE
hui-graph-header-footer: add own action handler

### LINKED ISSUE #29463: Sensor card graph area not clickable
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When clicking a sensor card with graph it does not open state history when you click on the graph section of it, only when you click title/value/icon (upper section)

mouse on graph section (not clickable)
Image

mouse on upper section (clickable)
Image

### Describe the behavior you expected

Clicking on the graph also opens state history dialog

### Steps to reproduce the issue

1. create a sensor card with line graph
2. try to click the footer/graph section of the card

### What version of Home Assistant Core has the issue?

core-2026.2.0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Firefox 147.0.3 / Home Assistant Companion App Android 2026.2.1-full

### Which operating system are you using to run this browser?

Arch Linux / Android 16

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
graph: line
type: sensor
entity: sensor.some_sensor
detail: 1
grid_options:
  columns: full
  rows: 3
hours_to_show: 24
limits:
  min: 20
  max: 70
```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ildar170975**
## Proposed change

The `hui-graph-header-footer` does not have own action handler.
Because of that – here is how a tap is processed for a graph footer:
1. When a footer is added into Entities card – more-info is not shown for a “graph entity” - UNEXPECTED.
2. When a footer is added into Entity card:
a. Before 2026.2 – more-info was shown for the “main entity” of the Entity card - UNEXPECTED.
b. Since 2026.2 – more-info is not shown - UNEXPECTED.
3. For the Sensor card  - which is internally Entity card where “main entity” & “graph entity” are same:
a. Before 2026.2 – more-info was shown for the “main/graph entity” of the Entity card - OK.
b. Since 2026.2 – more-info is not shown - WRONG.

In 2026.2 a processing was changed in https://github.com/home-assistant/frontend/pull/28949.

After this current PR - `hui-graph-header-footer` has own action handler:
1. When a footer is added into Entities card – more-info is shown for a “graph entity” - OK.
2. When a footer is added into Entity card - more-info is shown for a “graph entity” - OK.
3. For the Sensor card  - more-info is shown for the “main/graph entity” - OK.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/29463
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/header-footer/hui-graph-header-footer.ts [hunk 1]
```diff
@@ -122,10 +123,18 @@ export class HuiGraphHeaderFooter
...
   }
 
+  private _handleClick(): void {
+    fireEvent(this, "hass-more-info", {
+      entityId: this._config?.entity ?? null,
+    });
+  }
+
   public connectedCallback() {
     super.connectedCallback();
```
Comment (MindFreeze) [inline src/panels/lovelace/header-footer/hui-graph-header-footer.ts:137]:
```suggestion
    super.connectedCallback();
    this.addEventListener("click", this._handleClick);
```
We can avoid the extra DOM element by attaching the event to `:host` like this. Don't know if the extra `div` is a problem, so this is only a suggestion, but at the very least it might break some `card-mod` tweaks.

**Review by MindFreeze — COMMENTED** [review]
Won't this change conflict with #28949 and potentially fire `more-info` plus the actionHandler?

File: src/panels/lovelace/header-footer/hui-graph-header-footer.ts (hunk 1 above)
Comment (ildar170975) [reply src/panels/lovelace/header-footer/hui-graph-header-footer.ts:137]: > Won't this change conflict with https://github.com/home-assistant/frontend/pull/28949 and potentially fire more-info plus the actionHandler?

Tested locally, seems to be OK.

Comment (ildar170975) [reply src/panels/lovelace/header-footer/hui-graph-header-footer.ts:137]: > but at the very least it might break some card-mod tweaks.

I doubt on that, do not recall any possible difficulties with card-mod here.
But I do agree that it is better not to touch DOM structure.
Will consider your proposal.

Comment (ildar170975) [reply src/panels/lovelace/header-footer/hui-graph-header-footer.ts:137]: Did as you suggested, removed extra div, fixed a style.

**Review by MindFreeze — APPROVED** [review]
