### PR TITLE
Guard discovered devices flow subscription for non-admin users

### LINKED ISSUE #30100: Non-admin user raises Unauthorized error from websocket when trying to load discovered devices
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I created a new non-admin user, and my logs were showing unauthorized attempts to connect to the websocket_api. Looking at the console for that user shows it is trying to connect to the hui-discovered-devices-card.ts at line 42 and failing since it is non-admin. I believe there should be an admin guard around that line like so:
// hui-discovered-devices-card.ts ~line 42
hassSubscribe() {
  if (!this.hass.user?.is_admin) return [];  // ← add this guard
  return [
    g(this.hass, ...)  // config_flow subscription
  ];
}
It seems not to affect anything as the user can operate just fine, but it does through errors every time I load that page.

The error in the logs is below (redacted):
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:315
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 12:10:01 PM (7 occurrences)
Last logged: 12:15:38 PM

    [140299938795648] Error handling message: Unauthorized (unauthorized) DISPLAY NAME from X.X.X.X (Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:148.0) Gecko/20100101 Firefox/148.0)

### Describe the behavior you expected

I expected no errors in the log or console as they should not have access to the discovered devices card.

### Steps to reproduce the issue

1. Create new non-admin user (this part may be optional, I didn't have any non-admin users on this server so couldn't check)
2. Load the front page under the new user account.
3. Check the console and logs to see unauthorized errors.
...

### What version of Home Assistant Core has the issue?

2026.3.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Firefox 148.0 (aarch64)

### Which operating system are you using to run this browser?

macOS Tahoe 26.3

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt
Uncaught (in promise) 
Object { code: "unauthorized", message: "Unauthorized" }
connection.js:304:15
    subscribeMessage connection.js:304
    AsyncFunctionThrow self-hosted:784
    (Async: async)
    g config_flow.ts:105
    hassSubscribe hui-discovered-devices-card.ts:42
    _checkSubscribed subscribe-mixin.ts:73
    updated subscribe-mixin.ts:44
    _$AE reactive-element.ts:1563
    performUpdate reactive-element.ts:1528
    scheduleUpdate reactive-element.ts:1410
    _$EP reactive-element.ts:1382
    AsyncFunctionNext self-hosted:780
    (Async: async)
    requestUpdate reactive-element.ts:1321
    _$Ev reactive-element.ts:1055
    k reactive-element.ts:1038
    i lit-element.ts:130
    t subscribe-mixin.ts:13
    g hui-discovered-devices-card.ts:28
    I scoped-custom-element-registry.ts:642
    t scoped-custom-element-registry.ts:408
    define scoped-custom-element-registry.ts:243
    r custom-element.ts:60
    i tslib.es6.mjs:58
    38865 64522.e110f39edf80b94a.js:1
    h app.4685c82f04f5e1ef.js:78
    (Async: promise callback)
    devices create-card-element.ts:78
    h create-element-base.ts:307
    w create-card-element.ts:109
    _loadElement hui-card.ts:139
    load hui-card.ts:41
    _createCardElement hui-section.ts:78
    _cards hui-section.ts:325
    map self-hosted:163
    _createCards hui-section.ts:324
    _initializeConfig hui-section.ts:181
    willUpdate hui-section.ts:106
    performUpdate reactive-element.ts:1512
    performUpdate storage.ts:172
    scheduleUpdate reactive-element.ts:1410
    _$EP reactive-element.ts:1382
    AsyncFunctionNext self-hosted:780
    (Async: async)
    requestUpdate reactive-element.ts:1321
    _$Ev reactive-element.ts:1055
    k reactive-element.ts:1038
    <anonymous> conditional-listener-mixin.ts:41
    w hui-section.ts:37
    I scoped-custom-element-registry.ts:642
    t scoped-custom-element-registry.ts:408
    createSectionElement hui-view.ts:133
    _sections hui-view.ts:485
    map self-hosted:163
    _createSections hui-view.ts:484
    _setConfig hui-view.ts:338
    _initializeConfig hui-view.ts:362
    InterpretGeneratorResume self-hosted:1312
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by xtymmms1021**
## Proposed change

Prevent non-admin users from subscribing to config entry flow updates in `hui-discovered-devices-card`.

`/home/overview` includes the `discovered-devices` card via the Home strategy. Today, `hassSubscribe()` subscribes to `config_entries/flow/subscribe` before any admin guard, while visibility is gated later in `willUpdate()`. Because `connectedWhileHidden = true`, non-admin sessions can still attempt this subscription and trigger websocket `Unauthorized` errors.

This patch adds an early guard in `hassSubscribe()`:
- If `!this.hass || !this.hass.user?.is_admin`, clear `_discoveredFlows` and return `[]`.
- Otherwise subscribe as before.

## Type of change

- [x] Bugfix
- [ ] New feature
- [ ] Breaking change

## Related issue

Closes #30100

## Testing

- Reproduced issue on Core `2026.3.1` with non-admin users opening `/home/overview`.
- Verified command-level trigger in websocket logs: `config_entries/flow/subscribe` unauthorized for non-admin.
- Ran file-level eslint:
  - `corepack yarn eslint src/panels/lovelace/cards/hui-discovered-devices-card.ts`

### CODE REVIEW

File: src/panels/lovelace/cards/hui-discovered-devices-card.ts [hunk 1]
```diff
@@ -38,9 +38,14 @@ export class HuiDiscoveredDevicesCard
   @state() private _discoveredFlows: DataEntryFlowProgress[] = [];
 
   public hassSubscribe(): (UnsubscribeFunc | Promise<UnsubscribeFunc>)[] {
+    if (!this.hass || !this.hass.user?.is_admin) {
+      this._discoveredFlows = [];
```
Comment (MindFreeze) [inline src/panels/lovelace/cards/hui-discovered-devices-card.ts]:
```suggestion
    if (!this.hass!.user?.is_admin) {
```
`this.hass` is guaranteed here

File: src/panels/lovelace/cards/hui-discovered-devices-card.ts [hunk 2]
```diff
@@ -38,9 +38,14 @@ export class HuiDiscoveredDevicesCard
...
+      return [];
+    }
+
     return [
       subscribeConfigFlowInProgress(
-        this.hass!,
+        this.hass,
```
Comment (MindFreeze) [inline src/panels/lovelace/cards/hui-discovered-devices-card.ts]:
```suggestion
        this.hass!,
```

**Review by MindFreeze — COMMENTED** [review]
Please sign the CLA

**Comment by xtymmms1021** [comment]
Thanks for the reminder — I have now signed the CLA. Please let me know if the status still doesn’t update on your side.

**Comment by xtymmms1021** [comment]
Thanks @MindFreeze — I pushed the requested changes in commit 2ae724c.

- switched to: if (!this.hass!.user?.is_admin)
- passed this.hass! into subscribeConfigFlowInProgress(...)

Please take another look when you have time.

**Review by timmo001 — APPROVED** [review]
