### PR TITLE
Fix General Config Zone update on Mobile

### LINKED ISSUE #12621: Can't update location using map on general config page
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I am unable to update my "Home" location using the map on the General -> Config page.

I can drag the pin to a new location but pressing save does not update the location - reloading the page displays the pin back at its previous location

### Describe the behavior you expected

I can update my home location using the map.

### Steps to reproduce the issue

1. Visit `/config/general`
2. Drag the pin on the map
3. Press "Update"
4. Reload the page
5. Note that the location is not updated

### What version of Home Assistant Core has the issue?

2022.5.2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Firefox 99.0.1

### Which operating system are you using to run this browser?

macOS Monterey (12.3)

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

This only seems to happen when the browser is narrower than 871px - wider than that just takes me to the zone edit page instead of allowing me to edit the location inline.

It looks like the new location is not passed to `saveCoreConfig`:
https://github.com/home-assistant/frontend/blob/ce77ddf3659f082de8f1aaf9a710149da4281bbc/src/panels/config/core/ha-config-section-general.ts#L277-L283

It gets saved in `this._location` when the pin is moved but it doesn't seem to get used outside of that:
https://github.com/home-assistant/frontend/blob/ce77ddf3659f082de8f1aaf9a710149da4281bbc/src/panels/config/core/ha-config-section-general.ts#L265-L267

### PR DESCRIPTION
**Pull request by zsarnett**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #12621
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/core/ha-config-section-general.ts [hunk 1]
```diff
@@ -273,13 +273,23 @@ class HaConfigSectionGeneral extends LitElement {
     }
     button.progress = true;
 
+    let locationConfig = {};
```
Comment (bramkragten) [inline src/panels/config/core/ha-config-section-general.ts:276]:
```suggestion
    let locationConfig;
```

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
