### PR TITLE
Disable counter buttons if entity is unavailable

### LINKED ISSUE #8063: Counter more-info dialog shows controls when entity is unavailable
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

On the more info dialog for counter, the controls (increment, decrement, reset) are still shown even when the entity is unavailable. 

image

## Expected behavior

The controls should either be hidden or disabled (grayed out) when the entity is unavailable

## Steps to reproduce

1. Create a counter in YAML
2. Comment it out and reload counters so entity is unavailable
3. Open the more-info dialog for that counter. Controls will be shown still, even though clicking them will do nothing (obviously). In the logs it prints `Unable to find referenced entities counter.bedroom_window_opened`

## Environment

- Home Assistant release with the issue: 2021.1.0b0
- Last working Home Assistant release (if known): n/a
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Disable the buttons if entity is not available. 

Also reduced some margins for more-info elements. Given that the state display already adds 16px at the bottom before the more-info section starts and the mdc-dialog-content-box also already has 20px padding, there is more then enough negative space already.

image

image

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/8063
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/more-info/controls/more-info-counter.ts [hunk 1]
```diff
@@ -26,17 +27,23 @@ class MoreInfoCounter extends LitElement {
       <div class="actions">
         <mwc-button
           .action="${"increment"}"
-          @click="${this._handleActionClick}"
+          @click=${this._handleActionClick}
+          .disabled=${UNAVAILABLE_STATES.includes(this.stateObj!.state)}
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-counter.ts:31]: Make it a const and move it to line 25

**Review by bramkragten — APPROVED** [review]

**Review by bramkragten — APPROVED** [review]
