### PR TITLE
Fix display of arrays/objects in attributes

### LINKED ISSUE #3689: Bayesian binary sensor details - strange details view.
**Home Assistant release with the issue:**
0.98.5

**UI (States or Lovelace UI?):**
Lovelace UI

**Browser and Operating System:**
Chrome v76 Windows 10

**Description of problem:**
Strange details about observations in Bayesian binary sensor. Maybe it is possible to display some info about currently active observations (probability?)?
Look how this looks now:
image

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change
An array with an array of object and objects are now parsed as yaml.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #3689 
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-attributes.ts [hunk 1]
```diff
@@ -10,6 +10,7 @@ import {
 import { HassEntity } from "home-assistant-js-websocket";
 
 import hassAttributeUtil from "../util/hass-attributes-util";
+import { safeDump } from "js-yaml";
```
Comment (balloob) [inline src/components/ha-attributes.ts]: Can we import this async? We won't need it most of the time and we import the more info dialogs pretty early on.

Comment (balloob) [reply src/components/ha-attributes.ts]: We can use memoizeOne and a promise to import + render combined with lit rendering output of promise.

Comment (balloob) [reply src/components/ha-attributes.ts]: only care about this component because it's used in more info. For dev tool I don't care
