### PR TITLE
fix history graph configuration timeline update

### LINKED ISSUE #14097: Timeline view in history graph doesn't obey hours_to_show
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When creating a history graph card, numerical values are shown in the graph, while binary values get added in the typical timeline view.

The problem is that the timeline view does not align with the 'hours to show' configured in the card.

image
image

### Describe the behavior you expected

The timeline view in the history card should adjust to the 'hours to show' config

### Steps to reproduce the issue

1. Create history graph card + set time to show to 48h
2. Add some numerical entities
3. Add a binary entity (e.g. switch state)

### What version of Home Assistant Core has the issue?

 Frontend 20221010.0 - latest 

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

104.0.2 (64-bit)

### Which operating system are you using to run this browser?

macOS Monterey 12.4 (21F79)

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tradiff**
## Proposed change

In the configuration for the history card, the timeline preview was not changing it's scale if the hours_to_show was reduced by the user. This is because the suggestedMin and suggestedMax was set on the initial render based on hours_to_show, but never updated again if the config was changed. This was particularly awkward because the line chart below the timeline does update it's scale.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

### Before:
https://user-images.githubusercontent.com/934490/196015014-16e6b5a7-c7ae-4bb4-9738-e12c57a8fdd3.mov

### After:
https://user-images.githubusercontent.com/934490/196015028-c1b8d9c7-b344-44c8-81ea-532f562279d9.mov

- This PR fixes or closes issue: fixes #14097
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/chart/state-history-chart-timeline.ts [hunk 1]
```diff
@@ -118,101 +118,9 @@ export class StateHistoryChartTimeline extends LitElement {
...
-            },
-          },
-          filler: {
-            propagate: true,
-          },
-        },
-        // @ts-expect-error
-        locale: numberFormatToLocale(this.hass.locale),
-      };
+      this._createOptions();
```
Comment (travatomic) [inline src/components/chart/state-history-chart-timeline.ts:121]: In GitHub, this looks like a lot of change, but it's essentially breaking this code out into a _createOptions() function, so that it can be called from two different locations. (No other changes were made to the code within the _createOptions() function)

File: src/components/chart/state-history-chart-timeline.ts [hunk 2]
```diff
@@ -221,9 +129,107 @@ export class StateHistoryChartTimeline extends LitElement {
       // If the line is more than 5 minutes old, re-gen it
       // so the X axis grows even if there is no new data
       this._generateData();
+      this._createOptions();
```
Comment (travatomic) [inline src/components/chart/state-history-chart-timeline.ts:132]: This is the real change, refreshing the options when we've detected the data should change.

[the remark this answers is not in the document]
Comment (travatomic) [reply src/components/chart/state-history-chart-timeline.ts:135]: Yeah that's fair. I've updated the code. I was thinking there could be similar bugs with any other options.

**Review by bramkragten — APPROVED** [review]
