### PR TITLE
Fix media browser dialog window

### LINKED ISSUE #51421: Media player source selector dialog is compressed on desktop (unusable layout)
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After a recent Home Assistant update, the media player source selector dialog is visually broken on desktop.

When selecting a source for any media player, the dialog appears compressed and difficult to use. The source options are tightly packed, icons have incorrect spacing, and it is hard to see or select a source.

The issue occurs with both the default Home Assistant media player card and Mushroom media player card, so it does not seem related to a custom card.

The issue is reproducible in multiple desktop browsers (Chrome and Safari), but does not occur in the mobile app.

### Describe the behavior you expected

The media player source selector dialog should display normally with proper spacing between options, clear icons, and easy interaction.

Users should be able to clearly see and select a source without layout issues or compressed elements.

Image

### Steps to reproduce the issue

1. Open Home Assistant in a desktop browser (Chrome or Safari)
2. Open any media player (e.g. Sonos or other media_player entity)
3. Click on the source selection button
4. The source selector dialog opens
5. Observe that the layout is compressed and difficult to use

### What version of Home Assistant Core has the issue?

core-2026.4.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Google Chrome (latest) Safari (latest)

### Which operating system are you using to run this browser?

macOS Sonoma

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml
No custom configuration required.

The issue occurs with:
- Default Home Assistant media player card
- Mushroom media player card

No custom styling or special configuration is used.
```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

The issue started after a recent update and appears to be a frontend regression affecting desktop layouts only.

### PR DESCRIPTION
**Pull request by GeorgeZ83**
## Proposed change
Changed the window `width` to auto` and added `height: 100vh`

## Screenshots
Screenshot 2026-04-05 162534
Screenshot 2026-04-05 162832

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #51421
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

**Comment by wendevlin** [comment]
There is an issue with this on smaller screens:

grafik

grafik

File: src/components/media-player/dialog-media-player-browse.ts
Comment (wendevlin) [inline src/components/media-player/dialog-media-player-browse.ts:80]:
```suggestion
```

not needed anymore

Comment (wendevlin) [inline src/components/media-player/dialog-media-player-browse.ts:81]:
```suggestion
        .open=${this._open}
        width="large"
```

let's make it wider, makes more sense for such a dialog

File: src/components/media-player/dialog-media-player-browse.ts [hunk 1]
```diff
@@ -248,7 +248,8 @@ class DialogMediaPlayerBrowse extends LitElement {
             --media-browser-max-height: calc(
               100vh - 145px - var(--safe-area-inset-y)
             );
-            width: 700px;
+            width: auto;
+            height: 100vh;
```
Comment (wendevlin) [inline src/components/media-player/dialog-media-player-browse.ts]:
```suggestion
```

File: src/components/media-player/dialog-media-player-browse.ts
Comment (wendevlin) [inline src/components/media-player/dialog-media-player-browse.ts:233]:
```suggestion
          );
          height: 100vh;
```

**Review by wendevlin — COMMENTED** [review]
I added some suggestions.

File: src/components/media-player/dialog-media-player-browse.ts
Comment (GeorgeZ83) [reply src/components/media-player/dialog-media-player-browse.ts:80]: I get an error trying to commit this:
Suggestion can not be identical to original text. 😳

**Comment by GeorgeZ83** [comment]
> I added some suggestions. 

Thanks 🙏

File: src/components/media-player/dialog-media-player-browse.ts [hunk 2]
```diff
@@ -230,6 +231,8 @@ class DialogMediaPlayerBrowse extends LitElement {
           --media-browser-max-height: calc(
             100vh - 65px - var(--safe-area-inset-y)
           );
+          height: 100vh;
+          height: 100vh;
```
Comment (wendevlin) [inline src/components/media-player/dialog-media-player-browse.ts]:
```suggestion
          height: 100dvh;
```

**Review by wendevlin — APPROVED** [review]

**Comment by wendevlin** [comment]
@GeorgeZ83 thanks a lot!
