### PR TITLE
Escape special characters of automation ID in URL

### LINKED ISSUE #19786: An automation ID ending in '%' cannot be edited in the GUI.
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

I have some legacy automations with IDs like this:

`HVAC__MBR_auto_fan_also_drops_duty_cycle_down_to_50%`

If I click one of these in `/config/automation/dashboard`, I get a blank screen. The URL that HASS is trying to go to is `/config/automation/edit/HVAC__MBR_auto_fan_also_drops_duty_cycle_down_to_50%`, which is not properly escaped.

As a workaround, you can append `25` to the end of the URL because `%25` is the URL-escaped form of `%`.

### Describe the behavior you expected

I expected HASS to URL-escape any special characters in my automation ID when browsing to a URL based on that ID.

### Steps to reproduce the issue

1. Create an automation with an ID ending in `%`
2. Go to Settings -> Automations and Scenes -> Automations and click the above automation.
3. BUG: Instead of loading the automation for display or edit, you get a blank screen.
...

### What version of Home Assistant Core has the issue?

20240207.1 (frontend)

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Firefox 122.0.1

### Which operating system are you using to run this browser?

Ubuntu 23.10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

```yaml
- id: HVAC__MBR_auto_fan_also_drops_duty_cycle_down_to_50%
  alias: 'HVAC: MBR auto fan also drops duty cycle down to 50%'
  trigger:
    platform: state
    entity_id: input_select.fan_mode_mbr
    to: AUTO
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.fan_mbr_target
      value: '50'
```

### Javascript errors shown in your browser console/inspector

```txt
ReferenceError: GM_registerMenuCommand is not defined
    enableCommandMenu user-script:Absolute Right Click/Absolute Enable Right Click & Copy:94
    main user-script:Absolute Right Click/Absolute Enable Right Click & Copy:61
    userScript user-script:Absolute Right Click/Absolute Enable Right Click & Copy:119
    userScript user-script:Absolute Right Click/Absolute Enable Right Click & Copy:186
    scopeWrapper user-script:Absolute Right Click/Absolute Enable Right Click & Copy:208
    <anonymous> user-script:Absolute Right Click/Absolute Enable Right Click & Copy:209
Absolute Enable Right Click & Copy:101:21
Request for font "Roboto" blocked at visibility level 2 (requires 3)
HVAC__Daphne_auto_fan_also_drops_duty_cycle_down_to_50%
Request for font "Roboto Lt" blocked at visibility level 2 (requires 3)
HVAC__Daphne_auto_fan_also_drops_duty_cycle_down_to_50%
Uncaught (in promise) URIError: malformed URI sequence
    value ha-config-automation.ts:103
    value hass-router-page.ts:317
    value hass-router-page.ts:185
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
2 ha-config-automation.ts:103:46
The resource at “https://hass.igo:8124/static/fonts/roboto/Roboto-Regular.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dashboard
The resource at “https://hass.igo:8124/static/fonts/roboto/Roboto-Medium.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. dashboard
Uncaught (in promise) URIError: malformed URI sequence
    value ha-config-automation.ts:103
    value hass-router-page.ts:317
    value hass-router-page.ts:185
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
4 ha-config-automation.ts:103:46
Uncaught (in promise) URIError: malformed URI sequence
    value ha-config-automation.ts:103
    value hass-router-page.ts:317
    value hass-router-page.ts:185
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    value ha-panel-config.ts:607
    value hass-router-page.ts:137
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    value partial-panel-resolver.ts:101
    value hass-router-page.ts:137
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    j lit-html.ts:1883
    _$AI lit-html.ts:1825
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    z lit-html.ts:2183
    update lit-element.ts:165
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    j lit-html.ts:1883
    _$AI lit-html.ts:1825
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    z lit-html.ts:2183
    update lit-element.ts:165
ha-config-automation.ts:103:46
    _$Ej reactive-element.ts:1260
    AsyncFunctionNext self-hosted:852
    (Async: async)
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    value ha-panel-config.ts:607
    value hass-router-page.ts:137
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    AsyncFunctionNext self-hosted:852
    (Async: async)
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    value partial-panel-resolver.ts:101
    value hass-router-page.ts:137
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    AsyncFunctionNext self-hosted:852
    (Async: async)
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    j lit-html.ts:1883
    _$AI lit-html.ts:1825
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    z lit-html.ts:2183
    update lit-element.ts:165
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    AsyncFunctionNext self-hosted:852
    (Async: async)
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    j lit-html.ts:1883
    _$AI lit-html.ts:1825
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    z lit-html.ts:2183
    update lit-element.ts:165
XHRGET
https://hass.igo:8124/unknown/src/lit-element.ts
[HTTP/1.1 404 Not Found 0ms]

XHRGET
https://hass.igo:8124/unknown/src/lit-html.ts
[HTTP/1.1 404 Not Found 0ms]

Uncaught (in promise) URIError: malformed URI sequence
    value ha-config-automation.ts:103
    value hass-router-page.ts:317
    value hass-router-page.ts:185
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    value ha-panel-config.ts:607
    value hass-router-page.ts:137
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    value partial-panel-resolver.ts:101
    value hass-router-page.ts:137
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    j lit-html.ts:1883
    _$AI lit-html.ts:1825
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    z lit-html.ts:2183
    update lit-element.ts:165
    performUpdate reactive-element.ts:1329
    scheduleUpdate reactive-element.ts:1261
    _$Ej reactive-element.ts:1233
    requestUpdate reactive-element.ts:1208
    set reactive-element.ts:726
    j lit-html.ts:1883
    _$AI lit-html.ts:1825
    v lit-html.ts:1192
    g lit-html.ts:1540
    _$AI lit-html.ts:1384
    z lit-html.ts:2183
    update lit-element.ts:165
ha-config-automation.ts:103:46
```

### Additional information

I did not test automations with other special characters or with infix special characters, but I would guess there may be issues there as well. These were also legacy automations that were migrated from a version of HASS before the time of the visual automation editor, so I don't know if new automations are allowed to include special characters in their IDs

### PR DESCRIPTION
**Pull request by piitaya**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/19786
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/areas/ha-config-area-page.ts [hunk 1]
```diff
@@ -568,7 +568,7 @@ class HaConfigAreaPage extends LitElement {
       <a
         href=${ifDefined(
           entityState.attributes.id
-            ? `/config/automation/edit/${entityState.attributes.id}`
+            ? `/config/automation/edit/${encodeURI(entityState.attributes.id)}`
```
Comment (steverep) [inline src/panels/config/areas/ha-config-area-page.ts:571]: I think we should use `encodeURIComponent` instead to be more secure?

**Review by steverep — APPROVED** [review]
