### PR TITLE
Sync charts zoom in history tab

### LINKED ISSUE #23766: Zooming in history graph with numeric and text sensor not synchronized
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When you have a history card that has both text sensors (the "strip" of states) and numeric values displayed as a plot, then zooming on either the strips or the graph doesn't zoom on the other, making closer analysis of data tedious.

It seems like a bug because sensors within one graph card do otherwise zoom in sync, like multiple strips or multiple lines in a plot do zoom together.

### Describe the behavior you expected

Both "strip" and graph in the same card should zoom in sync and always show the same timeframe

### Steps to reproduce the issue

1. Add numeric sensor with a unit to the graph card
2. Add other sensor without unit to the graph card
3. Zoom either, observe the other not zooming

### What version of Home Assistant Core has the issue?

2025.2.0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Firefox 134

### Which operating system are you using to run this browser?

Arch Linux (2024-01-15)

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by birrejan**
## Proposed change

Add synchronized zoom functionality across multiple charts in the History tab with a unified reset interface. When users zoom into one chart, all charts automatically synchronize to the same time range, providing a cohesive view of historical data across different entities and chart types.

https://github.com/user-attachments/assets/77510e16-87ed-40af-98dd-0e3138f4e4b5

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #23766  
- This PR is related to issue or discussion:
- Link to documentation pull request: 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/chart/state-history-charts.ts [hunk 1]
```diff
@@ -29,6 +31,13 @@ const chunkData = (inputArray: any[], chunks: number) =>
 declare global {
   interface HASSDomEvents {
     "y-width-changed": { value: number; chartIndex: number };
+    "chart-zoom": {
```
Comment (bramkragten) [inline src/components/chart/state-history-charts.ts]: You should not define the same event twice

File: src/components/chart/state-history-charts.ts [hunk 2]
```diff
@@ -264,6 +296,85 @@ export class StateHistoryCharts extends LitElement {
...
+      chartComponents.forEach((chartComponent: any, index) => {
+        if (index === sourceChartIndex) {
+          return;
+        }
+
+        const chartBase =
+          chartComponent.renderRoot?.querySelector("ha-chart-base");
+
+        if (chartBase && chartBase.chart) {
+          chartBase.chart.dispatchAction({
```
Comment (bramkragten) [inline src/components/chart/state-history-charts.ts]: Create a public zoom function on `ha-chart-base` and on `state-history-chart-line`, `state-history-chart-line` call the function on the latter, and let it forward it to `ha-chart-base`. `ha-chart-base` should do the `dispatchAction` call.

File: src/components/chart/state-history-charts.ts (hunk 1 above)
Comment (birrejan) [reply src/components/chart/state-history-charts.ts]: You're absolutely right, I missed the general overview. Now it's fix! Thanks

File: src/components/chart/state-history-charts.ts (hunk 2 above)
Comment (birrejan) [reply src/components/chart/state-history-charts.ts]: that's indeed a cleaner solution.

**Comment by JanLayola** [comment]
@LiBe-net good catch! Now they should be working again

File: src/components/chart/state-history-charts.ts [hunk 3]
```diff
@@ -264,6 +289,76 @@ export class StateHistoryCharts extends LitElement {
...
+            type: "dataZoom",
+            dataZoomId: "dataZoom",
+            start: 0,
+            end: 100,
+            silent: true,
+          });
```
Comment (MindFreeze) [inline src/components/chart/state-history-charts.ts]:
```suggestion
          chartBase.zoom(0, 100);
```

File: src/components/chart/state-history-charts.ts [hunk 4]
```diff
@@ -115,19 +121,34 @@ export class StateHistoryCharts extends LitElement {
...
+              .items=${combinedItems}
+              .renderItem=${this._renderHistoryItem}
+            >
+            </lit-virtualizer>
+          </div>`
+        : html`${combinedItems.map((item, index) =>
+            this._renderHistoryItem(item, index)
+          )}`}
+      ${this._hasZoomedCharts
+        ? html`<ha-icon-button
```
Comment (bramkragten) [inline src/components/chart/state-history-charts.ts]: We should use a `ha-fab` here instead of an `icon-button`

File: src/components/chart/state-history-charts.ts [hunk 5]
```diff
@@ -115,19 +121,34 @@ export class StateHistoryCharts extends LitElement {
...
+            class="floating-reset-button"
+            .path=${mdiRestart}
+            @click=${this._handleGlobalZoomReset}
+            title=${this.hass.localize(
+              "ui.components.history_charts.zoom_reset"
+            )}
+          ></ha-icon-button>`
+        : ""}
```
Comment (bramkragten) [inline src/components/chart/state-history-charts.ts]:
```suggestion
        : nothing}
```

File: src/components/chart/state-history-charts.ts [hunk 6]
```diff
@@ -264,6 +289,70 @@ export class StateHistoryCharts extends LitElement {
...
+      const chartComponents = this.renderRoot.querySelectorAll(
+        "state-history-chart-line, state-history-chart-timeline"
+      );
+
+      chartComponents.forEach((chartComponent: any, index) => {
+        if (index === sourceChartIndex) {
+          return;
+        }
+
+        if (chartComponent.zoom) {
```
Comment (bramkragten) [inline src/components/chart/state-history-charts.ts]:
```suggestion
        if ("zoom" in chartComponent) {
```

File: src/components/chart/state-history-charts.ts [hunk 7]
```diff
@@ -264,6 +289,70 @@ export class StateHistoryCharts extends LitElement {
...
+    sourceChartIndex?: number
+  ) {
+    this._isSyncing = true;
+
+    requestAnimationFrame(() => {
+      const chartComponents = this.renderRoot.querySelectorAll(
+        "state-history-chart-line, state-history-chart-timeline"
+      );
+
+      chartComponents.forEach((chartComponent: any, index) => {
```
Comment (bramkragten) [inline src/components/chart/state-history-charts.ts]:
```suggestion
      chartComponents.forEach((chartComponent, index) => {
```

File: src/components/chart/state-history-charts.ts [hunk 8]
```diff
@@ -264,6 +289,70 @@ export class StateHistoryCharts extends LitElement {
...
+    start: number,
+    end: number,
+    sourceChartIndex?: number
+  ) {
+    this._isSyncing = true;
+
+    requestAnimationFrame(() => {
+      const chartComponents = this.renderRoot.querySelectorAll(
+        "state-history-chart-line, state-history-chart-timeline"
+      );
```
Comment (bramkragten) [inline src/components/chart/state-history-charts.ts]:
```suggestion
      const chartComponents = this.renderRoot.querySelectorAll(
        "state-history-chart-line, state-history-chart-timeline"
      ) as Array<StateHistoryChartLine | StateHistoryChartTimeline>;
```

File: src/components/chart/ha-chart-base.ts [hunk 9]
```diff
@@ -868,10 +869,80 @@ export class HaChartBase extends LitElement {
...
+      const end = typeof zoom.end === "number" ? zoom.end : 100;
+      const isZoomed = start !== 0 || end !== 100;
+
+      if (isZoomed !== this._isZoomed) {
+        this._isZoomed = isZoomed;
+        this._zoomRatio = (end - start) / 100;
+        fireEvent(this, "chart-zoom", { start, end });
+      }
+    }
+  }
```
Comment (MindFreeze) [inline src/components/chart/ha-chart-base.ts]: What is the purpose of this? We don't set initial start/end values in the options anywhere AFAIK, so this shouldn't do anything

File: src/components/chart/ha-chart-base.ts [hunk 10]
```diff
@@ -1024,5 +1095,12 @@ declare global {
     "dataset-hidden": { id: string };
     "dataset-unhidden": { id: string };
     "chart-click": ECElementEvent;
+    "chart-zoom": {
+      start: number;
+      end: number;
+      chartIndex?: number;
+      startTime?: Date;
+      endTime?: Date;
```
Comment (MindFreeze) [inline src/components/chart/ha-chart-base.ts]: These are not emitted or used by `ha-chart-base` so they shouldn't be here. There should be a new event type for them in the upper components

File: src/components/chart/state-history-chart-line.ts [hunk 11]
```diff
@@ -251,6 +271,7 @@ export class StateHistoryChartLine extends LitElement {
           type: "time",
           min: this.startTime,
           max: this.endTime,
+          boundaryGap: [0, 0],
```
Comment (MindFreeze) [inline src/components/chart/state-history-chart-line.ts]: Is this needed to align the axes?

File: src/components/chart/state-history-chart-timeline.ts [hunk 12]
```diff
@@ -256,6 +261,21 @@ export class StateHistoryChartTimeline extends LitElement {
...
+    chartBase.zoom(start, end, true);
+  }
+
+  private _handleDataZoom(ev: CustomEvent) {
+    fireEvent(this, "chart-zoom", {
+      start: ev.detail.start ?? 0,
+      end: ev.detail.end ?? 100,
+      chartIndex: this.chartIndex,
+      startTime: ev.detail.startTime,
+      endTime: ev.detail.endTime,
```
Comment (MindFreeze) [inline src/components/chart/state-history-chart-timeline.ts]: `startTime` & `endTime` don't seem to be used anywhere, so they can be removed

File: src/components/chart/state-history-charts.ts [hunk 13]
```diff
@@ -264,6 +294,70 @@ export class StateHistoryCharts extends LitElement {
...
+
+    requestAnimationFrame(() => {
+      const chartComponents = this.renderRoot.querySelectorAll(
+        "state-history-chart-line, state-history-chart-timeline"
+      ) as unknown as (StateHistoryChartLine | StateHistoryChartTimeline)[];
+
+      chartComponents.forEach((chartComponent, index) => {
+        if (index === sourceChartIndex) {
+          return;
+        }
```
Comment (MindFreeze) [inline src/components/chart/state-history-charts.ts:330]: `chartIndex` is not the best way for this, because we can just compare the object directly with something like `event.target` but we already use `chartIndex` for the "y-width-changed" sync, so it is fine.

File: src/components/chart/state-history-charts.ts [hunk 14]
```diff
@@ -345,6 +439,25 @@ export class StateHistoryCharts extends LitElement {
...
+      --mdc-icon-size: 24px;
+      color: var(--primary-color);
+      box-shadow: var(--ha-card-box-shadow, 0px 2px 4px rgba(0, 0, 0, 0.16));
+      border: 1px solid var(--divider-color);
+    }
+
+    .floating-reset-button:hover {
+      background: var(--primary-color);
+      color: var(--text-primary-on-accent-color, white);
+    }
```
Comment (MindFreeze) [inline src/components/chart/state-history-charts.ts]: Not used anymore

```suggestion
```

**Review by MindFreeze — CHANGES_REQUESTED** [review]

File: src/components/chart/ha-chart-base.ts (hunk 9 above)
Comment (birrejan) [reply src/components/chart/ha-chart-base.ts]: that's totally right

File: src/components/chart/state-history-chart-line.ts (hunk 11 above)
Comment (birrejan) [reply src/components/chart/state-history-chart-line.ts]: nope

File: src/components/chart/state-history-chart-line.ts [hunk 15]
```diff
@@ -192,6 +197,21 @@ export class StateHistoryChartLine extends LitElement {
...
+    chartBase.zoom(start, end, true);
+  }
+
+  private _handleDataZoom(ev: CustomEvent) {
+    fireEvent(this, "chart-zoom-with-index", {
+      start: ev.detail.start ?? 0,
+      end: ev.detail.end ?? 100,
+      chartIndex: this.chartIndex,
+      startTime: ev.detail.startTime,
+      endTime: ev.detail.endTime,
```
Comment (MindFreeze) [inline src/components/chart/state-history-chart-line.ts]: startTime & endTime are not used anywhere

File: src/components/chart/state-history-charts.ts [hunk 16]
```diff
@@ -29,6 +34,13 @@ const chunkData = (inputArray: any[], chunks: number) =>
 declare global {
   interface HASSDomEvents {
     "y-width-changed": { value: number; chartIndex: number };
+    "chart-zoom-with-index": {
+      start: number;
+      end: number;
+      chartIndex: number;
+      startTime?: Date;
+      endTime?: Date;
```
Comment (MindFreeze) [inline src/components/chart/state-history-charts.ts]: startTime & endTime are not used anywhere

File: src/components/chart/state-history-charts.ts [hunk 17]
```diff
@@ -345,6 +442,12 @@ export class StateHistoryCharts extends LitElement {
     state-history-chart-line {
       width: 100%;
     }
+    .reset-button {
+      position: fixed;
+      bottom: 24px;
+      right: 24px;
```
Comment (MindFreeze) [inline src/components/chart/state-history-charts.ts]: This is something we are adding right now so I don't expect you to know about it but may as well add it

```suggestion
      bottom: calc(24px + var(--safe-area-inset-bottom));
      right: calc(24px + var(--safe-area-inset-right));
```

**Review by MindFreeze — CHANGES_REQUESTED** [review]

File: src/components/chart/state-history-charts.ts (hunk 17 above)
Comment (birrejan) [reply src/components/chart/state-history-charts.ts]: make sense, thanks!

**Review by MindFreeze — CHANGES_REQUESTED** [review]
Found some issues:
- Double click to zoom out doesn't work. Probably a problem with the state of `this._isZoomed`
- Reset button is not rendered even when zoomed
- Ctrl/Cmd + drag with mouse to zoom doesn't sync and only zooms 1 chart

**Review by MindFreeze — APPROVED** [review]
Something must have been wrong with my build. Works great now. Thank you

File: src/components/chart/state-history-charts.ts [hunk 18]
```diff
@@ -345,6 +440,12 @@ export class StateHistoryCharts extends LitElement {
     state-history-chart-line {
       width: 100%;
     }
+    .reset-button {
+      position: fixed;
+      bottom: calc(24px + var(--safe-area-inset-bottom));
+      right: calc(24px + var(--safe-area-inset-bottom));
+      z-index: 1000;
```
Comment (MindFreeze) [inline src/components/chart/state-history-charts.ts]: This seems to be an issue. If you open a dialog (for example more-info with the 'e' shortcut), the reset button is above the dialog

**Review by MindFreeze — CHANGES_REQUESTED** [review]

**Comment by MindFreeze** [comment]
@bramkragten do we still need UX input here ?

**Comment by JanLayola** [comment]
I tested on a pixel 8 with all my entities (more than 500 hundred) and it's usable. Also I don't think it make sense to display that amount of data or more together but it works.

**Review by MindFreeze — APPROVED** [review]
Performance is about what you would expect in my testing as well. It's slow with a lot of charts but not because of the zoom sync. Confirmed by testing with the same entities on dev

**Comment by MindFreeze** [comment]
Thanks you @JanLayola
