### PR TITLE
Fix duplicate fetch of stats metadata in more info

### LINKED ISSUE #15586: More info is making duplicate calls to figure out how to display sensor stats
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Screenshot 2023-02-24 at 1 41 57 PM
Screenshot 2023-02-24 at 1 41 43 PM

### Describe the behavior you expected

Should only have one call to get_statistics_metadata

Not sure if we need the entity registry call either since it should already be loaded

### Steps to reproduce the issue

Click more info for a history only entity and a stats entity

### What version of Home Assistant Core has the issue?

dev

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bdraco**
## Proposed change

fixes #15586

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/more-info/ha-more-info-history.ts [hunk 1]
```diff
@@ -70,6 +73,7 @@ export class MoreInfoHistory extends LitElement {
                 .hass=${this.hass}
                 .isLoadingData=${!this._statistics}
                 .statisticsData=${this._statistics}
+                .metadata=${this._metadata}
```
Comment (bdraco) [inline src/dialogs/more-info/ha-more-info-history.ts:76]: We would fetch it and than discard it.  Now passed to the graph object instead so we don't have to do it again

**Review by bramkragten — APPROVED** [review]
