### PR TITLE
Translate dashboard panel url error message

### LINKED ISSUE #27162: Dashboard panel URL error message contains technical details
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When creating a new dashboard, and something goes shout:

Image

We shouldn't have such error message. The technical details there are not user-friendly.

Ideally the error message should have been shown on the field that is problematic as wel..

### Describe the behavior you expected

User-friendly message

### Steps to reproduce the issue

1. Create a new dashboard
2. Use an dashboard URL/path that is already in use
3. Be amazed.
...

### What version of Home Assistant Core has the issue?

2025.10.0b0

### What was the last working version of Home Assistant Core?

unknown

### In which browser are you experiencing the issue?

Unrelated

### Which operating system are you using to run this browser?

Unrelated

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by steinmn**
## Proposed change

If the user tries to create a new dashboard with a URL that already exist, the current error message contains technical details and is not translatable (#27162).

This PR uses the translation_key from the updated error message in https://github.com/home-assistant/core/pull/153501 to display an improved translated error message.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #27162
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/lovelace/dashboards/dialog-lovelace-dashboard-detail.ts [hunk 1]
```diff
@@ -283,6 +283,15 @@ export class DialogLovelaceDashboardDetail extends LitElement {
       }
       this.closeDialog();
     } catch (err: any) {
+      if (err?.translation_key === "url_already_exists") {
```
Comment (bramkragten) [inline src/panels/config/lovelace/dashboards/dialog-lovelace-dashboard-detail.ts]: We should not use the `translation_key` to identify errors, if there is a `translation_key` we should use the backend provided translation.

**Review by bramkragten — DISMISSED** [review]

File: src/panels/config/lovelace/dashboards/dialog-lovelace-dashboard-detail.ts (hunk 1 above)
Comment (steinmn) [reply src/panels/config/lovelace/dashboards/dialog-lovelace-dashboard-detail.ts]: Ok, any chance I can get a review on the linked backend PR first? Since the proper frontend solution depends on how it ends up being solved in the backend.

**Comment by steinmn** [comment]
borrowed the approach used in developer-tools-action.ts now, so I think it works as intended.

From the original issue:

> Ideally the error message should have been shown on the field that is problematic as wel..

The options I see for this are
- Using `translation_key` to identify the error (which is not desirable)
- Creating a new error code in the backend (which requires refactoring code that affects a larger part of the system than I am comfortable attempting)

so I think I will skip that part.

**Review by silamon — APPROVED** [review]
