### PR TITLE
Add welcome banner for new overview dashboard and fix some dashboard issues

### LINKED ISSUE #29083: Add banner in Home Dashboard when it replaces Overview - non customized Overviews only
### Description

As part of the official release of Home and replacement of Overview as default, we made some rules to make sure this has the lowest impact on existing custom defaults, but its known for people that haven't ever moved from old Overview and didn't even customize it. 

So the rules are:

- New users get Home (now called Overview).
- Existing users with customized Overview or custom dashboard as default, will stay as they are now - no changes
- Existing users with Overview not customized as default, will get changed to the new Overview (Home) and get a banner allowing them to switch back.

This task is for the third scenario.

## The banner

This is a mockup of the actions needed:

Image

- Copy is OK - although we can improve it
- Switch back - creates a new custom dashboard using legacy Overview as a template and sets it as default. And removes the banner.
- Cool its OK - removes the banner and does nothing else.
- Manage dashboards links to the dashboard manager in settings

### Additional context

- Release plan in more detail: https://docs.google.com/document/d/14imEEm1YJ7KSLmbB3Zmd5EF4Tyl2Uk8gNRP1xE3uShE

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Displays a welcome banner on the home panel to inform existing users about the new overview dashboard. The banner includes a "Learn more" button that opens a dialog explaining the changes.

**Banner**
CleanShot 2026-01-28 at 17 10 12

**Dialog**
CleanShot 2026-01-28 at 17 10 41

**Banner visibility conditions:**
- User was onboarded before 2026.2 (no onboarded_version stored)
- User doesn't have a custom `lovelace` dashboard configured
- Only shown the banner once (persisted in system storage)

**Other changes** 
- Store `onboarded_version` and `onboarded_date` during onboarding. This is useful to known when the user onboarded to display the welcome banner. It may be used for future use-cases.
- Fix default panel url when it's `lovelace`.
- Rename "Home" panel to "Overview" panel
- Rename "Overview" strategy to Overview (Legacy)

Translations are not done yet and will need product review so it's ok to merge it to beta without translations.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/29083
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by laupalombi** [comment]
@mbb365 FYI this is the banner - talked with Paul a bit ago and we cannot fit the banner with 3 buttons in mobile. Makes more sense to show it like this. We will iterate the copy in beta too.

**Review by silamon — APPROVED** [review]

File: src/panels/home/dialogs/dialog-new-overview.ts [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+      <ha-wa-dialog
+        .hass=${this.hass}
+        .open=${this._open}
+        header-title="Welcome to your new overview"
+        prevent-scrim-close
+        @closed=${this._dialogClosed}
+      >
+        <div class="content">
+          <p>
+            The overview dashboard has been redesigned to give you a better
```
Comment (bramkragten) [inline src/panels/home/dialogs/dialog-new-overview.ts:56]: This text is not translatable because it is not final yet?

Comment (silamon) [reply src/panels/home/dialogs/dialog-new-overview.ts:56]: "Translations are not done yet and will need product review so it's ok to merge it to beta without translations." from the pull request description

**Review by bramkragten — APPROVED** [review]

File: src/panels/home/dialogs/dialog-new-overview.ts (hunk 1 above)
Comment (silamon) [reply src/panels/home/dialogs/dialog-new-overview.ts:56]: It would be great though if they are translated somewhere mid beta so translators can have time to translate this.

Comment (piitaya) [reply src/panels/home/dialogs/dialog-new-overview.ts:56]: Yeah sure ! Need to check with product team for the final wording 👍

File: src/panels/home/dialogs/dialog-new-overview.ts [hunk 2]
```diff
@@ -0,0 +1,132 @@
...
+              automatically organized by area and floor.
+            </li>
+            <li>
+              <strong>Favorites</strong> - Pin your most used entities to the
+              top for quick access.
+            </li>
+          </ul>
+          <h3>Your existing dashboards</h3>
+          <p>
+            Your manual dashboards are still available in the sidebar. This new
```
Comment (laupalombi) [inline src/panels/home/dialogs/dialog-new-overview.ts:72]: > Your manual dashboards are still available in the sidebar. Miss the old format? You can have it by creating a new dashboard using the "Overview (legacy)" template in <a href="/config/lovelace/dashboards" @click=${this.closeDialog}>dashboard settings</a and then setting it to Default.

I would just change this paragraph, the rest is fine.

**Review by laupalombi — COMMENTED** [review]
@piitaya this is the only copy change I would suggest, and for me its ready for translations. Sorry for the delay!
