### PR TITLE
Don't show toggle always on more info

### LINKED ISSUE #8799: group more-info shows toggle on group with binary entities only
### Checklist

I have updated to the latest available Home Assistant version.
I have cleared the cache of my browser.
I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

as title, having a group consisting of only binary_sensors, the more-info show a non functional toggle

### Describe the behavior you expected

no toggle when none of the entities it togglable

### Steps to reproduce the issue

1. click entity
2.
3.
...

### What version of Home Assistant Core has the issue?

up to 2021.4.0b02

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

all

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```yaml
# Paste your state here.

```

### Problem-relevant frontend configuration

```yaml
# Paste your YAML here.
type: entity
entity: group.doors_open
name: Doors open
```

and group:
```
group:
 Doors open:
   - binary_sensor.back_door_is_open
   - binary_sensor.corridor_door_is_open
   - binary_sensor.front_door_is_open
   - etcetc
 ```
or 
```
group:
 doors_open:
   name: Doors open
   entities:
     - binary_sensor.back_door_is_open
     - binary_sensor.corridor_door_is_open
     - binary_sensor.front_door_is_open
```
### Javascript errors shown in your browser console/inspector

```txt
# Paste your logs here.

```

Schermafbeelding 2021-04-02 om 10 36 31

Schermafbeelding 2021-04-02 om 10 32 21

### PR DESCRIPTION
**Pull request by zsarnett**
## Proposed change

image
image

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #8799
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/common/entity/can_toggle_state.ts [hunk 1]
```diff
@@ -6,9 +6,17 @@ import { supportsFeature } from "./supports-feature";
 
 export const canToggleState = (hass: HomeAssistant, stateObj: HassEntity) => {
   const domain = computeStateDomain(stateObj);
+
   if (domain === "group") {
-    return stateObj.state === "on" || stateObj.state === "off";
+    for (const entity of stateObj.attributes.entity_id) {
+      const d = computeStateDomain(hass.states[entity]);
+      if (canToggleDomain(hass, d)) {
+        return stateObj.state === "on" || stateObj.state === "off";
```
Comment (bramkragten) [inline src/common/entity/can_toggle_state.ts:14]: should this be the state of `entity`?

File: src/common/entity/can_toggle_state.ts [hunk 2]
```diff
@@ -6,9 +6,17 @@ import { supportsFeature } from "./supports-feature";
 
 export const canToggleState = (hass: HomeAssistant, stateObj: HassEntity) => {
   const domain = computeStateDomain(stateObj);
+
   if (domain === "group") {
-    return stateObj.state === "on" || stateObj.state === "off";
+    for (const entity of stateObj.attributes.entity_id) {
+      const d = computeStateDomain(hass.states[entity]);
```
Comment (bramkragten) [inline src/common/entity/can_toggle_state.ts:12]: `hass.states[entity]` can be undefined

File: src/common/entity/can_toggle_state.ts (hunk 1 above)
Comment (zsarnett) [reply src/common/entity/can_toggle_state.ts:14]: No its should be the main group
This basically checks if toggle is possible and then it should use the group state for the on and off 
otherwise it would be different that the previous functionality when toggle is present

**Review by bramkragten — APPROVED** [review]
