### PR TITLE
Ensure we always have an active theme name (fixes dark theme issues)

### LINKED ISSUE #10514: Dark mode theme switch colors no longer being applied
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Looks like switch-checked-button-color and switch-unchecked-button-color are no longer themeable, and grab their color values from other parts of the system.

### Describe the behavior you expected

It used to be you could define discrete color values for switches in dark mode. This still works for switches in light mode.

### Steps to reproduce the issue

1. Apply theme with defined switch colors

### What version of Home Assistant Core has the issue?

core-2021.11.0

### What was the last working version of Home Assistant Core?

core-2021.10.7

### In which browser are you experiencing the issue with?

Safari, Google Chrome, Edge

### Which operating system are you using to run this browser?

iOS 15, Windows 11

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

```yaml
switch-checked-button-color: rgb(255, 255, 255)
switch-checked-track-color: rgb(48, 208, 88)
switch-unchecked-button-color: var(--switch-checked-button-color)
switch-unchecked-track-color: rgb(154, 160, 166)
```

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### LINKED ISSUE #10529: CSS variables incorrect in <hui-view> in the "dark" color mode
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Theme: [IBM1970 theme](https://github.com/andornaut/homeassistant-ibm1970-theme), which supports dark and light modes. (I am the author of this theme)

Since upgrading to 2021.11.0, the` --primary-background-color`,  `--card-background-color` and possibly other CSS variable values are not propagated to the main content area of the overview page when in dark mode. These same values are propagated correctly when in light mode. In fact, simply renaming "dark" to "light" in the [theme's YAML](https://github.com/andornaut/homeassistant-ibm1970-theme/blob/main/themes/ibm1970.yaml#L20) and then selecting the light mode in the user profile works-around this issue (though, this is not ideal, because the bug continues to be in effect if the dark mode is selected). Note that this appears to only affect the "Overview" page, but I haven't checked all possible pages.

In the example below, the expected `--primary-background-color` is "#464333", but is "#111111" present instead.

```
<ha-app-layout> /* has expected --primary-background-color */
    <hui-view> /* does NOT have expected --primary-background-color */
```
### Expected
Highlighting the custom element - `<ha-app-layout>` with the correct CSS variable value: #464333
1 expected

### Wrong
Highlighting the custom element - `<hui-view>` with the **incorrect** CSS variable value: #111111
2 wrong

### Expected after renaming "dark" to "light"

After swapping "light" and "dark" in the [theme's YAML](https://github.com/andornaut/homeassistant-ibm1970-theme/blob/main/themes/ibm1970.yaml#L20), and then selecting "light" (but since the names were swapped this actually uses the "dark" configuration as in the examples above), the bug is no longer present. The bug is present when selecting the dark mode (but now using the configuration that was formerly the "light" mode, since the names were swapped). This shows that this bug is only present when the dark mode is selected regardless of theme configuration.

3 expected

### Describe the behavior you expected

The color set in the theme applies to the main content area of the overview page.

### Steps to reproduce the issue

1. Install a theme that customizes the --primary-background-color CSS variable.
2. Select "dark" mode
3. Navigate to the Overview page
4. Note that the background color is not the one set by the theme.

### What version of Home Assistant Core has the issue?

core-2021.11.0

(The bug was also present in core-2021.11.0b0)

### What was the last working version of Home Assistant Core?

core-2021.10.7

### In which browser are you experiencing the issue with?

Firefox 90.0 and Chrome 95.0

### Which operating system are you using to run this browser?

Ubuntu 20.10

### State of relevant entities

_No response_

#### themes/ibm1970.yaml

```yaml
ibm1970:
  accent-color: '#33a999'
  app-header-background-color: 'var(--sidebar-background-color)'
  app-header-edit-background-color: 'var(--accent-color)'
  app-header-text-color: 'var(--sidebar-text-color)'
  disabled-text-color: '#999'
  label-badge-green: 'var(--accent-color)'
  light-primary-color: '#eeeccc'
  scrollbar-thumb-color: 'var(--sidebar-background-color)'
  sidebar-icon-color: 'var(--sidebar-text-color)'
  sidebar-selected-icon-color: 'var(--primary-text-color)'
  sidebar-selected-text-color: 'var(--primary-text-color)'
  state-icon-active-color: '#d0b550'
  switch-unchecked-button-color: 'var(--scrollbar-thumb-color)'
  switch-unchecked-track-color: 'var(--scrollbar-thumb-color)'
  text-primary-color: 'var(--card-background-color)'
  modes:
    dark:
      card-background-color: '#646050'
      divider-color: '#24201a'
      error-color: '#d55'
      mdc-theme-on-secondary: 'var(--card-background-color)'
      primary-background-color: '#464333'
      primary-color: '#ccc8b0'
      primary-text-color: '#eeeccc'
      secondary-background-color: '#9c9977'
      secondary-text-color: '#9c9977'
      sidebar-background-color: '#7c7755'
      sidebar-text-color: '#24201a'
      state-icon-color: 'var(--primary-background-color)'
    light:
      card-background-color: '#dddccc'
      divider-color: 'var(--primary-color)'
      error-color: '#b11'
      primary-background-color: '#eed'
      primary-color: '#646050'
      primary-text-color: '#24201a'
      secondary-background-color: 'var(--card-background-color)'
      secondary-text-color: '#646050'
      sidebar-background-color: '#ccc8b0'
      sidebar-text-color: 'var(--primary-color)'
      state-icon-color: 'var(--primary-color)'
```

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

This is what the dark mode color theme should look like:
dark-colors-small

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Some calls to `apply_themes_on_element` did not have an actual `selectedTheme` value resulting in themes being applied only partially.

With this PR we now have a globally active theme name in `hass.themes.theme` similar to the existing `darkMode`. Those values are different from the `themeSettings` since those represent the settings made on the theme picker, but do not necessarily represent the actually active values during runtime (e.g. dark mode can be auto `undefined/auto in `themeSettings` and the real value is in `hass.themes` and similar for backend-selected them names).

With this PR we have a clear separation of concerns. So the parameters for `apply_themes_on_element()` are:

1. `element`: The element to apply the theme on
2. `themes`: The hass.themes active info (includes the active dark mode and the active global theme e.g. derived from "Backend-selected")
3. `selectedTheme` Parameter to override the global theme, in case e.g. a card has another theme set in the card config
4. `themeSettings`:  Used only to pass additional attributes in = selected colors for default theme. The theme name and dark flag have no runtime relevance as they represent the theme settings for the theme picker.

**Note**: I don't have a hassio dev instance, so untested in that area.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #10529 fixes #10514
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/state/themes-mixin.ts [hunk 1]
```diff
@@ -89,6 +85,7 @@ export default <T extends Constructor<HassBaseEl>>(superClass: T) =>
       }
 
       themeSettings = { ...this.hass.selectedTheme, dark: darkMode };
+      this.hass.themes.theme = themeName;
```
Comment (bramkragten) [inline src/state/themes-mixin.ts:88]: This will not trigger an update of `themes`:
```suggestion
      this._updateHass({
          themes: { ...this.hass.themes!, theme: themeName },
      });```

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
