### PR TITLE
Don't filter attributes when saving scene

### LINKED ISSUE #4277: Scene editor missing entity states (f.e. for covers)
**Home Assistant release with the issue:**

0.102.2

**Last working Home Assistant release (if known):**
-

**Operating environment (Hass.io/Docker/Windows/etc.):**

hass.io

**Integration:**

**Description of problem:**
The new scene editor does not correctly store the state of the entities in the yaml file. F.e. for covers, the `current_position` is not stored. So when I'd like to create a scene with the blinds half way down, they will be open since the main state is `open` and neither a `current_position` nor `current_tilt_position` seem to be stored. Same probably applies to other entities, but not tested yet.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**

### LINKED ISSUE #4279: Missing attributes in SCENE_SAVED_ATTRIBUTES
**Description of problem:**

The following attributes are missing here:
https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/data/scene.ts#L21-L51

I'll look up the strings soon

### Counter
-  ATTR_INITIAL - `initial`
-  ATTR_MAXIMUM - `maximum`
-   ATTR_MINIMUM - `minimum`
-   ATTR_STEP - `step`

### Cover
-  ATTR_CURRENT_POSITION - `current_position`
-  ATTR_CURRENT_TILT_POSITION - `current_tilt_position`

### Fan
-  ATTR_OSCILLATING - `oscillating`

### Input datetime
-  CONF_HAS_DATE - `has_date`
-  CONF_HAS_TIME - `has_time`

### Input select
-  ATTR_OPTION - `option`
-  ATTR_OPTIONS - `options`

### Timer
-  ATTR_DURATION - `duration`

### Vacuum
-  ATTR_FAN_SPEED - `fan_speed`
-  `cleaning_mode` is not supported by base vacuum devices

### Water Heater
-  ATTR_AWAY_MODE - `away_mode`
- Be aware that `operation_mode` is equal to `state`, isn't it ?

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/4277
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/4279

### CODE REVIEW

File: src/data/scene.ts [hunk 1]
```diff
@@ -19,6 +19,26 @@ export const SCENE_IGNORED_DOMAINS = [
 ];
 
 export const SCENE_SAVED_ATTRIBUTES = {
+  counter: ["initial", "maximum", "minimum", "step"],
+  cover: [
+    "current_position",
+    "current_tilt_position",
+    "position",
+    "tilt_position",
```
Comment (Santobert) [inline src/data/scene.ts]: There aren't device state attributes. I've added them by mistake

File: src/data/scene.ts [hunk 2]
```diff
@@ -35,19 +55,9 @@ export const SCENE_SAVED_ATTRIBUTES = {
...
-    "fan_mode",
-    "swing_mode",
-    "hvac_mode",
-    "preset_mode",
-  ],
-  vacuum: ["cleaning_mode"],
-  fan: ["speed", "current_direction"],
-  water_heather: ["temperature", "operation_mode"],
+  timer: ["duration"],
+  vacuum: ["cleaning_mode", "fan_speed"],
```
Comment (Santobert) [inline src/data/scene.ts]: I'm not aware of an attribute `cleaning_mode` of vacuum devices. The base vacuum devices only know `fan_speed`.

File: src/data/scene.ts [hunk 3]
```diff
@@ -35,19 +55,9 @@ export const SCENE_SAVED_ATTRIBUTES = {
...
+  water_heather: ["temperature", "operation_mode", "away_mode"],
```
Comment (Santobert) [inline src/data/scene.ts]: `operation_mode` is always equal to the `state`
