### PR TITLE
Use new scaling features of round-slider

### LINKED ISSUE #4069: Thermostat card doesn't support well RTL languages
**Checklist:**

- [v ] I updated to the latest version available
- [ v] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.100.2

**Last working Home Assistant release (if known):** Unknown

**UI (States or Lovelace UI?):** 20191002.2 - latest

**Browser and Operating System:** Chrome version 77.0.3865.120, Windows 10x64

**Description of problem:**

While using Right-To-Left languages (such as Hebrew which I use), the thermostat card displays the round slider completely messed-up. I am not that much skilled with frontend, but I found that the origin of it is in the library that is used for rounded sliders, which doesn't handle rtl in html correctly. I tested the GUI in developer mode of chrome and added to the containing div tag a dir="ltr" attribute and it fixed the issue. As I'm not sure it is the best solution for such a problem (again not a frontend dev) I just taged in this issue the line I think the attribute dir="ltr" can be added to solve it.

Some images of the error and solution:
image
image

**Additional information:**
Link to the possible line in which the issue can be fixed: https://github.com/home-assistant/home-assistant-polymer/blob/f5e3a9ad403a5199ae27247df978000e82bbd58a/src/panels/lovelace/cards/hui-thermostat-card.ts#L130

### LINKED ISSUE #4156: Thermostat Card Title Size
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.101.0

**Last working Home Assistant release (if known):**
0.100 (at least I didn't notice it)

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome (latest)

**Description of problem:**
See screenshot below, my two thermostat cards have different title font sizes. The 'Bedroom AC' one is too large and interferes with the slider. Resizing the frame changes it and seems to fix it at almost all other ratios, however this default one (full screen on a 1920x1080) seems a bit tight. Happens on all views.

image

**Javascript errors shown in the web inspector (if applicable):**

```
N/A
```

**Additional information:**

### LINKED ISSUE #4157: Generic thermostat "broke font size"
Home Assistant release with the issue: 0.101.0

Last working Home Assistant release (if known): 0.100

Operating environment (Hass.io/Docker/Windows/etc.):
 Hass.io on a RPi4

Description of problem: 

Desktop
shot2

Mobile

It is not possible to put two generic_thermostat side by side because fonts are now too big and overlaps with other infos.

Please fix

### LINKED ISSUE #4175: Ecobee / generic thermostat ring broken in idle mode
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**

.101

**Last working Home Assistant release (if known):**

.100.3

**UI (States or Lovelace UI?):**

**Browser and Operating System:**

iOS 13

**Description of problem:**

When the thermostat is idle mode, the ring extends past the ring boundaries.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

5E96FA98-DBC7-4CBD-8E8B-9C7F1D24341D

### PR DESCRIPTION
**Pull request by thomasloven**
Not the best comparison, but Before:
Skärmavbild 2019-11-01 kl  22 43 57

After:
Skärmavbild 2019-11-01 kl  22 44 11

Everything scales dynamically and looks good down to about 200 px wide cards.

I have no idea what I'm doing when it comes to npm and yarn and stuff, so I'd appreciate if someone could make sure this won't mess up things too bad...

---

Fixes #4157
Fixes #4156
May fix #4069
Fixes #4175 by proxy - Though there's still a potential backend problem here!

### CODE REVIEW

**Comment by thomasloven** [comment]
Fixes #4157

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 1]
```diff
@@ -345,6 +344,7 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
         .mode="${mode}"
         .icon="${modeIcons[mode]}"
         @click="${this._handleModeClick}"
+        tabindex="0"
```
Comment (iantrich) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: enter wont work here. need to use action-handler or listen to keyup

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 2]
```diff
@@ -106,124 +101,149 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
       </ha-card>
     `;
   }
 
+  protected rescale_svg() {
+    // Set the viewbox of the SVG containing the set temperature to perfectly
+    // fit the text
+    // That way it will auto-scale correctly
+    // This is not done to the SVG containing the current temperature, because
+    // it should not be centered on the text, but only on the value
```
Comment (iantrich) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: :sunglasses:

**Comment by bramkragten** [comment]
I like it, but I think the light icon should be smaller and there should be more padding on the card; 16px following material guidelines

**Comment by thomasloven** [comment]
New paddings
Skärmavbild 2019-11-02 kl  22 34 04

**Comment by thomasloven** [comment]
I also locked down (I think) the version of the round-slider package. I don't trust the maintainer not to publish breaking changes without warning.

**Comment by iantrich** [comment]
Good call. I've heard stories about that guy

**Comment by iantrich** [comment]
Bram, okay to push this into next beta?

**Comment by bramkragten** [comment]
> Bram, okay to push this into next beta?

I'm going to review this today and will push it to beta (if ok)

File: src/panels/lovelace/cards/hui-light-card.ts [hunk 3]
```diff
@@ -93,36 +95,38 @@ export class HuiLightCard extends LitElement implements LovelaceCard {
...
         </div>
 
-        <div id="tooltip">
+        <div id="info">
           <div class="brightness" @ha-click="${this._handleClick}">
-            ${brightness} %
-          </div>
-          <div class="name">
-            ${this._config.name || computeStateName(stateObj)}
+            &nbsp;&nbsp;${brightness} %
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-light-card.ts]: Why are the  `&nbsp;&nbsp;` necessary?

File: src/panels/lovelace/cards/hui-light-card.ts [hunk 4]
```diff
@@ -159,110 +163,9 @@ export class HuiLightCard extends LitElement implements LovelaceCard {
...
-          color: var(--secondary-text-color);
-        }
-      </style>
-    `;
-  }
-
   private _dragEvent(e: any): void {
     this.shadowRoot!.querySelector(".brightness")!.innerHTML =
-      e.detail.value + "%";
+      "&nbsp;" + e.detail.value + " %";
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-light-card.ts]: Why the `&nbsp;` and please use a template literal

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 5]
```diff
@@ -106,124 +102,149 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
+              .min=${stateObj.attributes.min_temp}
+              .max=${stateObj.attributes.max_temp}
+              .step=${this._stepSize}
+              @value-changing=${this._dragEvent}
+              @value-changed=${this._setTemperature}
+            ></round-slider>
+          `;
+
+    const currentTemperature = stateObj.attributes.current_temperature
+      ? html`
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: Use `svg` instead of `html`

Comment (bramkragten) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: https://lit-html.polymer-project.org/api/modules/lit_html.html#svg

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 6]
```diff
@@ -106,124 +102,149 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
+              ${stateObj.attributes.current_temperature}
+              <tspan dx="-4" dy="-7" style="font-size: 5px;">
+                ${this.hass.config.unit_system.temperature}
+              </tspan>
+            </text>
+          </svg>
+        `
+      : "";
+
+    const setValues = html`
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]:
```suggestion
    const setValues = svg`
```

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 7]
```diff
@@ -106,124 +102,149 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
+              .sort(compareClimateHvacModes)
+              .map((modeItem) => this._renderIcon(modeItem, mode))}
+          </div>
+          ${name}
+        </div>
       </ha-card>
     `;
   }
 
+  protected rescale_svg() {
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: Why `protected`?

**Comment by bramkragten** [comment]
I really like how this scales, but I do think especially the light cards gets way to big. I personally think it looks better with a `max-width` of 200px.

**Comment by bramkragten** [comment]
One other thing we have to take in to account, by making the text in the thermostat card a SVG, it will no longer be accessible by screen readers I think.

File: src/panels/lovelace/cards/hui-light-card.ts (hunk 3 above)
Comment (thomasloven) [reply src/panels/lovelace/cards/hui-light-card.ts]: This has been removed. It's all done in `_dragEvent` anyway.

File: src/panels/lovelace/cards/hui-light-card.ts (hunk 4 above)
Comment (thomasloven) [reply src/panels/lovelace/cards/hui-light-card.ts]: `&nbsp`s are for alignment.
I don't want `50 %` to be perfectly centered, but shifted slightly to the right for balance.
I suppose the same thing could be done with an `em`-based offset, but this was simpler.

File: src/panels/lovelace/cards/hui-thermostat-card.ts (hunk 7 above)
Comment (thomasloven) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: Because I have no idea what I'm doing.

**Comment by thomasloven** [comment]
I agree about the max-width. It's been adjusted.

It seems screen readers *do* handle svg `<text>` https://stackoverflow.com/a/41064784/1975194

Also rebased onto recent `dev`.

File: src/panels/lovelace/cards/hui-thermostat-card.ts (hunk 7 above)
Comment (iantrich) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: I know that game 😂

Comment (bramkragten) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: `protected` means a class that extends this class can overwrite it, so not needed here :-)

File: src/panels/lovelace/cards/hui-light-card.ts (hunk 4 above)
Comment (bramkragten) [reply src/panels/lovelace/cards/hui-light-card.ts]: Can't you use padding?

File: src/panels/lovelace/cards/hui-thermostat-card.ts (hunk 7 above)
Comment (bramkragten) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: So here it should be `private`, private class members can be accessed from within the class only.

File: src/panels/lovelace/cards/hui-light-card.ts (hunk 4 above)
Comment (thomasloven) [reply src/panels/lovelace/cards/hui-light-card.ts]: That works.

File: src/panels/lovelace/cards/hui-thermostat-card.ts [hunk 8]
```diff
@@ -416,144 +425,96 @@ export class HuiThermostatCard extends LitElement implements LovelaceCard {
...
+
+      #slider-center {
         position: absolute;
-        top: 0;
-        left: 0;
-        right: 0;
-        height: 100%;
+        width: calc(100% - 40px);
+        height: calc(100% - 40px);
+        xborder: 1px green solid;
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-thermostat-card.ts]: Is `xborder` a typo or something I don't know?

Comment (thomasloven) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: You're not keeping up with the latest properties?

Comment (thomasloven) [reply src/panels/lovelace/cards/hui-thermostat-card.ts]: Let's call it a comment...

**Review by bramkragten — APPROVED** [review]

**Comment by Ahoui-group** [comment]
Please check the impact on a front end light where the light entity is created from a switch device and where no round slider is required. Seems to be broken in 102.0. No on/off bulb showing in front-end.

**Comment by bramkragten** [comment]
Please don't reply to merged PR, and there is already a fix in place for this. Thanks for reporting.
