### PR TITLE
Fix fan speed for new more info and tile feature

### LINKED ISSUE #16022: Fan preset mode Medium pushes High instead of Medium with 2023.4.x beta
### The problem

The new fan card of the home assistant beta (2023.4.0b3), seems to be sending speed mode 3 when pressing medium. I'm testing this with an esphome device (ifan03), with speed_count = 3 in esphome.

image

When not setting speed_count = 3 in esphome (thereby defaulting back to speed_count=100), the normal % slider is displayed, and i have no issues to switch from low, medium and high when using that slider.

### What version of Home Assistant Core has the issue?

core-2023.4.0b3

### What was the last working version of Home Assistant Core?

_No response_

### What type of installation are you running?

Home Assistant OS

### Integration causing the issue

Fan

### Link to integration documentation on our website

https://www.home-assistant.io/integrations/fan/

### Diagnostics information

_No response_

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/16022
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/data/fan.ts [hunk 1]
```diff
@@ -102,6 +102,6 @@ export function computeFanSpeedStateDisplay(
   const currentSpeed = speed ?? stateObj.attributes.percentage;
 
   return currentSpeed
-    ? `${Math.round(currentSpeed)}${blankBeforePercent(locale)}%`
+    ? `${Math.floor(currentSpeed)}${blankBeforePercent(locale)}%`
```
Comment (piitaya) [inline src/data/fan.ts:105]: Core do not round value but only keep the integer value.

**Review by bramkragten — APPROVED** [review]
