### PR TITLE
Fix history timeline showing same color for all zones

### LINKED ISSUE #14705: Different zones in History have same color
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Earlier different zones in History have different colors when displaying a history for `person` or `device_tracker` entities.
Since 2022.12 all zones have SAME color which makes graphs not easy to analyse.

### Describe the behavior you expected

1. Different zones must have different colors.
2. Same zone must have same color on graph.
3. If possible - same zone must have same color on all graphs.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2022.12.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chrome 108.0.5359.99 

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Fix for person and device_tracker entities where all zone states (e.g. "Kitchen", "Office", "Living Room") displayed with the same color in the history timeline, making the graph impossible to read.

This doesn't make the colors deterministic based on the zone name but they are consistent on the graph and activity log.

State based CSS var is kept for backwards compatibility.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #14705
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [x] I understand the code I am submitting and can explain how it works.
- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] I have followed the [perfect PR recommendations][perfect-pr]
- [x] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [x] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure
[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/components/chart/timeline-color.ts [hunk 1]
```diff
@@ -32,6 +33,22 @@ function computeTimelineStateColor(
...
 
+  const domain = computeDomain(stateObj.entity_id);
+
+  // Zone states for person/device_tracker don't have specific CSS color variables,
+  // so they all fall back to the same --state-person-active-color.
+  // Only use a custom CSS variable if explicitly defined (e.g. --state-person-kitchen-color),
+  // otherwise return undefined to get unique colors from the generic color handler.
+  if (
+    (domain === "person" || domain === "device_tracker") &&
+    !(FIXED_DOMAIN_STATES[domain] as readonly string[]).includes(state)
```
Comment (wendevlin) [inline src/components/chart/timeline-color.ts]:
```suggestion
    !((FIXED_DOMAIN_STATES[domain] || []) as readonly string[]).includes(state)
```

Just to be sure, if there is a domain not set in fixed domain we would raise a js error with the includes.

**Review by wendevlin — CHANGES_REQUESTED** [review]

**Comment by ildar170975** [comment]
Currently I can define these variables in a theme - and they are respected:
image
```
  state-person-home-color: purple
  state-person-xxxxx-color: cyan
```
where `xxx` is a slugified zone name.
Will it work with this PR?
Please don't break.
Seems that you already stated that these vars will still work - just in case I am asking to be sure.

**Comment by MindFreeze** [comment]
> Currently I can define these variables in a theme - and they are respected: image
> 
> ```
>   state-person-home-color: purple
>   state-person-xxxxx-color: cyan
> ```
> 
> where `xxx` is a slugified zone name. Will it work with this PR? Please don't break. Seems that you already stated that these vars will still work - just in case I am asking to be sure.

They are still respected

**Review by wendevlin — APPROVED** [review]

**Comment by ShadowJonathan** [comment]
I can confirm this works now, thanks!!
