### PR TITLE
Fix get card size for lazy elements

### LINKED ISSUE #5321: getCardSize is called before child cards have been created in custom-cards
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Since the lazy-loading of cards has been introduced, custom-cards stacking other cards can't properly compute the size of the card as the child/children of the custom-card are not defined when `getCardSize` is called.

## Expected behavior

getCardSize should be called asynchronously or called after the element has been updated completely.

## Steps to reproduce

This is how it is implemented right now in my card:
https://github.com/custom-cards/stack-in-card/blob/master/src/stack-in-card.ts#L120
https://github.com/custom-cards/stack-in-card/blob/master/src/stack-in-card.ts#L148-L150

It should return the size of the child element but always returns 1 because `this._card` is assigned later on because of the (`await HELPERS`)

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known): `< 0.106`
- Browser and browser version: N/A
- Operating system: N/A

## Problem-relevant configuration

Not relevant.

## Javascript errors shown in your browser console/inspector

None

### LINKED ISSUE #6038: Wrong display of vertical stack
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

I have 3 vertical stack within my view, by default they are showned 2 columns next to the others (like in the video bellow ), but when i edit the view and then close the editor without any changes the 3 clomuns are next to the others.

It seems to be related to the iframe card because i have another view with a iframe card and i have the same issue. The others view that containe vertical stack cards but without iframe cards are working correclty.

## Expected behavior

The 3 columns ( vertical-card ) need to be displayed next to the others.

## Steps to reproduce

Add 3 vertical stack cards, in the first one add 2 picture-entity cards, in the second an iframe card and in the last a weather card and also an iframe card.

## Environment

- Home Assistant release with the issue: 0.110.2
- Last working Home Assistant release (if known): 0.108 ( if i remember well )
- Browser and browser version: Chrome 
- Operating system: Windows 10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

No errros
```txt

```

## Additional information
Overview - Home Assistant 2020-05-25 10-23-26

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

`getCardSize` can now be an async function. `computeCardSize` will wait till an element is defined and then call `getCardSize`. This makes sure that the correct card size is reported at first load for all our built-in cards.

When building the view we will first add all columns (unlike before, where we would first calculate the columns based on card size) and then start filling them waiting for `getCardSize` for every card, or the next render after every 5 cards added.

Adding all columns does mean that the layout will jump if we have to remove a column at the end. This usually is not a big deal as that is the case with a small number of cards and that should render quickly.

Fixes https://github.com/home-assistant/frontend/issues/5321

For custom cards that would not be defined yet when the card is created, this still does not work correctly yet, but never has worked correctly. It would always get the size of the error card when the element was not defined yet.

I will check for a solution for that next.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by balloob** [comment]
Marked as breaking change because any custom stack card will need to be able to deal with this.

File: src/panels/lovelace/cards/hui-entity-filter-card.ts [hunk 1]
```diff
@@ -26,8 +26,8 @@ class EntityFilterCard extends UpdatingElement implements LovelaceCard {
 
   private _oldEntities?: EntityFilterEntityConfig[];
 
-  public getCardSize(): number {
-    return this._element ? computeCardSize(this._element) : 1;
+  public async getCardSize(): Promise<number> {
+    return this._element ? await computeCardSize(this._element) : 1;
```
Comment (balloob) [inline src/panels/lovelace/cards/hui-entity-filter-card.ts:30]: We can do a micro optimization here by bypassing a promise if we don't have an element. Would that be beneficial? 

```suggestion
  public getCardSize(): number | Promise<number> {
    return this._element ? computeCardSize(this._element) : 1;
```

File: src/panels/lovelace/cards/hui-horizontal-stack-card.ts [hunk 2]
```diff
@@ -3,17 +3,20 @@ import { computeCardSize } from "../common/compute-card-size";
...
+  public async getCardSize(): Promise<number> {
+    if (!this._cards) {
+      return 0;
     }
 
-    return totalSize;
+    const promises: Promise<number>[] = [];
+
+    for (const element of this._cards) {
+      promises.push(computeCardSize(element));
```
Comment (balloob) [inline src/panels/lovelace/cards/hui-horizontal-stack-card.ts:14]: This doesn't always have to be a promise?

Comment (balloob) [reply src/panels/lovelace/cards/hui-horizontal-stack-card.ts:14]: Oh my bad, `computeCardSize` does always return a promise.

File: src/panels/lovelace/common/compute-card-size.ts [hunk 3]
```diff
@@ -1,5 +1,13 @@
 import { LovelaceCard } from "../types";
 
-export const computeCardSize = (card: LovelaceCard): number => {
-  return typeof card.getCardSize === "function" ? card.getCardSize() : 4;
+export const computeCardSize = async (card: LovelaceCard): Promise<number> => {
+  if (typeof card.getCardSize === "function") {
+    return card.getCardSize();
+  }
+  if (customElements.get(card.localName)) {
```
Comment (balloob) [inline src/panels/lovelace/common/compute-card-size.ts:7]: From https://developer.mozilla.org/en-US/docs/Web/API/Node/localName:

image

```suggestion
  if (customElements.get(card.tagName)) {
```

File: src/panels/lovelace/common/compute-card-size.ts [hunk 4]
```diff
@@ -1,5 +1,13 @@
...
+    return 1;
+  }
+  return customElements.whenDefined(card.localName).then(() => {
+    return computeCardSize(card);
+  });
```
Comment (balloob) [inline src/panels/lovelace/common/compute-card-size.ts:12]: Should we do `await` here to make the stack traces nicer ? 

```suggestion
  await customElements.whenDefined(card.localName)
  return computeCardSize(card);
```

File: src/panels/lovelace/views/hui-view.ts [hunk 5]
```diff
@@ -226,59 +226,64 @@ export class HUIView extends LitElement {
       root.removeChild(root.lastChild);
     }
 
-    let columns: [number, number][][] = [];
     const columnEntityCount: number[] = [];
+    const columnElements: HTMLDivElement[] = [];
     for (let i = 0; i < this.columns!; i++) {
```
Comment (balloob) [inline src/panels/lovelace/views/hui-view.ts:231]: I wonder if we can do a small optimization here that we never make more columns than that we have cards: `Math.min(this.columns, this._cards.length)`.

File: src/panels/lovelace/views/hui-view.ts [hunk 6]
```diff
@@ -217,7 +217,7 @@ export class HUIView extends LitElement {
     root.style.display = elements.length > 0 ? "block" : "none";
   }
 
-  private _createColumns() {
+  private async _createColumns() {
```
Comment (balloob) [inline src/panels/lovelace/views/hui-view.ts:220]: Could we add some comments to each block to describe what we're doing?

File: src/panels/lovelace/views/hui-view.ts [hunk 7]
```diff
@@ -226,59 +226,64 @@ export class HUIView extends LitElement {
...
+      columnElements.push(columnEl);
     }
 
-    this._cards.forEach((el, index) => {
-      const cardSize = computeCardSize(
+    let cardsAdded = 0;
+
+    for (const [index, el] of this._cards.entries()) {
+      const cardSizeProm = computeCardSize(
         (el.tagName === "HUI-CARD-OPTIONS" ? el.firstChild : el) as LovelaceCard
```
Comment (balloob) [inline src/panels/lovelace/views/hui-view.ts:243]: Would it be faster to check `this.lovelace!.editMode` here instead of `el.tagName` ? Even better if we store editMode as a local variable.

File: src/panels/lovelace/views/hui-view.ts [hunk 8]
```diff
@@ -226,59 +226,64 @@ export class HUIView extends LitElement {
...
       );
-      columns[getColumnIndex(columnEntityCount, cardSize)].push([
+      let waitProm: Promise<unknown>;
+      if (cardsAdded > 5) {
```
Comment (balloob) [inline src/panels/lovelace/views/hui-view.ts:246]: So in the old approach each column had their own counter and it would pause for a render after it had added more than 5 "card size units". 

Now we're doing 5 cards, which could be a lot when we're doing vertical stack cards etc. 

I wonder if we can do a new approach here where we just check the time elapsed and if it's time for a pause?

```ts
let start = new Date()
const fps = 60;
const timePerFrame = 1000 / fps;
if (new Date() - start > timePerFrame) {
  waitProm = …
}
``` 

Awaiting card sizes can take until after next render, in that case we are not resetting `cardsAdded`. I wonder if we should treat that differently.

Untested, but would something like this work:

```ts
let tillNextRender = undefined;
let start = undefined;

for (const [index, el] of this._cards.entries()) {
  if (tillNextRender === undefined) {
    tillNextRender = nextRender().then(() => {
      tillNextRender = undefined;
      start = undefined;
    })
  }
    
  let waitProm = undefined;

  if (start === undefined) {
    start = new Date()
    waitProm = Promise.resolve()
  } else if (new Date() - start > 16) {
    waitProm = tillNextRender
  } else {
    waitProm = Promise.resolve()
  }

  const cardSizeProm = computeCardSize(…);
  const [cardSize] = await Promise.all([cardSizeProm, waitProm]);
}
```

File: src/panels/lovelace/common/compute-card-size.ts (hunk 3 above)
Comment (bramkragten) [reply src/panels/lovelace/common/compute-card-size.ts:7]: That's node, it was moved to element

Comment (bramkragten) [reply src/panels/lovelace/common/compute-card-size.ts:7]: But tagName to lower case would also work

File: src/panels/lovelace/views/hui-view.ts (hunk 7 above)
Comment (bramkragten) [reply src/panels/lovelace/views/hui-view.ts:243]: I think it is not even needed anymore

File: src/panels/lovelace/views/hui-view.ts (hunk 8 above)
Comment (bramkragten) [reply src/panels/lovelace/views/hui-view.ts:246]: I like it, takes the guessing out of how many cards we are rendering and how expensive they are.

**Review by balloob — APPROVED** [review]

**Review by balloob — APPROVED** [review]

File: src/panels/lovelace/common/compute-card-size.ts [hunk 9]
```diff
@@ -1,5 +1,12 @@
 import { LovelaceCard } from "../types";
 
-export const computeCardSize = (card: LovelaceCard): number => {
-  return typeof card.getCardSize === "function" ? card.getCardSize() : 4;
+export const computeCardSize = async (card: LovelaceCard): Promise<number> => {
```
Comment (balloob) [inline src/panels/lovelace/common/compute-card-size.ts:3]: I suggest that we don't make this function async, so that we can avoid an unnecessary await. 
```suggestion
export const computeCardSize = (card: LovelaceCard): number | Promise<number> => {
```

**Comment by scstraus** [comment]
As someone who has been making workarounds for years to deal with wrong size reporting of my stacks, I thank you very much for this and look forward to trying it.
