### PR TITLE
Z-Wave rebuild routes add detail progress

### LINKED ISSUE #15957: Improve Z-Wave heal network feedback
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This issue is the result of a meeting about current issues that blocks Home Assistant from becoming Z-Wave certified.

The heal network command, reached from the Z-Wave config panel, only shows a general progress indicator without further information.

### Describe the behavior you expected

The heal network command needs better UI feedback. We want to see the progress of the heal command among the devices in the network.

The progress of the network heal, is available from the backend with the `zwave_js/subscribe_heal_network_progress` websocket command. The returned data is an object with the node id of the nodes and a string with the node heal status.

```json
{
    "event": "heal network progress",
    "heal_node_status": {
        "2": "pending",
        "3": "done",
        "4": "failed",
        "6": "skipped"
    }
}
```

For more information about the command, see:

https://zwave-js.github.io/node-zwave-js/#/api/controller?id=beginhealingnetwork

### Steps to reproduce the issue

1. Go to the config panel of the Z-Wave integration.
2. Press Heal Network.
3. Press Start Healing.
4. See lack of detailed progress indicator as the heal progresses.
...

### What version of Home Assistant Core has the issue?

core-2023.4.0.dev0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome Version 111.0.5563.110

### Which operating system are you using to run this browser?

Ubuntu 20.04

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

Tested in Firefox 111.0.1 and Google Chrome Version 111.0.5563.110.

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change
- `dialog-zwave_js-rebuild-network-routes`
	- fix #15957
	- use detailed progress and show it in buttons
	- Show devices for each progress states in a detail dialog
	- Refactor dialog to use context instead of the hass object
		- To make this happen I had to change some functions and components
- Use context instead of hass in `ha-domain-icon`
- Change api of functions to use just the needed parts of hass instead of full hass
	- `data/icons/domainIcon`
	- `data/icons/getComponentIcons`
	- `common/version/atLeastVersion`
	- `common/config/isComponentLoaded`
	- `common/entity/compute_device_name/computeDeviceNameDisplay`
	- `common/entity/compute_device_name/fallbackDeviceName`
	- `common/entity/context/getDeviceContext`
	- `data/zwave_js/fetchZwaveNetworkStatus`
	- `data/zwave_js/rebuildZwaveNetworkRoutes`
	- `data/zwave_js/subscribeRebuildZwaveNetworkRoutesProgress`
	- `data/zwave_js/stopRebuildingZwaveNetworkRoutes`

## Screenshots
grafik
grafik

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to related backend pull request: home-assistant/core#167178

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/common/entity/context/get_device_context.ts [hunk 1]
```diff
@@ -11,12 +11,16 @@ interface DeviceContext {
 
 export const getDeviceContext = (
   device: DeviceRegistryEntry,
-  hass: HomeAssistant
+  areas: HomeAssistant["areas"],
+  floors?: HomeAssistant["floors"]
```
Comment (MindFreeze) [inline src/common/entity/context/get_device_context.ts]: Why is `floors` optional here? Seems unnecessary. If areas are available, floors should be too

Comment (wendevlin) [reply src/common/entity/context/get_device_context.ts]: Because in most usages we just take the area, so I made it optional so it doesn't need to be provided for nothing.

Comment (MindFreeze) [reply src/common/entity/context/get_device_context.ts]: Actually I think in all usages it's only for area

Comment (wendevlin) [reply src/common/entity/context/get_device_context.ts]: Then let's change it to get_device_area

**Review by MindFreeze — APPROVED** [review]
