### PR TITLE
Prevent automation action row issue if event name gets cleared

### LINKED ISSUE #8059: Automation editor reverts to YAML mode on clearing some text fields
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [ ] I have cleared the cache of my browser.
- [ ] I have tried a different browser to see if it is related to my browser.

## The problem

In the automation editor, clearing the text input field of at least:
- fire event
- delay, and
- wait

actions after having typed something there reverts the action editor to YAML mode, it appears to lose track of what kind of action was being edited.

## Expected behavior

UI stayed with the appropriate UI action editing mode.

## Steps to reproduce

Example from editing fire event:

Fire event chosen, started typing something to the event field:
Screenshot from 2021-01-01 10-51-00

At that point clear the event field with backspace, UI reverts to this:
Screenshot from 2021-01-01 10-51-15

Note the
> No UI support for action:

The action type is missing from the error message, that's why I thought it might be losing the context which type of action we were editing.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version: Firefox
- Operating system: Linux

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Previously the default `handleChangeEvent()` was used to react to changes in the "Event" input field. But as soon as it got empty, the property was removed from the action. Since however it is mandatory for the action row to know what type of action editor to show, the property needs to stay. Solved by calling "value-changed" ourself without property removal upon empty value.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/8059
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/automation/action/types/ha-automation-action-event.ts [hunk 1]
```diff
@@ -73,8 +74,11 @@ export class HaEventAction extends LitElement implements ActionElement {
     handleChangeEvent(this, ev);
   }
 
-  private _valueChanged(ev: CustomEvent): void {
-    handleChangeEvent(this, ev);
+  private _eventChanged(ev: CustomEvent): void {
+    ev.stopPropagation();
+    fireEvent(this, "value-changed", {
+      value: { ...this.action, entity_id: ev.detail.value },
```
Comment (bramkragten) [inline src/panels/config/automation/action/types/ha-automation-action-event.ts:80]: I assume this should be event?
```suggestion
      value: { ...this.action, event: ev.detail.value },
```

**Review by bramkragten — APPROVED** [review]
