### PR TITLE
Add fix to more-info for media players without play/pause state

### LINKED ISSUE #7074: Media player not showing play or pause
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Using bravia integration if I add the entity media_player into an entity card it will shows previous play/pause and next controls.

But when that entity is expanded the play/pause control disappears only previous and next are shown.

## Expected behavior

Play and pause should also be in the expanded card for the entity like it used to be.

Play pause is there in card on 114.4 screenshot below.
Screenshot_20200922-024341

## Steps to reproduce

Using bravia integration, add to Lovelace in entities card and turn TV on play and pause controls are shown. Then click on the entity in the card that pops up play and pause is missing.

## Environment

- Home Assistant release with the issue: 0.115.1
- Last working Home Assistant release (if known): pretty sure we're there on 0.114
- Browser and browser version: chrome or android app tested.
- Operating system: proxmox

## State of relevant entities

```

```
Screenshot_20200919-211601

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

Screenshot_20200919-210659
Play pause shown

Screenshot_20200919-210711
Play pause missing.

### PR DESCRIPTION
**Pull request by kg333**
## Proposed change
This corrects issue #7074 introduced in 0.115, and allows media players that do not show playing or paused states to still have a play/pause button if supported.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

N/A

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #7074 
- This PR is related to issue:
- Link to documentation pull request:

I do not have a media player that *does* support playing/pause states available in my dev environment.  If someone could please test this fix with a Google Home or similar device to ensure functionality does not change for these devices, it'd be greatly appreciated.

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- N/A [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- N/A [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @kg333, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;frontend#7608).

Once you do that we will be able to review and accept this pull request.

Thanks!

File: src/dialogs/more-info/controls/more-info-media_player.ts [hunk 1]
```diff
@@ -309,11 +309,16 @@ class MoreInfoMediaPlayer extends LitElement {
       (state === "playing" &&
         (supportsFeature(stateObj, SUPPORT_PAUSE) ||
           supportsFeature(stateObj, SUPPORT_STOP))) ||
-      (state === "paused" && supportsFeature(stateObj, SUPPORTS_PLAY))
+      (state === "paused" && supportsFeature(stateObj, SUPPORTS_PLAY)) ||
+      (state === "on" &&
+        supportsFeature(stateObj, SUPPORTS_PLAY) &&
+        supportsFeature(stateObj, SUPPORT_PAUSE))
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-media_player.ts:315]:
```suggestion
        supportsFeature(stateObj, SUPPORTS_PLAY) ||
        supportsFeature(stateObj, SUPPORT_PAUSE))
```

Comment (bramkragten) [reply src/dialogs/more-info/controls/more-info-media_player.ts:315]: Line 326 is a bug, we always call `media_play_pause`, even if pause is not supported and we show a stop icon. We should call `media_stop`.

Comment (kg333) [reply src/dialogs/more-info/controls/more-info-media_player.ts]: Agreed, changed the line as you suggested.

**Review by bramkragten — APPROVED** [review]
