### PR TITLE
Use websockets

### LINKED ISSUE #8332: supervisor.snapshots complains about double snapshot request
### Describe the issue
Snapshots work well - both automated and manually (CREATE button), BUT a few minutes after triggering a snapshot, the supervisor complains
```20-12-03 10:07:54 ERROR (MainThread) [supervisor.snapshots] A snapshot/restore process is already running```
although I only click the CREATE button once.

It does not seem to be a problem - a snapshot is created and snapshot restore works - but I wanted to point it out in case someone cares to check what causes it. I haven't found any other report about this problem, so it might be just my HA instance.

### Steps to reproduce
Trigger a snapshot creation - for example by manually clicking the CREATE button on the Snapshots page.

### Enviroment details

<details>
<summary>Environment details</summary>

```
System Health

Home Assistant Core Integration

version: 0.118.4
installation_type: Home Assistant Supervised
dev: false
hassio: true
docker: true
virtualenv: false
python_version: 3.8.6
os_name: Linux
os_version: 4.19.0-10-amd64
arch: x86_64
timezone: Europe/Oslo

Home Assistant Cloud

logged_in: true
subscription_expiration: 8. desember 2020, 1:00
relayer_connected: true
remote_enabled: true
remote_connected: true
alexa_enabled: false
google_enabled: true
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

hassio

host_os: Debian GNU/Linux 10 (buster)
update_channel: stable
supervisor_version: 2020.12.2
docker_version: 19.03.13
disk_total: 884.3 GB
disk_used: 81.1 GB
healthy: true
supported: true
supervisor_api: ok
version_api: ok
installed_addons: Samba share (9.3.0), Duck DNS (1.12.4), Check Home Assistant configuration (3.6.0), File editor (5.2.0), deCONZ (6.5.0), Mosquitto broker (5.1), Node-RED (7.2.11), Dnsmasq (1.3), Dropbox Sync (1.3.0), NGINX Home Assistant SSL proxy (3.0.1), Grafana (5.3.6), InfluxDB (3.7.9), Visual Studio Code (2.9.0), AppDaemon 4 (0.3.2), JupyterLab Lite (0.3.1), OpenZWave (0.7.1)

Lovelace

dashboards: 2
mode: storage
views: 14
resources: 0
```
</details>

### Supervisor logs
<details>
<summary>Supervisor logs</summary>

```
20-12-03 10:06:54 INFO (MainThread) [supervisor.snapshots] Creating new full-snapshot with slug 63ea58e0
20-12-03 10:06:54 INFO (MainThread) [supervisor.snapshots] Snapshotting 63ea58e0 store Add-ons
20-12-03 10:06:54 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_samba
20-12-03 10:06:54 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_samba
20-12-03 10:06:54 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_duckdns
20-12-03 10:06:54 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_duckdns
20-12-03 10:06:54 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_check_config
20-12-03 10:06:54 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_check_config
20-12-03 10:06:54 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_configurator
20-12-03 10:06:54 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_configurator
20-12-03 10:06:54 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_deconz
20-12-03 10:06:57 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_deconz
20-12-03 10:06:57 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_mosquitto
20-12-03 10:06:57 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_mosquitto
20-12-03 10:06:57 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_nodered
20-12-03 10:06:57 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_nodered
20-12-03 10:06:57 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_dnsmasq
20-12-03 10:06:57 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_dnsmasq
20-12-03 10:06:57 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on 7be23ff5_dropbox_sync
20-12-03 10:06:57 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon 7be23ff5_dropbox_sync
20-12-03 10:06:57 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on core_nginx_proxy
20-12-03 10:06:57 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon core_nginx_proxy
20-12-03 10:06:57 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_grafana
20-12-03 10:06:57 INFO (MainThread) [supervisor.addons.addon] Finish snapshot for addon a0d7b954_grafana
20-12-03 10:06:57 INFO (MainThread) [supervisor.addons.addon] Building snapshot for add-on a0d7b954_influxdb
20-12-03 10:07:54 ERROR (MainThread) [supervisor.snapshots] A snapshot/restore process is already running
```

</details>

### PR DESCRIPTION
**Pull request by ludeeus**
## Proposed change

- Uses WebSockets for API calls where we can.
- Adds event listener so the Supervisor can signal updates to the frontend.
- Extends `atLeastVersion` to check 3 sections

Needing to keep backward compatibility sucks...

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #8332
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: hassio/src/hassio-main.ts [hunk 1]
```diff
@@ -56,6 +60,30 @@ export class HassioMain extends SupervisorBaseElement {
...
+    if (
+      event.event === "supervisor-update" &&
+      event.update_key !== undefined &&
+      event.data !== undefined &&
+      this.supervisor !== undefined
+    ) {
+      const data: Partial<Supervisor> = {};
+      data[event.update_key] = {
+        ...this.supervisor![event.update_key],
+        ...event.data,
```
Comment (bramkragten) [inline hassio/src/hassio-main.ts:83]: Does this mean a key can never be removed in an update? Doesn't the update contain the entire new object?

File: src/common/config/version.ts [hunk 2]
```diff
@@ -1,11 +1,15 @@
...
 ): boolean => {
-  const [haMajor, haMinor] = version.split(".", 2);
+  const [haMajor, haMinor, haPatch] = version.split(".", 3);
   return (
     Number(haMajor) > major ||
-    (Number(haMajor) === major && Number(haMinor) >= minor)
+    (Number(haMajor) === major && Number(haMinor) >= minor) ||
+    (patch !== undefined &&
+      Number(haMinor) === minor &&
+      Number(haPatch) >= patch)
```
Comment (bramkragten) [inline src/common/config/version.ts:13]:
```suggestion
    (patch !== undefined &&
      Number(haMajor) === major && Number(haMinor) === minor &&
      Number(haPatch) >= patch)
```

**Review by bramkragten — DISMISSED** [review]

File: hassio/src/hassio-main.ts (hunk 1 above)
Comment (ludeeus) [reply hassio/src/hassio-main.ts:83]: a key should never be removed.

The idea here is that we can add partial updates in the backend for certain things, like the core state.
Instead of generating the entire JSON data and sending that over to core (which will populate the DB since it's an event), we could just send the new core state

File: hassio/src/supervisor-base-element.ts [hunk 3]
```diff
@@ -66,4 +91,20 @@ export class SupervisorBaseElement extends urlSyncMixin(
...
+      event.update_key !== undefined &&
+      event.data !== undefined &&
+      this.supervisor !== undefined
+    ) {
+      const data: Partial<Supervisor> = {};
+      data[event.update_key] = {
+        ...this.supervisor![event.update_key],
+        ...event.data,
+      };
+      fireEvent(this, "supervisor-update", data);
```
Comment (bramkragten) [inline hassio/src/supervisor-base-element.ts:107]: directly call `_updateSupervisor`

File: src/data/supervisor/supervisor.ts [hunk 4]
```diff
@@ -18,3 +34,24 @@ export interface Supervisor {
   resolution: HassioResolution;
   os: HassioHassOSInfo;
 }
+
+const subscribeSupervisorEventUpdates = (conn: Connection, store) =>
+  conn.subscribeEvents(
+    (event) => store.setState(event, true),
```
Comment (bramkragten) [inline src/data/supervisor/supervisor.ts:40]: the store should contain the supervisor, not the event data?

Comment (ludeeus) [reply src/data/supervisor/supervisor.ts:40]: should it?

Comment (bramkragten) [reply src/data/supervisor/supervisor.ts:40]: so, you dont want to use overwrite here

File: hassio/src/addon-store/hassio-addon-store.ts [hunk 5]
```diff
@@ -52,30 +48,25 @@ const sortRepos = (a: HassioAddonRepository, b: HassioAddonRepository) => {
...
 
   protected render(): TemplateResult {
     const repos: TemplateResult[] = [];
 
-    if (this._repos) {
-      for (const repo of this._repos) {
-        const addons = this._addons!.filter(
+    if (this.supervisor.addon.repositories) {
+      for (const repo of this.supervisor.addon.repositories.sort(sortRepos)) {
+        const addons = this.supervisor.addon.addons.filter(
```
Comment (bramkragten) [inline hassio/src/addon-store/hassio-addon-store.ts:69]: Make this a memoize

Comment (bramkragten) [reply hassio/src/addon-store/hassio-addon-store.ts:69]: or use the guard directive, with `this.supervisor.addon.addons` and `this.supervisor.addon.repositories`

**Review by bramkragten — APPROVED** [review]
