### PR TITLE
Check for `null` action nodes before rendering

### LINKED ISSUE #9901: Error rendering automation graph with empty sequence
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a working automation but the automation trace graph renderer shows "Error rendering graph. Please download trace and share with the developers. ".

This seems to happen when I have an action with an empty sequence (which is that way since I've temporarily removed the action during testing, but am keeping the enclosing choice since I still want the 'default' which follows).

A workaround is to add a 'delay: 00:00:00' as a no-op in the sequence.

### Describe the behavior you expected

I expected the Automation to show its trace successfully.

### Steps to reproduce the issue

1. Add this automation (you do NOT need to create helper input_boolean.dummy_switch):
```
- id: '999999'
  alias: automation bug demo
  trigger:
  - platform: state
    entity_id: input_boolean.dummy_switch
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.dummy_switch
        state: 'on'
      sequence:
```
2. reload automations
3. In Automations config, click "RUN ACTIONS" on this automation ("automation bug demo")
4. In Automations conflg, click the "trace" button for "automation bug demo".
5. Notice error message in left panel, "Error rendering graph. Please download trace and share with the developers." 

### What version of Home Assistant Core has the issue?

2021.8.8

### What was the last working version of Home Assistant Core?

n/a

### In which browser are you experiencing the issue with?

Google Chrome 92.0.4515.159, Firefox

### Which operating system are you using to run this browser?

MacOS Big Sur 11.5

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

```txt
none
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Handle `null` for `sequence` and `default`. In fact the fix is generic for all actions, but those are two I tested with. The backend allows those automation, so the frontend trace should handle them.

The path rendering looks a little bit off in the left path since there is no node in the right one, hence the left path has some slightly weird pathing angles, but I think this is unrelated to this PR.

image

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9901
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by balloob — DISMISSED** [review]

File: src/components/trace/hat-script-graph.ts [hunk 1]
```diff
@@ -115,6 +115,10 @@ export class HatScriptGraph extends LitElement {
   };
 
   private render_action_node(node: Action, path: string, graphStart = false) {
+    if (node === null) {
```
Comment (balloob) [inline src/components/trace/hat-script-graph.ts:118]: Actually thinking about it, instead of filtering it out here, we should guard for it and not call this function when it's `null` instead.

Comment (spacegaier) [reply src/components/trace/hat-script-graph.ts:118]: I thought about that as well, but then we have to duplicate the check a few times, since this function gets called in multiple places, so I went for the central approach (also prevents having to account for that scenario in case of future additions to the graph logic). But if preferred, I can move the check out to the different calls.

Comment (balloob) [reply src/components/trace/hat-script-graph.ts:118]: We should move it to the different calls, because if we ever have a bug where `null` is injected somewhere, it would now be silently ignored. We want to be explicit where we accept `null`.

**Comment by bramkragten** [comment]
For the angles, I think you can add a `hat-graph-spacer`

**Comment by spacegaier** [comment]
> 
> 
> For the angles, I think you can add a `hat-graph-spacer`

That was already in there. Without it it would look like this:
image

But the spacer is not wide enough to represent the full width of a missing node apparently, so it does not push the left node far enough away for proper angles.

**Review by balloob — APPROVED** [review]
