### PR TITLE
Fix copy to clipboard for wa dialogs

### LINKED ISSUE #29946: Copy to clipboard button not working on more info dialogs
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the beta it appears the copy to clipboard on more info dialogs "Settings" no longer works. Clicking the button shows the toast that says "Copied to clipboard" but it doesn't actually copy anything.

Image

### Describe the behavior you expected

Copy to clipboard

### Steps to reproduce the issue

1. Open any more info dialog, then click the settings cog in top right corner (to where you can change entity ID)
2. Click the copy to clipboard button next to the entity ID
3. Then try pasting it, the entity ID will not paste

### What version of Home Assistant Core has the issue?

2026.3.0b2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Google Chrome Version 145.0.7632.117 (Official Build) (arm64)

### Which operating system are you using to run this browser?

macOS Tahoe 26.3 (25D125)

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by timmo001**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #29946
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/common/util/copy-clipboard.ts [hunk 1]
```diff
@@ -8,10 +26,15 @@ export const copyToClipboard = async (str, rootEl?: HTMLElement) => {
     }
   }
 
-  const root = rootEl ?? document.body;
+  const root = getClipboardFallbackRoot(rootEl);
```
Comment (wendevlin) [inline src/common/util/copy-clipboard.ts]:
```suggestion
  const root = rootEl || getClipboardFallbackRoot();
```

File: src/common/util/copy-clipboard.ts [hunk 2]
```diff
@@ -1,3 +1,21 @@
+import { deepActiveElement } from "../dom/deep-active-element";
+
+const getClipboardFallbackRoot = (rootEl?: HTMLElement): HTMLElement => {
+  if (rootEl) {
+    return rootEl;
+  }
+
+  const activeElement = deepActiveElement();
```
Comment (wendevlin) [inline src/common/util/copy-clipboard.ts]:
```suggestion
const getClipboardFallbackRoot = (): HTMLElement => {
  const activeElement = deepActiveElement();
```

**Review by wendevlin — CHANGES_REQUESTED** [review]
rootElement shouldn't be in that function. Otherwise works good 👍

**Review by wendevlin — APPROVED** [review]
