### PR TITLE
Fix entities not showing due to JavaScript crash (fixes #25363)

### LINKED ISSUE #25363: No entities listed (device page, dropdowns...)
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After updating to version 2025.5.0, no entities are listed in the Entities page or in entity dropdowns, due to a JavaScript error caused by some entities lacking a name.

### Describe the behavior you expected

Entities are listed

### Steps to reproduce the issue

Have entities with no defined name
Open the entities page

### What version of Home Assistant Core has the issue?

2025.5.0

### What was the last working version of Home Assistant Core?

2025.4.4 (I think)

### In which browser are you experiencing the issue?

Chrome

### Javascript errors shown in your browser console/inspector

```txt
reactive-element.ts:1369 Uncaught (in promise) TypeError: e.toLowerCase is not a function
    at a (strip_prefix_from_entity_name.ts:13:43)
    at r (compute_entity_name.ts:55:12)
    at HTMLElement.<anonymous> (ha-config-entities.ts:677:28)
    at HTMLElement.a [as _filteredEntitiesAndDomains] (memoize-one.esm.js:37:35)
    at HTMLElement.render (ha-config-entities.ts:748:12)
    at HTMLElement.update (lit-element.ts:166:24)
    at HTMLElement.performUpdate (reactive-element.ts:1503:14)
```

### Additional information

This error appears to originate from this line:
https://github.com/home-assistant/frontend/blob/c7e79998a4380ce8942aa03d8085045e9d1343a2/src/common/entity/strip_prefix_from_entity_name.ts#L13

Root cause:

Entities without a defined name (but with has_entity_name: true) trigger the error when .toLowerCase() is called on undefined.

Example of problematic entity:
```
{
    "entity_id": "media_player.home_cinema_salon",
    "device_id": "4c88044b857e99504b93c6aa4985ce58",
    "labels": [],
    "platform": "cast",
    "has_entity_name": true
}
```

Script used to identify problematic entities:

```
Object.values(document.querySelector("home-assistant").hass.entities).forEach(function(e) {
    try {
        var a = e.name.toLowerCase();
    } catch (error) {
        console.log(JSON.stringify(e, null, 4));
    }
})
```

Findings:
- 42 entities are causing the issue due to missing name values.
- These entities render the entire entities UI unusable.

### PR DESCRIPTION
**Pull request by Drinory**
## Proposed change

Fixes a JavaScript crash in the entity UI that prevents entities (and potentially devices) from being listed in configuration pages and dropdowns.

The issue occurred when `stripPrefixFromEntityName` tried to call `.toLowerCase()` on undefined values, specifically affecting entities like SLZB ZHA coordinators that have numeric `original_name` values (e.g., `original_name: 2`). This crash could cascade to affect device listings that depend on entity name computation.

This fix adds proper null/undefined checks and type safety to prevent the crash while gracefully falling back to more descriptive entity names.

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)

## Example configuration

```yaml
# Not applicable - this fixes a JavaScript crash that affects any entity
# with undefined names or numeric original_name values
```

## Additional information

- This PR fixes or closes issue: fixes #25363
- This PR is related to issue or discussion: #25163 (potentially related device listing issue)
- Link to documentation pull request: 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] Tests have been added to verify that the new code works.

### CODE REVIEW

File: src/common/entity/compute_entity_name.ts [hunk 1]
```diff
@@ -30,11 +30,14 @@ export const computeEntityEntryName = (
   const name =
     entry.name || ("original_name" in entry ? entry.original_name : undefined);
```
Comment (MindFreeze) [inline src/common/entity/compute_entity_name.ts]: If you just coerce it to String here, you won't have to change anything else
```suggestion
    entry.name || (entry.original_name != null ? String(entry.original_name) : "");
```

Comment (Drinory) [reply src/common/entity/compute_entity_name.ts]: Thanks for the suggestion! I considered that approach, but chose the current implementation for better user experience:

With `String(original_name)`, entities would display confusing names like "2". 
My approach ensures users see descriptive fallback names instead of converted numbers.

However, I'm happy to simplify if you prefer the more targeted fix for this PR and address UX in a follow-up.

**Comment by Drinory** [comment]
I notice there's a linting issue on line 71 that wasn't part of my original changes - likely from updated ESLint rules in the dev branch. 

Should I:
1. Fix it in this PR since I'm already here, or 
2. Leave it for a separate cleanup PR to keep this focused?

Happy to go either way!

**Comment by Drinory** [comment]
I notice there's a linting issue on line 71 in `test/common/entity/compute_entity_name.test.ts` that wasn't part of my original changes - likely from updated ESLint rules in the dev branch. 

Should I:
1. Fix it in this PR since I'm already here, or 
2. Leave it for a separate cleanup PR to keep this focused?

Happy to go either way!

File: src/common/entity/compute_entity_name.ts (hunk 1 above)
Comment (MindFreeze) [reply src/common/entity/compute_entity_name.ts]: I think a number can be a meaningful name. We have power strips that name their outlets 1, 2 and 3. These would still be better names for the entities than having all of them named "Power strip".
Though I am not sure this is the same case and haven't seen the referenced issue myself so I may be wrong

Comment (Drinory) [reply src/common/entity/compute_entity_name.ts]: Thanks, good point that numbers can be meaningful (power strips, zones, etc.).
I’ve adopted your `String()` suggestion and kept a type-narrowing check for the union type. I also reverted unrelated tweaks to keep this PR minimal and focused on the crash fix. The line now is:

```
const name =
  entry.name ||
  ("original_name" in entry && entry.original_name != null
    ? String(entry.original_name)
    : "");

```

I’ve updated tests to cover:

numeric `original_name` (`2`, `0`) → preserved (`"2"`, `"0"`)

empty `entry.name` (`''`) → falls back via `||`

`null`/`undefined` → `""` as ultimate fallback

regular strings → passthrough

If you’d prefer a different ultimate fallback (e.g., undefined instead of ""), happy to adjust. Thanks for the nudge!

**Review by MindFreeze — APPROVED** [review]
Thank you!

File: src/common/entity/compute_entity_name.ts [hunk 2]
```diff
@@ -28,7 +28,10 @@ export const computeEntityEntryName = (
   hass: HomeAssistant
 ): string | undefined => {
   const name =
-    entry.name || ("original_name" in entry ? entry.original_name : undefined);
+    entry.name ||
+    ("original_name" in entry && entry.original_name != null
+      ? String(entry.original_name)
+      : "");
```
Comment (bramkragten) [inline src/common/entity/compute_entity_name.ts:34]: Shouldn't this stay `undefined` as before?

Comment (Drinory) [reply src/common/entity/compute_entity_name.ts:34]: @bramkragten Thanks for calling this out, agreed.
As noted earlier in the thread, after adopting @MindFreeze’s String() suggestion to prevent the crash, I set the ultimate fallback to "" and mentioned I was happy to adjust. To keep the original contract (string | undefined) and avoid ?? edge cases, I’ll do a tiny follow-up that keeps String(original_name) but reverts the final fallback to undefined.
Proposed line:

entry.name ||
  ("original_name" in entry && entry.original_name != null
    ? String(entry.original_name)
    : undefined);

I’ll include tests (numeric original_name → "2"; “no name” branch → undefined) to lock this in. Appreciate the review!
