### PR TITLE
🐛 don't remove key when value is empty

### LINKED ISSUE #4540: Markdown card bug with deleting all text
**Checklist:**
- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.104.2

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Chrome 79.0.3945.117 / macOS 10.13.6

**Description of problem:**
In the Markdown card, if you highlight all of the default text and press the delete key, you expect to have a clean slate to write your own stuff. But there's a bug with it now.

When you select all text and press delete key, it tosses you into the code editor. Underneath there's an error saying `Expected a value of type `string` for `content` but received `undefined`.`  

And there's no way to get back to the visual editor, since the button will be grayed out / disabled, even though a visual editor does in fact exist for this card.

markdown

If you highlight all the text inside the code editor (which would just be `type: markdown`), and then press Delete again, it takes you back to the add new card window (at least in Chrome).

**Steps to reproduce this problem:**
1. Add New Card > Markdown
2. Highlight all default text, press delete
3. It will kick you out of the visual editor and put you in code editor, with no way to switch back

### PR DESCRIPTION
**Pull request by iantrich**
fixes https://github.com/home-assistant/home-assistant-polymer/issues/4540

### CODE REVIEW

File: src/panels/lovelace/editor/config-elements/hui-markdown-card-editor.ts [hunk 1]
```diff
@@ -100,14 +100,10 @@ export class HuiMarkdownCardEditor extends LitElement
       return;
     }
     if (target.configValue) {
-      if (target.value === "") {
-        delete this._config[target.configValue!];
```
Comment (bramkragten) [inline src/panels/lovelace/editor/config-elements/hui-markdown-card-editor.ts]: Shouldn't this just be for `content`?
