### PR TITLE
Code editor fullscreen in dialogs

### LINKED ISSUE #29870: Card creation code editor fullscreen does not go full screen
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When creating a card going to the code editor and clicking on the fullscreen icon only expnds the editor to the width of the current card editor and not the whole screen.
Edit: Triedin safe mode as well

### Describe the behavior you expected

I expect fullscreen to actually be fullscreen. This has worked since the feature was introduced.

### Steps to reproduce the issue

1. Edit dashboard and add a card
2. Click 'code editor'
3. Click the 'fullscreen' icon
...

### What version of Home Assistant Core has the issue?

2026.3.0b1

### What was the last working version of Home Assistant Core?

2026.2.3

### In which browser are you experiencing the issue?

Chrome, Edge, and Iridium

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

Image

### PR DESCRIPTION
**Pull request by timmo001**
## Proposed change

- Adds an event for dialogs to enable or disable fullscreen
- Adds some CSS vars for code editors to fill the dialog space
- Removes fullscreen prop on disconnects
- Uses view transitions between layout changes

## Screenshots

https://github.com/user-attachments/assets/f9527650-7054-468c-8e61-546dde826492

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: closes #29870
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/components/ha-dialog.ts [hunk 1]
```diff
@@ -301,10 +339,37 @@ export class HaDialog extends ScrollableFadeMixin(LitElement) {
           --width: min(var(--ha-dialog-width-lg, 1024px), var(--full-width));
         }
 
-        :host([width="full"]) wa-dialog {
+        :host([width="full"]) wa-dialog,
+        :host([fullscreen]) wa-dialog {
```
Comment (bramkragten) [inline src/components/ha-dialog.ts:336]: Why do we have 2 properties now that do the same?

File: src/components/ha-dialog.ts [hunk 2]
```diff
@@ -301,10 +339,37 @@ export class HaDialog extends ScrollableFadeMixin(LitElement) {
...
+          --code-editor-position: absolute;
+          --code-editor-top: 0;
+          --code-editor-left: 0;
+          --code-editor-right: 0;
+          --code-editor-bottom: 0;
+          --code-editor-border-radius: 0;
+          --code-editor-padding-top: 0;
+          --code-editor-padding-left: 0;
+          --code-editor-padding-right: 0;
+          --code-editor-padding-bottom: 0;
```
Comment (bramkragten) [inline src/components/ha-dialog.ts]: Not sure all this code editor logic should be in `ha-dialog`?

Comment (bramkragten) [reply src/components/ha-dialog.ts]: Can't we instead set a `in-dialog` flag on the code editor?

File: src/components/ha-dialog.ts (hunk 1 above)
Comment (timmo001) [reply src/components/ha-dialog.ts:336]: Might be able to reuse width full instead

Comment (timmo001) [reply src/components/ha-dialog.ts:336]: Didn't make sense to do this. It's cleaner to have a controlled host property and an attribute. Might look into the "expand" stuff later though to use the event instead

File: src/components/ha-dialog.ts (hunk 2 above)
Comment (timmo001) [reply src/components/ha-dialog.ts]: We could yeah, I was at one point avoiding this, but it probably makes more sense

File: src/components/ha-dialog.ts [hunk 3]
```diff
@@ -227,15 +239,41 @@ export class HaDialog extends ScrollableFadeMixin(LitElement) {
...
+      this._setFullscreen(ev.detail);
+    });
+  }
+
+  private _setFullscreen(fullscreen: boolean): void {
+    if (this._fullscreen === fullscreen) {
+      return;
+    }
+
+    this._fullscreen = fullscreen;
```
Comment (bramkragten) [inline src/components/ha-dialog.ts]: We could drop the property right, it is not used anywhere? Otherwise make it a reflected property, so we are not manually syncing the attribute and property

**Review by bramkragten — DISMISSED** [review]

**Comment by timmo001** [comment]
position fixed is needed for the non-dialog usages like in the automation sidebar, this fills (most of) the screen, but in the case of dialogs, it needs to be absolute to fill the container

[b91f681](https://github.com/home-assistant/frontend/pull/29882/commits/b91f68134d2a2c017f615209afc97a1296b4192d) fixed the issue introduced before this while setting up an in-dialog flag

**Comment by timmo001** [comment]
Good to go now

File: src/components/ha-code-editor.ts [hunk 4]
```diff
@@ -524,6 +527,20 @@ export class HaCodeEditor extends ReactiveElement {
     }
   };
 
+  private _isInDialog(element: Element = this): boolean {
```
Comment (bramkragten) [inline src/components/ha-code-editor.ts]: Can't the user of the code editor set this as a public property?

Comment (timmo001) [reply src/components/ha-code-editor.ts]: Quite a few changes, but yeah

**Comment by timmo001** [comment]
Bug in more info details dialog, needs to reset fullscreen there too

File: src/dialogs/more-info/ha-more-info-details.ts [hunk 5]
```diff
@@ -61,6 +61,7 @@ class HaMoreInfoDetails extends LitElement {
               .value=${yamlData}
               read-only
               auto-update
+              .inDialog=${true}
```
Comment (bramkragten) [inline src/dialogs/more-info/ha-more-info-details.ts]:
```suggestion
              in-dialog
```

File: src/panels/lovelace/editor/badge-editor/hui-dialog-edit-badge.ts [hunk 6]
```diff
@@ -226,6 +226,7 @@ export class HuiDialogEditBadge
               .hass=${this.hass}
               .lovelace=${this._params.lovelaceConfig}
               .value=${this._badgeConfig}
+              .inDialog=${true}
```
Comment (bramkragten) [inline src/panels/lovelace/editor/badge-editor/hui-dialog-edit-badge.ts]:
```suggestion
              in-dialog
```

File: src/panels/lovelace/editor/badge-editor/hui-dialog-suggest-badge.ts [hunk 7]
```diff
@@ -97,6 +97,7 @@ export class HuiDialogSuggestBadge extends LitElement {
                   <ha-yaml-editor
                     .hass=${this.hass}
                     .defaultValue=${this._badgeConfig}
+                    .inDialog=${true}
```
Comment (bramkragten) [inline src/panels/lovelace/editor/badge-editor/hui-dialog-suggest-badge.ts]:
```suggestion
                    in-dialog
```

File: src/panels/lovelace/editor/card-editor/hui-dialog-edit-card.ts [hunk 8]
```diff
@@ -203,6 +203,7 @@ export class HuiDialogEditCard
               .hass=${this.hass}
               .lovelace=${this._params.lovelaceConfig}
               .value=${this._cardConfig}
+              .inDialog=${true}
```
Comment (bramkragten) [inline src/panels/lovelace/editor/card-editor/hui-dialog-edit-card.ts]:
```suggestion
              in-dialog
```

File: src/panels/lovelace/editor/card-editor/hui-dialog-suggest-card.ts [hunk 9]
```diff
@@ -133,6 +133,7 @@ export class HuiDialogSuggestCard extends LitElement {
                   <ha-yaml-editor
                     .hass=${this.hass}
                     .defaultValue=${this._cardConfig}
+                    .inDialog=${true}
```
Comment (bramkragten) [inline src/panels/lovelace/editor/card-editor/hui-dialog-suggest-card.ts]:
```suggestion
                    in-dialog
```

File: src/panels/lovelace/editor/section-editor/hui-dialog-edit-section.ts [hunk 10]
```diff
@@ -127,6 +127,7 @@ export class HuiDialogEditSection
         <ha-yaml-editor
           .hass=${this.hass}
           autofocus
+          .inDialog=${true}
```
Comment (bramkragten) [inline src/panels/lovelace/editor/section-editor/hui-dialog-edit-section.ts]:
```suggestion
          in-dialog
```

File: src/panels/lovelace/editor/view-editor/hui-dialog-edit-view.ts [hunk 11]
```diff
@@ -162,6 +162,7 @@ export class HuiDialogEditView extends LitElement {
         <ha-yaml-editor
           .hass=${this.hass}
           autofocus
+          .inDialog=${true}
```
Comment (bramkragten) [inline src/panels/lovelace/editor/view-editor/hui-dialog-edit-view.ts]:
```suggestion
          in-dialog
```

File: src/panels/lovelace/editor/view-header/hui-dialog-edit-view-header.ts [hunk 12]
```diff
@@ -84,6 +84,7 @@ export class HuiDialogEditViewHeader extends LitElement {
         <ha-yaml-editor
           .hass=${this.hass}
           autofocus
+          .inDialog=${true}
```
Comment (bramkragten) [inline src/panels/lovelace/editor/view-header/hui-dialog-edit-view-header.ts]:
```suggestion
          in-dialog
```

File: src/panels/lovelace/editor/hui-element-editor.ts [hunk 13]
```diff
@@ -57,6 +57,9 @@ export abstract class HuiElementEditor<
 
   @property({ attribute: false }) public context?: C;
 
+  @property({ type: Boolean, attribute: "in-dialog" })
+  public inDialog = false;
```
Comment (bramkragten) [inline src/panels/lovelace/editor/hui-element-editor.ts:61]: Where is this one set?

Comment (timmo001) [reply src/panels/lovelace/editor/hui-element-editor.ts:61]: Comes from `hui-card-element-editor` via `HuiTypedElementEditor`

**Review by bramkragten — APPROVED** [review]
