### PR TITLE
Group small power consumers into Other node instead of hiding

### LINKED ISSUE #29006: Current Power Flow needs note or setting for 10 watts threshold
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Devices that consume less than 10 watts of power are not shown in the 'Current power flow 'diagram of the Energy dashboard.

This looks like a malfunction as there is no note informing the user about this behavior.

I have spent quite some time trying to figure this out and thought that something in my setup must be wrong.
In our house we run many LED lights that have less than 10 watts thanks to their great efficiency on Shelly RGBWs which provide quite accurate energy and power metering.

### Describe the behavior you expected

There should be at least a note that informs about this behavior.

Better: Add a setting, perhaps a simple button, to turn "Hide devices with less than 10 watts" on or off.
This should help to either get a clearer picture of the big consumers or a more detailed view when desired.

### Steps to reproduce the issue

1. Go to /energy/now
2. Turn on a light that consumes over 10 watts
3. Dim it down till it's below 10 watts

### What version of Home Assistant Core has the issue?

core-2026.1.1

### What was the last working version of Home Assistant Core?

n/a

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Also set the threshold dynamically to 0.1% of the total consumption

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #29006
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/energy/hui-power-sankey-card.ts [hunk 1]
```diff
@@ -307,19 +319,34 @@ class HuiPowerSankeyCard
...
       // Find the effective parent (may be different from direct parent if parent has no stat_rate)
       const effectiveParent = findEffectiveParent(device.included_in_stat);
 
+      if (value < minPowerThreshold) {
+        // Collect small consumers instead of skipping them
+        const parentKey = effectiveParent ?? "home";
+        if (!smallConsumersByParent.has(parentKey)) {
+          smallConsumersByParent.set(parentKey, []);
+        }
+        smallConsumersByParent.get(parentKey)!.push({
```
Comment (timmo001) [inline src/panels/lovelace/cards/energy/hui-power-sankey-card.ts:340]:
```suggestion
        smallConsumersByParent.get(parentKey)?.push({
```

**Review by timmo001 — APPROVED** [review]
