### PR TITLE
Fix area dialog too wide

### LINKED ISSUE #5133: Create/update dialog button too far right, not responsive
**Home Assistant Android version: 26 feb. 2020**

**Android version: 7.1.1**

**Phone model: Samsung J5 (SM-J510FN)**

**Home Assistant version: 3.12 on Raspberry pi 3 64-bit**

**Last working Home Assistant release (if known): N/A**

**Description of problem:**

When the phone is vertical, the create button does not show (and the update button, which has a longer word in Spanish only shows a few letters).
See the attached screenshots.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

No "create" action in vertical.
Screenshot_20200311-081638

Shows OK in horizontal.
Screenshot_20200311-081633

**Additional information: N/A**

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes https://github.com/home-assistant/frontend/issues/5133

### CODE REVIEW

File: src/panels/config/areas/dialog-area-registry-detail.ts [hunk 1]
```diff
@@ -142,8 +142,10 @@ class DialogAreaDetail extends LitElement {
     return [
       haStyleDialog,
       css`
-        ha-paper-dialog {
-          min-width: 400px;
+        @media all and (min-width: 450px) {
```
Comment (balloob) [inline src/panels/config/areas/dialog-area-registry-detail.ts]: Shouldn't this become a shared style ?

**Review by balloob — APPROVED** [review]
