### PR TITLE
Fix issues with state_color as false

### LINKED ISSUE #14129: Light icons not respecting state_color: false in entities card
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If I have a light being displayed in an entities card, the icon always reflects the light's colour even if I have the state_color option set to false. Other entities such as switches do respect the setting.

In this screenshot the slideshow and air purifier are switches, the DJ screen and printer light are lights - in this case RGBW strips running WLED but the same thing happens with other lights including non-RGB ones.

Screenshot 2022-10-19 at 14 44 59

### Describe the behavior you expected

Expected behaviour is for the light icons to be the default colour as with other entities

### Steps to reproduce the issue

1. Add a light icon to an entities card
2. Set the state_color option to false
3. Change the light colour / state
4. See that the icon changes to match despite the setting

### What version of Home Assistant Core has the issue?

Home Assistant 2022.10.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

```yaml
type: entities
entities:
  - entity: light.printer_light
  - entity: switch.air_purifier
state_color: false
```

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

Regarding `state_color` being `false` vs. `undefined`:
- Fixes issue reported by @thomasloven from https://github.com/home-assistant/frontend/pull/19445#issuecomment-1937829732 by reverting the `false` initialization and turning off the attribute (but please note my responding comment for a better solution).
- Fixes #14129 by propagating setting `false` at the card level to the entities (not sure why this was not being done).
- Fixes a bug (I think?) in the glance card from #4854 where for some reason we set `stateColor` in the badge to true when it's configured in the entity as false.  This seems awfully deliberate so please confirm my removal is correct.
- Simplifies the boolean logic using `??` to make things clearer IMO.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/hui-entities-card.ts [hunk 1]
```diff
@@ -296,12 +296,11 @@ class HuiEntitiesCard extends LitElement implements LovelaceCard {
 
   private renderEntity(entityConf: LovelaceRowConfig): TemplateResult {
```
Comment (steverep) [inline src/panels/lovelace/cards/hui-entities-card.ts:297]: @bramkragten shouldn't the type be `EntitiesCardEntityConfig` here?  The Lovelace vs card types have always baffled me.

Comment (steverep) [reply src/panels/lovelace/cards/hui-entities-card.ts:297]: Looks like that's what it used to be before #7134... 😕

File: src/panels/lovelace/cards/hui-entities-card.ts [hunk 2]
```diff
@@ -295,15 +295,10 @@ class HuiEntitiesCard extends LitElement implements LovelaceCard {
   }
 
   private renderEntity(entityConf: LovelaceRowConfig): TemplateResult {
-    const element = createRowElement(
-      (!("type" in entityConf) || entityConf.type === "conditional") &&
```
Comment (steverep) [inline src/panels/lovelace/cards/hui-entities-card.ts:299]: This whole ternary seems unnecessary.  I'm guessing it was added to try to get TS to infer the type correctly but then in the end the types were just asserted as a hack anyway?

I'm removing it here.  If `state_color` is defined, it should be propagated.  If it's not, no harm as it stays undefined.

File: src/panels/lovelace/cards/hui-glance-card.ts [hunk 3]
```diff
@@ -311,7 +310,6 @@ export class HuiGlanceCard extends LitElement implements LovelaceCard {
                       <hui-timestamp-display
                         .hass=${this.hass}
                         .ts=${new Date(stateObj.state)}
-                        .format=${entityConf.format}
```
Comment (steverep) [inline src/panels/lovelace/cards/hui-glance-card.ts:314]: This is not a property of the config.  It should default to relative display I think.

Comment (karwosts) [reply src/panels/lovelace/cards/hui-glance-card.ts:314]: Is it really necessary to break this? I'm pretty sure at some point I've seen someone suggest that you can change the time format on glance card in the same way you can for entities card.

image

File: src/panels/lovelace/cards/hui-entities-card.ts (hunk 1 above)
Comment (karwosts) [reply src/panels/lovelace/cards/hui-entities-card.ts:297]: Can't entityConf here be one of the special row types, like a `type: divider` ? It's not necessarily an entity.

Comment (steverep) [reply src/panels/lovelace/cards/hui-entities-card.ts:297]: > Can't entityConf here be one of the special row types, like a `type: divider` ? It's not necessarily an entity.

Yes, but my point is that the `EntityConfig` type is wrong when it's an entity - `EntitiesCardEntityConfig` is what is schemed in the docs and UI.

File: src/panels/lovelace/cards/hui-glance-card.ts (hunk 3 above)
Comment (steverep) [reply src/panels/lovelace/cards/hui-glance-card.ts:314]: Hmm... looks like it's validated as part of the YAML struct, but the docs specifically say relative time is used.  Glance card also has no UI config per entity.

Can you add it to the docs along with `state_color` and I'll modify the type here?  UI config for glance should be a separate PR.

Comment (steverep) [reply src/panels/lovelace/cards/hui-glance-card.ts]: Okay I reverted and added to the type, which required fixing another type, and now my head is spinning... 🤯

File: src/panels/lovelace/cards/hui-entities-card.ts (hunk 1 above)
Comment (bramkragten) [reply src/panels/lovelace/cards/hui-entities-card.ts:297]: You mean that `LovelaceRowConfig` should have `EntitiesCardEntityConfig` in it instead of `EntityConfig`? Then yes.

File: src/panels/lovelace/cards/hui-entities-card.ts [hunk 4]
```diff
@@ -295,15 +295,10 @@ class HuiEntitiesCard extends LitElement implements LovelaceCard {
...
-        this._config!.state_color
-        ? ({
-            state_color: true,
-            ...(entityConf as EntityConfig),
-          } as EntityConfig)
-        : entityConf
-    );
+    const element = createRowElement({
+      state_color: this._config!.state_color,
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-entities-card.ts:299]: I would say this is not correct, as special case rows don't necessarily support `state_color` and could fail config checks because of it?

File: src/panels/lovelace/cards/hui-entities-card.ts (hunk 2 above)
Comment (steverep) [reply src/panels/lovelace/cards/hui-entities-card.ts:299]: But this is just internally propagating it right?  It should never be in the row-based config.

Either way, if I correct the `LovelaceRowConfig` type and remove the assertions, TS will dictate what the conditional should be (assuming the other types are correct).

Comment (steverep) [reply src/panels/lovelace/cards/hui-entities-card.ts:299]: Nevermind... keeping as is for now and just making sure `false` is propagated too.

File: src/panels/lovelace/cards/hui-entities-card.ts (hunk 1 above)
Comment (steverep) [reply src/panels/lovelace/cards/hui-entities-card.ts:297]: > You mean that `LovelaceRowConfig` should have `EntitiesCardEntityConfig` in it instead of `EntityConfig`? Then yes.

Yes, and making that change doesn't cause errors, but I see a bunch of type assertions and inconsistencies that probably ought to be checked as part of that change.  Keeping the scope narrow here, I kept it as is and just adjusted to make sure `false` is passed.

**Review by bramkragten — APPROVED** [review]
