### PR TITLE
Display full error for card preview mode

### LINKED ISSUE #25613: setConfig errors are not being shown
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since the UI redesign, the exact error messages thrown by card `setConfig` are missing:

Image

This legacy error message should have been shown:
```
    if (
      !config.show_all &&
      !config.entities?.length &&
      !config.geo_location_sources
    ) {
      throw new Error(
        "Either show_all, entities, or geo_location_sources must be specified"
      );
    }
```

### Describe the behavior you expected

Show the reason for the configuration error. 

### Steps to reproduce the issue

1. as above
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.6.b0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Display full error in the error card when going to edit mode.
Quick fix for https://github.com/home-assistant/frontend/issues/25613

CleanShot 2025-06-11 at 11 24 34

For now we have 2 types of errors : 
- the ones throw by the editor
- the ones throw by the card itself

I first tried to merge them but it was not possible because in many cases, errors were duplicated.
So I prefer to keep the previous behavior.

We should think about a better error management for error card and provide API for built-in card and custom card to provide different types of errors : 
- the parameter doesn't exist
- the parameter is not compatible with the editor
- some warning about the card

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/25613
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by MindFreeze — APPROVED** [review]

File: src/panels/lovelace/cards/hui-card.ts [hunk 1]
```diff
@@ -200,6 +222,7 @@ export class HuiCard extends ReactiveElement {
           this._element.preview = this.preview;
           // For backwards compatibility
           (this._element as any).editMode = this.preview;
+          fireEvent(this, "card-updated");
```
Comment (MindFreeze) [inline src/panels/lovelace/cards/hui-card.ts:225]: @piitaya could this be causing https://github.com/home-assistant/core/issues/146799 ?
