### PR TITLE
Fix jumping on iOS when toggle switch

### LINKED ISSUE #4179: Mobile app moves entire card when switching on/off
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.101.2

**Last working Home Assistant release (if known):**
0.100.x
**UI (States or Lovelace UI?):**
lovelace ui

**Browser and Operating System:**
safari latest, ios

**Description of problem:**
when I'm toggling the switches on/off on any theme included default Lovelace UI (the white and blue one) it moves the cards completely

**Javascript errors shown in the web inspector (if applicable):**
can't see in mobile
```

```

**Additional information:**

image

### LINKED ISSUE #4212: Scrollbars on Toggle off in entity cards
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
since 0.101.x i think, but also on 0.102.0b0

**Last working Home Assistant release (if known):**

**UI (States or Lovelace UI?):**
LL

**Browser and Operating System:**
Firefox, Chrome, iOS app

**Description of problem:**
On toogle something (switch, input_boolen, automation) off, scrollbars show up for a short time.
scrollbars
BUT only if the card with the toogle is on the right side of the browser window.
On the left or in the middle, everthing is ok.

This happens in the iOS app on every toogle (all on the right side here)

Also when i toogle in the iOS app, i see it in the browser and vice versa. 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
https://community.home-assistant.io/t/cards-shrink-when-turning-devices-off-ios-app-version-1-5-1-hass-io-version-0-101-3/147938?u=vdrainer

### PR DESCRIPTION
**Pull request by bramkragten**
Can't find the source of the problem so can not fix it...

This dirty fix does solve it, but will again break the mouse over of a graph (https://github.com/home-assistant/home-assistant-polymer/pull/3971)

Fixes https://github.com/home-assistant/home-assistant-polymer/issues/4212
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/4179

### CODE REVIEW

File: src/panels/lovelace/views/hui-view.ts [hunk 1]
```diff
@@ -136,6 +136,8 @@ export class HUIView extends LitElement {
           flex: 1 0 0;
           max-width: 500px;
           min-width: 0;
+          /* on iOS devices the column can become wider when toggling a switch */
```
Comment (balloob) [inline src/panels/lovelace/views/hui-view.ts]: I wonder if we should fix this at the place where we render the switch ?

Comment (balloob) [reply src/panels/lovelace/views/hui-view.ts]: I guess it can't hurt to do it here in HUI-view 🤷‍♂  We really don't want things to escape horizontally anyway.
