### PR TITLE
Fix HLS on Android 9.0

### LINKED ISSUE #2948: New Stream Player Not Loading On Android Phone
**Home Assistant release with the issue:**

0.91.0.dev0 with latest frontend installed: 20190315.1

**Last working Home Assistant release (if known):**

N/A new video player

**UI (States or Lovelace UI?):**

Lovelace
**Browser and Operating System:**

Pixel 3 XL Android 9 March security update.  Google Chrome 72.0.3626

**Description of problem:**

When I attempt to view (more info panel) an `amcrest` or `generic` camera with a valid RTSP stream the new video player never loads on my pixel (even in desktop mode).  When I am on Windows 10 Chrome 72.0.3626 the player loads fine, even in responsive mode.  When I go to do remote debugging in chrome I noticed that on mobile the entire `video` element is missing where in desktop it is not missing, see image links below.  There is no console log here and the network calls are successful.  You can even see the stream being processed while the panel is opened so it seems to just not load. 

mobile: https://imgur.com/a/wb9EL0I
desktop: https://imgur.com/a/X876rE9

**Javascript errors shown in the web inspector (if applicable):**
```
n/a
```

**Additional information:**

This issue does not occur in the old player, I am still able to load it successful on mobile.  I have also attempted to view: https://video-dev.github.io/hls.js/demo/ on my phone the player loads successfully and as I understand it this is the player we are using.

### PR DESCRIPTION
**Pull request by hunterjm**
This fixes #2948.  The issue is Chrome on Android 9.0 was returning "maybe" for `canPlayType` ([docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType#Return_value)), but was unable to actually play the media.  This PR checks HLS.js before "native" support, then falls back to MJPEG.

### CODE REVIEW

**Comment by hunterjm** [comment]
Hold off on this.  Apparently iOS Safari returns `maybe` here.  Will need to check HLS.js first, and fall back to native before going to MJPEG.

**Comment by hunterjm** [comment]
The latest commit is confirmed working in Chrome and Safari on their respective mobile emulators (Android 9.0, and iOS 12) and desktop.

File: src/dialogs/more-info/controls/more-info-camera.ts [hunk 1]
```diff
@@ -76,7 +74,7 @@ class MoreInfoCamera extends UpdatingElement {
           this.stateObj.entity_id
         );
 
-        if (Hls) {
+        if (Hls.isSupported()) {
```
Comment (balloob) [inline src/dialogs/more-info/controls/more-info-camera.ts]: This is weird. Does hls better check for supported than native? We can check the return type of can play too

Comment (hunterjm) [reply src/dialogs/more-info/controls/more-info-camera.ts]: So HLS.js just have to check if MediaSourceExtension is supported, which is an easy check on the window. I have no clue why canPlayType returns an empty string, maybe, or probably.  All 3 of them sound pretty uncertain. All the demos I’ve looked at use HLS.js first and fallback to canPlayType, then unsupported.

Comment (balloob) [reply src/dialogs/more-info/controls/more-info-camera.ts]: image

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType
