### PR TITLE
Display area with only sensors in climate view in home dashboard

### LINKED ISSUE #26859: Climate section of the new Home dashboard is missing sensors
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

In the new Home dashboard in the climate section, some temperature sensors are missing. These sensors do show on the cards in the Areas dashboard and the areas in the top level of the Home dashboard.

### Describe the behavior you expected

Climate shows all temperature sensors assigned to areas

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2025.9.0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Display area with only sensors in climate view in home dashboard

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/26859
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/strategies/home/home-climate-view-strategy.ts [hunk 1]
```diff
@@ -33,8 +33,27 @@ const processAreasForClimate = (
...
+        features: [{ type: "trend-graph" }],
+      });
+    }
+
+    if (area.humidity_entity_id) {
+      areaCards.push({
+        ...computeTileCard(area.humidity_entity_id),
+        features: [{ type: "trend-graph" }],
+      });
+    }
```
Comment (silamon) [inline src/panels/lovelace/strategies/home/home-climate-view-strategy.ts]:
```suggestion
    const temperatureEntityId = area.temperature_entity_id;
    if (temperatureEntityId && hass.states[temperatureEntityId]) {
      areaCards.push({
        ...computeTileCard(temperatureEntityId),
        features: [{ type: "trend-graph" }],
      });
    }
    const humidityEntityId = area.humidity_entity_id;
    if (humidityEntityId && hass.states[humidityEntityId]) {
      areaCards.push({
        ...computeTileCard(humidityEntityId),
        features: [{ type: "trend-graph" }],
      });
    }
```

**Comment by piitaya** [comment]
Thank you @silamon ! I always forget this case.

**Review by silamon — APPROVED** [review]
