### PR TITLE
Fix Webpack bundling of recorder worklet

### LINKED ISSUE #21234: Unable to use voice input microphone, prompt”. /“bug, 7.0b5
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

**Unable to use voice input microphone, prompt. /bug,7.0b5
audio-recorder.ts:40 TypeError: Failed to resolve module specifier "core-js/modules/es.array.iterator.js". 
Relative references must start with either "/", "./", or "../".**

Hopefully, this resolves the issue with browser identification Mozilla/5.0 (Macintosh; Intel Mac OS

### Describe the behavior you expected

or

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

core-2024.7.0b5

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by steverep**
## Proposed change

Webpack is not currently parsing the audio recorder worklet for imports or creating a proper chunk.  It happened to work prior to #20676 for the modern build because there were luckily no imports of polyfills or Babel helpers.  The legacy version never could have worked.

This adjusts the code which adds the worklet and the Webpack config to fix that problem.  Also, it keeps the worklet from splitting because of several bugs in Webpack related to loading any external chunks.  The worklet is small enough that this doesn't really matter.

So this fixes the regression for the modern build and also gets it working for the legacy build.  A follow up could better transpile the worklet similar to #21177 and also implement better feature detection instead of a try/catch.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #21234 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved audio recording reliability by updating the `AudioRecorder` context creation logic and module loading syntax.

- **Refactor**
  - Streamlined webpack configuration for better support of web workers and worklets, enhancing overall build performance.

- **Style**
  - Updated naming conventions for audio worklet processors to ensure consistency and compatibility.

### CODE REVIEW

**Comment by steverep** [comment]
PS - I was only able to do limited testing here and also just manually examine the Webpack output.  It would help if someone could verify voice input works for both the modern and legacy builds.

cc @silamon

File: src/util/audio-recorder.ts [hunk 1]
```diff
@@ -70,17 +70,18 @@ export class AudioRecorder {
...
   private async _createContext() {
-    // @ts-ignore-next-line
-    this._context = new (window.AudioContext || window.webkitAudioContext)();
+    // @ts-expect-error webkitAudioContext is not recognized
+    const context = new (AudioContext || webkitAudioContext)();
     this._stream = await navigator.mediaDevices.getUserMedia({ audio: true });
-
-    await this._context.audioWorklet.addModule(
-      new URL("./recorder.worklet.js", import.meta.url)
+    // Syntax here must match an item of `parser.worker` in Webpack config nin
```
Comment (silamon) [inline src/util/audio-recorder.ts:76]:
```suggestion
    // Syntax here must match an item of `parser.worker` in Webpack config in
```

**Comment by steverep** [comment]
NM.... found my headset and fully tested now.  Errors are gone and both builds load the worklet.

**Review by silamon — APPROVED** [review]
