### PR TITLE
Fix card deletion dialog buttons out of view

### LINKED ISSUE #7933: "Delete Card" confirmation dialog out of view
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

Delete of "big card" open an new "overlay confirmation dialog" but the Dialog expand out of View and no scrolling-bars appears.
A resizing of Browser draw the "overlay confirmation dialog" correctly:

Before Resizing:
grafik

after Resizing:
grafik

## Expected behavior

Draw the "overlay confirmation dialog" in View without resizing the Browser or enable scrolling-bar if dialog is out of view.

## Steps to reproduce
Make a "big card" and delete it.

## Environment

- Home Assistant release with the issue: 0.118.5
- Last working Home Assistant release (if known): don't know
- Browser and browser version: Firefox 83.0(64-bit) and Chrome  87.0.4280.88 (64-Bit)
- Operating system: Win10

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

For bigger elements such as a `picture-element` card the deletion buttons are out of view. A window resize solves it (dialog gets centered on screen again), but the existing "iron-resize" does not seem to work. If the resize event fire is put in a `setTimeout()` it works for the first time the deletion dialog gets opened, but not any subsequent times (proofing that a delayed "iron-resize" once the deletion card preview has rendered works fine).

This is my rather hacky attempt at solving that. A more elegant solution would of course be preferred.

Note: Despite `top: 0;` the dialog is not smushed to the window top since it carries a `24px` margin anyway.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #7933
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bramkragten** [comment]
We should really just migrate away from `paper-dialog` here, that will also fix this issue

File: src/panels/lovelace/editor/card-editor/hui-dialog-delete-card.ts [hunk 1]
```diff
@@ -83,6 +83,7 @@ export class HuiDialogDeleteCard extends LitElement {
   private _close(): void {
```
Comment (bramkragten) [inline src/panels/lovelace/editor/card-editor/hui-dialog-delete-card.ts:83]: Make this function public, so closing with the back button also works

Comment (spacegaier) [reply src/panels/lovelace/editor/card-editor/hui-dialog-delete-card.ts:83]: You mean the browser back button? If yes, this does not work even if I make the method public. Why/how should that work?

Comment (bramkragten) [inline src/panels/lovelace/editor/card-editor/hui-dialog-delete-card.ts:83]:
```suggestion
  public close(): void {
```

File: src/panels/lovelace/editor/card-editor/hui-dialog-delete-card.ts [hunk 2]
```diff
@@ -80,17 +80,18 @@ export class HuiDialogDeleteCard extends LitElement {
     ];
   }
 
-  private _close(): void {
+  public close(): void {
```
Comment (bramkragten) [inline src/panels/lovelace/editor/card-editor/hui-dialog-delete-card.ts:83]:
```suggestion
  public closeDialog(): void {
```

Comment (bramkragten) [reply src/panels/lovelace/editor/card-editor/hui-dialog-delete-card.ts:83]: And move it above the private functions

**Review by bramkragten — APPROVED** [review]
