### PR TITLE
Gui editor fixes

### LINKED ISSUE #5413: Code editors switch back to visual editor after just one keystroke
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

While trying to reproduce a different bug, I noticed that the code editors for ~~stack cards~~ ALL cards immediately switch back to visual editor after just one single keystroke.

## Steps to reproduce

1. Configure UI > Add any card
2. Switch from Visual to Code editor
3. Try to edit any code - either type a character or try to delete a character
4. Any keypress will switch you back to the visual editor

## Environment

- Home Assistant release with the issue: 0.108.0b0
- Last working Home Assistant release (if known): 0.107.7
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml
type: horizontal-stack
cards:
  - type: button
    tap_action:
      action: toggle
    hold_action:
      action: more-info
    show_icon: true
    show_name: true 
    entity: light.kitchen_lights
 
```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes https://github.com/home-assistant/frontend/issues/5413

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/editor/config-elements/hui-conditional-card-editor.ts [hunk 1]
```diff
@@ -36,7 +42,10 @@ export class HuiConditionalCardEditor extends LitElement
   @property() public hass?: HomeAssistant;
   @property() public lovelace?: LovelaceConfig;
   @property() private _config?: StackCardConfig;
+  @property() private _GUImode = true;
+  @property() private _guiModeAvailable? = true;
```
Comment (zsarnett) [inline src/panels/lovelace/editor/config-elements/hui-conditional-card-editor.ts:46]: Does this need the optional (undefined) `?` (I don't remember what that is called)

File: src/panels/lovelace/editor/card-editor/hui-dialog-edit-card.ts [hunk 2]
```diff
@@ -52,12 +52,15 @@ export class HuiDialogEditCard extends LitElement {
 
   @property() private _saving: boolean = false;
   @property() private _error?: string;
+  @property() private _guiModeAvailable? = true;
```
Comment (zsarnett) [inline src/panels/lovelace/editor/card-editor/hui-dialog-edit-card.ts:55]: Same here

**Review by zsarnett — APPROVED** [review]

File: src/panels/lovelace/editor/config-elements/hui-conditional-card-editor.ts (hunk 1 above)
Comment (bramkragten) [reply src/panels/lovelace/editor/config-elements/hui-conditional-card-editor.ts:46]: The event does not have to send it, so it could be undefined, should not happen...

Comment (zsarnett) [reply src/panels/lovelace/editor/config-elements/hui-conditional-card-editor.ts:46]: ah Gotcha
