### PR TITLE
Fix second visit to history panel

### LINKED ISSUE #1815: Graphs aren't loading on second click to the History tab.
**Home Assistant release with the issue:**
0.80.2

**Last working Home Assistant release (if known):**
0.72.1

**Browser and Operating System:**
Windows 10. Chrome Version 69.0.3497.100 (Official Build) (64-bit. 

**Description of problem:**
See https://www.youtube.com/watch?v=PMp4YxI8pGQ&feature=youtu.be for visual. 

To reproduce. Click on the "Overview" tab. From here, refresh your browser. Then click on the "History" tab. Note how the graphs appear immediately. Click on "Overview" again. Then click on "History" again. Note how the graphs no longer appear, but instead, you see "Loading state history..." forever. 

**Javascript errors shown in the web inspector (if applicable):**
Nothing appears in the Chrome console but the warning "Could not find style data in module named vaadin-date-picker-overlay-default-theme". No network traffic is shown in the Chrome network analysis tools. 

**Additional information:**

Just upgraded tonight. I don't recall this happening with earlier builds.

### PR DESCRIPTION
**Pull request by balloob**
Fixes #1815

### CODE REVIEW

File: src/data/ha-state-history-data.js [hunk 1]
```diff
@@ -210,13 +208,18 @@ class HaStateHistoryData extends LocalizeMixin(PolymerElement) {
...
     endTime,
     cacheConfig,
-    localize,
-    language
+    localize
   ) {
-    if (!this.hass) return;
-    if (cacheConfig && !cacheConfig.cacheKey) return;
-    if (!localize || !language) return;
-    this._madeFirstCall = true;
```
Comment (zsarnett) [inline src/data/ha-state-history-data.js]: Is this being set anywhere else? If not then does it make sense to use it in `hassChanged`

**Comment by Parlane** [comment]
This also fixed changing dates and time ranges on the history page. Thank you.
