### PR TITLE
Reload entity component icons when missing

### LINKED ISSUE #19601: Blue icons in "Add action" popup in automation edit page
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When editing an automation and adding a new action, the popup with the available actions displays icons next to each action. Most are dark gray, but some are blue.

add_action

### Describe the behavior you expected

All icons are the same color

### Steps to reproduce the issue

1. Create a new automation or edit an existing one
2. Click "Add action"
3. Notice that some icons are blue

### What version of Home Assistant Core has the issue?

2024.2.0b0

### What was the last working version of Home Assistant Core?

2024.1.5

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

If we cached too early, or a domain is added later, we would miss the icons for that domain. If we miss an icon now we refetch all icons.

Fixes https://github.com/home-assistant/frontend/issues/19601

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/data/icons.ts [hunk 1]
```diff
@@ -55,12 +66,14 @@ interface ServiceIcons {
 
 export type IconCategory = "entity" | "entity_component" | "services";
 
-export const getHassIcons = async (
+export const getHassIcons = async <
```
Comment (piitaya) [inline src/data/icons.ts:69]:
```ts
type CategoryType = {
  entity: PlatformIcons;
  entity_component: ComponentIcons;
  services: ServiceIcons;
};

export const getHassIcons = async <T extends IconCategory>(
  hass: HomeAssistant,
  category: T,
  integration?: string
) =>
  hass.callWS<IconResources<CategoryType[T]>>({
    type: "frontend/get_icons",
    category,
    integration,
  });
 ```

We can do something like this to infer the response type from the category.

**Review by piitaya — DISMISSED** [review]
It only made a small suggestion but I'm ok with the global change

**Review by piitaya — DISMISSED** [review]

File: src/data/icons.ts [hunk 2]
```diff
@@ -70,60 +87,79 @@ export const getPlatformIcons = async (
...
+): Promise<PlatformIcons | undefined> => {
   if (!force && integration in resources.entity) {
     return resources.entity[integration];
   }
-  const result = getHassIcons(hass, "entity", integration);
-  resources.entity[integration] = result.then(
+  if (!isComponentLoaded(hass, integration)) {
+    return undefined;
+  }
+  const result = getHassIcons<"entity">(hass, "entity", integration).then(
```
Comment (piitaya) [inline src/data/icons.ts:97]:
```suggestion
  const result = getHassIcons(hass, "entity", integration).then(
```

File: src/data/icons.ts [hunk 3]
```diff
@@ -70,60 +87,79 @@ export const getPlatformIcons = async (
...
   }
-  resources.entity_component = getHassIcons(hass, "entity_component").then(
-    (result) => result.resources
-  );
-  return resources.entity_component.then((res) => res[domain]);
+  if (!isComponentLoaded(hass, domain)) {
+    return undefined;
+  }
+  resources.entity_component.domains = [...hass.config.components];
+  resources.entity_component.resources = getHassIcons<"entity_component">(
```
Comment (piitaya) [inline src/data/icons.ts:120]:
```suggestion
  resources.entity_component.resources = getHassIcons(
```

File: src/data/icons.ts [hunk 4]
```diff
@@ -70,60 +87,79 @@ export const getPlatformIcons = async (
...
     if (!force && resources.services.all) {
       return resources.services.all;
     }
-    resources.services.all = getHassIcons(hass, "services", domain).then(
-      (res) => {
-        resources.services = res.resources;
-        return res?.resources;
-      }
-    );
+    resources.services.all = getHassIcons<"services">(
```
Comment (piitaya) [inline src/data/icons.ts:136]:
```suggestion
    resources.services.all = getHassIcons(
```

File: src/data/icons.ts [hunk 5]
```diff
@@ -70,60 +87,79 @@ export const getPlatformIcons = async (
...
+      return resources.services.domains[domain];
     }
   }
-  const result = getHassIcons(hass, "services", domain);
-  resources.services[domain] = result.then((res) => res?.resources[domain]);
-  return resources.services[domain];
+  if (!isComponentLoaded(hass, domain)) {
+    return undefined;
+  }
+  const result = getHassIcons<"services">(hass, "services", domain);
```
Comment (piitaya) [inline src/data/icons.ts:158]:
```suggestion
  const result = getHassIcons(hass, "services", domain);
```

**Review by piitaya — COMMENTED** [review]
Don't even need to add type as it's inferred.

**Comment by bramkragten** [comment]
I tried that before, but that doesn't work:
`const result: Promise<PlatformIcons | ComponentIcons | ServiceIcons>`

**Review by piitaya — APPROVED** [review]
