### PR TITLE
Use new entity picker style in quick bar

### LINKED ISSUE #25260: New 2025.5 entity picker not working on `E` hotkey
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When using the `E` hotkey the new entity picker introduced in the 2025.5 beta is not shown

### Describe the behavior you expected

Use the new entity picker for the `E` hotkey

### Steps to reproduce the issue

1. Press `E` while on a Home Assistant page
2. Try to pick an entity

### What version of Home Assistant Core has the issue?

2025.5.0b0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Google Chrome 136.0.7103.48

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jpbede**
## Proposed change
Use the new entity picker style in the quick bar as well.

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #25260
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/quick-bar/ha-quick-bar.ts [hunk 1]
```diff
@@ -555,18 +590,43 @@ export class QuickBar extends LitElement {
...
+
+        const primary = entityName || deviceName || entityId;
+        const secondary = [areaName, entityName ? deviceName : undefined]
+          .filter(Boolean)
+          .join(isRTL ? " ◂ " : " ▸ ");
+
+        const translatedDomain = domainToName(
+          this.hass.localize,
+          computeDomain(entityId)
+        );
```
Comment (piitaya) [inline src/dialogs/quick-bar/ha-quick-bar.ts:614]: Translations must be loaded in `firstUpdated` using `this.hass.loadBackendTranslation("title");`

**Review by piitaya — CHANGES_REQUESTED** [review]

File: src/dialogs/quick-bar/ha-quick-bar.ts (hunk 1 above)
Comment (jpbede) [reply src/dialogs/quick-bar/ha-quick-bar.ts:614]: Oh, thanks, that would explain why the translations don't appear from time to time 🙂

**Comment by nagtegaal** [comment]
Please make sure that the selection and insertion, of these entities-selectors within the mobile environment are also reflecting the selection which has been made. Prior to 2025.5, not every entity selection list is working as intended. So when you tap an entity from the list, make sure it is inserted in the selection field which triggered the list itself. Also when manually typing a portion of an entity, and then selecting it by tapping the desired entity to use from the list.

**Comment by piitaya** [comment]
@nagtegaal This change also fix the issue you described.

**Review by piitaya — APPROVED** [review]
