### PR TITLE
Fix more info group

### LINKED ISSUE #7307: Brightness slider doesn't appear for a light group
## Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

## The problem

In the previous HA versions I could set brightness for a group consisting of light entities. Now the brightness slider does not show up in the details view when I tap on a group entity in Lovelalce. I discovered a workaround for this: tap on a single light and then back on a light group. The slider then appears, but it's annoying that I have to do that every time I want  to control brighntess of a hole group (and I do that quite often for 3 light spots in my Living room).
image

## Expected behavior
Brightness slider should show up for a light group. It used to work fine in previous HA versions

## Steps to reproduce
1. Open HA GUI either HA app or desktop.
2. Tap on a group of lights
3. Observe no slider
4. Tap on a single light from this group
5. Slider appears just fine
6. Tap back on the light group. 
7. Then the slider apperas fine again but is lost when I refresh page or exit and reenter the HA app
image

## Environment

, Windows 10, Android HA app (Android 10)
- Home Assistant release with the issue:  0.116.2.
- Last working Home Assistant release (if known): 0.113, maybe 0.115 as well, but not sure here
- Browser and browser version: Chrome 85.0.4183.121 + the newest HA Android app - same behaviour
- Operating system: Windows 10, Android 11

## State of relevant entities

image
This happens for both situations when the lights in the group are on and off.
```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Fixes: #7307

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/more-info/controls/more-info-group.ts [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+      this._groupDomainStateObj = undefined;
+      this._moreInfoType = undefined;
+    }
+  }
+
+  protected render(): TemplateResult {
+    if (!this.hass || !this.stateObj) {
+      return html``;
+    }
+    return html` ${this._moreInfoType
```
Comment (zsarnett) [inline src/dialogs/more-info/controls/more-info-group.ts:75]:
```suggestion
    return html`${this._moreInfoType
```

**Review by zsarnett — APPROVED** [review]
