### PR TITLE
Automation traces localization

### LINKED ISSUE #18360: Missing in lokalise existing automation - "No traces found"
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Missing in lokalise

Screen can be found in web version Settings/Automations and Scenes/ in existing automatisation

Snag_NoTracesFound

### Describe the behavior you expected

Add to lokalise

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.10.5

### What was the last working version of Home Assistant Core?

not relevant

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change
Add some localization to automation traces area. 
Some tabs ids have been changed from "config" into either "step_config", "automation_config" or "blueprint_config". 

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #18360
- This PR is related to issue or discussion: #18362
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/trace/ha-trace-path-details.ts [hunk 1]
```diff
@@ -34,7 +47,8 @@ export class HaTracePathDetails extends LitElement {
 
   @property() public trackedNodes!: Record<string, any>;
 
-  @state() private _view: "config" | "changed_variables" | "logbook" = "config";
+  @state() private _view: "step_config" | "changed_variables" | "logbook" =
```
Comment (bramkragten) [inline src/components/trace/ha-trace-path-details.ts:50]:
```suggestion
  @state() private _view: typeof TRACE_PATH_TABS[number] =
```

File: src/panels/config/automation/ha-automation-trace.ts [hunk 2]
```diff
@@ -41,6 +48,8 @@ import { haStyle } from "../../../resources/styles";
 import { HomeAssistant, Route } from "../../../types";
 import { computeRTL } from "../../../common/util/compute_rtl";
 
+const TABS = ["details", "automation_config", "timeline", "logbook"] as const;
```
Comment (bramkragten) [inline src/panels/config/automation/ha-automation-trace.ts:51]: The typing of `_view` doesn't match this

**Review by bramkragten — APPROVED** [review]
