### PR TITLE
Ignore disconnect codes for shutdown and reboot

### LINKED ISSUE #6894: BUG : Failed to reboot error message
## The problem

Everytime i want to reboot Home Assistant using the supervisor, i get an error message "Failed to reboot" "unknow error, see logs".

But of course, logs are empty because the system DOES reboot. i don't know what causes this error message to show, but it is annoying :)

Supervisor version : 242
HassOS : 4.12
running on a raspberry pi 3b

Screenshot below:
Failed to reboot

Thanks in advance,

### PR DESCRIPTION
**Pull request by ludeeus**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #6894
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — APPROVED** [review]

File: hassio/src/system/hassio-host-info.ts [hunk 1]
```diff
@@ -245,10 +248,14 @@ class HassioHostInfo extends LitElement {
     try {
       await rebootHost(this.hass);
     } catch (err) {
-      showAlertDialog(this, {
-        title: "Failed to reboot",
-        text: extractApiErrorMessage(err),
-      });
+      console.log(err);
```
Comment (bramkragten) [inline hassio/src/system/hassio-host-info.ts:251]:
```suggestion
```

Comment (ludeeus) [reply hassio/src/system/hassio-host-info.ts]: Sorry!
