### PR TITLE
Fixed modal visibility issue in settings -> areas -> edit room

### LINKED ISSUE #28904: La fenêtre “Sélectionner parmi les médias” s’ouvre derrière “Modifier la pièce” (HA 2026.1.0)
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Since the 2026.1.0 update, it is impossible to assign a photo to a room.

When clicking “Select from media” inside the “Edit room” window, the media selection window opens in the background, behind the edit window.

Both windows are modal and cannot be moved, making it impossible to select or confirm an image. The issue is reproducible on desktop browsers (Edge/Chrome) and on Android.

### Describe the behavior you expected

The “Select from media” window should appear in the foreground or replace the previous window.

### Steps to reproduce the issue

1. Go to Settings → Home → Areas
2. Select an area → “Edit room”
3. Click “Select from media”
4. Observe that the media selection window opens behind the edit window
5. It is impossible to interact with the media selection window

### What version of Home Assistant Core has the issue?

2026.1.0

### What was the last working version of Home Assistant Core?

2025.12.5

### In which browser are you experiencing the issue?

Edge Version 143.0.3650.96 (Version officielle) (64 bits)

### Which operating system are you using to run this browser?

Windows 11 

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

Image

### PR DESCRIPTION
**Pull request by smartcoder0777**
Fixes: https://github.com/home-assistant/frontend/issues/28904

## Proposed change
_Root Cause:_ ha-dialog (Material Design) and ha-wa-dialog (Web Awesome with native <dialog>) use incompatible stacking systems. The native dialog element's "top layer" always appears above regular DOM, making z-index ineffective.

_Solution Applied:_
~~Converted dialog-area-registry-detail from ha-wa-dialog to ha-dialog - both dialogs now use the same Material Design system~~
- Z-index configuration:
    Media player dialog: z-index: 9 (will be on top)
    Area registry dialog: z-index: 8 (will be below)
Updated dialog structure to use ha-dialog slots and actions pattern

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

  The ha-dialog component uses a different structure than ha-wa-dialog. 
For ha-dialog (Material Design based), buttons should be placed directly with slot="primaryAction" or slot="secondaryAction" without wrapping them in ha-dialog-footer. The ha-dialog-footer component is only used with ha-wa-dialog.

- This PR fixes or closes issue: fixes #https://github.com/home-assistant/frontend/issues/28904

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

**Before fix:**
image

**After fix**
image

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by karwosts** [comment]
>  Converted dialog-area-registry-detail from ha-wa-dialog to ha-dialog - both dialogs now use the same Material Design system

This is the wrong direction, we're currently in process of migrating _to_ webawesome dialogs.

**Review by silamon — DISMISSED** [review]
Given that changes have been requested, I'm going to let it mark as draft. Feel free to undraft it when changes are made.

**Comment by smartcoder0777** [comment]
I just pushed the update.
I migrated area and media browser dialogs to ha-wa-dialog
It fixed modal stacking issue by converting both dialog-area-registry-detail and dialog-media-player-browse to use ha-wa-dialog (Web Awesome) instead of ha-dialog (Material Design). 
Both dialogs now use native <dialog> elements with proper top-layer stacking.

@karwosts @silamon please review my updates. If it looks good, please merge it and close the issue. 

Thanks

File: src/components/ha-wa-dialog.ts [hunk 1]
```diff
@@ -250,6 +250,7 @@ export class HaWaDialog extends ScrollableFadeMixin(LitElement) {
             var(--ha-border-radius-3xl)
           );
           max-width: var(--ha-dialog-max-width, var(--safe-width));
+          z-index: var(--dialog-z-index, 8);
```
Comment (karwosts) [inline src/components/ha-wa-dialog.ts]: Please explain why you added this, seems dubious that this needs a change to every dialog.

File: src/components/media-player/dialog-media-player-browse.ts [hunk 2]
```diff
@@ -71,21 +71,14 @@ class DialogMediaPlayerBrowse extends LitElement {
...
-        hideActions
-        flexContent
-        .heading=${!this._currentItem
-          ? this.hass.localize(
-              "ui.components.media-browser.media-player-browser"
-            )
-          : this._currentItem.title}
+      <ha-wa-dialog
+        .hass=${this.hass}
+        .open=${true}
```
Comment (karwosts) [inline src/components/media-player/dialog-media-player-browse.ts]: I don't think this should always be true. There have been many recent PRs examples of migrating to ha-wa-dialog, please review some of those to see how they handle open/close lifecycle and what kinds of changes are required.

**Review by karwosts — DISMISSED** [review]

**Comment by karwosts** [comment]
Also we would request you not @ people for reviews. Your changes are visible in the pending PR queue and a reviewer can clearly see them and will address them when they are ready. Please do not single out people or keep requesting reviews, anyone who wants to follow this thread can already control their notifications for themselves.

**Comment by smartcoder0777** [comment]
> Also we would request you not @ people for reviews. Your changes are visible in the pending PR queue and a reviewer can clearly see them and will address them when they are ready. Please do not single out people or keep requesting reviews, anyone who wants to follow this thread can already control their notifications for themselves.

I got it. Thanks

File: src/components/ha-wa-dialog.ts (hunk 1 above)
Comment (smartcoder0777) [reply src/components/ha-wa-dialog.ts]: You are right. It should be removed since  the native <dialog> elements in the top layer ignore z-index completely.

File: src/components/media-player/dialog-media-player-browse.ts (hunk 2 above)
Comment (smartcoder0777) [reply src/components/media-player/dialog-media-player-browse.ts]: Thanks for your good review. You are absolutely right. Let me fix it.

**Comment by smartcoder0777** [comment]
I updated the codebase and pushed it.

**Comment by smartcoder0777** [comment]
If it looks good, would you merge it and close the issue?

**Review by timmo001 — APPROVED** [review]
Thanks for this @smartcoder0777

**Comment by timmo001** [comment]
Final state of PR:

Migrates dialog to webawesome to be compatible with stacked dialog (shows on top now using native `<dialog`)
