### PR TITLE
Move Logbook and make device page better

### LINKED ISSUE #12759: New area logbook visual issues
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

1. In narrow mode, the padding looks off. We should consistently stick to left with 16px IMHO. Also not sure why it decides that this is narrow given that I am on a desktop monitor.
2. The fixed height is bad. For me that results in scrollbars although most of the logbook is empty. Something with a max-height would probably better so that it matches the content but does not grow endlessly.

image

### Describe the behavior you expected

See above

### Steps to reproduce the issue

1. Go to area page

### What version of Home Assistant Core has the issue?

2022.6.0.dev0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zsarnett**
## Proposed change

Move Logbook to right on Device page
Fixes height on Logbook in Area Page

Updates device actions to be in overflow 
Places ZHA and Zwave Device information in expansion panel

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #12759
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/devices/device-detail/integration-elements/zha/ha-device-info-zha.ts [hunk 1]
```diff
@@ -40,38 +41,39 @@ export class HaDeviceActionsZha extends LitElement {
...
-      </div>
-      ${this._zhaDevice.quirk_applied
-        ? html`
-            <div>
-              ${this.hass!.localize("ui.dialogs.zha_device_info.quirk")}:
-              ${this._zhaDevice.quirk_class}
-            </div>
-          `
-        : ""}
+      <ha-expansion-panel .header=${"Zigbee info"}>
```
Comment (bramkragten) [inline src/panels/config/devices/device-detail/integration-elements/zha/ha-device-info-zha.ts:44]:
```suggestion
      <ha-expansion-panel header="Zigbee info">
```

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
