### PR TITLE
Take cover "opening" and "closing" into account

### LINKED ISSUE #8489: Somfy myLink multiple commands frontend
**Checklist**

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

**Describe the issue you are experiencing**

When I send a command (cover.down) I'll get a double command in the log book & history showing different commands

7:56:55 PM - 3 seconds ago
Was opened by $user
7:56:34 PM - 24 seconds ago
Was closed by $user

It show only display opened command given by $user. 

Also if you send a cover.stop it should display a "Was STOPPED by $user". Right now it doesn't display a stop command in the history

further more, the command for cover.open_cover_tilt shoud send move.tiltup command and the cover.close_cover_tilt should send move.tiltdown command in the API. Right now it doesn't send a command for tilt. (EDIT for typo)

**Describe the behavior you expected**

Should only send/display 1 command in the history. UP should display opened command. DOWN should display closed command. STOP should display Partially Opened in the history.

Tilt UP should display Tilted up in the history
Tilt DOWN should display Tilted down in the history 

**Steps to reproduce the issue**

1. History iis wrong
2.
3.
...

**What version of Home Assistant Core has the issue?**

core-2021.2.3

**What was the last working version of Home Assistant Core?**

None - Known issue.

**In which browser are you experiencing the issue with?**

Google Chrome

**Which operating system are you using to run this browser?**

Version 88.0.4324.190 (Official Build) (64-bit)

**State of relevant entities**

```yaml
# Paste your state here.

```

**Problem-relevant frontend configuration**

```yaml
# Paste your YAML here.

```
image

**Javascript errors shown in your browser console/inspector**

Double command for UP being display and wrong commands. I send an UP command it displays in the history closed and then opened.

Kitchen Slider Left was opened by $user
7:56:34 PM - 10 minutes ago
Kitchen Slider Left was closed by $user

History needs to be fixed for the double commands being generated along with the tilt commands

up = move.tiltup for the API call
down = move.tiltdown for the API call

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Frontend logbook only considered `open`and `closed` in the logbook, but not the intermediate states `opening` and `closing`.

image

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/8489
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/data/logbook.ts [hunk 1]
```diff
@@ -216,7 +216,6 @@ export const getLogbookMessage = (
         case "cold":
         case "gas":
         case "heat":
-        case "colightld":
```
Comment (bdraco) [inline src/data/logbook.ts:219]: Intentional change or cruft on the branch?

Comment (spacegaier) [reply src/data/logbook.ts:219]: Ah, forgot to add a comment: Intentional change. This seems to be a very old legacy entry, if even Paulus is not aware of it: https://discord.com/channels/330944238910963714/674164904298676225/806654268378841128

That value is not used anywhere in core or frontend.

**Review by bdraco — APPROVED** [review]
LGTM

**Review by bramkragten — APPROVED** [review]
