### PR TITLE
Fix Automation Creation Dialog

### LINKED ISSUE #13311: Create new automation dubble 'Select a Blueprint'
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When i klick on 'create automation' i get the following dialog with dubble text 'Select a Blueprint'.
 Schermafbeelding 2022-07-30 om 12 10 47

### Describe the behavior you expected

Just one time the 'Select a Blueprint'

### Steps to reproduce the issue

1. Go to 'Settings'
2. 'Automation & scenes'
3. '+ Create Automation'

### What version of Home Assistant Core has the issue?

2022.8.0b3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome 103.0.5060.134 (Officiële build) (x86_64), Safari 15.5 (17613.2.7.1.8)

### Which operating system are you using to run this browser?

macOS Monterey 12.4

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zsarnett**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #13311
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-blueprint-picker.ts [hunk 1]
```diff
@@ -54,12 +54,12 @@ class HaBluePrintPicker extends LitElement {
...
         fixedMenuPosition
         naturalMenuWidth
-        .value=${this.value}
+        .value=${this.value || "default"}
         .disabled=${this.disabled}
         @selected=${this._blueprintChanged}
         @closed=${stopPropagation}
       >
-        <mwc-list-item value="">
+        <mwc-list-item value="default">
```
Comment (bramkragten) [inline src/components/ha-blueprint-picker.ts:62]: use the `selected` attribute

Comment (bramkragten) [reply src/components/ha-blueprint-picker.ts:62]: Or just remove this item?

**Review by bramkragten — APPROVED** [review]
