### PR TITLE
Set Error if entity is unavailable

### LINKED ISSUE #12617: Media entity not found
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When I open the Media Browser panel and I previously selected an offline device, the Media Browser would show me "Entity not found". The entity exists. But it's device is offline.
image

### Describe the behavior you expected

It should show something like "Device is offline" or "Entity not available"

### Steps to reproduce the issue

1. I previously selected a media player entity that's offline now, but when I selected it, it was not.
2. The Media Browser remembers the previously selected (offline) entity.
3. So when I open up the Media Browser, it shows the entity not found (it is there, but it's offline.

### What version of Home Assistant Core has the issue?

core-2022.5.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome 101.0.4951.54 (64-bit)

### Which operating system are you using to run this browser?

Windows 10 version 21H2

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by zsarnett**
## Proposed change

CleanShot 2022-05-25 at 23 06 03

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #12617
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/media-player/ha-media-player-browse.ts [hunk 1]
```diff
@@ -246,6 +248,13 @@ export class HaMediaPlayerBrowse extends LitElement {
             ],
             replace: true,
           });
+        } else if (
+          UNAVAILABLE_STATES.includes(this.hass.states[this.entityId]?.state)
+        ) {
+          this._setError({
+            message: "Entity unavailable",
```
Comment (spacegaier) [inline src/components/media-player/ha-media-player-browse.ts:255]: Is that something we can translate?

File: src/components/media-player/ha-media-player-browse.ts [hunk 2]
```diff
@@ -305,7 +314,11 @@ export class HaMediaPlayerBrowse extends LitElement {
   protected render(): TemplateResult {
     if (this._error) {
       return html`
-        <div class="container">${this._renderError(this._error)}</div>
+        <div class="container">
+          <ha-alert alert-type="error"
+            >${this._renderError(this._error)}</ha-alert
+          >
```
Comment (bramkragten) [inline src/components/media-player/ha-media-player-browse.ts:320]:
```suggestion
          <ha-alert alert-type="error">
            ${this._renderError(this._error)}
          </ha-alert>
```

File: src/components/media-player/ha-media-player-browse.ts [hunk 3]
```diff
@@ -420,7 +433,9 @@ export class HaMediaPlayerBrowse extends LitElement {
               this._error
                 ? html`
                     <div class="container">
-                      ${this._renderError(this._error)}
+                      <ha-alert alert-type="error"
+                        >${this._renderError(this._error)}</ha-alert
+                      >
```
Comment (bramkragten) [inline src/components/media-player/ha-media-player-browse.ts:438]:
```suggestion
                      <ha-alert alert-type="error">
                        ${this._renderError(this._error)}
                      </ha-alert>
```

File: src/components/media-player/ha-media-player-browse.ts (hunk 1 above)
Comment (bramkragten) [reply src/components/media-player/ha-media-player-browse.ts:255]: What is the `err` we get when this happens?

Comment (zsarnett) [reply src/components/media-player/ha-media-player-browse.ts:255]: Entity not found

Comment (bramkragten) [reply src/components/media-player/ha-media-player-browse.ts]: Can we not use that instead of checking the state?

File: src/components/media-player/ha-media-player-browse.ts [hunk 4]
```diff
@@ -246,6 +248,16 @@ export class HaMediaPlayerBrowse extends LitElement {
             ],
             replace: true,
           });
+        } else if (
+          err.code === "entity_not_found" &&
+          UNAVAILABLE_STATES.includes(this.hass.states[this.entityId]?.state)
```
Comment (bramkragten) [inline src/components/media-player/ha-media-player-browse.ts:253]: Do we need this check still?

**Review by bramkragten — APPROVED** [review]

File: src/components/media-player/ha-media-player-browse.ts (hunk 1 above)
Comment (zsarnett) [reply src/components/media-player/ha-media-player-browse.ts]: We do that now. The issue is that the entity is found its just unavailable.

File: src/components/media-player/ha-media-player-browse.ts (hunk 4 above)
Comment (zsarnett) [reply src/components/media-player/ha-media-player-browse.ts:253]: Yea. If the entity isnt found for another reason then we still just show the error. Not sure if there is another reason but guessing it could be possible to ask for an entity that doesn't exist at all
