### PR TITLE
Generic picker: show a label for area, category, language

### LINKED ISSUE #28049: No label for language field in general settings
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

UX Defect : no visible label on language field 

Image

### Describe the behavior you expected

Expecting "Language" like other fields for user reassurance

### Steps to reproduce the issue

Go to parameters > system > general

### What version of Home Assistant Core has the issue?

2025.11.3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

Méthode d'installation
Home Assistant OS
Core
2025.11.3
Supervisor
2025.11.4
Operating System
16.3
Interface utilisateur
20251105.1

### PR DESCRIPTION
**Pull request by ildar170975**
## Proposed change

Changes were made for:
`ha-language-picker`:

image

`ha-category-picker` - only for `ha-dialog-automation-save`:

image

`ha-area-picker` - only for:
-- `ha-dialog-automation-save`
-- `entity-registry-settings-editor`
-- `dialog-device-registry-detail`

image

Note that for `ha-area-picker` a label is only shown when a floor is not displayed (to prevent a clutter).

In `ha-combo-box-item`, styles were defined for `overline` slot to mimic (as possible) a floating label in `mdc-select`.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/28049
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-picker-field.ts [hunk 1]
```diff
@@ -49,13 +52,16 @@ export class HaPickerField extends LitElement {
   protected render() {
     const showClearIcon =
       !!this.value && !this.required && !this.disabled && !this.hideClearIcon;
+    const placeholder = this.showLabel
+      ? html`<span slot="overline">${this.placeholder}</span>`
+      : "";
```
Comment (timmo001) [inline src/components/ha-picker-field.ts]:
```suggestion
      : nothing;
```

File: src/components/ha-area-picker.ts [hunk 2]
```diff
@@ -360,9 +363,16 @@ export class HaAreaPicker extends LitElement {
...
-
     const valueRenderer = this._computeValueRenderer(this.hass.areas);
 
+    let showLabel;
+    if (this.value) {
+      const area_id = this.value;
+      const area = this.hass.areas[area_id];
+      const { floor } = getAreaContext(area, this.hass.floors);
+      showLabel = floor ? false : this.showLabel;
+    } else showLabel = this.showLabel;
```
Comment (timmo001) [inline src/components/ha-area-picker.ts]:
```suggestion
    } else {
      showLabel = this.showLabel;
    }
```

**Review by timmo001 — COMMENTED** [review]
Small code style tweaks

**Comment by marcinbauer-ohf** [comment]
This is great, thanks @ildar170975 🚀

**Comment by ildar170975** [comment]
Guys, thanks a lot for support

File: src/components/ha-area-picker.ts [hunk 3]
```diff
@@ -360,9 +363,18 @@ export class HaAreaPicker extends LitElement {
   protected render(): TemplateResult {
     const placeholder =
       this.placeholder ?? this.hass.localize("ui.components.area-picker.area");
-
     const valueRenderer = this._computeValueRenderer(this.hass.areas);
 
+    let showLabel;
```
Comment (timmo001) [inline src/components/ha-area-picker.ts]:
```suggestion
    let showLabel = this.showLabel;
```

File: src/components/ha-area-picker.ts [hunk 4]
```diff
@@ -360,9 +363,18 @@ export class HaAreaPicker extends LitElement {
...
+    if (this.value) {
+      const area_id = this.value;
+      const area = this.hass.areas[area_id];
+      const { floor } = getAreaContext(area, this.hass.floors);
+      showLabel = floor ? false : this.showLabel;
+    } else {
+      showLabel = this.showLabel;
```
Comment (timmo001) [inline src/components/ha-area-picker.ts]:
```suggestion
      const area = this.hass.areas[this.value];
      if (area) {
        const { floor } = getAreaContext(area, this.hass.floors);
        showLabel = !floor && this.showLabel;
      }
```

**Review by timmo001 — CHANGES_REQUESTED** [review]
You will also need to resolve the conflicts in the code, sorry I caused this 🙃

**Comment by ildar170975** [comment]
> resolve the conflicts 

No problem! I will do it in a few days when be near a PC. SORRY for a delay.

**Review by timmo001 — APPROVED** [review]
Thanks @ildar170975 !

**Comment by karwosts** [comment]
I've got a few concerns about this:

The labels are lost here, we used to have label that said "device energy consumption / device power consumption"

image

When an entity is selected, this feel pretty cramped at the top:

image

**Comment by karwosts** [comment]
Hmm actually sorry, maybe that is more related to https://github.com/home-assistant/frontend/pull/28570, not sure...
