### PR TITLE
fix #11041: The gauge card doesn't render correctly on iOS 15.2 / macOS 12.1 in the companion apps

### LINKED ISSUE #11041: The gauge card doesn't render correctly on iOS 15.2 / macOS 12.1 in the companion apps
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

This is the same issue as #10766 for which a partial fix was submitted via #10992. A potential fix was suggested in [this comment](https://github.com/home-assistant/frontend/pull/10992#issuecomment-1002134042).

### Describe the behavior you expected

The gauge card should correctly render also in the Home Assistant companion apps on both iOS/macOS.

### Steps to reproduce the issue

Have a gauge card configured like:
```
- type: gauge
   entity: sensor.temperature
   min: 0
   max: 100
   severity:
     green: 20
     yellow: 22
     red: 25
   name: ' '
```

### What version of Home Assistant Core has the issue?

core-2021.12.6 (and earlier)

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Safari 15.2 +

### Which operating system are you using to run this browser?

macOS 12.1, iOS 15.2

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by raducotescu**
Co-authored-by: Bram Kragten <mail@bramkragten.nl>
Co-authored-by: Radu Cotescu <radu-likes-to-code@cotescu.com>

## Proposed change

* changed the gauge's viewport so that all browsers render it the same
* removed Safari-specific handling

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #11041 
- This PR is related to issue or discussion: #11052 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by raducotescu** [comment]
@bramkragten, I've tested this PR on Safari on iOS 13.3, iOS 14.5, iOS 15.1, iOS 15.2.1, as well as in the Home Assistant companion app on iOS 15.1, iOS 15.2.1 and macOS 12.2 beta (21D5025f).

In addition, I also tested the fix on Chrome 97.0.4692.71, Safari 15.3 (17612.4.2.1.2) and Firefox 95.0.2 on macOS 12.2 beta (21D5025f).

We should be finally ready to fix this issue. Thanks for the help!

File: src/components/ha-gauge.ts [hunk 1]
```diff
@@ -110,46 +104,17 @@ export class Gauge extends LitElement {
...
-                    : undefined
-                )}
-                transform=${ifDefined(
-                  isSafari
-                    ? `rotate(${this._angle}${isSafari152 ? "" : " 50 50"})`
-                    : undefined
-                )}
+                d="M -25 -2.5 L -47.5 0 L -25 2.5 z"
+                style=${styleMap({ transform: `rotate(${this._angle}deg)` })}
+                transform=${`rotate(${this._angle})`}
```
Comment (bramkragten) [inline src/components/ha-gauge.ts:109]:
```suggestion
```

**Review by bramkragten — DISMISSED** [review]

**Comment by raducotescu** [comment]
@bramkragten, I've updated the PR with your suggestion. Thanks!

I've tested it on iOS 14.5 and iOS 15.2.1. 👍🏻

**Review by zsarnett — APPROVED** [review]
