### PR TITLE
`conditional` & `entity-filter`: add ability to filter through `entity_id` & add `entity-filter` `conditional`'s conditions

### LINKED ISSUE #13343: entity-filter operators don't work as intended with state as a value and == operator
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I want to display a list of cheapest gas station.

Once having the price of nearest stations, I created a min/max helper with those sensors, and now I want to display stations with the cheapest price.
So when [min price] == price

The problem is that I can't display filtered stations because the state_filter operator don't seems to work properly.

Now, with `operator: <=` !!

image

```
type: entity-filter
entities:
  - sensor.station_auchan_saint_priest_e10
  - sensor.station_carrefour_venissieux_e10
  - sensor.station_leclerc_drive_e10
  - sensor.prix_carburant
state_filter:
  - operator: <=
    value: sensor.prix_carburant
card:
  title: Stations essence les moins chères
  type: entities
```

With `operator: ==` !!

image

code 
```
type: entity-filter
entities:
  - sensor.station_auchan_saint_priest_e10
  - sensor.station_carrefour_venissieux_e10
  - sensor.station_leclerc_drive_e10
  - sensor.prix_carburant
state_filter:
  - operator: ==
    value: sensor.prix_carburant
card:
  title: Stations essence les moins chères
  type: entities
```

Then one with the red cross should be filtered, and the last line (lined with yellowed) indicate the min price and is here for this demo only.

----

While writing this issue I've noticed that the value of the value attribute is the cause of that

image

image

Apparently it's impossible to assigne a state to the value attribute.

Tried with curly, same results

image

----

There is an issue with `==` operator, see

image

image

image

### Describe the behavior you expected

1. state should be a good parameter of state_filter.value
2. `operator: ==` should display equals values

### Steps to reproduce the issue

1. Create 3 helper `input_number` with values 1, 2 & 3
2. Create an entity-filter card like this
```
type: entity-filter
entities:
  - input_number.test1
  - input_number.test2
  - input_number.test3
state_filter:
  - operator: <=
    value: 2
card:
  type: entities
```
It's working
3.  Create an entity-filter card like this
```
type: entity-filter
entities:
  - input_number.test1
  - input_number.test2
  - input_number.test3
state_filter:
  - operator: <=
    value: input_number.test2
card:
  type: entities
```
It's not working
4. same for `operator: ==`

### What version of Home Assistant Core has the issue?

core-2022.8.0

### What was the last working version of Home Assistant Core?

?

### In which browser are you experiencing the issue with?

Microsoft Edge 102.0.1245.50, Safari iOS 15.6

### Which operating system are you using to run this browser?

Windows 10, iOS 15.6

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

Exemple with gas station price only, not applicable to test bench
```shell
       RangeError: Invalid currency code : â¬
    at new NumberFormat (<anonymous>)
    at A (86066a2d.js:1:35223)
    at h (95446709.js:1:1244)
    at p (95446709.js:1:922)
    at F.value (hui-sensor-entity-row.ts:72:1)
    at F.update (styles.ts:370:1)
    at F.performUpdate (styles.ts:370:1)
    at F.scheduleUpdate (styles.ts:370:1)
    at F._$EC (styles.ts:370:1)
```

### Additional information

Documentation: https://www.home-assistant.io/dashboards/entity-filter/#operator

### PR DESCRIPTION
**Pull request by Quentame**
## Proposed change

- add to `conditional` card: `state` condition handle `entity_id`
- add to `conditional` card: `numeric_state` condition handle `entity_id`
- add to `entity-filter` card & badge: ALL `conditional` card conditions: `state`, `numeric_state`, `screen`, `user`, `or`, `and`
- fix to `entity-filter` card & badge: "`operator`" condition `in` with number
- fix to `entity-filter` card: error when no entities
- NO BREAKING CHANGES as legacy `entity-filter` config is still supported !

### entity-filter card

| Current dev  | NEW |
| ------------- | ------------- |
| entity-filter_dev  | entity-filter_new |

### conditional card

| Current dev  | NEW |
| ------------- | ------------- |
| conditional_dev  | conditional_new |

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
- type: entity-filter
  entities:
    - sensor.gas_station_1
    - sensor.gas_station_2
    - sensor.gas_station_3
  conditions:
    - condition: state
      state: sensor.gas_station_lowest_price
```

## Additional information

- This PR fixes or closes issue: fixes #13343
- This PR is related to issue or discussion:
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/30561

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [x] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/common/evaluate-filter.ts [hunk 1]
```diff
@@ -1,12 +1,31 @@
...
+  }
 
-export const evaluateFilter = (stateObj: HassEntity, filter: any): boolean => {
   const operator = filter.operator || "==";
   let value = filter.value ?? filter;
   let state = filter.attribute
     ? stateObj.attributes[filter.attribute]
     : stateObj.state;
 
+  if (typeof value === "string" && value.includes(".")) {
```
Comment (Quentame) [inline src/panels/lovelace/common/evaluate-filter.ts:21]:
```suggestion
  if (typeof value === "string" && RegExp("(sensor|number)\.").test(value)) {
```
Or maybe something like this to better check `sensor`/`input_number`/`number` entities ?

File: gallery/src/pages/lovelace/entity-filter-card.ts [hunk 2]
```diff
@@ -107,6 +132,43 @@ const CONFIGS = [
...
+- type: entity-filter
+  entities:
+    - sensor.gas_station_auchan_saint_priest_e10
+    - sensor.gas_station_carrefour_venissieux_e10
+    - sensor.gas_station_relais_lyon_mermoz_e10
+  state_filter:
+    - operator: ==
+      value: sensor.gas_station_lowest_price
+    `,
+  },
```
Comment (Quentame) [inline gallery/src/pages/lovelace/entity-filter-card.ts:171]:
```suggestion
  },
  {
    heading: "Filtered entities with operator & template value",
    config: `
- type: entity-filter
  entities:
    - sensor.gas_station_auchan_saint_priest_e10
    - sensor.gas_station_carrefour_venissieux_e10
    - sensor.gas_station_relais_lyon_mermoz_e10
  state_filter:
    - operator: <=
      value: {{ float(states.sensor.gas_station_lowest_price.state) + 0.05 }}
    `,
  },
```
I would love to make `value` template compatible too but I couldn't make it.

Having `filter.value` = `[object Object]: null`
image

File: src/panels/lovelace/common/evaluate-filter.ts (hunk 1 above)
Comment (karwosts) [reply src/panels/lovelace/common/evaluate-filter.ts:21]: If you want to limit I've seen code like:

`isValidEntityId(value) && ["sensor", "input_number", "number"].includes(computeDomain(value))`

There's a lot of common entity parsing functions for things like this.

File: gallery/src/pages/lovelace/entity-filter-card.ts (hunk 2 above)
Comment (karwosts) [reply gallery/src/pages/lovelace/entity-filter-card.ts:171]: I believe it's a conscious decision to not really support templates in any frontend cards (aside from maybe markdown).

I think it might be a performance thing, but I could be wrong. 

But I would guess a template is not going to be accepted here.

File: src/panels/lovelace/common/evaluate-filter.ts [hunk 3]
```diff
@@ -1,12 +1,31 @@
...
+    value = hass.states[value]?.state;
+
+    if (!value) {
```
Comment (karwosts) [inline src/panels/lovelace/common/evaluate-filter.ts:24]:
```suggestion
    if (value === undefined) {
```

I believe an empty string may be a legitimate state value, in which case we can allow that to pass through for comparison.

File: gallery/src/pages/lovelace/entity-filter-card.ts (hunk 2 above)
Comment (Quentame) [reply gallery/src/pages/lovelace/entity-filter-card.ts:171]: And the sensor itself could be a template one 🤷🏼‍♂️

File: src/panels/lovelace/common/evaluate-filter.ts (hunk 1 above)
Comment (Quentame) [reply src/panels/lovelace/common/evaluate-filter.ts:21]: Ok, thanks for the info.

But while I saw reading, finally I don't think it's good to limit that as == ou != operators could still work with non number entity.

File: src/panels/lovelace/common/evaluate-filter.ts (hunk 3 above)
Comment (Quentame) [reply src/panels/lovelace/common/evaluate-filter.ts:24]: And for 0

File: src/panels/lovelace/common/evaluate-filter.ts (hunk 1 above)
Comment (karwosts) [inline src/panels/lovelace/common/evaluate-filter.ts:21]: Should we maybe have used a new/different key other than `filter.value` for entity ids? Now I'm thinking that value string that has a `.` in it will no longer work since it will now be interpreted as an entity id, where maybe it was just supposed to be interpreted as a raw string. Like if it's filtering for state == "O.K." or "3.0" or something. 

Maybe instead of overloading filter.value with entity_ids, could have used filter.entity_id or filter.value_entity or something. Just something to think about that this might be breaking some existing usage.

Comment (Quentame) [reply src/panels/lovelace/common/evaluate-filter.ts:21]: Oh yeah sure, reopening my first comment then.

As discussed [here](https://github.com/home-assistant/frontend/pull/19182#discussion_r1438345035): could `isValidEntityId` be enough ?

Will check

Comment (karwosts) [reply src/panels/lovelace/common/evaluate-filter.ts:21]: isValidEntityId is probably not the right answer, as it's a very loose check, and it would still pass on things that may not be intended to be entities. 

IMO using a different key would be the correct solution.

Comment (Quentame) [reply src/panels/lovelace/common/evaluate-filter.ts]: 8c92954 should fix, as before changing the `value` value, it checks if the `value` is an `entity_id` part of `hass.states`.

Also using `isValidEntityId`: similar to `.includes(".")` but a regex to check word before and after the dot.

Comment (bramkragten) [reply src/panels/lovelace/common/evaluate-filter.ts]: I think core does similar things in automations, using the same field for entity id and a value, we should check what logic is used there and do the same.

Like:

```yaml
condition:
  condition: numeric_state
  entity_id: climate.living_room_thermostat
  attribute: temperature
  above: 17
  below: sensor.value
  ```

Comment (karwosts) [reply src/panels/lovelace/common/evaluate-filter.ts]: I suspect that might only work because `above` is treated as a literal if it is a number type, or as an entity if it is a string type.

Not sure if there's a case where a value can either be a literal string or an entity string.

Comment (bramkragten) [reply src/panels/lovelace/common/evaluate-filter.ts]: True, we could fix this, and make it consistent by actually using the syntax we use in the automation conditions and the conditional card... So you would get:

```yaml
- type: entity-filter
  entities:
    - sensor.gas_station_auchan_saint_priest_e10
    - sensor.gas_station_carrefour_venissieux_e10
    - sensor.gas_station_relais_lyon_mermoz_e10
  state_filter:
    - condition: numeric_state
      above: 17
      below: sensor.value
  ```

Comment (karwosts) [reply src/panels/lovelace/common/evaluate-filter.ts]: I don't think this quite address my concern as we don't have a matching syntax in automations for **non-numeric** state compare, where state can be either a string or an entity-id. Only numeric_state allows the field to be an entity_id. State condition does not allow that. 

But anyway it was just a minor suggestion, and I don't think it's a showstopper, so I guess whatever you settle on would be fine for most cases.

Comment (Quentame) [reply src/panels/lovelace/common/evaluate-filter.ts]: Using consistent syntax (as automation or conditional card) is also making breaking changes for this card.

How could we handle that ?

Comment (piitaya) [reply src/panels/lovelace/common/evaluate-filter.ts]: The old syntax should be removed from documentation but still functional in the card.

File: src/panels/lovelace/common/evaluate-filter.ts [hunk 4]
```diff
@@ -1,12 +1,32 @@
 import { HassEntity } from "home-assistant-js-websocket";
+import { HomeAssistant } from "../../../types";
+import { isValidEntityId } from "../../../common/entity/valid_entity_id";
+
+export const evaluateFilter = (
+  hass: HomeAssistant,
+  current_entity_id: string,
+  filter: any
```
Comment (Quentame) [inline src/panels/lovelace/common/evaluate-filter.ts:8]:
```ts
filter: FilterDeprecated | Filter

FilterDeprecated {
  operator: string;
  attribute?: string;
  state: string | number;
}

Filter {
  condition: "state" | "numeric_state";
  attribute?: string;
  state?: string | number;
  below?: string | number;
  above?: string | number;
}
```

Comment (karwosts) [reply src/panels/lovelace/common/evaluate-filter.ts:8]: Hmm, the deprecated operators were:
`==`, `<=`, `<`, `>=`, `>`, `!=`, `in`, `not in`, or `regex`.

I don't think there's a replacment for a lot of these in the new syntax?

Comment (bramkragten) [reply src/panels/lovelace/common/evaluate-filter.ts:8]: > I don't think there's a replacment for a lot of these in the new syntax?

Correct, they will stay in the old format only

Comment (Quentame) [reply src/panels/lovelace/common/evaluate-filter.ts:8]: While developing 8c929545174c7b907cd28065ba4817696094b991, I typed for `condition: numeric_state`, `condition: state` and `condition: operator`, which is the old syntax, that still works property

File: src/panels/lovelace/common/evaluate-filter.ts (hunk 1 above)
Comment (Quentame) [reply src/panels/lovelace/common/evaluate-filter.ts]: Forgot to push but my last night commit about adding new conditions types, but.
It is kinda bigger than this one ... should we merge this PR before and make a separate PR for new conditions types or stack it to this one ?

Next:  `condition: numeric_state`, `condition: state` and `condition: operator`, which is the old syntax, backward compatible.

File: src/panels/lovelace/common/evaluate-filter.ts [hunk 5]
```diff
@@ -1,12 +1,32 @@
...
   const operator = filter.operator || "==";
   let value = filter.value ?? filter;
   let state = filter.attribute
     ? stateObj.attributes[filter.attribute]
     : stateObj.state;
 
+  if (
+    typeof value === "string" &&
+    isValidEntityId(value) &&
+    hass.states[value]
```
Comment (Quentame) [inline src/panels/lovelace/common/evaluate-filter.ts:25]:
```suggestion
    hass.states[value] !== undefined
```
?

File: src/panels/lovelace/common/evaluate-filter.ts (hunk 1 above)
Comment (Quentame) [reply src/panels/lovelace/common/evaluate-filter.ts]: @karwosts to get back to your (first) comment:

The automation's `NumericStateCondition` -> `above`/`below` are actually either a number or a string:

See how they are handled:
https://github.com/home-assistant/frontend/blob/dcb3accdb86f534277c16fd6d1c063f0a79c52dd/src/panels/config/automation/condition/types/ha-automation-condition-numeric_state.ts#L202-L208

You can try:
```yaml
condition: numeric_state
entity_id: sensor. gas_station_1
above: 1.1
below: sensor. gas_station_lowest_price
```

And `hass.states[entity_id]` is largely used in the codebase (256 results).

File: src/panels/lovelace/common/evaluate-filter.ts (hunk 5 above)
Comment (Quentame) [reply src/panels/lovelace/common/evaluate-filter.ts]: Nope unneeded, states returns an object, not a value

File: src/panels/lovelace/badges/hui-entity-filter-badge.ts [hunk 6]
```diff
@@ -80,27 +86,20 @@ export class HuiEntityFilterBadge
...
+        this._config!.conditions ??
+        entityConf.state_filter ??
+        this._config!.state_filter;
+
+      return (
+        conditions
+          .map((condition) =>
+            buildConditionForFilter(condition, entityConf.entity)
+          )
+          .filter((condition) => checkConditionsMet([condition], this.hass!))
```
Comment (Quentame) [inline src/panels/lovelace/badges/hui-entity-filter-badge.ts:100]: or remove `[]` and use `ensureArray` at return of `buildConditionForFilter`

File: src/data/automation.ts [hunk 7]
```diff
@@ -219,8 +219,8 @@ export interface NumericStateCondition extends BaseCondition {
   condition: "numeric_state";
   entity_id: string;
   attribute?: string;
-  above?: number;
-  below?: number;
+  above?: string | number;
+  below?: string | number;
```
Comment (Quentame) [inline src/data/automation.ts:223]: Not directly related but actually wrong type: automation numeric_state can be a string as can be an entity_id.

See:
https://github.com/home-assistant/frontend/blob/dcb3accdb86f534277c16fd6d1c063f0a79c52dd/src/panels/config/automation/condition/types/ha-automation-condition-numeric_state.ts#L202-L208

File: src/panels/lovelace/common/validate-condition.ts [hunk 8]
```diff
@@ -1,54 +1,156 @@
...
+  entity?: string | number;
+  attribute?: string;
+  value: string | number | string[];
+}
+
+interface BaseCondition {
+  condition: string;
+}
+
+export interface NumericStateCondition extends BaseCondition {
```
Comment (Quentame) [inline src/panels/lovelace/common/validate-condition.ts:45]: `interface` & `extends` as in automation

File: src/panels/lovelace/common/validate-condition.ts [hunk 9]
```diff
@@ -58,32 +160,56 @@ function checkStateCondition(
...
-  if (isNaN(numericState)) {
+  if (isNaN(numericState) || isNaN(numericValue)) {
     return false;
   }
 
   return (
-    (condition.above == null || condition.above < numericState) &&
-    (condition.below == null || condition.below > numericState)
+    (condition.above && numericValue < numericState) ||
+    (condition.below && numericValue > numericState)
```
Comment (Quentame) [inline src/panels/lovelace/common/validate-condition.ts:212]: Add back `null`/`undefined` check to allow `0`

File: src/panels/lovelace/common/evaluate-filter.ts (hunk 1 above)
Comment (Quentame) [reply src/panels/lovelace/common/evaluate-filter.ts]: Resolving this comment:
- uses the same codebase for `conditional` & `entity-filter` cards (`automation` can't be used as compute server side)
- properties `value`, `state`, `state_not`, `above`, `below` handle `entity_id` the same way.

File: src/panels/lovelace/common/validate-condition.ts (hunk 9 above)
Comment (piitaya) [reply src/panels/lovelace/common/validate-condition.ts:212]: If above and below are defined, we should check if the number is between. Why was this condition changed?

File: src/panels/lovelace/common/validate-condition.ts [hunk 10]
```diff
@@ -1,54 +1,156 @@
...
 
-export type StateCondition = {
+export interface StateCondition extends BaseCondition {
   condition: "state";
   entity?: string;
-  state?: string | string[];
-  state_not?: string | string[];
-};
+  state?: string | number | string[];
+  state_not?: string | number | string[];
```
Comment (piitaya) [inline src/panels/lovelace/common/validate-condition.ts:56]: State is always string, right?

File: src/panels/lovelace/common/validate-condition.ts [hunk 11]
```diff
@@ -109,8 +235,49 @@ function checkOrCondition(condition: OrCondition, hass: HomeAssistant) {
...
+  // Set the entity to filter on
+  if (
+    "condition" in newCondition &&
+    (newCondition.condition === "numeric_state" ||
+      newCondition.condition === "state")
+  ) {
+    newCondition.entity = entityId;
+  } else if ("operator" in newCondition) {
+    newCondition.entity = entityId;
+  }
```
Comment (piitaya) [inline src/panels/lovelace/common/validate-condition.ts:268]:
```suggestion
  if (
    "condition" in newCondition &&
    (newCondition.condition === "numeric_state" ||
      newCondition.condition === "state") ||
    "operator" in newCondition
  ) {
    newCondition.entity = entityId;
  }
```

Comment (piitaya) [reply src/panels/lovelace/common/validate-condition.ts:268]: We can merge the conditions

**Review by piitaya — COMMENTED** [review]
Thank you for the refactoring. I added some comment to improve and clarify some points.

File: src/panels/lovelace/entity-rows/types.ts [hunk 12]
```diff
@@ -14,7 +14,8 @@ export interface ActionRowConfig extends EntityConfig {
   action_name?: string;
 }
 export interface EntityFilterEntityConfig extends EntityConfig {
-  state_filter?: Array<{ key: string } | string>;
+  state_filter?: Array<Condition | LegacyFilterCondition | string | number>;
+  conditions?: Array<Condition | LegacyFilterCondition | string | number>;
```
[the remark this answers is not in the document]
Comment (Quentame) [reply src/panels/lovelace/entity-rows/types.ts:18]: We totally can 😄

In order to make conditional et entity-filter card configs uniform, I made options the same (conditional uses `conditions`), but we totally can let entity-filter with `state_filter` option.

What do you think, stay the same or make them uniform ?

I changed that on 97fffe2891c0cfc60829ffc4719728401ddf0256

File: src/panels/lovelace/common/validate-condition.ts [hunk 13]
```diff
@@ -58,32 +160,56 @@ function checkStateCondition(
...
+      }
+      return `${v}`;
+    });
+  } else if (
+    typeof value === "string" &&
+    isValidEntityId(value) &&
+    hass.states[value]
+  ) {
+    value = hass.states[value]?.state;
+  }
```
[the remark this answers is not in the document]
Comment (Quentame) [reply src/panels/lovelace/common/validate-condition.ts:179]: Should we check the beginning of the value as on automation ?

https://github.com/home-assistant/frontend/blob/dcb3accdb86f534277c16fd6d1c063f0a79c52dd/src/panels/config/automation/condition/types/ha-automation-condition-numeric_state.ts#L202-L208

[the remark this answers is not in the document]
Comment (piitaya) [reply src/panels/lovelace/common/validate-condition.ts:179]: This is for numeric state conditions. State conditions don't support entity_id in automation.

File: src/panels/lovelace/entity-rows/types.ts (hunk 12 above)
[the remark this answers is not in the document]
Comment (piitaya) [reply src/panels/lovelace/entity-rows/types.ts:18]: IMO, it's named "condition" because it renders the card according to "conditions" while here it filters the list of entities according to state. 
It's just a proposal, may be someone else will have another thought about it.

File: src/panels/lovelace/common/validate-condition.ts (hunk 10 above)
Comment (Quentame) [reply src/panels/lovelace/common/validate-condition.ts:56]: As entity-filter is not UI configurable, the user can put number in state.

But I can convert it in `buildConditionForFilter` if you want.

File: src/panels/lovelace/common/validate-condition.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (Quentame) [reply src/panels/lovelace/common/validate-condition.ts:179]: Indeed.

May I support `entity_id` only in numeric_state condition ?

That is actually the reason I made the PR in the first place 🤣 

If not, I could only keep it in the legacy operator/value condition.

File: src/panels/lovelace/common/validate-condition.ts (hunk 9 above)
Comment (Quentame) [reply src/panels/lovelace/common/validate-condition.ts]: fixed in f2f9ddce337cdb0d796b7ea0fdb0d37d21a9a476)

File: src/panels/lovelace/common/validate-condition.ts (hunk 10 above)
Comment (Quentame) [reply src/panels/lovelace/common/validate-condition.ts]: fixed in e20bf741a4890f1b5c82794ede8ad1a235372345

File: src/panels/lovelace/editor/conditions/types/ha-card-condition-state.ts [hunk 14]
```diff
@@ -21,7 +21,7 @@ type StateConditionData = {
   condition: "state";
   entity?: string;
   invert: "true" | "false";
-  state?: string | string[];
+  state?: string | number | string[];
```
[the remark this answers is not in the document]
Comment (Quentame) [reply src/panels/lovelace/editor/conditions/types/ha-card-condition-state.ts]: fixed in e20bf741a4890f1b5c82794ede8ad1a235372345

File: src/panels/lovelace/common/validate-condition.ts (hunk 11 above)
Comment (Quentame) [reply src/panels/lovelace/common/validate-condition.ts]: Suggestion applied on 69310d2d4593455b9e5771c9c7c336095ed78a9d

**Comment by Quentame** [comment]
Doc updated

**Comment by Quentame** [comment]
Hi !
Any news on this PR ?

**Review by piitaya — APPROVED** [review]

File: src/panels/lovelace/common/validate-condition.ts [hunk 15]
```diff
@@ -134,6 +180,43 @@ export function checkConditionsMet(
...
+      if (
+        typeof condition.below === "string" &&
+        isValidEntityId(condition.below)
+      ) {
+        entityIds.add(condition.below);
+      }
+    } else if (condition.condition === "state") {
+      [
+        ...(ensureArray(condition.state) ?? []),
+        ...(ensureArray(condition.state_not) ?? []),
```
Comment (Quentame) [inline src/panels/lovelace/common/validate-condition.ts:204]: `ensureArray` actually ensure that it returns an array (undefined tested) --> `??` shouldn't be needed here

https://github.com/hacf-fr/home-assistant-frontend/blob/ac5d576c5b3b052e7d5c726f687e027cd0f9fad9/src/common/array/ensure-array.ts#L6-L11

Comment (piitaya) [reply src/panels/lovelace/common/validate-condition.ts:204]: It returns `undefined` is the value is `undefined`

Comment (Quentame) [reply src/panels/lovelace/common/validate-condition.ts:204]: Oh yeah 🤦 
My bad
