### PR TITLE
Fix last input margins in supervisor-network.ts

### LINKED ISSUE #19658: Last child overlaps ha-expansion-panel in Network area
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

image

### Describe the behavior you expected

image

### Steps to reproduce the issue

Expand any panel on /config/network

### What version of Home Assistant Core has the issue?

core-2024.2.0b3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by codyc1515**
## Proposed change
Fix last input margins in supervisor-network.ts

## Type of change
- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #19658
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/network/supervisor-network.ts [hunk 1]
```diff
@@ -574,6 +574,9 @@ export class HassioNetwork extends LitElement {
           display: block;
           margin-top: 16px;
         }
+        ha-expansion-panel ha-textfield:last-child {
+          margin-bottom: 8px;
```
Comment (bramkragten) [inline src/panels/config/network/supervisor-network.ts:578]:
```suggestion
          margin-bottom: 16px;
```

**Review by bramkragten — APPROVED** [review]
