### PR TITLE
Fix duplicate trigger IDs showing in the Triggered By condition

### LINKED ISSUE #13260: Duplicate Trigger Ids in Trigger Condition
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Experiencing the same issue as described in #10793. If multiple triggers define the same value the value is repeated in the trigger condition drop down menu.

### Describe the behavior you expected

I expected the list to be consolidated to unique values only.

### Steps to reproduce the issue

1. Create automation with multiple triggers with the same trigger id
2. Add a 'Triggered by' condition
3. Open drop down menu

### What version of Home Assistant Core has the issue?

2022.7.6

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Brave Version 1.41.96 Chromium: 103.0.5060.114 (Official Build) (64-bit)

### Which operating system are you using to run this browser?

Linux Mint 20.3 Cinnamon

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### LINKED ISSUE #13359: Trigger ID's with the same ID popups als multiply choices
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When you have multiply trigger id's with the ID "on", you see al those "on" choices in the conditions.
triggerid

### Describe the behavior you expected

When multipy id's, one "triggered by" choice.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

Home Assistant 2022.8.2

### What was the last working version of Home Assistant Core?

2022.7.x

### In which browser are you experiencing the issue with?

Chrome, Firefox, etc

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### LINKED ISSUE #14111: Non-unique trigger IDs displayed multiple times in the "Triggered by" dropdown
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When multiple triggers in an automation use the same trigger ID (that's a supported feature), the UI of the "Triggered by" condition shows that ID multiple times:

image

That's confusing.

### Describe the behavior you expected

It should just show unique trigger IDs.

### Steps to reproduce the issue

1. Create automation with multiple triggers with the same ID. Such as this one: 
image

2. Add a trigger condition 
image

### What version of Home Assistant Core has the issue?

2022.10.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bdr99**
## Proposed change

Fixes an issue where, if the same trigger ID was defined in multiple triggers, the trigger ID would be duplicated in the selector of the Triggered By condition.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: 
fixes #13260
fixes #13359
fixes #14111
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/automation/condition/types/ha-automation-condition-trigger.ts [hunk 1]
```diff
@@ -70,8 +70,11 @@ export class HaTriggerCondition extends LitElement {
   }
 
   private _automationUpdated(config?: AutomationConfig) {
+    const seenIds = new Set();
     this._triggers = config?.trigger
-      ? ensureArray(config.trigger).filter((t) => t.id)
+      ? ensureArray(config.trigger)
+          .filter((t) => t.id)
+          .filter((t) => (seenIds.has(t.id) ? false : seenIds.add(t.id)))
```
Comment (bramkragten) [inline src/panels/config/automation/condition/types/ha-automation-condition-trigger.ts:77]: Combine this in the same filter so we don't go over the array twice

Comment (bdr99) [reply src/panels/config/automation/condition/types/ha-automation-condition-trigger.ts]: Fixed.

**Review by bramkragten — APPROVED** [review]
