### PR TITLE
Ensure YAML editor gets updated during action change / deletion

### LINKED ISSUE #7932: UI Automation Editor Deletes Wrong Action
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

When editing an automation in the UI, if you click the three dots next to an 'action' & select delete then the wrong action is deleted. I have definitely had this issue normally but have today only been able to reproduce when actions are in "Edit as YAML" mode.

I have noticed though that the YAML issue seems to be that the UI gets 'confused' (for want of a better word) as if you then change back to UI mode for the actions (can be seen in the GIF below) it's not the same action that the YAML was showing.

image

## Expected behavior

The correct action is deleted & the correct YAML for that action is shown.

## Steps to reproduce

See my GIF - Add multiple actions to an automation in the UI, edit those actions as YAML, try to delete one.

## Environment

- Home Assistant release with the issue: 0.118.4
- Last working Home Assistant release (if known):
- Browser and browser version: Multiple
- Operating system: I run my installation on a Docker image on my Ubuntu 16.04 server.

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

I've hopefully explained well enough and if not, fingers crossed the GIF explains it better!

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

When an action row is in YAML editor mode, it previously did not react to action changes, e.g. when one row was deleted, the editor now needed to display another YAML content. With this PR, the YAML editor gets made aware of the new content to be be shown.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/7932
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/automation/action/ha-automation-action-row.ts [hunk 1]
```diff
@@ -103,6 +105,8 @@ export default class HaAutomationActionRow extends LitElement {
 
   @internalProperty() private _yamlMode = false;
 
+  @query("ha-yaml-editor", true) private _yamlEditor?: HaYamlEditor;
```
Comment (bramkragten) [inline src/panels/config/automation/action/ha-automation-action-row.ts:108]:
```suggestion
  @query("ha-yaml-editor") private _yamlEditor?: HaYamlEditor;
```

I don't think we should change this?

**Review by bramkragten — APPROVED** [review]

File: src/panels/config/automation/action/ha-automation-action-row.ts (hunk 1 above)
Comment (spacegaier) [reply src/panels/config/automation/action/ha-automation-action-row.ts:108]: I took that over from `ha-automation-action-events.ts` and `ha-automation-action-services.ts`. There they are cached as well.

Comment (bramkragten) [reply src/panels/config/automation/action/ha-automation-action-row.ts:108]: Then they should be updated too since we rerender/remove them, it should not be cached.

Comment (bramkragten) [reply src/panels/config/automation/action/ha-automation-action-row.ts:108]: Just checked, `ha-automation-action-event` and `action-service` never remove the YAML editor so, that is good to cache.

Comment (spacegaier) [reply src/panels/config/automation/action/ha-automation-action-row.ts]: Caching now removed for all three.

Comment (spacegaier) [reply src/panels/config/automation/action/ha-automation-action-row.ts]: Dang, did not see your update. Will add the caching back in...

Comment (bramkragten) [inline src/panels/config/automation/action/ha-automation-action-row.ts:108]:
```suggestion
  @query("ha-yaml-editor") private _yamlEditor?: HaYamlEditor;
```
