### PR TITLE
Media Card: Reset Marquee on Text change

### LINKED ISSUE #5151: Media Player Card: Unnecessary Marquee when skipping tracks
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I don't know if this is necessarily a bug, but when you hover over a very long song title and the marquee kicks in, and then you press the skip track button, the next song will always be scrolling initially even if that isn't necessary.

Long title, scrolling marquee:
image

Skipped track, this is a short song title (3 words) but you can see it was still scrolling at first:
image

This makes it a tiny bit harder to read the song title when skipping tracks if it's scrolling unnecessarily. Not a huge deal, only lasts for like 2 or 3 seconds maybe, but just thought I'd mention it. 

## Steps to reproduce

Can test it by playing this Weird Al album and skipping tracks, since it has some very long song titles followed by short song titles.

https://open.spotify.com/album/7xioktcLt004PnB9nqwBWz?si=83pde1eMQZSDS1N96ccfcA

## Environment

- Home Assistant release with the issue: 0.107.0b0
- Last working Home Assistant release (if known): n/a
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by zsarnett**
## Proposed change

https://gyazo.com/cca4b26d1d46f814a980fb57a5a4caf7

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #5151
- This PR is related to issue: 
- Link to documentation pull request:

### CODE REVIEW

File: src/panels/lovelace/components/hui-marquee.ts [hunk 1]
```diff
@@ -30,11 +30,20 @@ class HuiMarquee extends LitElement {
   protected updated(changedProperties: PropertyValues): void {
     super.updated(changedProperties);
 
+    if (changedProperties.has("text") && this._animating) {
+      this._animating = false;
+      this.setAttribute("stopped", "stopped");
```
Comment (zsarnett) [inline src/panels/lovelace/components/hui-marquee.ts]: I am not sure if I should just make this a property and reflect it. I went with this as I didn't think it was necessary.

Comment (bramkragten) [reply src/panels/lovelace/components/hui-marquee.ts]: Wouldn't it be enough to set `this._animating = false`? Or will it just pause then? I did it like this to prevent repaints but that can be solved in different ways since this will do that too.

Comment (bramkragten) [reply src/panels/lovelace/components/hui-marquee.ts]: Move the `animation: marquee 10s linear infinite;` to the `:host([animating]) .marquee-inner` rule

Comment (zsarnett) [reply src/panels/lovelace/components/hui-marquee.ts]: Yea just `this._animating = false` just pauses at the current position. Thats why I added the `none` but your suggestions worked

**Comment by bramkragten** [comment]
I think we need to add `transform: translateX(0);` to the `.marquee-inner` now to prevent a layout change (repaints of every element below the media card) when it starts animating.
