### PR TITLE
Fix fragment translation race condition returning stale localize

### LINKED ISSUE #51313: View tab titles not loaded in "Energy"
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The top names for the sections in "Energy" some times show the wrong names, a refresh solves it on mobile and in a browser

### Describe the behavior you expected

That the correct names are displayed

### Steps to reproduce the issue

Normal use, the text is not wrong every time.

### What version of Home Assistant Core has the issue?

2026.4.0b7

### What was the last working version of Home Assistant Core?

2026.3

### In which browser are you experiencing the issue?

Firefox

### Which operating system are you using to run this browser?

Ubuntu

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

Image

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

I finally found the real cause of #51313.

`_loadFragmentTranslations` uses a `Set` to track which fragments have been requested. Once a fragment name is added to the set, any subsequent caller immediately gets `this.hass!.localize` back — even if the original fetch is still in-flight. That returned `localize` is a closure over the **old** resources that don't include the fragment's translations yet.

Here's the race:

1. `translations-mixin.updated()` auto-triggers `_loadFragmentTranslations("energy")` when `panelUrl` changes to `"energy"` — adds `"energy"` to the set and starts the async fetch
2. The energy panel's `_setup()` calls `loadFragmentTranslation("energy")` — sees `"energy"` already in the set, immediately returns the current `this.hass!.localize` (stale, missing energy keys)
3. The energy dashboard strategy generates view titles with this stale `localize` → gets empty strings → tabs show "Unnamed view"

The fix changes `__loadedFragmentTranslations` from a `Set<string>` to a `Map<string, Promise<LocalizeFunc>>`. Instead of returning the stale localize for in-progress loads, concurrent callers now await the same promise and receive the fresh `localize` function once the fetch completes.

This also reverts the workaround from #51376 in the energy dashboard strategy since it's no longer needed.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #51313
- This PR is related to issue or discussion: #51327, #51376
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure
[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/state/translations-mixin.ts [hunk 1]
```diff
@@ -381,11 +384,13 @@ export default <T extends Constructor<HassBaseEl>>(superClass: T) =>
       }
 
       if (this.__loadedFragmentTranslations.has(fragment)) {
-        return this.hass!.localize;
+        return this.__loadedFragmentTranslations.get(fragment)!;
```
Comment (bramkragten) [inline src/state/translations-mixin.ts:387]: This will fix it for the fragment you request, but could cause you to have stale translations for other translations, as they are loaded after this fragment was loaded. Shouldn't we remove the promise from the map once it is resolved and only use the map for inflight loads? When it is not in the inflight map, check if it is in the `__loadedFragmentTranslations` Set, if thats the case return current `this.hass!.localize`.

**Review by bramkragten — APPROVED** [review]

**Comment by bramkragten** [comment]
Going to merge anyway, as the result of a load is mostly only used for getting the translations of that fragment.
