### PR TITLE
Fix entity card state display

### LINKED ISSUE #5630: Entity card shows duplicate unit of measurement
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Using Entity card for first time after Zack's [forum post](https://community.home-assistant.io/t/my-mobile-dashboard-pure-core-lovelace/189671) gave me some ideas/inspiration. It seems that on 0.109 whenever an entity has a unit of measurement the entity card will display that twice (see the "Percentage" card in top right of this pic):

image

## Expected behavior

The example on the [Entity Card docs](https://www.home-assistant.io/lovelace/entity/) shows how it's expected to look:

image

## Environment

- Home Assistant release with the issue: 0.109.0b0
- Last working Home Assistant release (if known): ??
- Browser and browser version: Chrome
- Operating system: macOS

## Problem-relevant configuration

```yaml
    - type: horizontal-stack
      cards:
        - entity: sensor.time_driving_today
          name: Drove Today
          type: entity

        - entity: sensor.percentage_driven_today
          name: Percentage
          type: entity

    - type: horizontal-stack
      cards:

        - entity: counter.car_trips
          type: entity
          name: Trips This Week

        - entity: counter.car_hard_brake_events
          type: entity
          name: Hard Brakes

    - type: horizontal-stack
      cards:
        - entity: counter.car_hard_accel_events
          type: entity
          name: Rapid Accels

        - entity: counter.car_speeding_events
          type: entity
          name: Speeding
```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes https://github.com/home-assistant/frontend/issues/5630

### CODE REVIEW

**Review by balloob — APPROVED** [review]

File: src/panels/lovelace/cards/hui-entity-card.ts [hunk 1]
```diff
@@ -129,11 +129,11 @@ export class HuiEntityCard extends LitElement implements LovelaceCard {
...
-                : computeStateDisplay(
-                    this.hass.localize,
-                    stateObj,
-                    this.hass.language
-                  )}</span
+                : this.hass.localize(
+                    `component.${computeDomain(this._config.entity)}.state.${
+                      stateObj.attributes.device_class || "_"
+                    }.${stateObj.state}`
+                  ) || stateObj.state}</span
```
Comment (balloob) [inline src/panels/lovelace/cards/hui-entity-card.ts:136]: Actually think that this is better

```suggestion
                : stateObj.attributes.unit_of_measurement
                ? stateObj.state
                : computeStateDisplay(
                    this.hass.localize,
                    stateObj,
                    this.hass.language
                  )}</span
```

Comment (zsarnett) [reply src/panels/lovelace/cards/hui-entity-card.ts:136]: I just setup a new PC so I am still working on getting my DEV Env back up. But if we use StateDisplay then we can't style the measurement. So this is not better

Comment (bramkragten) [reply src/panels/lovelace/cards/hui-entity-card.ts:136]: We only use statedisplay when there is no unit of measurement, so that would not interfere right?
