### PR TITLE
Webpage Card: Fix Aspect Ratio in Editor

### LINKED ISSUE #5194: Webpage card - changing aspect ratio breaks card editor
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

In the Webpage card, deleting the default aspect ratio (so you can change it) will result in the card breaking. 

You get switched to the code editor with an error message `Expected a value of type `string | undefined` for `aspect_ratio` but received `0`.`

image

image

Similar bug to https://github.com/home-assistant/frontend/issues/4540 which was fixed in the Markdown card a few weeks ago.

## Steps to reproduce

1. Enter Configure UI mode, select Webpage card
2. Delete the default '50' aspect ratio
3. Card now switches to code editor with an error message

## Environment

- Home Assistant release with the issue: 0.107.0b1
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by zsarnett**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #5194
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/editor/config-elements/hui-iframe-card-editor.ts [hunk 1]
```diff
@@ -81,8 +81,7 @@ export class HuiIframeCardEditor extends LitElement
             )} (${this.hass.localize(
               "ui.panel.lovelace.editor.card.config.optional"
             )})"
-            type="number"
-            .value="${Number(this._aspect_ratio.replace("%", ""))}"
+            .value="${this._aspect_ratio.replace("%", "")}"
```
Comment (bramkragten) [inline src/panels/lovelace/editor/config-elements/hui-iframe-card-editor.ts]: We should add a suffix to this input with `%`.

File: src/panels/lovelace/editor/config-elements/hui-iframe-card-editor.ts [hunk 2]
```diff
@@ -81,8 +81,7 @@ export class HuiIframeCardEditor extends LitElement
...
             .configValue="${"aspect_ratio"}"
             @value-changed="${this._valueChanged}"
           ></paper-input>
```
Comment (bramkragten) [inline src/panels/lovelace/editor/config-elements/hui-iframe-card-editor.ts]:
```suggestion
          ><div suffix>%</div></paper-input>
```

Comment (bramkragten) [reply src/panels/lovelace/editor/config-elements/hui-iframe-card-editor.ts]: Or `<div slot="suffix">%</div>`

**Review by bramkragten — APPROVED** [review]
