### PR TITLE
Fix iframe flash for dark theme using transition

### LINKED ISSUE #14754: Dashboard in Dark mode loads white page for a moment when opening integrations from Sidebar
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When Home Assistant dark mode in effect and I open HACS integration (the only one integration I have in that menu) from Sidebar, it first loads a blank white page for a moment (or even more if it wasn't recently accessed). That's not very pleasant for eyes when it's dark everywhere :)

image

### Describe the behavior you expected

Black page should appear while an integration is loading.

### Steps to reproduce the issue

1. Open Home Assistant in Dark mode in a dark room (in your browser or in Android app) with HACS integration installed (haven't checked with others as I don't know any).
2. Open HACS tab.
3. Close your eyes for a moment because of the bright light.

### What version of Home Assistant Core has the issue?

Home Assistant 2022.12.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome 108; Home Assistant Android App

### Which operating system are you using to run this browser?

MacOS Ventura 13.0.1; Android 13

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

The issue was initially opened in HACS repo, but looks like HACS cannot control this behaviour: https://github.com/hacs/integration/issues/2957

### PR DESCRIPTION
**Pull request by timmo001**
## Proposed change

Uses transition to stop flash while in dark theme

- #14754

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #14754
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/panels/app/ha-panel-app.ts [hunk 1]
```diff
@@ -431,6 +438,13 @@ class HaPanelApp extends LitElement {
       width: 100%;
       height: 100%;
       border: 0;
+      background-color: var(--primary-background-color);
+      opacity: 0;
+      transition: opacity var(--ha-animation-base-duration) ease;
```
Comment (MindFreeze) [inline src/panels/app/ha-panel-app.ts]:
```suggestion
      transition: opacity var(--ha-animation-duration-normal) ease;
```

File: src/panels/custom/ha-panel-custom.ts [hunk 2]
```diff
@@ -153,6 +156,11 @@ export class HaPanelCustom extends ReactiveElement {
           height: 100dvh;
           display: block;
           background-color: var(--primary-background-color);
+          opacity: 0;
+          transition: opacity var(--ha-animation-base-duration) ease;
```
Comment (MindFreeze) [inline src/panels/custom/ha-panel-custom.ts]:
```suggestion
          transition: opacity var(--ha-animation-duration-normal) ease;
```

**Review by MindFreeze — APPROVED** [review]
