### PR TITLE
Reflect media browser panel state in URL

### LINKED ISSUE #10950: Back buttons are inconsistent in the media browser compared with the rest of the UI
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Most of the Home Assistant UI returns to the previous page when the back button is pressed (including dialogs in many cases), however when navigating through the media browser, the back button returns to the previous non-media browser page.

### Describe the behavior you expected

The expected behavior would be that the back button returns up a level in the media browser (if you've navigated to a child item), rather than to the previous non-media browser page.

### Steps to reproduce the issue

1. Go to any page.
2. Go to the media browser and navigate to a directory.
3. Click the back button. You will now be back at the original page.

### What version of Home Assistant Core has the issue?

core-2021.12.2

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Firefox 95 and the HA Android App 2021.10.0-full

### Which operating system are you using to run this browser?

Windows 10 and Android 12

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change

Update state management of the media browser and reflect the state in the URL so we can refresh the page and stay on same folder.

Fixes #10950

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/layouts/home-assistant.ts [hunk 1]
```diff
@@ -21,13 +21,11 @@ import "./home-assistant-main";
 
 const useHash = __DEMO__;
 const curPath = () =>
-  window.decodeURIComponent(
```
Comment (balloob) [inline src/layouts/home-assistant.ts:24]: I added this when we migrated from app-route but I was unable to find this logic in the original package.

**Comment by balloob** [comment]
Squashed + rebased to resolve merge conflicts.

File: src/panels/media-browser/ha-panel-media-browser.ts [hunk 2]
```diff
@@ -111,6 +138,22 @@ class PanelMediaBrowser extends LitElement {
...
+    }
+    let path = "";
+    for (const item of ev.detail.ids.slice(1)) {
+      path +=
+        "/" +
+        encodeURIComponent(
+          `${item.media_content_type},${item.media_content_id}`
+        );
+    }
+    navigate(`/media-browser/${this._entityId}${path}`);
```
Comment (zsarnett) [inline src/panels/media-browser/ha-panel-media-browser.ts:154]: Google Chrome allows the maximum length of the URL to be of the size 2MB(2048 characters)

We may have to worry about this eventually... I was getting an average of about 80 characters per navigation down into a folder. Meaning 25 times I would be able to drill down. That is a lot of diving but still may be something to think about

**Review by zsarnett — APPROVED** [review]
