### PR TITLE
Fix flow form padding end

### LINKED ISSUE #20721: Settings -> Integrations: overflow in "Add entry" popup
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

For some integrations it is not possible to add more than 1 entry, so a popup is shown.
In this popup a title may be shown not in a nice way:

image

### Describe the behavior you expected

Suggest to show an integration name in a separate area with a possibility to wrap long strings.

### Steps to reproduce the issue

as above

### What version of Home Assistant Core has the issue?

2024.5

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chrome 124.0.6367.92

### Which operating system are you using to run this browser?

Win10x64

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### LINKED ISSUE #25325: Config Flow dialog header icon overlaps with text
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Starting the config flow for 1-Wire (the top option in Add integration), shows the help icon overlapping with the text.

Image

### Describe the behavior you expected

Icon should be next to the text.

### Steps to reproduce the issue

1. Go to the integration tab
2. Click "Add integration"
3. Select 1-Wire
...

### What version of Home Assistant Core has the issue?

core-2025.5.0b4

### What was the last working version of Home Assistant Core?

core-2025.4.0

### In which browser are you experiencing the issue?

Arc

### Which operating system are you using to run this browser?

Mac

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change
- fix #20721
- fix #25325

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/config-flow/styles.ts [hunk 1]
```diff
@@ -22,6 +22,9 @@ export const configFlowContentStyles = css`
     text-transform: var(--mdc-typography-headline6-text-transform, inherit);
     box-sizing: border-box;
   }
+  h2.end-space {
+    padding-inline-end: 72px;
+  }
```
Comment (piitaya) [inline src/dialogs/config-flow/styles.ts:27]: Can we use css variable to set this instead of a new property?
```
h2 {
   padding-inline-end: var(--title-padding-inline-end, 0);
}
```

And `--title-padding-inline-end` can be set in `dialog-data-entry-flow.ts`. What do you think?

Comment (wendevlin) [reply src/dialogs/config-flow/styles.ts:27]: Yes sure thats also an option.
I am not sure if it's worth the effort to change it again :slightly_smiling_face: 

In my opinion we should refactor the whole dialog-data-entry-flow. Each step does have a header, why not use `ha-dialog-header` for example, that would solve that problem and would set the close botton on the left where it should be. 

But I don't want to do such a change now as a beta patch

Comment (piitaya) [reply src/dialogs/config-flow/styles.ts:27]: I agree, let's merge it to fix the issue during beta and improve the flows later

**Review by piitaya — APPROVED** [review]
