### PR TITLE
Use --ha-box-shadow-l for footer

### LINKED ISSUE #30014: Footer in sections dashboard sets --ha-card-box-shadow variable overriding theme variable
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Hi, the new sticky footer built into the sections dashboards is great, but I’ve run into an issue which I noticed when I tried applying a theme to a specific dashboard in order to remove box-shadows.

It seems one of the wrapper elements inside the footer section redeclares the variable --ha-card-box-shadow, which overrides the box-shadow set in themes and applies its own box-shadow to elements in the footer.

Image

Image

### Describe the behavior you expected

The footer should allow the user to set their own box-shadow according to the user/dashboard theme.

### Steps to reproduce the issue

1. Apply a theme which removes box-shadows.
2. Add a card which generally uses box-shadows inside a regular section and again inside the footer section.
3. Check if the card within the footer has a box-shadow visible and the card inside a regular section doesn’t.

### What version of Home Assistant Core has the issue?

core-2026.3.0

### What was the last working version of Home Assistant Core?

N/A - Footer section was just added this release.

### In which browser are you experiencing the issue?

Google Chrome 145.0.7632.117 / Safari 26.2 (21623.1.14.11.9)

### Which operating system are you using to run this browser?

macOS Tahoe (26.2)

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

The shadow is now much fainter but this is the largest one we have defined.
Also removed `--ha-card-border-color` because it is redundant.

## Screenshots

Before:
image

After:
image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #30014
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [x] I understand the code I am submitting and can explain how it works.
- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] I have followed the [perfect PR recommendations][perfect-pr]
- [x] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [x] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/panels/lovelace/views/hui-view-footer.ts [hunk 1]
```diff
@@ -236,11 +236,7 @@ export class HuiViewFooter extends LitElement {
     }
 
     .wrapper:not(.edit-mode) {
-      --ha-card-box-shadow:
-        0px 3px 5px -1px rgba(0, 0, 0, 0.2),
-        0px 6px 10px 0px rgba(0, 0, 0, 0.14),
-        0px 1px 18px 0px rgba(0, 0, 0, 0.12);
-      --ha-card-border-color: var(--divider-color);
+      --ha-card-box-shadow: var(--ha-box-shadow-l);
```
Comment (wendevlin) [inline src/panels/lovelace/views/hui-view-footer.ts:239]:
```suggestion
      --ha-card-box-shadow: var(--hui-view-footer-box-shadow, var(--ha-box-shadow-l));
```

should we also add a component specific option?

Comment (MindFreeze) [reply src/panels/lovelace/views/hui-view-footer.ts:239]: I don't think it's needed. We should be dealing with abstract levels like `z-index` not specific components

**Review by wendevlin — APPROVED** [review]
