### PR TITLE
Convert suggest-card dialog to `ha-dialog`

### LINKED ISSUE #9452: Too many preview cards during adding pushes UI off screen, inaccessible
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

While editing the lovelace UI, I am filling a view with cameras. After checking a bunch of cameras for entities I want to add, it then gives me a preview of all the cards. However the number of cards pushed the bottom of the modal off the bottom of the screen and is inaccessible. 

I suspect this would probably happen with other types and not just camera but I don't know what preview cards are large enough to push off screen.

To continue: Clicking out of the modal will close it but I would be unable to ever get the 'card preview'. A refresh of the page will fix it (separate issue, will post - )

### Describe the behavior you expected

Still able to access the "continue" or "cancel" button on the bottom

### Steps to reproduce the issue

1. Edit UI / Add Card
2. By Entity
3. Add many things at once (in my case, 4+ cameras

### What version of Home Assistant Core has the issue?

core 2021.6.5

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chrome 91 / FF 89.0.1

### Which operating system are you using to run this browser?

Windows 21H1

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### LINKED ISSUE #9453: Clicking out of modal during card suggestion makes it unusable
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Clicking the background while in the 'We created a suggestion for you' closes the modal, but will never be able to open again.

1. edit UI
2. add card
3. by entity
4. select any entity press continue
5. get the 'We created a suggestion for you' screen
6. click in the background which closes it.
7. add card
8. by entity
9. select any entity press continue
10. modal closes immediately 

the only way to reset is to F5 / refresh the page. Going to other screens (configuration, etc) won't reset it.

### Describe the behavior you expected

prevent me from leaving the modal or able to get back to making new cards

### Steps to reproduce the issue

1. edit UI
2. add card
3. by entity
4. select any entity press continue
5. get the 'We created a suggestion for you' screen
6. click in the background which closes it.
7. add card
8. by entity
9. select any entity press continue
10. modal closes immediately 

### What version of Home Assistant Core has the issue?

core 2021.6.5

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Chrome 91 / FF 89.0.1

### Which operating system are you using to run this browser?

Windows 21H1

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Move to `ha-dialog` to prevent the resizing & positioning issues.

Also clear the selected entities upon dialog closure to prevent weird behavior after entity based card suggestion flow was cancelled (wrong buttons state + no more change to select entities).

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9452 fixes #9453
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/editor/card-editor/hui-dialog-suggest-card.ts [hunk 1]
```diff
@@ -157,6 +164,7 @@ export class HuiDialogSuggestCard extends LitElement {
   private _close(): void {
```
Comment (bramkragten) [inline src/panels/lovelace/editor/card-editor/hui-dialog-suggest-card.ts:164]:
```suggestion
  public close(): void {
```

File: src/panels/lovelace/editor/card-editor/hui-dialog-suggest-card.ts [hunk 2]
```diff
@@ -80,37 +91,39 @@ export class HuiDialogSuggestCard extends LitElement {
...
+        ${!this._params.yaml
+          ? html`
+              <mwc-button slot="primaryAction" @click="${this._pickCard}"
+                >${this.hass!.localize(
+                  "ui.panel.lovelace.editor.suggest_card.create_own"
+                )}</mwc-button
+              >
+              <mwc-button
+                slot="primaryAction"
+                ?disabled="${this._saving}"
```
Comment (bramkragten) [inline src/panels/lovelace/editor/card-editor/hui-dialog-suggest-card.ts:109]:
```suggestion
                .disabled="${this._saving}"
```

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
