### PR TITLE
Edit sidebar in a dialog

### LINKED ISSUE #25418: Side bar menu items no longer deletable when clicking on X
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

The side bar menu no longer deletes a menu item when clicking on the X

### Describe the behavior you expected

Clicking X on a side bar menu item should remove the item

### Steps to reproduce the issue

1.open side menu in edit mode 

2.click on X next to menu item
3.
...

### What version of Home Assistant Core has the issue?

2025.5.1

### What was the last working version of Home Assistant Core?

Unknown

### In which browser are you experiencing the issue?

Companion app, edge and chrome

### Which operating system are you using to run this browser?

W11, android

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change
- fix #25418
- In follow up PRs I would to change
  - Save sidebar settings by user
  - Add keyboard only order option

image

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/sidebar/dialog-edit-sidebar.ts [hunk 1]
```diff
@@ -0,0 +1,159 @@
...
+
+  @state() private _hidden: string[] = [];
+
+  private _saveCallback?: (order: string[], hidden: string[]) => void;
+
+  public async showDialog(params: EditSidebarDialogParams): Promise<void> {
+    this._open = true;
+
+    const storedOrder = localStorage.getItem("sidebarPanelOrder");
+    const storedHidden = localStorage.getItem("sidebarHiddenPanels");
```
Comment (bramkragten) [inline src/dialogs/sidebar/dialog-edit-sidebar.ts:35]: Why dont we use the `storage` decorator for this?

Comment (bramkragten) [reply src/dialogs/sidebar/dialog-edit-sidebar.ts:35]: Or pass the value when opening the dialog (I guess we then have to fetch them on the profile page...)

Comment (wendevlin) [reply src/dialogs/sidebar/dialog-edit-sidebar.ts:35]: Yes that was the reason that I don't have to get it in the profile page. I can add the `storage` decorator.

File: src/components/ha-items-display-editor.ts [hunk 2]
```diff
@@ -50,6 +51,9 @@ export class HaItemDisplayEditor extends LitElement {
   @property({ type: Boolean, attribute: "show-navigation-button" })
   public showNavigationButton = false;
 
+  @property({ type: Boolean, attribute: "disable-visible-sort" })
```
Comment (bramkragten) [inline src/components/ha-items-display-editor.ts:54]: It doesnt disable the sorting (as in, the user can still sort them) but we dont sort them...

Would `dont-sort-visible` be a better name?

File: src/dialogs/sidebar/dialog-edit-sidebar.ts (hunk 1 above)
Comment (bramkragten) [reply src/dialogs/sidebar/dialog-edit-sidebar.ts:35]: It is ok like this, leave it. We don't need the decorator as we only fetch it anyway.

**Comment by karwosts** [comment]
The visibility toggles are not keyboard focusable?

**Comment by wendevlin** [comment]
> The visibility toggles are not keyboard focusable?

You are right. I would like to work on a11y on a separate PR. But I did this dialog because of your sort button PR and I want to solve it with this.

**Comment by karwosts** [comment]
Thanks for coming back to that, appreciate it. 👍  I only noticed because I knew that all these style of dialogs had similar issues.

Just wanted to point it out to warn that this might be making the accessibility worse... do hope you're able to come back to it before too long 😰

**Comment by wendevlin** [comment]
> Thanks for coming back to that, appreciate it. 👍 I only noticed because I knew that all these style of dialogs had similar issues.
> 
> Just wanted to point it out to warn that this might be making the accessibility worse... do hope you're able to come back to it before too long 😰

My plan is release `2025.6` :+1: so I need to mainly finish it this week :slightly_smiling_face:

**Review by bramkragten — APPROVED** [review]
