### PR TITLE
Ensure helper type is always localized

### LINKED ISSUE #18822: Helpers listing missing type
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Since 2012.12.0b0 the helpers page misses the types of the entities.

image

### Describe the behavior you expected

Type to be shown.

### Steps to reproduce the issue

Open helpers page https://my.home-assistant.io/redirect/helpers/

### What version of Home Assistant Core has the issue?

2023.12.0b0

### What was the last working version of Home Assistant Core?

2023.11

### In which browser are you experiencing the issue with?

Chrome 119

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by silamon**
## Proposed change
Regression reported in #18822.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #18822
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/config/helpers/ha-config-helpers.ts [hunk 1]
```diff
@@ -226,20 +226,19 @@ export class HaConfigHelpers extends SubscribeMixin(LitElement) {
...
-        entity_id: "",
-        icon: mdiAlertCircle,
-        name: configEntry.title || "",
-        editable: true,
-        type: configEntry.domain,
-        configEntry,
-        entity: undefined,
-      }));
+      const entries =
+        Object.keys(configEntriesCopy).length !== 0
```
Comment (piitaya) [inline src/panels/config/helpers/ha-config-helpers.ts:230]: No need to check for the length because `Object.values({})` will return `[]`, right?

Comment (silamon) [reply src/panels/config/helpers/ha-config-helpers.ts]: Yeah, just checked and adjusted the code.

**Review by piitaya — APPROVED** [review]

**Comment by piitaya** [comment]
Thanks @silamon !
