### PR TITLE
Energy Dashboard: Align total cost with 'previous cost' column.

### LINKED ISSUE #12882: Energy dashboard compare: cost column misallignment
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

At the bottom of the `sources` section of the energy dashboard, when comparing in this example 2 weeks, the total cost of the previous week ends up in the wrong column. See screenshot:
image

### Describe the behavior you expected

That the previous cost total would line up with the previous cost column.

### Steps to reproduce the issue

1. Enable compare in energy dashboard
2. Verify problem
3.
...

### What version of Home Assistant Core has the issue?

2022.6.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome 102.0.5005.62

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

Also reproducible on HA companion app on android. (Latest)

### PR DESCRIPTION
**Pull request by RoboMagus**
## Proposed change

This reorders the bottom row cells for energy comparison such that the cost alligns with the 'previous cost' column.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
N/a
```

## Additional information

- This PR fixes or closes issue: fixes #12882
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts [hunk 1]
```diff
@@ -851,7 +851,10 @@ export class HuiEnergySourcesTableCard
                       )}
                     </th>
                     ${compare
-                      ? html`<td
+                      ? html` ${showCosts
```
Comment (bramkragten) [inline src/panels/lovelace/cards/energy/hui-energy-sources-table-card.ts:854]:
```suggestion
                      ? html`${showCosts
```

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
