### PR TITLE
Fix resize observers and update gauge styling

### LINKED ISSUE #5943: 0.110 broke gauges visualization
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Latest 0.110 update broke `type: gauge`
an image speaks better than what I can do.

as you can see gauges are misaligned now, with bigger and smaller gauge in the same horizontal layout.

before it worked better.

smartostat_dashboard

## Environment

- Home Assistant release with the issue: 0.110
- Last working Home Assistant release (if known): 0.109
- Browser and browser version: Chrome/Firefox
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

The debounced function was created on every resize observation, thus not debouncing at all.

Also changes some style rules for the gauge. 

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/hui-gauge-card.ts [hunk 1]
```diff
@@ -293,68 +294,70 @@ class HuiGaugeCard extends LitElement implements LovelaceCard {
       round-slider {
         max-width: 200px;
         --round-slider-path-width: 35px;
-        --round-slider-path-color: var(--disabled-text-color);
+        --round-slider-path-color: var(--primary-background-color);
```
Comment (zsarnett) [inline src/panels/lovelace/cards/hui-gauge-card.ts:297]: Is this right? Shouldn't it be the gray color? At least that's what it has been I thought

File: src/panels/lovelace/cards/hui-gauge-card.ts [hunk 2]
```diff
@@ -250,7 +248,10 @@ class HuiGaugeCard extends LitElement implements LovelaceCard {
     this._resizeObserver.observe(card);
   }
 
+  private _debouncedMeasure = debounce(() => this._measureCard(), 250, true);
+
   private _measureCard() {
+    console.log("meause gauge");
```
Comment (zsarnett) [inline src/panels/lovelace/cards/hui-gauge-card.ts:254]:
```suggestion
```

Console.bye

File: src/panels/lovelace/cards/hui-gauge-card.ts (hunk 1 above)
Comment (bramkragten) [reply src/panels/lovelace/cards/hui-gauge-card.ts:297]: Should definitely not be a text color, I think this was used before the round slider change

**Review by zsarnett — APPROVED** [review]
