### PR TITLE
Fix inconsistencies in `slugify` between frontend and core implementation

### LINKED ISSUE #15757: Entity IDs are not always renamed when renaming a device
### The problem

When I rename a Zigbee device there is a dialog that asks me to if I want to change the entity IDs as well. If I say yes, the entity IDs are not changed.

Here is a screen recording:

https://user-images.githubusercontent.com/1188538/196586382-af10dcee-ebb9-48f6-ab20-c4f74e09fba4.mp4

### What version of Home Assistant Core has the issue?

Home Assistant 2022.9.6 Frontend 20220907.2 - latest

### What was the last working version of Home Assistant Core?

_No response_

### What type of installation are you running?

Home Assistant Container

### Integration causing the issue

It's a ZHA device, but renaming entities might be a core feature

### Link to integration documentation on our website

_No response_

### Diagnostics information

[zha-e44f7ca51ed6bada21b888b7b0c6b6c0-LUMI lumi.weather-08fe1d02a16a83e6e6930e325da2cc71.json (1).txt](https://github.com/home-assistant/core/files/9816469/zha-e44f7ca51ed6bada21b888b7b0c6b6c0-LUMI.lumi.weather-08fe1d02a16a83e6e6930e325da2cc71.json.1.txt)

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Caius-Bonus**
## Proposed change
Change behaviour of slugify
Replace all special characters.
Remove commas from in between numbers.
Don't replace & with "and"
Update the language specific letters with the string from the original gist.
Return "unknown" if slug is empty and "" if input is empty.

There are 3 things it doesn't exactly mimic:
The replacement of language specific characters is not done by the same library.
The Decimal and Hex Patterns (decimal and hexadecimal numbers preceded by "&#") are not handled the same way.

## Benefits

This solves issues with renaming entity ids when renaming the device in home assistant. If the device id contains specific characters (special characters like ".", "&", etc.), the device name cannot be recognized in the entity id and it will not rename the entity.

## Impact

It is a little unclear to me what the impact of this could be, because I don't know if these need to be reproducible. With that I mean: Needing to follow a strict format between different Home Assistant versions to allow for regeneration of the same slugified string for referencing data made with previous versions.

It is used for non-entities here, where I don't know if these need to be reproducible:
https://github.com/home-assistant/frontend/blob/16766f8878a944ba3ebff438efd8bb96e5e45392/src/common/entity/state_color.ts#L67
https://github.com/home-assistant/frontend/blob/16766f8878a944ba3ebff438efd8bb96e5e45392/src/panels/lovelace/editor/view-editor/hui-view-editor.ts#L124
https://github.com/home-assistant/frontend/blob/16766f8878a944ba3ebff438efd8bb96e5e45392/src/panels/lovelace/editor/view-editor/hui-view-editor.ts#L126
https://github.com/home-assistant/frontend/blob/16766f8878a944ba3ebff438efd8bb96e5e45392/src/panels/config/lovelace/dashboards/dialog-lovelace-dashboard-detail.ts#L246

It is used for non-entities here, where they don't seem like they need to be reproducible:
https://github.com/home-assistant/frontend/blob/16766f8878a944ba3ebff438efd8bb96e5e45392/hassio/src/dialogs/backup/dialog-hassio-backup.ts#L355
https://github.com/home-assistant/frontend/blob/16766f8878a944ba3ebff438efd8bb96e5e45392/src/panels/config/automation/trigger/types/ha-automation-trigger-webhook.ts#L74

It is used for entities here (These need to be reproducible with the same format as in the back-end, but are not right now):
https://github.com/home-assistant/frontend/blob/16766f8878a944ba3ebff438efd8bb96e5e45392/src/panels/config/integrations/integration-panels/zha/zha-device-card.ts#L139
https://github.com/home-assistant/frontend/blob/16766f8878a944ba3ebff438efd8bb96e5e45392/src/panels/config/integrations/integration-panels/zha/zha-device-card.ts#L140
https://github.com/home-assistant/frontend/blob/16766f8878a944ba3ebff438efd8bb96e5e45392/src/panels/config/script/ha-script-editor.ts#L622
https://github.com/home-assistant/frontend/blob/16766f8878a944ba3ebff438efd8bb96e5e45392/src/panels/config/devices/ha-config-device-page.ts#L1363
https://github.com/home-assistant/frontend/blob/16766f8878a944ba3ebff438efd8bb96e5e45392/src/panels/config/devices/ha-config-device-page.ts#L1368

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/15757
- This PR is related to issue or discussion: 
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by bdraco** [comment]
Confirmed this now matches the backend
```
>>> from homeassistant.util import slugify
>>> slugify("abc.DEF")
'abc_def'
>>> 
```

**Comment by bdraco** [comment]
Specifically its used here

https://github.com/home-assistant/frontend/blob/16766f8878a944ba3ebff438efd8bb96e5e45392/src/panels/config/integrations/integration-panels/zha/zha-device-card.ts#L139

This seems brittle as it relies on the slugify implementation matching perfectly

**Review by bdraco — DISMISSED** [review]

**Comment by Caius-Bonus** [comment]
I agree that this is brittle. As I have understood the functionality, it needs to replace the part of the id that was supposed to be the device name (which should be at the start of the id). I don't know of another way to do this than by string comparison unfortunately.

**Comment by Caius-Bonus** [comment]
I've looked at the backend code for slugify. I think it is not that complicated. It is a very barebones algorithm. I think I got it working the same now as back-end. However, the behaviour is no significantly altered. As long as nothing depends on the old names, this should be fine and increase compatibility with the back-end.

File: src/common/string/slugify.ts [hunk 1]
```diff
@@ -1,19 +1,25 @@
...
-    .replace(/[^\w-]+/g, "") // Remove all non-word characters
-    .replace(/-/g, delimiter) // Replace - with delimiter
+    .replace(/(?<=\d),(?=\d)/g, "") // Remove Commas between numbers
+    .replace(/[^a-z0-9]+/g, delimiter) // Replace all non-word characters
     .replace(new RegExp(`(${delimiter})\\1+`, "g"), "$1") // Replace multiple delimiters with single delimiter
     .replace(new RegExp(`^${delimiter}+`), "") // Trim delimiter from start of text
     .replace(new RegExp(`${delimiter}+$`), ""); // Trim delimiter from end of text
+
+  if (value == "") {
+    return "";
```
Comment (bramkragten) [inline src/common/string/slugify.ts:19]: We can do this before calculating the slug

Comment (Caius-Bonus) [reply src/common/string/slugify.ts:19]: That is correct, but it would be returning from 2 different places in the code, which I consider to be ugly. The time and space complexity are the same in that case (because it is the empty string) and this is easier to read in my opinion.

Comment (Caius-Bonus) [reply src/common/string/slugify.ts]: Nvm. I just realized that the linter wasn't happy with the "else". I changed it so that it checked "value" before calculating the slug.

**Review by bramkragten — APPROVED** [review]
