### PR TITLE
Fix integrations fab spacing

### LINKED ISSUE #5592: Lack of spacing for FAB on Integrations page
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

First reported by @TheZoker  in Discord, the FAB on the Integrations page lacks spacing and touches the far right side of the browser window. I've noticed this too in my personal setup a while ago so it's not new to this version.
 
image

If you switch between "Integrations" and "Areas" panels using the tabs at the top, you should notice the difference of FAB spacing.

Using latest Chrome stable but I also just checked in Firefox too and it's happening there as well.

## Environment

- Home Assistant release with the issue:
- Last working Home Assistant release (if known):
- Browser and browser version: Chrome stable
- Operating system: macOS

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by timmo001**
## Proposed change

Makes sure fab works with scrollbars. Using same logic as the Lovelace view fab

## Type of change

- [x] Code quality improvements to existing code or addition of tests

- This PR fixes or closes issue: fixes #5592 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] Tests have been added to verify that the new code works.

### CODE REVIEW

File: src/panels/config/integrations/ha-config-integrations.ts [hunk 1]
```diff
@@ -637,7 +637,8 @@ class HaConfigIntegrations extends SubscribeMixin(LitElement) {
           margin-top: 0;
         }
         ha-fab {
-          position: fixed;
+          position: sticky;
```
Comment (bramkragten) [inline src/panels/config/integrations/ha-config-integrations.ts:640]: We should not make it sticky, that means it will be under the content instead of at the bottom of your screen when there is little content. We should do it the same as we do on the other pages:
```css
        ha-fab[is-wide] {
          bottom: 24px;
          right: 24px;
        }
```

Comment (timmo001) [reply src/panels/config/integrations/ha-config-integrations.ts:640]: 24px high? Doesn't that go against the material design [spec](https://material.io/components/buttons-floating-action-button#specs)?

Done anyway to match the rest

**Review by bramkragten — APPROVED** [review]
