### PR TITLE
Make "Show more" show everything starting from yesterday

### LINKED ISSUE #10511: See more link actually shows less
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

With the new link "See more" in entity detail "history" tab the logbook shows by default only 3 hours.
But the History tab show states changes for the whole day.

This is quite strange to click on "see more" and getting less informations without another input...

BTW: this is same behaviour on history :)

### Describe the behavior you expected

It should at least diplay the same time period

### Steps to reproduce the issue

1. Click any entity
2. Go to history tab
3. Click in front of "Logbook" the new link see more
4. Logbook shows 3 hours

### What version of Home Assistant Core has the issue?

2021.11.0

### What was the last working version of Home Assistant Core?

N/A

### In which browser are you experiencing the issue with?

Not browser related

### Which operating system are you using to run this browser?

Not browser related

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

I think as the change has been done in the frontend I opened the issue here. I'm not sure it would be relevant in core repo.
See #9717

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Added a new query parameter "start_date" that expects an ISO timestamp string. The more-info dialog will set it to the start of yesterday for the navigation links.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #10511
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by zsarnett — DISMISSED** [review]

File: src/dialogs/more-info/ha-more-info-logbook.ts [hunk 1]
```diff
@@ -44,7 +45,11 @@ export class MoreInfoLogbook extends LitElement {
       return html``;
     }
 
-    const href = "/logbook?entity_id=" + this.entityId;
+    const href =
+      "/logbook?entity_id=" +
+      this.entityId +
+      "&start_date=" +
+      startOfYesterday().getTime();
```
Comment (bramkragten) [inline src/dialogs/more-info/ha-more-info-logbook.ts:52]: Can we not calculate this on every render, either do it just on click (but that will break normal link actions) or calc it only on the first will update (as it will not update much anyway)

Comment (bramkragten) [reply src/dialogs/more-info/ha-more-info-logbook.ts:52]: And let's use an iso string instead of time

File: src/dialogs/more-info/ha-more-info-history.ts [hunk 2]
```diff
@@ -53,6 +54,14 @@ export class MoreInfoHistory extends LitElement {
       : ""}`;
   }
 
+  protected firstUpdated(): void {
+    this._showMoreHref =
+      "/history?entity_id=" +
+      this.entityId +
+      "&start_date=" +
+      startOfYesterday().toISOString();
```
Comment (bramkragten) [inline src/dialogs/more-info/ha-more-info-history.ts:62]:
```suggestion
    this._showMoreHref =
      `/history?entity_id=${this.entityId}&start_date=${startOfYesterday().toISOString()}`;
```

File: src/dialogs/more-info/ha-more-info-history.ts [hunk 3]
```diff
@@ -59,6 +60,10 @@ export class MoreInfoHistory extends LitElement {
     if (changedProps.has("entityId")) {
       this._stateHistory = undefined;
 
+      this._showMoreHref = `/history?entity_id=${
+        this.entityId
+      }&start_date=${startOfYesterday().toISOString()}`;
```
Comment (bramkragten) [inline src/dialogs/more-info/ha-more-info-history.ts:65]: Move it below the `if (!this.entityId)` check

Comment (spacegaier) [reply src/dialogs/more-info/ha-more-info-history.ts:65]: But that would mean that if we generated a HREF and then the entity ID is getting undefined, the HREF would still contain the old entity ID resulting in a wrong link? We could completely clear the HREF in that case, so no navigation happens anymore?

Comment (bramkragten) [reply src/dialogs/more-info/ha-more-info-history.ts:65]: We dont render when the entity id is undefined

**Review by bramkragten — APPROVED** [review]
