### PR TITLE
Fix safari issues and move scrollable to own container

### LINKED ISSUE #7011: Media Browser dialog header disappears after scrolling in Safari
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

So another Safari-specific issue with the media browser.

When you scroll the dialog, the header is supposed to shrink and stay on top like this:
image

It does that initially. But after a tiny bit this header starts to disappear. Here is a screenshot of where it first starts to happen, you lose the breadcrumb trail link and the close button is no longer on-screen:

image

If you scroll a tiny bit more it goes completely off screen:
image

Confirmed this doesn't happen in Chrome or Firefox, only Safari. On both macOS and iOS. 

It's not a huge deal but it does mean you have to scroll all the way back up to the top. 

## Expected behavior

behave same as chrome/ff, sticky header

## Steps to reproduce

1. In Safari, go to Spotify media browser dialog. 
2. Click Categories
3. Scroll. It will "break" by the third row of cover arts.

## Environment

- Home Assistant release with the issue: 0.115.0b9
- Last working Home Assistant release (if known): ??
- Browser and browser version: iOS companion app, macOS companion app (both Safari)
- Operating system: ios/macos

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/7011
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/media-player/ha-media-player-browse.ts [hunk 1]
```diff
@@ -427,6 +446,32 @@ export class HaMediaPlayerBrowse extends LitElement {
       });
   }
 
+  private async _setHeaderHeight() {
+    await this.updateComplete;
+    const header = this._header;
+    const content = this._content;
```
Comment (zsarnett) [inline src/components/media-player/ha-media-player-browse.ts:452]: why?

**Review by zsarnett — APPROVED** [review]
I tested it on a few devices. Seems pretty good. 👍

File: src/components/media-player/ha-media-player-browse.ts (hunk 1 above)
Comment (bramkragten) [reply src/components/media-player/ha-media-player-browse.ts:452]: Saves a few media queries.
