### PR TITLE
Fix ha-dialog actions padding to use safe-area-inset

### LINKED ISSUE #25356: Z-Wave: Primary actions on "remove device" dialog overlap with iPhone home screen
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When removing a device in Z-Wave, the primary actions of that dialog overlap with the iPhone's "home screen" touch area. 

Image

### Describe the behavior you expected

They should be moved up.

### Steps to reproduce the issue

Open Z-Wave network page. Click "Remove device"

### What version of Home Assistant Core has the issue?

2025.5.0b8

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change
- Correctly use `env(safe-area-inset-bottom)` for `ha-dialog` actions.
  - fix #25356

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-dialog.ts [hunk 1]
```diff
@@ -90,7 +90,7 @@ export class HaDialog extends DialogBase {
       }
       .mdc-dialog__actions {
         justify-content: var(--justify-action-buttons, flex-end);
-        padding-bottom: max(env(safe-area-inset-bottom), 24px);
+        padding: 12px 24px max(env(safe-area-inset-bottom), 24px) 24px;
```
Comment (MindFreeze) [inline src/components/ha-dialog.ts:93]:
```suggestion
        padding: 12px 24px max(env(safe-area-inset-bottom), 12px) 24px;
```
Shouldn't this be 12px?

**Review by silamon — APPROVED** [review]
