### PR TITLE
Fix entity-filter-badge update

### LINKED ISSUE #4183: Entity filter badge in LL view needs page refresh
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**
0.101.2

**Last working Home Assistant release (if known):**
None, new feature in 0.101

**UI (States or Lovelace UI?):**
Lovelace

**Browser and Operating System:**
Firefox on Ubuntu

**Description of problem:**
Simple view for playing with the new entity filter badge
```yaml
  - title: Badges Test
    path: badges-test
    badges:
      - type: entity-filter
        entities:
          - entity: switch.mqtt_test1
          - entity: switch.mqtt_test2
        state_filter:
          - 'on'
    cards:
      - type: entities
        entities:
          - entity: switch.mqtt_test1
          - entity: switch.mqtt_test2
        title: Test Switches
```
After toggle of the switches the page needs a reload (F5 in Storage mode) to reflect the state changes.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

### PR DESCRIPTION
**Pull request by iantrich**
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/4183

### CODE REVIEW

File: src/panels/lovelace/badges/hui-entity-filter-badge.ts [hunk 1]
```diff
@@ -109,11 +109,14 @@ class EntityFilterBadge extends HTMLElement implements LovelaceBadge {
       return;
     }
 
-    // Attach element if it has never been attached.
-    if (!this.lastChild) {
-      for (const element of this._elements) {
-        this.appendChild(element);
-      }
+    let child = this.lastElementChild;
```
Comment (bramkragten) [inline src/panels/lovelace/badges/hui-entity-filter-badge.ts]: Can we use `lastChild`? Browser support is better and I don't think we need `lastElementChild`?

File: src/panels/lovelace/badges/hui-entity-filter-badge.ts [hunk 2]
```diff
@@ -109,11 +109,14 @@ class EntityFilterBadge extends HTMLElement implements LovelaceBadge {
...
+    while (child) {
```
Comment (bramkragten) [inline src/panels/lovelace/badges/hui-entity-filter-badge.ts]: while (this.lastChild) {
      this.removeChild(this.lastChild);
    }

**Review by bramkragten — APPROVED** [review]
