### PR TITLE
Fix conditional card visiblity inside section

### LINKED ISSUE #20923: 2024.6.0b0: issue with conditional cards in sections view
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When adding a conditional card to a section and when the condition is not met there is an empty space on the dashboard.

With 2024.5.4:
IMG_9802

With 2024.6.0b0 and b1:
IMG_9803

### Describe the behavior you expected

Same behavior as 2024.5.4 so no empty space

### Steps to reproduce the issue

1. add a section view to a dashboard
2. Add a section 
3. Add a conditional view with a condition which is false 
4. Save your view
...

### What version of Home Assistant Core has the issue?

core-2024.6.0b0

### What was the last working version of Home Assistant Core?

core-2024.5.x

### In which browser are you experiencing the issue with?

Safari, Firefox latest release

### Which operating system are you using to run this browser?

macOS and iOS

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/20923
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **New Features**
  - Introduced dynamic visibility handling for cards, allowing cards to update their visibility based on certain conditions.
  - Added event handling for "card-visibility-changed" to manage card display dynamically.

- **Improvements**
  - Enhanced `HuiCard`, `HuiConditionalCard`, and `HuiEntityFilterCard` with visibility control and event firing capabilities.
  - Improved visibility control logic in `HuiConditionalBase` class.

### CODE REVIEW

File: src/panels/lovelace/cards/hui-card.ts [hunk 1]
```diff
@@ -67,7 +73,11 @@ export class HuiCard extends ReactiveElement {
     this._element = createCardElement(config);
     this._element.hass = this.hass;
     this._element.editMode = this.lovelace.editMode;
-
+    // Update element when the visibility of the card changes (e.g. conditional card or filter card)
+    this._element.addEventListener("card-visibility-changed", (ev) => {
+      ev.stopPropagation();
+      this._updateElement();
+    });
```
[the remark this answers is not in the document]
Comment (piitaya) [reply src/panels/lovelace/cards/hui-card.ts:80]: Element is created few line before so it never have this listener

File: src/panels/lovelace/components/hui-conditional-base.ts [hunk 2]
```diff
@@ -132,14 +138,15 @@ export class HuiConditionalBase extends ReactiveElement {
     this._setVisibility(conditionMet);
   }
 
-  private _setVisibility(conditionMet: boolean) {
+  protected _setVisibility(conditionMet: boolean) {
```
Comment (bramkragten) [inline src/panels/lovelace/components/hui-conditional-base.ts:141]: Should a protected function start with a `_`? 🤔

**Review by bramkragten — DISMISSED** [review]

File: src/panels/lovelace/components/hui-conditional-base.ts (hunk 2 above)
Comment (piitaya) [reply src/panels/lovelace/components/hui-conditional-base.ts:141]: Of course not ! 😅

**Review by bramkragten — DISMISSED** [review]

**Review by bramkragten — APPROVED** [review]
