### PR TITLE
Fix custom panel size

### LINKED ISSUE #28868: `hass-subpage` in `ha-panel-custom` has incorrect height on mobile
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

When loading a `hass-subpage` or `hass-tabs-subpage-data-table` embedded in a `ha-panel-custom` (iframe) the height seems to be off on iOS depending on the app that's used:
- mobile Safari: you can scroll the header (menu, search bar etc.) upwards (individually of the content) until it isn't visible anymore. 
- HA companion app: the header is fixed properly, but there is a unusable grey margin at the bottom
- desktop Safari responsive mode: everything works as expected, but there are no browser-search-bars or something like that that may use the height

### Describe the behavior you expected

The full height shall be usable for companion app and the app header shall be fixed on mobile Safari

### Steps to reproduce the issue

1. open a custom panel that uses `hass-subpage` (or data-table) on an iOS device (app or Safari). Possible candidates are KNX or HACS config panel
2. scroll the header
3. wonder why the header is scrollable
...

### What version of Home Assistant Core has the issue?

2026.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

mobile Safari and Companion App

### Which operating system are you using to run this browser?

iOS 18.6.2

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

mobile Safari scrolling a `hass-subpage` and a `hass-tabs-subpage-data-table`
https://github.com/user-attachments/assets/5e166caf-bc5f-4365-9802-c77170a5beec

Companion App with unused margin at bottom for 
| `hass-subpage` | `hass-tabs-subpage-data-table` |
|--------|--------|
| Image | Image |

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change
- custom panel should be always full width and height and manage safe area on it's own to provide a natural scrolling
- fix #28868

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [ ] I understand the code I am submitting and can explain how it works.
- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] I have followed the [development checklist][dev-checklist]
- [ ] I have followed the [perfect PR recommendations][perfect-pr]
- [ ] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/panels/custom/ha-panel-custom.ts [hunk 1]
```diff
@@ -147,20 +147,12 @@ export class HaPanelCustom extends ReactiveElement {
     this.innerHTML = `
       <style>
         iframe {
-          border: 0;
-          width: calc(100% - var(--safe-area-inset-right, 0px));
-          height: calc(100% - var(--safe-area-inset-top, 0px) - var(--safe-area-inset-bottom, 0px));
+          border: none;
+          width: 100%;
+          height: 100vh;
+          height: 100dvh;
```
Comment (timmo001) [inline src/panels/custom/ha-panel-custom.ts:153]: Should this be 100%? Would this break if a toolbar is in use?

Pre safe area commit:

https://github.com/home-assistant/frontend/blob/abe8899f9b78ef5923fac7b5060eb2878f5447a6/src/panels/custom/ha-panel-custom.ts#L150-L151

**Review by timmo001 — APPROVED** [review]
This might have been old knowledge. I don't see any that use the toolbar like in /history anymore

**Comment by dcapslock** [comment]
@wendevlin Just notcied that a build with fix means that Browser Mod custom panel no longer scrolls. Any pointers as to why?

**Comment by wendevlin** [comment]
> @wendevlin Just notcied that a build with fix means that Browser Mod custom panel no longer scrolls. Any pointers as to why?

Sorry no idea. We just made the panel size the actual screen size.

**Comment by dcapslock** [comment]
OK. It's not this change, it seems to be overflow: none on app-top-bar-fixed.

**Comment by dcapslock** [comment]
Worked it out :-)
