### PR TITLE
Fix filters for entity/device from integrations dashboard

### LINKED ISSUE #20919: New data table feature that saves filters interferes with integration entities
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

So the new release now saves your filters which is cool, but noticed a potential issue with it.. Because it saves your filters, some links like this on the integrations page may not work properly anymore. 

For example, if your Entities page is filtered by "Living Room" area, and then you click the link in this screenshot, it will not show any sun entities because none of them are in the living room area. So the user clicks something saying 9 entities and instead gets 0 entities and is wondering what's going on.

Screen Shot 2024-05-30 at 5 08 28 AM

(There's an example below to reproduce)

### Describe the behavior you expected

Technically this is not a bug I guess, but I feel it's gonna be super confusing for some, especially those who don't read the release notes and aren't aware of the new behavior. It might be better for these links specifically to ignore the users saved filters if possible?

If the user clicks on something that says "9 entities" it should actually show those 9 entities, not 0 entities...

### Steps to reproduce the issue

1. Go to Entities page
2. Open filter sidebar and select "Domain: Binary Sensor"
4. Now go to Integrations page (can use the tabs at the top)
5. Click on an integration, for example "Sun"
6. On the next page click the "9 entities" button.
7.  Instead of showing those 9 entities it shows 0 entities because it's using saved filter from step 2, and the sun integration has no binary sensors. 

### What version of Home Assistant Core has the issue?

2024.6.0b1

### What was the last working version of Home Assistant Core?

2024.5.5

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ZephireNZ**
## Proposed change

- Fix the entity list so that it adds URL filters when navigating from the integration dashboard
- Tweak the logic for `_setFiltersFromUrl` so that `domain`/`config_entry` are cleared when not present in the URL.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

N/A

## Additional information

- This PR fixes or closes issue: fixes #20919
- This PR is related to issue or discussion: N/A
- Link to documentation pull request: N/A

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

## Summary by CodeRabbit

- **Refactor**
  - Simplified filter setting logic in device and entity dashboards for better maintainability and readability.

### CODE REVIEW

File: src/panels/config/entities/ha-config-entities.ts [hunk 1]
```diff
@@ -952,39 +953,31 @@ ${
...
-          value: [this._searchParms.get("config_entry")!],
-          items: undefined,
-        },
-      };
-    }
+    const domain = this._searchParms.get("domain");
+    const configEntry = this._searchParms.get("config_entry");
+
+    this._filters = {
+      ...this._filters,
```
Comment (ZephireNZ) [inline src/panels/config/entities/ha-config-entities.ts:966]: The GH issue brings up a good point - should we clear some more/all existing filters when URL parameters are present?

I feel like the areas and devices filters could also cause confusion.

Comment (bramkragten) [reply src/panels/config/entities/ha-config-entities.ts:966]: I agree!

**Review by bramkragten — APPROVED** [review]
