### PR TITLE
Fix double toolbars on error/loading in dev tools

### LINKED ISSUE #4973: Dev tools pages use hass-loading-page rendering second toolbar
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

The dev tool pages uses hass-loading-page, rendering a second toolbar. Looks especially weird when we have an error.

Screen Shot 2020-02-24 at 17 58 54
Screen Shot 2020-02-24 at 18 00 05

## Expected behavior

No double toolbars. It should just render the loading spinner in the middle.

## Steps to reproduce
1. Open Home Assistant
2. Open Dev tools
3. Turn off Home Assistant
4. Navigate to another tab

## Environment

- Home Assistant release with the issue: 107
- Last working Home Assistant release (if known): -
- UI Type (States or Lovelace): dev tools
- Browser and browser version: all
- Operating system: all

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Fixes https://github.com/home-assistant/frontend/issues/4973

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/layouts/hass-loading-screen.ts [hunk 1]
```diff
@@ -16,28 +16,32 @@ import { HomeAssistant } from "../types";
 
 @customElement("hass-loading-screen")
 class HassLoadingScreen extends LitElement {
-  @property({ type: Boolean }) public rootnav? = false;
+  @property({ type: Boolean }) public toolbar = true;
```
Comment (balloob) [inline src/layouts/hass-loading-screen.ts:19]: If we do this, we can remove `layouts/loading-screen.ts`, which is the loading screen without a toolbar.

**Review by balloob — APPROVED** [review]

File: src/layouts/hass-loading-screen.ts (hunk 1 above)
Comment (bramkragten) [reply src/layouts/hass-loading-screen.ts:19]: Let me turn it around then, so we can do `<hass-loading-screen no-toolbar></hass-loading-screen>`

Comment (balloob) [reply src/layouts/hass-loading-screen.ts:19]: sounds good
