### PR TITLE
Fix lock more info with attributes

### LINKED ISSUE #15568: Lock Attributes Bug Fix
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

Look at the Attributes
image

### Describe the behavior you expected

*

### Steps to reproduce the issue

*

### What version of Home Assistant Core has the issue?

Beta

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by piitaya**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #15568
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/more-info/controls/more-info-lock.ts [hunk 1]
```diff
@@ -20,8 +20,8 @@ class MoreInfoLock extends LitElement {
       return html``;
     }
     return html`
-      ${this.stateObj.attributes.code_format
-        ? html`
+      ${this.stateObj.attributes.code_format || true
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-lock.ts:23]:
```suggestion
      ${this.stateObj.attributes.code_format
```

Comment (piitaya) [reply src/dialogs/more-info/controls/more-info-lock.ts]: 🙈

**Review by bramkragten — APPROVED** [review]
