### PR TITLE
Simplify calendar "listWeek" and enable for "initial_view"

### LINKED ISSUE #9193: Calendard card : not possible to have more than 2 weeks in 'week list'. Whereas possible in month list and day list
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

When display in lovelace a calendar
````yaml
type: calendar
entities:
  - calendar.garbage_collection
initial_view: dayGridMonth
title: Poubelle
````
In week list only current week and next week is available.
If you go in month list or day list you can go backward and forward. If you go back to "week list" , then you can go further ....

### Describe the behavior you expected

Get the same behaviour for prev and next button for month, day, week : not limited to current and next week

### Steps to reproduce the issue

1. create a calendar card in lovelace
2. select "week view"
3. press next button or previous button
4. issue : you can only select current and the following week
...

### What version of Home Assistant Core has the issue?

2021.5.4

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Microsoft Edge Version 90.0.818.62 (Version officielle) (64 bits) and Firefox 88.0.1 (64 bits)

### Which operating system are you using to run this browser?

window 10

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

```yaml
type: calendar
entities:
  - calendar.garbage_collection
initial_view: dayGridMonth
title: Poubelle
```

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

Hereafter screenshot
Month list :  
image
You can go backward/foward

In Week list, the arrow button let you go to current and next week
image

Nevertheless, if you go through month or day lists, you can go beyond this limit
image

### LINKED ISSUE #9954: Home assistant calendar card week view starting on previous sunday
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

The home assistant calendar card is starting on the previous sunday, even though per closed issue #7064 the start day is now today.

### Describe the behavior you expected

The start day for the calendar should be today.

### Steps to reproduce the issue

1. Setup calendar card
2. Load home assistant

### What version of Home Assistant Core has the issue?

core-2021.9.3

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Safari 14.1.12

### Which operating system are you using to run this browser?

macOS 11.5.2

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

```yaml
type: calendar
entities:
  - calendar.1
  - calendar.2
initial_view: listWeek
```

### Javascript errors shown in your browser console/inspector

```txt
n/a
```

### Additional information

The date today is 9/4 but the calendar list view by default shows last sunday to today. If I click the list view icon after the page loads it then changes to the correct view.

View on page load:
Screen Shot 2021-09-04 at 9 48 14 PM
View after clicking circled button:
Screen Shot 2021-09-04 at 9 50 29 PM

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Make sure we have a proper list view that can navigate also in the future (the current one only goes one page into the future at most, see https://github.com/home-assistant/frontend/issues/9193).

Keeps the old translation key and <s>stay true to the current keys in the documentation</s> (the key unfortunately was changed by now https://github.com/home-assistant/home-assistant.io/pull/24826). Also simplifies the logic (there is no need for a custom `visibleRange` logic).

Also ensured that toggle buttons now have a tooltip, so that the user can get an idea what the different view buttons are.

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #9954 fixes #9193
- This PR is related to issue or discussion:
- Link to documentation pull request: https://github.com/home-assistant/home-assistant.io/pull/25158

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/calendar/ha-full-calendar.ts [hunk 1]
```diff
@@ -73,7 +65,7 @@ const viewButtons: ToggleButton[] = [
   { label: "Month View", value: "dayGridMonth", iconPath: mdiViewModule },
   { label: "Week View", value: "dayGridWeek", iconPath: mdiViewWeek },
   { label: "Day View", value: "dayGridDay", iconPath: mdiViewDay },
-  { label: "List View", value: "list", iconPath: mdiViewAgenda },
+  { label: "List View (7 days)", value: "listWeek", iconPath: mdiViewAgenda },
```
Comment (bramkragten) [inline src/panels/calendar/ha-full-calendar.ts:68]: Can we use the translation?

**Review by bramkragten — DISMISSED** [review]

File: src/panels/calendar/ha-full-calendar.ts [hunk 2]
```diff
@@ -275,11 +270,44 @@ export class HAFullCalendar extends LitElement {
     });
   }
 
-  private _viewToggleButtons = memoize((views) =>
-    viewButtons.filter((button) =>
+  private _viewToggleButtons = memoize((views) => {
+    if (!this._viewButtons) {
```
Comment (bramkragten) [inline src/panels/calendar/ha-full-calendar.ts:274]: If the user changes the language, it should still update

**Comment by spacegaier** [comment]
**Note to self:** Before we merge that, https://github.com/home-assistant/frontend/issues/9193 should be investigated, since that might tie into this PR.

**Review by zsarnett — DISMISSED** [review]

**Comment by zsarnett** [comment]
Can we add the user's language to memoize?

**Comment by spacegaier** [comment]
Yes, plus there is another comment I mentioned above that needs to be checked out => this PR should be a draft

**Comment by jugla** [comment]
#12093 seems to be stuck and this PR may solve it.
How to handle ?

**Comment by spacegaier** [comment]
@bramkragten @piitaya Direct ping, since this PR is quite down in the list but might be of interest for 2012.12 in combination with all the other improvements around calendars (local calendar in the backend and the myriad of related frontend PRs is crated over the last days 😉).

**Review by bramkragten — APPROVED** [review]
