### PR TITLE
Standardise fixed top ha-dialog usages and fix safe areas

### LINKED ISSUE #27996: Safe area: ha-dialog
### Description

The issue here is the use of padding for narrow layouts, we should make it so all layouts use the safe areas, whether that be margins or container padding over the surface padding while not in fullscreen modal mode

https://github.com/home-assistant/frontend/issues/26818#issuecomment-3396566152

Image

https://github.com/home-assistant/frontend/issues/26818#issuecomment-3396575607

Image

https://github.com/home-assistant/frontend/issues/26818#issuecomment-3396574095

Image

https://github.com/home-assistant/frontend/issues/26818#issuecomment-3396554178

Image

### PR DESCRIPTION
**Pull request by timmo001**
## Proposed change

Various style consolidation and fixes for ha-dialog and its usages.

Introduces a container padding to make dialogs conform to safe areas and use padding on the surface instead when on narrow layouts. Swaps between the 2 when layout changes to full mode.

https://github.com/user-attachments/assets/f7cfed44-f515-492b-a52e-43048cc67a6a

https://github.com/user-attachments/assets/5c07a5fd-14bf-433c-abe8-7fdc5e5580c5

Also moves more info dialog styles for fixed top to shared area to be reused on other dialogs like the media browser.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #27996
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/media-player/dialog-media-player-browse.ts [hunk 1]
```diff
@@ -223,30 +223,53 @@ class DialogMediaPlayerBrowse extends LitElement {
...
       css`
         ha-dialog {
           --dialog-z-index: 9;
           --dialog-content-padding: 0;
         }
 
         ha-media-player-browse {
-          --media-browser-max-height: calc(100vh - 65px);
+          --media-browser-max-height: calc(
+            100vh -
```
Comment (timmo001) [inline src/components/media-player/dialog-media-player-browse.ts]: This appears to always show full height, may be lit-virtualiser related

File: src/components/media-player/dialog-media-player-browse.ts [hunk 2]
```diff
@@ -223,30 +223,45 @@ class DialogMediaPlayerBrowse extends LitElement {
...
+              65px - var(--safe-area-inset-top, var(--ha-space-0)) - var(
+                --safe-area-inset-bottom,
+                var(--ha-space-0)
+              )
+          );
```
Comment (MindFreeze) [inline src/components/media-player/dialog-media-player-browse.ts:236]: This can be simplified, I think
```suggestion
          --media-browser-max-height: calc(100vh - 65px - var(--safe-area-inset-y));
```

File: src/components/media-player/dialog-media-player-browse.ts [hunk 3]
```diff
@@ -223,30 +223,41 @@ class DialogMediaPlayerBrowse extends LitElement {
...
 
         :host(.opened) ha-media-player-browse {
-          height: calc(100vh - 65px);
+          height: calc(
+            100vh -
+              65px - var(--safe-area-inset-top, var(--ha-space-0)) - var(
+                --safe-area-inset-bottom,
+                var(--ha-space-0)
+              )
+          );
```
Comment (MindFreeze) [inline src/components/media-player/dialog-media-player-browse.ts]: Another one
```suggestion
          height: calc(
            100vh - 65px - var(--safe-area-inset-y)
          );
```

**Review by MindFreeze — DISMISSED** [review]

**Review by MindFreeze — APPROVED** [review]
