### PR TITLE
Fix hui-conditional-row causing varying row margins.

### LINKED ISSUE #7292: Entities card with conditional row - card’s height is changing when it shouldn’t
## Checklist
- [ x ] I have updated to the latest available Home Assistant version.
- [ x ] I have cleared the cache of my browser.
- [ x ] I have tried a different browser to see if it is related to my browser.

## The problem
When an Entities card has at least one conditional row (one row if condition "true", another row if condition "false" - i.e. "show one row instead another row"), then the card's height is changing dependently on condition - but it shouldn't since total number of rows is not changing.

## Expected behavior
Both the cards should have the same height - because total number of rows was not changed.

## Steps to reproduce
1. Create 2 cards (code is provided below).
2. Place them in one line.
3. Note that both the cards have the same height.
4. Switch a state on any of these cards.
5. Now you see that one card has a bigger height.

## Environment

- Home Assistant release with the issue: 0.116.0
- Last working Home Assistant release (if known):
- Browser and browser version: Firefox 81.0.1
- Operating system: Win10x64

## State of relevant entities

```yaml

```

## Problem-relevant configuration

Card 1:
```
type: entities
entities:
  - input_boolean.test_boolean
  - type: conditional
    conditions:
      - entity: input_boolean.test_boolean
        state: 'on'
    row:
      entity: sun.sun
  - type: conditional
    conditions:
      - entity: input_boolean.test_boolean
        state: 'off'
    row:
      entity: sun.sun
```

Card 2:
```
type: entities
entities:
  - entity: input_boolean.test_boolean
  - entity: sun.sun

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by dcapslock**
## Breaking change

DOM structure is same so should not be breaking in any way but slim chance that it may affect card modders.

## Proposed change

Entities card rows use margins set by CSS selectors :first-child and :last-child which break when using conditional row as first or last row. This PR changes the states div child divs to have their visibiity updated on visibility-change so that flex grid display and gap CSS can be used, similar to how other cards manage this, though entities card has teh complexity of teh extra div.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml
type: entities
entities:
  - entity: input_boolean.test_boolean
  - type: conditional
    conditions:
      - entity: input_boolean.test_boolean
        state: "on"
    row:
      entity: sun.sun
  - entity: device_tracker.demo_anne_therese
  - type: conditional
    conditions:
      - entity: input_boolean.test_boolean
        state: "off"
    row:
      entity: sun.sun
```

## Additional information

Video of issue prior PR

https://github.com/user-attachments/assets/f0f56b56-b0e1-4107-83db-17038738c3e4

Video after PR

https://github.com/user-attachments/assets/9598f7dc-0a40-4fd7-b695-f383fc9aa989

- This PR fixes or closes issue: fixes #7292 
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/hui-entities-card.ts [hunk 1]
```diff
@@ -60,6 +60,22 @@ class HuiEntitiesCard extends LitElement implements LovelaceCard {
 
   private _footerElement?: LovelaceHeaderFooter;
 
+  connectedCallback(): void {
+    super.connectedCallback();
+    this.addEventListener(
+      "visibility-changed",
+      this._updateRowVisibility.bind(this)
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-entities-card.ts]:
```suggestion
      this._updateRowVisibility
```

File: src/panels/lovelace/cards/hui-entities-card.ts [hunk 2]
```diff
@@ -60,6 +60,22 @@ class HuiEntitiesCard extends LitElement implements LovelaceCard {
...
+    );
+  }
+
+  disconnectedCallback(): void {
+    super.disconnectedCallback();
+    this.removeEventListener(
+      "visibility-changed",
+      this._updateRowVisibility.bind(this)
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-entities-card.ts]:
```suggestion
      this._updateRowVisibility
```

File: src/panels/lovelace/cards/hui-entities-card.ts [hunk 3]
```diff
@@ -301,7 +308,19 @@ class HuiEntitiesCard extends LitElement implements LovelaceCard {
       element.hass = this._hass;
     }
 
-    return html`<div>${element}</div>`;
+    return html`<div ?hidden=${element.hidden}>${element}</div>`;
+  }
+
+  private _updateRowVisibility() {
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-entities-card.ts]:
```suggestion
  private _updateRowVisibility = () => {
```

File: src/panels/lovelace/components/hui-conditional-base.ts [hunk 4]
```diff
@@ -147,6 +148,7 @@ export class HuiConditionalBase extends ReactiveElement {
     if (this.hidden !== !visible) {
       this.toggleAttribute("hidden", !visible);
       this.style.setProperty("display", visible ? "" : "none");
+      fireEvent(this, "visibility-changed", { value: visible });
```
Comment (bramkragten) [inline src/panels/lovelace/components/hui-conditional-base.ts]: this event was no longer used, and we should follow the pattern of the other events, like `card-visibility-changed`

Comment (bramkragten) [reply src/panels/lovelace/components/hui-conditional-base.ts]: So implement it in `hui-conditional-row`

File: src/panels/lovelace/cards/hui-entities-card.ts [hunk 5]
```diff
@@ -244,18 +260,9 @@ class HuiEntitiesCard extends LitElement implements LovelaceCard {
...
-
-    #states > *:first-child {
-      margin-top: 0;
-    }
-
-    #states > *:last-child {
-      margin-bottom: 0;
+      display: flex;
+      flex-direction: column;
+      gap: var(--entities-card-row-gap, var(--card-row-gap, 8px));
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-entities-card.ts:271]: this change seems unrelated to the bugfix right? Or?

File: src/panels/lovelace/cards/hui-entities-card.ts [hunk 6]
```diff
@@ -301,7 +308,19 @@ class HuiEntitiesCard extends LitElement implements LovelaceCard {
...
     }
 
-    return html`<div>${element}</div>`;
+    return html`<div ?hidden=${element.hidden}>${element}</div>`;
+  }
+
+  private _updateRowVisibility() {
+    this.shadowRoot
+      ?.querySelectorAll("#states > div > *")
+      .forEach((element: unknown) => {
```
Comment (bramkragten) [inline src/panels/lovelace/cards/hui-entities-card.ts]: Why do we query, when the event contains if the element will be hidden or not and what element it is for?

File: src/panels/lovelace/cards/hui-entities-card.ts (hunk 5 above)
Comment (dcapslock) [reply src/panels/lovelace/cards/hui-entities-card.ts:271]: This is what now provides the 8px gap between rows.

File: src/panels/lovelace/cards/hui-entities-card.ts (hunk 6 above)
Comment (dcapslock) [reply src/panels/lovelace/cards/hui-entities-card.ts]: The element is the entity row. This follows the similar construct in how hass is applied to row elemets vis the #states div elements.

Comment (dcapslock) [reply src/panels/lovelace/cards/hui-entities-card.ts]: The hidden attribute comes from the entity row. Hiding the div manages not having multiple gap CSS applied. There is actually a gap-collapse CSS directive proposed (will function like border-collapse) which would make this much simpler.

To note: This is similar to vertical-stack, but in that case, the cards are direct children, whereas entities have the #states > div to deal with. It may be possible to refactor the whole layout of entities to take out the div layer which then makes things a bit simpler.

File: src/panels/lovelace/components/hui-conditional-base.ts (hunk 4 above)
Comment (dcapslock) [reply src/panels/lovelace/components/hui-conditional-base.ts]: Thanks for the suggestion. I will proceed to make these changes.

File: src/panels/lovelace/cards/hui-entities-card.ts (hunk 6 above)
Comment (bramkragten) [reply src/panels/lovelace/cards/hui-entities-card.ts]: I still dont understand why we have to query and go over all the rows, and can not just do it for the row the event is fired on.

Something like:
```ts
private _updateRowVisibility = (ev) => {
	if (!ev.detail.value) {
		ev.target.parentElement!.style.display = "none";
	} else {
		ev.target.parentElement!.style.display = "";		
	}
}

```

Comment (dcapslock) [reply src/panels/lovelace/cards/hui-entities-card.ts]: It should work. I will test it out.

Comment (dcapslock) [reply src/panels/lovelace/cards/hui-entities-card.ts]: Target is entities card, not row. To simplify I have passed row in row-visibility-changed event and used that to make the event handler simpler like you suggested.

**Review by MindFreeze — APPROVED** [review]

**Comment by ildar170975** [comment]
The Entities card became bigger after this PR.
Was it possible to keep the same size?

изображение

Update: seems be caused by migration to typography tokens instead.
