### PR TITLE
Fix formfield display

### LINKED ISSUE #6233: Panel mode secondary text in View Configuration dialog in 0.112.0b0
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

This one is a minor cosmetic thing, but in 0.112.0b0 the secondary text for Panel Mode does not appear on its own line like it used to. Screenshot:

image

How it's supposed to look:

image

## Steps to reproduce

1. Enter Configure UI Mode
2. Add or Edit a view, look at bottom of that dialog

## Environment

- Home Assistant release with the issue: 0.112.0b0
- Last working Home Assistant release (if known): 0.111.4
- Browser and browser version: Chrome latest
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### LINKED ISSUE #6234: Cosmetic issue on toggles when editing dashboards 0.112.0b0
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Perhaps related to https://github.com/home-assistant/frontend/issues/6233 but this is a bit different so opened a new issue just to be safe.

Prior to this version the toggle switches would appear on different lines, this is no longer the case. They're showing on the same line now, which might be intentional, but I think at the very least it needs some spacing between. 

image

## Steps to reproduce

1. Go to Configuration -> Lovelace Dashboards
2. Click on a UI-controlled one to open the dialog

## Environment

- Home Assistant release with the issue: 0.112.0b0
- Last working Home Assistant release (if known): 0.111.4
- Browser and browser version: Chrome
- Operating system: macOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by balloob**
## Proposed change
ha-formfield display option was changed to inline-flex. Addresses UI issues.

Fixes #6234
Fixes #6233

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/editor/config-elements/hui-button-card-editor.ts [hunk 1]
```diff
@@ -133,78 +133,78 @@ export class HuiButtonCardEditor extends LitElement
...
-          ><div class="suffix" slot="suffix">px</div>
+            ><div class="suffix" slot="suffix">px</div>
           </paper-input>
           <hui-theme-select-editor
             .hass=${this.hass}
             .value="${this._theme}"
             .configValue="${"theme"}"
             @value-changed="${this._valueChanged}"
           ></hui-theme-select-editor>
-        </paper-input>
```
Comment (balloob) [inline src/panels/lovelace/editor/config-elements/hui-button-card-editor.ts:186]: This was invalid HTML, once I removed it prettier kicked in.

**Review by zsarnett — APPROVED** [review]
