### PR TITLE
Handle "unknown" for date, time and datetime entities

### LINKED ISSUE #17041: Time entity can't be set when state is `unknown`
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

If a time entity has a state of `unknown` a user can't select the input to set a new time.
This may be the case when a time entity is initially configured and its state can't be sourced from the integration (ie. it is write only).

### Describe the behavior you expected

Users should be able to set new times when the entity is available.

### Steps to reproduce the issue

1.
2.
3.
...

### What version of Home Assistant Core has the issue?

2023.7.0.dev0

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt
unknown
```

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

Bildschirmfoto 2023-06-26 um 22 23 19

"MyTime" here is `unknown`, the second time entity "Time" is from the `demo` integration.

Bildschirmfoto 2023-06-26 um 22 24 34

### PR DESCRIPTION
**Pull request by spacegaier**
## Proposed change

Previously the state "unknown" meant that the user could not input any time values as the controls were hidden and/or disabled. This PR reduces that behavior to the state "unavailable" only.

Example of all three being in state "unknown"

image

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #17041
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [X] The code change is tested and works locally.
- [X] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/dialogs/more-info/controls/more-info-time.ts [hunk 1]
```diff
@@ -14,15 +14,15 @@ class MoreInfoTime extends LitElement {
...
 
   protected render() {
-    if (!this.stateObj || isUnavailableState(this.stateObj.state)) {
+    if (!this.stateObj || this.stateObj.state === UNAVAILABLE) {
       return nothing;
     }
 
     return html`
       <ha-time-input
         .value=${this.stateObj.state}
```
Comment (bramkragten) [inline src/dialogs/more-info/controls/more-info-time.ts:23]: we also set the value of the input to `unknown`, we should probably guard for that as it is not a valid time?

Comment (spacegaier) [reply src/dialogs/more-info/controls/more-info-time.ts]: I changed it to set `undefined` which means the time/date widgets are empty which is the correct visual state from my POV.

**Review by bramkragten — APPROVED** [review]
