### PR TITLE
Use whole months for "Last 12 Months" on Energy Date Picker

### LINKED ISSUE #30089: Endergy Dashboard - 12 Months
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Using the last 12 months view for energy is showing 365 days individually instead of the last 12 months total.

Image

### Describe the behavior you expected

Should be monthly totals not daily.

### Steps to reproduce the issue

1. Visit Energy Dashboard
2. Select "Last 12" months as date range
...

### What version of Home Assistant Core has the issue?

core-2026.3.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Firefox

### Which operating system are you using to run this browser?

Arch

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by TCWORLD**
## Breaking change

This is potentially breaking in that the function that calculates `now-12m` has been changed to use the logic proposed here - selecting 12 whole months up to and including the current month - rather than the original behaviour of selecting the ~365 individual days up to and including today.

However the `now-12m` option seems to be only used by the energy date picker so I don't think this is a particular problem.

## Proposed change

Currently the "Last 12 Months" date function selects 12 months worth of days back from the current day. So if today is March 10, then it would retrieve April 11 to March 10.

For the energy dashboard, previously this would select those days but they the ECharts would display them as aggregated monthly bars. This changed recently (see #30089) meaning we now see all those individual days.

This doesn't seem like a particularly useful range - particularly for comparing month on month data.

I'm proposing we change the meaning of the "Last 12 Months" to imply whole months up to and including the current month - i.e. treat "now" to mean (currently) "March", so the last 12 months selects Apr 1 to March 31. This means the quick action of selecting that range picks whole numbers of months so renders nicely and makes comparison of monthly data neater.

The changes here also improve the rendering of whole-month ranges on the energy date picker to shorten to just the month name - so would say "Apr-Mar" (with year shown where needed) rather than "1 Apr-31 Mar" for consistency with the way selecting a single month displays.

## Screenshots

Last 12 Months:
image

This Quarter:
image

Other manually selected monthly ranges (e.g. 4 months) also show as month names now not short dates:
image

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #30089
- This PR is related to issue or discussion: #30089
- Link to documentation pull request:
- Link to developer documentation pull request:
- Link to backend pull request:

## Checklist

- [x] I understand the code I am submitting and can explain how it works.
- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] I have followed the [perfect PR recommendations][perfect-pr]
- [x] Any generated code has been carefully reviewed for correctness and compliance with project standards.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

To help with the load of incoming pull requests:

- [x] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/frontend/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

File: src/common/datetime/calc_date_range.ts [hunk 1]
```diff
@@ -93,8 +93,8 @@ export const calcDateRange = (
       ];
     case "now-12m":
       return [
-        calcDate(today, subMonths, hass.locale, hass.config, 12),
-        calcDate(today, subMonths, hass.locale, hass.config, 0),
+        calcDate(subMonths(today, 11), startOfMonth, hass.locale, hass.config),
```
Comment (MindFreeze) [inline src/common/datetime/calc_date_range.ts]: Calling `subMonths(today, 11)` here bypasses the timezone checks in `calcDate`. Better to still pass `today` and just pass a custom callback instead of `subMonths` that does `date => startOfMonth(subMonths(date, 11))`

**Review by MindFreeze — CHANGES_REQUESTED** [review]

File: src/common/datetime/calc_date_range.ts (hunk 1 above)
Comment (TCWORLD) [reply src/common/datetime/calc_date_range.ts]: I'll have another look. I just followed the pattern used for `case "yesterday"` where it uses `addDays` in the same way.

**Review by MindFreeze — APPROVED** [review]

**Comment by NL-DUX** [comment]
I, for one, was happy to see the situation above where "last twelve months" would equal today-365d for it would give me insight whether my current usage has a rising of falling trend on a daily basis. I don't want to wait a full month to see how I did? Nevertheless, I do understand that there a two sides on this request and (sadly) the other team won on this. Perhaps a future extra filter option will fill my personal request on this.

HOWEVER, today I noticed that neither of us seem to get what we want. The current "last 12 months" filter on the energy dashboard now displays the last 11 full months PLUS whatever amount of days passed in the current 12th month. So now it's neither twelve full months nor the last 365 days. Today being april 5th, it shows the last 340 days. Tomorrow it will show the last 341 days.

Core 2026.4.1
Supervisor 2026.03.2
Operating System 17.1
Frontend 20260325.6

**Comment by TCWORLD** [comment]
@NL-DUX  There's a lot of ambiguity in what last 12 months means. The logic was made to be consistent with e. g. last 7 days, where it will show 6 days previous and today - so for months it does last 11 months and this month. 

This was intended to mimic the original behaviour from 2026.1 that was lost - it would show monthly bars not daily ones I think due to the way ECharts handled the data (screenshot from older version):

Screenshot_20260405-073442_ASUS_Launcher (1)

I think the only difference is before that it was showing the current month only part way into the month (I think rounding once it reached half way through the current month), whereas now it is consistent in showing this month always.

**Comment by NL-DUX** [comment]
That may be true, but how would the current situation reflect on this comment of yours in the opening post: "This doesn't seem like a particularly useful range - particularly for comparing month on month data."?

I'd say that this is exactly what's happening now, with the partially filled current month and all? Right now with the filters working as they do, at no point in time except for the one hour between two months does the filter compare the current month effectively to the previous month. Also, there's no projected or estimated (future) data so you're stuck with an incomplete dataset and are forced to manually click yourself a 1:1 comparable date range. My personal activity, the comparison of two consecutive years (being either the last 12 full months OR the last 365 days which has my preference), is even worse. It can't be achieved without endless mouse clicks going exactly twelve months back in time on the tiny calendar - and then the same amount of clicks back again to the present day to achieve the desired date range and make it 1:1 comparable with a previous series.

I tend to use the energy statistic as follows: "Last year I spent 3000 Euros on the total energy bill, how am I doing right now? Guess I will find out in 8 months time..." with the current setup, but it also could be something like "last 365 days I tracked 3000 Euros on energy bills - what's my trend on this: is this year more expensive than the 365 days before that?". For a brief moment I was able to get this info with ease.

**Comment by TCWORLD** [comment]
I'll be honest, I'm not entirely sure I follow. This was intended to fix something that appeared to be unintentional - if showing the individual day bars was actually an intentional change that I didn't spot, I apologise.

If you want to compare this year to last year, you can select the "This year" range which will show you the current year, and then either enable compare mode to see how this year is comparing to last year trend wise, or use next/previous buttons to quickly switch between years. 

Similarly with last 12 months, compare mode will show you monthly on month comparisons.

I suppose we could have a last 365 days option as well that specifically shows daily data rather than monthly aggregation, but that's not my decision to make.

**Comment by TCWORLD** [comment]
Ok, I was wrong the change in date range was an intentional change by #28902 that I completely missed. Whether rendering as individual bars was a side-effect of that PR, whether intended or unintended.

Perhaps then having a specific last 365 days would give people both options. It seems different people have different opinions of what it should do.
