### PR TITLE
Fix drag and drop when using action and trigger selector

### LINKED ISSUE #22255: Automation: Repeat GUI not visually updating after drag and drop
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.
- [X] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

After creating an Automation and with the 'Repeat' action, trying to drag and drop removes the dragged Action from its original location but it appears no action is added to the 'Repeat' action. If you save the automation and refresh the page or navigate away and back, it correctly displays the action within the 'Repeat' action only. 

The same issue occurs in reverse. Dragging an action from a 'Repeat' action to somewhere else appears to duplicate it, but does not truly continue to exist.

https://github.com/user-attachments/assets/615f595d-8333-4e78-8af5-2acdffaa7aad

### Describe the behavior you expected

To see the 'Action' update in real time and visually show its location.

### Steps to reproduce the issue

1. Create/Edit an Automation
2. Create a `Repeat` action and any other action
3. Drag and drop the other action into the `Repeat` action, and it will visually disappear
4. (Optional) Navigate away and back/refresh the page and it will display correctly

### What version of Home Assistant Core has the issue?

2024.10.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue with?

Google Chrome 129.0.6668.90, Firefox 131.0

### Which operating system are you using to run this browser?

Windows 11

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

I recently attempted to recover a backup and am not confident I did so correctly. This may be a local issue instead of a bug.

### PR DESCRIPTION
**Pull request by piitaya**
## Proposed change

Replaces https://github.com/home-assistant/frontend/pull/22273

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/22255
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by silamon** [comment]
The memoize was introduced in the ha-selector-action, but also in the ha-selector-trigger. Still, I can only reproduce some kind of bug in the ha-selector-action.

**Comment by piitaya** [comment]
> The memoize was introduced in the ha-selector-action, but also in the ha-selector-trigger. Still, I can only reproduce some kind of bug in the ha-selector-action.  

Do you have steps to reproduce it? I tested in blueprints and also using repeat action.
Drag and drop in config flow is still not supported yet. It would be another fix for that.

**Comment by silamon** [comment]
> > The memoize was introduced in the ha-selector-action, but also in the ha-selector-trigger. Still, I can only reproduce some kind of bug in the ha-selector-action.
> 
> Do you have steps to reproduce it? I tested in blueprints and also using repeat action. Drag and drop in config flow is still not supported yet. It would be another fix for that.



> > The memoize was introduced in the ha-selector-action, but also in the ha-selector-trigger. Still, I can only reproduce some kind of bug in the ha-selector-action.
> 
> Do you have steps to reproduce it? I tested in blueprints and also using repeat action. Drag and drop in config flow is still not supported yet. It would be another fix for that.

Your PR works, the only thing I'm questioning if why we see this in the ha-selector-action and not in the ha-selector-trigger. Both have similar code, and having those new nested triggers should bug in the same way, but it doesn't.

**Comment by piitaya** [comment]
I just tested on a blueprint with 2 triggers and we have the same issue. We have it in the automation editor for action because the repeat action is using selector internally instead of directly using the `ha-automation-action` component.

I will add the fix for trigger too.

**Review by silamon — APPROVED** [review]

File: src/components/ha-selector/ha-selector-action.ts [hunk 1]
```diff
@@ -18,19 +18,22 @@ export class HaActionSelector extends LitElement {
 
   @property({ type: Boolean, reflect: true }) public disabled = false;
 
-  private _actions = memoizeOne((action: Action | undefined) => {
-    if (!action) {
-      return [];
+  // Add path here to ignore memoize if the path changes
+  private _actions = memoizeOne(
+    (action: Action | undefined, _path?: ItemPath) => {
```
Comment (bramkragten) [inline src/components/ha-selector/ha-selector-action.ts:23]: The only reason this works is because we create (the same) path on every render in the parent, this is not the proper fix

Comment (silamon) [reply src/components/ha-selector/ha-selector-action.ts:23]: I will open a revert and reopen the solution from @wendevlin since the only proper solution would probably to modify the trigger/action array reference.
