### PR TITLE
Another fix for history chart axis rounding

### LINKED ISSUE #25847: History chart rounds values ​​in Y-axis labels
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Before the last update, the history graph labels on the Y axis displayed as many decimal places as the sensor provided. After the last update, the values ​​started rounding.
One of my sensors has values ​​in the range of 3.278 - 3.281. Previously, the Y axis labels had the corresponding values ​​(3.278, 3.279, 3.280, 3.281). Now the values ​​are displayed as 3.28. Accordingly, I have now lost the ability to visually assess the changes in the sensor values ​​over time

Image

### Describe the behavior you expected

The accuracy of the values ​​in the Y-axis labels should be calculated based on the spread of the values. If the spread of the values ​​is large, the number of decimal places may be smaller. If the spread of the values ​​is small, the number of decimal places should correspond to the sensor.

### Steps to reproduce the issue

1. Have a sensor that provides >=3 decimal places accuracy and a small spread of values.
2. View it in a History Graph or the History viewer.

### What version of Home Assistant Core has the issue?

2025.6.1

### What was the last working version of Home Assistant Core?

2025.4.4

### In which browser are you experiencing the issue?

Google Chrome 137.0.7151.104 / Home Assistant mobile app

### Which operating system are you using to run this browser?

Windows 10 / Android 14

### State of relevant entities

```txt
unit_of_measurement: V
device_class: voltage
```

### Problem-relevant frontend configuration

```yaml
type: history-graph
entities:
  - entity: sensor.cell_volt_average
```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #25847
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/chart/state-history-chart-line.ts [hunk 1]
```diff
@@ -729,20 +729,17 @@ export class StateHistoryChartLine extends LitElement {
   }
 
   private _formatYAxisLabel = (value: number) => {
-    const formatOptions =
-      value >= 1 || value <= -1
```
Comment (bramkragten) [inline src/components/chart/state-history-chart-line.ts:733]: Can you explain why this is no longer needed? the comment still implies we only want to do it for tiny values?

Comment (MindFreeze) [reply src/components/chart/state-history-chart-line.ts:733]: Yes but it should be if the delta with the previous value is tiny. I think I added that check before I started tracking the delta and only had access to the current value being formatted. So it was a bad heuristic that I should've removed

Comment (MindFreeze) [reply src/components/chart/state-history-chart-line.ts:733]: Also checked with normal big numbers and setting `maximumFractionDigits` doesn't seem to affect the format for round numbers.
I guess the only effect of removing this check is in cases like #25836 it would display that number as 28.52 because we set `maximumFractionDigits` to 2+ . But that issue is fixed in another PR so we shouldn't get that case anymore

Comment (MindFreeze) [reply src/components/chart/state-history-chart-line.ts:733]: I'll change it to 1+ anyway

**Review by bramkragten — APPROVED** [review]
