### PR TITLE
Pass updated cards and badges to view element

### LINKED ISSUE #7384: Custom components not loading properly
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I just updated from 0.115.2 -> 0.116.4. After updating I noticed some custom components not loading in Lovelace. Upon further expection it seems like it's failing to find custom components:
html

The custom components will only show when resizing the screen of pressing edit.

## Expected behavior

Normally it should just load custom components without any issue

## Steps to reproduce

1. Add a custom component, took [simple-thermostat](https://github.com/nervetattoo/simple-thermostat) as example here.
2. Navigate to Lovelace
3. Add a new card with the custom component
4. Reload the page
5. Card won't show up unless pressing edit/resizing

## Environment

- Home Assistant release with the issue: 0.116.4
- Last working Home Assistant release (if known): 1.114
- Browser and browser version: Chrome 86.0.4240.75
- Operating system: Windows 10 2004

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Fixes https://github.com/home-assistant/frontend/issues/7384

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/views/hui-view.ts [hunk 1]
```diff
@@ -131,7 +131,12 @@ export class HUIView extends UpdatingElement {
       this._layoutElement!.lovelace = lovelace;
     }
 
-    if (configChanged || hassChanged || editModeChanged) {
+    if (
+      configChanged ||
+      hassChanged ||
+      editModeChanged ||
+      changedProperties.has("_cards" || changedProperties.has("_badges"))
```
Comment (maxwroc) [inline src/panels/lovelace/views/hui-view.ts]: it doesn't look right

shouldn't it be `changedProperties.has("_cards") || changedProperties.has("_badges")`

**Review by zsarnett — APPROVED** [review]
