### PR TITLE
Fix period boundaries in Energy dashboard

### LINKED ISSUE #25551: Energy dashboard 30 days display error in rendering after refresh
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

There is a fault in displaying the energy dashboard with the last 30 days option. When selecting the 30 days it is ok, but when refreshing (F5 browser) it's wrong. See image

Image

### Describe the behavior you expected

same as initial

### Steps to reproduce the issue

1. Select 30 days view
2. Refresh browser (Chrome; latest)
3.
...

### What version of Home Assistant Core has the issue?

from 2025.5.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

Google Chrome versie 136.0.7103.114 (Officiële build) (64-bits)

### Which operating system are you using to run this browser?

Windows 10

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MindFreeze**
## Proposed change

Start & end datetimes were set differently in `hui-energy-period-selector` and when loaded in `energy.ts` leading to inconsistent behaviour.

Also included a fix for DST bug I discovered when comparing arbitrary periods (ex. last 30 days) that include a DST change.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #25551
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/data/energy.ts [hunk 1]
```diff
@@ -679,7 +680,14 @@ export const getEnergyDataCollection = (
...
 
-  [collection.start, collection.end] = calcDateRange(hass, period);
+  const [start, end] = calcDateRange(hass, period);
+  const weekStartsOn = firstWeekdayIndex(hass.locale);
+  collection.start = calcDate(start, startOfDay, hass.locale, hass.config, {
+    weekStartsOn,
+  });
+  collection.end = calcDate(end, endOfDay, hass.locale, hass.config, {
+    weekStartsOn,
+  });
```
Comment (Marchat9) [inline src/data/energy.ts]: Would we also need to modify the other `calcDate` function calls to add the `{ weekStartsOn }` option, typically in the `scheduleUpdatePeriod` and the `collection.setPeriod` equalities ?

l.695-706 :
```
collection.start = calcDate(
          new Date(),
          startOfDay,
          hass.locale,
          hass.config
        );
        collection.end = calcDate(
          new Date(),
          endOfDay,
          hass.locale,
          hass.config
        );
```

And maybe

l. 727-732 :
```
if (
      collection.start.getTime() ===
        calcDate(new Date(), startOfDay, hass.locale, hass.config).getTime() &&
      collection.end?.getTime() ===
        calcDate(new Date(), endOfDay, hass.locale, hass.config).getTime()
    ) {
```

Comment (MindFreeze) [reply src/data/energy.ts]: Good catch. Actually `weekStartsOn` is not needed at all for `startOfDay`/`endOfDay` so I'll remove it

File: src/panels/lovelace/cards/energy/common/energy-chart-options.ts [hunk 2]
```diff
@@ -282,6 +284,10 @@ export function getCompareTransform(start: Date, compareStart?: Date) {
   ) {
     return (ts: Date) => addMonths(ts, compareMonthDiff);
   }
+  const compareDayDiff = differenceInDays(start, compareStart);
+  if (compareDayDiff !== 0 && start.getTime() === startOfDay(start).getTime()) {
+    return (ts: Date) => addDays(ts, compareDayDiff);
+  }
```
Comment (MindFreeze) [inline src/panels/lovelace/cards/energy/common/energy-chart-options.ts:290]: This handles comparing "last n days" when daylight savings changed during that period

**Review by bramkragten — APPROVED** [review]
