### PR TITLE
Fix height & scroll in hui-dialog-create-card

### LINKED ISSUE #25041: "Create a card" dialog: too large height after filtering
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [ ] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Open a "Create a card" dialog.
Scroll down a list of cards.
Now type "al" to search for an "Alarm card".
A height of a list is same huge, the "Alarm card" is on a top of the list (not shown):

Image

The list is large since it's height is restored here:
https://github.com/home-assistant/frontend/blob/67937537553663ce49d6fd7e7355f1eebfbefb31/src/panels/lovelace/editor/card-editor/hui-card-picker.ts#L153

### Describe the behavior you expected

A list could be large, but should be auto-scrolled to a top.

### Steps to reproduce the issue

see above

### What version of Home Assistant Core has the issue?

2025.4.1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt

```

### Problem-relevant frontend configuration

```yaml

```

### Javascript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ildar170975**
## Proposed change

Currently a list of cards has a height which is kept same after filtering (to prevent "jumping" while searching).
But it may cause this look - a list is too huge & filtered cards are not shown, you need to scroll (steps to reproduce described in https://github.com/home-assistant/frontend/issues/25041):

image

After this PR:

image

A constant height is provided by `--mdc-dialog-min/max-height` vars.

Also, had to fix `--card-picker-search-margin` variable, otherwise a negative margin causes a not needed vert. scrollbar (observed in Chrome & Edge, not observed in FF).
With this change, a tiny portion of scrolled cards may be seen through a gap between a dialog's header and a "search" field on some devices (observed on iPad). Imho not a big deal if compared to a not needed scrollbar.

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes https://github.com/home-assistant/frontend/issues/25041
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by ildar170975** [comment]
Added an automatic scrolling to top after every filtering.

**Comment by marcinbauer85** [comment]
Nice, thanks for fixing this :)

File: src/panels/lovelace/editor/card-editor/hui-card-picker.ts [hunk 1]
```diff
@@ -262,6 +251,14 @@ export class HuiCardPicker extends LitElement {
     this._loadCards();
   }
 
+  protected updated(changedProps) {
+    super.updated(changedProps);
+    const div = this.parentElement!.shadowRoot!.getElementById("content");
+    if (div) {
```
Comment (MindFreeze) [inline src/panels/lovelace/editor/card-editor/hui-card-picker.ts:257]: Better add a check here that `this._filter` changed so it doesn't trigger on irrelevant updates

**Review by MindFreeze — CHANGES_REQUESTED** [review]

File: src/panels/lovelace/editor/card-editor/hui-card-picker.ts (hunk 1 above)
Comment (ildar170975) [reply src/panels/lovelace/editor/card-editor/hui-card-picker.ts]: This case is possible:
1. Open "add card" dialog.
2. Scroll a list down.
3. Type "a" in a "search" field.
4. A list is filtered & scrolled up.
5. Again scroll down.
6. Type "a" again.
7. Now a list is NOT scrolled up.

Let's consider this as an edge case & ignore it.
Will add the proposed check.

File: src/panels/lovelace/editor/card-editor/hui-card-picker.ts [hunk 2]
```diff
@@ -262,6 +253,17 @@ export class HuiCardPicker extends LitElement {
     this._loadCards();
   }
 
+  protected updated(changedProps) {
+    super.updated(changedProps);
+    if (this._prevFilter !== this._filter) {
+      this._prevFilter = this._filter;
```
Comment (MindFreeze) [inline src/panels/lovelace/editor/card-editor/hui-card-picker.ts:259]: You should be able to this just based on `changedProps`. `changedProps.has('_filter') I think.

Comment (ildar170975) [reply src/panels/lovelace/editor/card-editor/hui-card-picker.ts]: Done

**Review by MindFreeze — APPROVED** [review]
