### PR TITLE
Fix ES5 build and fix polyfill of Intl.Locale

### LINKED ISSUE #15303: 2023.2 not working with Old Android 4.3 browsers
### Checklist

- [X] I have updated to the latest available Home Assistant version.
- [X] I have cleared the cache of my browser.
- [X] I have tried a different browser to see if it is related to my browser.

### Describe the issue you are experiencing

I have a few old Rooted Wink Relays which run Android 4.3. Using Chrome and Firefox these have shown the HA frontend fine until the 2023.2 betas. With 2023.2 they hang with the logo screen, and after clearing the browser data they hang before giving the log in screen. I suspect something was added that the old browser can't do and would like to find a work around for these devices since it is nice having a simple button screen on them.

### Describe the behavior you expected

I would expect to see the same browser screens I see in devices with newer browsers.

### Steps to reproduce the issue

1. Update to 2023.2.xxx
2. open Home assistant in Android 4.3 browser (I think they are Chrome 76 and earlier, but are the latest I could get to work with Android 4.3)
3. Screen is just HA Logo
...

### What version of Home Assistant Core has the issue?

2023.2.0bx (it seemed to appear in 0b0 and is still there in 0b9

### What was the last working version of Home Assistant Core?

2023.1.x

### In which browser are you experiencing the issue with?

Google Chrome 76.xxxx and early Firefox (Android 4.3)

### Which operating system are you using to run this browser?

Android 4.3

### State of relevant entities

_No response_

### Problem-relevant frontend configuration

_No response_

### Javascript errors shown in your browser console/inspector

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bramkragten**
## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/components/ha-form/ha-form.ts [hunk 1]
```diff
@@ -1,22 +1,33 @@
...
-import "./ha-form-grid";
-import "./ha-form-expandable";
-import "./ha-form-integer";
-import "./ha-form-multi_select";
-import "./ha-form-positive_time_period_dict";
-import "./ha-form-select";
-import "./ha-form-string";
 import { HaFormDataContainer, HaFormElement, HaFormSchema } from "./types";
 
+const LOAD_ELEMENTS = {
```
Comment (balloob) [inline src/components/ha-form/ha-form.ts:17]: is this meant to be part of this PR ?

**Review by balloob — APPROVED** [review]
