### PR TITLE
Fix-labels-yaml-helper

### LINKED ISSUE #27740: Label Assignment to (some) YAML entries has been removed
### Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.
- [x] I have tried reproducing the issue in [safe mode](https://www.home-assistant.io/blog/2023/11/01/release-202311/#restarting-into-safe-mode) to rule out problems with unsupported custom resources.

### Describe the issue you are experiencing

Odd one here - only noticed it since this beta but would like confirmation that it is not just me...
YAML based input_select always used to be editable in the UI but now this does not appear to be possible.

I clearly was able to edit this in the past as I have assigned an Area and 3 Labels - ability to assign subsequent labels has been removed - did a soft and hard reboot - still an issue.

Existing labels are greyed-out (can be removed and remain removed after hitting update)
Ability to add new labels is greyed-out and disabled

I have reported this as a front-end issue as the back-end still clearly permits label manipulation on this entity (I can add labels with Spook, just not though the UI)

Image

### Describe the behavior you expected

I expected to be able to continue to manage labels on these YAML created entities

I EXPECT that a check for uniqie_id property may be governing this, and although these do not have an explicitly assigned unique_id, they (like scripts) have an implied unique_id as in YAML they are keyed by a unique key (dictionary) under the script node

### Steps to reproduce the issue

1. Find a YAML Created input_select, input_number, input_boolean (all affected) that already has labels
2. Attempt to add new labels
3. Experience disappointment :)
...

### What version of Home Assistant Core has the issue?

2025.11.b1

### What was the last working version of Home Assistant Core?

_No response_

### In which browser are you experiencing the issue?

_No response_

### Which operating system are you using to run this browser?

_No response_

### State of relevant entities

```txt
input_select.washing_machine_cycle

Washing Machine Cycle

State: Off
Attributes:
  options: Running, Spinning, Not Emptied, Off, Idle
  editable: false
  icon: mdi:washing-machine
  friendly_name: Washing Machine Cycle
```

### Problem-relevant frontend configuration

```yaml

```

### JavaScript errors shown in your browser console/inspector

```txt

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by wendevlin**
## Proposed change
- yaml helper entity settings
  - fix labels picker to be enabled
  - show helper form but disabled
  - fixes #27740

grafik

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Review by bramkragten — DISMISSED** [review]

File: src/panels/config/entities/editor-tabs/settings/entity-settings-helper-tab.ts [hunk 1]
```diff
@@ -72,22 +72,28 @@ export class EntitySettingsHelperTab extends LitElement {
...
-                <span @value-changed=${this._valueChanged}>
-                  ${dynamicElement(`ha-${this.entry.platform}-form`, {
-                    hass: this.hass,
-                    item: this._item,
-                    entry: this.entry,
-                  })}
-                </span>
-              `}
+          : html`
+              <span @value-changed=${this._valueChanged}>
```
Comment (bramkragten) [inline src/panels/config/entities/editor-tabs/settings/entity-settings-helper-tab.ts:88]: Maybe also return in `_valueChanged` if there is no `_item`

**Review by bramkragten — APPROVED** [review]
