### PR TITLE
Fix markdown card crashing the demo

### LINKED ISSUE #5953: Add card picker appears broken on demo site
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Card picker appears to be messed up on the demo site.

image

I see spinning progress indicators on half the cards on my desktop browsers. Tried first in Chrome and then in Firefox. I can scroll the card picker dialog in Chrome but nothing else - can't type into the search field and cannot press the cancel button at the bottom of the dialog. 

My MacBook Pro's fans spin up, and eventually I get the Chrome "Page Unresponsive" prompt where I can kill the tab. 

image

iPhone is a sort of similar issue, cannot scroll it at all. After about a minute iOS seems to automatically kill the page. So that's three different browsers across desktop and mobile.

My own setup with 0.110 does not have this issue so this appears limited to demo.

## Environment

- Home Assistant release with the issue: 0.110
- Last working Home Assistant release (if known): 0.109.6
- Browser and browser version: latest Firefox and Chrome (desktop), latest Safari (iOS 13.5)
- Operating system: macOS, iOS

## State of relevant entities

```yaml

```

## Problem-relevant configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### LINKED ISSUE #5956: weather-forecast card does not respect `theme:` override when using custom icons.
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

I have created a custom weather.yaml theme and included via the configuration.yaml file, then set a custom theme in the lovelace card but the only way the lovelace card actually utilizes it is if i `frontend.set_theme` to `{"name":"weather"}`... it seems the `theme: weather` option on the lovelace config will only take the color variables into account when generating the card. The preview generator also only shows these if you add a `"` at the end of the config (until you hit save). A clue into what is happening is via the inspect element. screenshots attached. 

Config: 
image
_(i understand there are additional unused states in this image)_

image
Yields:
image

image
Yields:
image

## Expected behavior

Ability to set create a theme that only includes the custom icons for the weather, then set the theme of the card to override the icons only. 

If I set the backend theme to 'weather' then i see this (which is expected):
image

Should be able to set a theme independently of the theme override in the lovelace card config.

## Steps to reproduce

screenshots above.

## Environment

HA-Core 0.110.0

- Home Assistant release with the issue: 0.110.0
- Last working Home Assistant release (if known): new option via (https://github.com/home-assistant/frontend/pull/5736) . not available < 0.110.0
- Browser and browser version: Chrome 81
- Operating system: Win10

## State of relevant entities

n/a

## Problem-relevant configuration

```yaml
frontend:
  themes: !include_dir_merge_named themes
weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api
    mode: hourly
```

## Javascript errors shown in your browser console/inspector

n/a

### LINKED ISSUE #5959: Lovelace, view consisting of multiple picture-elements not displayed properly after 110.0
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

A view view consisting of multiple picture-elements is shown in vertical layout, one below other, instead of spread out on screen. The issue occurs in YAML and UI edit modes. "Refresh" command from Lovelace top right menu fixes the layout, however same happen on next session. 

## Expected behavior

When view consisting of multiple picture-elements is shown elements are  spread out on screen

## Steps to reproduce

 Using UI mode:
    1. Click Configure UI
    2. Add a new view
    3. Add 3 picture elements 
    4. Close UI mode
    5. Close web browser 
    6. Open web browser and connect to HA, navigate to added view to see the issue

## Environment

Home Assistant 0.110.0
Frontend version: 20200519.0 - latest

Client OSX Catalina and Chrome 81/Firefox 76

Worked well on HA 0.109

## State of relevant entities

N/A

```yaml

```

## Problem-relevant configuration

  An example configuration that caused the problem for you. Fill this out even
  if it seems unimportant to you. Please be sure to remove personal information
  like passwords, private URLs and other credentials.

```yaml
title: TEST
views:
  - badges: []
    panel: false
    title: Test
    icon: mdi:biohazard
    cards:
      - type: picture-elements
        elements:
        - type: state-badge
          entity: binary_sensor.updater
          style:
            top: 32%
            left: 40%
        image: 'https://demo.home-assistant.io/stub_config/floorplan.png'
      - type: picture-elements
        elements:
        - type: state-badge
          entity: binary_sensor.updater
          style:
            top: 32%
            left: 40%
        image: 'https://demo.home-assistant.io/stub_config/floorplan.png'
      - type: picture-elements
        elements:
        - type: state-badge
          entity: binary_sensor.updater
          style:
            top: 32%
            left: 40%
        image: 'https://demo.home-assistant.io/stub_config/floorplan.png'

```

## Javascript errors shown in your browser console/inspector

```txt

```

## Additional information

Screen Shot 2020-05-21 at 09 35 46
Screen Shot 2020-05-21 at 09 36 04
Screen Shot 2020-05-21 at 09 36 12

### PR DESCRIPTION
**Pull request by bramkragten**
## Proposed change

Fixes https://github.com/home-assistant/frontend/issues/5953

Setting the default `cardSize` to 4 for now, as that was the height of the error card that was used in 0.109.
Fixes https://github.com/home-assistant/frontend/issues/5959

Fixes https://github.com/home-assistant/frontend/issues/5956

## Type of change

- [ ] Dependency upgrade
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

File: src/panels/lovelace/cards/hui-markdown-card.ts [hunk 1]
```diff
@@ -121,24 +121,25 @@ export class HuiMarkdownCard extends LitElement implements LovelaceCard {
...
+        {
+          template: this._config.content,
+          entity_ids: this._config.entity_id,
+          variables: {
+            config: this._config,
+            user: this.hass.user!.name,
+          },
+        }
+      );
+    } catch {
```
Comment (balloob) [inline src/panels/lovelace/cards/hui-markdown-card.ts:139]: This breaks ES5 build. Optional catch binding is pretty new. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#Browser_compatibility

image

File: src/panels/lovelace/cards/hui-markdown-card.ts [hunk 2]
```diff
@@ -41,7 +41,7 @@ export class HuiMarkdownCard extends LitElement implements LovelaceCard {
 
   @property() private _content = "";
 
-  @property() private _unsubRenderTemplate?: Promise<UnsubscribeFunc>;
+  @property() private _unsubRenderTemplate?: UnsubscribeFunc;
```
Comment (balloob) [inline src/panels/lovelace/cards/hui-markdown-card.ts:44]: The reason we stored it as a template was that we would guarantee to clean it up if the element was thrown away before the subscription would resolve to an unsubscribe function.
