### PR TITLE
Fix excessive rerendering of history charts

### LINKED ISSUE #8274: Chart tooltips hidden immediately
## Checklist

- [x] I have updated to the latest available Home Assistant version.
- [x] I have cleared the cache of my browser.
- [x] I have tried a different browser to see if it is related to my browser.

## The problem

Tooltips of charts in modals will be hidden almost immediately on at least Android

## Environment

- Home Assistant release with the issue: latest beta
- Last working Home Assistant release (if known):
- Browser and browser version:
- Operating system:

## State of relevant entities

```yaml

```

## Problem-relevant frontend configuration

```yaml

```

## Javascript errors shown in your browser console/inspector

```txt

```

### PR DESCRIPTION
**Pull request by larena1**
## Proposed change

Closes https://github.com/home-assistant/frontend/issues/8274

When @spacegaier reimplemented the history chart as LitElement, that unfortunately broke their tooltips because the chart would rerender on every change of the hass object. In my case that was every 500 ms and I'm not able to read that fast.

This PR implements shouldUpdate so the chart only rerenders when there was either a change to its own entity or the underlying history data.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Example configuration

```yaml

```

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue or discussion:
- Link to documentation pull request:

## Checklist

- [ ] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [ ] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

[docs-repository]: https://github.com/home-assistant/home-assistant.io

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @larena1, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;frontend#8340).

Once you do that we will be able to review and accept this pull request.

Thanks!

File: src/components/state-history-charts.ts [hunk 1]
```diff
@@ -83,6 +85,13 @@ class StateHistoryCharts extends LitElement {
     `;
   }
 
+  protected shouldUpdate(changedProps: PropertyValues): boolean {
+    return (
+      hasConfigOrEntityChanged(this, changedProps) ||
```
Comment (bramkragten) [inline src/components/state-history-charts.ts:90]: This one is for lovelace cards, and should not be used here. 

You should add `isLoadingData`.

Comment (larena1) [reply src/components/state-history-charts.ts:90]: Do you mean only isLoadingData or also historyData

Comment (bramkragten) [reply src/components/state-history-charts.ts:90]: both

Comment (larena1) [reply src/components/state-history-charts.ts]: Done and CI passed

File: src/components/state-history-charts.ts [hunk 2]
```diff
@@ -83,6 +84,13 @@ class StateHistoryCharts extends LitElement {
     `;
   }
 
+  protected shouldUpdate(changedProps: PropertyValues): boolean {
+    return (
+      changedProps.has("isLoadingData") ||
+      changedProps.has("historyData")
+    );
```
Comment (bramkragten) [inline src/components/state-history-charts.ts:91]:
```suggestion
    return !(changedProps.size === 1 &&changedProps.has("hass"));
```

**Review by bramkragten — APPROVED** [review]
