### PR TITLE
Update lokalise cli to version 2 + fix replacing localise vars

### LINKED ISSUE #4181: Binary sensor value is [%key_id:state::default::on%]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Home Assistant release with the issue:**

Home Assistant 0.101.2

**Last working Home Assistant release (if known):**

Home Assistant 0.99

**Browser and Operating System:**

I replicated the issue with
* Chrome on MAC
* Chrome on PC
* Internet explorer on PC
* FireFox on PC
* Chrome on Android

**Description of problem:**

For binary sensor set to "on" without any device class, the display value on the entities card is now _[%key_id:state::default::on%]_

The issue seems to be present only for sensors set to "on", sensors set to "off" are display as"off" as usual

It is **only a display issue**, the sensor is set to "on" in the developer tools and all my automations are still working.

See screenshots below for a detailed view of the issue.

**Additional information:**

*The entities card with the faulty "on" value for my binary sensor:*
entities_card

*The sensor view:*
sensor_view

*The developer tool, showing the correct "on" value:*
dev_tools

NOTE : First time opening an issue on home assistant, I remain available if you need more details
NOTE : Issue experienced by other people : [here](https://community.home-assistant.io/t/sensor-displaying-key-id-off-instead-of-simply-off/145927)

### PR DESCRIPTION
**Pull request by bramkragten**
Fixes https://github.com/home-assistant/home-assistant-polymer/issues/4181

### CODE REVIEW

File: build-scripts/gulp/translations.js [hunk 1]
```diff
@@ -99,18 +98,16 @@ function recursiveEmpty(data) {
  * @link https://docs.lokalise.co/article/KO5SZWLLsy-key-referencing
  */
 const re_key_reference = /\[%key:([^%]+)%\]/;
-function lokalise_transform(data, original) {
+function lokaliseTransform(data, original, file) {
```
Comment (balloob) [inline build-scripts/gulp/translations.js]: We so much need to re-do this file in a non-stream way so we can actually see what's going on .

**Comment by antro31** [comment]
Hi! I migrated this morning to 0.102.0. Issue is still there. What happened?

**Comment by bramkragten** [comment]
That's not easy to say when there is so little information.

But if you think there (still) is a bug, please create an issue with information instead of responding on a PR.
